set identity_insert SCFS_ERP.DBO.CATEGORYMASTER on  
insert into scfs_erp.dbo.CATEGORYMASTER 
(CATEID, CATETID, CATENAME, CATEDNAME, CATEADDR, CATEPHNID, CATEPHN1, CATEPHN2, CATEPHN3, CATEPHN4, CATEMAIL, CATECPRSN, CATECODE, ACHEADID, TARIFFMID, CATEBTYPE, 
CATEMAIL2, CATEMAIL3, CATEMAIL4, CATEMAIL5, CATEMAIL6, CATEMAIL7, CATEMAIL8, CATEMAIL9, CATEMAIL10, CATETDSEXPRN, CATELICNO, CATEFNOD, CATEBNAME, CATEBADDR, CATEBSTATENAME, 
CATEBRNCHCODE, CATEBACCTYPE, CATEBACCTNO, CATEBPANNO, CATEBNEFTCODE, CATEBRTGSCODE, CATETDSCODE, CATETDSRATE, CATEBFROM, CATEBTO, CATEBVATNO, CATEBCSTNO, CATEBCARGO ,
CATEBSTAXNO, CATESTRCALCTYPE, CATEBTANNO, STATEID, HSNID, CATEBGSTNO, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, CATEBILLTYPE
)
select CATEID, CATETID, CATENAME, CATEDNAME, CATEADDR, CATEPHNID, CATEPHN1, CATEPHN2, CATEPHN3, CATEPHN4, CATEMAIL, CATECPRSN, CATECODE, ACHEADID, TARIFFMID, CATEBTYPE, 
CATEMAIL2, CATEMAIL3, CATEMAIL4, CATEMAIL5, CATEMAIL6, CATEMAIL7, CATEMAIL8, CATEMAIL9, CATEMAIL10, CATETDSEXPRN, CATELICNO, CATEFNOD, CATEBNAME, CATEBADDR, CATEBSTATENAME, 
CATEBRNCHCODE, CATEBACCTYPE, CATEBACCTNO, CATEBPANNO, CATEBNEFTCODE, CATEBRTGSCODE, CATETDSCODE, CATETDSRATE, CATEBFROM, CATEBTO, CATEBVATNO, CATEBCSTNO, CATEBCARGO ,
CATEBSTAXNO, CATESTRCALCTYPE, CATEBTANNO, STATEID, HSNID, CATEBGSTNO, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, 1
from scfs.dbo.CATEGORYMASTER where cateid not in(select cateid from SCFS_ERP.dbo.CATEGORYMASTER)
set identity_insert SCFS_ERP.DBO.CATEGORYMASTER off

set identity_insert SCFS_ERP.DBO.CATEGORY_ADDRESS_DETAIL on  
insert into scfs_erp.dbo.CATEGORY_ADDRESS_DETAIL 
(CATEAID, CATEID, STATEID, CATEAGSTNO, CATEAADDR1, CATEAADDR2, CATEAADDR3, CATEAADDR4, CATEATYPEDESC, CATEAPANNO)
select CATEAID, CATEID, STATEID, CATEAGSTNO, CATEAADDR1, CATEAADDR2, CATEAADDR3, CATEAADDR4, CATEATYPEDESC, ''
from scfs.dbo.CATEGORY_ADDRESS_DETAIL where cateaid not in(select cateaid from SCFS_ERP.dbo.CATEGORY_ADDRESS_DETAIL)
set identity_insert SCFS_ERP.DBO.CATEGORY_ADDRESS_DETAIL off

select count('*') from scfs.dbo.CATEGORYMASTER 
select count('*') from SCFS_ERP.dbo.CATEGORYMASTER

select count('*') from scfs.dbo.CATEGORY_ADDRESS_DETAIL
select count('*') from SCFS_ERP.dbo.CATEGORY_ADDRESS_DETAIL