SELECT DISTINCT VSLDESC fROM SCFS_ERP.DBO.VESSELMASTER
SELECT DISTINCT VSLDESC fROM SCFS.DBO.VESSELMASTER

SELECT * FROM SCFS.DBO.VESSELMASTER A(NOLOCK)
LEFT JOIN SCFS_ERP.DBO.VESSELMASTER B(NOLOCK) ON A.VSLDESC = B.VSLDESC
--SELECT * INTO VESSELMASTER_BKUP300921 FROM SCFS_ERP.DBO.VESSELMASTER
--DELETE SCFS_ERP.DBO.VESSELMASTER

SET IDENTITY_INSERT SCFS_ERP.DBO.VESSELMASTER ON

INSERT INTO SCFS_ERP.DBO.VESSELMASTER(VSLID, VSLDESC, VSLCODE, CUSRID, LMUSRID,DISPSTATUS, PRCSDATE)
SELECT VSLID, VSLDESC, VSLCODE, CUSRID, LMUSRID,DISPSTATUS, GETDATE()
FROM SCFS.DBO.VESSELMASTER (NOLOCK)

SET IDENTITY_INSERT SCFS_ERP.DBO.VESSELMASTER OFF
