USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_CARGO_OUT_CONTAINER_CBX_ASSGN]    Script Date: 06/11/2021 11:56:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create VIEW [dbo].[VW_CARGO_OUT_CONTAINER_CBX_ASSGN]
AS
SELECT     dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.GPREFNO + ' - ' + dbo.GATEINDETAIL.CONTNRNO AS CONTNRNO
FROM         dbo.GATEINDETAIL LEFT OUTER JOIN
                      dbo.VW_CARGO_OUT_CONTAINER_CBX_ASSGN_01 ON 
                      dbo.GATEINDETAIL.GIDID = dbo.VW_CARGO_OUT_CONTAINER_CBX_ASSGN_01.GIDID
WHERE     (dbo.GATEINDETAIL.SDPTID = 4) AND (dbo.GATEINDETAIL.GPWGHT - ISNULL(dbo.VW_CARGO_OUT_CONTAINER_CBX_ASSGN_01.GOQTY, 0) > 0)



GO


