USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_CARGO_OUT_CONTAINER_CBX_ASSGN_01]    Script Date: 06/11/2021 11:57:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

create VIEW [dbo].[VW_CARGO_OUT_CONTAINER_CBX_ASSGN_01]
AS
SELECT     GIDID, SUM(GOQTY) AS GOQTY
FROM         dbo.GATEOUTDETAIL
WHERE     (SDPTID = 4)
GROUP BY GIDID



GO


