
ALTER VIEW [dbo].[VW_CARGOOUT_CONTAINER_GATEOUTDETAILS_ASSGN]
AS
SELECT   Isnull(CONTAINERSIZEMASTER.CONTNRSDESC,'') as CONTNRSDESC, dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO AS CONTNRNO,
          GATEOUTDETAIL.GODID,  
           VEHICLETICKETDETAIL.CGIDID, GATEINDETAIL.GIDNO, GATEINDETAIL.GIDATE, VEHICLETICKETDETAIL.VTDATE, GATEINDETAIL.IMPRTNAME, 
		   GATEINDETAIL.STMRNAME,GATEINDETAIL.GPLNO,VEHICLETICKETDETAIL.VHLNO ,isnull(PRODUCTGROUPMASTER.PRDTGDESC,'') as PRDTGDESC,
		   isnull(GATEINDETAIL.PRDTDESC,'') as PRDTDESC,
		   GATEINDETAIL.GPWGHT ,(GATEINDETAIL.GPWGHT - ISNUll(GATEOUTDETAIL.GOQTY,0)) AS BGOQTY,ISNUll(GATEOUTDETAIL.GOQTY,0) as GOQTY
           


FROM       dbo.GATEINDETAIL  (NOLOCK)  INNER JOIN 
           dbo.VEHICLETICKETDETAIL  (NOLOCK) ON GATEINDETAIL.GIDID = VEHICLETICKETDETAIL.CGIDID INNER JOIN 
		   dbo.CONTAINERSIZEMASTER (NOLOCK) ON GATEINDETAIL.CONTNRSID = CONTAINERSIZEMASTER.CONTNRSID Inner Join 
		   dbo.PRODUCTGROUPMASTER  (NOLOCK) ON GATEINDETAIL.PRDTGID = PRODUCTGROUPMASTER.PRDTGID  Inner JOIN 
		   dbo.GATEOUTDETAIL (NOLOCk) ON   GATEINDETAIL.GIDID = GATEOUTDETAIL.GIDID 
WHERE     (dbo.GATEINDETAIL.SDPTID = 4) and (GATEOUTDETAIL.SDPTID = 4 )





