
ALTER VIEW [dbo].[VW_IMPORT_CONTAINER_DETAIL_QUERY_ASSGN]
AS
SELECT     dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.GITIME, dbo.GATEINDETAIL.GIDATE, dbo.GATEINDETAIL.GIDNO, dbo.GATEINDETAIL.VHLNO, 
                      dbo.GATEINDETAIL.DRVNAME, dbo.GATEINDETAIL.IMPRTNAME, dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.CONTNRNO, 
                      dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.CONTAINERTYPEMASTER.CONTNRTDESC, dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, 
                      dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.GPETYPE, dbo.GATEINDETAIL.GPWTYPE, 
                      dbo.GATEINDETAIL.GPSTYPE, dbo.GATEINDETAIL.GIREMKRS, dbo.GATEINDETAIL.GPWGHT, dbo.GATEINDETAIL.GIDMGDESC, 
                      case when  (isnull(dbo.VW_GATEIN_BLOCK_DETAILS_01.GBDID,0) = 0 OR isnull(dbo.VW_GATEIN_BLOCK_DETAILS_01.GBSTYPE,0) = 1 ) then 0  else 1 end  AS GBDID, dbo.BILLENTRYMASTER.BILLEMDNO, dbo.BILLENTRYMASTER.BILLEMDATE, 
					  isnull(dbo.VW_GATEIN_BLOCK_DETAILS_01.BLOCKEDDATE,'') as BLOCKEDDATE,isnull(dbo.VW_GATEIN_BLOCK_DETAILS_01.UNBLOCKEDDATE,'') as UNBLOCKEDDATE,
                      dbo.BILLENTRYMASTER.BLNO, dbo.GATEOUTDETAIL.GODATE, dbo.GATEOUTDETAIL.GOTIME,isnull(dbo.BILLENTRYDETAIL.BILLEDID,0) as BILLEDID,ROWMASTER.ROWDESC,SLOTDESC
FROM         dbo.GATEOUTDETAIL (NOLOCK)  RIGHT OUTER JOIN
                      dbo.GATEINDETAIL (NOLOCK)  INNER JOIN
					 
                      dbo.CONTAINERSIZEMASTER (NOLOCK) ON  dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                      dbo.CONTAINERTYPEMASTER (NOLOCK) ON  dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID ON 
                      dbo.GATEOUTDETAIL.GIDID = dbo.GATEINDETAIL.GIDID LEFT OUTER JOIN
                      dbo.BILLENTRYMASTER RIGHT OUTER JOIN
                      dbo.BILLENTRYDETAIL (NOLOCK) ON  dbo.BILLENTRYMASTER.BILLEMID = dbo.BILLENTRYDETAIL.BILLEMID  ON  
                      dbo.GATEINDETAIL.GIDID = dbo.BILLENTRYDETAIL.GIDID LEFT OUTER JOIN
                      dbo.VW_GATEIN_BLOCK_DETAILS_01 (NOLOCK) ON  dbo.GATEINDETAIL.GIDID = dbo.VW_GATEIN_BLOCK_DETAILS_01.GIDID LEFT OUTER JOIN
					   dbo.ROWMASTER (NOLOCK) ON  GATEINDETAIL.ROWID=ROWMASTER.ROWID LEFT OUTER JOIN
					  dbo.SLOTMASTER (NOLOCK) ON  GATEINDETAIL.SLOTID=SLOTMASTER.SLOTID 
					  



