ALTER VIEW dbo.VW_IMPORT_GATEOUT_TRUCKNO_CBX_ASSGN
AS
SELECT     TOP 100 PERCENT dbo.GATEINDETAIL.GIDID,dbo.GATEINDETAIL.AVHLNO, dbo.GATEINDETAIL.DRVNAME, dbo.GATEINDETAIL.CHAID,
			CHANAME, GIDATE
FROM         dbo.GATEINDETAIL LEFT OUTER JOIN
                      dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID
WHERE     (dbo.GATEINDETAIL.SDPTID = 1) AND (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) 
and dbo.GATEINDETAIL.AVHLNO is not null and GATEINDETAIL.CNTNRSID=0 and GATEINDETAIL.CONTNRTID=0

ORDER BY dbo.GATEINDETAIL.GIDID


select *from GATEINDETAIL where GIDID in (60508,60512)