
CREATE VIEW [dbo].[z_din_25092021]
AS
SELECT        TOP (100) PERCENT dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.GIDATE, dbo.GATEINDETAIL.GITIME, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.CONTNRSID,
                         dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.IMPRTNAME, dbo.GATEINDETAIL.IMPRTID, dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO,
                         dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.GIREMKRS, dbo.GATEINDETAIL.STMRID, dbo.OPENSHEETMASTER.BOENO, dbo.OPENSHEETMASTER.BOEDATE, dbo.GATEINDETAIL.SLOTID, dbo.SLOTMASTER.ROWID,
                         dbo.SLOTMASTER.SLOTDESC, dbo.SLOTMASTER.SLOTCODE, dbo.ROWMASTER.ROWDESC, dbo.ROWMASTER.ROWCODE, dbo.GATEINDETAIL.GSEALTYPE, dbo.GATEINDETAIL.GSECTYPE, dbo.GATEINDETAIL.GSEALREMKRS,
                         dbo.GATEINDETAIL.GSECREMKRS, dbo.GATEINDETAIL.GPPTYPE, dbo.OPENSHEETMASTER.OSMNAME, dbo.OPENSHEETMASTER.OSMLNAME, dbo.GPMODEMASTER.GPMODEDESC, dbo.GATEINDETAIL.IGMDATE,
                         dbo.GATEINDETAIL.BLNO
FROM            dbo.SLOTMASTER INNER JOIN
                         dbo.GATEINDETAIL INNER JOIN
                         dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID ON dbo.SLOTMASTER.SLOTID = dbo.GATEINDETAIL.SLOTID INNER JOIN
                         dbo.ROWMASTER ON dbo.SLOTMASTER.ROWID = dbo.ROWMASTER.ROWID LEFT OUTER JOIN
                         dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID LEFT OUTER JOIN
                         dbo.GPMODEMASTER ON dbo.GATEINDETAIL.GPMODEID = dbo.GPMODEMASTER.GPMODEID LEFT OUTER JOIN
                         dbo.OPENSHEETMASTER RIGHT OUTER JOIN
                         dbo.OPENSHEETDETAIL ON dbo.OPENSHEETMASTER.OSMID = dbo.OPENSHEETDETAIL.OSMID ON dbo.GATEINDETAIL.GIDID = dbo.OPENSHEETDETAIL.GIDID
WHERE        (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) AND (dbo.GATEINDETAIL.SDPTID = 1)
ORDER BY dbo.GATEINDETAIL.STMRID, dbo.GATEINDETAIL.GIDATE, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.VOYNO, dbo.GATEINDETAIL.CONTNRNO

