USE SCFS
GO
ALTER VIEW DBO.Z_IMP_RGIN_VIEW
AS 
select DISTINCT REMOTEGATEINDETAIL.GIDID
from REMOTEGATEINDETAIL left join GATEINDETAIL on REMOTEGATEINDETAIL.gidid = GATEINDETAIL.RGIDID
where SCFS.DBO.GATEINDETAIL.RGIDID is null
UNION
select DISTINCT RGIDID
from SCFS_ERP..GATEINDETAIL where OLDGID > 0 and isnull(RGIDID,0) > 0

alter table REMOTEGATEINDETAIL
add OLDGID INT NULL DEFAULT 0




CREATE PROCEDURE [dbo].[Z_IMPORT_REMOTEGATEIN_DETAIL_Auto_Generate_XML]
AS
BEGIN
	SET NOCOUNT ON
	
      DECLARE @Counter INT
      SET @Counter = 1
      
	  DELETE [SCFS_ERP].dbo.REMOTEGATEINDETAIL WHERE OLDGID > 0 AND SDPTID = 1

	  Declare @GIDID int

      --DECLARE THE CURSOR FOR A QUERY.
      DECLARE RGIDetail CURSOR READ_ONLY
      FOR
	  
	  Select DISTINCT GIDID 
	  From [SCFS].dbo.Z_IMP_RGIN_VIEW (nolock) 
	  Group by GIDID
	  Order by GIDID
  
      --OPEN CURSOR.
      OPEN RGIDetail
 
      --FETCH THE RECORD INTO THE VARIABLES.
      FETCH NEXT FROM RGIDetail INTO @GIDID
 
      --LOOP UNTIL RECORDS ARE AVAILABLE.
      WHILE @@FETCH_STATUS = 0
      BEGIN

			EXEC Z_IMPORT_REMOTEGATEIN_DETAIL_INSERT_XML @GIDID
             --INCREMENT COUNTER.
			 
             SET @Counter = @Counter + 1
             
             --FETCH THE NEXT RECORD INTO THE VARIABLES.
             FETCH NEXT FROM RGIDetail INTO @GIDID
      END
 
      --CLGIE THE CURSOR.
      CLOSE RGIDetail
      DEALLOCATE RGIDetail


END


--RGI DEtail Insert
USE [SCFS_ERP]
GO
/****** Object:  StoredProcedure [dbo].[Z_IMPORT_REMOTEGATEIN_DETAIL_INSERT_XML]    Script Date: 20/09/2021 19:37:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[Z_IMPORT_REMOTEGATEIN_DETAIL_INSERT_XML] 
@PGIDID INT
AS
BEGIN
	  SET NOCOUNT ON
	
	  Declare @ccount int, @boecount int

	  Set @ccount = 1
	  Set @boecount = 0

	  If @ccount > 0 

  			INSERT INTO [SCFS_ERP].dbo.REMOTEGATEINDETAIL
			(COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, CONTNRID, CONTNRSID, CONTNRNO, 
			 VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, IGMNO, GPLNO, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, GIISOCODE, GPNWGHT, GPGWGHT , GPCBM, GPLENGTH, 
			 GPWIDTH, GPHEIGHT, GPBLNO, GPEAMT, GPAAMT, GPPTYPE,  WMDID, IGMDATE, BLNO, GPMODEID, OLDGID)
			Select COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, CONTNRID, CONTNRSID, CONTNRNO, 
			 VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, IGMNO, GPLNO, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, GIISOCODE, GPNWGHT, GPGWGHT , GPCBM, GPLENGTH, 
			 GPWIDTH, GPHEIGHT, GPBLNO, GPEAMT, GPAAMT, GPPTYPE,  WMDID, IGMDATE, BLNO, GPMODEID, REMOTEGATEINDETAIL.GIDID
			From [SCFS].dbo.REMOTEGATEINDETAIL (NOLOCK) 
			--INNER JOIN [SCFS].dbo.z_din_18092021 (NOLOCK) ON [SCFS].dbo.GATEINDETAIL.GIDID = [SCFS].dbo.z_din_18092021.GIDID
			where [SCFS].dbo.REMOTEGATEINDETAIL.GIDID = @PGIDID

	update [SCFS_ERP].dbo.REMOTEGATEINDETAIL
	set CONTNRID = 1
	where GIDID = @PGIDID
	and CONTNRID = 0
END

DELETE [SCFS_ERP].dbo.REMOTEGATEINDETAIL WHERE SDPTID = 1

-- RGI
EXEC [Z_IMPORT_REMOTEGATEIN_DETAIL_Auto_Generate_XML]
GO

	update a
	SET IGMDATE = GIDATE
	from SCFS_ERP.DBO.REMOTEGATEINDETAIL a
	WHERE A.OLDGID > 0
	and IGMDATE is null

	update C
	SET RGIDID = A.GIDID
	from SCFS_ERP.DBO.REMOTEGATEINDETAIL a, SCFS_ERP.DBO.GATEINDETAIL C(NOLOCK) 
	WHERE A.OLDGID > 0 
	AND A.OLDGID = C.RGIDID

	update B
	SET CONTNRID = 1
	from SCFS_ERP.DBO.REMOTEGATEINDETAIL B
	WHERE OLDGID > 0 
	and CONTNRID = 0