use SCFS_ERP
go
 
--DELETE [SCFS_ERP].dbo.GATEINDETAIL WHERE SDPTID = 1
--DELETE [SCFS_ERP].dbo.REMOTEGATEINDETAIL WHERE SDPTID = 1
--DELETE [SCFS_ERP].dbo.OPENSHEETMASTER WHERE SDPTID = 1
--DELETE [SCFS_ERP].dbo.BILLENTRYMASTER WHERE SDPTID = 1
--DELETE [SCFS_ERP].dbo.DELIVERYORDERMASTER WHERE SDPTID = 1
--DELETE [SCFS_ERP].dbo.AUTHORIZATIONSLIPMASTER WHERE SDPTID = 1
--DELETE [SCFS_ERP].dbo.VEHICLETICKETDETAIL WHERE SDPTID = 1
--DELETE [SCFS_ERP].dbo.GATEOUTDETAIL WHERE SDPTID = 1
--DELETE [SCFS_ERP].dbo.TRANSACTIONMASTER WHERE SDPTID = 1
--DELETE [SCFS_ERP].dbo.PERFORMA_TRANSACTIONMASTER WHERE SDPTID = 1
--DELETE [SCFS_ERP].dbo.CREDITNOTE_TRANSACTIONMASTER WHERE SDPTID = 1


--GateInDetail Insert Assgn
--DELETE [SCFS_ERP].dbo.GATEINDETAIL WHERE OLDGID > 0
--INSERT INTO [SCFS_ERP].dbo.GATEINDETAIL
--(COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GIVHLTYPE, TRNSPRTID, TRNSPRTNAME, VHLNO, DRVNAME, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, 
--                         CONTNRID, CONTNRSID, CONTNRNO, LPSEALNO, CSEALNO, YRDID, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, IGMNO, GPLNO, GPWTYPE, GPSTYPE, GPETYPE, BOEDID, INVDID, RGIDID, 
--                         GIREMKRS, SLOTID, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, GPEAMT, CHAID, CHANAME, AVHLNO, GPNOP, PRDTTID, GIISOCODE, GIDMGDESC, NGIDID, GPNWGHT, GPGWGHT, GPCBM, GPLENGTH, GPWIDTH, 
--                         GPHEIGHT, GPBLNO, GPAAMT, CLNTID, CLNTNAME, SHPRNAME, GPPLCNAME, GPTWGHT, CONTNRFID, CONDTNID, GRADEID, CNTNRSID, GPPTYPE, GFCLTYPE, GSEALTYPE, GSECTYPE, GSEALREMKRS, GSECREMKRS, 
--                         GPNRNO, ESBNO, EVSLRNO, EMONO, EEGMNO, ESBDATE, GPSCNTYPE, IGMDATE, BLNO, GPMODEID, OLDGID)
--Select COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GIVHLTYPE, TRNSPRTID, TRNSPRTNAME, VHLNO, 
--DRVNAME, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, CONTNRID, CONTNRSID, 
--[SCFS].dbo.GATEINDETAIL.CONTNRNO, LPSEALNO, CSEALNO, YRDID, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, 
--[SCFS].dbo.GATEINDETAIL.IGMNO, [SCFS].dbo.GATEINDETAIL.GPLNO, GPWTYPE, GPSTYPE, GPETYPE, BOEDID, INVDID, RGIDID, 
--GIREMKRS, SLOTID, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, GPEAMT, CHAID, CHANAME, AVHLNO, GPNOP, PRDTTID, GIISOCODE, 
--GIDMGDESC, NGIDID, GPNWGHT, GPGWGHT, GPCBM, GPLENGTH, GPWIDTH, GPHEIGHT, GPBLNO, GPAAMT, CLNTID, CLNTNAME, SHPRNAME, 
--GPPLCNAME, GPTWGHT, CONTNRFID, CONDTNID, GRADEID, CNTNRSID, GPPTYPE, GFCLTYPE, GSEALTYPE, GSECTYPE, GSEALREMKRS, 
--GSECREMKRS, GPNRNO, ESBNO, EVSLRNO, EMONO, EEGMNO, ESBDATE, GPSCNTYPE, IGMDATE, BLNO, GPMODEID, GATEINDETAIL.GIDID
--From [SCFS].dbo.GATEINDETAIL (NOLOCK) INNER JOIN
--       [SCFS].dbo.z_din_18092021 (NOLOCK) ON [SCFS].dbo.GATEINDETAIL.GIDID = [SCFS].dbo.z_din_18092021.GIDID
--GO

-- GI
EXEC [Z_IMPORT_GATEIN_DETAIL_Auto_Generate_XML]
GO

	update B
	SET ROWID = C.ROWID
	from SCFS_ERP.DBO.GATEINDETAIL B, SLOTMASTER C(NOLOCK)
	WHERE OLDGID > 0 
	AND B.SLOTID = C.SLOTID
	and SDPTID = 1

	update B
	SET CONTNRID = 1
	from SCFS_ERP.DBO.GATEINDETAIL B
	WHERE OLDGID > 0
	and CONTNRID = 0
	and SDPTID = 1


	/*
	USE SCFS
	GO
	create table Z_IMP_RGIN
(GIDID INT NULL DEFAULT 0)

DELETE SCFS.DBO.Z_IMP_RGIN
INSERT INTO Z_IMP_RGIN
select DISTINCT REMOTEGATEINDETAIL.GIDID
from REMOTEGATEINDETAIL left join GATEINDETAIL on REMOTEGATEINDETAIL.gidid = GATEINDETAIL.RGIDID
where SCFS.DBO.GATEINDETAIL.RGIDID is null
UNION
select DISTINCT RGIDID
from SCFS_ERP..GATEINDETAIL where OLDGID > 0 and isnull(RGIDID,0) > 0*/
-- RGI
EXEC [Z_IMPORT_REMOTEGATEIN_DETAIL_Auto_Generate_XML]
GO

	update C
	SET RGIDID = A.GIDID
	from SCFS_ERP.DBO.REMOTEGATEINDETAIL a, SCFS_ERP.DBO.GATEINDETAIL C(NOLOCK) 
	WHERE A.OLDGID > 0 
	AND A.OLDGID = C.RGIDID
	and C.SDPTID = 1

	update B
	SET CONTNRID = 1
	from SCFS_ERP.DBO.REMOTEGATEINDETAIL B
	WHERE OLDGID > 0 
	and CONTNRID = 0

	update a
	SET IGMDATE = GIDATE
	from SCFS_ERP.DBO.REMOTEGATEINDETAIL a
	WHERE A.OLDGID > 0
	and IGMDATE is null

-- OS 
EXEC [Z_IMPORT_OPNSHEET_DETAIL_Auto_Generate_XML]
GO


	update a
	SET GIDID = B.GIDID
	from [SCFS_ERP].dbo.OPENSHEETDETAIL a, SCFS_ERP.DBO.GATEINDETAIL B(NOLOCK)
	WHERE A.GIDID = B.OLDGID
	and a.oldosdid > 0 

	update a
	SET GIDID = B.GIDID
	from [SCFS_ERP].dbo.BILLENTRYDETAIL a, SCFS_ERP.DBO.GATEINDETAIL B(NOLOCK)
	WHERE A.GIDID = B.OLDGID
	and a.oldbilledid > 0 

	update a
	SET IGMDATE = B.IGMDATE
	from [SCFS_ERP].dbo.GATEINDETAIL a, SCFS.DBO.GATEINDETAIL B(NOLOCK)
	WHERE A.OLDGID = B.GIDID

	update a
	SET OSMIGMDATE = B.IGMDATE
	from [SCFS_ERP].dbo.OPENSHEETMASTER a, SCFS_ERP.DBO.GATEINDETAIL B(NOLOCK), [SCFS_ERP].dbo.OPENSHEETDETAIL c
	WHERE c.GIDID = B.GIDID
	and c.OSMID = a.OSMID
	and c.oldosdid >0

--Update CHA Adress Detaila
UPDATE OPENSHEETMASTER SET OSBCHACATEAID = CATEAID, OSBCHACATEAGSTNO = CATEAGSTNO,
OSBCHAADDR1 = CATEAADDR1, OSBCHAADDR2 = CATEAADDR2, OSBCHAADDR3 = CATEAADDR3, OSBCHAADDR4 = CATEAADDR4,
OSBCHASTATEID  = CATEGORY_ADDRESS_DETAIL.STATEID
FROM SCFS_ERP.DBO.OPENSHEETMASTER INNER JOIN
				   SCFS_ERP.dbo.CATEGORY_ADDRESS_DETAIL ON dbo.OPENSHEETMASTER.CHAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID

--Update Billing CHA Adress Detaila
UPDATE OPENSHEETMASTER SET OSBCHACATEAID = CATEAID, OSBBCHACATEAGSTNO = CATEAGSTNO,
OSBBCHAADDR1 = CATEAADDR1, OSBBCHAADDR2 = CATEAADDR2, OSBBCHAADDR3 = CATEAADDR3, OSBBCHAADDR4 = CATEAADDR4,
OSBBCHASTATEID  = CATEGORY_ADDRESS_DETAIL.STATEID
FROM OPENSHEETMASTER INNER JOIN
				   dbo.CATEGORY_ADDRESS_DETAIL ON dbo.OPENSHEETMASTER.OSBILLREFID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID

GO


--Open Sheet BillEDID Update

update OPENSHEETDETAIL Set OPENSHEETDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID
FROM            dbo.OPENSHEETDETAIL INNER JOIN
                         dbo.BILLENTRYDETAIL ON dbo.OPENSHEETDETAIL.GIDID = dbo.BILLENTRYDETAIL.GIDID

GO

-- ASL

EXEC [Z_IMPORT_ASL_DETAIL_Auto_Generate_XML]
GO

update a
SET GIDID = B.GIDID
from [SCFS_ERP].dbo.AUTHORIZATIONSLIPDETAIL a, SCFS_ERP.DBO.GATEINDETAIL B(NOLOCK)
WHERE A.GIDID = B.OLDGID
AND A.OLDASLDID > 0
and SDPTID = 1 

update a
SET  OSDID = B.OSDID
from [SCFS_ERP].dbo.AUTHORIZATIONSLIPDETAIL a,  SCFS_ERP.DBO.OPENSHEETDETAIL b(NOLOCK)
WHERE A.GIDID = B.GIDID
AND A.OLDASLDID > 0 

update C
SET ASLMNO = C.ASLMID, ASLMDNO = C.ASLMID
from [SCFS_ERP].dbo.AUTHORIZATIONSLIPDETAIL a, [SCFS_ERP].dbo.AUTHORIZATIONSLIPMASTER C
WHERE  A.ASLMID = C.ASLMID
AND A.OLDASLDID > 0 
and SDPTID = 1

GO

-- VT
EXEC [Z_IMPORT_VT_DETAIL_Auto_Generate_XML]
GO


--update a
--SET GIDID = C.GIDID
--from [SCFS_ERP].dbo.VEHICLETICKETDETAIL a, [SCFS_ERP].dbo.AUTHORIZATIONSLIPDETAIL B(NOLOCK),
-- [SCFS].dbo.OPENSHEETDETAIL C(NOLOCK)
--WHERE A.ASLDID = B.OLDASLDID
--AND B.OSDID = C.OLDOSDID
--AND A.OLDVTDID > 0 

update a
SET GIDID = B.GIDID
from [SCFS_ERP].dbo.VEHICLETICKETDETAIL a, SCFS_ERP.DBO.GATEINDETAIL B(NOLOCK)
WHERE A.GIDID = B.OLDGID
and a.SDPTID = b.SDPTID
AND A.OLDVTDID > 0 
and a.SDPTID = 1

update a
SET VTNO = VTDID, VTDNO = VTDID
from [SCFS_ERP].dbo.VEHICLETICKETDETAIL a
WHERE A.OLDVTDID > 0 
and a.SDPTID = 1

update a
SET ASLDID = C.ASLDID
from [SCFS_ERP].dbo.VEHICLETICKETDETAIL a, SCFS_ERP.DBO.AUTHORIZATIONSLIPDETAIL C
WHERE  A.ASLDID = C.OLDASLDID
AND A.OLDVTDID > 0 
and a.SDPTID = 1

GO

EXEC [Z_IMPORT_GO_DETAIL_Auto_Generate_XML]
GO

--SELECT * fROM GATEOUTDETAIL WHERE OLDGODID > 0 
update a
SET GONO = GODID, GODNO = GODID
from [SCFS_ERP].dbo.GATEOUTDETAIL a
WHERE OLDGODID > 0 
and GATEOUTDETAIL.SDPTID = 1

update a
SET EHIDATE = PRCSDATE, EHITIME= PRCSDATE
from [SCFS_ERP].dbo.GATEOUTDETAIL a
WHERE OLDGODID > 0 
and GATEOUTDETAIL.SDPTID = 1

update a
SET GIDID = B.GIDID
from [SCFS_ERP].dbo.GATEOUTDETAIL a JOIN [SCFS_ERP].dbo.GATEINDETAIL B ON A.GIDID = B.OLDGID
WHERE B.OLDGID > 0 
and GATEOUTDETAIL.SDPTID = 1

--Delivery order 
exec [Z_IMPORT_DO_DETAIL_Auto_Generate_XML]

update a
SET BILLEDID = B.BILLEDID
from [SCFS_ERP].dbo.DELIVERYORDERDETAIL a, SCFS_ERP.DBO.BILLENTRYDETAIL B(NOLOCK)
WHERE A.BILLEDID = B.OLDBILLEDID
AND A.OLDDODID > 0 
