--select GIDID, COUNT(ASLMID)
-- from  [SCFS].dbo.z_din_18092021 (nolock)
-- GROUP BY GIDID 
-- HAVING COUNT(ASLMID) > 1

-- SELECT * from  [SCFS].dbo.z_din_18092021 (nolock)
-- WHERE GIDID IN ( 1508588, 1638491)

-- SELECT * FROM SCFS.DBO.AUTHORIZATIONSLIPMASTER
-- WHERE ASLMID IN ( 166024, 514846, 182246, 538402)
 
-- SELECT * FROM SCFS.DBO.AUTHORIZATIONSLIPDETAIL
-- WHERE ASLDID IN ( 196405, 615073, 215898, 642559)

-- select * From opensheetmaster where osmid = 383
 
-- select * From opensheetdetail where osmid = 383

-- select * from BILLENTRYdetail where BILLEDID = 1314
 
-- select * From billentrymaster where billemid = 383

SELECT * FROM GATEINDETAIL (NOLOCK) WHERE OLDGID > 0

SELECT OLDGID,COUNT('*') FROM GATEINDETAIL (NOLOCK) WHERE OLDGID > 0 
group by OLDGID
having count('*')>1

SELECT OLDOSDID,COUNT('*') FROM OPENSHEETDETAIL (NOLOCK) WHERE OLDOSDID > 0 
group by OLDOSDID
having count('*')>1


SELECT OLDBILLEDID,COUNT('*') FROM BILLENTRYDETAIL (NOLOCK) WHERE OLDBILLEDID > 0 
group by OLDBILLEDID
having count('*')>1


SELECT OLDASLDID,COUNT('*') FROM AUTHORIZATIONSLIPDETAIL (NOLOCK) WHERE OLDASLDID > 0 
group by OLDASLDID
having count('*')>1


select * into CATEGORYMASTER_bkup290921 from CATEGORYMASTER
SELECT OLDVTDID,COUNT('*') FROM VEHICLETICKETDETAIL (NOLOCK) WHERE OLDVTDID > 0 
group by OLDVTDID
having count('*')>1

SELECT OLDGODID,COUNT('*') FROM GATEOUTDETAIL (NOLOCK) WHERE OLDGODID > 0 
group by OLDGODID
having count('*')>1
--ORDER BY GIDID
SELECT COUNT(*) FROM GATEINDETAIL (NOLOCK) WHERE OLDGID > 0
SELECT COUNT(*) FROM OPENSHEETDETAIL (NOLOCK) WHERE OLDOSDID > 0
SELECT COUNT(*) FROM BILLENTRYDETAIL (NOLOCK) WHERE OLDBILLEDID > 0
SELECT COUNT(*) FROM AUTHORIZATIONSLIPDETAIL (NOLOCK) WHERE OLDASLDID > 0
SELECT COUNT(*) FROM AUTHORIZATIONSLIPMASTER A (NOLOCK) JOIN AUTHORIZATIONSLIPDETAIL B(NOLOCK) ON A.ASLMID = B.ASLMID WHERE OLDASLDID > 0
--ORDER BY ASLMDATE DESC

SELECT COUNT(*) FROM VEHICLETICKETDETAIL (NOLOCK) WHERE OLDVTDID > 0 and SDPTID = 1
SELECT COUNT(*) FROM GATEOUTDETAIL (NOLOCK) WHERE OLDGODID > 0 and SDPTID = 1
SELECT COUNT(*) FROM DELIVERYORDERDETAIL (NOLOCK) WHERE OLDDODID > 0 


SELECT count('*') FROM REMOTEGATEINDETAIL (nolock) WHERE OLDGID > 0

--select * from VEHICLETICKETDETAIL left join GATEINDETAIL on VEHICLETICKETDETAIL.GIDID = GATEINDETAIL.GIDID
--where isnull( GATEINDETAIL.GIDID,0) =0

--SELECT * fROM SCFS.DBO.VEHICLETICKETDETAIL WHERE VTDID = 597763
--SELECT * fROM SCFS.DBO.AUTHORIZATIONSLIPDETAIL WHERE ASLDID = 642739
--SELECT * fROM SCFS.DBO.OPENSHEETDETAIL WHERE OSDID = 482890

--SELECT * fROM SCFS_eRP.DBO.VEHICLETICKETDETAIL WHERE OLDVTDID = 597763
--SELECT * fROM SCFS_ERP.DBO.AUTHORIZATIONSLIPDETAIL WHERE OLDASLDID = 642739
--SELECT * fROM SCFS_ERP.DBO.OPENSHEETDETAIL WHERE OLDOSDID = 482890
--SELECT * fROM SCFS_ERP.DBO.BILLENTRYDETAIL WHERE OSDID = 482890

--DELETE [SCFS_ERP].[dbo].VEHICLETICKETDETAIL WHERE OLDVTDID = 597763
--SELECT * FROM [SCFS_ERP].[dbo].VEHICLETICKETDETAIL WHERE OLDVTDID = 597763
--INSERT INTO [SCFS_ERP].[dbo].VEHICLETICKETDETAIL
--			(
--			  COMPYID, SDPTID, VTDATE, VTTIME, VTNO, VTDNO, ASLDID, VHLNO, DRVNAME, VTDESC, VTQTY, VTTYPE, VTSTYPE, VTREMRKS, 
--			  GIDID, EGIDID , CUSRID,  LMUSRID, DISPSTATUS, PRCSDATE, VTSSEALNO, VTCTYPE, CGIDID, STFDID, EVLDATE, EVSDATE,
--			  ELRDATE, TRNSPRTID, TRNSPRTNAME, GTRNSPRTNAME, VHLMID, OLDVTDID
--			)
--			Select	A.COMPYID, A.SDPTID, A.VTDATE, A.VTTIME, A.VTNO, A.VTDNO, A.ASLDID, A.VHLNO, A.DRVNAME, A.VTDESC, 
--					A.VTQTY, A.VTTYPE, A.VTSTYPE, A.VTREMRKS, A.GIDID, A.EGIDID , A.CUSRID,  A.LMUSRID, A.DISPSTATUS, 
--					A.PRCSDATE, A.VTSSEALNO, A.VTCTYPE, A.CGIDID, A.STFDID, A.EVLDATE, A.EVSDATE, A.ELRDATE, 0, 
--					'', '', 0, A.VTDID
--			From [SCFS].dbo.VEHICLETICKETDETAIL A(NOLOCK) INNER JOIN
--					[SCFS].dbo.z_din_18092021 b(nolock) ON a.VTDID = b.VTDID
--			  Where B.VTDID = 597763
--			  Group by  A.COMPYID, A.SDPTID, A.VTDATE, A.VTTIME, A.VTNO, A.VTDNO, A.ASLDID, A.VHLNO, A.DRVNAME, A.VTDESC, 
--					A.VTQTY, A.VTTYPE, A.VTSTYPE, A.VTREMRKS, A.GIDID, A.EGIDID , A.CUSRID,  A.LMUSRID, A.DISPSTATUS, 
--					A.PRCSDATE, A.VTSSEALNO, A.VTCTYPE, A.CGIDID, A.STFDID, A.EVLDATE, A.EVSDATE, A.ELRDATE, A.VTDID


--	   Select b.* 
--	  from [SCFS].dbo.z_din_18092021 B (NOLOCK)
--	  where VTDID = 597763 gidid  in ( select oldgid from gateindetail where oldgid >0)
