
ALTER TABLE [dbo].[GATEIN_BLOCK_DETAILS] DROP CONSTRAINT DF_GATEIN_BLOCK_DETAILS_LMUSRID
alter table [GATEIN_BLOCK_DETAILS]
alter column LMUSRID varchar(100) null 

ALTER TABLE [dbo].[GATEIN_BLOCK_DETAILS] ADD  CONSTRAINT DF_GATEIN_BLOCK_DETAILS_LMUSRID  DEFAULT (('')) FOR [LMUSRID]
