//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BondEntities : DbContext
    {
        public BondEntities()
            : base("name=BondEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BONDSPACEDETAIL> BONDSPACEDETAILs { get; set; }
        public virtual DbSet<VW_BOND_RATECARDMASTER_FLX_ASSGN> VW_BOND_RATECARDMASTER_FLX_ASSGN { get; set; }
        public virtual DbSet<VW_BOND_SLABTYPE_HSN_DETAIL_ASSGN> VW_BOND_SLABTYPE_HSN_DETAIL_ASSGN { get; set; }
    
        public virtual ObjectResult<pr_Search_BondGodownMaster_Result> pr_Search_BondGodownMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_BondGodownMaster_Result>("pr_Search_BondGodownMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_Bond_Information_Result> pr_Search_Bond_Information(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pCompyid)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pCompyidParameter = pCompyid.HasValue ?
                new ObjectParameter("PCompyid", pCompyid) :
                new ObjectParameter("PCompyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Bond_Information_Result>("pr_Search_Bond_Information", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter, pCompyidParameter);
        }
    
        public virtual ObjectResult<pr_Search_Bond_GateIn_Result> pr_Search_Bond_GateIn(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pCompyid)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pCompyidParameter = pCompyid.HasValue ?
                new ObjectParameter("PCompyid", pCompyid) :
                new ObjectParameter("PCompyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Bond_GateIn_Result>("pr_Search_Bond_GateIn", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter, pCompyidParameter);
        }
    
        public virtual ObjectResult<pr_Search_BondSlabTypeMaster_Result> pr_Search_BondSlabTypeMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_BondSlabTypeMaster_Result>("pr_Search_BondSlabTypeMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Search_BondSlabMaster_Result> pr_Search_BondSlabMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pTARIFFMID, Nullable<int> pCHRGETYPE, Nullable<int> pSLABTID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pTARIFFMIDParameter = pTARIFFMID.HasValue ?
                new ObjectParameter("PTARIFFMID", pTARIFFMID) :
                new ObjectParameter("PTARIFFMID", typeof(int));
    
            var pCHRGETYPEParameter = pCHRGETYPE.HasValue ?
                new ObjectParameter("PCHRGETYPE", pCHRGETYPE) :
                new ObjectParameter("PCHRGETYPE", typeof(int));
    
            var pSLABTIDParameter = pSLABTID.HasValue ?
                new ObjectParameter("PSLABTID", pSLABTID) :
                new ObjectParameter("PSLABTID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_BondSlabMaster_Result>("pr_Search_BondSlabMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pTARIFFMIDParameter, pCHRGETYPEParameter, pSLABTIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Bond_TariffMaster_Result> pr_Search_Bond_TariffMaster(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Bond_TariffMaster_Result>("pr_Search_Bond_TariffMaster", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_get_Bond_Details_for_Invoice_Result> pr_get_Bond_Details_for_Invoice(string term)
        {
            var termParameter = term != null ?
                new ObjectParameter("term", term) :
                new ObjectParameter("term", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_get_Bond_Details_for_Invoice_Result>("pr_get_Bond_Details_for_Invoice", termParameter);
        }
    
        public virtual ObjectResult<pr_SearchBondProductGroup_Result> pr_SearchBondProductGroup(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchBondProductGroup_Result>("pr_SearchBondProductGroup", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<pr_Get_Bond_Contnr_Recev_Frm_Result> pr_Get_Bond_Contnr_Recev_Frm()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Bond_Contnr_Recev_Frm_Result>("pr_Get_Bond_Contnr_Recev_Frm");
        }
    
        public virtual ObjectResult<pr_get_Bond_Godown_Types_Result> pr_get_Bond_Godown_Types()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_get_Bond_Godown_Types_Result>("pr_get_Bond_Godown_Types");
        }
    
        public virtual ObjectResult<pr_get_Bond_Godowns_Result> pr_get_Bond_Godowns(Nullable<int> gwtid)
        {
            var gwtidParameter = gwtid.HasValue ?
                new ObjectParameter("gwtid", gwtid) :
                new ObjectParameter("gwtid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_get_Bond_Godowns_Result>("pr_get_Bond_Godowns", gwtidParameter);
        }
    
        public virtual ObjectResult<pr_Get_Bond_Tariff_Period_Types_Result> pr_Get_Bond_Tariff_Period_Types(Nullable<int> tariffmid)
        {
            var tariffmidParameter = tariffmid.HasValue ?
                new ObjectParameter("tariffmid", tariffmid) :
                new ObjectParameter("tariffmid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Bond_Tariff_Period_Types_Result>("pr_Get_Bond_Tariff_Period_Types", tariffmidParameter);
        }
    
        public virtual ObjectResult<pr_get_Bond_Operation_Types_Result> pr_get_Bond_Operation_Types()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_get_Bond_Operation_Types_Result>("pr_get_Bond_Operation_Types");
        }
    
        public virtual ObjectResult<pr_get_Bond_Types_Result> pr_get_Bond_Types()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_get_Bond_Types_Result>("pr_get_Bond_Types");
        }
    
        public virtual ObjectResult<pr_get_BondMaster_Status_Result2> pr_get_BondMaster_Status()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_get_BondMaster_Status_Result2>("pr_get_BondMaster_Status");
        }
    
        public virtual ObjectResult<pr_Search_ExBond_Information_Result> pr_Search_ExBond_Information(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pCompyid)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pCompyidParameter = pCompyid.HasValue ?
                new ObjectParameter("PCompyid", pCompyid) :
                new ObjectParameter("PCompyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_ExBond_Information_Result>("pr_Search_ExBond_Information", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter, pCompyidParameter);
        }
    
        public virtual ObjectResult<pr_Get_Bond_Info_Result> pr_Get_Bond_Info(Nullable<int> compyid, Nullable<int> bondid)
        {
            var compyidParameter = compyid.HasValue ?
                new ObjectParameter("compyid", compyid) :
                new ObjectParameter("compyid", typeof(int));
    
            var bondidParameter = bondid.HasValue ?
                new ObjectParameter("bondid", bondid) :
                new ObjectParameter("bondid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Bond_Info_Result>("pr_Get_Bond_Info", compyidParameter, bondidParameter);
        }
    
        public virtual ObjectResult<pr_Search_Bond_Vehicle_Ticket_Result> pr_Search_Bond_Vehicle_Ticket(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Bond_Vehicle_Ticket_Result>("pr_Search_Bond_Vehicle_Ticket", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pSDateParameter, pEDateParameter);
        }
    
        public virtual ObjectResult<pr_Get_ExBond_Info_Result> pr_Get_ExBond_Info(Nullable<int> compyid, Nullable<int> exbondid)
        {
            var compyidParameter = compyid.HasValue ?
                new ObjectParameter("compyid", compyid) :
                new ObjectParameter("compyid", typeof(int));
    
            var exbondidParameter = exbondid.HasValue ?
                new ObjectParameter("exbondid", exbondid) :
                new ObjectParameter("exbondid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_ExBond_Info_Result>("pr_Get_ExBond_Info", compyidParameter, exbondidParameter);
        }
    
        public virtual ObjectResult<pr_Search_Bond_GateOut_Result> pr_Search_Bond_GateOut(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Bond_GateOut_Result>("pr_Search_Bond_GateOut", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pSDateParameter, pEDateParameter);
        }
    
        public virtual ObjectResult<pr_Bond_Invoice_BondNO_Grid_Assgn_Result> pr_Bond_Invoice_BondNO_Grid_Assgn(string userid, Nullable<int> pBNDID, Nullable<int> pTRANMID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE, Nullable<int> pBCHAID, Nullable<int> pBCATEAID, Nullable<int> pTARIFFMID, Nullable<int> pSLABTID, Nullable<int> pCHRGTYPE, Nullable<int> pRDTID, Nullable<int> pYRDID, Nullable<int> pOPRID, Nullable<int> pHNDTID, Nullable<int> pCNTSID, Nullable<decimal> pQTY, Nullable<decimal> pNOP, Nullable<decimal> pRATE, Nullable<decimal> pAMT, Nullable<short> pTAXTYPE)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var pBNDIDParameter = pBNDID.HasValue ?
                new ObjectParameter("PBNDID", pBNDID) :
                new ObjectParameter("PBNDID", typeof(int));
    
            var pTRANMIDParameter = pTRANMID.HasValue ?
                new ObjectParameter("PTRANMID", pTRANMID) :
                new ObjectParameter("PTRANMID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            var pBCHAIDParameter = pBCHAID.HasValue ?
                new ObjectParameter("PBCHAID", pBCHAID) :
                new ObjectParameter("PBCHAID", typeof(int));
    
            var pBCATEAIDParameter = pBCATEAID.HasValue ?
                new ObjectParameter("PBCATEAID", pBCATEAID) :
                new ObjectParameter("PBCATEAID", typeof(int));
    
            var pTARIFFMIDParameter = pTARIFFMID.HasValue ?
                new ObjectParameter("PTARIFFMID", pTARIFFMID) :
                new ObjectParameter("PTARIFFMID", typeof(int));
    
            var pSLABTIDParameter = pSLABTID.HasValue ?
                new ObjectParameter("PSLABTID", pSLABTID) :
                new ObjectParameter("PSLABTID", typeof(int));
    
            var pCHRGTYPEParameter = pCHRGTYPE.HasValue ?
                new ObjectParameter("PCHRGTYPE", pCHRGTYPE) :
                new ObjectParameter("PCHRGTYPE", typeof(int));
    
            var pRDTIDParameter = pRDTID.HasValue ?
                new ObjectParameter("PRDTID", pRDTID) :
                new ObjectParameter("PRDTID", typeof(int));
    
            var pYRDIDParameter = pYRDID.HasValue ?
                new ObjectParameter("PYRDID", pYRDID) :
                new ObjectParameter("PYRDID", typeof(int));
    
            var pOPRIDParameter = pOPRID.HasValue ?
                new ObjectParameter("POPRID", pOPRID) :
                new ObjectParameter("POPRID", typeof(int));
    
            var pHNDTIDParameter = pHNDTID.HasValue ?
                new ObjectParameter("PHNDTID", pHNDTID) :
                new ObjectParameter("PHNDTID", typeof(int));
    
            var pCNTSIDParameter = pCNTSID.HasValue ?
                new ObjectParameter("PCNTSID", pCNTSID) :
                new ObjectParameter("PCNTSID", typeof(int));
    
            var pQTYParameter = pQTY.HasValue ?
                new ObjectParameter("PQTY", pQTY) :
                new ObjectParameter("PQTY", typeof(decimal));
    
            var pNOPParameter = pNOP.HasValue ?
                new ObjectParameter("PNOP", pNOP) :
                new ObjectParameter("PNOP", typeof(decimal));
    
            var pRATEParameter = pRATE.HasValue ?
                new ObjectParameter("PRATE", pRATE) :
                new ObjectParameter("PRATE", typeof(decimal));
    
            var pAMTParameter = pAMT.HasValue ?
                new ObjectParameter("PAMT", pAMT) :
                new ObjectParameter("PAMT", typeof(decimal));
    
            var pTAXTYPEParameter = pTAXTYPE.HasValue ?
                new ObjectParameter("PTAXTYPE", pTAXTYPE) :
                new ObjectParameter("PTAXTYPE", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Bond_Invoice_BondNO_Grid_Assgn_Result>("pr_Bond_Invoice_BondNO_Grid_Assgn", useridParameter, pBNDIDParameter, pTRANMIDParameter, pSDATEParameter, pEDATEParameter, pBCHAIDParameter, pBCATEAIDParameter, pTARIFFMIDParameter, pSLABTIDParameter, pCHRGTYPEParameter, pRDTIDParameter, pYRDIDParameter, pOPRIDParameter, pHNDTIDParameter, pCNTSIDParameter, pQTYParameter, pNOPParameter, pRATEParameter, pAMTParameter, pTAXTYPEParameter);
        }
    
        public virtual ObjectResult<pr_BondPerforma_Invoice_BondNO_Grid_Assgn_Result> pr_BondPerforma_Invoice_BondNO_Grid_Assgn(string userid, Nullable<int> pBNDID, Nullable<int> pTRANMID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE, Nullable<int> pBCHAID, Nullable<int> pBCATEAID, Nullable<int> pTARIFFMID, Nullable<int> pSLABTID, Nullable<int> pCHRGTYPE, Nullable<int> pRDTID, Nullable<int> pYRDID, Nullable<int> pOPRID, Nullable<int> pHNDTID, Nullable<int> pCNTSID, Nullable<decimal> pQTY, Nullable<decimal> pNOP, Nullable<decimal> pRATE, Nullable<decimal> pAMT, Nullable<short> pTAXTYPE)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var pBNDIDParameter = pBNDID.HasValue ?
                new ObjectParameter("PBNDID", pBNDID) :
                new ObjectParameter("PBNDID", typeof(int));
    
            var pTRANMIDParameter = pTRANMID.HasValue ?
                new ObjectParameter("PTRANMID", pTRANMID) :
                new ObjectParameter("PTRANMID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            var pBCHAIDParameter = pBCHAID.HasValue ?
                new ObjectParameter("PBCHAID", pBCHAID) :
                new ObjectParameter("PBCHAID", typeof(int));
    
            var pBCATEAIDParameter = pBCATEAID.HasValue ?
                new ObjectParameter("PBCATEAID", pBCATEAID) :
                new ObjectParameter("PBCATEAID", typeof(int));
    
            var pTARIFFMIDParameter = pTARIFFMID.HasValue ?
                new ObjectParameter("PTARIFFMID", pTARIFFMID) :
                new ObjectParameter("PTARIFFMID", typeof(int));
    
            var pSLABTIDParameter = pSLABTID.HasValue ?
                new ObjectParameter("PSLABTID", pSLABTID) :
                new ObjectParameter("PSLABTID", typeof(int));
    
            var pCHRGTYPEParameter = pCHRGTYPE.HasValue ?
                new ObjectParameter("PCHRGTYPE", pCHRGTYPE) :
                new ObjectParameter("PCHRGTYPE", typeof(int));
    
            var pRDTIDParameter = pRDTID.HasValue ?
                new ObjectParameter("PRDTID", pRDTID) :
                new ObjectParameter("PRDTID", typeof(int));
    
            var pYRDIDParameter = pYRDID.HasValue ?
                new ObjectParameter("PYRDID", pYRDID) :
                new ObjectParameter("PYRDID", typeof(int));
    
            var pOPRIDParameter = pOPRID.HasValue ?
                new ObjectParameter("POPRID", pOPRID) :
                new ObjectParameter("POPRID", typeof(int));
    
            var pHNDTIDParameter = pHNDTID.HasValue ?
                new ObjectParameter("PHNDTID", pHNDTID) :
                new ObjectParameter("PHNDTID", typeof(int));
    
            var pCNTSIDParameter = pCNTSID.HasValue ?
                new ObjectParameter("PCNTSID", pCNTSID) :
                new ObjectParameter("PCNTSID", typeof(int));
    
            var pQTYParameter = pQTY.HasValue ?
                new ObjectParameter("PQTY", pQTY) :
                new ObjectParameter("PQTY", typeof(decimal));
    
            var pNOPParameter = pNOP.HasValue ?
                new ObjectParameter("PNOP", pNOP) :
                new ObjectParameter("PNOP", typeof(decimal));
    
            var pRATEParameter = pRATE.HasValue ?
                new ObjectParameter("PRATE", pRATE) :
                new ObjectParameter("PRATE", typeof(decimal));
    
            var pAMTParameter = pAMT.HasValue ?
                new ObjectParameter("PAMT", pAMT) :
                new ObjectParameter("PAMT", typeof(decimal));
    
            var pTAXTYPEParameter = pTAXTYPE.HasValue ?
                new ObjectParameter("PTAXTYPE", pTAXTYPE) :
                new ObjectParameter("PTAXTYPE", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_BondPerforma_Invoice_BondNO_Grid_Assgn_Result>("pr_BondPerforma_Invoice_BondNO_Grid_Assgn", useridParameter, pBNDIDParameter, pTRANMIDParameter, pSDATEParameter, pEDATEParameter, pBCHAIDParameter, pBCATEAIDParameter, pTARIFFMIDParameter, pSLABTIDParameter, pCHRGTYPEParameter, pRDTIDParameter, pYRDIDParameter, pOPRIDParameter, pHNDTIDParameter, pCNTSIDParameter, pQTYParameter, pNOPParameter, pRATEParameter, pAMTParameter, pTAXTYPEParameter);
        }
    
        public virtual ObjectResult<pr_Search_BondExBond_EInvoice_Result> pr_Search_BondExBond_EInvoice(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<int> pTRANBTYPE, Nullable<int> pREGSTRID, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pTRANBTYPEParameter = pTRANBTYPE.HasValue ?
                new ObjectParameter("PTRANBTYPE", pTRANBTYPE) :
                new ObjectParameter("PTRANBTYPE", typeof(int));
    
            var pREGSTRIDParameter = pREGSTRID.HasValue ?
                new ObjectParameter("PREGSTRID", pREGSTRID) :
                new ObjectParameter("PREGSTRID", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_BondExBond_EInvoice_Result>("pr_Search_BondExBond_EInvoice", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pTRANBTYPEParameter, pREGSTRIDParameter, pSDateParameter, pEDateParameter);
        }
    
        public virtual ObjectResult<pr_Search_BondInvoice_Result> pr_Search_BondInvoice(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<int> pTRANBTYPE, Nullable<int> pREGSTRID, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pTAXTYPE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pTRANBTYPEParameter = pTRANBTYPE.HasValue ?
                new ObjectParameter("PTRANBTYPE", pTRANBTYPE) :
                new ObjectParameter("PTRANBTYPE", typeof(int));
    
            var pREGSTRIDParameter = pREGSTRID.HasValue ?
                new ObjectParameter("PREGSTRID", pREGSTRID) :
                new ObjectParameter("PREGSTRID", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pTAXTYPEParameter = pTAXTYPE.HasValue ?
                new ObjectParameter("PTAXTYPE", pTAXTYPE) :
                new ObjectParameter("PTAXTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_BondInvoice_Result>("pr_Search_BondInvoice", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pTRANBTYPEParameter, pREGSTRIDParameter, pSDateParameter, pEDateParameter, pTAXTYPEParameter);
        }
    
        public virtual ObjectResult<pr_Search_BondPerformaInvoice_Result> pr_Search_BondPerformaInvoice(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<int> pTRANBTYPE, Nullable<int> pREGSTRID, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pTAXTYPE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pTRANBTYPEParameter = pTRANBTYPE.HasValue ?
                new ObjectParameter("PTRANBTYPE", pTRANBTYPE) :
                new ObjectParameter("PTRANBTYPE", typeof(int));
    
            var pREGSTRIDParameter = pREGSTRID.HasValue ?
                new ObjectParameter("PREGSTRID", pREGSTRID) :
                new ObjectParameter("PREGSTRID", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pTAXTYPEParameter = pTAXTYPE.HasValue ?
                new ObjectParameter("PTAXTYPE", pTAXTYPE) :
                new ObjectParameter("PTAXTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_BondPerformaInvoice_Result>("pr_Search_BondPerformaInvoice", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pTRANBTYPEParameter, pREGSTRIDParameter, pSDateParameter, pEDateParameter, pTAXTYPEParameter);
        }
    
        public virtual ObjectResult<pr_Search_ExBondVTInvoice_Result> pr_Search_ExBondVTInvoice(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<int> pTRANBTYPE, Nullable<int> pREGSTRID, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pTAXTYPE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pTRANBTYPEParameter = pTRANBTYPE.HasValue ?
                new ObjectParameter("PTRANBTYPE", pTRANBTYPE) :
                new ObjectParameter("PTRANBTYPE", typeof(int));
    
            var pREGSTRIDParameter = pREGSTRID.HasValue ?
                new ObjectParameter("PREGSTRID", pREGSTRID) :
                new ObjectParameter("PREGSTRID", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pTAXTYPEParameter = pTAXTYPE.HasValue ?
                new ObjectParameter("PTAXTYPE", pTAXTYPE) :
                new ObjectParameter("PTAXTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_ExBondVTInvoice_Result>("pr_Search_ExBondVTInvoice", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pTRANBTYPEParameter, pREGSTRIDParameter, pSDateParameter, pEDateParameter, pTAXTYPEParameter);
        }
    
        public virtual ObjectResult<pr_Search_BondManualInvoice_Result> pr_Search_BondManualInvoice(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<int> pTRANBTYPE, Nullable<int> pREGSTRID, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pTAXTYPE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pTRANBTYPEParameter = pTRANBTYPE.HasValue ?
                new ObjectParameter("PTRANBTYPE", pTRANBTYPE) :
                new ObjectParameter("PTRANBTYPE", typeof(int));
    
            var pREGSTRIDParameter = pREGSTRID.HasValue ?
                new ObjectParameter("PREGSTRID", pREGSTRID) :
                new ObjectParameter("PREGSTRID", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pTAXTYPEParameter = pTAXTYPE.HasValue ?
                new ObjectParameter("PTAXTYPE", pTAXTYPE) :
                new ObjectParameter("PTAXTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_BondManualInvoice_Result>("pr_Search_BondManualInvoice", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pTRANBTYPEParameter, pREGSTRIDParameter, pSDateParameter, pEDateParameter, pTAXTYPEParameter);
        }
    
        public virtual ObjectResult<pr_Bond_Manual_Invoice_BondNO_Grid_Assgn_Result> pr_Bond_Manual_Invoice_BondNO_Grid_Assgn(string userid, Nullable<int> pBNDID, Nullable<int> pTRANMID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE, Nullable<int> pBCHAID, Nullable<int> pBCATEAID, Nullable<int> pTARIFFMID, Nullable<int> pSLABTID, Nullable<int> pCHRGTYPE, Nullable<int> pRDTID, Nullable<int> pYRDID, Nullable<int> pOPRID, Nullable<int> pHNDTID, Nullable<int> pCNTSID, Nullable<decimal> pQTY, Nullable<decimal> pNOP, Nullable<decimal> pRATE, Nullable<decimal> pAMT, Nullable<short> pTAXTYPE, string pBILLDESC)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var pBNDIDParameter = pBNDID.HasValue ?
                new ObjectParameter("PBNDID", pBNDID) :
                new ObjectParameter("PBNDID", typeof(int));
    
            var pTRANMIDParameter = pTRANMID.HasValue ?
                new ObjectParameter("PTRANMID", pTRANMID) :
                new ObjectParameter("PTRANMID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            var pBCHAIDParameter = pBCHAID.HasValue ?
                new ObjectParameter("PBCHAID", pBCHAID) :
                new ObjectParameter("PBCHAID", typeof(int));
    
            var pBCATEAIDParameter = pBCATEAID.HasValue ?
                new ObjectParameter("PBCATEAID", pBCATEAID) :
                new ObjectParameter("PBCATEAID", typeof(int));
    
            var pTARIFFMIDParameter = pTARIFFMID.HasValue ?
                new ObjectParameter("PTARIFFMID", pTARIFFMID) :
                new ObjectParameter("PTARIFFMID", typeof(int));
    
            var pSLABTIDParameter = pSLABTID.HasValue ?
                new ObjectParameter("PSLABTID", pSLABTID) :
                new ObjectParameter("PSLABTID", typeof(int));
    
            var pCHRGTYPEParameter = pCHRGTYPE.HasValue ?
                new ObjectParameter("PCHRGTYPE", pCHRGTYPE) :
                new ObjectParameter("PCHRGTYPE", typeof(int));
    
            var pRDTIDParameter = pRDTID.HasValue ?
                new ObjectParameter("PRDTID", pRDTID) :
                new ObjectParameter("PRDTID", typeof(int));
    
            var pYRDIDParameter = pYRDID.HasValue ?
                new ObjectParameter("PYRDID", pYRDID) :
                new ObjectParameter("PYRDID", typeof(int));
    
            var pOPRIDParameter = pOPRID.HasValue ?
                new ObjectParameter("POPRID", pOPRID) :
                new ObjectParameter("POPRID", typeof(int));
    
            var pHNDTIDParameter = pHNDTID.HasValue ?
                new ObjectParameter("PHNDTID", pHNDTID) :
                new ObjectParameter("PHNDTID", typeof(int));
    
            var pCNTSIDParameter = pCNTSID.HasValue ?
                new ObjectParameter("PCNTSID", pCNTSID) :
                new ObjectParameter("PCNTSID", typeof(int));
    
            var pQTYParameter = pQTY.HasValue ?
                new ObjectParameter("PQTY", pQTY) :
                new ObjectParameter("PQTY", typeof(decimal));
    
            var pNOPParameter = pNOP.HasValue ?
                new ObjectParameter("PNOP", pNOP) :
                new ObjectParameter("PNOP", typeof(decimal));
    
            var pRATEParameter = pRATE.HasValue ?
                new ObjectParameter("PRATE", pRATE) :
                new ObjectParameter("PRATE", typeof(decimal));
    
            var pAMTParameter = pAMT.HasValue ?
                new ObjectParameter("PAMT", pAMT) :
                new ObjectParameter("PAMT", typeof(decimal));
    
            var pTAXTYPEParameter = pTAXTYPE.HasValue ?
                new ObjectParameter("PTAXTYPE", pTAXTYPE) :
                new ObjectParameter("PTAXTYPE", typeof(short));
    
            var pBILLDESCParameter = pBILLDESC != null ?
                new ObjectParameter("PBILLDESC", pBILLDESC) :
                new ObjectParameter("PBILLDESC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Bond_Manual_Invoice_BondNO_Grid_Assgn_Result>("pr_Bond_Manual_Invoice_BondNO_Grid_Assgn", useridParameter, pBNDIDParameter, pTRANMIDParameter, pSDATEParameter, pEDATEParameter, pBCHAIDParameter, pBCATEAIDParameter, pTARIFFMIDParameter, pSLABTIDParameter, pCHRGTYPEParameter, pRDTIDParameter, pYRDIDParameter, pOPRIDParameter, pHNDTIDParameter, pCNTSIDParameter, pQTYParameter, pNOPParameter, pRATEParameter, pAMTParameter, pTAXTYPEParameter, pBILLDESCParameter);
        }
    
        public virtual ObjectResult<pr_Ex_Bond_VT_Invoice_BondNO_Grid_Assgn_Result> pr_Ex_Bond_VT_Invoice_BondNO_Grid_Assgn(string userid, Nullable<int> pVTDID, Nullable<int> pEBNDID, Nullable<int> pBNDID, Nullable<int> pTRANMID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE, Nullable<int> pBCHAID, Nullable<int> pBCATEAID, Nullable<int> pTARIFFMID, Nullable<int> pSLABTID, Nullable<int> pCHRGTYPE, Nullable<int> pRDTID, Nullable<int> pYRDID, Nullable<int> pOPRID, Nullable<int> pHNDTID, Nullable<int> pCNTSID, Nullable<decimal> pQTY, Nullable<decimal> pNOP, Nullable<decimal> pRATE, Nullable<decimal> pAMT, Nullable<int> pHTYPE, Nullable<short> pTAXTYPE, Nullable<decimal> pVTSPC)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var pVTDIDParameter = pVTDID.HasValue ?
                new ObjectParameter("PVTDID", pVTDID) :
                new ObjectParameter("PVTDID", typeof(int));
    
            var pEBNDIDParameter = pEBNDID.HasValue ?
                new ObjectParameter("PEBNDID", pEBNDID) :
                new ObjectParameter("PEBNDID", typeof(int));
    
            var pBNDIDParameter = pBNDID.HasValue ?
                new ObjectParameter("PBNDID", pBNDID) :
                new ObjectParameter("PBNDID", typeof(int));
    
            var pTRANMIDParameter = pTRANMID.HasValue ?
                new ObjectParameter("PTRANMID", pTRANMID) :
                new ObjectParameter("PTRANMID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            var pBCHAIDParameter = pBCHAID.HasValue ?
                new ObjectParameter("PBCHAID", pBCHAID) :
                new ObjectParameter("PBCHAID", typeof(int));
    
            var pBCATEAIDParameter = pBCATEAID.HasValue ?
                new ObjectParameter("PBCATEAID", pBCATEAID) :
                new ObjectParameter("PBCATEAID", typeof(int));
    
            var pTARIFFMIDParameter = pTARIFFMID.HasValue ?
                new ObjectParameter("PTARIFFMID", pTARIFFMID) :
                new ObjectParameter("PTARIFFMID", typeof(int));
    
            var pSLABTIDParameter = pSLABTID.HasValue ?
                new ObjectParameter("PSLABTID", pSLABTID) :
                new ObjectParameter("PSLABTID", typeof(int));
    
            var pCHRGTYPEParameter = pCHRGTYPE.HasValue ?
                new ObjectParameter("PCHRGTYPE", pCHRGTYPE) :
                new ObjectParameter("PCHRGTYPE", typeof(int));
    
            var pRDTIDParameter = pRDTID.HasValue ?
                new ObjectParameter("PRDTID", pRDTID) :
                new ObjectParameter("PRDTID", typeof(int));
    
            var pYRDIDParameter = pYRDID.HasValue ?
                new ObjectParameter("PYRDID", pYRDID) :
                new ObjectParameter("PYRDID", typeof(int));
    
            var pOPRIDParameter = pOPRID.HasValue ?
                new ObjectParameter("POPRID", pOPRID) :
                new ObjectParameter("POPRID", typeof(int));
    
            var pHNDTIDParameter = pHNDTID.HasValue ?
                new ObjectParameter("PHNDTID", pHNDTID) :
                new ObjectParameter("PHNDTID", typeof(int));
    
            var pCNTSIDParameter = pCNTSID.HasValue ?
                new ObjectParameter("PCNTSID", pCNTSID) :
                new ObjectParameter("PCNTSID", typeof(int));
    
            var pQTYParameter = pQTY.HasValue ?
                new ObjectParameter("PQTY", pQTY) :
                new ObjectParameter("PQTY", typeof(decimal));
    
            var pNOPParameter = pNOP.HasValue ?
                new ObjectParameter("PNOP", pNOP) :
                new ObjectParameter("PNOP", typeof(decimal));
    
            var pRATEParameter = pRATE.HasValue ?
                new ObjectParameter("PRATE", pRATE) :
                new ObjectParameter("PRATE", typeof(decimal));
    
            var pAMTParameter = pAMT.HasValue ?
                new ObjectParameter("PAMT", pAMT) :
                new ObjectParameter("PAMT", typeof(decimal));
    
            var pHTYPEParameter = pHTYPE.HasValue ?
                new ObjectParameter("PHTYPE", pHTYPE) :
                new ObjectParameter("PHTYPE", typeof(int));
    
            var pTAXTYPEParameter = pTAXTYPE.HasValue ?
                new ObjectParameter("PTAXTYPE", pTAXTYPE) :
                new ObjectParameter("PTAXTYPE", typeof(short));
    
            var pVTSPCParameter = pVTSPC.HasValue ?
                new ObjectParameter("PVTSPC", pVTSPC) :
                new ObjectParameter("PVTSPC", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Ex_Bond_VT_Invoice_BondNO_Grid_Assgn_Result>("pr_Ex_Bond_VT_Invoice_BondNO_Grid_Assgn", useridParameter, pVTDIDParameter, pEBNDIDParameter, pBNDIDParameter, pTRANMIDParameter, pSDATEParameter, pEDATEParameter, pBCHAIDParameter, pBCATEAIDParameter, pTARIFFMIDParameter, pSLABTIDParameter, pCHRGTYPEParameter, pRDTIDParameter, pYRDIDParameter, pOPRIDParameter, pHNDTIDParameter, pCNTSIDParameter, pQTYParameter, pNOPParameter, pRATEParameter, pAMTParameter, pHTYPEParameter, pTAXTYPEParameter, pVTSPCParameter);
        }
    
        public virtual ObjectResult<pr_Search_ExBondVTProformaInvoice_Result> pr_Search_ExBondVTProformaInvoice(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<int> pTRANBTYPE, Nullable<int> pREGSTRID, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pTAXTYPE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pTRANBTYPEParameter = pTRANBTYPE.HasValue ?
                new ObjectParameter("PTRANBTYPE", pTRANBTYPE) :
                new ObjectParameter("PTRANBTYPE", typeof(int));
    
            var pREGSTRIDParameter = pREGSTRID.HasValue ?
                new ObjectParameter("PREGSTRID", pREGSTRID) :
                new ObjectParameter("PREGSTRID", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pTAXTYPEParameter = pTAXTYPE.HasValue ?
                new ObjectParameter("PTAXTYPE", pTAXTYPE) :
                new ObjectParameter("PTAXTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_ExBondVTProformaInvoice_Result>("pr_Search_ExBondVTProformaInvoice", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pTRANBTYPEParameter, pREGSTRIDParameter, pSDateParameter, pEDateParameter, pTAXTYPEParameter);
        }
    
        public virtual ObjectResult<pr_Ex_Bond_VT_Proforma_Invoice_BondNO_Grid_Assgn_Result> pr_Ex_Bond_VT_Proforma_Invoice_BondNO_Grid_Assgn(string userid, Nullable<int> pVTDID, Nullable<int> pEBNDID, Nullable<int> pBNDID, Nullable<int> pTRANMID, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE, Nullable<int> pBCHAID, Nullable<int> pBCATEAID, Nullable<int> pTARIFFMID, Nullable<int> pSLABTID, Nullable<int> pCHRGTYPE, Nullable<int> pRDTID, Nullable<int> pYRDID, Nullable<int> pOPRID, Nullable<int> pHNDTID, Nullable<int> pCNTSID, Nullable<decimal> pQTY, Nullable<decimal> pNOP, Nullable<decimal> pRATE, Nullable<decimal> pAMT, Nullable<int> pHTYPE, Nullable<short> pTAXTYPE, Nullable<decimal> pVTSPC)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var pVTDIDParameter = pVTDID.HasValue ?
                new ObjectParameter("PVTDID", pVTDID) :
                new ObjectParameter("PVTDID", typeof(int));
    
            var pEBNDIDParameter = pEBNDID.HasValue ?
                new ObjectParameter("PEBNDID", pEBNDID) :
                new ObjectParameter("PEBNDID", typeof(int));
    
            var pBNDIDParameter = pBNDID.HasValue ?
                new ObjectParameter("PBNDID", pBNDID) :
                new ObjectParameter("PBNDID", typeof(int));
    
            var pTRANMIDParameter = pTRANMID.HasValue ?
                new ObjectParameter("PTRANMID", pTRANMID) :
                new ObjectParameter("PTRANMID", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            var pBCHAIDParameter = pBCHAID.HasValue ?
                new ObjectParameter("PBCHAID", pBCHAID) :
                new ObjectParameter("PBCHAID", typeof(int));
    
            var pBCATEAIDParameter = pBCATEAID.HasValue ?
                new ObjectParameter("PBCATEAID", pBCATEAID) :
                new ObjectParameter("PBCATEAID", typeof(int));
    
            var pTARIFFMIDParameter = pTARIFFMID.HasValue ?
                new ObjectParameter("PTARIFFMID", pTARIFFMID) :
                new ObjectParameter("PTARIFFMID", typeof(int));
    
            var pSLABTIDParameter = pSLABTID.HasValue ?
                new ObjectParameter("PSLABTID", pSLABTID) :
                new ObjectParameter("PSLABTID", typeof(int));
    
            var pCHRGTYPEParameter = pCHRGTYPE.HasValue ?
                new ObjectParameter("PCHRGTYPE", pCHRGTYPE) :
                new ObjectParameter("PCHRGTYPE", typeof(int));
    
            var pRDTIDParameter = pRDTID.HasValue ?
                new ObjectParameter("PRDTID", pRDTID) :
                new ObjectParameter("PRDTID", typeof(int));
    
            var pYRDIDParameter = pYRDID.HasValue ?
                new ObjectParameter("PYRDID", pYRDID) :
                new ObjectParameter("PYRDID", typeof(int));
    
            var pOPRIDParameter = pOPRID.HasValue ?
                new ObjectParameter("POPRID", pOPRID) :
                new ObjectParameter("POPRID", typeof(int));
    
            var pHNDTIDParameter = pHNDTID.HasValue ?
                new ObjectParameter("PHNDTID", pHNDTID) :
                new ObjectParameter("PHNDTID", typeof(int));
    
            var pCNTSIDParameter = pCNTSID.HasValue ?
                new ObjectParameter("PCNTSID", pCNTSID) :
                new ObjectParameter("PCNTSID", typeof(int));
    
            var pQTYParameter = pQTY.HasValue ?
                new ObjectParameter("PQTY", pQTY) :
                new ObjectParameter("PQTY", typeof(decimal));
    
            var pNOPParameter = pNOP.HasValue ?
                new ObjectParameter("PNOP", pNOP) :
                new ObjectParameter("PNOP", typeof(decimal));
    
            var pRATEParameter = pRATE.HasValue ?
                new ObjectParameter("PRATE", pRATE) :
                new ObjectParameter("PRATE", typeof(decimal));
    
            var pAMTParameter = pAMT.HasValue ?
                new ObjectParameter("PAMT", pAMT) :
                new ObjectParameter("PAMT", typeof(decimal));
    
            var pHTYPEParameter = pHTYPE.HasValue ?
                new ObjectParameter("PHTYPE", pHTYPE) :
                new ObjectParameter("PHTYPE", typeof(int));
    
            var pTAXTYPEParameter = pTAXTYPE.HasValue ?
                new ObjectParameter("PTAXTYPE", pTAXTYPE) :
                new ObjectParameter("PTAXTYPE", typeof(short));
    
            var pVTSPCParameter = pVTSPC.HasValue ?
                new ObjectParameter("PVTSPC", pVTSPC) :
                new ObjectParameter("PVTSPC", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Ex_Bond_VT_Proforma_Invoice_BondNO_Grid_Assgn_Result>("pr_Ex_Bond_VT_Proforma_Invoice_BondNO_Grid_Assgn", useridParameter, pVTDIDParameter, pEBNDIDParameter, pBNDIDParameter, pTRANMIDParameter, pSDATEParameter, pEDATEParameter, pBCHAIDParameter, pBCATEAIDParameter, pTARIFFMIDParameter, pSLABTIDParameter, pCHRGTYPEParameter, pRDTIDParameter, pYRDIDParameter, pOPRIDParameter, pHNDTIDParameter, pCNTSIDParameter, pQTYParameter, pNOPParameter, pRATEParameter, pAMTParameter, pHTYPEParameter, pTAXTYPEParameter, pVTSPCParameter);
        }
    
        public virtual ObjectResult<pr_Get_ExBond_VT_Info_Result> pr_Get_ExBond_VT_Info(Nullable<int> compyid, Nullable<int> vTDID)
        {
            var compyidParameter = compyid.HasValue ?
                new ObjectParameter("compyid", compyid) :
                new ObjectParameter("compyid", typeof(int));
    
            var vTDIDParameter = vTDID.HasValue ?
                new ObjectParameter("VTDID", vTDID) :
                new ObjectParameter("VTDID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_ExBond_VT_Info_Result>("pr_Get_ExBond_VT_Info", compyidParameter, vTDIDParameter);
        }
    
        public virtual ObjectResult<pr_get_Bond_Entry_Types_Result> pr_get_Bond_Entry_Types()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_get_Bond_Entry_Types_Result>("pr_get_Bond_Entry_Types");
        }
    }
}
