//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONDSPACEDETAIL
    {
        public int SPCID { get; set; }
        public int COMPYID { get; set; }
        public int SDPTID { get; set; }
        public System.DateTime SPCDATE { get; set; }
        public Nullable<System.DateTime> SPCTIME { get; set; }
        public Nullable<int> SPCNO { get; set; }
        public string SPCDNO { get; set; }
        public string SPCBENO { get; set; }
        public Nullable<System.DateTime> SPCBEDATE { get; set; }
        public string SPCBLNO { get; set; }
        public Nullable<System.DateTime> SPCBLDATE { get; set; }
        public Nullable<int> IMPRTID { get; set; }
        public Nullable<int> PRDTID { get; set; }
        public Nullable<int> TYPEID { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> GWGHT { get; set; }
        public Nullable<decimal> DQTY { get; set; }
        public Nullable<decimal> WGHT { get; set; }
        public Nullable<decimal> MTRS { get; set; }
        public Nullable<decimal> AAMT { get; set; }
        public Nullable<decimal> DAMT { get; set; }
        public string SPCDESC { get; set; }
        public Nullable<System.DateTime> SPCEDATE { get; set; }
        public Nullable<System.DateTime> SPCSFDATE { get; set; }
        public Nullable<System.DateTime> SPCSTDATE { get; set; }
        public string CUSRID { get; set; }
        public string LMUSRID { get; set; }
        public Nullable<short> DISPSTATUS { get; set; }
        public Nullable<System.DateTime> PRCSDATE { get; set; }
    }
}
