//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CFSImportEntities : DbContext
    {
        public CFSImportEntities()
            : base("name=CFSImportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01> VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01 { get; set; }
        public virtual DbSet<VW_ASL_IGMNO_CONTAINER_CBX_ASSGN_01> VW_ASL_IGMNO_CONTAINER_CBX_ASSGN_01 { get; set; }
        public virtual DbSet<VW_IMPORT_TRANSACTION_ADDRESS_DETAIL_ASSGN> VW_IMPORT_TRANSACTION_ADDRESS_DETAIL_ASSGN { get; set; }
        public virtual DbSet<VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN> VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN { get; set; }
        public virtual DbSet<VW_DELIVERY_ORDER_DETAIL_GRID_ASSGN> VW_DELIVERY_ORDER_DETAIL_GRID_ASSGN { get; set; }
        public virtual DbSet<VW_VEHICLETICKET_IMPORT_CONTAINER_CBX_ASSGN> VW_VEHICLETICKET_IMPORT_CONTAINER_CBX_ASSGN { get; set; }
        public virtual DbSet<VW_IMPORT_GATEOUT_DETAIL_CTRL_ASSGN> VW_IMPORT_GATEOUT_DETAIL_CTRL_ASSGN { get; set; }
        public virtual DbSet<VW_IMPORT_GATEOUT_DETAIL_CTRL_ASSGN_001> VW_IMPORT_GATEOUT_DETAIL_CTRL_ASSGN_001 { get; set; }
        public virtual DbSet<VW_IMPORT_PERFORMA_TRANSACTION_ADDRESS_DETAIL_ASSGN> VW_IMPORT_PERFORMA_TRANSACTION_ADDRESS_DETAIL_ASSGN { get; set; }
        public virtual DbSet<VW_IMPORT_LORRYHIRE_DETAIL_CTRL_ASSGN> VW_IMPORT_LORRYHIRE_DETAIL_CTRL_ASSGN { get; set; }
        public virtual DbSet<VW_IMPORT_LORRYHIRE_DETAIL_CTRL_MOD_ASSGN> VW_IMPORT_LORRYHIRE_DETAIL_CTRL_MOD_ASSGN { get; set; }
        public virtual DbSet<VW_IMPORT_GATEOUT_CONTAINER_CBX_CHNG_ASSGN> VW_IMPORT_GATEOUT_CONTAINER_CBX_CHNG_ASSGN { get; set; }
        public virtual DbSet<VW_ACCOUNTHEADER_HSNCODE_DETAIL> VW_ACCOUNTHEADER_HSNCODE_DETAIL { get; set; }
        public virtual DbSet<VW_MANUALOPENSHEET_DETAIL_CTRL_ASSGN> VW_MANUALOPENSHEET_DETAIL_CTRL_ASSGN { get; set; }
        public virtual DbSet<VW_CARGOIN_CONTAINER_GATEINDETAILS_ASSGN> VW_CARGOIN_CONTAINER_GATEINDETAILS_ASSGN { get; set; }
        public virtual DbSet<VW_CARGOOUT_CONTAINER_GATEOUTDETAILS_ASSGN> VW_CARGOOUT_CONTAINER_GATEOUTDETAILS_ASSGN { get; set; }
        public virtual DbSet<VW_NONPNR_VEHICLETICKET_CONTAINER_CTRL_ASSGN> VW_NONPNR_VEHICLETICKET_CONTAINER_CTRL_ASSGN { get; set; }
        public virtual DbSet<VW_IMPORT_EMPTYGATEIN_CONTAINER_DEATILS_ASSGN> VW_IMPORT_EMPTYGATEIN_CONTAINER_DEATILS_ASSGN { get; set; }
        public virtual DbSet<VW_TALLYCHANAME_UPDATE_VIEW_ASSGN> VW_TALLYCHANAME_UPDATE_VIEW_ASSGN { get; set; }
        public virtual DbSet<VW_OPENSHEET_SEAL_DETAIL_CTRL_ASSGN> VW_OPENSHEET_SEAL_DETAIL_CTRL_ASSGN { get; set; }
        public virtual DbSet<VW_VEHICLETICKET_IMPORT_CONTAINER_CTRL_ASSGN> VW_VEHICLETICKET_IMPORT_CONTAINER_CTRL_ASSGN { get; set; }
        public virtual DbSet<VW_OPENSHEET_DETAIL_CTRL_ASSGN> VW_OPENSHEET_DETAIL_CTRL_ASSGN { get; set; }
    
        public virtual ObjectResult<pr_SearchBillOfEntry_Result> pr_SearchBillOfEntry(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pCompyid)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pCompyidParameter = pCompyid.HasValue ?
                new ObjectParameter("PCompyid", pCompyid) :
                new ObjectParameter("PCompyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchBillOfEntry_Result>("pr_SearchBillOfEntry", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter, pCompyidParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_RemoteGateIn_Result> pr_Search_Import_RemoteGateIn(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_RemoteGateIn_Result>("pr_Search_Import_RemoteGateIn", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_RemoteGateInTransfer_Result> pr_Search_Import_RemoteGateInTransfer(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_RemoteGateInTransfer_Result>("pr_Search_Import_RemoteGateInTransfer", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount);
        }
    
        public virtual ObjectResult<PR_DORDER_IGMNO_BOE_NO_CTRL_ASSGN_E001_Result> PR_DORDER_IGMNO_BOE_NO_CTRL_ASSGN_E001(string pIGMNO, string pGPLNO)
        {
            var pIGMNOParameter = pIGMNO != null ?
                new ObjectParameter("PIGMNO", pIGMNO) :
                new ObjectParameter("PIGMNO", typeof(string));
    
            var pGPLNOParameter = pGPLNO != null ?
                new ObjectParameter("PGPLNO", pGPLNO) :
                new ObjectParameter("PGPLNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_DORDER_IGMNO_BOE_NO_CTRL_ASSGN_E001_Result>("PR_DORDER_IGMNO_BOE_NO_CTRL_ASSGN_E001", pIGMNOParameter, pGPLNOParameter);
        }
    
        public virtual ObjectResult<pr_Search_DeliveryOrder_Result> pr_Search_DeliveryOrder(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_DeliveryOrder_Result>("pr_Search_DeliveryOrder", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pSDateParameter, pEDateParameter);
        }
    
        public virtual ObjectResult<PR_DORDER_IGMNO_BILLENTRY_WISE_CONTAINER_FLX_ASSGN_Result> PR_DORDER_IGMNO_BILLENTRY_WISE_CONTAINER_FLX_ASSGN(string pIGMNO, string pGPLNO)
        {
            var pIGMNOParameter = pIGMNO != null ?
                new ObjectParameter("PIGMNO", pIGMNO) :
                new ObjectParameter("PIGMNO", typeof(string));
    
            var pGPLNOParameter = pGPLNO != null ?
                new ObjectParameter("PGPLNO", pGPLNO) :
                new ObjectParameter("PGPLNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_DORDER_IGMNO_BILLENTRY_WISE_CONTAINER_FLX_ASSGN_Result>("PR_DORDER_IGMNO_BILLENTRY_WISE_CONTAINER_FLX_ASSGN", pIGMNOParameter, pGPLNOParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_GateOut_Result> pr_Search_Import_GateOut(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE, Nullable<int> pCOMPYID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_GateOut_Result>("pr_Search_Import_GateOut", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDATEParameter, pEDATEParameter, pCOMPYIDParameter);
        }
    
        public virtual ObjectResult<pr_SearchImportLorryHire_Result> pr_SearchImportLorryHire(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE, Nullable<int> pCOMPYID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchImportLorryHire_Result>("pr_SearchImportLorryHire", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDATEParameter, pEDATEParameter, pCOMPYIDParameter);
        }
    
        public virtual ObjectResult<pr_Import_Manual_Invoice_Ctrl_Flx_Assgn_Result> pr_Import_Manual_Invoice_Ctrl_Flx_Assgn(Nullable<int> pTRANMID)
        {
            var pTRANMIDParameter = pTRANMID.HasValue ?
                new ObjectParameter("PTRANMID", pTRANMID) :
                new ObjectParameter("PTRANMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Import_Manual_Invoice_Ctrl_Flx_Assgn_Result>("pr_Import_Manual_Invoice_Ctrl_Flx_Assgn", pTRANMIDParameter);
        }
    
        public virtual ObjectResult<pr_SearchManualOpenSheetGridAssgn_Result> pr_SearchManualOpenSheetGridAssgn(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pCompyid, Nullable<int> fcltype)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pCompyidParameter = pCompyid.HasValue ?
                new ObjectParameter("PCompyid", pCompyid) :
                new ObjectParameter("PCompyid", typeof(int));
    
            var fcltypeParameter = fcltype.HasValue ?
                new ObjectParameter("fcltype", fcltype) :
                new ObjectParameter("fcltype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchManualOpenSheetGridAssgn_Result>("pr_SearchManualOpenSheetGridAssgn", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter, pCompyidParameter, fcltypeParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_Performa_Invoice_Result> pr_Search_Import_Performa_Invoice(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<int> pTRANBTYPE, Nullable<int> pREGSTRID, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pTRANBTYPEParameter = pTRANBTYPE.HasValue ?
                new ObjectParameter("PTRANBTYPE", pTRANBTYPE) :
                new ObjectParameter("PTRANBTYPE", typeof(int));
    
            var pREGSTRIDParameter = pREGSTRID.HasValue ?
                new ObjectParameter("PREGSTRID", pREGSTRID) :
                new ObjectParameter("PREGSTRID", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_Performa_Invoice_Result>("pr_Search_Import_Performa_Invoice", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pTRANBTYPEParameter, pREGSTRIDParameter, pSDateParameter, pEDateParameter);
        }
    
        public virtual ObjectResult<pr_Performa_Invoice_Print_Customer_Detail_Assgn_Result> pr_Performa_Invoice_Print_Customer_Detail_Assgn(Nullable<int> pTranMID)
        {
            var pTranMIDParameter = pTranMID.HasValue ?
                new ObjectParameter("PTranMID", pTranMID) :
                new ObjectParameter("PTranMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Performa_Invoice_Print_Customer_Detail_Assgn_Result>("pr_Performa_Invoice_Print_Customer_Detail_Assgn", pTranMIDParameter);
        }
    
        public virtual ObjectResult<pr_Import_DO_Invoice_IGMNO_Grid_Assgn_Result> pr_Import_DO_Invoice_IGMNO_Grid_Assgn(Nullable<int> pDONO)
        {
            var pDONOParameter = pDONO.HasValue ?
                new ObjectParameter("PDONO", pDONO) :
                new ObjectParameter("PDONO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Import_DO_Invoice_IGMNO_Grid_Assgn_Result>("pr_Import_DO_Invoice_IGMNO_Grid_Assgn", pDONOParameter);
        }
    
        public virtual ObjectResult<pr_Import_Container_Stock_Assgn_Result> pr_Import_Container_Stock_Assgn(Nullable<System.DateTime> pSDATE)
        {
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Import_Container_Stock_Assgn_Result>("pr_Import_Container_Stock_Assgn", pSDATEParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_TruckOut_Result> pr_Search_Import_TruckOut(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE, Nullable<int> pCOMPYID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_TruckOut_Result>("pr_Search_Import_TruckOut", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDATEParameter, pEDATEParameter, pCOMPYIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_TruckIn_Result> pr_Search_Import_TruckIn(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pCOMPYID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_TruckIn_Result>("pr_Search_Import_TruckIn", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter, pCOMPYIDParameter);
        }
    
        public virtual ObjectResult<pr_Import_Performa_Invoice_IGMNO_Grid_Assgn_Result> pr_Import_Performa_Invoice_IGMNO_Grid_Assgn(string pIGMNO, string pLNO, Nullable<int> pTRANMID)
        {
            var pIGMNOParameter = pIGMNO != null ?
                new ObjectParameter("PIGMNO", pIGMNO) :
                new ObjectParameter("PIGMNO", typeof(string));
    
            var pLNOParameter = pLNO != null ?
                new ObjectParameter("PLNO", pLNO) :
                new ObjectParameter("PLNO", typeof(string));
    
            var pTRANMIDParameter = pTRANMID.HasValue ?
                new ObjectParameter("PTRANMID", pTRANMID) :
                new ObjectParameter("PTRANMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Import_Performa_Invoice_IGMNO_Grid_Assgn_Result>("pr_Import_Performa_Invoice_IGMNO_Grid_Assgn", pIGMNOParameter, pLNOParameter, pTRANMIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_Invoice_Result> pr_Search_Import_Invoice(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<int> pTRANBTYPE, Nullable<int> pREGSTRID, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pTRANBTYPEParameter = pTRANBTYPE.HasValue ?
                new ObjectParameter("PTRANBTYPE", pTRANBTYPE) :
                new ObjectParameter("PTRANBTYPE", typeof(int));
    
            var pREGSTRIDParameter = pREGSTRID.HasValue ?
                new ObjectParameter("PREGSTRID", pREGSTRID) :
                new ObjectParameter("PREGSTRID", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_Invoice_Result>("pr_Search_Import_Invoice", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pTRANBTYPEParameter, pREGSTRIDParameter, pSDateParameter, pEDateParameter);
        }
    
        public virtual ObjectResult<pr_Search_ImportManualBill_Result> pr_Search_ImportManualBill(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<int> pREGSTRID, Nullable<int> pTRANBTYPE, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pREGSTRIDParameter = pREGSTRID.HasValue ?
                new ObjectParameter("PREGSTRID", pREGSTRID) :
                new ObjectParameter("PREGSTRID", typeof(int));
    
            var pTRANBTYPEParameter = pTRANBTYPE.HasValue ?
                new ObjectParameter("PTRANBTYPE", pTRANBTYPE) :
                new ObjectParameter("PTRANBTYPE", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_ImportManualBill_Result>("pr_Search_ImportManualBill", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pREGSTRIDParameter, pTRANBTYPEParameter, pSDateParameter, pEDateParameter);
        }
    
        public virtual ObjectResult<pr_Get_Import_Slab_Narration_Detail_Result> pr_Get_Import_Slab_Narration_Detail(Nullable<int> pTranMID)
        {
            var pTranMIDParameter = pTranMID.HasValue ?
                new ObjectParameter("PTranMID", pTranMID) :
                new ObjectParameter("PTranMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Get_Import_Slab_Narration_Detail_Result>("pr_Get_Import_Slab_Narration_Detail", pTranMIDParameter);
        }
    
        public virtual ObjectResult<SP_MANUALOPENSHEET_CONTAINER_FLX_ASSGN_Result> SP_MANUALOPENSHEET_CONTAINER_FLX_ASSGN(string pIGMNO, string pGPLNO)
        {
            var pIGMNOParameter = pIGMNO != null ?
                new ObjectParameter("PIGMNO", pIGMNO) :
                new ObjectParameter("PIGMNO", typeof(string));
    
            var pGPLNOParameter = pGPLNO != null ?
                new ObjectParameter("PGPLNO", pGPLNO) :
                new ObjectParameter("PGPLNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MANUALOPENSHEET_CONTAINER_FLX_ASSGN_Result>("SP_MANUALOPENSHEET_CONTAINER_FLX_ASSGN", pIGMNOParameter, pGPLNOParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_CargoIn_Result> pr_Search_Import_CargoIn(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pCOMPYID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_CargoIn_Result>("pr_Search_Import_CargoIn", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter, pCOMPYIDParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_CargoOut_Result> pr_Search_Import_CargoOut(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDATE, Nullable<System.DateTime> pEDATE, Nullable<int> pCOMPYID)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDATEParameter = pSDATE.HasValue ?
                new ObjectParameter("PSDATE", pSDATE) :
                new ObjectParameter("PSDATE", typeof(System.DateTime));
    
            var pEDATEParameter = pEDATE.HasValue ?
                new ObjectParameter("PEDATE", pEDATE) :
                new ObjectParameter("PEDATE", typeof(System.DateTime));
    
            var pCOMPYIDParameter = pCOMPYID.HasValue ?
                new ObjectParameter("PCOMPYID", pCOMPYID) :
                new ObjectParameter("PCOMPYID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_CargoOut_Result>("pr_Search_Import_CargoOut", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDATEParameter, pEDATEParameter, pCOMPYIDParameter);
        }
    
        public virtual ObjectResult<PR_IMPORT_REMOTEGATEINCONTAINER_DETAILS_Result> PR_IMPORT_REMOTEGATEINCONTAINER_DETAILS(Nullable<System.DateTime> pFDT, Nullable<System.DateTime> pTDT, Nullable<int> pSDPTID)
        {
            var pFDTParameter = pFDT.HasValue ?
                new ObjectParameter("PFDT", pFDT) :
                new ObjectParameter("PFDT", typeof(System.DateTime));
    
            var pTDTParameter = pTDT.HasValue ?
                new ObjectParameter("PTDT", pTDT) :
                new ObjectParameter("PTDT", typeof(System.DateTime));
    
            var pSDPTIDParameter = pSDPTID.HasValue ?
                new ObjectParameter("PSDPTID", pSDPTID) :
                new ObjectParameter("PSDPTID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_IMPORT_REMOTEGATEINCONTAINER_DETAILS_Result>("PR_IMPORT_REMOTEGATEINCONTAINER_DETAILS", pFDTParameter, pTDTParameter, pSDPTIDParameter);
        }
    
        public virtual ObjectResult<PR_IMPORT_LOADESTUFFTOTCONTAINER_DETAILS_Result> PR_IMPORT_LOADESTUFFTOTCONTAINER_DETAILS(Nullable<System.DateTime> pFDT, Nullable<System.DateTime> pTDT, Nullable<int> pSDPTID)
        {
            var pFDTParameter = pFDT.HasValue ?
                new ObjectParameter("PFDT", pFDT) :
                new ObjectParameter("PFDT", typeof(System.DateTime));
    
            var pTDTParameter = pTDT.HasValue ?
                new ObjectParameter("PTDT", pTDT) :
                new ObjectParameter("PTDT", typeof(System.DateTime));
    
            var pSDPTIDParameter = pSDPTID.HasValue ?
                new ObjectParameter("PSDPTID", pSDPTID) :
                new ObjectParameter("PSDPTID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_IMPORT_LOADESTUFFTOTCONTAINER_DETAILS_Result>("PR_IMPORT_LOADESTUFFTOTCONTAINER_DETAILS", pFDTParameter, pTDTParameter, pSDPTIDParameter);
        }
    
        public virtual ObjectResult<pr_Import_EmptyGatein_Detail_Assgn_Result> pr_Import_EmptyGatein_Detail_Assgn(string pCONTNRNO)
        {
            var pCONTNRNOParameter = pCONTNRNO != null ?
                new ObjectParameter("PCONTNRNO", pCONTNRNO) :
                new ObjectParameter("PCONTNRNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Import_EmptyGatein_Detail_Assgn_Result>("pr_Import_EmptyGatein_Detail_Assgn", pCONTNRNOParameter);
        }
    
        public virtual ObjectResult<PR_IMPORT_AUTHORIZATION_DETAIL_CTRL_ASSGN_Result> PR_IMPORT_AUTHORIZATION_DETAIL_CTRL_ASSGN(Nullable<int> pASLMID)
        {
            var pASLMIDParameter = pASLMID.HasValue ?
                new ObjectParameter("PASLMID", pASLMID) :
                new ObjectParameter("PASLMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_IMPORT_AUTHORIZATION_DETAIL_CTRL_ASSGN_Result>("PR_IMPORT_AUTHORIZATION_DETAIL_CTRL_ASSGN", pASLMIDParameter);
        }
    
        public virtual ObjectResult<pr_UPDATAE_SSRCHARGES_CONTAINERNo_Result> pr_UPDATAE_SSRCHARGES_CONTAINERNo(string filterTerm)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_UPDATAE_SSRCHARGES_CONTAINERNo_Result>("pr_UPDATAE_SSRCHARGES_CONTAINERNo", filterTermParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_GateInGridAssgn_Result> pr_Search_Import_GateInGridAssgn(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pCompyid)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pCompyidParameter = pCompyid.HasValue ?
                new ObjectParameter("PCompyid", pCompyid) :
                new ObjectParameter("PCompyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_GateInGridAssgn_Result>("pr_Search_Import_GateInGridAssgn", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter, pCompyidParameter);
        }
    
        public virtual ObjectResult<pr_UPDATAE_CONTAINERNo_Result> pr_UPDATAE_CONTAINERNo(string filterTerm)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_UPDATAE_CONTAINERNo_Result>("pr_UPDATAE_CONTAINERNo", filterTermParameter);
        }
    
        public virtual ObjectResult<PR_IMPORT_GATEIN_CONTAINER_CHK_ASSGN_Result> PR_IMPORT_GATEIN_CONTAINER_CHK_ASSGN(string pCONTNRNO)
        {
            var pCONTNRNOParameter = pCONTNRNO != null ?
                new ObjectParameter("PCONTNRNO", pCONTNRNO) :
                new ObjectParameter("PCONTNRNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_IMPORT_GATEIN_CONTAINER_CHK_ASSGN_Result>("PR_IMPORT_GATEIN_CONTAINER_CHK_ASSGN", pCONTNRNOParameter);
        }
    
        public virtual ObjectResult<pr_BS_Import_Invoice_No_Wise_Grid_Pulses_Assgn_Result> pr_BS_Import_Invoice_No_Wise_Grid_Pulses_Assgn(string pSBILLNO, Nullable<int> pTRANMID, Nullable<int> pTRANBTYPE)
        {
            var pSBILLNOParameter = pSBILLNO != null ?
                new ObjectParameter("PSBILLNO", pSBILLNO) :
                new ObjectParameter("PSBILLNO", typeof(string));
    
            var pTRANMIDParameter = pTRANMID.HasValue ?
                new ObjectParameter("PTRANMID", pTRANMID) :
                new ObjectParameter("PTRANMID", typeof(int));
    
            var pTRANBTYPEParameter = pTRANBTYPE.HasValue ?
                new ObjectParameter("PTRANBTYPE", pTRANBTYPE) :
                new ObjectParameter("PTRANBTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_BS_Import_Invoice_No_Wise_Grid_Pulses_Assgn_Result>("pr_BS_Import_Invoice_No_Wise_Grid_Pulses_Assgn", pSBILLNOParameter, pTRANMIDParameter, pTRANBTYPEParameter);
        }
    
        public virtual ObjectResult<pr_SearchOpenSheetGridAssgn_Result> pr_SearchOpenSheetGridAssgn(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pCompyid, string pUsrname, Nullable<int> fcltype)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pCompyidParameter = pCompyid.HasValue ?
                new ObjectParameter("PCompyid", pCompyid) :
                new ObjectParameter("PCompyid", typeof(int));
    
            var pUsrnameParameter = pUsrname != null ?
                new ObjectParameter("PUsrname", pUsrname) :
                new ObjectParameter("PUsrname", typeof(string));
    
            var fcltypeParameter = fcltype.HasValue ?
                new ObjectParameter("fcltype", fcltype) :
                new ObjectParameter("fcltype", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SearchOpenSheetGridAssgn_Result>("pr_SearchOpenSheetGridAssgn", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter, pCompyidParameter, pUsrnameParameter, fcltypeParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_DeStuffSlip_Result> pr_Search_Import_DeStuffSlip(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_DeStuffSlip_Result>("pr_Search_Import_DeStuffSlip", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pSDateParameter, pEDateParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_LoadSlip_Result> pr_Search_Import_LoadSlip(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_LoadSlip_Result>("pr_Search_Import_LoadSlip", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pSDateParameter, pEDateParameter);
        }
    
        public virtual ObjectResult<PR_ES_GATEIN_CONTAINER_CHK_ASSGN_001_Result> PR_ES_GATEIN_CONTAINER_CHK_ASSGN_001(string pCONTNRNO)
        {
            var pCONTNRNOParameter = pCONTNRNO != null ?
                new ObjectParameter("PCONTNRNO", pCONTNRNO) :
                new ObjectParameter("PCONTNRNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_ES_GATEIN_CONTAINER_CHK_ASSGN_001_Result>("PR_ES_GATEIN_CONTAINER_CHK_ASSGN_001", pCONTNRNOParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PR_ES_GATEIN_CONTAINER_CHK_ASSGN(string pCONTNRNO)
        {
            var pCONTNRNOParameter = pCONTNRNO != null ?
                new ObjectParameter("PCONTNRNO", pCONTNRNO) :
                new ObjectParameter("PCONTNRNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PR_ES_GATEIN_CONTAINER_CHK_ASSGN", pCONTNRNOParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_VehicleTicket_Result> pr_Search_Import_VehicleTicket(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pVTTYPE)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pVTTYPEParameter = pVTTYPE.HasValue ?
                new ObjectParameter("PVTTYPE", pVTTYPE) :
                new ObjectParameter("PVTTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_VehicleTicket_Result>("pr_Search_Import_VehicleTicket", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pSDateParameter, pEDateParameter, pVTTYPEParameter);
        }
    
        public virtual ObjectResult<pr_Search_Import_GateInBlock_Result> pr_Search_Import_GateInBlock(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate, Nullable<int> pCompyid)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            var pCompyidParameter = pCompyid.HasValue ?
                new ObjectParameter("PCompyid", pCompyid) :
                new ObjectParameter("PCompyid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Import_GateInBlock_Result>("pr_Search_Import_GateInBlock", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pSDateParameter, pEDateParameter, pCompyidParameter);
        }
    
        public virtual ObjectResult<pr_SSRCharge_Container_Detail_Assgn_Result> pr_SSRCharge_Container_Detail_Assgn(string pContnrNo)
        {
            var pContnrNoParameter = pContnrNo != null ?
                new ObjectParameter("PContnrNo", pContnrNo) :
                new ObjectParameter("PContnrNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_SSRCharge_Container_Detail_Assgn_Result>("pr_SSRCharge_Container_Detail_Assgn", pContnrNoParameter);
        }
    
        public virtual ObjectResult<SP_OPENSHEET_CONTAINER_FLX_ASSGN_Result> SP_OPENSHEET_CONTAINER_FLX_ASSGN(string pIGMNO, string pGPLNO)
        {
            var pIGMNOParameter = pIGMNO != null ?
                new ObjectParameter("PIGMNO", pIGMNO) :
                new ObjectParameter("PIGMNO", typeof(string));
    
            var pGPLNOParameter = pGPLNO != null ?
                new ObjectParameter("PGPLNO", pGPLNO) :
                new ObjectParameter("PGPLNO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OPENSHEET_CONTAINER_FLX_ASSGN_Result>("SP_OPENSHEET_CONTAINER_FLX_ASSGN", pIGMNOParameter, pGPLNOParameter);
        }
    
        public virtual ObjectResult<pr_Import_Invoice_IGMNO_Grid_Assgn_Result> pr_Import_Invoice_IGMNO_Grid_Assgn(string pIGMNO, string pLNO, Nullable<int> pTRANMID, Nullable<int> pTRANBTYPE)
        {
            var pIGMNOParameter = pIGMNO != null ?
                new ObjectParameter("PIGMNO", pIGMNO) :
                new ObjectParameter("PIGMNO", typeof(string));
    
            var pLNOParameter = pLNO != null ?
                new ObjectParameter("PLNO", pLNO) :
                new ObjectParameter("PLNO", typeof(string));
    
            var pTRANMIDParameter = pTRANMID.HasValue ?
                new ObjectParameter("PTRANMID", pTRANMID) :
                new ObjectParameter("PTRANMID", typeof(int));
    
            var pTRANBTYPEParameter = pTRANBTYPE.HasValue ?
                new ObjectParameter("PTRANBTYPE", pTRANBTYPE) :
                new ObjectParameter("PTRANBTYPE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Import_Invoice_IGMNO_Grid_Assgn_Result>("pr_Import_Invoice_IGMNO_Grid_Assgn", pIGMNOParameter, pLNOParameter, pTRANMIDParameter, pTRANBTYPEParameter);
        }
    }
}
