//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SCFS_ERP_SPBWEntities : DbContext
    {
        public SCFS_ERP_SPBWEntities()
            : base("name=SCFS_ERP_SPBWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<pr_Search_Bond_Invoice_Result> pr_Search_Bond_Invoice(string filterTerm, Nullable<int> sortIndex, string sortDirection, Nullable<int> startRowNum, Nullable<int> endRowNum, ObjectParameter totalRowsCount, ObjectParameter filteredRowsCount, Nullable<int> pCompyId, Nullable<int> pTRANBTYPE, Nullable<int> pREGSTRID, Nullable<System.DateTime> pSDate, Nullable<System.DateTime> pEDate)
        {
            var filterTermParameter = filterTerm != null ?
                new ObjectParameter("FilterTerm", filterTerm) :
                new ObjectParameter("FilterTerm", typeof(string));
    
            var sortIndexParameter = sortIndex.HasValue ?
                new ObjectParameter("SortIndex", sortIndex) :
                new ObjectParameter("SortIndex", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var startRowNumParameter = startRowNum.HasValue ?
                new ObjectParameter("StartRowNum", startRowNum) :
                new ObjectParameter("StartRowNum", typeof(int));
    
            var endRowNumParameter = endRowNum.HasValue ?
                new ObjectParameter("EndRowNum", endRowNum) :
                new ObjectParameter("EndRowNum", typeof(int));
    
            var pCompyIdParameter = pCompyId.HasValue ?
                new ObjectParameter("PCompyId", pCompyId) :
                new ObjectParameter("PCompyId", typeof(int));
    
            var pTRANBTYPEParameter = pTRANBTYPE.HasValue ?
                new ObjectParameter("PTRANBTYPE", pTRANBTYPE) :
                new ObjectParameter("PTRANBTYPE", typeof(int));
    
            var pREGSTRIDParameter = pREGSTRID.HasValue ?
                new ObjectParameter("PREGSTRID", pREGSTRID) :
                new ObjectParameter("PREGSTRID", typeof(int));
    
            var pSDateParameter = pSDate.HasValue ?
                new ObjectParameter("PSDate", pSDate) :
                new ObjectParameter("PSDate", typeof(System.DateTime));
    
            var pEDateParameter = pEDate.HasValue ?
                new ObjectParameter("PEDate", pEDate) :
                new ObjectParameter("PEDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_Search_Bond_Invoice_Result>("pr_Search_Bond_Invoice", filterTermParameter, sortIndexParameter, sortDirectionParameter, startRowNumParameter, endRowNumParameter, totalRowsCount, filteredRowsCount, pCompyIdParameter, pTRANBTYPEParameter, pREGSTRIDParameter, pSDateParameter, pEDateParameter);
        }
    
        public virtual ObjectResult<Z_pr_ExBond_NOP_Assgn_Result> Z_pr_ExBond_NOP_Assgn(Nullable<int> pBNDID, Nullable<System.DateTime> pEBNDEDATE)
        {
            var pBNDIDParameter = pBNDID.HasValue ?
                new ObjectParameter("PBNDID", pBNDID) :
                new ObjectParameter("PBNDID", typeof(int));
    
            var pEBNDEDATEParameter = pEBNDEDATE.HasValue ?
                new ObjectParameter("PEBNDEDATE", pEBNDEDATE) :
                new ObjectParameter("PEBNDEDATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Z_pr_ExBond_NOP_Assgn_Result>("Z_pr_ExBond_NOP_Assgn", pBNDIDParameter, pEBNDEDATEParameter);
        }
    }
}
