//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ACCOUNTHEADER_HSNCODE_DETAIL
    {
        public decimal AIGSTEXPRN { get; set; }
        public string HSNCODE { get; set; }
        public int ACHEADID { get; set; }
        public int HSNID { get; set; }
        public string ACHEADDESC { get; set; }
    }
}
