//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN
    {
        public int GIDID { get; set; }
        public System.DateTime GIDATE { get; set; }
        public string STMRNAME { get; set; }
        public string IMPRTNAME { get; set; }
        public string VOYNO { get; set; }
        public string VSLNAME { get; set; }
        public string GIDNO { get; set; }
        public int GINO { get; set; }
        public string CONTNRNO { get; set; }
        public string IGMNO { get; set; }
        public string GPLNO { get; set; }
        public string CONTNRSDESC { get; set; }
        public string BOENO { get; set; }
        public Nullable<System.DateTime> BOEDATE { get; set; }
        public string LPSEALNO { get; set; }
        public string CSEALNO { get; set; }
        public int SDPTID { get; set; }
        public Nullable<int> ASLDID { get; set; }
    }
}
