//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_BOND_RATECARDMASTER_FLX_ASSGN
    {
        public int TARIFFMID { get; set; }
        public int SLABTID { get; set; }
        public short CHRGETYPE { get; set; }
        public int CHAID { get; set; }
        public int CONTNRSID { get; set; }
        public int SLABMID { get; set; }
        public int COMPYID { get; set; }
        public string CATEDNAME { get; set; }
        public string CONTNRSCODE { get; set; }
        public short YRDTYPE { get; set; }
        public short SDTYPE { get; set; }
        public short HTYPE { get; set; }
        public short WTYPE { get; set; }
        public Nullable<int> PERIODTID { get; set; }
        public decimal SLABMIN { get; set; }
        public decimal SLABMAX { get; set; }
        public decimal SLABAMT { get; set; }
        public System.DateTime SLABMDATE { get; set; }
        public int SDPTTYPEID { get; set; }
        public int PRDTGID { get; set; }
        public Nullable<short> HANDTYPE { get; set; }
    }
}
