//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_BOND_SLABTYPE_HSN_DETAIL_ASSGN
    {
        public int SLABTID { get; set; }
        public string HSNCODE { get; set; }
        public decimal CGSTEXPRN { get; set; }
        public decimal SGSTEXPRN { get; set; }
        public decimal IGSTEXPRN { get; set; }
        public decimal ACGSTEXPRN { get; set; }
        public decimal ASGSTEXPRN { get; set; }
        public decimal AIGSTEXPRN { get; set; }
    }
}
