//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CARGOIN_CONTAINER_GATEINDETAILS_ASSGN
    {
        public string CONTNRSDESC { get; set; }
        public int GIDID { get; set; }
        public string CONTNRNO { get; set; }
        public Nullable<int> CGIDID { get; set; }
        public string GIDNO { get; set; }
        public System.DateTime GIDATE { get; set; }
        public System.DateTime VTDATE { get; set; }
        public string IMPRTNAME { get; set; }
        public string STMRNAME { get; set; }
        public string GPLNO { get; set; }
        public string VHLNO { get; set; }
        public string PRDTGDESC { get; set; }
        public string PRDTDESC { get; set; }
        public Nullable<decimal> GPWGHT { get; set; }
        public Nullable<decimal> BGOQTY { get; set; }
    }
}
