//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DELIVERY_ORDER_DETAIL_GRID_ASSGN
    {
        public int DOMID { get; set; }
        public int DODID { get; set; }
        public string DODREFNO { get; set; }
        public string IGMNO { get; set; }
        public string GPLNO { get; set; }
        public string CONTNRNO { get; set; }
        public string CONTNRSDESC { get; set; }
        public Nullable<System.DateTime> DOIDATE { get; set; }
        public System.DateTime GIDATE { get; set; }
        public string VSLNAME { get; set; }
        public string VOYNO { get; set; }
        public string PRDTDESC { get; set; }
        public Nullable<decimal> GPWGHT { get; set; }
        public int GIDID { get; set; }
        public int BILLEDID { get; set; }
        public string STMRNAME { get; set; }
        public string IMPRTNAME { get; set; }
        public string DPAIDNO { get; set; }
        public Nullable<decimal> DPAIDAMT { get; set; }
        public int BILLEMID { get; set; }
    }
}
