//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EXPORT_SHIPPINGBILL_NO_CTRL_ASSGN
    {
        public string ESBMDNO { get; set; }
        public int ESBMID { get; set; }
        public Nullable<int> SBDID { get; set; }
    }
}
