//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EXPORT_INVOICE_STUFFING_DETAIL_CTRL_ASSGN
    {
        public string EXPRTNAME { get; set; }
        public string CHANAME { get; set; }
        public int CHAID { get; set; }
        public int EXPRTID { get; set; }
        public int STFMID { get; set; }
        public Nullable<int> STFTID { get; set; }
        public int SLABTID { get; set; }
        public short STATETYPE { get; set; }
    }
}
