//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EXPORT_INVOICE_OPERATION_WISE_TARIFF_ASSGN
    {
        public int TGID { get; set; }
        public int TARIFFMID { get; set; }
        public string TARIFFMDESC { get; set; }
    }
}
