//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EXPORT_STUFFING_BILL_PRINT_ADDRESS_DETAIL_ASSGN
    {
        public int TRANMID { get; set; }
        public string TRANCSNAME { get; set; }
        public string TRANIMPADDR1 { get; set; }
        public string TRANIMPADDR2 { get; set; }
        public string TRANIMPADDR3 { get; set; }
        public string TRANIMPADDR4 { get; set; }
        public string TRANGSTNO { get; set; }
        public int TRANREFID { get; set; }
        public Nullable<int> CATEAID { get; set; }
    }
}
