//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EXPORT_ASL_DETAIL_CTRL_ASSGN_MODS
    {
        public int ASLDID { get; set; }
        public int ASLMID { get; set; }
        public int OSDID { get; set; }
        public Nullable<int> LCATEID { get; set; }
        public Nullable<short> ASLDTYPE { get; set; }
        public Nullable<short> ASLLTYPE { get; set; }
        public Nullable<short> ASLOTYPE { get; set; }
        public string VHLNO { get; set; }
        public string DRVNAME { get; set; }
        public Nullable<short> DISPSTATUS { get; set; }
        public string ASLFDESC { get; set; }
        public string ASLTDESC { get; set; }
        public Nullable<System.DateTime> PRCSDATE { get; set; }
        public Nullable<System.DateTime> ASLDODATE { get; set; }
        public Nullable<int> STFDID { get; set; }
        public string CSEALNO { get; set; }
        public string ASEALNO { get; set; }
        public string STFDSBNO { get; set; }
        public string STFDSBDNO { get; set; }
        public string CONTNRNO { get; set; }
        public string CONTNRSDESC { get; set; }
        public string CHANAME { get; set; }
        public string EXPRTNAME { get; set; }
        public string PRDTDESC { get; set; }
        public System.DateTime GIDATE { get; set; }
        public int GIDID { get; set; }
        public int SLTID { get; set; }
        public string SLTDESC { get; set; }
    }
}
