//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EXPORT_ASL_STUFF_CONTAINER_CBX_ASSGN_NEW
    {
        public string CONTNRNO { get; set; }
        public int STFDID { get; set; }
        public int GIDID { get; set; }
    }
}
