//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ESEAL_GATEOUT_MOD_ASSGN
    {
        public int GODID { get; set; }
        public int COMPYID { get; set; }
        public int SDPTID { get; set; }
        public int REGSTRID { get; set; }
        public System.DateTime GODATE { get; set; }
        public System.DateTime GOTIME { get; set; }
        public int GONO { get; set; }
        public string GODNO { get; set; }
        public Nullable<int> GIDID { get; set; }
        public Nullable<int> TRANDID { get; set; }
        public string VHLNO { get; set; }
        public string DRVNAME { get; set; }
        public string CHASNAME { get; set; }
        public Nullable<short> GOBTYPE { get; set; }
        public int CHAID { get; set; }
        public string LSEALNO { get; set; }
        public int STMRID { get; set; }
        public string STMRNAME { get; set; }
        public Nullable<int> EXPRTRID { get; set; }
        public string EXPRTRNAME { get; set; }
        public string SSEALNO { get; set; }
        public string CUSRID { get; set; }
        public string LMUSRID { get; set; }
        public Nullable<short> DISPSTATUS { get; set; }
        public Nullable<System.DateTime> PRCSDATE { get; set; }
        public Nullable<decimal> GOQTY { get; set; }
        public Nullable<int> OTDID { get; set; }
        public string OTDNO { get; set; }
        public Nullable<int> CONTNRFID { get; set; }
        public Nullable<int> BOOKID { get; set; }
        public string GOPLCNAME { get; set; }
        public string GOBKGNO { get; set; }
        public string GOEGMNO { get; set; }
        public Nullable<int> OVSLID { get; set; }
        public string OVSLNAME { get; set; }
        public string OVOYNO { get; set; }
        public string GOREMRKS { get; set; }
        public Nullable<System.DateTime> EHIDATE { get; set; }
        public Nullable<System.DateTime> EHITIME { get; set; }
        public string GOTRNSPRTNAME { get; set; }
        public Nullable<short> GOTTYPE { get; set; }
        public Nullable<short> GOOTYPE { get; set; }
        public Nullable<short> GOCTYPE { get; set; }
        public string CONTNRNO { get; set; }
        public string CONTNRSDESC { get; set; }
        public int VTNO { get; set; }
        public int VTTYPE { get; set; }
        public string Port { get; set; }
        public string DRVMBLNO { get; set; }
        public string DRVLCNO { get; set; }
        public string GIDATE { get; set; }
        public string CHANAME { get; set; }
        public string ASEALNO { get; set; }
        public string VTSSEALNO { get; set; }
        public Nullable<int> GPSTYPE { get; set; }
    }
}
