//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ESEAL_GATEOUT_CONTAINER_CBX_CHNG_ASSGN
    {
        public int GIDID { get; set; }
        public string CONTNRNO { get; set; }
        public string CONTNRSDESC { get; set; }
        public int VTNO { get; set; }
        public string VTDNO { get; set; }
        public Nullable<int> CHAID { get; set; }
        public string CHANAME { get; set; }
        public string DRVNAME { get; set; }
        public int STMRID { get; set; }
        public string STMRNAME { get; set; }
        public Nullable<int> EXPRTRID { get; set; }
        public string EXPRTRNAME { get; set; }
        public string CSEALNO { get; set; }
        public string VTSSEALNO { get; set; }
        public int VTTYPE { get; set; }
        public string Port { get; set; }
        public string GIDATE { get; set; }
        public string DRVMBLNO { get; set; }
        public string DRVLCNO { get; set; }
        public string GOTRNSPRTNAME { get; set; }
        public string VHLNO { get; set; }
    }
}
