//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02
    {
        public Nullable<int> Expr1 { get; set; }
        public int SLABTID { get; set; }
        public int TARIFFMID { get; set; }
        public int STMRID { get; set; }
        public short CHRGETYPE { get; set; }
        public int CONTNRSID { get; set; }
        public short SDTYPE { get; set; }
        public short YRDTYPE { get; set; }
        public short HTYPE { get; set; }
        public short WTYPE { get; set; }
        public Nullable<System.DateTime> XTRANSDATE { get; set; }
        public int SDPTTYPEID { get; set; }
    }
}
