//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN
    {
        public int OSDID { get; set; }
        public int GIDID { get; set; }
        public System.DateTime GIDATE { get; set; }
        public string CONTNRNO { get; set; }
        public string IGMNO { get; set; }
        public string GPLNO { get; set; }
        public string CONTNRSDESC { get; set; }
        public string OSMDNO { get; set; }
        public string BOENO { get; set; }
        public Nullable<System.DateTime> BOEDATE { get; set; }
        public Nullable<System.DateTime> DODATE { get; set; }
        public string LSEALNO { get; set; }
        public string SSEALNO { get; set; }
        public string OOCDATE { get; set; }
    }
}
