//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_IMPORT_EMPTYGATEIN_CONTAINER_DEATILS_ASSGN
    {
        public int GIDID { get; set; }
        public string CONTNRNO { get; set; }
        public string GIDATE { get; set; }
        public string VHLNO { get; set; }
        public int STMRID { get; set; }
        public string STMRNAME { get; set; }
        public int IMPRTID { get; set; }
        public string IMPRTNAME { get; set; }
    }
}
