//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_IMPORT_GATEOUT_DETAIL_CTRL_ASSGN
    {
        public int GIDID { get; set; }
        public string CONTNRNO { get; set; }
        public string VTDNO { get; set; }
        public int VTNO { get; set; }
        public int COMPYID { get; set; }
        public string CONTNRSDESC { get; set; }
        public string GIDATE { get; set; }
        public string VSLNAME { get; set; }
        public string VOYNO { get; set; }
        public string PRDTDESC { get; set; }
        public string IMPRTNAME { get; set; }
        public string STMRNAME { get; set; }
        public string CHANAME { get; set; }
        public int CHAID { get; set; }
        public string CFSNAME { get; set; }
        public string IGMNO { get; set; }
        public string GPLNO { get; set; }
        public string VHLNO { get; set; }
        public string DRVNAME { get; set; }
        public string LPSEALNO { get; set; }
        public string VTSSEALNO { get; set; }
        public Nullable<short> ASLMTYPE { get; set; }
        public int GODID { get; set; }
        public Nullable<int> VTSTYPE { get; set; }
        public string OOCDATE { get; set; }
    }
}
