//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_NEW_EMPTY_GATEOUT_CONTAINER_CBX_ASSGN
    {
        public int GIDID { get; set; }
        public string CONTNRNO { get; set; }
        public Nullable<int> PGIDID { get; set; }
        public string CONTNRSDESC { get; set; }
        public System.DateTime GIDATE { get; set; }
        public string STMRNAME { get; set; }
        public int CHAID { get; set; }
        public string CHANAME { get; set; }
        public string DRVNAME { get; set; }
        public string VHLNO { get; set; }
    }
}
