//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_NONPNR_GATEOUT_PRINT_ASSGN
    {
        public string COMPDNAME { get; set; }
        public string COMPADDR { get; set; }
        public int GODID { get; set; }
        public int COMPYID { get; set; }
        public int SDPTID { get; set; }
        public int REGSTRID { get; set; }
        public System.DateTime GODATE { get; set; }
        public System.DateTime GOTIME { get; set; }
        public int GONO { get; set; }
        public string GODNO { get; set; }
        public string CHANAME { get; set; }
        public string CONTNRNO { get; set; }
        public string CONTNRSDESC { get; set; }
        public string CONTNRTCODE { get; set; }
        public string IMPRTNAME { get; set; }
        public string STMRNAME { get; set; }
        public string VHLNO { get; set; }
        public Nullable<short> GOBTYPE { get; set; }
        public string GDRVNAME { get; set; }
        public string LSEALNO { get; set; }
        public string SSEALNO { get; set; }
        public string EMPNAME { get; set; }
        public string CHASNAME { get; set; }
        public string PRDTDESC { get; set; }
        public string IGMNO { get; set; }
        public string GPLNO { get; set; }
        public string KUSRID { get; set; }
        public string OPTNSTR { get; set; }
        public int RPTID { get; set; }
    }
}
