//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_NONPNR_VEHICLETICKET_CONTAINER_CTRL_ASSGN
    {
        public int GIDID { get; set; }
        public System.DateTime GIDATE { get; set; }
        public System.DateTime GITIME { get; set; }
        public string GIDNO { get; set; }
        public string CONTNRNO { get; set; }
        public string CONTNRSDESC { get; set; }
        public string GPLNO { get; set; }
        public string VSLNAME { get; set; }
        public string VOYNO { get; set; }
        public string IGMNO { get; set; }
        public string IMPRTNAME { get; set; }
        public string STMRNAME { get; set; }
        public string CHANAME { get; set; }
        public string LPSEALNO { get; set; }
        public string CSEALNO { get; set; }
        public int SLOTID { get; set; }
        public string ASLMDNO { get; set; }
        public int ASLDID { get; set; }
        public string VHLNO { get; set; }
        public string DRVNAME { get; set; }
        public string PRDTDESC { get; set; }
        public short ASLMTYPE { get; set; }
        public string BOENO { get; set; }
        public System.DateTime BOEDATE { get; set; }
        public System.DateTime ASLMDATE { get; set; }
        public System.DateTime ASLMTIME { get; set; }
        public int STMRID { get; set; }
        public int CONTNRSID { get; set; }
        public int CONTNRTID { get; set; }
    }
}
