//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_NONPNR_GATE_IN_PRINT_ASSGN
    {
        public string COMPDNAME { get; set; }
        public string COMPADDR { get; set; }
        public int GIDID { get; set; }
        public int COMPYID { get; set; }
        public int SDPTID { get; set; }
        public System.DateTime GIDATE { get; set; }
        public string GITIME { get; set; }
        public int GINO { get; set; }
        public string GIDNO { get; set; }
        public int GIVHLTYPE { get; set; }
        public string TRNSPRTNAME { get; set; }
        public string VHLNO { get; set; }
        public string DRVNAME { get; set; }
        public string GPREFNO { get; set; }
        public string IMPRTNAME { get; set; }
        public string STMRNAME { get; set; }
        public string CONTNRNO { get; set; }
        public string CONTNRSDESC { get; set; }
        public string CONTNRTCODE { get; set; }
        public string LPSEALNO { get; set; }
        public string CSEALNO { get; set; }
        public string VSLNAME { get; set; }
        public string VOYNO { get; set; }
        public string PRDTDESC { get; set; }
        public Nullable<decimal> GPWGHT { get; set; }
        public string IGMNO { get; set; }
        public string GPLNO { get; set; }
        public string KUSRID { get; set; }
        public string GIISOCODE { get; set; }
        public Nullable<int> GPSCNTYPE { get; set; }
        public Nullable<System.DateTime> IGMDATE { get; set; }
    }
}
