//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OPENSHEET_DETAIL_CTRL_ASSGN
    {
        public int OSDID { get; set; }
        public int OSMID { get; set; }
        public int BILLEDID { get; set; }
        public int BILLEMID { get; set; }
        public int GIDID { get; set; }
        public Nullable<System.DateTime> GIDATE { get; set; }
        public string LSEALNO { get; set; }
        public string SSEALNO { get; set; }
        public string CSEALNO { get; set; }
        public Nullable<short> INSPTYPE { get; set; }
        public string IMPRTNAME { get; set; }
        public string STMRNAME { get; set; }
        public string VSLNAME { get; set; }
        public string VOYNO { get; set; }
        public string PRDTGDESC { get; set; }
        public int PRDTGID { get; set; }
        public string PRDTGCODE { get; set; }
        public string PRDTDESC { get; set; }
        public string CONTNRNO { get; set; }
        public int CONTNRSID { get; set; }
        public string OSMIGMNO { get; set; }
        public string OSMLNO { get; set; }
        public string INSP_DES { get; set; }
        public string Block { get; set; }
        public Nullable<System.DateTime> BILLEMDATE { get; set; }
        public string SealNos { get; set; }
        public int GPSCNMTYPE { get; set; }
        public Nullable<int> GPSCNTYPE { get; set; }
    }
}
