//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SHUTOUT_VEHICLETICKET_CTRL_ASSGN
    {
        public System.DateTime STFMDATE { get; set; }
        public string STFMDNO { get; set; }
        public string STFMNAME { get; set; }
        public int CHAID { get; set; }
        public int STFMID { get; set; }
        public int STFCATEAID { get; set; }
        public string TRANIMPADDR1 { get; set; }
        public string TRANIMPADDR2 { get; set; }
        public string TRANIMPADDR3 { get; set; }
        public string TRANIMPADDR4 { get; set; }
        public Nullable<int> STATEID { get; set; }
        public string STFCATELOCN { get; set; }
        public string CATEAGSTNO { get; set; }
        public Nullable<decimal> STFDNOP { get; set; }
        public Nullable<int> SHUTOUTVTSTFMID { get; set; }
    }
}
