//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUFFING_ORGSBILLNO_REFNO_CBX_ASSGN
    {
        public int CHAID { get; set; }
        public int SBMID { get; set; }
        public int SBDID { get; set; }
        public string SBMDNO { get; set; }
        public string SBMDATE { get; set; }
        public string ESBMDNO { get; set; }
        public string ESBMDATE { get; set; }
        public int SBDNO { get; set; }
        public string SBDDNO { get; set; }
        public string SBDDATE { get; set; }
        public string PRDTDESC { get; set; }
        public Nullable<decimal> sbdnop { get; set; }
        public string KUSRID { get; set; }
        public Nullable<decimal> OBNOP { get; set; }
        public int GIDID { get; set; }
        public string CONTNRNO { get; set; }
        public string ESBD_SBILLNO { get; set; }
        public string ESBD_SBILLDATE { get; set; }
        public string ESBOINVNO { get; set; }
        public string ESBOINVDATE { get; set; }
        public Nullable<decimal> ESBOINVAMT { get; set; }
        public Nullable<decimal> ESBOINVFOBAMT { get; set; }
        public string ESBDDPNAME { get; set; }
        public Nullable<decimal> ESBMNOP { get; set; }
        public Nullable<decimal> BNOP { get; set; }
        public int ESBDID { get; set; }
        public int id { get; set; }
        public string sbno { get; set; }
        public int s2id { get; set; }
        public int s3id { get; set; }
        public Nullable<decimal> STFDNOP { get; set; }
    }
}
