//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUFF_GATEIN_CTRL_ASSGN
    {
        public int GIDID { get; set; }
        public int STFDID { get; set; }
        public string STFDSBNO { get; set; }
        public string STFDSBDNO { get; set; }
        public string CONTNRNO { get; set; }
        public string CONTNRSDESC { get; set; }
        public string CHANAME { get; set; }
        public string EXPRTNAME { get; set; }
        public string PRDTDESC { get; set; }
        public System.DateTime GIDATE { get; set; }
        public string DRVNAME { get; set; }
        public string LPSEALNO { get; set; }
        public string CSEALNO { get; set; }
    }
}
