//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SHIPPINGBILL_GATEINT_TRUCKNO_CBX_ASSGN
    {
        public int GIDID { get; set; }
        public Nullable<int> EXPRTID { get; set; }
        public Nullable<decimal> SBDNOP { get; set; }
        public string ESBMDNO { get; set; }
        public int ESBMID { get; set; }
    }
}
