//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN
    {
        public int CHAID { get; set; }
        public int SBMID { get; set; }
        public int SBDID { get; set; }
        public string SBMDNO { get; set; }
        public System.DateTime SBMDATE { get; set; }
        public string ESBMDNO { get; set; }
        public Nullable<System.DateTime> ESBMDATE { get; set; }
        public int SBDNO { get; set; }
        public string SBDDNO { get; set; }
        public System.DateTime SBDDATE { get; set; }
        public string PRDTDESC { get; set; }
        public Nullable<decimal> SBDNOP { get; set; }
        public string KUSRID { get; set; }
        public Nullable<decimal> BNOP { get; set; }
        public int GIDID { get; set; }
        public string CONTNRNO { get; set; }
        public string ESBD_SBILLNO { get; set; }
        public System.DateTime ESBD_SBILLDATE { get; set; }
    }
}
