//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUFFING_CHECKEXISTING_ORGSHIPPINGBILL
    {
        public int ESBMID { get; set; }
        public int SBMID { get; set; }
        public int STFMID { get; set; }
        public int GIDID { get; set; }
        public Nullable<int> ESBDID { get; set; }
    }
}
