//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TALLYCHANAME_UPDATE_VIEW_ASSGN
    {
        public Nullable<System.DateTime> OSMDATE { get; set; }
        public int OSMID { get; set; }
        public Nullable<int> CHAID { get; set; }
        public string OSMNAME { get; set; }
    }
}
