//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VEHICLETICKET_IMPORT_CONTAINER_CBX_ASSGN
    {
        public int ASLDID { get; set; }
        public Nullable<int> SDPTID { get; set; }
        public int GIDID { get; set; }
        public string IGMNO { get; set; }
        public string CONTNRNO { get; set; }
        public string GPLNO { get; set; }
    }
}
