//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scfs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VEHICLETICKET_EXPORT_CONTAINER_CTRL_ASSGN_DIRECT
    {
        public int STFDID { get; set; }
        public string STFMDNO { get; set; }
        public System.DateTime STFMDATE { get; set; }
        public string CHANAME { get; set; }
        public string EXPRTNAME { get; set; }
        public int GIDID { get; set; }
        public System.DateTime GIDATE { get; set; }
        public string CONTNRSDESC { get; set; }
        public string PRDTDESC { get; set; }
        public string SBILLNO { get; set; }
        public string SBILLDATE { get; set; }
        public string SBMDNO { get; set; }
        public string SBMDATE { get; set; }
        public int SDPTID { get; set; }
        public Nullable<int> GPSTYPE { get; set; }
        public int ASLDID { get; set; }
        public string CSEALNO { get; set; }
        public string ASEALNO { get; set; }
    }
}
