select *from PERFORMA_TRANSACTIONDETAIL  

select *from PERFORMA_TRANSACTIONMASTER 



ALTER TABLE [PERFORMA_TRANSACTIONDETAIL]
ADD [TRANDADONAMT] numeric(18,2) NULL CONSTRAINT [DF_PERFORMA_TRANSACTIONDETAIL_TRANDADONAMT]  DEFAULT (0)  

ALTER TABLE [PERFORMA_TRANSACTIONMASTER]
ADD [TRANADONAMT] numeric(18,2) NULL CONSTRAINT [DF_PERFORMA_TRANSACTIONMASTER_TRANADONAMT]  DEFAULT (0)

