

select *from CREDITNOTE_TRANSACTIONDETAIL

ALTER TABLE [CREDITNOTE_TRANSACTIONDETAIL]
ADD [TRANDHSNCODE]  varchar(25) NULL CONSTRAINT [CREDITNOTE_TRANSACTIONDETAIL_TRANDHSNCODE]  DEFAULT ('') 

update CREDITNOTE_TRANSACTIONDETAIL set TRANDHSNCODE='' where TRANDHSNCODE is null

 

