
ALTER TABLE [dbo].STUFFINGPRODUCTDETAIL DROP CONSTRAINT DF_STUFFINGPRODUCTDETAIL_LMUSRID
GO

alter table STUFFINGPRODUCTDETAIL 
alter column LMUSRID varchar(50)  null 

ALTER TABLE [dbo].STUFFINGPRODUCTDETAIL ADD  CONSTRAINT DF_STUFFINGPRODUCTDETAIL_LMUSRID  DEFAULT (('')) FOR [LMUSRID]
GO


ALTER TABLE [dbo].STUFFINGPRODUCTDETAIL DROP CONSTRAINT DF_STUFFINGPRODUCTDETAIL_CUSRID
GO

alter table STUFFINGPRODUCTDETAIL 
alter column CUSRID varchar(50)  null 

ALTER TABLE [dbo].STUFFINGPRODUCTDETAIL ADD  CONSTRAINT DF_STUFFINGPRODUCTDETAIL_CUSRID  DEFAULT (('')) FOR CUSRID
GO