
ALTER TABLE [dbo].STUFFINGMASTER DROP CONSTRAINT DF_STUFFINGMASTER1_LMUSRID
GO

alter table STUFFINGMASTER 
alter column LMUSRID varchar(50)  null 

ALTER TABLE [dbo].STUFFINGMASTER ADD  CONSTRAINT DF_STUFFINGMASTER1_LMUSRID  DEFAULT (('')) FOR [LMUSRID]
GO


ALTER TABLE [dbo].STUFFINGMASTER DROP CONSTRAINT DF_STUFFINGMASTER1_CUSRID
GO

alter table STUFFINGMASTER 
alter column CUSRID varchar(50)  null 

ALTER TABLE [dbo].STUFFINGMASTER ADD  CONSTRAINT DF_STUFFINGMASTER1_CUSRID  DEFAULT (('')) FOR CUSRID
GO