USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[BILLENTRYMASTER]    Script Date: 12-08-2021 13:03:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BILLENTRYMASTER](
	[BILLEMID] [int] IDENTITY(1,1) NOT NULL,
	[SDPTID] [int] NOT NULL CONSTRAINT [DF_BILLENTRYMASTER_SDPTID]  DEFAULT (0),
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_BILLENTRYMASTER_COMPYID]  DEFAULT (0),
	[BILLEMDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_BILLENTRYMASTER_BILLEMDATE]  DEFAULT (null),
	[BILLEMTIME] [datetime] NOT NULL CONSTRAINT [DF_BILLENTRYMASTER_BILLEMTIME]  DEFAULT (null),
	[BILLEMNO] [int] NOT NULL CONSTRAINT [DF_BILLENTRYMASTER_BILLEMNO]  DEFAULT (0),
	[BILLEMDNO] [varchar](15) NOT NULL CONSTRAINT [DF_BILLENTRYMASTER_BILLEMDNO]  DEFAULT (null),
	[CHAID] [int] NOT NULL CONSTRAINT [DF_BILLENTRYMASTER_CHAID]  DEFAULT (0),
	[BILLEMNAME] [varchar](100) NULL CONSTRAINT [DF_BILLENTRYMASTER_BILLEMNAME]  DEFAULT (null),
	[BILLEMAAMT] [numeric](18, 2) NULL CONSTRAINT [DF_BILLENTRYMASTER_BILLEMAAMT]  DEFAULT (0),
	[BLNO] [varchar](20) NULL CONSTRAINT [DF_BILLENTRYMASTER_BLNO]  DEFAULT (null),
	[NOP] [numeric](18, 2) NULL CONSTRAINT [DF_BILLENTRYMASTER_NOP]  DEFAULT (0),
	[WGHT] [numeric](18, 4) NULL CONSTRAINT [DF_BILLENTRYMASTER_WGHT]  DEFAULT (0),
	[UNITID] [int] NULL CONSTRAINT [DF_BILLENTRYMASTER_UNITID]  DEFAULT (0),
	[BILLEDMTYPE] [smallint] NULL CONSTRAINT [DF_BILLENTRYMASTER_BILLEDMTYPE]  DEFAULT (0),
	[DPAIDNO] [varchar](20) NULL CONSTRAINT [DF_BILLENTRYMASTER_DPAIDNO]  DEFAULT (null),
	[DPAIDAMT] [numeric](18, 2) NULL CONSTRAINT [DF_BILLENTRYMASTER_DPAIDAMT]  DEFAULT (0),
	[CUSRID] varchar(25) NULL CONSTRAINT [DF_BILLENTRYMASTER_CUSRID]  DEFAULT (''),
	[LMUSRID] varchar(25) NULL CONSTRAINT [DF_BILLENTRYMASTER_LMUSRID]  DEFAULT (''),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_BILLENTRYMASTER_DISPSTATUS]  DEFAULT (0),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_BILLENTRYMASTER_PRCSDATE]  DEFAULT (null),
 CONSTRAINT [PK_BILLENTRYMASTER] PRIMARY KEY CLUSTERED 
(
	[BILLEMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ASSESSABLE VALUE' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BILLENTRYMASTER', @level2type=N'COLUMN',@level2name=N'BILLEMAAMT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'MOVEMENT BY' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BILLENTRYMASTER', @level2type=N'COLUMN',@level2name=N'BILLEDMTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DUTY PAID NUMBER' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BILLENTRYMASTER', @level2type=N'COLUMN',@level2name=N'DPAIDNO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'DUTY PAID AMOUNT' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BILLENTRYMASTER', @level2type=N'COLUMN',@level2name=N'DPAIDAMT'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ENTERED BY' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BILLENTRYMASTER', @level2type=N'COLUMN',@level2name=N'CUSRID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'MODIFIED BY' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BILLENTRYMASTER', @level2type=N'COLUMN',@level2name=N'LMUSRID'
GO


