select * from opensheetmaster
select gateindetail.gidate, GATEINDETAIL.GIDID, opensheetdetail.BILLEDID, OPENSHEETMASTER.OSMID, OPENSHEETMASTER.OSMLNO,
BILLENTRYDETAIL.* From gateindetail 
 join opensheetdetail on gateindetail.GIDID = OPENSHEETDETAIL.GIDID
 join opensheetmaster on OPENSHEETDETAIL.OSMID = OPENSHEETMASTER.OSMID
left join BILLENTRYDETAIL on GATEINDETAIL.GIDID = BILLENTRYDETAIL.GIDID
 join BILLENTRYMASTER on BILLENTRYMASTER.BILLEMID = BILLENTRYDETAIL.BILLEMID
where --BILLENTRYDETAIL.GIDID is  null AND 
IGMNO= '2293480' and GPLNO ='244'
and gateindetail.SDPTID = 1
order by 1 desc
--SELECT * FROM gateindetail where IGMNO= '2293480' and GPLNO ='244'


INSERT INTO BILLENTRYMASTER (SDPTID, COMPYID, BILLEMDATE, BILLEMTIME, BILLEMNO,BILLEMDNO,CHAID, BILLEMNAME, BILLEMAAMT, BLNO, NOP,WGHT,UNITID,BILLEDMTYPE, CUSRID, 
LMUSRID,DISPSTATUS,PRCSDATE,DPAIDAMT,DPAIDNO)
SELECT   DISTINCT GATEINDETAIL.SDPTID, GATEINDETAIL.COMPYID, CONVERT(VARCHAR(10), OPENSHEETMASTER.OSMDATE,120), OPENSHEETMASTER.OSMDATE, '0', OPENSHEETMASTER.BOENO, OPENSHEETMASTER.CHAID,
OPENSHEETMASTER.OSMNAME, OPENSHEETMASTER.OSMAAMT, OPENSHEETMASTER.OSMBLNO,  OPENSHEETMASTER.OSMNOP,OPENSHEETMASTER.OSMWGHT, OPENSHEETMASTER.OSMUNITID, OPENSHEETMASTER.OSMTYPE,
 OPENSHEETDETAIL.CUSRID, OPENSHEETDETAIL.LMUSRID, 0 , GETDATE(),OSMDUTYAMT,1
From gateindetail 
 join opensheetdetail on gateindetail.GIDID = OPENSHEETDETAIL.GIDID
 join opensheetmaster on OPENSHEETDETAIL.OSMID = OPENSHEETMASTER.OSMID
left join BILLENTRYDETAIL on GATEINDETAIL.GIDID = BILLENTRYDETAIL.GIDID
where --BILLENTRYDETAIL.GIDID is  null AND 
IGMNO= '2293480' and GPLNO ='244'
and gateindetail.SDPTID = 1

DECLARE @BILEMNO INT, @BILLMID INT
SELECT @BILLMID = SCOPE_IDENTITY()

SELECT @BILEMNO = MAX(BILLEMNO)+1 FROM BILLENTRYMASTER WHERE COMPYID = 32
SELECT @BILEMNO
UPDATE BILLENTRYMASTER 
SET BILLEMNO = @BILEMNO
WHERE BILLEMNO = '0'

SET IDENTITY_INSERT  BILLENTRYDETAIL ON
INSERT INTO BILLENTRYDETAIL (BILLEDID, BILLEMID, GIDID, GIDATE, DNOP, DWGHT, CUSRID, LMUSRID,DISPSTATUS, PRCSDATE,OLDBILLEDID)
SELECT  opensheetdetail.BILLEDID, 5098, GATEINDETAIL.GIDID,GATEINDETAIL.GIDATE, OPENSHEETMASTER.OSMNOP, OPENSHEETMASTER.OSMWGHT, OPENSHEETDETAIL.CUSRID, OPENSHEETDETAIL.LMUSRID, 0 , GETDATE(),0
From gateindetail 
 join opensheetdetail on gateindetail.GIDID = OPENSHEETDETAIL.GIDID
 join opensheetmaster on OPENSHEETDETAIL.OSMID = OPENSHEETMASTER.OSMID
left join BILLENTRYDETAIL on GATEINDETAIL.GIDID = BILLENTRYDETAIL.GIDID
where BILLENTRYDETAIL.GIDID is  null --IGMNO= '2293480' and GPLNO ='244'
and gateindetail.SDPTID = 1


SELECT * FROM BILLENTRYMASTER WHERE BILLEMNO =6356
SELECT * FROM BILLENTRYDETAIL WHERE BILLEMID =5098

UPDATE BILLENTRYDETAIL
SET BILLEMID = 6356
WHERE BILLEDID IN (17466,17465)

SELECT * FROM AUTHORIZATIONSLIPDETAIL WHERE GIDID IN(62722, 62685)

SELECT * FROM GATEINDETAIL WHERE CONTNRNO IN ('WHLU0431098')
SELECT * FROM VEHICLETICKETDETAIL WHERE ASLDID IN (24257, 24258)
 = 24199
SELECT * FROM AUTHORIZATIONSLIPDETAIL WHERE GIDID = 34984