USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[BILLENTRYDETAIL]    Script Date: 12-08-2021 13:00:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
-- drop table [BILLENTRYDETAIL]
CREATE TABLE [dbo].[BILLENTRYDETAIL](
	[BILLEDID] [int]  IDENTITY(1,1) NOT NULL,
	[BILLEMID] [int] NOT NULL CONSTRAINT [DF_BILLENTRYDETAIL_BILLEMID]  DEFAULT (0),
	[GIDID] [int] NOT NULL CONSTRAINT [DF_BILLENTRYDETAIL_GIDID]  DEFAULT (0),
	[GIDATE] [smalldatetime] NULL CONSTRAINT [DF_BILLENTRYDETAIL_GIDATE]  DEFAULT (null),
	[DNOP] [numeric](18, 2) NULL CONSTRAINT [DF_BILLENTRYDETAIL_NOP]  DEFAULT (0),
	[DWGHT] [numeric](18, 4) NULL CONSTRAINT [DF_BILLENTRYDETAIL_WGHT]  DEFAULT (0),
	[CUSRID] varchar(25) NULL CONSTRAINT [DF_BILLENTRYDETAIL_CUSRID]  DEFAULT (''),
	[LMUSRID] varchar(25) NULL CONSTRAINT [DF_BILLENTRYDETAIL_LMUSRID]  DEFAULT (''),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_BILLENTRYDETAIL_DISPSTATUS]  DEFAULT (0),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_BILLENTRYDETAIL_PRCSDATE]  DEFAULT (null),
 CONSTRAINT [PK_BILLENTRYDETAIL] PRIMARY KEY CLUSTERED 
(
	[BILLEDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BILLENTRYDETAIL]  WITH NOCHECK ADD  CONSTRAINT [FK_BILLENTRYDETAIL_BILLENTRYMASTER] FOREIGN KEY([BILLEMID])
REFERENCES [dbo].[BILLENTRYMASTER] ([BILLEMID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BILLENTRYDETAIL] CHECK CONSTRAINT [FK_BILLENTRYDETAIL_BILLENTRYMASTER]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'GATE IN DETAIL IN' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BILLENTRYDETAIL', @level2type=N'COLUMN',@level2name=N'GIDID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ENTERED BY' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BILLENTRYDETAIL', @level2type=N'COLUMN',@level2name=N'CUSRID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'MODIFIED BY' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BILLENTRYDETAIL', @level2type=N'COLUMN',@level2name=N'LMUSRID'
GO


