select STMRNAME, IMPRTNAME, TRNSPRTNAME, CONTNRNO,GIDATE,GITIME, B.GODATE,B.GOTIME, CS.CONTNRSDESC
from GATEINDETAIL A (nolock) 
	left join GATEOUTDETAIL B (nolock) on A.GIDID = B.GIDID AND A.SDPTID = B.SDPTID
	LEFT JOIN CONTAINERSIZEMASTER CS(NOLOCK) ON A.CONTNRSID = CS.CONTNRSID
where A.SDPTID = 1
and (GIDATE >= '2015-10-01' AND GIDATE <= '2022-06-22')
and IMPRTNAME like 'BMW%'
ORDER BY GIDATE,GODATE