SELECT COUNT('*') FROM BONDMASTER
BEGIN  TRAN
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDMASTER ON 
INSERT INTO SCFS_ERP.DBO.BONDMASTER
(
BNDID,COMPYID,SDPTID,BNDNO,BNDDNO,BNDDATE,BNDFDATE,BNDTDATE,BNDADATE,IMPRTID,CHAID,YRDID,TYPEID,BNDBENO,BNDBLNO,BNDIGMNO,BNDLINENO,
BND20, BND40, BNDGWGHT, BNDCIFAMT, BNDDTYAMT, BNDINSAMT,BNDBCIFAMT, BNDBDTYAMT, BNDBINSAMT, GWNID, PRDTGID,PRDTDESC,PRDTTID,BNDNOP,
BNDSPC, BNDBNOP,BNDBSPC,BNDHAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE,BNDBEDATE,BNDBLDATE,BNDTYPE)

SELECT BNDID,31,10,BNDNO,BNDDNO,BNDDATE,BNDFDATE,BNDTDATE,BNDADATE,IMPRTID,CHAID,0,TYPEID+1,BNDBENO,BNDBLNO,BNDIGMNO,'-',
BND20, BND40, BNDGWGHT, BNDCIFAMT, BNDDTYAMT, BNDINSAMT,BNDBCIFAMT, BNDBDTYAMT, BNDBINSAMT, GWNID, A.PRDTGID,B.PRDTGDESC,1,BNDNOP,
BNDSPC, BNDBNOP,BNDBSPC,BNDHAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,A.CUSRID,A.LMUSRID,A.DISPSTATUS,A.PRCSDATE,BNDBEDATE,BNDBLDATE,
A.TYPEID + 1
FROM SPBW..BONDMASTER A LEFT JOIN SPBW..PRODUCTGROUPMASTER B(NOLOCK) ON A.PRDTGID = B.PRDTGID
WHERE COMPYID=25 
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDMASTER OFF
SELECT COUNT('*') FROM BONDMASTER
ROLLBACK TRAN
--COMMIT TRAN
--UPDATE SCFS_ERP..BONDMASTER
--SET YRDID = 0 WHERE YRDID > 0
--UPDATE SCFS_ERP..BONDMASTER
--SET TYPEID = TYPEID+1 
--WHERE BNDID < 5750
SELECT COUNT('*') FROM BONDMASTER