--alter table BONDTRANSACTIONMASTER
--drop column [TRAN_TAXABLE_AMT]
--go
--alter table BONDTRANSACTIONMASTER
--drop column TRANBILLREFNO
--go
--alter table BONDTRANSACTIONMASTER
--drop column [TRAN_TAXABLE_AMT]
--go
alter table BONDTRANSACTIONMASTER
ADD [TRAN_TAXABLE_AMT] [numeric](18, 2)  NULL
GO
UPDATE BONDTRANSACTIONMASTER
SET [TRAN_TAXABLE_AMT] =0 
WHERE [TRAN_TAXABLE_AMT] IS NULL

alter table BONDTRANSACTIONMASTER
ADD TRANBILLREFNO VARCHAR(50)  NULL
GO
UPDATE BONDTRANSACTIONMASTER
SET TRANBILLREFNO =''
WHERE TRANBILLREFNO IS NULL
go
alter table BONDTRANSACTIONDETAIL
ADD [TRAND_HSN_CODE] VARCHAR(50) NULL
go
UPDATE BONDTRANSACTIONDETAIL
SET [TRAND_HSN_CODE] =''
WHERE [TRAND_HSN_CODE] IS NULL

alter table BONDTRANSACTIONDETAIL
ADD INS_TRAND_HSN_CODE VARCHAR(50) NULL
go
UPDATE BONDTRANSACTIONDETAIL
SET INS_TRAND_HSN_CODE =''
WHERE INS_TRAND_HSN_CODE IS NULL

alter table BONDTRANSACTIONDETAIL
ADD TRAND_TAXABLE_AMT numeric(18,2) NULL
go
UPDATE BONDTRANSACTIONDETAIL
SET TRAND_TAXABLE_AMT=TRANDGAMT
WHERE TRAND_TAXABLE_AMT IS NULL


alter table BONDTRANSACTIONDETAIL
ADD INS_TRAND_TAXABLE_AMT numeric(18,2) NULL
go
UPDATE BONDTRANSACTIONDETAIL
SET INS_TRAND_TAXABLE_AMT=0
WHERE INS_TRAND_TAXABLE_AMT IS NULL

alter table BONDTRANSACTIONDETAIL
ADD STATETYPE int NULL
go
UPDATE A
SET a.STATETYPE=d.STATETYPE
from BONDTRANSACTIONDETAIL a, BONDTRANSACTIONMASTER b, CATEGORY_ADDRESS_DETAIL c,
STATEMASTER d 
WHERE a.TRANMID = b.TRANMID
and b.BCATEAID = c.CATEAID
and c.STATEID = d.STATEID

UPDATE BONDTRANSACTIONDETAIL
SET STATETYPE=0
where  STATETYPE is null



--alter table BONDTRANSACTIONDETAIL
--drop column [TRAND_HSNCODE]

--select * from BONDTRANSACTIONmaster order by tranmid desc
--select b.* from BONDTRANSACTIONmaster a(nolock) left join BONDTRANSACTIONDETAIL b (nolock) on a.tranmid = b.tranmid
--where a.TRANDATE = '2022-10-01'

--delete BONDTRANSACTIONmaster
--where TRANDATE = '2022-10-01'