select * from BONDTRANSACTIONDETAIL where  TRANDEBNDNO ='3172993'
select * from spbw..TRANSACTIONDETAIL where TRANDEBNDNO ='3172993'

select * from BONDTRANSACTIONDETAIL where  TRANMID = 14338
select * from spbw..TRANSACTIONDETAIL where TRANMID = 14338


select distinct a1.bndid BondID, a.[Bond No] BondNo, a1.BNDNOP BondNOP, 
b.BNDID ExBndBondID, b.ebndid ExBondID,b.EBNDNO ExBondNo, b.EBNDNOP EXBondNOP, 
c.TRANMID InvID, d.TRANDNO InvNO, d.TRANDATE InvDt, c.SLABTID, e.SLABTDESC,
c.bndid InvBondId, TRANDBNDNO InvBondNo, c.EBNDID InvExBondID, c.TRANDEBNDNO InvExBondNo,
c.TRANDNOP InvNOP, TRANTID
from Old_Live_Bond_Closing_Details a (nolock) 
	 join BONDMASTER a1(nolock) on a.[Bond No] = a1.BNDDNO
	 join EXBONDMASTER b(nolock) on a1.BNDID = b.BNDID
	 join BONDTRANSACTIONDETAIL c(nolock) on (
	(b.eBNDDNO = TRANDEBNDNO)
	or (a.[Bond No] = TRANDBNDNO)                                                                                                                          )
	 join BONDTRANSACTIONMASTER d(nolock) on c.TRANMID = d.TRANMID
	 join BONDSLABTYPEMASTER e(nolock) on c.SLABTID = e.SLABTID 
where slabtdesc = 'storage' --or SLABTDESC is null
and a.[Bond No]  = '2001974811' --in ('2015337007' ,'2002029677')

select * from Old_Live_Bond_Closing_Details


select * from BONDTRANSACTIONMASTER where  TRANDNO  = 'BWH/2223/000020'-- TRANMID =14612
select * from spbw..TRANSACTIONMASTER where TRANDNO = 'BWH/2223/000020'-- TRANMID = 14612

select A.BNDID ,  BNDDNO ,  convert(varchar,BNDDATE,103) ,EB.EBNDID ,  EB.EBNDDNO ,  convert(varchar,EB.EBNDDATE,103) , 
	 VT.VTDID ,  VT.VTDNO ,  convert(varchar,VT.VTDATE,103) , 
	 A.IMPRTID, A.CHAID, BNDBENO, BNDBLNO, BNDIGMNO,isnull(BNDLINENO,''), isnull(BND20,0),isnull(BND40,0),BNDGWGHT,
	 A.PRDTGID, A.PRDTDESC,PRDTTID,convert(varchar,BNDBEDATE,103) , convert(varchar,BNDBLDATE,103) ,BNDTYPE,
	 VTQTY,VTAREA,eb.EBNDNOP,eb.EBNDSPC, --B.CATENAME, C.CATENAME, 
	 CASE WHEN BNDTYPE = 1 THEN 'FCL' ELSE 'LCL' END,
	 --EBNDASSAMT/eb.EBNDNOP*BEBNOP,EBNDDTYAMT/eb.EBNDNOP*BEBNOP, EBNDINSAMT/eb.EBNDNOP*BEBNOP, 
	 convert(varchar,max(isnull(isnull(eBID.TRANSFDATE,BID.TRANSFDATE),GIDATE)),103) 'BNDSDATE', convert(varchar,max(VTDATE),103) 'BNDCDATE',
	 convert(varchar,max(isnull(isnull(eBID.TRANIFDATE,BID.TRANIFDATE),GIDATE)),103) 'BNDISDATE', convert(varchar,max(VTDATE),103) 'BNDICDATE'
	 --BEBNOP BBNDNOP, BEBSPC BBNDSPC , 0 BEBNDASSAMT , 0 BEBNDDTYAMT , 0 BEBNDINSAMT,EBNDNOC, EBVTNOC 
	 from BONDVEHICLETICKETDETAIL VT(NOLOCK) JOIN EXBONDMASTER EB(NOLOCK) ON VT.EBNDID = EB.EBNDID
		JOIN BONDMASTER a (nolock) ON EB.BNDID = A.BNDID
		LEFT JOIN BONDGATEINDETAIL D(NOLOCK) ON A.BNDID = D.BNDID
		left join [BONDTRANSACTIONDETAIL] BID (nolock) on
		((EB.BNDID = BID.BNDID AND eb.EBNDID = BID.EBNDID) 		
		or
		(a.BNDDNO = BID.TRANDBNDNO AND eb.EBNDDNO = BID.TRANDEBNDNO)) 
		left join [BONDTRANSACTIONMASTER] BIM (nolock) on   BId.tranmid = BIm.tranmid and BIM.TRANTID=2	--EB.BNDID = BIM.TRANLMID AND A.BNDDNO = BIM.TRANLMNO AND	
		left join [BONDTRANSACTIONDETAIL] EBID (nolock) on 
		((EB.eBNDID = eBID.eBNDID AND eb.EBNDID = eBID.EBNDID) 		
		or
		(a.BNDDNO = eBID.TRANDBNDNO AND eb.EBNDDNO = eBID.TRANDEBNDNO)) 	
		left join [BONDTRANSACTIONMASTER] EBIM (nolock) on eBId.tranmid = eBIm.tranmid and eBIM.TRANTID=3	--vt.VTDID = EBIM.TRANLMID AND vt.VTDNO = EBIM.TRANLMNO AND	
			
where EBNDDNO = '3172993'
GROUP BY A.BNDID ,  BNDDNO ,  BNDDATE , A.IMPRTID, A.CHAID, BNDBENO, BNDBLNO, BNDIGMNO,BNDLINENO, BND20,BND40,BNDGWGHT,
	 A.PRDTGID, A.PRDTDESC,PRDTTID,BNDNOP,BNDSPC,BNDBEDATE, BNDBLDATE,BNDTYPE, --B.CATENAME, C.CATENAME, 
	 CASE WHEN BNDTYPE = 1 THEN 'FCL' ELSE 'LCL' END,EBNDASSAMT,EBNDDTYAMT,EBNDINSAMT, BNDDATE, BNDTDATE,
	 --BEBNOP, BEBSPC ,
	 EB.EBNDID ,  EB.EBNDDNO ,  EB.EBNDDATE, 	 VT.VTDID ,  VT.VTDNO ,VTDATE, VTQTY,VTAREA,
	 EBNDNOP,EBNDSPC,EBNDNOC,EBVTNOC


select * From [VW_VT_EXBOND_BALANCE_DETAIL_ASSGN] where 
select A.BNDID ,  BNDDNO ,  convert(varchar,BNDDATE,103) ,EB.EBNDID ,  EB.EBNDDNO ,  convert(varchar,EB.EBNDDATE,103) , 
	 VT.VTDID ,  VT.VTDNO ,  convert(varchar,VT.VTDATE,103) , 
	 A.IMPRTID, A.CHAID, BNDBENO, BNDBLNO, BNDIGMNO,isnull(BNDLINENO,''), isnull(BND20,0),isnull(BND40,0),BNDGWGHT,
	 A.PRDTGID, A.PRDTDESC,PRDTTID,convert(varchar,BNDBEDATE,103) , convert(varchar,BNDBLDATE,103) ,BNDTYPE,
	 VTQTY,VTAREA,eb.EBNDNOP,eb.EBNDSPC, B.CATENAME, C.CATENAME, 
	 CASE WHEN BNDTYPE = 1 THEN 'FCL' ELSE 'LCL' END,
	 EBNDASSAMT/eb.EBNDNOP*BEBNOP,EBNDDTYAMT/eb.EBNDNOP*BEBNOP, EBNDINSAMT/eb.EBNDNOP*BEBNOP, 
	 convert(varchar,max(isnull(isnull(eBID.TRANSFDATE,BID.TRANSFDATE),GIDATE)),103) 'BNDSDATE', convert(varchar,max(VTDATE),103) 'BNDCDATE',
	 convert(varchar,max(isnull(isnull(eBID.TRANIFDATE,BID.TRANIFDATE),GIDATE)),103) 'BNDISDATE', convert(varchar,max(VTDATE),103) 'BNDICDATE',
	 BEBNOP BBNDNOP, BEBSPC BBNDSPC , 0 BEBNDASSAMT , 0 BEBNDDTYAMT , 0 BEBNDINSAMT,EBNDNOC, EBVTNOC
	 from BONDVEHICLETICKETDETAIL VT(NOLOCK) JOIN EXBONDMASTER EB(NOLOCK) ON VT.EBNDID = EB.EBNDID
		JOIN BONDMASTER a (nolock) ON EB.BNDID = A.BNDID
		join [VW_VT_EXBOND_BALANCE_DETAIL_ASSGN] e (nolock) on VT.EBNDID = e.EBNDID 
		LEFT JOIN CATEGORYMASTER B(NOLOCK) ON A.CHAID = B.CATEID AND B.CATETID = 4
		LEFT JOIN CATEGORYMASTER C(NOLOCK) ON A.IMPRTID = C.CATEID AND C.CATETID = 1
		LEFT JOIN BONDGATEINDETAIL D(NOLOCK) ON A.BNDID = D.BNDID				
		left join [BONDTRANSACTIONMASTER] BIM (nolock) on EB.BNDID = BIM.TRANLMID AND A.BNDDNO = BIM.TRANLMNO AND BIM.TRANTID=2		
		left join [BONDTRANSACTIONDETAIL] BID (nolock) on 
		((EB.BNDID = BID.BNDID AND eb.EBNDID = BID.EBNDID) 		
		or
		(a.BNDDNO = BID.TRANDBNDNO AND eb.EBNDDNO = BID.TRANDEBNDNO)) 	
		left join [BONDTRANSACTIONMASTER] EBIM (nolock) on vt.VTDID = EBIM.TRANLMID AND vt.VTDNO = EBIM.TRANLMNO AND BIM.TRANTID=3		
		left join [BONDTRANSACTIONDETAIL] EBID (nolock) on 
		((EB.eBNDID = eBID.eBNDID AND eb.EBNDID = eBID.EBNDID) 		
		or
		(a.BNDDNO = eBID.TRANDBNDNO AND eb.EBNDDNO = eBID.TRANDEBNDNO)) 	

	where -- a.COMPYID = @compyid 	and 
	vt.VTDID = 57
	GROUP BY A.BNDID ,  BNDDNO ,  BNDDATE , A.IMPRTID, A.CHAID, BNDBENO, BNDBLNO, BNDIGMNO,BNDLINENO, BND20,BND40,BNDGWGHT,
	 A.PRDTGID, A.PRDTDESC,PRDTTID,BNDNOP,BNDSPC,BNDBEDATE, BNDBLDATE,BNDTYPE,B.CATENAME, C.CATENAME, 
	 CASE WHEN BNDTYPE = 1 THEN 'FCL' ELSE 'LCL' END,EBNDASSAMT,EBNDDTYAMT,EBNDINSAMT, BNDDATE, BNDTDATE,
	 BEBNOP, BEBSPC , EB.EBNDID ,  EB.EBNDDNO ,  EB.EBNDDATE, 	 VT.VTDID ,  VT.VTDNO ,VTDATE, VTQTY,VTAREA,
	 EBNDNOP,EBNDSPC,EBNDNOC,EBVTNOC


	