
ALTER TABLE BONDSLABTYPEMASTER
ADD HSNID INT NULL 
go

UPDATE A
SET HSNID = B.HSNID
FROM BONDSLABTYPEMASTER A, HSNCODEMASTER B
WHERE A.SLABTDESC = B.HSNDESC

UPDATE BONDSLABTYPEMASTER 
SET HSNID = 0
WHERE hsnid is null
-- SELECT * FROM HSNCODEMASTER
-- SELECT * FROM BONDSLABTYPEMASTER