update BONDTRANSACTIONMASTER
set TRANNO = 293,TRANDNO='BWH/2223/00293',  TRANBILLREFNO='BWH/INB/CU/00293'
WHERE TRANMID = 14711 --14701

update BONDTRANSACTIONMASTER
set TRANNO = 302,TRANDNO='BWH/2223/00302',  TRANBILLREFNO='BWH/EXB/CU/00302'
WHERE TRANMID = 14721 
--delete BONDTRANSACTIONMASTER WHERE TRANMID = 14722 14721 
SELECT * FROM BONDTRANSACTIONMASTER WHERE TRANROAMT > 0 order by tranmid desc
UPDATE BONDTRANSACTIONMASTER 
WHERE TRANROAMT > 0
order by tranmid desc
SELECT * FROM BONDTRANSACTIONDETAIL order by tranmid desc

update BONDTRANSACTIONDETAIL
set VTDID = 1
where TRANDID = 38660

UPDATE BONDTRANSACTIONDETAIL
SET TRAND_CGST_AMT = ROUND(TRAND_CGST_AMT,0), TRAND_SGST_AMT = ROUND(TRAND_SGST_AMT,0),  TRAND_IGST_AMT = ROUND(TRAND_IGST_AMT,0)
WHERE TRANMID >14611


UPDATE BONDTRANSACTIONMASTER
SET TRAN_CGST_AMT = ROUND(TRAN_CGST_AMT,0), TRAN_SGST_AMT = ROUND(TRAN_SGST_AMT,0),  TRAN_IGST_AMT = ROUND(TRAN_IGST_AMT,0), TRANROAMT=0
WHERE TRANMID >14611

select * From SPBW..TRANSACTIONMASTER order by tranmid desc


select *From BONDTRANSACTIONDETAIL

update BONDTRANSACTIONDETAIL
set TRANDGAMT = TRANDNAMT-TRAND_CGST_AMT-	TRAND_SGST_AMT
WHERE TRANMID =14701

select * From BONDTRANSACTIONMASTER order by tranmid desc
update BONDTRANSACTIONMASTER
set TRANDATE = '2022-10-22'
where tranmid =14724

update BONDTRANSACTIONMASTER
set CHAID = 53617
where tranmid in(14724,14725)

select * from EXBONDMASTER