USE SCFS_ERP
GO

/****** Object:  Table [dbo].[BONDMASTER]    Script Date: 22/08/2022 14:26:32 ******/
DROP TABLE [dbo].[BONDMASTER]
GO

/****** Object:  Table [dbo].[BONDMASTER]    Script Date: 22/08/2022 14:26:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BONDMASTER](
	[BNDID] [int] identity(1,1) NOT NULL ,
	[COMPYID] [int] NULL CONSTRAINT [DF_BONDMASTER_COMPYID_1]  DEFAULT (0),
	[SDPTID] [int] NULL CONSTRAINT [DF_BONDMASTER_SDPTID]  DEFAULT (0),
	[BNDNO] [int] NULL CONSTRAINT [DF_BONDMASTER_BNDNO_1]  DEFAULT (0),
	[BNDDNO] [varchar](50) NULL CONSTRAINT [DF_BONDMASTER_BNDDNO_1]  DEFAULT (null),
	[BNDDATE] [smalldatetime] NULL CONSTRAINT [DF_BONDMASTER_BNDDATE_1]  DEFAULT (null),
	[BNDFDATE] [smalldatetime] NULL CONSTRAINT [DF_BONDMASTER_BNDFDATE_1]  DEFAULT (null),
	[BNDTDATE] [smalldatetime] NULL CONSTRAINT [DF_BONDMASTER_BNDTDATE_1]  DEFAULT (null),
	[BNDADATE] [smalldatetime] NULL CONSTRAINT [DF_BONDMASTER_BNDADATE_1]  DEFAULT (null),
	[IMPRTID] [int] NULL CONSTRAINT [DF_BONDMASTER_IMPRTID_1]  DEFAULT (0),
	[CHAID] [int] NULL CONSTRAINT [DF_BONDMASTER_CHAID_1]  DEFAULT (0),
	[YRDID] [int] NULL CONSTRAINT [DF_BONDMASTER_YRDID_1]  DEFAULT (0),
	[TYPEID] [smallint] NULL CONSTRAINT [DF_BONDMASTER_TYPEID_1]  DEFAULT (0),
	[BNDBENO] [varchar](50) NULL CONSTRAINT [DF_BONDMASTER_BNDBENO_1]  DEFAULT (null),
	[BNDBLNO] [varchar](50) NULL CONSTRAINT [DF_BONDMASTER_BNDBLNO_1]  DEFAULT (null),
	[BNDIGMNO] [varchar](50) NULL CONSTRAINT [DF_BONDMASTER_BNDIGMNO_1]  DEFAULT (null),
	[BNDLINENO] [varchar](50) NULL CONSTRAINT [DF_BONDMASTER_BNDLINENO_1]  DEFAULT (null),
	[BND20] [int] NULL CONSTRAINT [DF_BONDMASTER_BND20_1]  DEFAULT (0),
	[BND40] [int] NULL CONSTRAINT [DF_BONDMASTER_BND40_1]  DEFAULT (0),
	[BNDGWGHT] [numeric](18, 3) NULL CONSTRAINT [DF_BONDMASTER_BNDGWGHT_1]  DEFAULT (0),
	[BNDCIFAMT] [numeric](18, 2) NULL CONSTRAINT [DF_BONDMASTER_BNDCIFAMT_1]  DEFAULT (0),
	[BNDDTYAMT] [numeric](18, 2) NULL CONSTRAINT [DF_BONDMASTER_BNDDTYAMT_1]  DEFAULT (0),
	[BNDINSAMT] [numeric](18, 2) NULL CONSTRAINT [DF_BONDMASTER_BNDINSAMT_1]  DEFAULT (0),
	[BNDBCIFAMT] [numeric](18, 2) NULL CONSTRAINT [DF_BONDMASTER_BNDBCIFAMT]  DEFAULT (0),
	[BNDBDTYAMT] [numeric](18, 2) NULL CONSTRAINT [DF_BONDMASTER_BNDBDTYAMT_1]  DEFAULT (0),
	[BNDBINSAMT] [numeric](18, 2) NULL CONSTRAINT [DF_BONDMASTER_BNDBINSAMT_1]  DEFAULT (0),
	[GWNID] [int] NULL,
	[PRDTGID] [int] NULL CONSTRAINT [DF_BONDMASTER_PRDTGID]  DEFAULT (0),
	[PRDTDESC] [varchar](100) NOT NULL CONSTRAINT [DF_BONDMASTER_PRDTDESC]  DEFAULT (NULL),
	[PRDTTID] INT  NULL CONSTRAINT [DF_BONDMASTER_PRDTTID]  DEFAULT (0),
	[BNDNOP] [numeric](18, 2) NULL CONSTRAINT [DF_BONDMASTER_BNDNOP]  DEFAULT (0),
	[BNDSPC] [numeric](18, 2) NULL CONSTRAINT [DF_BONDMASTER_BNDSPC]  DEFAULT (0),
	[BNDBNOP] [int] NULL CONSTRAINT [DF_BONDMASTER_BNDBNOP]  DEFAULT (0),
	[BNDBSPC] [numeric](18, 2) NULL CONSTRAINT [DF_BONDMASTER_BNDBSPC]  DEFAULT (0),
	[BNDHAMT] [numeric](18, 2) NULL CONSTRAINT [DF_BONDMASTER_BNDHAMT]  DEFAULT (0),
	[STRGSDATE] [smalldatetime] NULL CONSTRAINT [DF_BONDMASTER_STRGSDATE]  DEFAULT (null),
	[STRGEDATE] [smalldatetime] NULL CONSTRAINT [DF_BONDMASTER_STRGEDATE]  DEFAULT (null),
	[INSRSDATE] [smalldatetime] NULL CONSTRAINT [DF_BONDMASTER_INSRSDATE]  DEFAULT (null),
	[INSREDATE] [smalldatetime] NULL CONSTRAINT [DF_BONDMASTER_INSREDATE]  DEFAULT (null),
	[CUSRID] VARCHAR(100) NULL CONSTRAINT [DF_BONDMASTER_CUSRID_1]  DEFAULT (0),
	[LMUSRID] VARCHAR(100) NULL CONSTRAINT [DF_BONDMASTER_LMUSRID_1]  DEFAULT (0),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_BONDMASTER_DISPSTATUS_1]  DEFAULT (0),
	[PRCSDATE] [smalldatetime] NULL CONSTRAINT [DF_BONDMASTER_PRCSDATE_1]  DEFAULT (null),
	[BNDBEDATE] [smalldatetime] NULL CONSTRAINT [DF_BONDMASTER_BNDBEDATE]  DEFAULT (NULL),
	[BNDBLDATE] [smalldatetime] NULL CONSTRAINT [DF_BONDMASTER_BNDBLDATE]  DEFAULT (NULL),
	[BNDTYPE] [smallint] NOT NULL CONSTRAINT [DF_BONDMASTER_BNDTYPE]  DEFAULT ((0)),
 CONSTRAINT [PK_BONDMASTER_1] PRIMARY KEY CLUSTERED 
(
	[BNDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE SCFS_ERP
GO

/****** Object:  Table [dbo].[EXBONDMASTER]    Script Date: 22/08/2022 14:26:09 ******/
DROP TABLE [dbo].[EXBONDMASTER]
GO

/****** Object:  Table [dbo].[EXBONDMASTER]    Script Date: 22/08/2022 14:26:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EXBONDMASTER](
	[EBNDID] [int] NOT NULL identity(1,1),
	[COMPYID] [int] NULL CONSTRAINT [DF_EXBONDMASTER_COMPYID]  DEFAULT (0),
	[SDPTID] [int] NULL CONSTRAINT [DF_EXBONDMASTER_SDPTID]  DEFAULT (0),
	[EBNDNO] [int] NULL CONSTRAINT [DF_EXBONDMASTER_EBNDNO]  DEFAULT (0),
	[EBNDDNO] [varchar](50) NULL CONSTRAINT [DF_EXBONDMASTER_EDBNDNO]  DEFAULT (null),
	[EBNDDATE] [smalldatetime] NULL CONSTRAINT [DF_EXBONDMASTER_EBNDDATE]  DEFAULT (null),
	[IMPRTID] [int] NULL CONSTRAINT [DF_EXBONDMASTER_IMPRTID]  DEFAULT (0),
	[CHAID] [int] NULL CONSTRAINT [DF_EXBONDMASTER_CHAID]  DEFAULT (0),
	[EBNDBENO] [varchar](50) NULL CONSTRAINT [DF_EXBONDMASTER_EBNDDBENO]  DEFAULT (null),
	[EBNDBEDATE] [smalldatetime] NULL CONSTRAINT [DF_EXBONDMASTER_EBNDDBEDATE]  DEFAULT (null),
	[BNDID] [int] NULL CONSTRAINT [DF_EXBONDMASTER_BNDID]  DEFAULT (0),
	[TYPEID] [smallint] NULL CONSTRAINT [DF_EXBONDMASTER_TYPEID]  DEFAULT (0),
	[CONTNRSID] [int] NULL CONSTRAINT [DF_EXBONDMASTER_CONTRSID]  DEFAULT (0),
	[PRDTGID] [int] NULL CONSTRAINT [DF_EXBONDMASTER_PRDTID]  DEFAULT (0),
	[EBNDCTYPE] [smallint] NULL CONSTRAINT [DF_EXBONDMASTER_CTYPE]  DEFAULT (0),
	[EBNDNOC] [int] NULL CONSTRAINT [DF_EXBONDMASTER_EBNDDCONTRS]  DEFAULT (0),
	[EBNDNOP] [numeric](18, 2) NULL CONSTRAINT [DF_EXBONDMASTER_EBNDDNOP]  DEFAULT (0),
	[EBNDSPC] [numeric](18, 2) NULL CONSTRAINT [DF_EXBONDMASTER_EBNDDSPC]  DEFAULT (0),
	[EBNDASSAMT] [numeric](18, 2) NULL CONSTRAINT [DF_EXBONDMASTER_EBNDDASSAMT]  DEFAULT (0),
	[EBNDDTYAMT] [numeric](18, 2) NULL CONSTRAINT [DF_EXBONDMASTER_EBNDDDTYAMT]  DEFAULT (0),
	[EBNDINSAMT] [numeric](18, 2) NULL CONSTRAINT [DF_EXBONDMASTER_EBNDDINSAMT]  DEFAULT (0),
	[EBNDBSPC] [numeric](18, 2) NULL CONSTRAINT [DF_EXBONDMASTER_EBNDDBSPC]  DEFAULT (0),
	[EBNDBCFAMT] [numeric](18, 2) NULL CONSTRAINT [DF_EXBONDMASTER_EBNDBCFAMT]  DEFAULT (0),
	[EBNDBDTYAMT] [numeric](18, 2) NULL CONSTRAINT [DF_EXBONDMASTER_EBNDBDTYAMT]  DEFAULT (0),
	[EBNDDBINSAMT] [numeric](18, 2) NULL CONSTRAINT [DF_EXBONDMASTER_EBNDDBINSAMT]  DEFAULT (0),
	[STRGSDATE] [smalldatetime] NULL CONSTRAINT [DF_EXBONDMASTER_STRGSDATE]  DEFAULT (null),
	[STRGEDATE] [smalldatetime] NULL CONSTRAINT [DF_EXBONDMASTER_STRGEDATE]  DEFAULT (null),
	[INSRSDATE] [smalldatetime] NULL CONSTRAINT [DF_EXBONDMASTER_INSRSDATE]  DEFAULT (null),
	[INSREDATE] [smalldatetime] NULL CONSTRAINT [DF_EXBONDMASTER_INSREDATE]  DEFAULT (null),
	[INVDID] [int] NULL CONSTRAINT [DF_EXBONDMASTER_INVDID1]  DEFAULT (0),
	[CUSRID] VARCHAR(100) NULL CONSTRAINT [DF_EXBONDMASTER_CUSRID]  DEFAULT (NULL),
	[LMUSRID] VARCHAR(100) NULL CONSTRAINT [DF_EXBONDMASTER_LMUSRID]  DEFAULT (NULL),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_EXBONDMASTER_DISPSTATUS]  DEFAULT (0),
	[PRCSDATE] [smalldatetime] NULL CONSTRAINT [DF_EXBONDMASTER_PRCSDATE]  DEFAULT (null),
	[EBNDEDATE] [smalldatetime] NULL CONSTRAINT [DF_EXBONDMASTER_EBNDDATE1]  DEFAULT (null),
	[EBNDREMKRS] [varchar](100) NULL CONSTRAINT [DF_EXBONDMASTER_EBNDREMKRS]  DEFAULT (NULL),
 CONSTRAINT [PK_EXBONDMASTER] PRIMARY KEY CLUSTERED 
(
	[EBNDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE [SCFS_ERP]
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BONDGODOWNMASTER_BONDGODOWNTYPEMASTER]') AND parent_object_id = OBJECT_ID(N'[dbo].[BONDGODOWNMASTER]'))
ALTER TABLE [dbo].[BONDGODOWNMASTER] DROP CONSTRAINT [FK_BONDGODOWNMASTER_BONDGODOWNTYPEMASTER]
GO
/****** Object:  Table [dbo].[BONDGODOWNTYPEMASTER]    Script Date: 26/08/2022 17:47:28 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BONDGODOWNTYPEMASTER]') AND type in (N'U'))
DROP TABLE [dbo].[BONDGODOWNTYPEMASTER]
GO
/****** Object:  Table [dbo].[BONDGODOWNMASTER]    Script Date: 26/08/2022 17:47:28 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BONDGODOWNMASTER]') AND type in (N'U'))
DROP TABLE [dbo].[BONDGODOWNMASTER]
GO
/****** Object:  Table [dbo].[BONDGODOWNMASTER]    Script Date: 26/08/2022 17:47:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BONDGODOWNMASTER]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[BONDGODOWNMASTER](
	[GWNID] [int] NOT NULL identity(1,1) ,
	[GWNTID] [int] NULL CONSTRAINT [DF_BONDGODOWNMASTER_GWNTID]  DEFAULT (null),
	[GWNDESC] [varchar](100) NULL CONSTRAINT [DF_BONDGODOWNMASTER_GWNDESC]  DEFAULT (null),
	[GWNCODE] [varchar](50) NULL CONSTRAINT [DF_BONDGODOWNMASTER_GWNCODE]  DEFAULT (null),
	[GWNSPC] [numeric](18, 2) NULL CONSTRAINT [DF_BONDGODOWNMASTER_GWNSPC]  DEFAULT (0),
	[GWNADDR] [varchar](250) NULL CONSTRAINT [DF_BONDGODOWNMASTER_GWNADDR]  DEFAULT (null),
	[CUSRID] [varchar] (50) NULL CONSTRAINT [DF_BONDGODOWNMASTER_CUSRID]  DEFAULT (''),
	[LMUSRID] [varchar] (50) NULL CONSTRAINT [DF_BONDGODOWNMASTER_LMUSRID]  DEFAULT (''),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_BONDGODOWNMASTER_DISPSTATUS]  DEFAULT (0),
	[PRCSDATE] [smalldatetime] NULL CONSTRAINT [DF_BONDGODOWNMASTER_PRCSDATE]  DEFAULT (null),
 CONSTRAINT [PK_BONDGODOWNMASTER] PRIMARY KEY CLUSTERED 
(
	[GWNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[BONDGODOWNTYPEMASTER]    Script Date: 26/08/2022 17:47:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BONDGODOWNTYPEMASTER]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[BONDGODOWNTYPEMASTER](
	[GWNTID] [int] NOT NULL identity(1,1) ,
	[GWNTDESC] [nvarchar](100) NULL CONSTRAINT [DF_BONDGODOWNTYPEMASTER_GWNTDESC]  DEFAULT (null),
	[GWNTCODE] [nvarchar](10) NULL CONSTRAINT [DF_BONDGODOWNTYPEMASTER_GWNTCODE]  DEFAULT (null),
	[CUSRID] [varchar] (50) NULL CONSTRAINT [DF_BONDGODOWNTYPEMASTER_CUSRID]  DEFAULT (''),
	[LMUSRID] [varchar] (50) NULL CONSTRAINT [DF_BONDGODOWNTYPEMASTER_LMUSRID]  DEFAULT (''),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_BONDGODOWNTYPEMASTER_DISPSTATUS]  DEFAULT (0),
	[PRCSDATE] [smalldatetime] NULL CONSTRAINT [DF_BONDGODOWNTYPEMASTER_PRCSDATE]  DEFAULT (null),
 CONSTRAINT [PK_BONDGODOWNTYPEMASTER] PRIMARY KEY CLUSTERED 
(
	[GWNTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
set identity_insert [BONDGODOWNTYPEMASTER] on 
INSERT [dbo].[BONDGODOWNTYPEMASTER] ([GWNTID], [GWNTDESC], [GWNTCODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (1, N'Of all BONDGODOWNs….!', N'ALL', 1, 1, 1, CAST(N'2006-02-07 00:00:00' AS SmallDateTime))
INSERT [dbo].[BONDGODOWNTYPEMASTER] ([GWNTID], [GWNTDESC], [GWNTCODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (2, N'OWNED', N'OWN', 1, 1, 0, CAST(N'2006-08-10 00:00:00' AS SmallDateTime))
INSERT [dbo].[BONDGODOWNTYPEMASTER] ([GWNTID], [GWNTDESC], [GWNTCODE], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (3, N'RENTAL', N'RENT', 1, 1, 0, CAST(N'2006-08-10 00:00:00' AS SmallDateTime))
set identity_insert [BONDGODOWNTYPEMASTER] off

set identity_insert [BONDGODOWNMASTER] on 
INSERT [dbo].[BONDGODOWNMASTER] ([GWNID], [GWNTID], [GWNDESC], [GWNCODE], [GWNSPC], [GWNADDR], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (1, 1, N'Of all BONDGODOWNs….!', N'all', CAST(0.00 AS Numeric(18, 2)), NULL, 1, 1, 1, CAST(N'2006-02-07 00:00:00' AS SmallDateTime))
INSERT [dbo].[BONDGODOWNMASTER] ([GWNID], [GWNTID], [GWNDESC], [GWNCODE], [GWNSPC], [GWNADDR], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (2, 2, N'CFSC - SANCO 1', N'MAA1U0040', CAST(0.00 AS Numeric(18, 2)), NULL, 1, 1, 0, CAST(N'2016-08-01 00:00:00' AS SmallDateTime))
INSERT [dbo].[BONDGODOWNMASTER] ([GWNID], [GWNTID], [GWNDESC], [GWNCODE], [GWNSPC], [GWNADDR], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (12, 3, N'O Y', N'C018', CAST(889.00 AS Numeric(18, 2)), NULL, 1, 1, 0, CAST(N'2006-12-13 00:00:00' AS SmallDateTime))
INSERT [dbo].[BONDGODOWNMASTER] ([GWNID], [GWNTID], [GWNDESC], [GWNCODE], [GWNSPC], [GWNADDR], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (16, 3, N'I M I', N'MAA1U0041', CAST(1200.00 AS Numeric(18, 2)), NULL, 1, 1, 0, CAST(N'2007-08-23 00:00:00' AS SmallDateTime))
INSERT [dbo].[BONDGODOWNMASTER] ([GWNID], [GWNTID], [GWNDESC], [GWNCODE], [GWNSPC], [GWNADDR], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (17, 3, N'ANG', N'C075', CAST(7079.00 AS Numeric(18, 2)), NULL, 1, 1, 0, CAST(N'2009-10-31 00:00:00' AS SmallDateTime))
INSERT [dbo].[BONDGODOWNMASTER] ([GWNID], [GWNTID], [GWNDESC], [GWNCODE], [GWNSPC], [GWNADDR], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (22, 2, N'SECTION49', N'MAA1U0040', CAST(0.00 AS Numeric(18, 2)), N'#No. 224/1, Ennore Express High Road,', 1, 1, 0, CAST(N'2016-09-01 00:00:00' AS SmallDateTime))
set identity_insert [BONDGODOWNMASTER] off
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BONDGODOWNMASTER_BONDGODOWNTYPEMASTER]') AND parent_object_id = OBJECT_ID(N'[dbo].[BONDGODOWNMASTER]'))
ALTER TABLE [dbo].[BONDGODOWNMASTER]  WITH NOCHECK ADD  CONSTRAINT [FK_BONDGODOWNMASTER_BONDGODOWNTYPEMASTER] FOREIGN KEY([GWNTID])
REFERENCES [dbo].[BONDGODOWNTYPEMASTER] ([GWNTID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_BONDGODOWNMASTER_BONDGODOWNTYPEMASTER]') AND parent_object_id = OBJECT_ID(N'[dbo].[BONDGODOWNMASTER]'))
ALTER TABLE [dbo].[BONDGODOWNMASTER] CHECK CONSTRAINT [FK_BONDGODOWNMASTER_BONDGODOWNTYPEMASTER]
GO

USE SCFS_ERP
GO




ALTER TABLE [dbo].[BONDSLABMASTER] DROP CONSTRAINT [FK_BONDSLABMASTER_BONDSLABTYPEMASTER]
GO

/****** Object:  Table [dbo].[BONDSLABMASTER]    Script Date: 22/08/2022 14:28:41 ******/
DROP TABLE [dbo].[BONDSLABMASTER]
go


ALTER TABLE [dbo].[BONDSLABTYPEMASTER] DROP CONSTRAINT [FK_BONDSLABTYPEMASTER_BONDSLABCLASSIFICATIONMASTER]
GO

/****** Object:  Table [dbo].[BONDSLABTYPEMASTER]    Script Date: 22/08/2022 14:28:58 ******/
DROP TABLE [dbo].[BONDSLABTYPEMASTER]
GO



/****** Object:  Table [dbo].[BONDSLABCLASSIFICATIONMASTER]    Script Date: 22/08/2022 14:28:04 ******/
DROP TABLE [dbo].[BONDSLABCLASSIFICATIONMASTER]
GO

/****** Object:  Table [dbo].[BONDSLABCLASSIFICATIONMASTER]    Script Date: 22/08/2022 14:28:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BONDSLABCLASSIFICATIONMASTER](
	[SLABCID] [int] NOT NULL CONSTRAINT [DF_BONDSLABCLASSIFICATIONMASTER_SLABCID]  DEFAULT (0),
	[SLABCDESC] [varchar](100) NULL CONSTRAINT [DF_BONDSLABCLASSIFICATIONMASTER_SLABCDESC]  DEFAULT (null),
	[SLABCCODE] [varchar](50) NULL CONSTRAINT [DF_BONDSLABCLASSIFICATIONMASTER_SLABCCODE]  DEFAULT (null),
	[DISPORDR] [smallint] NULL CONSTRAINT [DF_BONDSLABCLASSIFICATIONMASTER_DISPORDR]  DEFAULT (0),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_BONDSLABCLASSIFICATIONMASTER_DISPSTATUS]  DEFAULT (0),
	[PRCSDATE] [smalldatetime] NULL CONSTRAINT [DF_BONDSLABCLASSIFICATIONMASTER_PRCSDATE]  DEFAULT (null),
 CONSTRAINT [PK_BONDSLABCLASSIFICATIONMASTER] PRIMARY KEY CLUSTERED 
(
	[SLABCID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE SCFS_ERP
GO

/****** Object:  Table [dbo].[BONDSLABTYPEMASTER]    Script Date: 22/08/2022 14:28:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BONDSLABTYPEMASTER](
	[SLABTID] [int] NOT NULL CONSTRAINT [DF_BONDSLABTYPEMASTER_SLABTID]  DEFAULT (0),
	[SLABCID] [int] NOT NULL CONSTRAINT [DF_BONDSLABTYPEMASTER_SLABCID]  DEFAULT (0),
	[SLABTDESC] [varchar](50) NULL CONSTRAINT [DF_BONDSLABTYPEMASTER_SLABTDESC]  DEFAULT (null),
	[SLABTCODE] [varchar](15) NULL CONSTRAINT [DF_BONDSLABTYPEMASTER_SLABTCODE]  DEFAULT (null),
	[SLABPTYPE] [smallint] NULL CONSTRAINT [DF_BONDSLABTYPEMASTER_SLABPTYPE]  DEFAULT (0),
	[SLABCTYPE] [smallint] NULL CONSTRAINT [DF_BONDSLABTYPEMASTER_SLABCTYPE]  DEFAULT (0),
	[DISPORDER] [int] NOT NULL CONSTRAINT [DF_BONDSLABTYPEMASTER_DISPORDER]  DEFAULT (0),
	[CUSRID] VARCHAR(100) NULL CONSTRAINT [DF_BONDSLABTYPEMASTER_CUSRID]  DEFAULT (NULL),
	[LMUSRID] VARCHAR(100) NULL CONSTRAINT [DF_BONDSLABTYPEMASTER_LMUSRID]  DEFAULT (NULL),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_BONDSLABTYPEMASTER_DISPSTATUS]  DEFAULT (0),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_BONDSLABTYPEMASTER_PRCSDATE]  DEFAULT (null),
 CONSTRAINT [PK_BONDSLABTYPEMASTER] PRIMARY KEY CLUSTERED 
(
	[SLABTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[BONDSLABTYPEMASTER]  WITH CHECK ADD  CONSTRAINT [FK_BONDSLABTYPEMASTER_BONDSLABCLASSIFICATIONMASTER] FOREIGN KEY([SLABCID])
REFERENCES [dbo].[BONDSLABCLASSIFICATIONMASTER] ([SLABCID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BONDSLABTYPEMASTER] CHECK CONSTRAINT [FK_BONDSLABTYPEMASTER_BONDSLABCLASSIFICATIONMASTER]
GO


USE SCFS_ERP
GO

/****** Object:  Table [dbo].[BONDSLABMASTER]    Script Date: 22/08/2022 14:28:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BONDSLABMASTER](
	[SLABMID] [int] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_SLABMID]  DEFAULT (0),
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_COMPYID]  DEFAULT (0),
	[SLABMDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_SLABMDATE]  DEFAULT (null),
	[SLABTID] [int] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_SLABTID]  DEFAULT (0),
	[TARIFFMID] [int] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_TARIFFMID]  DEFAULT (0),
	[CHAID] [int] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_STMRID]  DEFAULT (0),
	[CHRGETYPE] [smallint] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_CHRGETYPE]  DEFAULT (0),
	[CONTNRSID] [int] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_CONTNRSID]  DEFAULT (0),
	[PRDTGID] [int] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_PRDTGID]  DEFAULT (0),
	[SDTYPE] [smallint] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_SDTYPE]  DEFAULT (0),
	[YRDTYPE] [smallint] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_YRDTYPE]  DEFAULT (0),
	[HTYPE] [smallint] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_HTYPE]  DEFAULT (0),
	[WTYPE] [smallint] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_WTYPE]  DEFAULT (0),
	[SLABMIN] [numeric](18, 2) NOT NULL CONSTRAINT [DF_BONDSLABMASTER_SLABMIN]  DEFAULT (0),
	[SLABMAX] [numeric](18, 2) NOT NULL CONSTRAINT [DF_BONDSLABMASTER_SLABMAX]  DEFAULT (0),
	[SLABAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_BONDSLABMASTER_SLABAMT]  DEFAULT (0),
	[CUSRID] VARCHAR(100) NOT NULL CONSTRAINT [DF_BONDSLABMASTER_CUSRID]  DEFAULT (NULL),
	[LMUSRID] VARCHAR(100) NOT NULL CONSTRAINT [DF_BONDSLABMASTER_CUSRID1]  DEFAULT (0),
	[DISPSTATUS] [smallint] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_DISPSTATUS]  DEFAULT (0),
	[PRCSDATE] [datetime] NOT NULL CONSTRAINT [DF_BONDSLABMASTER_PRCSDATE]  DEFAULT (null),
 CONSTRAINT [PK_BONDSLABMASTER] PRIMARY KEY CLUSTERED 
(
	[SLABMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BONDSLABMASTER]  WITH NOCHECK ADD  CONSTRAINT [FK_BONDSLABMASTER_BONDSLABTYPEMASTER] FOREIGN KEY([SLABTID])
REFERENCES [dbo].[BONDSLABTYPEMASTER] ([SLABTID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[BONDSLABMASTER] CHECK CONSTRAINT [FK_BONDSLABMASTER_BONDSLABTYPEMASTER]
GO




USE SCFS_ERP
GO

/****** Object:  Table [dbo].[BONDTARIFFMASTER]    Script Date: 22/08/2022 14:32:32 ******/
DROP TABLE [dbo].[BONDTARIFFMASTER]
GO

/****** Object:  Table [dbo].[BONDTARIFFMASTER]    Script Date: 22/08/2022 14:32:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BONDTARIFFMASTER](
	[TARIFFMID] [int] NOT NULL CONSTRAINT [DF_BONDTARIFFMASTER_TARIFFMID]  DEFAULT (0),
	[TARIFFMDESC] [varchar](100) NOT NULL CONSTRAINT [DF_BONDTARIFFMASTER_TARIFFMDESC]  DEFAULT (null),
	[TARIFFMCODE] [varchar](10) NOT NULL CONSTRAINT [DF_BONDTARIFFMASTER_TARIFFMCODE]  DEFAULT (null),
	[SDPTID] [int] NOT NULL CONSTRAINT [DF_BONDTARIFFMASTER_SDPTID]  DEFAULT (0),
	[CUSRID] VARCHAR(100) NOT NULL CONSTRAINT [DF_BONDTARIFFMASTER_CUSRID]  DEFAULT (0),
	[LMUSRID] VARCHAR(100) NOT NULL CONSTRAINT [DF_BONDTARIFFMASTER_LMUSRID]  DEFAULT (0),
	[DISPSTATUS] [smallint] NOT NULL CONSTRAINT [DF_BONDTARIFFMASTER_DISPSTATUS]  DEFAULT (0),
	[PRCSDATE] [datetime] NOT NULL CONSTRAINT [DF_BONDTARIFFMASTER_PRCSDATE]  DEFAULT (null),
 CONSTRAINT [PK_BONDTARIFFMASTER] PRIMARY KEY CLUSTERED 
(
	[TARIFFMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE SCFS_ERP
GO

/****** Object:  Table [dbo].[TMP_EXBOND_DELIVERED]    Script Date: 22/08/2022 14:33:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[TMP_EXBOND_ID]    Script Date: 22/08/2022 14:33:22 ******/
DROP TABLE [dbo].[TMP_EXBOND_DELIVERED]
GO

CREATE TABLE [dbo].[TMP_EXBOND_DELIVERED](
	[BNDID] [int] NOT NULL CONSTRAINT [DF_TMP_EXBOND_DELIVERED_BNDID]  DEFAULT ((0)),
	[EBNDNOP] [numeric](18, 2) NOT NULL CONSTRAINT [DF_TMP_EXBOND_DELIVERED_EBNDNOP]  DEFAULT ((0)),
	[EBNDIAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_TMP_EXBOND_DELIVERED_EBNDIAMT]  DEFAULT ((0)),
	[EBNDSPC] [numeric](18, 2) NOT NULL CONSTRAINT [DF_TMP_EXBOND_DELIVERED_EBNDNOP1]  DEFAULT ((0)),
	[EBNDASSAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_TMP_EXBOND_DELIVERED_EBNDASSAMT]  DEFAULT ((0)),
	[EBNDDTYAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_TMP_EXBOND_DELIVERED_EBNDDTYAMT]  DEFAULT ((0))
) ON [PRIMARY]

GO


USE SCFS_ERP
GO

/****** Object:  Table [dbo].[TMP_EXBOND_ID]    Script Date: 22/08/2022 14:33:22 ******/
DROP TABLE [dbo].[TMP_EXBOND_ID]
GO

/****** Object:  Table [dbo].[TMP_EXBOND_ID]    Script Date: 22/08/2022 14:33:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TMP_EXBOND_ID](
	[EBNDID] [int] NOT NULL CONSTRAINT [DF_TMP_EXBOND_ID_EBNDID]  DEFAULT ((0))
) ON [PRIMARY]

GO


USE SCFS_ERP
GO

ALTER TABLE [dbo].[TMP_EXBOND_PREVIOUS_AMT] DROP CONSTRAINT [DF_TMP_EXBOND_PREVIOUS_AMT_ASSGN_EBNDINSAMT]
GO

ALTER TABLE [dbo].[TMP_EXBOND_PREVIOUS_AMT] DROP CONSTRAINT [DF_TMP_EXBOND_PREVIOUS_AMT_ASSGN_EBNDDTYAMT]
GO

ALTER TABLE [dbo].[TMP_EXBOND_PREVIOUS_AMT] DROP CONSTRAINT [DF_TMP_EXBOND_PREVIOUS_AMT_ASSGN_EBNDCIFAMT]
GO

ALTER TABLE [dbo].[TMP_EXBOND_PREVIOUS_AMT] DROP CONSTRAINT [DF_TMP_EXBOND_PREVIOUS_AMT_ASSGN_BNDID]
GO

/****** Object:  Table [dbo].[TMP_EXBOND_PREVIOUS_AMT]    Script Date: 22/08/2022 14:33:32 ******/
DROP TABLE [dbo].[TMP_EXBOND_PREVIOUS_AMT]
GO

/****** Object:  Table [dbo].[TMP_EXBOND_PREVIOUS_AMT]    Script Date: 22/08/2022 14:33:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TMP_EXBOND_PREVIOUS_AMT](
	[BNDID] [int] NOT NULL,
	[EBNDCIFAMT] [numeric](18, 2) NULL,
	[EBNDDTYAMT] [numeric](18, 2) NULL,
	[EBNDINSAMT] [numeric](18, 2) NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TMP_EXBOND_PREVIOUS_AMT] ADD  CONSTRAINT [DF_TMP_EXBOND_PREVIOUS_AMT_ASSGN_BNDID]  DEFAULT (0) FOR [BNDID]
GO

ALTER TABLE [dbo].[TMP_EXBOND_PREVIOUS_AMT] ADD  CONSTRAINT [DF_TMP_EXBOND_PREVIOUS_AMT_ASSGN_EBNDCIFAMT]  DEFAULT (0) FOR [EBNDCIFAMT]
GO

ALTER TABLE [dbo].[TMP_EXBOND_PREVIOUS_AMT] ADD  CONSTRAINT [DF_TMP_EXBOND_PREVIOUS_AMT_ASSGN_EBNDDTYAMT]  DEFAULT (0) FOR [EBNDDTYAMT]
GO

ALTER TABLE [dbo].[TMP_EXBOND_PREVIOUS_AMT] ADD  CONSTRAINT [DF_TMP_EXBOND_PREVIOUS_AMT_ASSGN_EBNDINSAMT]  DEFAULT (0) FOR [EBNDINSAMT]
GO



--USE SCFS_ERP
--GO

--EXEC sys.sp_dropextendedproperty @name=N'MS_DiagramPaneCount' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_BOND STORAGE INSURANCE CAL'

--GO

--EXEC sys.sp_dropextendedproperty @name=N'MS_DiagramPane1' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_BOND STORAGE INSURANCE CAL'

--GO

--/****** Object:  View [dbo].[VW_BOND STORAGE INSURANCE CAL]    Script Date: 22/08/2022 14:34:20 ******/
--DROP VIEW [dbo].[VW_BOND STORAGE INSURANCE CAL]
--GO

--/****** Object:  View [dbo].[VW_BOND STORAGE INSURANCE CAL]    Script Date: 22/08/2022 14:34:20 ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

--CREATE VIEW [dbo].[VW_BOND STORAGE INSURANCE CAL]
--AS
--SELECT     dbo.TRANSACTIONMASTER.TRANDNO, dbo.TRANSACTIONDETAIL.TRANSFDATE, dbo.TRANSACTIONDETAIL.TRANSEDATE, dbo.TRANSACTIONDETAIL.TRANIFDATE, 
--                      dbo.TRANSACTIONDETAIL.TRANIEDATE, dbo.TRANSACTIONDETAIL.TRANDQTY, dbo.TRANSACTIONDETAIL.TRANDNOP, dbo.TRANSACTIONDETAIL.TRANDEIAMT, 
--                      dbo.TRANSACTIONDETAIL.TRANDGAMT, dbo.TRANSACTIONDETAIL.TRANDSAMT, dbo.TRANSACTIONDETAIL.TRANDHAMT, dbo.TRANSACTIONDETAIL.TRANDIAMT, 
--                      dbo.TRANSACTIONDETAIL.TRANDNAMT, dbo.TRANSACTIONMASTER.TRANGAMT, dbo.TRANSACTIONMASTER.TRANSAMT, dbo.TRANSACTIONMASTER.TRANHAMT, 
--                      dbo.TRANSACTIONMASTER.TRANNAMT, dbo.TRANSACTIONMASTER.TRANDATE, dbo.TRANSACTIONMASTER.TRANBTYPE
--FROM         dbo.TRANSACTIONMASTER INNER JOIN
--                      dbo.TRANSACTIONDETAIL ON dbo.TRANSACTIONMASTER.TRANMID = dbo.TRANSACTIONDETAIL.TRANMID
--WHERE     (dbo.TRANSACTIONMASTER.TRANDATE BETWEEN CONVERT(DATETIME, '2018-04-01 00:00:00', 102) AND CONVERT(DATETIME, '2019-12-31 00:00:00', 102)) AND 
--                      (dbo.TRANSACTIONMASTER.TRANBTYPE IN (1, 4, 5))

--GO

--EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
--Begin DesignProperties = 
--   Begin PaneConfigurations = 
--      Begin PaneConfiguration = 0
--         NumPanes = 4
--         Configuration = "(H (1[41] 4[13] 2[3] 3) )"
--      End
--      Begin PaneConfiguration = 1
--         NumPanes = 3
--         Configuration = "(H (1 [50] 4 [25] 3))"
--      End
--      Begin PaneConfiguration = 2
--         NumPanes = 3
--         Configuration = "(H (1 [50] 2 [25] 3))"
--      End
--      Begin PaneConfiguration = 3
--         NumPanes = 3
--         Configuration = "(H (4 [30] 2 [40] 3))"
--      End
--      Begin PaneConfiguration = 4
--         NumPanes = 2
--         Configuration = "(H (1 [56] 3))"
--      End
--      Begin PaneConfiguration = 5
--         NumPanes = 2
--         Configuration = "(H (2 [66] 3))"
--      End
--      Begin PaneConfiguration = 6
--         NumPanes = 2
--         Configuration = "(H (4 [50] 3))"
--      End
--      Begin PaneConfiguration = 7
--         NumPanes = 1
--         Configuration = "(V (3))"
--      End
--      Begin PaneConfiguration = 8
--         NumPanes = 3
--         Configuration = "(H (1[56] 4[18] 2) )"
--      End
--      Begin PaneConfiguration = 9
--         NumPanes = 2
--         Configuration = "(H (1 [75] 4))"
--      End
--      Begin PaneConfiguration = 10
--         NumPanes = 2
--         Configuration = "(H (1[66] 2) )"
--      End
--      Begin PaneConfiguration = 11
--         NumPanes = 2
--         Configuration = "(H (4 [60] 2))"
--      End
--      Begin PaneConfiguration = 12
--         NumPanes = 1
--         Configuration = "(H (1) )"
--      End
--      Begin PaneConfiguration = 13
--         NumPanes = 1
--         Configuration = "(V (4))"
--      End
--      Begin PaneConfiguration = 14
--         NumPanes = 1
--         Configuration = "(V (2))"
--      End
--      ActivePaneConfig = 0
--   End
--   Begin DiagramPane = 
--      Begin Origin = 
--         Top = 0
--         Left = 0
--      End
--      Begin Tables = 
--         Begin Table = "TRANSACTIONMASTER"
--            Begin Extent = 
--               Top = 6
--               Left = 38
--               Bottom = 318
--               Right = 204
--            End
--            DisplayFlags = 280
--            TopColumn = 0
--         End
--         Begin Table = "TRANSACTIONDETAIL"
--            Begin Extent = 
--               Top = 6
--               Left = 242
--               Bottom = 337
--               Right = 397
--            End
--            DisplayFlags = 280
--            TopColumn = 8
--         End
--      End
--   End
--   Begin SQLPane = 
--   End
--   Begin DataPane = 
--      Begin ParameterDefaults = ""
--      End
--      Begin ColumnWidths = 20
--         Width = 284
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--      End
--   End
--   Begin CriteriaPane = 
--      Begin ColumnWidths = 11
--         Column = 1440
--         Alias = 900
--         Table = 1170
--         Output = 720
--         Append = 1400
--         NewValue = 1170
--         SortType = 1350
--         SortOrder = 1410
--         GroupBy = 1350
--         Filter = 1350
--         Or = 1350
--         Or = 1350
--         Or = 1350
--      End
--   End
--End
--' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_BOND STORAGE INSURANCE CAL'
--GO

--EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_BOND STORAGE INSURANCE CAL'
--GO


USE SCFS_ERP
GO

/****** Object:  View [dbo].[VW_BOND_CHA_TEUS_DETAIL_ASSGN]    Script Date: 22/08/2022 14:35:37 ******/
DROP VIEW [dbo].[VW_BOND_CHA_TEUS_DETAIL_ASSGN]
GO

/****** Object:  View [dbo].[VW_BOND_CHA_TEUS_DETAIL_ASSGN]    Script Date: 22/08/2022 14:35:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


create VIEW [dbo].[VW_BOND_CHA_TEUS_DETAIL_ASSGN]
AS
SELECT        dbo.TMPRPT_IDS.KUSRID, dbo.BONDMASTER.BNDDATE, dbo.CATEGORYMASTER.CATENAME, SUM(CASE BNDTYPE WHEN 0 THEN BND20 ELSE 0 END) 
                         AS ACOL20, SUM(CASE BNDTYPE WHEN 0 THEN BND40 ELSE 0 END) AS ACOL40, SUM(CASE BNDTYPE WHEN 1 THEN BND20 ELSE 0 END) AS BCOL20, 
                         SUM(CASE BNDTYPE WHEN 1 THEN BND40 ELSE 0 END) AS BCOL40
FROM            dbo.BONDMASTER INNER JOIN
                         dbo.CATEGORYMASTER ON dbo.BONDMASTER.CHAID = dbo.CATEGORYMASTER.CATEID INNER JOIN
                         dbo.TMPRPT_IDS ON dbo.BONDMASTER.BNDID = dbo.TMPRPT_IDS.RPTID
GROUP BY dbo.BONDMASTER.BNDDATE, dbo.CATEGORYMASTER.CATENAME, dbo.TMPRPT_IDS.KUSRID


GO


--USE SCFS_ERP
--GO

--/****** Object:  View [dbo].[VW_BOND_DETAIL_FLX_ASSGN]    Script Date: 22/08/2022 14:36:22 ******/
--DROP VIEW [dbo].[VW_BOND_DETAIL_FLX_ASSGN]
--GO

--/****** Object:  View [dbo].[VW_BOND_DETAIL_FLX_ASSGN]    Script Date: 22/08/2022 14:36:22 ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

--CREATE VIEW [dbo].[VW_BOND_DETAIL_FLX_ASSGN]
--AS
--SELECT     dbo.BONDDETAIL.BNDDID, dbo.BONDDETAIL.BNDID, dbo.BONDDETAIL.PRDTGID, dbo.PRODUCTGROUPMASTER.PRDTGDESC, 
--                      dbo.BONDGODOWNMASTER.GWNDESC, dbo.BONDDETAIL.BNDNOP, dbo.BONDDETAIL.BNDSPC, dbo.BONDDETAIL.BNDBNOP, 
--                      dbo.BONDDETAIL.BNDBSPC, dbo.BONDDETAIL.BNDHAMT, dbo.BONDDETAIL.GWNID, dbo.BONDDETAIL.STRGSDATE, dbo.BONDDETAIL.STRGEDATE, 
--                      dbo.BONDDETAIL.INSRSDATE, dbo.BONDDETAIL.INSREDATE
--FROM         dbo.BONDDETAIL INNER JOIN
--                      dbo.PRODUCTGROUPMASTER ON dbo.BONDDETAIL.PRDTGID = dbo.PRODUCTGROUPMASTER.PRDTGID INNER JOIN
--                      dbo.BONDGODOWNMASTER ON dbo.BONDDETAIL.GWNID = dbo.BONDGODOWNMASTER.GWNID

--GO


USE SCFS_ERP
GO

/****** Object:  Table [dbo].[BONDGATEINDETAIL]    Script Date: 22/08/2022 14:37:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
DROP TABLE [dbo].[BONDGATEINDETAIL]
GO

CREATE TABLE [dbo].[BONDGATEINDETAIL](
	[GIDID] [int] NOT NULL identity(1,1),
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_COMPYID]  DEFAULT ((0)),
	[SDPTID] [int] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_SDPTID]  DEFAULT ((0)),
	[GIDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_GIDATE]  DEFAULT (NULL),
	[GITIME] [datetime] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_GITIME]  DEFAULT (NULL),
	[GINO] [int] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_GINO]  DEFAULT ((0)),
	[GIDNO] [varchar](15) NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_GIDNO]  DEFAULT (NULL),
	[TRNSPRTID] [int] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_TRNSPRTID]  DEFAULT ((0)),
	[TRNSPRTNAME] [varchar](100) NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_TRNSPRTNAME]  DEFAULT (NULL),
	[VHLNO] [varchar](15) NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_VHLNO]  DEFAULT (NULL),
	[DRVNAME] [varchar](100) NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_DRVNAME]  DEFAULT (NULL),
	[IMPRTID] [int] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_IMPRTID]  DEFAULT ((0)),
	[IMPRTNAME] [varchar](100) NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_IMPRTNAME]  DEFAULT (NULL),
	[STMRID] [int] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_STMRID]  DEFAULT ((0)),
	[STMRNAME] [varchar](100) NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_STMRNAME]  DEFAULT (NULL),
	[CHAID] [int] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_CHAID]  DEFAULT ((0)),
	[CHANAME] [varchar](100) NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_CHANAME]  DEFAULT (NULL),
	[CONTNRTID] [int] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_CONTNRTID]  DEFAULT ((0)),
	[CONTNRID] [int] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_CONTNRID]  DEFAULT ((0)),
	[CONTNRSID] [int] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_CONTNRSID]  DEFAULT ((0)),
	[CONTNRNO] [varchar](15) NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_CONTNRNO]  DEFAULT (NULL),
	[VSLID] [int] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_VSLID]  DEFAULT ((0)),
	[VSLNAME] [varchar](100) NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_VSLNAME]  DEFAULT (NULL),
	[VOYNO] [varchar](10) NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_VOYNO]  DEFAULT (NULL),
	[IGMNO] [varchar](15) NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_IGMNO]  DEFAULT (NULL),
	[GPLNO] [varchar](15) NULL CONSTRAINT [DF_BONDGATEINDETAIL_GPLNO]  DEFAULT ((0)),
	[PRDTGID] [int] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_PRDTGID]  DEFAULT ((0)),
	[PRDTDESC] [varchar](100) NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_PRDTDESC]  DEFAULT (NULL),
	[UNITID] [int] NOT NULL CONSTRAINT [DF_BONDGATEINDETAIL_UNITID]  DEFAULT ((0)),
	[GPWGHT] [numeric](18, 4) NULL CONSTRAINT [DF_BONDGATEINDETAIL_GPWGHT]  DEFAULT ((0)),
	[GPNOP] [numeric](18, 2) NULL CONSTRAINT [DF_BONDGATEINDETAIL_GPNOP]  DEFAULT ((0)),
	[GPCBM] [numeric](18, 4) NULL CONSTRAINT [DF_BONDGATEINDETAIL_GPCBM]  DEFAULT ((0)),
	[BNDID] [int] NOT NULL CONSTRAINT [DF_Table_1_BNDID]  DEFAULT ((0)),
	[CONTNRRCVFRM] [int] NOT NULL CONSTRAINT [DF_Table_1_CONTNRRCVFRM]  DEFAULT ((0)),
	[CONTNRRCVFRMOTH] VARCHAR(100) NULL CONSTRAINT [DF_BONDGATEINDETAIL_CONTNRRCVFRMOTH]  DEFAULT ((NULL)),
	[GIREMKRS] [varchar](100) NULL CONSTRAINT [DF_BONDGATEINDETAIL_GIREMKRS]  DEFAULT (NULL),
	[CUSRID] VARCHAR(100) NULL CONSTRAINT [DF_BONDGATEINDETAIL_CUSRID]  DEFAULT ((NULL)),
	[LMUSRID] VARCHAR(100) NULL CONSTRAINT [DF_BONDGATEINDETAIL_LMUSRID]  DEFAULT ((NULL)),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_BONDGATEINDETAIL_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_BONDGATEINDETAIL_PRCSDATE]  DEFAULT (NULL),
 CONSTRAINT [PK_BONDGATEINDETAIL] PRIMARY KEY CLUSTERED 
(
	[GIDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE SCFS_ERP
GO

/****** Object:  Table [dbo].[BONDGATEOUTDETAIL]    Script Date: 22/08/2022 14:37:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING OFF
GO

DROP TABLE [dbo].[BONDGATEOUTDETAIL]
GO

CREATE TABLE [dbo].[BONDGATEOUTDETAIL](
	[GODID] [int] NOT NULL identity(1,1),
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_COMPYID]  DEFAULT ((0)),
	[SDPTID] [int] NOT NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_SDPTID]  DEFAULT ((0)),
	[GODATE] [smalldatetime] NOT NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_GODATE]  DEFAULT (NULL),
	[GOTIME] [datetime] NOT NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_GOTIME]  DEFAULT (NULL),
	[GONO] [int] NOT NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_GONO]  DEFAULT ((0)),
	[GODNO] [varchar](15) NOT NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_GODNO]  DEFAULT (NULL),
	[GIDID] [int] NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_GIDID]  DEFAULT ((0)),
	[VHLNO] [varchar](20) NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_VHLNO]  DEFAULT (NULL),
	[GDRVNAME] [varchar](50) NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_GDRVNAME]  DEFAULT (NULL),
	[CHASNAME] [varchar](50) NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_CHASNAME]  DEFAULT (NULL),
	[GOBTYPE] [smallint] NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_GOBTYPE]  DEFAULT ((0)),
	[CHAID] [int] NOT NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_CHAID]  DEFAULT ((0)),
	[GOREMRKS] [varchar](100) NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_GOREMRKS]  DEFAULT (NULL),
	[CUSRID] VARCHAR(100) NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_CUSRID]  DEFAULT ((NULL)),
	[LMUSRID] VARCHAR(100) NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_LMUSRID]  DEFAULT ((NULL)),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_BONDGATEOUTDETAIL_PRCSDATE]  DEFAULT (NULL),
 CONSTRAINT [PK_BONDGATEOUTDETAIL] PRIMARY KEY CLUSTERED 
(
	[GODID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


USE SCFS_ERP
GO

EXEC sys.sp_dropextendedproperty @name=N'MS_Description' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BONDVEHICLETICKETDETAIL', @level2type=N'COLUMN',@level2name=N'VTSTYPE'

GO

EXEC sys.sp_dropextendedproperty @name=N'MS_Description' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BONDVEHICLETICKETDETAIL', @level2type=N'COLUMN',@level2name=N'VTTYPE'

GO

/****** Object:  Table [dbo].[BONDVEHICLETICKETDETAIL]    Script Date: 22/08/2022 14:37:56 ******/
DROP TABLE [dbo].[BONDVEHICLETICKETDETAIL]
GO

/****** Object:  Table [dbo].[BONDVEHICLETICKETDETAIL]    Script Date: 22/08/2022 14:37:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BONDVEHICLETICKETDETAIL](
	[VTDID] [int] NOT NULL identity(1,1),
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_COMPYID]  DEFAULT ((0)),
	[SDPTID] [int] NOT NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_SDPTID]  DEFAULT ((0)),
	[VTDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTDATE]  DEFAULT (NULL),
	[VTTIME] [datetime] NOT NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTTIME]  DEFAULT (NULL),
	[VTNO] [int] NOT NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTNO]  DEFAULT ((0)),
	[VTDNO] [varchar](15) NOT NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTDNO]  DEFAULT (NULL),
	[VHLNO] [varchar](15) NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VHLNO]  DEFAULT (NULL),
	[DRVNAME] [varchar](100) NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_DRVNAME]  DEFAULT (NULL),
	[VTDESC] [varchar](100) NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_PRDTDESC]  DEFAULT (NULL),
	[VTQTY] [numeric](18, 2) NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTQTY]  DEFAULT ((0)),
	[VTTYPE] [int] NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTTYPE]  DEFAULT ((0)),
	[VTSTYPE] [int] NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTTYPE1]  DEFAULT ((0)),
	[VTREMRKS] [varchar](100) NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTREMKRS]  DEFAULT (NULL),
	[CUSRID] VARCHAR(100) NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_CUSRID]  DEFAULT ((NULL)),
	[LMUSRID] VARCHAR(100) NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_LMUSRID]  DEFAULT ((NULL)),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_PRCSDATE]  DEFAULT (NULL),
	[EBNDID] [int] NOT NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_EBNDID]  DEFAULT ((0)),
	[VTAREA] [numeric](18, 2) NOT NULL CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTAREA]  DEFAULT ((0)),
 CONSTRAINT [PK_BONDVEHICLETICKETDETAIL] PRIMARY KEY CLUSTERED 
(
	[VTDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 - LOAD, 2 - DESTUFF' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BONDVEHICLETICKETDETAIL', @level2type=N'COLUMN',@level2name=N'VTTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'0 - PART DESTUFF, 1 - FULL DESTUFF' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BONDVEHICLETICKETDETAIL', @level2type=N'COLUMN',@level2name=N'VTSTYPE'
GO


USE SCFS_ERP
GO

/****** Object:  Table [dbo].[BONDSPACEDETAIL]    Script Date: 22/08/2022 14:38:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
DROP TABLE [dbo].[BONDSPACEDETAIL]
GO

CREATE TABLE [dbo].[BONDSPACEDETAIL](
	[SPCID] [int] NOT NULL identity(1,1),
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_SPACEMASTER_COMPYID]  DEFAULT (0),
	[SDPTID] [int] NOT NULL CONSTRAINT [DF_BONDSPACEDETAIL_SDPTID]  DEFAULT (0),
	[SPCDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_SPACEMASTER_SPCDATE]  DEFAULT (null),
	[SPCTIME] [datetime] NULL CONSTRAINT [DF_BONDSPACEDETAIL_SPCDATE1]  DEFAULT (null),
	[SPCNO] [int] NULL CONSTRAINT [DF_SPACEMASTER_SPCNO]  DEFAULT (0),
	[SPCDNO] [varchar](50) NULL CONSTRAINT [DF_SPACEMASTER_DSPCNO]  DEFAULT (null),
	[SPCBENO] [varchar](50) NULL CONSTRAINT [DF_SPACEMASTER_SPCBENO]  DEFAULT (null),
	[SPCBEDATE] [smalldatetime] NULL CONSTRAINT [DF_SPACEMASTER_SPCBEDATE]  DEFAULT (null),
	[SPCBLNO] [varchar](50) NULL CONSTRAINT [DF_SPACEMASTER_SPCBLNO]  DEFAULT (null),
	[SPCBLDATE] [smalldatetime] NULL CONSTRAINT [DF_SPACEMASTER_SPCBLDATE]  DEFAULT (null),
	[IMPRTID] [int] NULL CONSTRAINT [DF_SPACEMASTER_CATEID]  DEFAULT (0),
	[PRDTID] [int] NULL CONSTRAINT [DF_SPACEMASTER_PRDTID]  DEFAULT (0),
	[TYPEID] [int] NULL CONSTRAINT [DF_SPACEMASTER_TYPEID]  DEFAULT (0),
	[QTY] [numeric](18, 2) NULL CONSTRAINT [DF_SPACEMASTER_QTY]  DEFAULT (0),
	[GWGHT] [numeric](18, 0) NULL CONSTRAINT [DF_SPACEMASTER_SPCGWGHT]  DEFAULT (0),
	[DQTY] [numeric](18, 0) NULL CONSTRAINT [DF_SPACEMASTER_INDDIM]  DEFAULT (0),
	[WGHT] [numeric](18, 0) NULL CONSTRAINT [DF_SPACEMASTER_DIMWGHT]  DEFAULT (0),
	[MTRS] [numeric](18, 0) NULL CONSTRAINT [DF_SPACEMASTER_SPCINMTR]  DEFAULT (0),
	[AAMT] [numeric](18, 0) NULL CONSTRAINT [DF_SPACEMASTER_SPCASSAMT]  DEFAULT (0),
	[DAMT] [numeric](18, 0) NULL CONSTRAINT [DF_SPACEMASTER_SPCDTYAMT]  DEFAULT (0),
	[SPCDESC] [varchar](100) NULL CONSTRAINT [DF_SPACEMASTER_SPCDESC]  DEFAULT (null),
	[SPCEDATE] [smalldatetime] NULL CONSTRAINT [DF_SPACEMASTER_SPCEDATE]  DEFAULT (null),
	[SPCSFDATE] [smalldatetime] NULL CONSTRAINT [DF_SPACEMASTER_SPCSFDATE]  DEFAULT (null),
	[SPCSTDATE] [smalldatetime] NULL CONSTRAINT [DF_SPACEMASTER_SPCSTDATE]  DEFAULT (null),
	[CUSRID] VARCHAR(100) NULL CONSTRAINT [DF_SPACEMASTER_CUSRID]  DEFAULT (0),
	[LMUSRID] VARCHAR(100) NULL CONSTRAINT [DF_SPACEMASTER_LMUSRID]  DEFAULT (0),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_SPACEMASTER_DISPSTATUS]  DEFAULT (0),
	[PRCSDATE] [smalldatetime] NULL CONSTRAINT [DF_SPACEMASTER_PRCSDATE]  DEFAULT (null),
 CONSTRAINT [PK_SPACEMASTER] PRIMARY KEY CLUSTERED 
(
	[SPCID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO





--USE SCFS_ERP
--GO

--/****** Object:  View [dbo].[VW_BOND_DETAIL_FLX_ASSGN]    Script Date: 22/08/2022 14:39:39 ******/
--DROP VIEW [dbo].[VW_BOND_DETAIL_FLX_ASSGN]
--GO

--/****** Object:  View [dbo].[VW_BOND_DETAIL_FLX_ASSGN]    Script Date: 22/08/2022 14:39:39 ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

--CREATE VIEW [dbo].[VW_BOND_DETAIL_FLX_ASSGN]
--AS
--SELECT     dbo.BONDDETAIL.BNDDID, dbo.BONDDETAIL.BNDID, dbo.BONDDETAIL.PRDTGID, dbo.PRODUCTGROUPMASTER.PRDTGDESC, 
--                      dbo.BONDGODOWNMASTER.GWNDESC, dbo.BONDDETAIL.BNDNOP, dbo.BONDDETAIL.BNDSPC, dbo.BONDDETAIL.BNDBNOP, 
--                      dbo.BONDDETAIL.BNDBSPC, dbo.BONDDETAIL.BNDHAMT, dbo.BONDDETAIL.GWNID, dbo.BONDDETAIL.STRGSDATE, dbo.BONDDETAIL.STRGEDATE, 
--                      dbo.BONDDETAIL.INSRSDATE, dbo.BONDDETAIL.INSREDATE
--FROM         dbo.BONDDETAIL INNER JOIN
--                      dbo.PRODUCTGROUPMASTER ON dbo.BONDDETAIL.PRDTGID = dbo.PRODUCTGROUPMASTER.PRDTGID INNER JOIN
--                      dbo.BONDGODOWNMASTER ON dbo.BONDDETAIL.GWNID = dbo.BONDGODOWNMASTER.GWNID

--GO


USE SCFS_ERP
GO

/****** Object:  View [dbo].[VW_IMPORTER_MASTER]    Script Date: 22/08/2022 15:02:23 ******/
DROP VIEW [dbo].[VW_IMPORTER_MASTER]
GO

/****** Object:  View [dbo].[VW_IMPORTER_MASTER]    Script Date: 22/08/2022 15:02:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_IMPORTER_MASTER]
AS
SELECT     CATEID AS IMPRTID, CATENAME AS IMPRTNAME, CATECODE AS IMPRTCODE, 0 AS CATEINSRDAYS, 0 AS IMPCATEWIPTYPE --CATEWIPTYPE
FROM         dbo.CATEGORYMASTER (NOLOCK)
WHERE     (CATETID = 1)



GO


USE SCFS_ERP
GO

--/****** Object:  View [dbo].[VW_BOND_QUERY_DETAIL_ASSGN]    Script Date: 22/08/2022 14:39:57 ******/
--DROP VIEW [dbo].[VW_BOND_QUERY_DETAIL_ASSGN]
--GO

--/****** Object:  View [dbo].[VW_BOND_QUERY_DETAIL_ASSGN]    Script Date: 22/08/2022 14:39:57 ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER OFF
--GO


--CREATE VIEW [dbo].[VW_BOND_QUERY_DETAIL_ASSGN]
--AS
--SELECT     dbo.BONDMASTER.BNDID, dbo.BONDMASTER.COMPYID, dbo.BONDMASTER.SDPTID, dbo.BONDMASTER.BNDNO, dbo.BONDMASTER.BNDDNO, 
--                      dbo.BONDMASTER.BNDDATE, dbo.BONDMASTER.BNDFDATE, dbo.BONDMASTER.BNDTDATE, dbo.BONDMASTER.BNDADATE, 
--                      dbo.BONDMASTER.IMPRTID, dbo.BONDMASTER.CHAID, dbo.BONDMASTER.YRDID, dbo.BONDMASTER.TYPEID, dbo.BONDMASTER.BNDBENO, 
--                      dbo.BONDMASTER.BNDBLNO, dbo.BONDMASTER.BNDIGMNO, dbo.BONDMASTER.BND20, dbo.BONDMASTER.BND40, 
--                      dbo.BONDMASTER.BNDGWGHT, dbo.BONDMASTER.BNDCIFAMT, dbo.BONDMASTER.BNDDTYAMT, dbo.BONDMASTER.BNDINSAMT, 
--                      dbo.BONDMASTER.BNDBCIFAMT, dbo.BONDMASTER.BNDBDTYAMT, dbo.BONDMASTER.BNDBINSAMT, dbo.BONDMASTER.GWNID, 
--                      dbo.BONDMASTER.PRDTGID, dbo.BONDMASTER.BNDNOP, dbo.BONDMASTER.BNDSPC, dbo.BONDMASTER.BNDBNOP, 
--                      dbo.BONDMASTER.BNDBSPC, dbo.BONDMASTER.BNDHAMT, dbo.BONDMASTER.STRGSDATE, dbo.BONDMASTER.STRGEDATE, 
--                      dbo.BONDMASTER.INSRSDATE, dbo.BONDMASTER.INSREDATE, dbo.BONDMASTER.CUSRID, dbo.BONDMASTER.LMUSRID, 
--                      dbo.BONDMASTER.DISPSTATUS, dbo.BONDMASTER.PRCSDATE, dbo.BONDGODOWNMASTER.GWNDESC, dbo.VW_CHA_MASTER.CHANAME, 
--                      dbo.VW_IMPORTER_MASTER.IMPRTNAME, dbo.PRODUCTGROUPMASTER.PRDTGDESC, dbo.YARDMASTER.YRDDESC
--FROM         dbo.BONDMASTER INNER JOIN
--                      dbo.BONDGODOWNMASTER ON dbo.BONDMASTER.GWNID = dbo.BONDGODOWNMASTER.GWNID INNER JOIN
--                      dbo.VW_CHA_MASTER ON dbo.BONDMASTER.CHAID = dbo.VW_CHA_MASTER.CHAID INNER JOIN
--                      dbo.VW_IMPORTER_MASTER ON dbo.BONDMASTER.IMPRTID = dbo.VW_IMPORTER_MASTER.IMPRTID INNER JOIN
--                      dbo.PRODUCTGROUPMASTER ON dbo.BONDMASTER.PRDTGID = dbo.PRODUCTGROUPMASTER.PRDTGID INNER JOIN
--                      dbo.YARDMASTER ON dbo.BONDMASTER.YRDID = dbo.YARDMASTER.YRDID




--GO


--USE SCFS_ERP
--GO

--EXEC sys.sp_dropextendedproperty @name=N'MS_DiagramPaneCount' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_EXBOND_PRINT_ASSGN'

--GO

--EXEC sys.sp_dropextendedproperty @name=N'MS_DiagramPane2' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_EXBOND_PRINT_ASSGN'

--GO

--EXEC sys.sp_dropextendedproperty @name=N'MS_DiagramPane1' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_EXBOND_PRINT_ASSGN'

--GO

/****** Object:  View [dbo].[VW_EXBOND_PRINT_ASSGN]    Script Date: 22/08/2022 14:40:27 ******/
DROP VIEW [dbo].[VW_EXBOND_PRINT_ASSGN]
GO

/****** Object:  View [dbo].[VW_EXBOND_PRINT_ASSGN]    Script Date: 22/08/2022 14:40:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_EXBOND_PRINT_ASSGN]
AS
SELECT     dbo.TMPRPT_IDS.KUSRID, dbo.EXBONDMASTER.CHAID, dbo.EXBONDMASTER.PRDTGID, dbo.PRODUCTGROUPMASTER.PRDTGDESC, 
                      dbo.EXBONDMASTER.EBNDNO, dbo.EXBONDMASTER.EBNDDNO, dbo.EXBONDMASTER.EBNDDATE, dbo.EXBONDMASTER.IMPRTID, 
                      dbo.CATEGORYMASTER.CATEDNAME AS CHA, CATEGORYMASTER_1.CATEDNAME AS IMP, dbo.EXBONDMASTER.EBNDBENO, dbo.EXBONDMASTER.EBNDBEDATE, 
                      dbo.BONDMASTER.BNDNO, dbo.BONDMASTER.BNDDNO, dbo.BONDMASTER.BNDDATE, dbo.EXBONDMASTER.EBNDID, 
                      dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.EXBONDMASTER.EBNDNOP, dbo.BONDMASTER.BNDNOP, dbo.BONDMASTER.BNDSPC, 
                      dbo.EXBONDMASTER.EBNDASSAMT, dbo.EXBONDMASTER.EBNDDTYAMT, dbo.EXBONDMASTER.EBNDINSAMT, dbo.EXBONDMASTER.EBNDBSPC, 
                      dbo.EXBONDMASTER.EBNDSPC, CATEGORYMASTER_2.CATENAME AS CHANAME, CATEGORYMASTER_3.CATENAME AS IMPRTNAME, 
                      dbo.EXBONDMASTER.EBNDEDATE, dbo.EXBONDMASTER.EBNDREMKRS
FROM         dbo.CONTAINERSIZEMASTER INNER JOIN
                      dbo.EXBONDMASTER ON dbo.CONTAINERSIZEMASTER.CONTNRSID = dbo.EXBONDMASTER.CONTNRSID INNER JOIN
                      dbo.PRODUCTGROUPMASTER ON dbo.EXBONDMASTER.PRDTGID = dbo.PRODUCTGROUPMASTER.PRDTGID INNER JOIN
                      dbo.BONDMASTER ON dbo.EXBONDMASTER.BNDID = dbo.BONDMASTER.BNDID INNER JOIN
                      dbo.CATEGORYMASTER ON dbo.EXBONDMASTER.CHAID = dbo.CATEGORYMASTER.CATEID INNER JOIN
                      dbo.CATEGORYMASTER AS CATEGORYMASTER_1 ON dbo.EXBONDMASTER.IMPRTID = CATEGORYMASTER_1.CATEID INNER JOIN
                      dbo.TMPRPT_IDS ON dbo.EXBONDMASTER.EBNDID = dbo.TMPRPT_IDS.RPTID INNER JOIN
                      dbo.CATEGORYMASTER AS CATEGORYMASTER_2 ON dbo.EXBONDMASTER.CHAID = CATEGORYMASTER_2.CATEID INNER JOIN
                      dbo.CATEGORYMASTER AS CATEGORYMASTER_3 ON dbo.EXBONDMASTER.IMPRTID = CATEGORYMASTER_3.CATEID

GO

EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[41] 4[20] 2[8] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "CONTAINERSIZEMASTER"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 114
               Right = 194
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "EXBONDMASTER"
            Begin Extent = 
               Top = 6
               Left = 232
               Bottom = 114
               Right = 389
            End
            DisplayFlags = 280
            TopColumn = 32
         End
         Begin Table = "PRODUCTGROUPMASTER"
            Begin Extent = 
               Top = 114
               Left = 38
               Bottom = 222
               Right = 189
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "BONDMASTER"
            Begin Extent = 
               Top = 114
               Left = 227
               Bottom = 222
               Right = 378
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "CATEGORYMASTER"
            Begin Extent = 
               Top = 222
               Left = 38
               Bottom = 330
               Right = 197
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "CATEGORYMASTER_1"
            Begin Extent = 
               Top = 222
               Left = 235
               Bottom = 330
               Right = 394
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "TMPRPT_IDS"
            Begin Extent = 
               Top = 330
               Left = 38
               Bottom = 423
               Right = 189
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_EXBOND_PRINT_ASSGN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N'
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "CATEGORYMASTER_2"
            Begin Extent = 
               Top = 27
               Left = 552
               Bottom = 135
               Right = 711
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "CATEGORYMASTER_3"
            Begin Extent = 
               Top = 116
               Left = 523
               Bottom = 224
               Right = 682
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 30
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 1110
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_EXBOND_PRINT_ASSGN'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=2 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_EXBOND_PRINT_ASSGN'
GO


USE SCFS_ERP
GO

/****** Object:  View [dbo].[VW_BOND_GATE_INPRINT_ASSGN]    Script Date: 22/08/2022 14:41:23 ******/
DROP VIEW [dbo].[VW_BOND_GATE_INPRINT_ASSGN]
GO

/****** Object:  View [dbo].[VW_BOND_GATE_INPRINT_ASSGN]    Script Date: 22/08/2022 14:41:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_BOND_GATE_INPRINT_ASSGN]
AS
SELECT     dbo.COMPANYMASTER.COMPDNAME, dbo.COMPANYMASTER.COMPADDR, dbo.TMPRPT_IDS.KUSRID, dbo.TMPRPT_IDS.RPTID, dbo.BONDGATEINDETAIL.GIDID, 
                      dbo.BONDGATEINDETAIL.COMPYID, dbo.BONDGATEINDETAIL.SDPTID, dbo.BONDGATEINDETAIL.GIDATE, RIGHT(dbo.BONDGATEINDETAIL.GITIME, 8) AS GITIME, dbo.BONDGATEINDETAIL.GINO, 
                      dbo.BONDGATEINDETAIL.GIDNO, dbo.BONDGATEINDETAIL.TRNSPRTNAME, dbo.BONDGATEINDETAIL.VHLNO, dbo.BONDGATEINDETAIL.DRVNAME, dbo.BONDGATEINDETAIL.IMPRTNAME, 
                      dbo.BONDGATEINDETAIL.STMRNAME, dbo.BONDGATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.CONTAINERTYPEMASTER.CONTNRTCODE, 
                      dbo.BONDGATEINDETAIL.VSLNAME, dbo.BONDGATEINDETAIL.VOYNO, dbo.BONDGATEINDETAIL.PRDTDESC, dbo.BONDGATEINDETAIL.GPWGHT, dbo.BONDGATEINDETAIL.IGMNO, 
                      dbo.BONDGATEINDETAIL.GPLNO, dbo.BONDMASTER.BNDDNO, dbo.BONDGATEINDETAIL.CHANAME, dbo.BONDGATEINDETAIL.GPNOP, dbo.BONDGATEINDETAIL.GPCBM
FROM         dbo.BONDGATEINDETAIL INNER JOIN
                      dbo.COMPANYACCOUNTINGDETAIL ON dbo.BONDGATEINDETAIL.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                      dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.BONDGATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                      dbo.CONTAINERTYPEMASTER ON dbo.BONDGATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID INNER JOIN
                      dbo.TMPRPT_IDS ON dbo.BONDGATEINDETAIL.GIDID = dbo.TMPRPT_IDS.RPTID INNER JOIN
                      dbo.BONDMASTER ON dbo.BONDGATEINDETAIL.BNDID = dbo.BONDMASTER.BNDID


GO


--USE SCFS_ERP
--GO

--EXEC sys.sp_dropextendedproperty @name=N'MS_DiagramPaneCount' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_BOND_GATE_OUTPRINT_ASSGN'

--GO

--EXEC sys.sp_dropextendedproperty @name=N'MS_DiagramPane2' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_BOND_GATE_OUTPRINT_ASSGN'

--GO

--EXEC sys.sp_dropextendedproperty @name=N'MS_DiagramPane1' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_BOND_GATE_OUTPRINT_ASSGN'

--GO

--/****** Object:  View [dbo].[VW_BOND_GATE_OUTPRINT_ASSGN]    Script Date: 22/08/2022 14:41:31 ******/
--DROP VIEW [dbo].[VW_BOND_GATE_OUTPRINT_ASSGN]
--GO

--/****** Object:  View [dbo].[VW_BOND_GATE_OUTPRINT_ASSGN]    Script Date: 22/08/2022 14:41:31 ******/
--SET ANSI_NULLS ON
--GO

--SET QUOTED_IDENTIFIER ON
--GO

--CREATE VIEW [dbo].[VW_BOND_GATE_OUTPRINT_ASSGN]
--AS
--SELECT     dbo.COMPANYMASTER.COMPDNAME, dbo.COMPANYMASTER.COMPADDR, dbo.TMPRPT_IDS.KUSRID, dbo.TMPRPT_IDS.RPTID, dbo.BONDGATEOUTDETAIL.GODID, 
--                      dbo.BONDGATEOUTDETAIL.COMPYID, dbo.BONDGATEOUTDETAIL.SDPTID, dbo.BONDGATEOUTDETAIL.GODATE, RIGHT(dbo.BONDGATEOUTDETAIL.GOTIME, 8) AS GOTIME, 
--                      dbo.BONDGATEOUTDETAIL.GONO, dbo.BONDGATEOUTDETAIL.GODNO, dbo.BONDGATEINDETAIL.CONTNRNO, dbo.BONDGATEINDETAIL.IMPRTNAME, dbo.BONDGATEINDETAIL.STMRNAME, 
--                      dbo.BONDGATEOUTDETAIL.VHLNO, dbo.BONDGATEOUTDETAIL.GOBTYPE, dbo.BONDGATEOUTDETAIL.GDRVNAME, dbo.BONDGATEOUTDETAIL.CHASNAME, dbo.BONDGATEINDETAIL.PRDTDESC, 
--                      dbo.BONDGATEINDETAIL.IGMNO, dbo.BONDGATEINDETAIL.GPLNO, dbo.BONDMASTER.BNDDNO, dbo.BONDGATEINDETAIL.GPNOP, dbo.BONDGATEINDETAIL.GPWGHT, 
--                      dbo.BONDGATEINDETAIL.GPCBM, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.CONTAINERTYPEMASTER.CONTNRTDESC, 
--                      dbo.PRODUCTGROUPMASTER.PRDTGDESC, dbo.BONDGATEINDETAIL.CHANAME, dbo.TMPRPT_IDS.OPTNSTR
--FROM         dbo.BONDMASTER INNER JOIN
--                      dbo.BONDGATEOUTDETAIL INNER JOIN
--                      dbo.COMPANYACCOUNTINGDETAIL ON dbo.BONDGATEOUTDETAIL.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
--                      dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID INNER JOIN
--                      dbo.BONDGATEINDETAIL ON dbo.BONDGATEOUTDETAIL.GIDID = dbo.BONDGATEINDETAIL.GIDID INNER JOIN
--                      dbo.TMPRPT_IDS ON dbo.BONDGATEOUTDETAIL.GODID = dbo.TMPRPT_IDS.RPTID ON dbo.BONDMASTER.BNDID = dbo.BONDGATEINDETAIL.BNDID INNER JOIN
--                      dbo.CONTAINERSIZEMASTER ON dbo.BONDGATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
--                      dbo.CONTAINERTYPEMASTER ON dbo.BONDGATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID INNER JOIN
--                      dbo.PRODUCTGROUPMASTER ON dbo.BONDMASTER.PRDTGID = dbo.PRODUCTGROUPMASTER.PRDTGID

--GO

--EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
--Begin DesignProperties = 
--   Begin PaneConfigurations = 
--      Begin PaneConfiguration = 0
--         NumPanes = 4
--         Configuration = "(H (1[52] 4[4] 2[4] 3) )"
--      End
--      Begin PaneConfiguration = 1
--         NumPanes = 3
--         Configuration = "(H (1 [50] 4 [25] 3))"
--      End
--      Begin PaneConfiguration = 2
--         NumPanes = 3
--         Configuration = "(H (1 [50] 2 [25] 3))"
--      End
--      Begin PaneConfiguration = 3
--         NumPanes = 3
--         Configuration = "(H (4 [30] 2 [40] 3))"
--      End
--      Begin PaneConfiguration = 4
--         NumPanes = 2
--         Configuration = "(H (1 [56] 3))"
--      End
--      Begin PaneConfiguration = 5
--         NumPanes = 2
--         Configuration = "(H (2 [66] 3))"
--      End
--      Begin PaneConfiguration = 6
--         NumPanes = 2
--         Configuration = "(H (4 [50] 3))"
--      End
--      Begin PaneConfiguration = 7
--         NumPanes = 1
--         Configuration = "(V (3))"
--      End
--      Begin PaneConfiguration = 8
--         NumPanes = 3
--         Configuration = "(H (1[56] 4[18] 2) )"
--      End
--      Begin PaneConfiguration = 9
--         NumPanes = 2
--         Configuration = "(H (1 [75] 4))"
--      End
--      Begin PaneConfiguration = 10
--         NumPanes = 2
--         Configuration = "(H (1[66] 2) )"
--      End
--      Begin PaneConfiguration = 11
--         NumPanes = 2
--         Configuration = "(H (4 [60] 2))"
--      End
--      Begin PaneConfiguration = 12
--         NumPanes = 1
--         Configuration = "(H (1) )"
--      End
--      Begin PaneConfiguration = 13
--         NumPanes = 1
--         Configuration = "(V (4))"
--      End
--      Begin PaneConfiguration = 14
--         NumPanes = 1
--         Configuration = "(V (2))"
--      End
--      ActivePaneConfig = 0
--   End
--   Begin DiagramPane = 
--      Begin Origin = 
--         Top = 0
--         Left = 0
--      End
--      Begin Tables = 
--         Begin Table = "BONDMASTER"
--            Begin Extent = 
--               Top = 6
--               Left = 38
--               Bottom = 114
--               Right = 189
--            End
--            DisplayFlags = 280
--            TopColumn = 0
--         End
--         Begin Table = "BONDGATEOUTDETAIL"
--            Begin Extent = 
--               Top = 192
--               Left = 394
--               Bottom = 300
--               Right = 545
--            End
--            DisplayFlags = 280
--            TopColumn = 0
--         End
--         Begin Table = "COMPANYACCOUNTINGDETAIL"
--            Begin Extent = 
--               Top = 300
--               Left = 314
--               Bottom = 408
--               Right = 465
--            End
--            DisplayFlags = 280
--            TopColumn = 0
--         End
--         Begin Table = "COMPANYMASTER"
--            Begin Extent = 
--               Top = 350
--               Left = 696
--               Bottom = 458
--               Right = 856
--            End
--            DisplayFlags = 280
--            TopColumn = 0
--         End
--         Begin Table = "BONDGATEINDETAIL"
--            Begin Extent = 
--               Top = 17
--               Left = 294
--               Bottom = 125
--               Right = 447
--            End
--            DisplayFlags = 280
--            TopColumn = 32
--         End
--         Begin Table = "TMPRPT_IDS"
--            Begin Extent = 
--               Top = 26
--               Left = 740
--               Bottom = 119
--               Right = 891
--            End
--            DisplayFlags = 280
--            TopColumn = 0
--         End
--         Begin Table = "CONTAINERSIZEMASTER"
--            Begin Extent = 
--               Top = 231
--               Left = 61
--               Bottom = 339
--               Right = 21' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_BOND_GATE_OUTPRINT_ASSGN'
--GO

--EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N'7
--            End
--            DisplayFlags = 280
--            TopColumn = 0
--         End
--         Begin Table = "CONTAINERTYPEMASTER"
--            Begin Extent = 
--               Top = 195
--               Left = 720
--               Bottom = 303
--               Right = 876
--            End
--            DisplayFlags = 280
--            TopColumn = 0
--         End
--         Begin Table = "PRODUCTGROUPMASTER"
--            Begin Extent = 
--               Top = 173
--               Left = 11
--               Bottom = 281
--               Right = 162
--            End
--            DisplayFlags = 280
--            TopColumn = 0
--         End
--      End
--   End
--   Begin SQLPane = 
--   End
--   Begin DataPane = 
--      Begin ParameterDefaults = ""
--      End
--      Begin ColumnWidths = 30
--         Width = 284
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--         Width = 1500
--      End
--   End
--   Begin CriteriaPane = 
--      Begin ColumnWidths = 11
--         Column = 1440
--         Alias = 900
--         Table = 1170
--         Output = 720
--         Append = 1400
--         NewValue = 1170
--         SortType = 1350
--         SortOrder = 1410
--         GroupBy = 1350
--         Filter = 1350
--         Or = 1350
--         Or = 1350
--         Or = 1350
--      End
--   End
--End
--' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_BOND_GATE_OUTPRINT_ASSGN'
--GO

--EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=2 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'VW_BOND_GATE_OUTPRINT_ASSGN'
--GO


USE SCFS_ERP
GO

/****** Object:  View [dbo].[VW_BONDSPACEDETAIL_CTRL_ASSGN]    Script Date: 22/08/2022 14:42:08 ******/
DROP VIEW [dbo].[VW_BONDSPACEDETAIL_CTRL_ASSGN]
GO

/****** Object:  View [dbo].[VW_BONDSPACEDETAIL_CTRL_ASSGN]    Script Date: 22/08/2022 14:42:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_BONDSPACEDETAIL_CTRL_ASSGN]
AS
SELECT     dbo.BONDSPACEDETAIL.SPCID, dbo.BONDSPACEDETAIL.COMPYID, dbo.BONDSPACEDETAIL.SDPTID, dbo.BONDSPACEDETAIL.SPCDATE, dbo.BONDSPACEDETAIL.SPCTIME, 
                      dbo.BONDSPACEDETAIL.SPCNO, dbo.BONDSPACEDETAIL.SPCDNO, dbo.BONDSPACEDETAIL.SPCBENO, dbo.BONDSPACEDETAIL.SPCBEDATE, dbo.BONDSPACEDETAIL.SPCBLNO, 
                      dbo.BONDSPACEDETAIL.SPCBLDATE, dbo.BONDSPACEDETAIL.IMPRTID, dbo.CATEGORYMASTER.CATENAME, dbo.CATEGORYMASTER.CATECODE, 
                      dbo.BONDSPACEDETAIL.PRDTID, dbo.BONDSPACEDETAIL.TYPEID, dbo.BONDSPACEDETAIL.QTY, dbo.BONDSPACEDETAIL.GWGHT, dbo.BONDSPACEDETAIL.DQTY, 
                      dbo.BONDSPACEDETAIL.WGHT, dbo.BONDSPACEDETAIL.MTRS, dbo.BONDSPACEDETAIL.AAMT, dbo.BONDSPACEDETAIL.DAMT, dbo.BONDSPACEDETAIL.SPCDESC, 
                      dbo.BONDSPACEDETAIL.SPCEDATE, dbo.BONDSPACEDETAIL.SPCSFDATE, dbo.BONDSPACEDETAIL.SPCSTDATE, dbo.BONDSPACEDETAIL.CUSRID, 
                      dbo.BONDSPACEDETAIL.LMUSRID, dbo.BONDSPACEDETAIL.DISPSTATUS, dbo.BONDSPACEDETAIL.PRCSDATE
FROM         dbo.BONDSPACEDETAIL INNER JOIN
                      dbo.CATEGORYMASTER ON dbo.BONDSPACEDETAIL.IMPRTID = dbo.CATEGORYMASTER.CATEID

GO

-- select * From UNITMASTER
-- select * From spbw..gateindetail