USE [SCFS_ERP]
GO

EXEC sys.sp_dropextendedproperty @name=N'MS_Description' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BONDVEHICLETICKETDETAIL', @level2type=N'COLUMN',@level2name=N'VTSTYPE'
GO

EXEC sys.sp_dropextendedproperty @name=N'MS_Description' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BONDVEHICLETICKETDETAIL', @level2type=N'COLUMN',@level2name=N'VTTYPE'
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTAREA]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_EBNDID]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_PRCSDATE]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_DISPSTATUS]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_LMUSRID]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_CUSRID]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTREMKRS]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTTYPE1]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTTYPE]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTQTY]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_PRDTDESC]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_DRVNAME]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VHLNO]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTDNO]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTNO]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTTIME]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTDATE]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_SDPTID]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] DROP CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_COMPYID]
GO

/****** Object:  Table [dbo].[BONDVEHICLETICKETDETAIL]    Script Date: 14-10-2022 18:34:47 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BONDVEHICLETICKETDETAIL]') AND type in (N'U'))
DROP TABLE [dbo].[BONDVEHICLETICKETDETAIL]
GO

/****** Object:  Table [dbo].[BONDVEHICLETICKETDETAIL]    Script Date: 14-10-2022 18:34:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BONDVEHICLETICKETDETAIL](
	[VTDID] [int] IDENTITY(1,1) NOT NULL,
	[COMPYID] [int] NOT NULL,
	[SDPTID] [int] NOT NULL,
	[VTDATE] [smalldatetime] NOT NULL,
	[VTTIME] [datetime] NOT NULL,
	[VTNO] [int] NOT NULL,
	[VTDNO] [varchar](15) NOT NULL,
	[VHLNO] [varchar](15) NULL,
	[DRVNAME] [varchar](100) NULL,
	[VTDESC] [varchar](100) NULL,
	[VTQTY] [numeric](18, 2) NULL,
	[VTTYPE] [int] NULL,
	[VTSTYPE] [int] NULL,
	[VTREMRKS] [varchar](100) NULL,
	[CUSRID] [varchar](100) NULL,
	[LMUSRID] [varchar](100) NULL,
	[DISPSTATUS] [smallint] NULL,
	[PRCSDATE] [datetime] NULL,
	[EBNDID] [int] NOT NULL,
	[VTAREA] [numeric](18, 2) NOT NULL,
 CONSTRAINT [PK_BONDVEHICLETICKETDETAIL] PRIMARY KEY CLUSTERED 
(
	[VTDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_COMPYID]  DEFAULT ((0)) FOR [COMPYID]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_SDPTID]  DEFAULT ((0)) FOR [SDPTID]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTDATE]  DEFAULT (NULL) FOR [VTDATE]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTTIME]  DEFAULT (NULL) FOR [VTTIME]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTNO]  DEFAULT ((0)) FOR [VTNO]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTDNO]  DEFAULT (NULL) FOR [VTDNO]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VHLNO]  DEFAULT (NULL) FOR [VHLNO]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_DRVNAME]  DEFAULT (NULL) FOR [DRVNAME]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_PRDTDESC]  DEFAULT (NULL) FOR [VTDESC]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTQTY]  DEFAULT ((0)) FOR [VTQTY]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTTYPE]  DEFAULT ((0)) FOR [VTTYPE]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTTYPE1]  DEFAULT ((0)) FOR [VTSTYPE]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTREMKRS]  DEFAULT (NULL) FOR [VTREMRKS]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_CUSRID]  DEFAULT (NULL) FOR [CUSRID]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_LMUSRID]  DEFAULT (NULL) FOR [LMUSRID]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_DISPSTATUS]  DEFAULT ((0)) FOR [DISPSTATUS]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_PRCSDATE]  DEFAULT (NULL) FOR [PRCSDATE]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_EBNDID]  DEFAULT ((0)) FOR [EBNDID]
GO

ALTER TABLE [dbo].[BONDVEHICLETICKETDETAIL] ADD  CONSTRAINT [DF_BONDVEHICLETICKETDETAIL_VTAREA]  DEFAULT ((0)) FOR [VTAREA]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 - LOAD, 2 - DESTUFF' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BONDVEHICLETICKETDETAIL', @level2type=N'COLUMN',@level2name=N'VTTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'0 - PART LOAD, 1 - FULL LOAD' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'BONDVEHICLETICKETDETAIL', @level2type=N'COLUMN',@level2name=N'VTSTYPE'
GO


