select * from BONDSLABMASTER join BONDTARIFFMASTER on BONDSLABMASTER.TARIFFMID = BONDTARIFFMASTER.TARIFFMID
where BONDTARIFFMASTER.TARIFFMDESC like '%in%bond%'
and SLABTID = 3

update BONDSLABMASTER 
set HANDTYPE = 2
from BONDSLABMASTER join BONDTARIFFMASTER on BONDSLABMASTER.TARIFFMID = BONDTARIFFMASTER.TARIFFMID
where BONDTARIFFMASTER.TARIFFMDESC like '%in%bond%'
and SLABTID != 3


select * from BONDSLABMASTER join BONDTARIFFMASTER on BONDSLABMASTER.TARIFFMID = BONDTARIFFMASTER.TARIFFMID
where BONDTARIFFMASTER.TARIFFMDESC like '%ex%bond%'
and SLABTID = 3

update BONDSLABMASTER 
set HANDTYPE = 1
from BONDSLABMASTER join BONDTARIFFMASTER on BONDSLABMASTER.TARIFFMID = BONDTARIFFMASTER.TARIFFMID
where BONDTARIFFMASTER.TARIFFMDESC like '%ex%bond%'
and SLABTID = 3


select SLABAMT,SLABMIN,SLABMAX from VW_BOND_RATECARDMASTER_FLX_ASSGN (NOLOCK) 
where TARIFFMID=11 and SLABTID=2 
and HTYPE=3 
AND YRDTYPE = 1 
AND PERIODTID = 2 
and CHRGETYPE=1 and HANDTYPE= 2 and CONTNRSID= 2 
and (PRDTGID = 589 or PRDTGID =1) order by SLABMIN