USE SCFS_ERP
GO

SELECT 'BTRNMST-BEF-INS', COUNT('*') FROM BONDTRANSACTIONMASTER
BEGIN  TRAN
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONMASTER ON 
INSERT INTO SCFS_ERP.DBO.BONDTRANSACTIONMASTER
(
TRANMID, COMPYID, SDPTID, REGSTRID, TRANBTYPE, TRANDATE, TRANTIME, TRANNO, TRANDNO,CHAID, IMPRTID, TRANCHANAME,
TRANIMPRTNAME, TRANTID, BANKMID, TRANMODE, TRANMODEDETL,TRANREFNO, TRANREFDATE, TRANREFBNAME, TRANREFAMT, TRANROAMT,
TRANGAMT, TRANSAMT,TRANHAMT, TRANIAMT, TRANNAMT, TRANAMTWRDS, TRANLMID, TRANLMNO, TRANLMDATE,TRANNARTN, TRANRMKS,
TRANPCOUNT,  CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, TRANREFNAME, BILLREFID, TRANGSTNO, TRANPTAMT, TRANPLAMT, IRNNO,
ACKNO, ACKDT, QRCODEPATH, TRAN_CGST_AMT, TRAN_SGST_AMT, TRAN_IGST_AMT, BCATEAID, TRAN_TAXABLE_AMT, TRANBILLREFNO
)

SELECT 
TRANMID, 31, 10, REGSTRID, TRANBTYPE, TRANDATE, TRANTIME, TRANNO, TRANDNO,CHAID, IMPRTID, TRANCHANAME,
TRANIMPRTNAME, TRANTID, BANKMID, TRANMODE, TRANMODEDETL,TRANREFNO, TRANREFDATE, TRANREFBNAME, TRANREFAMT, TRANROAMT,
TRANGAMT, TRANSAMT,TRANHAMT, TRANIAMT, TRANNAMT, TRANAMTWRDS, TRANLMID, TRANLMNO, TRANLMDATE,TRANNARTN, TRANRMKS,
TRANPCOUNT,  CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, TRANREFNAME, BILLREFID, TRANGSTNO, 0, 0, IRNNO,
ACKNO, ACKDT, QRCODEPATH, TRAN_CGST_AMT, TRAN_SGST_AMT, TRAN_IGST_AMT, 0, 0, replace(TRANLMNO,'BWH/','BWH/EXB/')
FROM SPBW..TRANSACTIONMASTER A
WHERE COMPYID=25 
AND TRANDATE < '2022-10-19'
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONMASTER OFF
SELECT 'BTRNMST-AFT-INS',COUNT('*') FROM BONDTRANSACTIONMASTER
--ROLLBACK TRAN
COMMIT TRAN

SELECT 'BTRNMST-FNL-INS',COUNT('*') FROM BONDTRANSACTIONMASTER


SELECT 'BTRNDTL-BEF-INS',COUNT('*') FROM BONDTRANSACTIONDETAIL
BEGIN  TRAN
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONDETAIL ON 
INSERT INTO SCFS_ERP.DBO.BONDTRANSACTIONDETAIL
(
TRANDID, TRANMID, BNDID, EBNDID, TRANDBNDNO, TRANDEBNDNO, TARIFFMID, SLABTID, CONTNRSID, YRDID, TRANCTYPE, TRANOTYPE,
TRANHTYPE,  TRANCDATE,  TRANSFDATE, TRANSEDATE, TRANIFDATE, TRANIEDATE, TRANDQTY, TRANDNOP, TRANDRATE, TRANDWGHT,
TRANDCIFAMT, TRANDDTYAMT, TRANDINSAMT, TRANDEIAMT, TRANDGAMT, TRANDSAMT, TRANDHAMT, TRANDIAMT, TRANDNAMT,TRANDAID,
DISPSTATUS, RCOLDESC1, RCOLDESC2, RCOLDESC3, RCOLDESC4, VTDID, TRANDPLAMT, TRANDPTAMT, TRAND_CGST_EXPRN, 
TRAND_SGST_EXPRN, TRAND_IGST_EXPRN, TRAND_CGST_AMT, TRAND_SGST_AMT, TRAND_IGST_AMT, INS_TRAND_CGST_AMT, 
INS_TRAND_SGST_AMT,  INS_TRAND_IGST_AMT, PERIODTID,  TRAND_HSN_CODE, INS_TRAND_HSN_CODE, TRAND_TAXABLE_AMT, 
INS_TRAND_TAXABLE_AMT, STATETYPE)
SELECT 
TRANDID, OTD.TRANMID, BNDID, EBNDID, TRANDBNDNO, TRANDEBNDNO, OTD.TARIFFMID, OTD.SLABTID, CONTNRSID, YRDID, TRANCTYPE, TRANOTYPE,
TRANHTYPE,  TRANCDATE,  TRANSFDATE, TRANSEDATE, TRANIFDATE, TRANIEDATE, TRANDQTY, TRANDNOP, TRANDRATE, TRANDWGHT,
TRANDCIFAMT, TRANDDTYAMT, TRANDINSAMT, TRANDEIAMT, TRANDGAMT, TRANDSAMT, TRANDHAMT, TRANDIAMT, TRANDNAMT,TRANDAID,
OTD.DISPSTATUS, RCOLDESC1, RCOLDESC2, RCOLDESC3, RCOLDESC4, 0, 0, 0, TRAND_CGST_EXPRN, 
TRAND_SGST_EXPRN, TRAND_IGST_EXPRN, TRAND_CGST_AMT, TRAND_SGST_AMT, TRAND_IGST_AMT, 0, 
0,  0, 2,  HSNCODE, '', 0, 0,  OST.STATETYPE
FROM SPBW..TRANSACTIONDETAIL  OTD JOIN SPBW..TRANSACTIONMASTER  OTM (NOLOCK) ON OTD.TRANMID = OTM.TRANMID
JOIN SCFS_ERP..BONDSLABTYPEMASTER BSM(NOLOCK) ON OTD.SLABTID = BSM.SLABTID
JOIN SCFS_ERP..HSNCODEMASTER HSN(NOLOCK) ON BSM.HSNID = HSN.HSNID
JOIN SPBW..CATEGORYMASTER OCTG(NOLOCK) ON OTM.BILLREFID = OCTG.CATEID
JOIN SPBW..STATEMASTER OST(NOLOCK) ON OCTG.STATEID = OST.STATEID
WHERE TRANDATE < '2022-10-19'
AND OTM.COMPYID=25 
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONDETAIL OFF
SELECT 'BTRNDTL-AFT-INS',COUNT('*') FROM BONDTRANSACTIONDETAIL
--ROLLBACK TRAN
COMMIT TRAN

SELECT 'BTRNDTL-FNL-INS',COUNT('*') FROM BONDTRANSACTIONDETAIL




SELECT 'BTRNDCF-BEF-INS',COUNT('*') FROM BONDTRANSACTIONMASTERFACTOR
BEGIN  TRAN
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONMASTERFACTOR ON 
INSERT INTO SCFS_ERP.DBO.BONDTRANSACTIONMASTERFACTOR
(
TRANMFID, OTFD.TRANMID , CFID, DEDEXPRN, DEDNOS, DEDMODE, DEDTYPE, DEDORDR, CFOPTN, DORDRID, DEDVALUE)
SELECT 
TRANMFID, OTFD.TRANMID , CFID, DEDEXPRN, DEDNOS, DEDMODE, DEDTYPE, DEDORDR, CFOPTN, DORDRID, DEDVALUE
FROM SPBW..TRANSACTIONMASTERFACTOR  OTFD (NOLOCK) 
JOIN SPBW..TRANSACTIONMASTER  OTM (NOLOCK) ON OTFD.TRANMID = OTM.TRANMID
WHERE TRANDATE < '2022-10-19'
AND OTM.COMPYID=25 
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONMASTERFACTOR OFF
SELECT 'BTRNDCF-AFT-INS',COUNT('*') FROM BONDTRANSACTIONMASTERFACTOR
--ROLLBACK TRAN
COMMIT TRAN

SELECT 'BTRNDCF-FNL-INS',COUNT('*') FROM BONDTRANSACTIONMASTERFACTOR

--SELECT * FROM BONDTRANSACTIONMASTERFACTOR