
IF NOT EXISTS(select '*' from EXPORT_INVOICE_REGISTER WHERE REGSTRID = 46)
BEGIN

	insert into  EXPORT_INVOICE_REGISTER
	select 46, 'CUSTOMER'
	UNION
	SELECT 47, 'NOTIONAL'
	UNION
	SELECT 48, 'ZERO BILL'
END
