
USE SCFS_ERP
GO
SELECT * FROM CATEGORYTYPEMASTER

IF nOT EXISTS(SELECT '*' FROM CATEGORYTYPEMASTER (NOLOCK) WHERE CATETDESC = 'IMPORTER')
BEGIN
	INSERT INTO CATEGORYTYPEMASTER (CATETDESC, CATETCODE, CUSRID, DISPSTATUS, PRCSDATE)
	SELECT 'IMPORTER','IMPORTER','admin', 0,GETDATE()
END

SELECT * FROM CATEGORYTYPEMASTER
SELECT * FROM SPBW..CATEGORYTYPEMASTER