alter table CATEGORY_ADDRESS_DETAIL
add [CATEAPANNO] [varchar](100) NOT NULL CONSTRAINT [DF_CATEGORY_ADDRESS_DETAIL_CATEBNAME16]  DEFAULT ('')

UPDATE CATEGORY_ADDRESS_DETAIL
SET CATEAPANNO = CATEBPANNO
FROM CATEGORY_ADDRESS_DETAIL JOIN CATEGORYMASTER ON CATEGORY_ADDRESS_DETAIL.CATEID = CATEGORYMASTER.CATEID

SELECT * FROM CATEGORY_ADDRESS_DETAIL
WHERE CATEAPANNO IS NULL