select *from CATEGORYMASTER

ALTER TABLE CATEGORYMASTER
ADD [CATEBILLTYPE] [int] NOT NULL CONSTRAINT [DF_CATEGORYMASTER_CATEBILLTYPE]  DEFAULT (1)

update CATEGORYMASTER set CATEBILLTYPE=1 where CATEBILLTYPE is null