/*
drop table Init_Bond_CategoryMaster
select b.CATETID curcatetid,b.cateid curcateid,b.catename curcatename,B.STATEID 'CURSTATID',B.CATEBGSTNO 'CURGSTNO',
a.* 
into Init_Bond_CategoryMaster
from spbw..CATEGORYMASTER a left join scfs_erp..CATEGORYMASTER b(nolock) 
on a.CATENAME = b.CATENAME and a.CATETID = b.CATETID

SELECT B.CATEID,B.CATETID, B.CATENAME, B.CATEDNAME, B.CATEADDR, B.CATEPHNID, B.CATEPHN1, B.CATEPHN2, B.CATEPHN3,
B.CATEPHN4,  B.CATEMAIL,  B.CATECPRSN, B.CATECODE, B.CUSRID, B.LMUSRID, B.ACHEADID,
B.TARIFFMID,B.CATEBTYPE,B.CATEINSRDAYS,B.CATEMINWEEKS,B.CATENUMTYPE,B.DISPSTATUS,B.PRCSDATE,B.CATEWIPTYPE,
B.STATEID,B.CATEGSTNO,B.CATELICNO,B.CATEADDR1,B.CATEADDR2,B.CATEADDR3,B.CATEADDR4
--INTO BOND_MISSING_CATEGORY_MASTER_RECS
FROM Init_Bond_CategoryMaster A JOIN SPBW..CATEGORYMASTER B(NOLOCK) ON A.CATEID = B.CATEID AND A.CATETID = B.CATETID
WHERE curcatetid IS NULL

INSERT INTO CATEGORYMASTER (CATETID, CATENAME, CATEDNAME, CATEADDR, CATEPHNID, CATEPHN1, CATEPHN2, CATEPHN3,
CATEPHN4,  CATEMAIL,  CATECPRSN, CATECODE, CUSRID, LMUSRID, ACHEADID,
TARIFFMID,CATEBTYPE,DISPSTATUS,STATEID,CATEBGSTNO,CATELICNO,PRCSDATE)
SELECT A.CATETID, A.CATENAME, A.CATEDNAME, A.CATEADDR, A.CATEPHNID, A.CATEPHN1, A.CATEPHN2, A.CATEPHN3,
A.CATEPHN4,  A.CATEMAIL,  A.CATECPRSN, A.CATECODE, 'ADMIN', '', A.ACHEADID,
A.TARIFFMID, A.CATEBTYPE, A.DISPSTATUS, A.STATEID,CATEGSTNO,A.CATELICNO,'2022-10-22 11:45'
FROM BOND_MISSING_CATEGORY_MASTER_RECS  A left join scfs_erp..CATEGORYMASTER b(nolock) 
on a.CATENAME = b.CATENAME and a.CATETID = b.CATETID
WHERE  B.CATEID IS NULL


drop table FINALInit_Bond_CategoryMaster
select b.CATETID curcatetid,b.cateid curcateid,b.catename curcatename,B.STATEID 'CURSTATID',B.CATEBGSTNO 'CURGSTNO',
a.* 
into FINALInit_Bond_CategoryMaster
from spbw..CATEGORYMASTER a left join scfs_erp..CATEGORYMASTER b(nolock) 
on a.CATENAME = b.CATENAME and a.CATETID = b.CATETID


SELECT * fROM SPBW..CATEGORYMASTER WHERE CATENAME LIKE 'AASHIRVA%'

BEGIN TRAN
INSERT INTO SCFS_ERP..CATEGORY_ADDRESS_DETAIL(CATEID, STATEID, CATEAGSTNO, CATEAADDR1, CATEAADDR2, CATEAADDR3, 
CATEAADDR4, CATEATYPEDESC, CATEAPANNO)
SELECT B.CATEID, B.STATEID, B.CATEGSTNO, B.CATEADDR1, B.CATEADDR2,  B.CATEADDR3, B.CATEADDR4,
B.CATEADDR3,  ISNULL(SUBSTRING(B.CATEGSTNO,3,10),'-')
--SELECT B.*
FROM SCFS_ERP..CATEGORYMASTER A JOIN FINALInit_Bond_CategoryMaster B ON 
 A.CATENAME = b.CATENAME and A.CATETID = b.CATETID AND A.CATEID = B.CATEID
 WHERE A.curcateid IS NULL
 ROLLBACK TRAN

 */
 /*
 UPDATE A
 SET CHAID = B.CHAID
 FROM  BONDMASTER A JOIN SPBW..BONDMASTER B(NOLOCK) ON A.BNDID = B.BNDID

 UPDATE A
 SET CHAID = B.CURCATEID
 FROM BONDMASTER A JOIN FINALInit_Bond_CategoryMaster B ON A.CHAID =  B.CATEID AND B.CATETID = 4
 UPDATE A
 SET IMPRTID = B.IMPRTID
 FROM  BONDMASTER A JOIN SPBW..BONDMASTER B(NOLOCK) ON A.BNDID = B.BNDID

 UPDATE A
 SET IMPRTID = B.CURCATEID
 FROM BONDMASTER A JOIN FINALInit_Bond_CategoryMaster B ON A.IMPRTID =  B.CATEID AND B.CATETID =1

 SELECT * FROM BONDMASTER WHERE BNDID = 5718
 SELECT * FROM CATEGORYMASTER WHERE CATEID = 758

 UPDATE A
 SET CHAID = B.CHAID
 FROM  EXBONDMASTER A JOIN SPBW..EXBONDMASTER B(NOLOCK) ON A.EBNDID = B.EBNDID

 UPDATE A
 SET CHAID = B.CURCATEID
 FROM EXBONDMASTER A JOIN FINALInit_Bond_CategoryMaster B ON A.CHAID =  B.CATEID AND B.CATETID = 4

 
 UPDATE A
 SET IMPRTID = B.IMPRTID
 FROM  EXBONDMASTER A JOIN SPBW..EXBONDMASTER B(NOLOCK) ON A.EBNDID = B.EBNDID

 UPDATE A
 SET IMPRTID = B.CURCATEID
 FROM EXBONDMASTER A JOIN FINALInit_Bond_CategoryMaster B ON A.IMPRTID =  B.CATEID AND B.CATETID =1



 
 UPDATE A
 SET BILLREFID = B.BILLREFID, TRANTID = 3
 FROM  BONDTRANSACTIONMASTER A JOIN SPBW..TRANSACTIONMASTER B(NOLOCK) ON A.TRANMID = B.TRANMID

 UPDATE A
 SET BILLREFID = B.CURCATEID ,TRANREFBNAME = B.CATENAME
 FROM BONDTRANSACTIONMASTER A JOIN FINALInit_Bond_CategoryMaster B ON 
 (A.BILLREFID =  B.CATEID OR A.TRANREFBNAME = B.CATENAME)
 --AND B.CATETID =4


 UPDATE A
 SET CHAID = B.CHAID
 FROM  BONDTRANSACTIONMASTER A JOIN SPBW..TRANSACTIONMASTER B(NOLOCK) ON A.TRANMID = B.TRANMID

 UPDATE A
 SET CHAID = B.CURCATEID, TRANCHANAME =B.CATENAME
 FROM BONDTRANSACTIONMASTER A JOIN FINALInit_Bond_CategoryMaster B 
 ON  (A.CHAID =  B.CATEID OR A.TRANCHANAME = B.CATENAME) --B.CATETID =4 AND

 
 UPDATE A
 SET IMPRTID = B.IMPRTID
 FROM  BONDTRANSACTIONMASTER A JOIN SPBW..TRANSACTIONMASTER B(NOLOCK) ON A.TRANMID = B.TRANMID

 UPDATE A
 SET IMPRTID = B.CURCATEID, TRANIMPRTNAME =B.CATENAME
 FROM BONDTRANSACTIONMASTER A JOIN FINALInit_Bond_CategoryMaster B 
 ON 
 (A.IMPRTID =  B.CATEID OR A.TRANIMPRTNAME = B.CATENAME) -- B.CATETID =1 AND

 
 
 SELECT B.CATEID, MIN(CATEAID) 'CATEAID'
 INTO FINALBILLADDRIDDTL
 FROM FINALInit_Bond_CategoryMaster A JOIN CATEGORY_ADDRESS_DETAIL B(NOLOCK) ON A.CURCATEID = B.CATEID
 GROUP BY B.CATEID

 

 UPDATE A
 SET BCATEAID = B.CATEAID
 FROM BONDTRANSACTIONMASTER A JOIN FINALBILLADDRIDDTL B ON A.BILLREFID = B.CATEID
 WHERE --ISNULL(BCATEAID,0) = 0 AND 
 TRANTID = 3
 SELECT * fROM BONDTRANSACTIONMASTER WHERE BILLREFID IN(758,71960)
 SELECT * fROM FINALInit_Bond_CategoryMaster WHERE CATEID IN(758,71960)
 SELECT * FROM BONDTRANSACTIONMASTER WHERE ISNULL(BCATEAID,0) = 0
 */
