select * from GATEINDETAIL WHERE GIDID = 10
--select * from AUTHORIZATIONSLIPMASTER WHERE GIDID = 10
select * from AUTHORIZATIONSLIPDETAIL WHERE GIDID = 10
select * from VEHICLETICKETDETAIL WHERE GIDID = 10
select * from GATEOUTDETAIL --WHERE GIDID = 10
select * from VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN --WHERE GIDID = 10


sp_helptext VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN
select * from dbo.VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN
dbo.VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN_001
dbo.VW_NONPNR_GATEOUT_PRINT_ASSGN
dbo.VW_VEHICLETICKET_NONPNR_CONTAINER_CBX_ASSGN
sp_depends GATEOUTDETAIL
select * from VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN