USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[BANKMASTER]    Script Date: 03-03-2022 12:04:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE COMPANYBANKMASTER
GO

CREATE TABLE [dbo].[COMPANYBANKMASTER](

	[CBANKMID] [int] IDENTITY(1,1) NOT NULL,
	COMPID INT NULL,
	[CBANKMDESC] [varchar](100) NULL,
	[CBANKMACCODE] [varchar](50) NULL,
	[CBANKMIFSCCODE] [varchar](25) NULL,
	[CBANKMBRANCHNAME] [varchar](100) NULL,
	[CUSRID] [varchar](100) NULL,
	[LMUSRID] [varchar](100) NULL,
	[DISPSTATUS] [smallint] NULL,
	[EFF_FRM_DT] DATETIME NULL,
	[EFF_TO_DT] DATETIME NULL,
	[PRCSDATE] [datetime] NULL,
 CONSTRAINT [PK_COMPANYBANKMASTER] PRIMARY KEY CLUSTERED 
(
	[CBANKMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
