USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[CREDITNOTE_TRANSACTIONDETAIL]    Script Date: 17/09/2021 13:52:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CREDITNOTE_TRANSACTIONDETAIL](
	[TRANDID] [int] IDENTITY(1,1) NOT NULL,
	[TRANMID] [int] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANMID]  DEFAULT ((0)),
	[SLABTID] [int] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_SLABTID]  DEFAULT ((0)),
	[BILLEDID] [int] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_BILLEDID]  DEFAULT ((0)),
	[TRANDREFID] [int] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDREFID]  DEFAULT ((0)),
	[TRANDREFNAME] [varchar](200) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDREFNAME]  DEFAULT (NULL),
	[TRANDREFNO] [varchar](15) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDREFNO]  DEFAULT (NULL),
	[TRANIDATE] [smalldatetime] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANFDATE]  DEFAULT (NULL),
	[TRANSDATE] [smalldatetime] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANSDATE]  DEFAULT (NULL),
	[TRANEDATE] [smalldatetime] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANEDATE]  DEFAULT (NULL),
	[TRANVDATE] [smalldatetime] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANEDATE1]  DEFAULT (NULL),
	[TARIFFMID] [int] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TARIFFMID]  DEFAULT ((0)),
	[TRANOTYPE] [smallint] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANOTYPE]  DEFAULT ((0)),
	[TRANYTYPE] [smallint] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANYTYPE]  DEFAULT ((0)),
	[RCOL1] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RCOL1]  DEFAULT ((0)),
	[RCOL2] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RCOL11]  DEFAULT ((0)),
	[RCOL3] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RCOL12]  DEFAULT ((0)),
	[RCOL4] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RCOL11_1]  DEFAULT ((0)),
	[RAMT1] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RAMT1]  DEFAULT ((0)),
	[RAMT2] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RAMT11]  DEFAULT ((0)),
	[RAMT3] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RAMT12]  DEFAULT ((0)),
	[RAMT4] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RAMT13]  DEFAULT ((0)),
	[RCAMT1] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RAMT11_1]  DEFAULT ((0)),
	[RCAMT2] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RAMT21]  DEFAULT ((0)),
	[RCAMT3] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RAMT31]  DEFAULT ((0)),
	[RCAMT4] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RAMT41]  DEFAULT ((0)),
	[TRANDQTY] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDQTY]  DEFAULT ((0)),
	[TRANDRATE] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDRATE_1]  DEFAULT ((0)),
	[TRANDWGHT] [numeric](18, 3) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDWGHT]  DEFAULT ((0)),
	[TRANDGAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDGAMT]  DEFAULT ((0)),
	[TRANDSAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDSAMT]  DEFAULT ((0)),
	[TRANDHAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDCAMT]  DEFAULT ((0)),
	[TRANDNAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDNAMT]  DEFAULT ((0)),
	[TRANDAID] [int] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDAID]  DEFAULT ((0)),
	[TRANVHLFROM] [varchar](25) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANVHLFROM]  DEFAULT (NULL),
	[TRANVHLTO] [varchar](25) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANVHLFROM1]  DEFAULT (NULL),
	[DISPSTATUS] [smallint] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_DISPSTATUS]  DEFAULT ((0)),
	[STFDID] [int] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_STFDID]  DEFAULT ((0)),
	[SBDID] [int] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_SBDID]  DEFAULT ((0)),
	[TRANDNOP] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDNOP]  DEFAULT ((0)),
	[TRANDEAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDEAMT]  DEFAULT ((0)),
	[TRANDFAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDFAMT]  DEFAULT ((0)),
	[TRANDPAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDPAMT]  DEFAULT ((0)),
	[TRANDAAMT] [numeric](18, 0) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDAAMT]  DEFAULT ((0)),
	[RCOL5] [numeric](18, 0) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RCOL5]  DEFAULT ((0)),
	[RCOL6] [numeric](18, 0) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RCOL6]  DEFAULT ((0)),
	[RCOL7] [numeric](18, 0) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RCOL7]  DEFAULT ((0)),
	[RAMT5] [numeric](18, 0) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RAMT5]  DEFAULT ((0)),
	[RAMT6] [numeric](18, 0) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RAMT6]  DEFAULT ((0)),
	[RAMT7] [numeric](18, 0) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RAMT7]  DEFAULT ((0)),
	[RCAMT5] [numeric](18, 0) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RCAMT5]  DEFAULT ((0)),
	[RCAMT6] [numeric](18, 0) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RCAMT6]  DEFAULT ((0)),
	[RCAMT7] [numeric](18, 0) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_RCAMT7]  DEFAULT ((0)),
	[ACHEADID] [int] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_ACHEADID]  DEFAULT ((0)),
	[TRANDDESC] [ntext] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDDESC]  DEFAULT (NULL),
	[TRANDAHAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRANDAHAMT]  DEFAULT ((0)),
	[TRAND_COVID_DISC_AMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRAND_COVID_DISC_AMT]  DEFAULT ((0)),
	[TRAND_STRG_CGST_EXPRN] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRAND_STRG_CGST_EXPRN]  DEFAULT ((0)),
	[TRAND_STRG_SGST_EXPRN] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRAND_STRG_SGST_EXPRN]  DEFAULT ((0)),
	[TRAND_STRG_IGST_EXPRN] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRAND_STRG_IGST_EXPRN]  DEFAULT ((0)),
	[TRAND_STRG_CGST_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRAND_STRG_CGST_AMT]  DEFAULT ((0)),
	[TRAND_STRG_SGST_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRAND_STRG_SGST_AMT]  DEFAULT ((0)),
	[TRAND_STRG_IGST_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRAND_STRG_IGST_AMT]  DEFAULT ((0)),
	[TRAND_HANDL_CGST_EXPRN] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRAND_HANDL_CGST_EXPRN]  DEFAULT ((0)),
	[TRAND_HANDL_SGST_EXPRN] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRAND_HANDL_SGST_EXPRN]  DEFAULT ((0)),
	[TRAND_HANDL_IGST_EXPRN] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRAND_HANDL_IGST_EXPRN]  DEFAULT ((0)),
	[TRAND_HANDL_CGST_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRAND_HANDL_CGST_AMT]  DEFAULT ((0)),
	[TRAND_HANDL_SGST_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRAND_HANDL_SGST_AMT]  DEFAULT ((0)),
	[TRAND_HANDL_IGST_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONDETAIL_TRAND_HANDL_IGST_AMT]  DEFAULT ((0)),
 CONSTRAINT [PK_CREDITNOTE_TRANSACTIONDETAIL] PRIMARY KEY CLUSTERED 
(
	[TRANDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CREDITNOTE_TRANSACTIONDETAIL]  WITH NOCHECK ADD  CONSTRAINT [FK_CREDITNOTE_TRANSACTIONDETAIL_CREDITNOTE_TRANSACTIONMASTER] FOREIGN KEY([TRANMID])
REFERENCES [dbo].[CREDITNOTE_TRANSACTIONMASTER] ([TRANMID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CREDITNOTE_TRANSACTIONDETAIL] CHECK CONSTRAINT [FK_CREDITNOTE_TRANSACTIONDETAIL_CREDITNOTE_TRANSACTIONMASTER]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONDETAIL', @level2type=N'COLUMN',@level2name=N'TRANDREFNAME'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'PREVIOUS DETAIL ADJUSTED ID' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONDETAIL', @level2type=N'COLUMN',@level2name=N'TRANDAID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'0-IN BOOKS 1 -CANCELLED' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONDETAIL', @level2type=N'COLUMN',@level2name=N'DISPSTATUS'
GO


