USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[CREDITNOTE_TRANSACTIONMASTER]    Script Date: 17/09/2021 13:50:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CREDITNOTE_TRANSACTIONMASTER](
	[TRANMID] [int] IDENTITY(1,1) NOT NULL,
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_COMPYID]  DEFAULT ((0)),
	[SDPTID] [int] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_SDPTID]  DEFAULT ((0)),
	[REGSTRID] [int] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_REGSTRID]  DEFAULT ((0)),
	[TRANBTYPE] [smallint] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANBTYPE]  DEFAULT ((0)),
	[TRANDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANDATE]  DEFAULT (NULL),
	[TRANTIME] [datetime] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANTIME]  DEFAULT (NULL),
	[TRANNO] [int] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANNO]  DEFAULT ((0)),
	[TRANDNO] [varchar](50) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANDNO]  DEFAULT (NULL),
	[TRANREFID] [int] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANREFID]  DEFAULT ((0)),
	[TRANREFNAME] [varchar](100) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANREFNAME]  DEFAULT (''),
	[LCATEID] [int] NOT NULL,
	[TRANTID] [numeric](18, 0) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANTID]  DEFAULT ((0)),
	[BANKMID] [int] NULL,
	[TRANMODE] [smallint] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANMODE]  DEFAULT ((0)),
	[TRANMODEDETL] [varchar](150) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANMODEDETL]  DEFAULT (NULL),
	[TRANREFNO] [varchar](25) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANREFNO]  DEFAULT (NULL),
	[TRANREFDATE] [smalldatetime] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANDATE1]  DEFAULT (NULL),
	[TRANREFBNAME] [varchar](100) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANREFNAME1]  DEFAULT (NULL),
	[TRANREFAMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANGAMT1]  DEFAULT ((0)),
	[TRANROAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANROAMT]  DEFAULT ((0)),
	[TRANGAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANGAMT]  DEFAULT ((0)),
	[TRANSAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANSAMT]  DEFAULT ((0)),
	[TRANHAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANCAMT]  DEFAULT ((0)),
	[TRANNAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANNAMT]  DEFAULT ((0)),
	[TRANAMTWRDS] [varchar](250) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANAMTWRDS]  DEFAULT (NULL),
	[TRANLMID] [int] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANLMID]  DEFAULT ((0)),
	[TRANLMNO] [varchar](50) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANLMNO]  DEFAULT (NULL),
	[TRANLMDATE] [smalldatetime] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANLMDATE]  DEFAULT (NULL),
	[TRANLSID] [int] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANLSID]  DEFAULT ((0)),
	[TRANLSNO] [varchar](50) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANLMNO1]  DEFAULT (NULL),
	[TRANLSDATE] [smalldatetime] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANLMDATE1]  DEFAULT (NULL),
	[TRANNARTN] [varchar](250) NULL,
	[TRANRMKS] [varchar](250) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANRMKS]  DEFAULT (NULL),
	[TRANCSNAME] [varchar](50) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANCSNAME]  DEFAULT (NULL),
	[TRANPCOUNT] [int] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANPCOUNT]  DEFAULT ((0)),
	[CUSRID] [varchar](25) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_CUSRID]  DEFAULT ((0)),
	[LMUSRID] [varchar](100) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_LMUSRID]  DEFAULT (''),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_PRCSDATE]  DEFAULT (NULL),
	[TRANEAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANEAMT]  DEFAULT ((0)),
	[TRANFAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANFAMT]  DEFAULT ((0)),
	[TRANPAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANPAMT]  DEFAULT ((0)),
	[TRANTCAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANPAMT1]  DEFAULT ((0)),
	[TRANAAMT] [numeric](18, 0) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANAAMT]  DEFAULT ((0)),
	[TRANINOC1] [numeric](18, 0) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANINOC1]  DEFAULT ((0)),
	[TRANINOC2] [numeric](18, 0) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANINOC2]  DEFAULT ((0)),
	[TRANHBLNO] [varchar](50) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANHBLNO]  DEFAULT (NULL),
	[TRANPONO] [varchar](50) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANPONO]  DEFAULT (NULL),
	[TRANIMPADDR1] [varchar](100) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANIMPADDR1]  DEFAULT (NULL),
	[TRANIMPADDR2] [varchar](100) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANIMPADDR13]  DEFAULT (NULL),
	[TRANIMPADDR3] [varchar](100) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANIMPADDR12]  DEFAULT (NULL),
	[TRANIMPADDR4] [varchar](100) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANIMPADDR11]  DEFAULT (NULL),
	[LEMID] [int] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_LEMID]  DEFAULT ((0)),
	[TRANAHAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANAHAMT]  DEFAULT ((0)),
	[STRG_HSNCODE] [varchar](50) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_STRG_HSNCODE]  DEFAULT (NULL),
	[HANDL_HSNCODE] [varchar](50) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_HANDL_HSNCODE]  DEFAULT (NULL),
	[STRG_TAXABLE_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_STRG_TAXABLE_AMT]  DEFAULT ((0)),
	[HANDL_TAXABLE_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_HANDL_TAXABLE_AMT]  DEFAULT ((0)),
	[STRG_CGST_EXPRN] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_STRG_CGST_EXPRN]  DEFAULT ((0)),
	[STRG_SGST_EXPRN] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_STRG_SGST_EXPRN]  DEFAULT ((0)),
	[STRG_IGST_EXPRN] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_STRG_IGST_EXPRN]  DEFAULT ((0)),
	[STRG_CGST_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_STRG_CGST_AMT]  DEFAULT ((0)),
	[STRG_SGST_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_STRG_SGST_AMT]  DEFAULT ((0)),
	[STRG_IGST_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_STRG_IGST_AMT]  DEFAULT ((0)),
	[HANDL_CGST_EXPRN] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_HANDL_CGST_EXPRN]  DEFAULT ((0)),
	[HANDL_SGST_EXPRN] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_HANDL_SGST_EXPRN]  DEFAULT ((0)),
	[HANDL_IGST_EXPRN] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_HANDL_IGST_EXPRN]  DEFAULT ((0)),
	[HANDL_CGST_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_HANDL_CGST_AMT]  DEFAULT ((0)),
	[HANDL_SGST_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_HANDL_SGST_AMT]  DEFAULT ((0)),
	[HANDL_IGST_AMT] [numeric](18, 2) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_HANDL_IGST_AMT]  DEFAULT ((0)),
	[TRANGSTNO] [varchar](50) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRANGSTNO]  DEFAULT (NULL),
	[CATEAID] [int] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_CATEAID]  DEFAULT ((0)),
	[TALLYSTAT] [int] NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TALLYSTAT]  DEFAULT ((0)),
	[TRAN_COVID_DISC_AMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_TRAN_COVID_DISC_AMT]  DEFAULT ((0)),
	[IRNNO] [varchar](100) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_IRNNO]  DEFAULT (NULL),
	[ACKNO] [varchar](50) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_ACKNO]  DEFAULT (NULL),
	[ACKDT] [datetime] NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_ACKDT]  DEFAULT (NULL),
	[QRCODEPATH] [varchar](max) NULL CONSTRAINT [DF_CREDITNOTE_TRANSACTIONMASTER_QRCODEPATH]  DEFAULT (NULL),
	[TRANBILLREFNO] [varchar](35) NULL,
	[STATEID] [int] NULL DEFAULT ((0)),
	[CATEAGSTNO] [varchar](50) NULL DEFAULT (''),
	[TRANCGSTAMT] [numeric](18, 2) NOT NULL DEFAULT ((0)),
	[TRANSGSTAMT] [numeric](18, 2) NOT NULL DEFAULT ((0)),
	[TRANIGSTAMT] [numeric](18, 2) NOT NULL DEFAULT ((0)),
 CONSTRAINT [PK_CREDITNOTE_TRANSACTIONMASTER] PRIMARY KEY CLUSTERED 
(
	[TRANMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'AUTOMATIC / MANUAL' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONMASTER', @level2type=N'COLUMN',@level2name=N'TRANBTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'IF REGSTRID -6 SUPPLIERID 7-WARDID' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONMASTER', @level2type=N'COLUMN',@level2name=N'TRANREFID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SUPPLIER / DOCTOR / WARD NAME' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONMASTER', @level2type=N'COLUMN',@level2name=N'TRANREFNAME'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'MODE 0 -CASH 1 -CREDIT' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONMASTER', @level2type=N'COLUMN',@level2name=N'TRANMODE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'CHEQUE / CREDIT / CARD DETAIL' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONMASTER', @level2type=N'COLUMN',@level2name=N'TRANMODEDETL'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'REFERENCE NO (if any)' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONMASTER', @level2type=N'COLUMN',@level2name=N'TRANREFNO'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'SUPPLIER / DOCTOR / WARD NAME' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONMASTER', @level2type=N'COLUMN',@level2name=N'TRANREFBNAME'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'AMOUNT IN WORDS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONMASTER', @level2type=N'COLUMN',@level2name=N'TRANAMTWRDS'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ORIGINAL BILL NO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONMASTER', @level2type=N'COLUMN',@level2name=N'TRANLMID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'REMARKS' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONMASTER', @level2type=N'COLUMN',@level2name=N'TRANRMKS'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'CHA STAFF NAME' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONMASTER', @level2type=N'COLUMN',@level2name=N'TRANCSNAME'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ENTERED BY' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONMASTER', @level2type=N'COLUMN',@level2name=N'CUSRID'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'MODIFIED BY' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CREDITNOTE_TRANSACTIONMASTER', @level2type=N'COLUMN',@level2name=N'LMUSRID'
GO


