USE [SCFS_ERP]
GO
/****** Object:  Table [dbo].[CUSTOMERGROUPMASTER]    Script Date: 27-05-2025 14:52:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMERGROUPMASTER](
	[CUSTGID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTGDESC] [varchar](100) NOT NULL,
	[CUSRID] [varchar](100) NOT NULL,
	[LMUSRID] [int] NOT NULL,
	[DISPSTATUS] [smallint] NOT NULL,
	[PRCSDATE] [datetime] NOT NULL,
 CONSTRAINT [PK_CUSTOMERGROUPMASTER] PRIMARY KEY CLUSTERED 
(
	[CUSTGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMERGROUPMASTER] ADD  CONSTRAINT [DF_CUSTOMERGROUPMASTER_CUSTGDESC]  DEFAULT (NULL) FOR [CUSTGDESC]
GO
ALTER TABLE [dbo].[CUSTOMERGROUPMASTER] ADD  CONSTRAINT [DF_CUSTOMERGROUPMASTER_CUSRID]  DEFAULT ((0)) FOR [CUSRID]
GO
ALTER TABLE [dbo].[CUSTOMERGROUPMASTER] ADD  CONSTRAINT [DF_CUSTOMERGROUPMASTER_LMUSRID]  DEFAULT ((0)) FOR [LMUSRID]
GO
ALTER TABLE [dbo].[CUSTOMERGROUPMASTER] ADD  CONSTRAINT [DF_CUSTOMERGROUPMASTER_DISPSTATUS]  DEFAULT ((0)) FOR [DISPSTATUS]
GO
ALTER TABLE [dbo].[CUSTOMERGROUPMASTER] ADD  CONSTRAINT [DF_CUSTOMERGROUPMASTER_PRCSDATE]  DEFAULT (NULL) FOR [PRCSDATE]
GO
