USE [SCFS_ERP]
GO
SET IDENTITY_INSERT [dbo].[CUSTOMERGROUPMASTER] ON 
GO
INSERT [dbo].[CUSTOMERGROUPMASTER] ([CUSTGID], [CUSTGDESC], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (1, N'General', N'admin', 1, 0, CAST(N'2020-04-01T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[CUSTOMERGROUPMASTER] ([CUSTGID], [CUSTGDESC], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (2, N'Group of Companies', N'admin', 1, 0, CAST(N'2020-04-01T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[CUSTOMERGROUPMASTER] ([CUSTGID], [CUSTGDESC], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (3, N'Sister Concern', N'admin', 1, 0, CAST(N'2020-04-01T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[CUSTOMERGROUPMASTER] ([CUSTGID], [CUSTGDESC], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (4, N'Reference', N'admin', 1, 0, CAST(N'2020-04-01T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[CUSTOMERGROUPMASTER] ([CUSTGID], [CUSTGDESC], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (5, N'OEM', N'admin', 1, 0, CAST(N'2020-04-01T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[CUSTOMERGROUPMASTER] ([CUSTGID], [CUSTGDESC], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE]) VALUES (6, N'SEZ', N'admin', 1, 0, CAST(N'2021-04-01T00:00:00.000' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[CUSTOMERGROUPMASTER] OFF
GO




UPDATE CATEGORYMASTER SET CUSTGID = 1