select * from scfs_erp..ACCOUNTINGYEAR where fdate = '2022-04-01'

select * from TRANSACTIONMASTER where COMPYID = 25 order by TRANMID desc

select * from BONDTRANSACTIONMASTER where COMPYID = 25 order by TRANMID desc

select * from spbw..TRANSACTIONDETAIL join spbw..TRANSACTIONMASTER on transactiondetail.tranmid = TRANSACTIONMASTER.tranmid 
where COMPYID = 25 
--and (isnull(EBNDID,0) = 0 or isnull(TRANDEBNDNO,'-') = '-')
order by transactiondetail.TRANMID desc


select * from BONDTRANSACTIONDETAIL join BONDTRANSACTIONMASTER on BONDTRANSACTIONDETAIL.tranmid = BONDTRANSACTIONMASTER.tranmid 
where COMPYID = 25 
--and (isnull(EBNDID,0) = 0 or isnull(TRANDEBNDNO,'-') = '-')
order by BONDTRANSACTIONDETAIL.TRANMID desc

select BNDIGMNO,count('*') from BONDMASTER where COMPYID = 25  group by BNDIGMNO
select * from spbw..BONDMASTER where COMPYID = 25 

select * from  spbw..EXBONDMASTER where COMPYID = 25 

select * from EXBONDMASTER where COMPYID = 25 

select * from SPBW..CATEGORYMASTER 
	select b.catename,a.* From  SPBW..CATEGORYMASTER b  left join CATEGORYMASTER a
	on b.catetid = a.CATETID and b.cateid = a.cateid and b.CATENAME = a.CATENAME
where b.CATENAME is null

select BNDID, COMPYID,  SDPTID,  BNDNO,  BNDDNO,  BNDDATE, BNDFDATE, BNDTDATE,  BNDADATE,  IMPRTID, CHAID,
YRDID, TYPEID, BNDBENO, BNDBLNO, BNDIGMNO, BND20, BND40, BNDGWGHT, BNDCIFAMT, BNDDTYAMT, BNDINSAMT, BNDBCIFAMT,
BNDBDTYAMT, BNDBINSAMT, GWNID,PRDTGID,BNDNOP,BNDSPC,BNDBNOP,BNDBSPC,BNDHAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,
CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, BNDBEDATE,BNDBLDATE
from BONDMASTER



BILLREFID
TRANGSTNO

select  distinct a.* from spbw..CATEGORYMASTER a (nolock) join spbw..TRANSACTIONMASTER b (nolock) on a.cateid = b.CHAID 
union
select distinct a.* from spbw..CATEGORYMASTER a (nolock) join spbw..TRANSACTIONMASTER b (nolock) on a.cateid = b.IMPRTID
where CATETID>0

select  *  From spbw..CATEGORYMASTER
select  * into Init_Bond_CATEGORY_ADDRESS_DETAIL From spbw..CATEGORY_ADDRESS_DETAIL

select * into BEFORE_BOND_CATEGORYMASTER_BKUP211022
FROM SCFS_ERP..CATEGORYMASTER

SELECT * FROM spbw..CATEGORYMASTER
SELECT * FROM SCFS_ERP..CATEGORYMASTER
SELECT B.CATENAME, B.CATEID,B.CATETID,B.DISPSTATUS, A.* 
FROM Init_Bond_CategoryMaster A(NOLOCK) JOIN SCFS_ERP..CATEGORYMASTER B(NOLOCK) ON A.CATENAME = B.CATENAME
WHERE curcateid IS NULL
select * From SCFS_ERP..Init_Bond_CategoryMaster


SELECT DISTINCT TYPEID FROM SPBW..BONDMASTER

SELECT * FROM SPBW..BONDMASTER WHERE COMPYID=25 
SELECT * FROM SCFS_ERP..BONDMASTER WHERE COMPYID=31 

SELECT TOP 3 * FROM SPBW..EXBONDMASTER WHERE COMPYID=25 --ORDER BY EBNDID DESC
SELECT TOP 3 * FROM SCFS_ERP..EXBONDMASTER WHERE COMPYID=31 


SELECT B.CFID OLDCFID, B.CFDESC 'NEWCFDESC', B.CFTYPE 'NEWCFTYPE', B.CFEXPR 'NEWCFEXPR', B.DORDRID 'NEWDORDRID',A.* 
fROM SPBW..COSTFACTORMASTER A (NOLOCK) LEFT JOIN SCFS_ERP..COSTFACTORMASTER  B(NOLOCK) ON A.CFDESC = B.CFDESC
