-- select * from SOFT_TABLE_DELETE_DETAIL (nolock) 
if not exists (select '*' from SOFT_TABLE_DELETE_DETAIL (nolock) where OPTNSTR = 'GATEINDETAIL' and tabname ='AUTHORIZATIONSLIPDETAIL')
begin
	insert into SOFT_TABLE_DELETE_DETAIL
	select 49, 'GATEINDETAIL', 'AUTHORIZATIONSLIPDETAIL', 'GIDID', 'GIDID=', 'Selected Record Exists In Non PNR Authorization Slip Detail..........................!'
end


if not exists (select '*' from SOFT_TABLE_DELETE_DETAIL (nolock) where OPTNSTR = 'AUTHORIZATIONSLIPDETAIL' and tabname ='VEHICLETICKET')
begin
	insert into SOFT_TABLE_DELETE_DETAIL
	select 50, 'AUTHORIZATIONSLIPDETAIL', 'VEHICLETICKETDETAIL INNER JOIN AUTHORIZATIONSLIPDETAIL ON AUTHORIZATIONSLIPDETAIL.ASLDID=VEHICLETICKETDETAIL.ASLDID INNER JOIN AUTHORIZATIONSLIPMASTER ON AUTHORIZATIONSLIPMASTER.ASLMID=AUTHORIZATIONSLIPDETAIL.ASLMID ', 'VTDID', 'AUTHORIZATIONSLIPDETAIL.ASLDID=', 'Selected Record Exists In Vehicle Ticket Detail..........................!'
end



/*
select * from SOFT_TABLE_DELETE_DETAIL
where OPTNSTR= 'GATEINDETAIL'

GATEINDETAIL	OPENSHEETDETAIL	OSDID	GIDID=	Selected Record Exists In Open Sheet Detail..........................!
SELECT * FROM AUTHORIZATIONSLIPDETAIL
SELECT * FROM VEHICLETICKETDETAIL
SELECT * FROM GATEOUTDETAIL



insert into SOFT_TABLE_DELETE_DETAIL
select 50, 'AUTHORIZATIONSLIPDETAIL', 'VEHICLETICKETDETAIL INNER JOIN AUTHORIZATIONSLIPDETAIL ON AUTHORIZATIONSLIPDETAIL.ASLDID=VEHICLETICKETDETAIL.ASLDID INNER JOIN AUTHORIZATIONSLIPMASTER ON AUTHORIZATIONSLIPMASTER.ASLMID=AUTHORIZATIONSLIPDETAIL.ASLMID ', 'VTDID', 'AUTHORIZATIONSLIPMASTER.ASLMID=', 'Selected Record Exists In Vehicle Ticket Detail..........................!'

insert into SOFT_TABLE_DELETE_DETAIL
select 51, 'VEHICLETICKET', 'GATEOUT', 'GIDID', 'GIDID=', 'Selected Record Exists In Non PNR Authorization Slip IN Detail..........................!'
*/