USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[DELIVERYORDERDETAIL]    Script Date: 27-08-2021 11:24:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
drop table [DELIVERYORDERDETAIL]
CREATE TABLE [dbo].[DELIVERYORDERDETAIL](
	[DODID] [int] IDENTITY(1,1) NOT NULL,
	[DOMID] [int] NOT NULL,
	[BILLEDID] [int] NOT NULL,
	[DODREFID] [int] NOT NULL,
	[DODREFNAME] [varchar](100) NULL,
	[DODREFNO] [varchar](15) NULL,
	[DOIDATE] [smalldatetime] NULL,
	[DOVDATE] [smalldatetime] NULL,
	[DISPSTATUS] [smallint] NOT NULL,
 CONSTRAINT [PK_DELIVERYORDERDETAIL] PRIMARY KEY CLUSTERED 
(
	[DODID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DELIVERYORDERDETAIL] ADD  CONSTRAINT [DF_DELIVERYORDERDETAIL_DOMID]  DEFAULT ((0)) FOR [DOMID]
GO

ALTER TABLE [dbo].[DELIVERYORDERDETAIL] ADD  CONSTRAINT [DF_DELIVERYORDERDETAIL_BILLEDID]  DEFAULT ((0)) FOR [BILLEDID]
GO

ALTER TABLE [dbo].[DELIVERYORDERDETAIL] ADD  CONSTRAINT [DF_DELIVERYORDERDETAIL_DODREFID]  DEFAULT ((0)) FOR [DODREFID]
GO

ALTER TABLE [dbo].[DELIVERYORDERDETAIL] ADD  CONSTRAINT [DF_DELIVERYORDERDETAIL_DODREFNAME]  DEFAULT (NULL) FOR [DODREFNAME]
GO

ALTER TABLE [dbo].[DELIVERYORDERDETAIL] ADD  CONSTRAINT [DF_DELIVERYORDERDETAIL_DODREFNO]  DEFAULT (NULL) FOR [DODREFNO]
GO

ALTER TABLE [dbo].[DELIVERYORDERDETAIL] ADD  CONSTRAINT [DF_DELIVERYORDERDETAIL_DOIDATE]  DEFAULT (NULL) FOR [DOIDATE]
GO

ALTER TABLE [dbo].[DELIVERYORDERDETAIL] ADD  CONSTRAINT [DF_DELIVERYORDERDETAIL_DOVDATE]  DEFAULT (NULL) FOR [DOVDATE]
GO

ALTER TABLE [dbo].[DELIVERYORDERDETAIL] ADD  CONSTRAINT [DF_DELIVERYORDERDETAIL_DISPSTATUS]  DEFAULT ((0)) FOR [DISPSTATUS]
GO

ALTER TABLE [dbo].[DELIVERYORDERDETAIL]  WITH CHECK ADD  CONSTRAINT [FK_DELIVERYORDERDETAIL_DELIVERYORDERMASTER] FOREIGN KEY([DOMID])
REFERENCES [dbo].[DELIVERYORDERMASTER] ([DOMID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[DELIVERYORDERDETAIL] CHECK CONSTRAINT [FK_DELIVERYORDERDETAIL_DELIVERYORDERMASTER]
GO


