USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[DELIVERYORDERMASTER]    Script Date: 27-08-2021 11:24:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
drop table [DELIVERYORDERMASTER]
CREATE TABLE [dbo].[DELIVERYORDERMASTER](
	[DOMID] [int] IDENTITY(1,1) NOT NULL,
	[COMPYID] [int] NOT NULL,
	[SDPTID] [int] NOT NULL,
	[DODATE] [smalldatetime] NOT NULL,
	[DOTIME] [datetime] NOT NULL,
	[DONO] [int] NOT NULL,
	[DODNO] [varchar](50) NOT NULL,
	[DOREFID] [int] NOT NULL,
	[DOREFNAME] [varchar](100) NOT NULL,
	[DOREFNO] [varchar](25) NULL,
	[DOREFDATE] [smalldatetime] NULL,
	[DONARTN] [varchar](250) NULL,
	[DORMKS] [varchar](250) NULL,
	[DOPCOUNT] [int] NULL,
	[CUSRID] [varchar](25) NULL,
	[LMUSRID] [varchar](25) NULL,
	[DISPSTATUS] [smallint] NULL,
	[PRCSDATE] [datetime] NULL,
	[DOMODE] [smallint] NULL,
	[DOMODEDETL] [varchar](150) NULL,
	[DOREFBNAME] [varchar](100) NULL,
	[DOREFAMT] [numeric](18, 2) NULL,
	[TARIFFMID] [int] NULL,
	[BANKMID] [int] NULL,
 CONSTRAINT [PK_DELIVERYORDERMASTER] PRIMARY KEY CLUSTERED 
(
	[DOMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_COMPYID]  DEFAULT ((0)) FOR [COMPYID]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_SDPTID]  DEFAULT ((0)) FOR [SDPTID]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DODATE]  DEFAULT (NULL) FOR [DODATE]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DOTIME]  DEFAULT (NULL) FOR [DOTIME]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DONO]  DEFAULT ((0)) FOR [DONO]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DODNO]  DEFAULT (NULL) FOR [DODNO]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DOREFID]  DEFAULT ((0)) FOR [DOREFID]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DOREFNAME]  DEFAULT (NULL) FOR [DOREFNAME]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DOREFNO]  DEFAULT (NULL) FOR [DOREFNO]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DOREFDATE]  DEFAULT (NULL) FOR [DOREFDATE]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DONARTN]  DEFAULT (NULL) FOR [DONARTN]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DORMKS]  DEFAULT (NULL) FOR [DORMKS]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DOPCOUNT]  DEFAULT ((0)) FOR [DOPCOUNT]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_CUSRID]  DEFAULT ('') FOR [CUSRID]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_LMUSRID]  DEFAULT (('')) FOR [LMUSRID]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DISPSTATUS]  DEFAULT ((0)) FOR [DISPSTATUS]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_PRCSDATE]  DEFAULT (NULL) FOR [PRCSDATE]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DOMODE]  DEFAULT ((0)) FOR [DOMODE]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DOMODEDETL]  DEFAULT (NULL) FOR [DOMODEDETL]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DOREFBNAME]  DEFAULT (NULL) FOR [DOREFBNAME]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_DOREFAMT]  DEFAULT ((0)) FOR [DOREFAMT]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_TARIFFMID]  DEFAULT ((0)) FOR [TARIFFMID]
GO

ALTER TABLE [dbo].[DELIVERYORDERMASTER] ADD  CONSTRAINT [DF_DELIVERYORDERMASTER_BANKMID]  DEFAULT ((0)) FOR [BANKMID]
GO


