USE SCFS_ERP
GO
alter table DELIVERYORDERMASTER
add OOCNO varchar(50) NULL 
GO
alter table DELIVERYORDERMASTER
add OOCDATE DATETIME  NULL  

GO
UPDATE DELIVERYORDERMASTER
SET OOCNO = ''
WHERE OOCNO IS NULL

UPDATE DELIVERYORDERMASTER
SET OOCDATE = CONVERT(VARCHAR(10),PRCSDATE,120)
WHERE OOCDATE IS NULL