select * from SOFT_DEPARTMENTMASTER

update SOFT_DEPARTMENTMASTER
set SDPTNAME = 'EMPTY', OPTNSTR = 'EMPTY'
WHERE SDPTID = 3
AND SDPTNAME = 'CARGO'

update SOFT_DEPARTMENTMASTER
set SDPTNAME = 'CARGO', OPTNSTR = 'CARGO'
WHERE SDPTID = 4
AND SDPTNAME = 'GENERAL'