SELECT COUNT('*') FROM EXBONDMASTER
BEGIN  TRAN
SET IDENTITY_INSERT SCFS_ERP.DBO.EXBONDMASTER ON 
INSERT INTO SCFS_ERP.DBO.EXBONDMASTER
(
EBNDID,COMPYID,SDPTID,EBNDNO,EBNDDNO,EBNDDATE,IMPRTID,CHAID,EBNDBENO,EBNDBEDATE,BNDID,TYPEID,CONTNRSID,PRDTGID,EBNDCTYPE,EBNDNOC,
EBNDNOP,EBNDSPC,EBNDASSAMT,EBNDDTYAMT,EBNDINSAMT,EBNDBSPC,EBNDBCFAMT,EBNDBDTYAMT,EBNDDBINSAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,
INVDID,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE,EBNDEDATE
)

SELECT 
EBNDID,31,10,EBNDNO,EBNDDNO,EBNDDATE,IMPRTID,CHAID,EBNDBENO,EBNDBEDATE,BNDID,TYPEID,CONTNRSID,PRDTGID,EBNDCTYPE+1,EBNDNOC,
EBNDNOP,EBNDSPC,EBNDASSAMT,EBNDDTYAMT,EBNDINSAMT,EBNDBSPC,EBNDBCFAMT,EBNDBDTYAMT,EBNDDBINSAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,
INVDID,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE,EBNDEDATE
FROM SPBW..EXBONDMASTER A
WHERE COMPYID=25 
SET IDENTITY_INSERT SCFS_ERP.DBO.EXBONDMASTER OFF
SELECT COUNT('*') FROM EXBONDMASTER
--ROLLBACK TRAN
COMMIT TRAN

SELECT COUNT('*') FROM EXBONDMASTER