select *from CREDITNOTE_TRANSACTIONDETAIL

select *from TRANSACTIONMASTER where SDPTID=2 --TRANDNO='IMP/2122/00002'

select *from TRANSACTIONDETAIL where TRANMID in( 1028,1038,1039,1041,1042)


DECLARE @TableMaster Table(
  STRG_CGST_EXPRN numeric(18,0) not null,
  STRG_IGST_EXPRN numeric(18,0) not null,
  STRG_SGST_EXPRN numeric(18,0) not null,
  HANDL_CGST_EXPRN numeric(18,0) not null,
  HANDL_IGST_EXPRN numeric(18,0) not null,
  HANDL_SGST_EXPRN numeric(18,0) not null,  
  TRAND_STRG_CGST_AMT numeric(18,0) not null,
  TRAND_STRG_IGST_AMT  numeric(18,0) not null,
  TRAND_STRG_SGST_AMT  numeric(18,0) not null,   
  TRAND_HANDL_CGST_AMT numeric(18,0) not null,
  TRAND_HANDL_IGST_AMT numeric(18,0) not null,
  TRAND_HANDL_SGST_AMT numeric(18,0) not null,
  STRG_CGST_AMT numeric(18,0) not null,
  STRG_IGST_AMT numeric(18,0) not null,
  STRG_SGST_AMT numeric(18,0) not null,
  HANDL_CGST_AMT numeric(18,0) not null,
  HANDL_IGST_AMT numeric(18,0) not null,
  HANDL_SGST_AMT numeric(18,0) not null,
  TRANCGSTAMT numeric(18,0) not null,
  TRANIGSTAMT numeric(18,0) not null,
  TRANSGSTAMT numeric(18,0) not null,
  TRANGAMT numeric(18,0) not null,
  TRANDGAMT numeric(18,0) not null,
  TRANDNAMT numeric(18,0) not null,		
  TRANNAMT numeric(18,0) not null 
)

Insert Into  @TableMaster(STRG_CGST_EXPRN,STRG_IGST_EXPRN,STRG_SGST_EXPRN,
                          HANDL_CGST_EXPRN,HANDL_IGST_EXPRN,HANDL_SGST_EXPRN,
						  TRAND_STRG_CGST_AMT,TRAND_STRG_IGST_AMT,TRAND_STRG_SGST_AMT,
						  TRAND_HANDL_CGST_AMT,TRAND_HANDL_IGST_AMT,TRAND_HANDL_SGST_AMT,
						  STRG_CGST_AMT,STRG_IGST_AMT,STRG_SGST_AMT,
						  HANDL_CGST_AMT,HANDL_IGST_AMT,HANDL_SGST_AMT,
						  TRANCGSTAMT,TRANIGSTAMT,TRANSGSTAMT,TRANGAMT,
						  TRANDGAMT, TRANDNAMT,TRANNAMT )

SELECT TRANSACTIONMASTER.STRG_CGST_EXPRN,TRANSACTIONMASTER.STRG_IGST_EXPRN,TRANSACTIONMASTER.STRG_SGST_EXPRN,
       TRANSACTIONMASTER.HANDL_CGST_EXPRN, TRANSACTIONMASTER.HANDL_IGST_EXPRN, TRANSACTIONMASTER.HANDL_SGST_EXPRN , 
	   TRANSACTIONMASTER.STRG_CGST_AMT,TRANSACTIONMASTER.STRG_IGST_AMT,TRANSACTIONMASTER.STRG_SGST_AMT,
       TRANSACTIONMASTER.HANDL_CGST_AMT, TRANSACTIONMASTER.HANDL_IGST_AMT, TRANSACTIONMASTER.HANDL_SGST_AMT ,
	   TRANSACTIONDETAIL.TRAND_STRG_CGST_AMT,TRANSACTIONDETAIL.TRAND_STRG_IGST_AMT,TRANSACTIONDETAIL.TRAND_STRG_SGST_AMT,
	   TRANSACTIONDETAIL.TRAND_HANDL_CGST_AMT,TRANSACTIONDETAIL.TRAND_HANDL_IGST_AMT,TRANSACTIONDETAIL.TRAND_HANDL_SGST_AMT,
	   TRANSACTIONMASTER.TRANCGSTAMT,TRANSACTIONMASTER.TRANIGSTAMT,TRANSACTIONMASTER.TRANSGSTAMT,TRANSACTIONMASTER.TRANGAMT,
	   TRANSACTIONDETAIL.TRANDGAMT,  TRANSACTIONDETAIL.TRANDNAMT, TRANSACTIONMASTER.TRANNAMT 

 from TRANSACTIONDETAIL (Nolock) INNER JOIN  
TRANSACTIONMASTER (Nolock) ON TRANSACTIONDETAIL.TRANMID = TRANSACTIONMASTER.TRANMID 

WHERE TRANSACTIONDETAIL.TRANMID = 1041  AND TRANSACTIONMASTER.SDPTID=1 GROUP BY 
      TRANSACTIONMASTER.STRG_CGST_EXPRN,TRANSACTIONMASTER.STRG_IGST_EXPRN,TRANSACTIONMASTER.STRG_SGST_EXPRN, 
	  TRANSACTIONMASTER.HANDL_CGST_EXPRN, TRANSACTIONMASTER.HANDL_IGST_EXPRN, TRANSACTIONMASTER.HANDL_SGST_EXPRN , 
	  TRANSACTIONMASTER.STRG_CGST_AMT,TRANSACTIONMASTER.STRG_IGST_AMT,TRANSACTIONMASTER.STRG_SGST_AMT,
      TRANSACTIONMASTER.HANDL_CGST_AMT, TRANSACTIONMASTER.HANDL_IGST_AMT, TRANSACTIONMASTER.HANDL_SGST_AMT ,
	  TRANSACTIONDETAIL.TRAND_STRG_CGST_AMT,TRANSACTIONDETAIL.TRAND_STRG_IGST_AMT,TRANSACTIONDETAIL.TRAND_STRG_SGST_AMT,
	  TRANSACTIONDETAIL.TRAND_HANDL_CGST_AMT,TRANSACTIONDETAIL.TRAND_HANDL_IGST_AMT,TRANSACTIONDETAIL.TRAND_HANDL_SGST_AMT,
	  TRANSACTIONMASTER.TRANCGSTAMT,TRANSACTIONMASTER.TRANIGSTAMT,TRANSACTIONMASTER.TRANSGSTAMT,TRANSACTIONMASTER.TRANGAMT,
	  TRANSACTIONDETAIL.TRANDGAMT,  TRANSACTIONDETAIL.TRANDNAMT, TRANSACTIONMASTER.TRANNAMT 

	   Select Isnull(STRG_CGST_EXPRN,0) as STRG_CGST_EXPRN, Isnull(STRG_IGST_EXPRN,0) as STRG_IGST_EXPRN,Isnull(STRG_SGST_EXPRN,0) as STRG_SGST_EXPRN,
	          Isnull(HANDL_CGST_EXPRN,0) as HANDL_CGST_EXPRN, Isnull(HANDL_IGST_EXPRN,0) as HANDL_IGST_EXPRN,Isnull(HANDL_SGST_EXPRN,0) as HANDL_SGST_EXPRN,
			   STRG_CGST_AMT, STRG_IGST_AMT,STRG_SGST_AMT,
			   HANDL_CGST_AMT,  HANDL_IGST_AMT, HANDL_SGST_AMT,
			  TRAND_STRG_CGST_AMT, TRAND_STRG_IGST_AMT,TRAND_STRG_SGST_AMT,
			  TRAND_HANDL_CGST_AMT, TRAND_HANDL_IGST_AMT,TRAND_HANDL_SGST_AMT,
			  TRANCGSTAMT,TRANIGSTAMT,TRANSGSTAMT,TRANGAMT,
			  TRANDGAMT, TRANDNAMT,TRANNAMT
	    FROM @TableMaster