USE [SCFS_ERP]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDREMKRS]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDDATE1]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_PRCSDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_DISPSTATUS]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_LMUSRID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_CUSRID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_INVDID1]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_INSREDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_INSRSDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_STRGEDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_STRGSDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDDBINSAMT]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDBDTYAMT]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDBCFAMT]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDDBSPC]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDDINSAMT]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDDDTYAMT]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDDASSAMT]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDDSPC]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDDNOP]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDDCONTRS]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_CTYPE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_PRDTID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_CONTRSID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_TYPEID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_BNDID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDDBEDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDDBENO]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_CHAID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_IMPRTID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EDBNDNO]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_EBNDNO]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_SDPTID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] DROP CONSTRAINT [DF_EXBONDMASTER_COMPYID]
GO

/****** Object:  Table [dbo].[EXBONDMASTER]    Script Date: 13-10-2022 11:40:32 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EXBONDMASTER]') AND type in (N'U'))
DROP TABLE [dbo].[EXBONDMASTER]
GO

/****** Object:  Table [dbo].[EXBONDMASTER]    Script Date: 13-10-2022 11:40:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EXBONDMASTER](
	[EBNDID] [int] NOT NULL identity(1,1),
	[COMPYID] [int] NULL,
	[SDPTID] [int] NULL,
	[EBNDNO] [int] NULL,
	[EBNDDNO] [varchar](50) NULL,
	[EBNDDATE] [smalldatetime] NULL,
	[IMPRTID] [int] NULL,
	[CHAID] [int] NULL,
	[EBNDBENO] [varchar](50) NULL,
	[EBNDBEDATE] [smalldatetime] NULL,
	[BNDID] [int] NULL,
	[TYPEID] [smallint] NULL,
	[CONTNRSID] [int] NULL,
	[PRDTGID] [int] NULL,
	[EBNDCTYPE] [smallint] NULL,
	[EBNDNOC] [int] NULL,
	[EBNDNOP] [numeric](18, 2) NULL,
	[EBNDSPC] [numeric](18, 2) NULL,
	[EBNDASSAMT] [numeric](18, 2) NULL,
	[EBNDDTYAMT] [numeric](18, 2) NULL,
	[EBNDINSAMT] [numeric](18, 2) NULL,
	[EBNDBSPC] [numeric](18, 2) NULL,
	[EBNDBCFAMT] [numeric](18, 2) NULL,
	[EBNDBDTYAMT] [numeric](18, 2) NULL,
	[EBNDDBINSAMT] [numeric](18, 2) NULL,
	[STRGSDATE] [smalldatetime] NULL,
	[STRGEDATE] [smalldatetime] NULL,
	[INSRSDATE] [smalldatetime] NULL,
	[INSREDATE] [smalldatetime] NULL,
	[INVDID] [int] NULL,
	[CUSRID] [varchar](50) NULL,
	[LMUSRID] [varchar](50) NULL,
	[DISPSTATUS] [smallint] NULL,
	[PRCSDATE] [smalldatetime] NULL,
	[EBNDEDATE] [smalldatetime] NULL,
	[EBNDREMKRS] [varchar](100) NULL,
 CONSTRAINT [PK_EXBONDMASTER] PRIMARY KEY CLUSTERED 
(
	[EBNDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_COMPYID]  DEFAULT (0) FOR [COMPYID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_SDPTID]  DEFAULT (0) FOR [SDPTID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDNO]  DEFAULT (0) FOR [EBNDNO]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EDBNDNO]  DEFAULT (null) FOR [EBNDDNO]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDDATE]  DEFAULT (null) FOR [EBNDDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_IMPRTID]  DEFAULT (0) FOR [IMPRTID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_CHAID]  DEFAULT (0) FOR [CHAID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDDBENO]  DEFAULT (null) FOR [EBNDBENO]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDDBEDATE]  DEFAULT (null) FOR [EBNDBEDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_BNDID]  DEFAULT (0) FOR [BNDID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_TYPEID]  DEFAULT (0) FOR [TYPEID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_CONTRSID]  DEFAULT (0) FOR [CONTNRSID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_PRDTID]  DEFAULT (0) FOR [PRDTGID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_CTYPE]  DEFAULT (0) FOR [EBNDCTYPE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDDCONTRS]  DEFAULT (0) FOR [EBNDNOC]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDDNOP]  DEFAULT (0) FOR [EBNDNOP]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDDSPC]  DEFAULT (0) FOR [EBNDSPC]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDDASSAMT]  DEFAULT (0) FOR [EBNDASSAMT]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDDDTYAMT]  DEFAULT (0) FOR [EBNDDTYAMT]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDDINSAMT]  DEFAULT (0) FOR [EBNDINSAMT]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDDBSPC]  DEFAULT (0) FOR [EBNDBSPC]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDBCFAMT]  DEFAULT (0) FOR [EBNDBCFAMT]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDBDTYAMT]  DEFAULT (0) FOR [EBNDBDTYAMT]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDDBINSAMT]  DEFAULT (0) FOR [EBNDDBINSAMT]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_STRGSDATE]  DEFAULT (null) FOR [STRGSDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_STRGEDATE]  DEFAULT (null) FOR [STRGEDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_INSRSDATE]  DEFAULT (null) FOR [INSRSDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_INSREDATE]  DEFAULT (null) FOR [INSREDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_INVDID1]  DEFAULT (0) FOR [INVDID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_CUSRID]  DEFAULT ('') FOR [CUSRID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_LMUSRID]  DEFAULT ('') FOR [LMUSRID]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_DISPSTATUS]  DEFAULT (0) FOR [DISPSTATUS]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_PRCSDATE]  DEFAULT (null) FOR [PRCSDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDDATE1]  DEFAULT (null) FOR [EBNDEDATE]
GO

ALTER TABLE [dbo].[EXBONDMASTER] ADD  CONSTRAINT [DF_EXBONDMASTER_EBNDREMKRS]  DEFAULT (NULL) FOR [EBNDREMKRS]
GO


