/****** Object:  View [dbo].[VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN_01]    Script Date: 12-10-2022 11:29:29 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN_01]'))
DROP VIEW [dbo].[VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN_01]
GO
/****** Object:  View [dbo].[VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN]    Script Date: 12-10-2022 11:29:29 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN]'))
DROP VIEW [dbo].[VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN]
GO


CREATE VIEW [dbo].[VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN_01]
AS
SELECT     BNDID, SUM(EBNDNOP) AS EBNDNOP, SUM(EBNDSPC) AS EBNDSPC, SUM(EBNDASSAMT) AS EBNDASSAMT, SUM(EBNDDTYAMT) AS EBNDDTYAMT,
                       SUM(EBNDINSAMT) AS EBNDINSAMT
FROM         dbo.EXBONDMASTER (nolock)
GROUP BY BNDID
GO
/****** Object:  View [dbo].[VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN]    Script Date: 12-10-2022 11:29:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN]
AS
SELECT     dbo.BONDMASTER.BNDID, dbo.BONDMASTER.TYPEID, dbo.BONDMASTER.PRDTGID, dbo.BONDPRODUCTGROUPMASTER.PRDTGDESC, 
                      dbo.BONDMASTER.BNDNOP - ISNULL(dbo.VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN_01.EBNDNOP, 0) AS BBNDNOP, 
                      dbo.BONDMASTER.BNDSPC - ISNULL(dbo.VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN_01.EBNDSPC, 0) AS BBNDSPC, 
                      dbo.BONDMASTER.BNDCIFAMT - ISNULL(dbo.VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN_01.EBNDASSAMT, 0) AS BBNDCIFAMT, 
                      dbo.BONDMASTER.BNDDTYAMT - ISNULL(dbo.VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN_01.EBNDDTYAMT, 0) AS BBNDDTYAMT, 
                      dbo.BONDMASTER.BNDINSAMT - ISNULL(dbo.VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN_01.EBNDINSAMT, 0) AS BBNDINSAMT
FROM         dbo.BONDMASTER (nolock) INNER JOIN
                      dbo.BONDPRODUCTGROUPMASTER (nolock) ON dbo.BONDMASTER.PRDTGID = dbo.BONDPRODUCTGROUPMASTER.PRDTGID LEFT OUTER JOIN
                      dbo.VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN_01 (nolock) ON 
                      dbo.BONDMASTER.BNDID = dbo.VW_EXBOND_BOND_BALANCE_DETAIL_ASSGN_01.BNDID
GO