USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[EXPORTSHIPPINGBILLMASTER]    Script Date: 13-08-2021 14:54:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
/*SELECT * --INTO  EXPORTSHIPPINGBILLMASTER_BKUP13082021
FROM [EXPORTSHIPPINGBILLMASTER]
ORDER BY ESBMID
DROP TABLE [EXPORTSHIPPINGBILLMASTER]
*/
CREATE TABLE [dbo].[EXPORTSHIPPINGBILLMASTER](
	[ESBMID] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[COMPYID] [int] NOT NULL,
	[ESBMDNO] [varchar](50) NULL,
	[ESBMDATE] [smalldatetime] NULL,
	[EXPRTID] [int] NULL,
	[EXPRTNAME] [varchar](100) NULL,
	[CHAID] [int] NULL,
	[CHANAME] [varchar](100) NULL,
	[ESBMREFNO] [varchar](25) NULL,
	[ESBMREFDATE] [smalldatetime] NULL,
	[ESBMREFAMT] [numeric](18, 2) NULL,
	[ESBMFOBAMT] [numeric](18, 2) NULL,
	[ESBMDPNAME] [varchar](50) NULL,
	[PRDTGID] [int] NULL,
	[PRDTDESC] [varchar](100) NULL,
	[ESBMNOP] [numeric](18, 2) NULL,
	[ESBMQTY] [numeric](18, 4) NULL,
	[ESBMRMKS] [varchar](250) NULL,
	[ESBMITYPE] [smallint] NULL,
	[ESBMIDATE] [smalldatetime] NULL,
	[CUSRID] [varchar](100) NULL,
	[LMUSRID] [varchar](100) NULL,
	[PRCSDATE] [datetime] NULL,
	[DISPSTATUS] [smallint] NOT NULL,
	[ESBMNO] [int] NOT NULL DEFAULT ((0))
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

--SET IDENTITY_INSERT dbo.[EXPORTSHIPPINGBILLMASTER] ON;  

--INSERT INTO [EXPORTSHIPPINGBILLMASTER]
--SELECT * FROM EXPORTSHIPPINGBILLMASTER_BKUP13082021
--ORDER BY ESBMID