USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[EXPORT_STUFF_TYPE_MASTER]    Script Date: 03-08-2021 18:00:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EXPORT_STUFF_TYPE_MASTER](
	[ESTID] [int] NOT NULL,
	[ESTDESC] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ESTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


