SET IDENTITY_INSERT DBO.EXPORTSLABTYPEMASTER ON
select * from EXPORTSLABTYPEMASTER
if not exists(select * from EXPORTSLABTYPEMASTER where SLABTID = 20)
begin
	insert into EXPORTSLABTYPEMASTER (SLABTID, SLABTDESC, SLABTCODE, DISPORDER, HSNID, CUSRID, LMUSRID, DISPSTATUS,
			PRCSDATE, SLABSTYPE)
	select 20, 'E-SEAL STORAGE CHARGES', '996729', 0,2,1,1,0,GETDATE(),NULL
end

if not exists(select * from EXPORTSLABTYPEMASTER where SLABTID = 21)
begin
	insert into EXPORTSLABTYPEMASTER (SLABTID, SLABTDESC, SLABTCODE, DISPORDER, HSNID, CUSRID, LMUSRID, DISPSTATUS,
			PRCSDATE, SLABSTYPE)
	select 21, 'E-SEAL HANDLING CHARGES', '996729', 0,2,1,1,0,GETDATE(),NULL
end
select * from EXPORTSLABTYPEMASTER
SET IDENTITY_INSERT DBO.EXPORTSLABTYPEMASTER OFF