ALTER TABLE [dbo].EXPORT_OPERATIONTYPEMASTER DROP CONSTRAINT DF_EXPORT_OPERATIONTYPEMASTER_LMUSRID
GO

alter table EXPORT_OPERATIONTYPEMASTER 
alter column LMUSRID varchar(100)  null 

ALTER TABLE [dbo].EXPORT_OPERATIONTYPEMASTER ADD  CONSTRAINT DF_EXPORT_OPERATIONTYPEMASTER_LMUSRID  DEFAULT (('')) FOR [LMUSRID]
GO


ALTER TABLE [dbo].EXPORT_OPERATIONTYPEMASTER DROP CONSTRAINT DF_EXPORT_OPERATIONTYPEMASTER_CUSRID
GO

alter table EXPORT_OPERATIONTYPEMASTER 
alter column CUSRID varchar(100)  null 

ALTER TABLE [dbo].EXPORT_OPERATIONTYPEMASTER ADD  CONSTRAINT DF_EXPORT_OPERATIONTYPEMASTER_CUSRID  DEFAULT (('')) FOR [CUSRID]
GO



