alter table EXPORTSHIPPINGBILLDETAIL 
Add GIDID INT NULL

update EXPORTSHIPPINGBILLDETAIL
set GIDID = null

update EXPORTSHIPPINGBILLDETAIL
set GIDID = SHIPPINGBILLDETAIL.GIDID
FROM   SHIPPINGBILLDETAIL (nolock) Inner Join 
	       SHIPPINGBILLMASTER (nolock) ON SHIPPINGBILLMASTER.SBMID = SHIPPINGBILLDETAIL.SBMID INNER Join 
		   EXPORTSHIPPINGBILLMASTER (nolock) ON SHIPPINGBILLDETAIL.ESBMID = EXPORTSHIPPINGBILLMASTER.ESBMID  inner join 
		   EXPORTSHIPPINGBILLDETAIL (nolock) ON EXPORTSHIPPINGBILLMASTER.ESBMID = EXPORTSHIPPINGBILLDETAIL.ESBMID inner join
		   GATEINDETAIL (nolock) ON SHIPPINGBILLDETAIL.GIDID = GATEINDETAIL.GIDID    
where EXPORTSHIPPINGBILLDETAIL.GIDID is null
and GATEINDETAIL.GIDATE <='2022-12-15'

-- select * From EXPORTSHIPPINGBILLDETAIL where GIDID is NULL