DROP TABLE EXPORT_SEALTYPEMASTER
CREATE TABLE DBO.EXPORT_SEALTYPEMASTER
(
SLTID  INT IDENTITY(0,1) primary key,
SLTDESC VARCHAR(25) DEFAULT ('')
)

INSERT INTO EXPORT_SEALTYPEMASTER(SLTDESC)
SELECT 'NIL'
INSERT INTO EXPORT_SEALTYPEMASTER(SLTDESC)
SELECT 'E-SEAL'
INSERT INTO EXPORT_SEALTYPEMASTER(SLTDESC)
SELECT 'BOTTLE SEAL'
INSERT INTO EXPORT_SEALTYPEMASTER(SLTDESC)
SELECT 'OTHERS'

SELECT * FROM EXPORT_SEALTYPEMASTER



alter table authorizationslipdetail
ADD  SLTID INT NOT NULL DEFAULT(0)

select * From authorizationslipdetail