ALTER TABLE [dbo].EXPORTTARIFFTYPEMASTER DROP CONSTRAINT DF_EXPORTTARIFFTYPEMASTER_LMUSRID
GO

alter table EXPORTTARIFFTYPEMASTER 
alter column LMUSRID varchar(100)  null 

ALTER TABLE [dbo].EXPORTTARIFFTYPEMASTER ADD  CONSTRAINT DF_EXPORTTARIFFTYPEMASTER_LMUSRID  DEFAULT (('')) FOR [LMUSRID]
GO


ALTER TABLE [dbo].EXPORTTARIFFTYPEMASTER DROP CONSTRAINT DF_EXPORTTARIFFTYPEMASTER_CUSRID
GO

alter table EXPORTTARIFFTYPEMASTER 
alter column CUSRID varchar(100)  null 

ALTER TABLE [dbo].EXPORTTARIFFTYPEMASTER ADD  CONSTRAINT DF_EXPORTTARIFFTYPEMASTER_CUSRID  DEFAULT (('')) FOR [CUSRID]
GO



