CREATE TABLE [dbo].[EXPORT_SLAB_CHARGE_TYPE_MASTER](
    [CTID] [int] PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[CHRGETYPE] [int] NOT NULL CONSTRAINT [DF_EXPORT_SLAB_CHARGE_TYPE_MASTER_CHRGETYPE]  DEFAULT ((0)),
	[CHRGETYPEDESC] [varchar](100) NULL CONSTRAINT [DF_EXPORT_SLAB_CHARGE_TYPE_MASTER_CHRGETYPEDESC]  DEFAULT (NULL))