ALTER TABLE [dbo].EXPORTTARIFFGROUPMASTER DROP CONSTRAINT DF_EXPORTTARIFFGROUPMASTER_LMUSRID
GO

alter table EXPORTTARIFFGROUPMASTER 
alter column LMUSRID varchar(100)  null 

ALTER TABLE [dbo].EXPORTTARIFFGROUPMASTER ADD  CONSTRAINT DF_EXPORTTARIFFGROUPMASTER_LMUSRID  DEFAULT (('')) FOR [LMUSRID]
GO


ALTER TABLE [dbo].EXPORTTARIFFGROUPMASTER DROP CONSTRAINT DF_EXPORTTARIFFGROUPMASTER_CUSRID
GO

alter table EXPORTTARIFFGROUPMASTER 
alter column CUSRID varchar(100)  null 

ALTER TABLE [dbo].EXPORTTARIFFGROUPMASTER ADD  CONSTRAINT DF_EXPORTTARIFFGROUPMASTER_CUSRID  DEFAULT (('')) FOR [CUSRID]
GO



