ALTER TABLE [dbo].EXPORTSLABTYPEMASTER DROP CONSTRAINT DF_EXPORTSLABTYPEMASTER_LMUSRID
GO

alter table EXPORTSLABTYPEMASTER 
alter column LMUSRID varchar(100)  null 

ALTER TABLE [dbo].EXPORTSLABTYPEMASTER ADD  CONSTRAINT DF_EXPORTSLABTYPEMASTER_LMUSRID  DEFAULT (('')) FOR [LMUSRID]
GO


ALTER TABLE [dbo].EXPORTSLABTYPEMASTER DROP CONSTRAINT DF_EXPORTSLABTYPEMASTER_CUSRID
GO

alter table EXPORTSLABTYPEMASTER 
alter column CUSRID varchar(100)  null 

ALTER TABLE [dbo].EXPORTSLABTYPEMASTER ADD  CONSTRAINT DF_EXPORTSLABTYPEMASTER_CUSRID  DEFAULT (('')) FOR [CUSRID]
GO



