USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[EXPORT_SEAL_TYPE_MASTER]    Script Date: 07/08/2021 16:48:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EXPORT_SEAL_TYPE_MASTER](
	[ESLID] [int] IDENTITY(1,1) NOT NULL,
	[ESLTID] [int] NOT NULL,
	[ESLTDESC] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ESLID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


