ALTER TABLE [dbo].[EXPORTSLABMASTER] DROP CONSTRAINT [DF_EXPORTSLABMASTER_LMUSRID]
GO

alter table [EXPORTSLABMASTER] 
alter column LMUSRID varchar(100)  null 

ALTER TABLE [dbo].[EXPORTSLABMASTER] ADD  CONSTRAINT [DF_EXPORTSLABMASTER_LMUSRID]  DEFAULT (('')) FOR [LMUSRID]
GO


ALTER TABLE [dbo].[EXPORTSLABMASTER] DROP CONSTRAINT DF_EXPORTSLABMASTER_CUSRID
GO

alter table [EXPORTSLABMASTER] 
alter column CUSRID varchar(100)  null 

ALTER TABLE [dbo].[EXPORTSLABMASTER] ADD  CONSTRAINT DF_EXPORTSLABMASTER_CUSRID  DEFAULT (('')) FOR [CUSRID]
GO



