USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[EXPORTSHIPPINGBILLDETAIL]    Script Date: 16/08/2021 14:33:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

drop table [EXPORTSHIPPINGBILLDETAIL]

CREATE TABLE [dbo].[EXPORTSHIPPINGBILLDETAIL](
	[ESBDID] [int] IDENTITY(1,1) NOT NULL,
	[ESBMID] [int] NOT NULL,
	[ESBD_SBILLNO] varchar(25) Not null,
	[ESBD_SBILLDATE] [smalldatetime] NULL,	
	[ESBOINVNO] [varchar](25) NULL,
	[ESBOINVDATE] [smalldatetime] NULL,
	[ESBOINVAMT] [numeric](18, 2) NULL,
	[ESBOINVFOBAMT] [numeric](18, 2) NULL,
	[ESBDDPNAME] [varchar](50) NULL,
	[PRDTDESC] [varchar](100) NULL,
	[ESBMNOP] [numeric](18, 2) NULL,
	[ESBMQTY] [numeric](18, 4) NULL,
	[CUSRID] [varchar](25) NULL,
	[LMUSRID] [varchar](25) NULL,
	[PRCSDATE] [datetime] NULL,
	[DISPSTATUS] [smallint] NOT NULL
	
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[EXPORTSHIPPINGBILLDETAIL]  WITH NOCHECK ADD  CONSTRAINT [FK_EXPORTSHIPPINGBILLDETAIL_EXPORTSHIPPINGBILLMASTER] FOREIGN KEY([ESBMID])
REFERENCES [dbo].[EXPORTSHIPPINGBILLMASTER] ([ESBMID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[EXPORTSHIPPINGBILLDETAIL] CHECK CONSTRAINT [FK_EXPORTSHIPPINGBILLDETAIL_EXPORTSHIPPINGBILLMASTER]
GO


