USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[EXPORT_CARGO_BLOCK_DETAILS]    Script Date: 09-02-2023 11:03:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
-- DROP TABLE [EXPORT_CARGO_BLOCK_DETAILS]
GO

CREATE TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS](
	[GBDID] [int] IDENTITY(1,1) NOT NULL,
	[COMPYID] [int] NOT NULL,
	[SDPTID] [int] NOT NULL,
	[GBDATE] [smalldatetime] NOT NULL,
	[GBTIME] [datetime] NOT NULL,
	[GBNO] [int] NOT NULL,
	[GBDNO] [varchar](15) NOT NULL,
	[SBMID] [int] NULL,
	[GBTYPE] [smallint] NULL,
	[NARTN] [varchar](250) NULL,
	[CUSRID] [varchar](25) NULL,
	[LMUSRID] [varchar](100) NULL,
	[DISPSTATUS] [smallint] NULL,
	[PRCSDATE] [datetime] NULL,
	[GBUDATE] [smalldatetime] NULL,
	[GBUTIME] [smalldatetime] NULL,
	[UNARTN] [varchar](250) NULL,
	[GBSTYPE] [smallint] NULL,
 CONSTRAINT [PK_EXPORT_CARGO_BLOCK_DETAILS] PRIMARY KEY CLUSTERED 
(
	[GBDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_COMPYID]  DEFAULT ((0)) FOR [COMPYID]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_SDPTID]  DEFAULT ((0)) FOR [SDPTID]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_GBDATE]  DEFAULT (NULL) FOR [GBDATE]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_GBTIME]  DEFAULT (NULL) FOR [GBTIME]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_GBNO]  DEFAULT ((0)) FOR [GBNO]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_GBDNO]  DEFAULT (NULL) FOR [GBDNO]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_SBMID]  DEFAULT ((0)) FOR [SBMID]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_GBTYPE]  DEFAULT ((0)) FOR [GBTYPE]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_NARTN]  DEFAULT ('') FOR [NARTN]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_CUSRID]  DEFAULT ('') FOR [CUSRID]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_LMUSRID]  DEFAULT ('') FOR [LMUSRID]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_DISPSTATUS]  DEFAULT ((0)) FOR [DISPSTATUS]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_PRCSDATE]  DEFAULT (NULL) FOR [PRCSDATE]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_GBUDATE]  DEFAULT (NULL) FOR [GBUDATE]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_GBUTIME]  DEFAULT (NULL) FOR [GBUTIME]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_UNARTN]  DEFAULT ('') FOR [UNARTN]
GO

ALTER TABLE [dbo].[EXPORT_CARGO_BLOCK_DETAILS] ADD  CONSTRAINT [DF_EXPORT_CARGO_BLOCK_DETAILS_GBSTYPE]  DEFAULT ((0)) FOR [GBSTYPE]
GO


