--SELECT * FROM EXPORTSLABTYPEMASTER

ALTER TABLE EXPORTSLABTYPEMASTER
ADD SLABSTYPE SMALLINT DEFAULT (0)


--SELECT * FROM HSNCODEMASTER

ALTER TABLE [dbo].EXPORTSLABTYPEMASTER DROP CONSTRAINT DF_EXPORTSLABTYPEMASTER_HSNID
GO

alter table EXPORTSLABTYPEMASTER 
alter column HSNID INT  null 

ALTER TABLE [dbo].EXPORTSLABTYPEMASTER ADD  CONSTRAINT DF_EXPORTSLABTYPEMASTER_HSNID  DEFAULT ((0)) FOR HSNID
GO