select *from EXPORT_INVOICE_REGISTER

if NOT EXISTS (SELECT *from EXPORT_INVOICE_REGISTER where REGSTRID=54)


INSERT INTO EXPORT_INVOICE_REGISTER(REGSTRID,REGSTRDESC)
VALUES(54,'TAX INVOICE')

if NOT EXISTS (SELECT *from EXPORT_INVOICE_REGISTER where REGSTRID=55)

INSERT INTO EXPORT_INVOICE_REGISTER(REGSTRID,REGSTRDESC)
VALUES(55,'BILL OF SUPPLY')