USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[EXPORT_SLAB_WAGES_TYPE_MASTER]    Script Date: 07/08/2021 19:35:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EXPORT_SLAB_WAGES_TYPE_MASTER](
    [WTID] [int] PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[WTYPE] [int] NOT NULL CONSTRAINT [DF_EXPORT_SLAB_WAGES_TYPE_MASTER_WTYPE]  DEFAULT ((0)),
	[WTYPEDESC] [varchar](100) NULL CONSTRAINT [DF_EXPORT_SLAB_WAGES_TYPE_MASTER_WTYPEDESC]  DEFAULT (NULL)
 )

GO

SET ANSI_PADDING OFF
GO


