USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[EXPORT_SLAB_YARD_TYPE_MASTER]    Script Date: 07/08/2021 19:27:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EXPORT_SLAB_YARD_TYPE_MASTER](
	[YTID] [int] IDENTITY(1,1) NOT NULL,
	[YRDTYPE] [int] NOT NULL,
	[YRDDESC] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[YTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


