ALTER TABLE [dbo].EXPORTTARIFFMASTER DROP CONSTRAINT DF_EXPORTTARIFFMASTER_LMUSRID
GO

alter table EXPORTTARIFFMASTER 
alter column LMUSRID varchar(100)  null 

ALTER TABLE [dbo].EXPORTTARIFFMASTER ADD  CONSTRAINT DF_EXPORTTARIFFMASTER_LMUSRID  DEFAULT (('')) FOR [LMUSRID]
GO


ALTER TABLE [dbo].EXPORTTARIFFMASTER DROP CONSTRAINT DF_EXPORTTARIFFMASTER_CUSRID
GO

alter table EXPORTTARIFFMASTER 
alter column CUSRID varchar(100)  null 

ALTER TABLE [dbo].EXPORTTARIFFMASTER ADD  CONSTRAINT DF_EXPORTTARIFFMASTER_CUSRID  DEFAULT (('')) FOR [CUSRID]
GO



