USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[GATEINLORRYHIREDETAIL]    Script Date: 01-09-2021 17:32:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
-- drop table [GATEINLORRYHIREDETAIL]
CREATE TABLE [dbo].[GATEINLORRYHIREDETAIL](
	[GILDID] [int] IDENTITY(1,1) NOT NULL,
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_COMPYID]  DEFAULT ((0)),
	[SDPTID] [int] NOT NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_SDPTID]  DEFAULT ((0)),
	[GILDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_GILDATE]  DEFAULT (NULL),
	[GILTIME] [datetime] NOT NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_GILTIME]  DEFAULT (NULL),
	[GILNO] [int] NOT NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_GILNO]  DEFAULT ((0)),
	[GILDNO] [varchar](15) NOT NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_GILDNO]  DEFAULT (NULL),
	[GIDID] [int] NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_GIDID]  DEFAULT ((0)),
	[GILBILLNO] [varchar](20) NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_GILBILLNO]  DEFAULT (NULL),
	[GILBILLDATE] [smalldatetime] NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_GILBILLDATE]  DEFAULT (NULL),
	[GILNARTN] [varchar](100) NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_GILNARTN]  DEFAULT (NULL),
	[CUSRID] [varchar](50) NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_CUSRID]  DEFAULT ((null)),
	[LMUSRID] [varchar](50)  NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_LMUSRID]  DEFAULT ((null)),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_GATEINLORRYHIREDETAIL_PRCSDATE]  DEFAULT (NULL),
 CONSTRAINT [PK_GATEINLORRYHIREDETAIL] PRIMARY KEY CLUSTERED 
(
	[GILDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


