USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[GATEIN_BLOCK_DETAILS]    Script Date: 11-09-2021 14:24:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
-- drop table [GATEIN_BLOCK_DETAILS]
CREATE TABLE [dbo].[GATEIN_BLOCK_DETAILS](
	[GBDID] [int] IDENTITY(1,1) NOT NULL,
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_COMPYID]  DEFAULT ((0)),
	[SDPTID] [int] NOT NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_SDPTID]  DEFAULT ((0)),
	[GBDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_GBDATE]  DEFAULT (NULL),
	[GBTIME] [datetime] NOT NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_GBTIME]  DEFAULT (NULL),
	[GBNO] [int] NOT NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_GBNO]  DEFAULT ((0)),
	[GBDNO] [varchar](15) NOT NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_GBDNO]  DEFAULT (NULL),
	[GIDID] [int] NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_GIDID]  DEFAULT ((0)),
	[GBTYPE] [smallint] NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_GBTYPE]  DEFAULT ((0)),
	[NARTN] [varchar](250) NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_NARTN]  DEFAULT (''),
	[CUSRID] [varchar](25) NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_CUSRID]  DEFAULT (('')),
	[LMUSRID] [varchar](100) NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_LMUSRID]  DEFAULT (('')),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_PRCSDATE]  DEFAULT (NULL),
	[GBUDATE] [smalldatetime] NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_GBUDATE]  DEFAULT (NULL),
	[GBUTIME] [smalldatetime] NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_GBUTIME]  DEFAULT (NULL),
	[UNARTN] [varchar](250) NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_UNARTN]  DEFAULT (''),
	[GBSTYPE] [smallint] NULL CONSTRAINT [DF_GATEIN_BLOCK_DETAILS_GBSTYPE]  DEFAULT ((0)),
 CONSTRAINT [PK_GATEIN_BLOCK_DETAILS] PRIMARY KEY CLUSTERED 
(
	[GBDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


--select * from [GATEIN_BLOCK_DETAILS]

