alter table GATEINDETAIL
ADD [GPCSTYPE] [smallint] NOT NULL CONSTRAINT [DF_GATEINDETAIL_GPCSTYPE]  DEFAULT ((0))

alter table GATEINDETAIL
ADD [GPCSAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_GATEINDETAIL_GPCSAMT]  DEFAULT ((0))

alter table GATEINDETAIL
ADD 	[GPLBTYPE] [smallint] NOT NULL CONSTRAINT [DF_GATEINDETAIL_GPCSTYPE1]  DEFAULT ((0))


alter table GATEINDETAIL
ADD 	[GPLBAMT] [numeric](18, 2) NOT NULL CONSTRAINT [DF_GATEINDETAIL_GPCSAMT1]  DEFAULT ((0))
