
ALTER TABLE [dbo].[GATEOUTDETAIL] DROP CONSTRAINT [DF_GATEOUTDETAIL_LMUSRID]
GO

alter table GATEOUTDETAIL 
alter column LMUSRID varchar(25)  null 

ALTER TABLE [dbo].[GATEOUTDETAIL] ADD  CONSTRAINT [DF_GATEOUTDETAIL_LMUSRID]  DEFAULT (('')) FOR [LMUSRID]
GO