 SELECT DISTINCT   
        dbo.OPENSHEETMASTER.OSBILLREFID, dbo.OPENSHEETMASTER.OSBILLREFNAME, dbo.BILLENTRYMASTER.BILLEMDNO, dbo.BILLENTRYMASTER.BILLEMID,dbo.BILLENTRYDETAIL.BILLEDID,  
        dbo.BILLENTRYDETAIL.GIDID, dbo.GATEINDETAIL.STMRID,GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.CONTNRNO,   
        dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.CONTNRSID, dbo.GATEINDETAIL.GIDATE,   
        dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN.XGIDATE AS STRGDATE,   
        --dbo.GATEOUTDETAIL.GODATE,   
        CASE WHEN DATEPART(HOUR,GOTIME)<6 THEN DATEADD(D,-1,GODATE) ELSE GODATE END AS GODATE,  
        dbo.GATEOUTDETAIL.GOTIME,   
        dbo.OPENSHEETMASTER.DODATE, 0 AS NOD, dbo.GATEINDETAIL.GPWGHT, dbo.GATEINDETAIL.PRDTGID, 0 AS TRANDID, 0 AS TRANDOTYPE, 0 AS TARIFFMID,   
        dbo.BILLENTRYMASTER.DPAIDNO, dbo.BILLENTRYMASTER.DPAIDAMT, dbo.GATEINDETAIL.GPEAMT, dbo.GATEINDETAIL.GPCSAMT,dbo.GATEINDETAIL.GPLBAMT, dbo.GATEINDETAIL.GPAAMT,  
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,0, isnull(STATETYPE,0),  
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0  
 FROM         dbo.OPENSHEETMASTER (NOLOCK) INNER JOIN  
        dbo.BILLENTRYMASTER  (NOLOCK) INNER JOIN  
        dbo.BILLENTRYDETAIL  (NOLOCK) ON dbo.BILLENTRYMASTER.BILLEMID = dbo.BILLENTRYDETAIL.BILLEMID INNER JOIN  
        dbo.GATEINDETAIL  (NOLOCK) ON dbo.BILLENTRYDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN  
        dbo.CONTAINERSIZEMASTER  (NOLOCK) ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN  
        dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN  (NOLOCK) ON dbo.BILLENTRYMASTER.BILLEMID = dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN.BILLEMID INNER JOIN  
        dbo.OPENSHEETDETAIL  (NOLOCK) ON dbo.GATEINDETAIL.GIDID = dbo.OPENSHEETDETAIL.GIDID ON   
        dbo.OPENSHEETMASTER.OSMID = dbo.OPENSHEETDETAIL.OSMID INNER  JOIN  
        dbo.GATEOUTDETAIL  (NOLOCK) ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID LEFT OUTER JOIN  
        dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01  (NOLOCK) ON   
        dbo.BILLENTRYDETAIL.BILLEDID = dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.BILLEDID INNER JOIN  
                         dbo.CATEGORYMASTER  (NOLOCK) ON dbo.OPENSHEETMASTER.OSBILLREFID = dbo.CATEGORYMASTER.CATEID LEFT OUTER JOIN  
       dbo.CATEGORY_ADDRESS_DETAIL  (NOLOCK) ON dbo.OPENSHEETMASTER.OSBBCHACATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID  LEFT OUTER JOIN  
                         dbo.STATEMASTER  (NOLOCK) ON dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID inner JOIN   
       AUTHORIZATIONSLIPDETAIL B (NOLOCK)  on dbo.GATEINDETAIL.GIDID =  b.GIDID inner JOIN AUTHORIZATIONSLIPMASTER C ON B.ASLMID = C.ASLMID and c.DISPSTATUS=0  
 WHERE     (ISNULL(dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDID, 0) = 0) AND  
  (dbo.BILLENTRYMASTER.SDPTID = 1) 
 -- AND     (dbo.GATEINDETAIL.IGMNO = @LIGMNO) AND (dbo.GATEINDETAIL.GPLNO = @LLNO)  