select * from GPModeMaster

set IDENTITY_INSERT GPMODEMASTER on 
if not exists ( select '*' from GPMODEMASTER where GPMODEID = 6)
BEGIN
	INSERT INTO GPMODEMASTER( GPMODEID, GPMODEDESC, GPMODECODE, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE)
	SELECT 6, 'ENBLOCK', 'ENBLOCK', 1,1,0,getdate()
END

set IDENTITY_INSERT GPMODEMASTER off 
select * from GPModeMaster