--SELECT        TRANMID, STRG_HSNCODE, HANDL_HSNCODE, STRG_CGST_EXPRN, STRG_SGST_EXPRN, STRG_IGST_EXPRN, HANDL_CGST_EXPRN, HANDL_SGST_EXPRN, 
--                         HANDL_IGST_EXPRN, SUM(STRG_TAXABLE_AMT) AS STRG_TAXABLE_AMT, SUM(HANDL_TAXABLE_AMT) AS HANDL_TAXABLE_AMT, SUM(STRG_CGST_AMT) 
--                         AS STRG_CGST_AMT, SUM(STRG_SGST_AMT) AS STRG_SGST_AMT, SUM(STRG_IGST_AMT) AS STRG_IGST_AMT, SUM(HANDL_CGST_AMT) AS HANDL_CGST_AMT, 
--                         SUM(HANDL_SGST_AMT) AS HANDL_SGST_AMT, SUM(HANDL_IGST_AMT) AS HANDL_IGST_AMT, SUM(STRG_CGST_AMT + HANDL_CGST_AMT) AS CGST_AMT, 
--                         SUM(STRG_SGST_AMT + HANDL_SGST_AMT) AS SGST_AMT, SUM(STRG_IGST_AMT + HANDL_IGST_AMT) AS IGST_AMT
--FROM            dbo.TRANSACTIONMASTER
--WHERE REGSTRID = 15
--GROUP BY TRANMID, STRG_HSNCODE, HANDL_HSNCODE, STRG_CGST_EXPRN, STRG_SGST_EXPRN, STRG_IGST_EXPRN, HANDL_CGST_EXPRN, HANDL_SGST_EXPRN, 
--                         HANDL_IGST_EXPRN
--HAVING        (STRG_HSNCODE IS NOT NULL OR HANDL_HSNCODE IS NOT NULL)

SELECT * FROM [VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01] WHERE TRANMID NOT IN (SELECT TRANMID FROM [Z_IMPORT_MANUAL_EINVOICE_DETAILS])
SELECT * FROM [Z_IMPORT_MANUAL_EINVOICE_DETAILS]
SELECT A.TRANMID, ACHEADDESC, STRG_HSNCODE,  HANDL_HSNCODE, D.HSNCODE, TRAND_HANDL_CGST_AMT, TRAND_HANDL_IGST_AMT, 
		XSTRG_HSNCODE = CASE WHEN TRAND_STRG_CGST_AMT > 0 OR TRAND_STRG_IGST_AMT > 0 THEN D.HSNCODE ELSE '' END,
		XHANDL_HSNCODE = CASE WHEN TRAND_HANDL_CGST_AMT > 0 OR TRAND_HANDL_IGST_AMT > 0 THEN D.HSNCODE ELSE '' END,
		TRAND_STRG_CGST_EXPRN as XTRAND_STRG_CGST_EXPRN, TRAND_STRG_SGST_EXPRN as XTRAND_STRG_SGST_EXPRN, 
		TRAND_STRG_IGST_EXPRN as XTRAND_STRG_IGST_EXPRN, 
		TRAND_HANDL_CGST_EXPRN as XTRAND_HANDL_CGST_EXPRN, TRAND_HANDL_SGST_EXPRN as XTRAND_HANDL_SGST_EXPRN, 
		TRAND_HANDL_IGST_EXPRN as XTRAND_HANDL_IGST_EXPRN, 
		XHANDL_HSNCODE = CASE WHEN TRAND_HANDL_CGST_AMT > 0 OR TRAND_HANDL_IGST_AMT > 0 THEN D.HSNCODE ELSE '' END,
		XSTRG_TAXABLE_AMT = CASE WHEN TRAND_STRG_CGST_AMT > 0 OR TRAND_STRG_IGST_AMT > 0 THEN TRANDGAMT ELSE 0 END,
		XSTRG_CGST_AMT = CASE WHEN TRAND_STRG_CGST_AMT > 0  THEN TRAND_STRG_CGST_AMT ELSE 0 END,
		XSTRG_SGST_AMT = CASE WHEN TRAND_STRG_SGST_AMT > 0  THEN TRAND_STRG_SGST_AMT ELSE 0 END,
		XSTRG_IGST_AMT = CASE WHEN TRAND_STRG_IGST_AMT > 0  THEN TRAND_STRG_IGST_AMT ELSE 0 END,

		XHANDL_TAXABLE_AMT = CASE WHEN TRAND_HANDL_CGST_AMT > 0 OR TRAND_HANDL_IGST_AMT > 0 THEN TRANDGAMT ELSE 0 END,
		XHANDL_CGST_AMT = CASE WHEN TRAND_HANDL_CGST_AMT > 0  THEN TRAND_HANDL_CGST_AMT ELSE 0 END,
		XHANDL_SGST_AMT = CASE WHEN TRAND_HANDL_SGST_AMT > 0  THEN TRAND_HANDL_SGST_AMT ELSE 0 END,
		XHANDL_IGST_AMT = CASE WHEN TRAND_HANDL_IGST_AMT > 0  THEN TRAND_HANDL_IGST_AMT ELSE 0 END
FROM TRANSACTIONDETAIL A(NOLOCK) 
		JOIN TRANSACTIONMASTER B(NOLOCK) ON A.TRANMID = B.TRANMID 
		JOIN ACCOUNTHEADMASTER C(NOLOCK) ON A.ACHEADID = C.ACHEADID
		JOIN HSNCODEMASTER D(NOLOCK) ON C.HSNID =D.HSNID
WHERE REGSTRID = 15



SELECT A.TRANMID, HANDL_HSNCODE,  D.HSNCODE, TRAND_HANDL_CGST_AMT, TRAND_HANDL_IGST_AMT, 
		XSTRG_HSNCODE = CASE WHEN TRAND_STRG_CGST_AMT > 0 OR TRAND_STRG_IGST_AMT > 0 THEN D.HSNCODE ELSE '' END,
		XHANDL_HSNCODE = CASE WHEN TRAND_HANDL_CGST_AMT > 0 OR TRAND_HANDL_IGST_AMT > 0 THEN D.HSNCODE ELSE '' END,
		TRAND_STRG_CGST_EXPRN as XTRAND_STRG_CGST_EXPRN, TRAND_STRG_SGST_EXPRN as XTRAND_STRG_SGST_EXPRN, 
		TRAND_STRG_IGST_EXPRN as XTRAND_STRG_IGST_EXPRN, 
		TRAND_HANDL_CGST_EXPRN as XTRAND_HANDL_CGST_EXPRN, TRAND_HANDL_SGST_EXPRN as XTRAND_HANDL_SGST_EXPRN, 
		TRAND_HANDL_IGST_EXPRN as XTRAND_HANDL_IGST_EXPRN, 
		XHANDL_HSNCODE = CASE WHEN TRAND_HANDL_CGST_AMT > 0 OR TRAND_HANDL_IGST_AMT > 0 THEN D.HSNCODE ELSE '' END,
		XSTRG_TAXABLE_AMT = CASE WHEN TRAND_STRG_CGST_AMT > 0 OR TRAND_STRG_IGST_AMT > 0 THEN TRANDGAMT ELSE 0 END,
		XSTRG_CGST_AMT = CASE WHEN TRAND_STRG_CGST_AMT > 0  THEN TRAND_STRG_CGST_AMT ELSE 0 END,
		XSTRG_SGST_AMT = CASE WHEN TRAND_STRG_SGST_AMT > 0  THEN TRAND_STRG_SGST_AMT ELSE 0 END,
		XSTRG_IGST_AMT = CASE WHEN TRAND_STRG_IGST_AMT > 0  THEN TRAND_STRG_IGST_AMT ELSE 0 END,

		XHANDL_TAXABLE_AMT = CASE WHEN TRAND_HANDL_CGST_AMT > 0 OR TRAND_HANDL_IGST_AMT > 0 THEN TRANDGAMT ELSE 0 END,
		XHANDL_CGST_AMT = CASE WHEN TRAND_HANDL_CGST_AMT > 0  THEN TRAND_HANDL_CGST_AMT ELSE 0 END,
		XHANDL_SGST_AMT = CASE WHEN TRAND_HANDL_SGST_AMT > 0  THEN TRAND_HANDL_SGST_AMT ELSE 0 END,
		XHANDL_IGST_AMT = CASE WHEN TRAND_HANDL_IGST_AMT > 0  THEN TRAND_HANDL_IGST_AMT ELSE 0 END