
ALTER TABLE [dbo].[IMPORT_SEAL_MASTER] DROP CONSTRAINT [DF_IMPORT_SEAL_MASTER_LMUSRID]
GO

alter table IMPORT_SEAL_MASTER 
alter column LMUSRID varchar(25)  null 

ALTER TABLE [dbo].[IMPORT_SEAL_MASTER] ADD  CONSTRAINT [DF_IMPORT_SEAL_MASTER_LMUSRID]  DEFAULT (('')) FOR [LMUSRID]
GO