USE [SCFS_ERP]
GO
CREATE NONCLUSTERED INDEX [pr_Import_Container_Stock_Assgn_NC_01]
ON [dbo].[GATEINDETAIL] ([SDPTID],[DISPSTATUS],[GIDATE],[CONTNRSID])
INCLUDE ([IMPRTNAME],[STMRID],[STMRNAME],[CONTNRTID],[CONTNRNO],[PRDTDESC],[IGMNO],[GPLNO])
GO

USE [SCFS_ERP]
GO
CREATE NONCLUSTERED INDEX [pr_Import_Container_Stock_Assgn_NC_02]
ON [dbo].[GATEINDETAIL] ([SDPTID],[CONTNRTID],[DISPSTATUS],[GIDATE],[CONTNRSID])
INCLUDE ([IMPRTNAME],[STMRID],[STMRNAME],[CONTNRNO],[PRDTDESC],[IGMNO],[GPLNO])
GO

