INSERT INTO CREDITNOTE_TYPEMASTER(CNTDESC)VALUES('Discount on Handling Charges')
INSERT INTO CREDITNOTE_TYPEMASTER(CNTDESC)VALUES('Discount on Storage Charges')
INSERT INTO CREDITNOTE_TYPEMASTER(CNTDESC)VALUES('Renomination Charges Reimbursed')
INSERT INTO CREDITNOTE_TYPEMASTER(CNTDESC)VALUES('Cancellation of Invoice')

select *from CREDITNOTE_TYPEMASTER