Declare @Compyid int,@Cusrid varchar(25),@GIDATE datetime,@GITIME datetime,
  @GICCTLDATE datetime,@GICCTLTIME datetime,@GINO INT,@GIDNO VARCHAR(15),
  @STMRID INT,@STMRNAME VARCHAR(100),@CONTNRTID INT,@CONTNRSID INT,@CONTNRNO INT,
  @ASLMID INT,@ASLDID INT,@VTNO INT,@VTDNO VARCHAR(15),@GONO INT,@GODNO VARCHAR(15)


  insert into GATEINDETAIL( [COMPYID], [SDPTID], [GIDATE], [GITIME], [GICCTLDATE], [GICCTLTIME], [GINO], [GIDNO], [GIVHLTYPE],
   [TRNSPRTID], [TRNSPRTNAME], [VHLNO], [DRVNAME],  [IMPRTID], [IMPRTNAME], [STMRID], [STMRNAME], [CONTNRTID], [CONTNRID], 
   [CONTNRSID], [CONTNRNO], [LPSEALNO], [CSEALNO], [YRDID], [VSLID], [VSLNAME], [VOYNO], [PRDTGID], [PRDTDESC], [UNITID], [GPWGHT], 
   [IGMNO], [GPLNO], [GPWTYPE], [GPSTYPE], [GPETYPE], [BOEDID], [INVDID], [RGIDID], [GIREMKRS], [SLOTID], [CUSRID], [LMUSRID], [DISPSTATUS], [PRCSDATE],
    [GPEAMT], [CHAID], [CHANAME], [AVHLNO], [GPNOP], [PRDTTID], [GIISOCODE], [GIDMGDESC], [NGIDID], [GPNWGHT], [GPGWGHT], [GPCBM], [GPLENGTH], [GPWIDTH],
	 [GPHEIGHT], [GPBLNO], [GPAAMT], [CLNTID], [CLNTNAME], [SHPRNAME], [GPPLCNAME], [GPTWGHT], [CONTNRFID], [CONDTNID], [GRADEID], [CNTNRSID], [GPPTYPE], 
	 [GFCLTYPE], [GSEALTYPE], [GSECTYPE], [GSEALREMKRS], [GSECREMKRS], [GPNRNO], [ESBNO], [EVSLRNO], [EMONO], [EEGMNO], [ESBDATE], [GPSCNTYPE], [ROWID], 
	 [GDWNID], [STAGID], [IGMDATE], [BLNO], [ESBMID])

	 select @Compyid,1,@GIDATE,@GITIME,@GICCTLDATE,@GICCTLTIME,@GINO,@GIDNO,0,
	         0,'-','-','-',0,'-',@STMRID,@STMRNAME,@CONTNRTID,

--select max(gino)+1 as gino from GATEINDETAIL