select *from SOFT_DEPARTMENTMASTER

INSERT INTO SOFT_DEPARTMENTMASTER (SDPTNAME,OPTNSTR,DISPSTATUS,PRCSDATE)
VALUES('BOND','BOND',0,GETDATE()) 

INSERT INTO SOFT_DEPARTMENTMASTER (SDPTNAME,OPTNSTR,DISPSTATUS,PRCSDATE)
VALUES('MNR','MNR',0,GETDATE()) 

