
SELECT * FROM TRANSACTIONMASTER
WHERE ACKDT IS NOT NULL

UPDATE TRANSACTIONMASTER
SET ACKDT = NULL
WHERE ISNULL(ACKNO,'')=''

SELECT * FROM TRANSACTIONMASTER
WHERE IRNNO IS NOT NULL

UPDATE TRANSACTIONMASTER
SET IRNNO = NULL
WHERE ISNULL(IRNNO,'')=''

SELECT * FROM TRANSACTIONMASTER
WHERE ACKNO IS NOT NULL

UPDATE TRANSACTIONMASTER
SET ACKNO = NULL
WHERE ISNULL(ACKNO,'')=''



