delete FROM EXPORT_INVOICE_REGISTER WHERE REGSTRID = 34
SELECT * FROM EXPORT_INVOICE_REGISTER WHERE REGSTRID IN ( 34, 35,36)
IF NOT EXISTS (SELECT '*' FROM EXPORT_INVOICE_REGISTER WHERE REGSTRID = 34)
BEGIN
	insert into EXPORT_INVOICE_REGISTER
	select 34, 'CUSTOMER'

	insert into EXPORT_INVOICE_REGISTER
	select 35, 'NOTIONAL'

	insert into EXPORT_INVOICE_REGISTER
	select 36, 'ZERO BILL'
END
SELECT * FROM EXPORT_INVOICE_REGISTER WHERE REGSTRID IN ( 34, 35,36)

IF NOT EXISTS (SELECT '*' FROM EXPORT_INVOICE_REGISTER WHERE REGSTRID = 37)
BEGIN
	insert into EXPORT_INVOICE_REGISTER
	select 37, 'BILL OF SUPPLY'
end