USE [SCFS_ERP]
GO

ALTER TABLE [dbo].AUTHORIZATIONSLIPMASTER DROP CONSTRAINT DF_AUTHORIZATIONSLIPMASTER_LMUSRID
GO

alter table AUTHORIZATIONSLIPMASTER 
alter column LMUSRID varchar(100)  null 

ALTER TABLE [dbo].AUTHORIZATIONSLIPMASTER ADD  CONSTRAINT DF_AUTHORIZATIONSLIPMASTER_LMUSRID  DEFAULT (('')) FOR [LMUSRID]
GO

ALTER TABLE [dbo].VEHICLETICKETDETAIL DROP CONSTRAINT DF_VEHICLETICKETDETAIL_LMUSRID
GO

alter table VEHICLETICKETDETAIL 
alter column LMUSRID varchar(100)  null 

ALTER TABLE [dbo].VEHICLETICKETDETAIL ADD  CONSTRAINT DF_VEHICLETICKETDETAIL_LMUSRID  DEFAULT (('')) FOR [LMUSRID]
GO