USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[MANUALOPENSHEETMASTER]    Script Date: 13-09-2021 12:35:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MANUALOPENSHEETMASTER](
	[OSMID] [int] IDENTITY(1,1) NOT NULL,
	[SDPTID] [int] NOT NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_SDPTID]  DEFAULT ((0)),
	[COMPYID] [int] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_COMPYID]  DEFAULT ((0)),
	[OSMDATE] [smalldatetime] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_BILLEMDATE]  DEFAULT (NULL),
	[OSMTIME] [datetime] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_BILLEMTIME]  DEFAULT (NULL),
	[OSMNO] [int] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_BILLEMNO]  DEFAULT ((0)),
	[OSMDNO] [varchar](15) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_BILLEMDNO]  DEFAULT (NULL),
	[CHAID] [int] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_CHAID]  DEFAULT ((0)),
	[OSMNAME] [varchar](100) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_BILLEMNAME]  DEFAULT (NULL),
	[OSMCNAME] [varchar](100) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMCNAME]  DEFAULT (NULL),
	[OSMIGMNO] [varchar](10) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMIGMNO]  DEFAULT (NULL),
	[OSMVSLNAME] [varchar](50) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMVSLNAME]  DEFAULT (NULL),
	[BOENO] [varchar](20) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_BLNO]  DEFAULT (NULL),
	[BOEDATE] [smalldatetime] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMDATE1]  DEFAULT (NULL),
	[OSMTYPE] [smallint] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_BILLEDMTYPE]  DEFAULT ((0)),
	[DOTYPE] [smallint] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMTYPE1]  DEFAULT ((0)),
	[DODATE] [smalldatetime] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMDATE1_1]  DEFAULT (NULL),
	[CUSRID] [varchar](25) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_CUSRID]  DEFAULT (''),
	[LMUSRID] [varchar](25) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_LMUSRID]  DEFAULT (''),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_PRCSDATE]  DEFAULT (NULL),
	[OSMLNO] [varchar](15) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMLNO]  DEFAULT (NULL),
	[DONO] [varchar](15) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_DONO]  DEFAULT (NULL),
	[DOIDATE] [smalldatetime] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_DOIDATE]  DEFAULT (NULL),
	[SCTYPE] [smallint] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_DOTYPE1]  DEFAULT ((0)),
	[SCDESC] [varchar](100) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_SCDESC]  DEFAULT (NULL),
	[SCDATE] [smalldatetime] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMDATE1_2]  DEFAULT (NULL),
	[SCTIME] [datetime] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMTIME1]  DEFAULT (NULL),
	[SCREMRKS] [varchar](100) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_SCREMRKS]  DEFAULT (NULL),
	[OSMAAMT] [numeric](18, 0) NULL,
	[OSMBLNO] [varchar](20) NULL,
	[OSMNOP] [numeric](18, 0) NULL,
	[OSMWGHT] [numeric](18, 0) NULL,
	[OSMUNITID] [int] NULL,
	[OSMLNAME] [varchar](100) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMNAME1]  DEFAULT (NULL),
	[OSMTNOC] [int] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMTNOC]  DEFAULT ((0)),
	[OSMFNOC] [int] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMFNOC]  DEFAULT ((0)),
	[OSMLCATEID] [int] NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMLCATEID]  DEFAULT ((0)),
	[OSMLCATENAME] [varchar](100) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMLCATENAME]  DEFAULT (NULL),
	[OSBILLEDTO] [smallint] NOT NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSBILLEDTO]  DEFAULT ((0)),
	[OSBILLREFID] [int] NOT NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSBILLREFID]  DEFAULT ((0)),
	[OSBILLREFNAME] [varchar](100) NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSBILLREFNAME]  DEFAULT (NULL),
	[OSCATEAID] [int] NOT NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSCATEAID]  DEFAULT ((0)),
	[OSMLDTYPE] [smallint] NULL,
	[OSMDUTYAMT] [numeric](18, 0) NOT NULL CONSTRAINT [DF_MANUALOPENSHEETMASTER_OSMDUTYAMT]  DEFAULT ((0)),
	[OSMBLDATE] [smalldatetime] NULL,
	[OSMIGMDATE] [smalldatetime] NULL,
	[OSBCHACATEAID] [int] NULL DEFAULT ((0)),
	[OSBCHACATEAGSTNO] [varchar](50) NULL DEFAULT (''),
	[OSBCHAADDR1] [varchar](100) NULL DEFAULT (''),
	[OSBCHAADDR2] [varchar](100) NULL DEFAULT (''),
	[OSBCHAADDR3] [varchar](100) NULL DEFAULT (''),
	[OSBCHAADDR4] [varchar](100) NULL DEFAULT (''),
	[OSBCHASTATEID] [int] NULL DEFAULT ((0)),
	[OSBBCHACATEAID] [int] NULL DEFAULT ((0)),
	[OSBBCHACATEAGSTNO] [varchar](50) NULL DEFAULT (''),
	[OSBBCHAADDR1] [varchar](100) NULL DEFAULT (''),
	[OSBBCHAADDR2] [varchar](100) NULL DEFAULT (''),
	[OSBBCHAADDR3] [varchar](100) NULL DEFAULT (''),
	[OSBBCHAADDR4] [varchar](100) NULL DEFAULT (''),
	[OSBBCHASTATEID] [int] NULL DEFAULT ((0)),
 CONSTRAINT [PK_MANUALOPENSHEETMASTER] PRIMARY KEY CLUSTERED 
(
	[OSMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


