USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[MANUALOPENSHEETDETAIL]    Script Date: 13-09-2021 12:35:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MANUALOPENSHEETDETAIL](
	[OSDID] [int] IDENTITY(1,1) NOT NULL,
	[OSMID] [int] NOT NULL CONSTRAINT [DF_MANUALOPENSHEETDETAIL_OSMID]  DEFAULT ((0)),
	[GIDID] [int] NOT NULL CONSTRAINT [DF_MANUALOPENSHEETDETAIL_GIDID]  DEFAULT ((0)),
	[GIDATE] [smalldatetime] NULL CONSTRAINT [DF_MANUALOPENSHEETDETAIL_GIDATE]  DEFAULT (NULL),
	[INSPTYPE] [smallint] NULL CONSTRAINT [DF_MANUALOPENSHEETDETAIL_INSPTYPE]  DEFAULT ((0)),
	[LSEALNO] [varchar](50) NULL CONSTRAINT [DF_MANUALOPENSHEETDETAIL_LSEALNO]  DEFAULT (NULL),
	[SSEALNO] [varchar](50) NULL CONSTRAINT [DF_MANUALOPENSHEETDETAIL_SSEALNO]  DEFAULT (NULL),
	[CUSRID] [varchar](25) NULL CONSTRAINT [DF_MANUALOPENSHEETDETAIL_CUSRID]  DEFAULT (''),
	[LMUSRID] [varchar](25) NULL CONSTRAINT [DF_MANUALOPENSHEETDETAIL_LMUSRID]  DEFAULT (''),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_MANUALOPENSHEETDETAIL_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_MANUALOPENSHEETDETAIL_PRCSDATE]  DEFAULT (NULL),
	[BILLEDID] [int] NULL,
 CONSTRAINT [PK_MANUALOPENSHEETDETAIL] PRIMARY KEY CLUSTERED 
(
	[OSDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MANUALOPENSHEETDETAIL]  WITH NOCHECK ADD  CONSTRAINT [FK_MANUALOPENSHEETDETAIL_MANUALOPENSHEETMASTER] FOREIGN KEY([OSMID])
REFERENCES [dbo].[MANUALOPENSHEETMASTER] ([OSMID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[MANUALOPENSHEETDETAIL] CHECK CONSTRAINT [FK_MANUALOPENSHEETDETAIL_MANUALOPENSHEETMASTER]
GO


