UPDATE A
SET TRANDREFNO= C.ACHEADCODE
--SELECT A.*
FROM TRANSACTIONDETAIL A LEFT join ACCOUNTHEADMASTER C on A.ACHEADID = C.ACHEADID
WHERE  (A.TRANDREFNO = '' or A.TRANDREFNO = '-')AND 
TRANMID in (select TRANMID from TRANSACTIONMASTER where REGSTRID = 15 AND TRANBTYPE <> 7)

UPDATE A
SET TRANDREFNAME = C.ACHEADDESC
--SELECT A.*
FROM TRANSACTIONDETAIL A LEFT join ACCOUNTHEADMASTER C on A.ACHEADID = C.ACHEADID
WHERE -- (A.TRANDREFNO = '' or A.TRANDREFNO = '-')AND 
TRANMID in (select TRANMID from TRANSACTIONMASTER where REGSTRID = 15 AND TRANBTYPE <> 7)

