IF NOT EXISTS(select '*' from EXPORT_INVOICE_REGISTER WHERE REGSTRID = 51)
BEGIN

	insert into  EXPORT_INVOICE_REGISTER
	select 51, 'CUSTOMER'
	UNION
	SELECT 52, 'NOTIONAL'
	UNION
	SELECT 53, 'ZERO BILL'
END

UPDATE TRANSACTIONMASTER
SET REGSTRID = 51
WHERE REGSTRID = 1
AND SDPTID = 9
