-- DROP TABLE BONDTRANSACTIONMASTER_17112022
SELECT * INTO BONDTRANSACTIONMASTER_19112022
FROM BONDTRANSACTIONMASTER
WHERE --TRANDNO = 'BWH/2223/00315'
TRANNO IN (315,314,313,312,311)AND
TRANBILLREFNO LIKE 'BWH/EXB/CU/%'
--AND TRANDATE>='2022-10-19'
ORDER BY TRANBILLREFNO

delete BONDTRANSACTIONMASTER where tranmid in (14749, 14750, 14751, 14752, 14753)

SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONMASTER ON 
insert into BONDTRANSACTIONMASTER (TRANMID, COMPYID , SDPTID , REGSTRID, TRANBTYPE, TRANDATE ,TRANTIME,  TRANNO, TRANDNO, CHAID , IMPRTID,
TRANCHANAME, TRANIMPRTNAME, TRANTID ,BANKMID , TRANMODE, TRANMODEDETL ,TRANREFNO, TRANREFDATE, TRANREFBNAME, TRANREFAMT, TRANROAMT,
TRANGAMT, TRANSAMT, TRANHAMT, TRANIAMT, TRANNAMT, TRANAMTWRDS, TRANLMID, TRANLMNO, TRANLMDATE, TRANNARTN, TRANRMKS,  TRANPCOUNT, 
CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, TRANREFNAME, BILLREFID, TRANGSTNO, TRANPTAMT, TRANPLAMT, IRNNO, ACKNO, ACKDT, QRCODEPATH,
TRAN_CGST_AMT, TRAN_SGST_AMT , TRAN_IGST_AMT, BCATEAID , TRAN_TAXABLE_AMT, TRANBILLREFNO, TAXTYPE)
select TRANMID, COMPYID , SDPTID , REGSTRID, TRANBTYPE, TRANDATE ,TRANTIME , TRANNO, TRANDNO, CHAID , IMPRTID,
TRANCHANAME, TRANIMPRTNAME, TRANTID ,BANKMID , TRANMODE, TRANMODEDETL ,TRANREFNO, TRANREFDATE, TRANREFBNAME, TRANREFAMT, TRANROAMT,
TRANGAMT, TRANSAMT, TRANHAMT, TRANIAMT, TRANNAMT, TRANAMTWRDS, TRANLMID, TRANLMNO, TRANLMDATE, TRANNARTN, TRANRMKS,  TRANPCOUNT, 
CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, TRANREFNAME, BILLREFID, TRANGSTNO, TRANPTAMT, TRANPLAMT, IRNNO, ACKNO, ACKDT, QRCODEPATH,
TRAN_CGST_AMT, TRAN_SGST_AMT , TRAN_IGST_AMT, BCATEAID , TRAN_TAXABLE_AMT, TRANBILLREFNO, TAXTYPE
from [BONDTRANSACTIONMASTER_18112022]
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONMASTER OFF 
-- DROP TABLE BONDTRANSACTIONDETAIL_17112022
SELECT A.*  INTO BONDTRANSACTIONDETAIL_19112022
FROM BONDTRANSACTIONDETAIL  A JOIN BONDTRANSACTIONMASTER_17112022 B ON A.TRANMID = B.TRANMID



SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONDETAIL ON 
insert into BONDTRANSACTIONDETAIL (TRANDID, TRANMID, BNDID, EBNDID, TRANDBNDNO, TRANDEBNDNO, TARIFFMID, SLABTID, CONTNRSID, 
YRDID, TRANCTYPE, TRANOTYPE, TRANHTYPE, TRANCDATE, TRANSFDATE,TRANSEDATE, TRANIFDATE,TRANIEDATE, TRANDQTY, TRANDNOP,TRANDRATE,
TRANDWGHT, TRANDCIFAMT, TRANDDTYAMT, TRANDINSAMT, TRANDEIAMT, TRANDGAMT,TRANDSAMT, TRANDHAMT,TRANDIAMT, TRANDNAMT, TRANDAID,
DISPSTATUS, RCOLDESC1, RCOLDESC2, RCOLDESC3, RCOLDESC4, VTDID, TRANDPLAMT, TRANDPTAMT, TRAND_CGST_EXPRN, TRAND_SGST_EXPRN, 
TRAND_IGST_EXPRN, TRAND_CGST_AMT, TRAND_SGST_AMT, TRAND_IGST_AMT, INS_TRAND_CGST_AMT, INS_TRAND_SGST_AMT, INS_TRAND_IGST_AMT,
PERIODTID, TRAND_HSN_CODE, INS_TRAND_HSN_CODE, TRAND_TAXABLE_AMT, INS_TRAND_TAXABLE_AMT, STATETYPE, BILLDESC)
select TRANDID, TRANMID, BNDID, EBNDID, TRANDBNDNO, TRANDEBNDNO, TARIFFMID, SLABTID, CONTNRSID, 
YRDID, TRANCTYPE, TRANOTYPE, TRANHTYPE, TRANCDATE, TRANSFDATE,TRANSEDATE, TRANIFDATE,TRANIEDATE, TRANDQTY, TRANDNOP,TRANDRATE,
TRANDWGHT, TRANDCIFAMT, TRANDDTYAMT, TRANDINSAMT, TRANDEIAMT, TRANDGAMT,TRANDSAMT, TRANDHAMT,TRANDIAMT, TRANDNAMT, TRANDAID,
DISPSTATUS, RCOLDESC1, RCOLDESC2, RCOLDESC3, RCOLDESC4, VTDID, TRANDPLAMT, TRANDPTAMT, TRAND_CGST_EXPRN, TRAND_SGST_EXPRN, 
TRAND_IGST_EXPRN, TRAND_CGST_AMT, TRAND_SGST_AMT, TRAND_IGST_AMT, INS_TRAND_CGST_AMT, INS_TRAND_SGST_AMT, INS_TRAND_IGST_AMT,
PERIODTID, TRAND_HSN_CODE, INS_TRAND_HSN_CODE, TRAND_TAXABLE_AMT, INS_TRAND_TAXABLE_AMT, STATETYPE, BILLDESC
from BONDTRANSACTIONDETAIL_18112022
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONDETAIL OFF


-- DROP TABLE BONDTRANSACTIONMASTERFACTOR_19112022
SELECT A.*  INTO BONDTRANSACTIONMASTERFACTOR_19112022
FROM BONDTRANSACTIONMASTERFACTOR A JOIN BONDTRANSACTIONMASTER_17112022 B ON A.TRANMID = B.TRANMID

/*
DELETE FROM BONDTRANSACTIONMASTER
WHERE --TRANDNO = 'BWH/2223/00315'
TRANNO IN (315,314,313,312,311)AND
TRANBILLREFNO LIKE 'BWH/EXB/CU/%'
*/