select distinct a.bndid BondID, a.bnddno BondNo, a.BNDNOP BondNOP, 
b.BNDID ExBndBondID, b.ebndid ExBondID,b.EBNDNO ExBondNo, b.EBNDNOP EXBondNOP, 
c.TRANMID InvID, d.TRANDNO InvNO, d.TRANDATE InvDt, c.SLABTID, e.SLABTDESC,
c.bndid InvBondId, TRANDBNDNO InvBondNo, c.EBNDID InvExBondID, c.TRANDEBNDNO InvExBondNo,
c.TRANDNOP InvNOP
from BONDMASTER a (nolock) 
	left join EXBONDMASTER b(nolock) on a.BNDID = b.BNDID
	left join BONDTRANSACTIONDETAIL c(nolock) on (
	(b.eBNDDNO = TRANDEBNDNO and b.EBNDID <> c.EBNDID)
	or (a.BNDDNO = TRANDBNDNO and a.BNDID <> c.EBNDID)                                                                                                                          )
	left join BONDTRANSACTIONMASTER d(nolock) on c.TRANMID = d.TRANMID
	left join BONDSLABTYPEMASTER e(nolock) on c.SLABTID = e.SLABTID 
where slabtdesc = 'storage' or SLABTDESC is null

select distinct a1.bndid BondID, a.[Bond No] BondNo, a1.BNDNOP BondNOP, 
b.BNDID ExBndBondID, b.ebndid ExBondID,b.EBNDNO ExBondNo, b.EBNDNOP EXBondNOP, 
c.TRANMID InvID, d.TRANDNO InvNO, d.TRANDATE InvDt, c.SLABTID, e.SLABTDESC,
c.bndid InvBondId, TRANDBNDNO InvBondNo, c.EBNDID InvExBondID, c.TRANDEBNDNO InvExBondNo,
c.TRANDNOP InvNOP, TRANTID
from Old_Live_Bond_Closing_Details a (nolock) 
	left join BONDMASTER a1(nolock) on a.[Bond No] = a1.BNDDNO
	left join EXBONDMASTER b(nolock) on a1.BNDID = b.BNDID
	left join BONDTRANSACTIONDETAIL c(nolock) on (
	(b.eBNDDNO = TRANDEBNDNO)
	or (a.[Bond No] = TRANDBNDNO)                                                                                                                          )
	left join BONDTRANSACTIONMASTER d(nolock) on c.TRANMID = d.TRANMID
	left join BONDSLABTYPEMASTER e(nolock) on c.SLABTID = e.SLABTID 
where slabtdesc = 'storage' or SLABTDESC is null
2001979608



--union
--select distinct a.bndid BondID, a.bnddno BondNo, a.BNDNOP BondNOP, 
--b.BNDID ExBndBondID, b.ebndid ExBondID,b.EBNDNO ExBondNo, b.EBNDNOP EXBondNOP, 
--c.TRANMID InvID, d.TRANDNO InvNO, d.TRANDATE InvDt, c.SLABTID, e.SLABTDESC,
--c.bndid InvBondId, TRANDBNDNO InvBondNo, c.EBNDID InvExBondID, c.TRANDEBNDNO InvExBondNo,
--c.TRANDNOP InvNOP
--from BONDMASTER a (nolock) 
-- join EXBONDMASTER b(nolock) on a.BNDID = b.BNDID
-- join BONDTRANSACTIONDETAIL c(nolock) on (
--	(b.eBNDID = c.EBNDID  and b.eBNDDNO = TRANDEBNDNO)
--	or (a.BNDID = c.BNDID and a.BNDDNO = TRANDBNDNO)                                                                                                                          )
-- join BONDTRANSACTIONMASTER d(nolock) on c.TRANMID = d.TRANMID
-- join BONDSLABTYPEMASTER e(nolock) on c.SLABTID = e.SLABTID 
--where slabtdesc = 'storage' or SLABTDESC is null
----and c.tranmid > 0
----and a.BNDDNO = '2001972860'

--select * From BONDMASTER where BNDDNO = '2001972860'
--select * From Old_Live_Bond_Closing_Details where [Bond No] = '2001972860'
union
select distinct a1.bndid BondID, a.[Bond No] BondNo, a1.BNDNOP BondNOP, 
b.BNDID ExBndBondID, b.ebndid ExBondID,b.EBNDNO ExBondNo, b.EBNDNOP EXBondNOP, 
c.TRANMID InvID, d.TRANDNO InvNO, d.TRANDATE InvDt, c.SLABTID, e.SLABTDESC,
c.bndid InvBondId, TRANDBNDNO InvBondNo, c.EBNDID InvExBondID, c.TRANDEBNDNO InvExBondNo,
c.TRANDNOP InvNOP
from Old_Live_Bond_Closing_Details a (nolock) 
	join SPBW..BONDMASTER a1(nolock) on a.[Bond No] = a1.BNDDNO
	left join EXBONDMASTER b(nolock) on a1.BNDID = b.BNDID
	left join spbw..TRANSACTIONDETAIL c(nolock) on (
	(b.eBNDDNO = TRANDEBNDNO)
	or (a.[Bond No] = TRANDBNDNO)                                                                                                                          )
	left join spbw..TRANSACTIONMASTER d(nolock) on c.TRANMID = d.TRANMID
	left join BONDSLABTYPEMASTER e(nolock) on c.SLABTID = e.SLABTID 
where slabtdesc = 'storage' or SLABTDESC is null

union
select distinct a1.bndid BondID, a.[Bond No] BondNo, a1.BNDNOP BondNOP,
--[Total. Pkgs],[Del. Pkgs], [Bal. Pkgs], [Ass. Value], [Duty. Amt], 
b.BNDID ExBndBondID, b.ebndid ExBondID,
b.EBNDNO ExBondNo, b.EBNDNOP EXBondNOP, c.TRANMID InvID, d.TRANDNO InvNO, d.TRANDATE InvDt, 
c.SLABTID, e.SLABTDESC, c.bndid InvBondId, TRANDBNDNO InvBondNo, c.EBNDID InvExBondID, 
c.TRANDEBNDNO InvExBondNo, c.TRANDNOP InvNOP
from Old_Expired_Bond_Closing_Details a (nolock) 
	join SPBW..BONDMASTER a1(nolock) on a.[Bond No] = a1.BNDDNO
	left join EXBONDMASTER b(nolock) on a1.BNDID = b.BNDID
	left join spbw..TRANSACTIONDETAIL c(nolock) on (
	(b.eBNDDNO = TRANDEBNDNO)
	or (a.[Bond No] = TRANDBNDNO)                                                                                                                          )
	left join spbw..TRANSACTIONMASTER d(nolock) on c.TRANMID = d.TRANMID
	left join BONDSLABTYPEMASTER e(nolock) on c.SLABTID = e.SLABTID 
where slabtdesc = 'storage' or SLABTDESC is null

SET IDENTITY_INSERT SCFS_ERP.DBO.BONDMASTER ON 
INSERT INTO SCFS_ERP.DBO.BONDMASTER
(
BNDID,COMPYID,SDPTID,BNDNO,BNDDNO,BNDDATE,BNDFDATE,BNDTDATE,BNDADATE,IMPRTID,CHAID,YRDID,TYPEID,BNDBENO,BNDBLNO,BNDIGMNO,BNDLINENO,
BND20, BND40, BNDGWGHT, BNDCIFAMT, BNDDTYAMT, BNDINSAMT,BNDBCIFAMT, BNDBDTYAMT, BNDBINSAMT, GWNID, PRDTGID,PRDTDESC,PRDTTID,BNDNOP,
BNDSPC, BNDBNOP,BNDBSPC,BNDHAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE,BNDBEDATE,BNDBLDATE,BNDTYPE)

SELECT BNDID,31 COMPYID,10 SDPTID,BNDNO,BNDDNO,BNDDATE,BNDFDATE,BNDTDATE,BNDADATE,IMPRTID,CHAID,0 YRDID,TYPEID+1 TYPEID,BNDBENO,BNDBLNO,BNDIGMNO,'-' BNDLINENO,
BND20, BND40, BNDGWGHT, BNDCIFAMT, BNDDTYAMT, BNDINSAMT,BNDBCIFAMT, BNDBDTYAMT, BNDBINSAMT, GWNID, A.PRDTGID,B.PRDTGDESC,1 PRDTTID,BNDNOP,
BNDSPC, BNDBNOP,BNDBSPC,BNDHAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,A.CUSRID,A.LMUSRID,A.DISPSTATUS,A.PRCSDATE,BNDBEDATE,BNDBLDATE,
A.TYPEID + 1 BNDTYPE
FROM SPBW..BONDMASTER A LEFT JOIN SPBW..PRODUCTGROUPMASTER B(NOLOCK) ON A.PRDTGID = B.PRDTGID
where a.BNDDNO in(
select a.[Bond No]--, b.bndid,b.BNDDNO, b.compyid, c.bndid,c.BNDDNO,c.compyid
from Old_Live_Bond_Closing_Details a
join SPBW..BONDMASTER b(nolock) on a.[bond no] = b.bnddno
left join BONDMASTER c(nolock) on b.bnddno = c.bnddno
where c.BNDDNO is null -- b.bndid <> c.bndid or c.bndid is null
)
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDMASTER OFF



SET IDENTITY_INSERT SCFS_ERP.DBO.BONDMASTER ON 
INSERT INTO SCFS_ERP.DBO.BONDMASTER
(
BNDID,COMPYID,SDPTID,BNDNO,BNDDNO,BNDDATE,BNDFDATE,BNDTDATE,BNDADATE,IMPRTID,CHAID,YRDID,TYPEID,BNDBENO,BNDBLNO,BNDIGMNO,BNDLINENO,
BND20, BND40, BNDGWGHT, BNDCIFAMT, BNDDTYAMT, BNDINSAMT,BNDBCIFAMT, BNDBDTYAMT, BNDBINSAMT, GWNID, PRDTGID,PRDTDESC,PRDTTID,BNDNOP,
BNDSPC, BNDBNOP,BNDBSPC,BNDHAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE,BNDBEDATE,BNDBLDATE,BNDTYPE)

SELECT BNDID,31 COMPYID,10 SDPTID,BNDNO,BNDDNO,BNDDATE,BNDFDATE,BNDTDATE,BNDADATE,IMPRTID,CHAID,0 YRDID,TYPEID+1 TYPEID,BNDBENO,BNDBLNO,BNDIGMNO,'-' BNDLINENO,
BND20, BND40, BNDGWGHT, BNDCIFAMT, BNDDTYAMT, BNDINSAMT,BNDBCIFAMT, BNDBDTYAMT, BNDBINSAMT, GWNID, A.PRDTGID,B.PRDTGDESC,1 PRDTTID,BNDNOP,
BNDSPC, BNDBNOP,BNDBSPC,BNDHAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,A.CUSRID,A.LMUSRID,A.DISPSTATUS,A.PRCSDATE,BNDBEDATE,BNDBLDATE,
A.TYPEID + 1 BNDTYPE
FROM SPBW..BONDMASTER A LEFT JOIN SPBW..PRODUCTGROUPMASTER B(NOLOCK) ON A.PRDTGID = B.PRDTGID
where a.BNDDNO in(
select a.[Bond No]--, b.bndid,b.BNDDNO, b.compyid, c.bndid,c.BNDDNO,c.compyid
from Old_Expired_Bond_Closing_Details a
join SPBW..BONDMASTER b(nolock) on a.[bond no] = b.bnddno
left join BONDMASTER c(nolock) on b.bnddno = c.bnddno
where c.BNDDNO is null -- b.bndid <> c.bndid or c.bndid is null
)
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDMASTER OFF


SET IDENTITY_INSERT SCFS_ERP.DBO.BONDMASTER ON 
INSERT INTO SCFS_ERP.DBO.BONDMASTER
(
BNDID,COMPYID,SDPTID,BNDNO,BNDDNO,BNDDATE,BNDFDATE,BNDTDATE,BNDADATE,IMPRTID,CHAID,YRDID,TYPEID,BNDBENO,BNDBLNO,BNDIGMNO,BNDLINENO,
BND20, BND40, BNDGWGHT, BNDCIFAMT, BNDDTYAMT, BNDINSAMT,BNDBCIFAMT, BNDBDTYAMT, BNDBINSAMT, GWNID, PRDTGID,PRDTDESC,PRDTTID,BNDNOP,
BNDSPC, BNDBNOP,BNDBSPC,BNDHAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE,BNDBEDATE,BNDBLDATE,BNDTYPE)

SELECT BNDID,31 COMPYID,10 SDPTID,BNDNO,BNDDNO,BNDDATE,BNDFDATE,BNDTDATE,BNDADATE,IMPRTID,CHAID,0 YRDID,TYPEID+1 TYPEID,BNDBENO,BNDBLNO,BNDIGMNO,'-' BNDLINENO,
BND20, BND40, BNDGWGHT, BNDCIFAMT, BNDDTYAMT, BNDINSAMT,BNDBCIFAMT, BNDBDTYAMT, BNDBINSAMT, GWNID, A.PRDTGID,B.PRDTGDESC,1 PRDTTID,BNDNOP,
BNDSPC, BNDBNOP,BNDBSPC,BNDHAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,A.CUSRID,A.LMUSRID,A.DISPSTATUS,A.PRCSDATE,BNDBEDATE,BNDBLDATE,
A.TYPEID + 1 BNDTYPE
FROM SPBW..BONDMASTER A LEFT JOIN SPBW..PRODUCTGROUPMASTER B(NOLOCK) ON A.PRDTGID = B.PRDTGID
where a.BNDDNO in(
select a.[Bond No]--, b.bndid,b.BNDDNO, b.compyid, c.bndid,c.BNDDNO,c.compyid
from Old_Live_Bond_Closing_Details_191122 a
join SPBW..BONDMASTER b(nolock) on a.[bond no] = b.bnddno
left join BONDMASTER c(nolock) on b.bnddno = c.bnddno
where c.BNDDNO is null -- b.bndid <> c.bndid or c.bndid is null
)
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDMASTER OFF

select * from BONDMASTER order by bndid desc where bndid = 5466
select * from BONDMASTER where bndid = 5546
select a.[Bond No], b.bndid,b.BNDDNO, b.compyid, c.bndid,c.BNDDNO,c.compyid,
d.ebndid, d.EBNDDNO, d.COMPYID, e.EBNDID, e.EBNDDNO , e.COMPYID
from Old_Live_Bond_Closing_Details a
join SPBW..BONDMASTER b(nolock) on a.[bond no] = b.bnddno
left join BONDMASTER c(nolock) on b.bnddno = c.bnddno
join SPBW..EXBONDMASTER d(nolock) on b.BNDID = d.BNDID
left join EXBONDMASTER e(nolock) on d.EBNDDNO = e.EBNDDNO
where  e.EBNDDNO is null --d.ebndid <> e.ebndid or e.ebndid is null

SET IDENTITY_INSERT SCFS_ERP.DBO.EXBONDMASTER ON 
INSERT INTO SCFS_ERP.DBO.EXBONDMASTER
(
EBNDID,COMPYID,SDPTID,EBNDNO,EBNDDNO,EBNDDATE,IMPRTID,CHAID,EBNDBENO,EBNDBEDATE,BNDID,TYPEID,CONTNRSID,PRDTGID,EBNDCTYPE,EBNDNOC,
EBNDNOP,EBNDSPC,EBNDASSAMT,EBNDDTYAMT,EBNDINSAMT,EBNDBSPC,EBNDBCFAMT,EBNDBDTYAMT,EBNDDBINSAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,
INVDID,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE,EBNDEDATE
)

SELECT 
EBNDID,31,10,EBNDNO,EBNDDNO,EBNDDATE,IMPRTID,CHAID,EBNDBENO,EBNDBEDATE,BNDID,TYPEID,CONTNRSID,PRDTGID,EBNDCTYPE+1,EBNDNOC,
EBNDNOP,EBNDSPC,EBNDASSAMT,EBNDDTYAMT,EBNDINSAMT,EBNDBSPC,EBNDBCFAMT,EBNDBDTYAMT,EBNDDBINSAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,
INVDID,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE,EBNDEDATE
FROM SPBW..EXBONDMASTER A
WHERE EBNDDNO
in
(

select d.EBNDDNO 
from Old_Live_Bond_Closing_Details a
join SPBW..BONDMASTER b(nolock) on a.[bond no] = b.bnddno
left join BONDMASTER c(nolock) on b.bnddno = c.bnddno
join SPBW..EXBONDMASTER d(nolock) on b.BNDID = d.BNDID
left join EXBONDMASTER e(nolock) on d.EBNDDNO = e.EBNDDNO
where  e.EBNDDNO is null --d.ebndid <> e.ebndid or e.ebndid is null
)
SET IDENTITY_INSERT SCFS_ERP.DBO.EXBONDMASTER OFF




SET IDENTITY_INSERT SCFS_ERP.DBO.EXBONDMASTER ON 
INSERT INTO SCFS_ERP.DBO.EXBONDMASTER
(
EBNDID,COMPYID,SDPTID,EBNDNO,EBNDDNO,EBNDDATE,IMPRTID,CHAID,EBNDBENO,EBNDBEDATE,BNDID,TYPEID,CONTNRSID,PRDTGID,EBNDCTYPE,EBNDNOC,
EBNDNOP,EBNDSPC,EBNDASSAMT,EBNDDTYAMT,EBNDINSAMT,EBNDBSPC,EBNDBCFAMT,EBNDBDTYAMT,EBNDDBINSAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,
INVDID,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE,EBNDEDATE
)

SELECT 
EBNDID,31,10,EBNDNO,EBNDDNO,EBNDDATE,IMPRTID,CHAID,EBNDBENO,EBNDBEDATE,BNDID,TYPEID,CONTNRSID,PRDTGID,EBNDCTYPE+1,EBNDNOC,
EBNDNOP,EBNDSPC,EBNDASSAMT,EBNDDTYAMT,EBNDINSAMT,EBNDBSPC,EBNDBCFAMT,EBNDBDTYAMT,EBNDDBINSAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,
INVDID,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE,EBNDEDATE
FROM SPBW..EXBONDMASTER A
WHERE EBNDDNO
in
(

select d.EBNDDNO 
from Old_Live_Bond_Closing_Details_191122 a
join SPBW..BONDMASTER b(nolock) on a.[bond no] = b.bnddno
left join BONDMASTER c(nolock) on b.bnddno = c.bnddno
join SPBW..EXBONDMASTER d(nolock) on b.BNDID = d.BNDID
left join EXBONDMASTER e(nolock) on d.EBNDDNO = e.EBNDDNO
where  e.EBNDDNO is null --d.ebndid <> e.ebndid or e.ebndid is null
)
SET IDENTITY_INSERT SCFS_ERP.DBO.EXBONDMASTER OFF
--select * into Old_Live_Bond_Closing_Details_191122 from Old_Live_Bond_Closing_Details where 1=0
--delete Old_Live_Bond_Closing_Details_191122
Insert into Old_Live_Bond_Closing_Details_191122([Sl.No.],[Bond No],[Date],[Valid Till],[Cargo IN Date],[No of Pkgs],[Description],[CHA],[Importer],[BE No.],[CIF Value],[Duty Amount]) SELECT 1,'2001944625','28-12-2021','27-12-2022','31-12-2021','18','ASSORTED LIQUORS','NEPTUNES CARGO MOVERS PVT LTD','PLUS MAX DUTY FREE PVT LTD','6838810','172317','258473'
Insert into Old_Live_Bond_Closing_Details_191122([Sl.No.],[Bond No],[Date],[Valid Till],[Cargo IN Date],[No of Pkgs],[Description],[CHA],[Importer],[BE No.],[CIF Value],[Duty Amount]) SELECT 2,'2001974811','22-03-2022','21-03-2023','44565','50','ASSORTED LIQUORS','NEPTUNES CARGO MOVERS PVT LTD','PLUS MAX DUTY FREE PVT LTD','7937284','1458973','2188460'
Insert into Old_Live_Bond_Closing_Details_191122([Sl.No.],[Bond No],[Date],[Valid Till],[Cargo IN Date],[No of Pkgs],[Description],[CHA],[Importer],[BE No.],[CIF Value],[Duty Amount]) SELECT 3,'2001989932','30-04-2022','29-04-2023','44839','255','ASSORTED LIQUORS','NEPTUNES CARGO MOVERS PVT LTD','PLUS MAX DUTY FREE PVT LTD','8470705','2380618.15','3570932.22'
Insert into Old_Live_Bond_Closing_Details_191122([Sl.No.],[Bond No],[Date],[Valid Till],[Cargo IN Date],[No of Pkgs],[Description],[CHA],[Importer],[BE No.],[CIF Value],[Duty Amount]) SELECT 4,'2002010060','23-06-2022','22-06-2023','29-06-2022','104','TROLLEY BAG','NEPTUNES CARGO MOVERS PVT LTD','PLUS MAX DUTY FREE PVT LTD','9185682','32843','12307'
Insert into Old_Live_Bond_Closing_Details_191122([Sl.No.],[Bond No],[Date],[Valid Till],[Cargo IN Date],[No of Pkgs],[Description],[CHA],[Importer],[BE No.],[CIF Value],[Duty Amount]) SELECT 5,'2002034996','30-08-2022','29-08-2023','44690','1416','ASSORTED LIQUORS','NEPTUNES CARGO MOVERS PVT LTD','PLUS MAX DUTY FREE PVT LTD','2163829','9645027','14255182'
Insert into Old_Live_Bond_Closing_Details_191122([Sl.No.],[Bond No],[Date],[Valid Till],[Cargo IN Date],[No of Pkgs],[Description],[CHA],[Importer],[BE No.],[CIF Value],[Duty Amount]) SELECT 6,'2002034997','30-08-2022','29-08-2023','44690','1630','ASSORTED LIQUORS','NEPTUNES CARGO MOVERS PVT LTD','PLUS MAX DUTY FREE PVT LTD','2192826','25705421','38558132'
Insert into Old_Live_Bond_Closing_Details_191122([Sl.No.],[Bond No],[Date],[Valid Till],[Cargo IN Date],[No of Pkgs],[Description],[CHA],[Importer],[BE No.],[CIF Value],[Duty Amount]) SELECT 7,'2002036037','44601','44935','44813','650','ASSORTED LIQUORS','NEPTUNES CARGO MOVERS PVT LTD','PLUS MAX DUTY FREE PVT LTD','2234928','21473616','32210424'
Insert into Old_Live_Bond_Closing_Details_191122([Sl.No.],[Bond No],[Date],[Valid Till],[Cargo IN Date],[No of Pkgs],[Description],[CHA],[Importer],[BE No.],[CIF Value],[Duty Amount]) SELECT 8,'2002041277','16-09-2022','15-09-2023','22-09-2022','900','ASSORTED LIQUORS','NEPTUNES CARGO MOVERS PVT LTD','PLUS MAX DUTY FREE PVT LTD','2436333','11097917','16646875'

select * from Old_Live_Bond_Closing_Details_191122 a  left join Old_Live_Bond_Closing_Details b on a.[Bond No] = b.[Bond No]
SET IDENTITY_INSERT SCFS_ERP.DBO.EXBONDMASTER ON 
INSERT INTO SCFS_ERP.DBO.EXBONDMASTER
(
EBNDID,COMPYID,SDPTID,EBNDNO,EBNDDNO,EBNDDATE,IMPRTID,CHAID,EBNDBENO,EBNDBEDATE,BNDID,TYPEID,CONTNRSID,PRDTGID,EBNDCTYPE,EBNDNOC,
EBNDNOP,EBNDSPC,EBNDASSAMT,EBNDDTYAMT,EBNDINSAMT,EBNDBSPC,EBNDBCFAMT,EBNDBDTYAMT,EBNDDBINSAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,
INVDID,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE,EBNDEDATE
)

SELECT 
EBNDID,31,10,EBNDNO,EBNDDNO,EBNDDATE,IMPRTID,CHAID,EBNDBENO,EBNDBEDATE,BNDID,TYPEID,CONTNRSID,PRDTGID,EBNDCTYPE+1,EBNDNOC,
EBNDNOP,EBNDSPC,EBNDASSAMT,EBNDDTYAMT,EBNDINSAMT,EBNDBSPC,EBNDBCFAMT,EBNDBDTYAMT,EBNDDBINSAMT,STRGSDATE,STRGEDATE,INSRSDATE,INSREDATE,
INVDID,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE,EBNDEDATE
FROM SPBW..EXBONDMASTER A
WHERE EBNDDNO
in
(

select d.EBNDDNO 
from Old_Expired_Bond_Closing_Details a
join SPBW..BONDMASTER b(nolock) on a.[bond no] = b.bnddno
left join BONDMASTER c(nolock) on b.bnddno = c.bnddno
join SPBW..EXBONDMASTER d(nolock) on b.BNDID = d.BNDID
left join EXBONDMASTER e(nolock) on d.EBNDDNO = e.EBNDDNO
where  e.EBNDDNO is null --d.ebndid <> e.ebndid or e.ebndid is null
)
SET IDENTITY_INSERT SCFS_ERP.DBO.EXBONDMASTER OFF
select * from BONDTRANSACTIONDETAIL
where bndid in( 5551, 5751, 5752, 5753, 5762, 5778, 5779)

select BNDDNO, count('*') from BONDMASTER
group by BNDDNO
having  count('*') >1


select * from BONDTRANSACTIONMASTER where TRANDATE < '2022-10-19'
select * from spbw..TRANSACTIONMASTER where TRANDATE < '2022-10-19'





select a.[Bond No] LiveBndNo, b.bndid OldBndID,b.BNDDNO OldBndNo, c.bndid NewBndID,c.BNDDNO NewBndNo
into LiveBondOldVsNewBondNoDiffChk
from Old_Live_Bond_Closing_Details a
join SPBW..BONDMASTER b(nolock) on a.[bond no] = b.bnddno
left join BONDMASTER c(nolock) on b.bnddno = c.bnddno
where b.bndid <> c.bndid or c.bndid is null

update a
set BNDID = NewBndID
--select *
from SCFS_ERP..BONDTRANSACTIONDETAIL a join LiveBondOldVsNewBondNoDiffChk b (nolock)
on a.TRANDBNDNO = b.OldBndNo and a.TRANDBNDNO = b.NewBndNo
where a.BNDID <> NewBndID

drop table LiveExBondOldVsNewExBondNoDiffChk
select a.[Bond No] LiveBndNo, b.bndid OldBndID,b.BNDDNO OldBndNO, c.bndid NewBndID,c.BNDDNO NewBndNo,
d.ebndid OldExBndID, d.EBNDDNO OldExBndNo, e.EBNDID NewExBndID, e.EBNDDNO NewExBndNo
into LiveExBondOldVsNewExBondNoDiffChk
from Old_Live_Bond_Closing_Details a
join SPBW..BONDMASTER b(nolock) on a.[bond no] = b.bnddno
left join BONDMASTER c(nolock) on b.bnddno = c.bnddno
join SPBW..EXBONDMASTER d(nolock) on b.BNDID = d.BNDID
left join EXBONDMASTER e(nolock) on d.EBNDDNO = e.EBNDDNO
where  d.ebndid <> e.ebndid or e.ebndid is null

update a
set BNDID = NewBndID, EBNDID = NewExBndID
--select b.*, a.*
from SCFS_ERP..BONDTRANSACTIONDETAIL a join LiveExBondOldVsNewExBondNoDiffChk b (nolock)
on a.TRANDEBNDNO = b.OldExBndNo and a.TRANDEBNDNO = b.NewExBndNo
where a.EBNDID <> NewExBndID or a.BNDID <> b.NewBndID




drop table MissingTranNos
SELECT 
TRANMID, 31 COMPYID, 10 SDPTID, REGSTRID, TRANBTYPE, TRANDATE, TRANTIME, TRANNO, TRANDNO,CHAID, IMPRTID, TRANCHANAME,
TRANIMPRTNAME, 3 TRANTID, BANKMID, TRANMODE, TRANMODEDETL,TRANREFNO, TRANREFDATE, TRANREFBNAME, TRANREFAMT, TRANROAMT,
TRANGAMT, TRANSAMT,TRANHAMT, TRANIAMT, TRANNAMT, TRANAMTWRDS, TRANLMID, TRANLMNO, TRANLMDATE,TRANNARTN, TRANRMKS,
TRANPCOUNT,  CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, TRANREFNAME, BILLREFID, TRANGSTNO, 0 TRANPTAMT, 0 TRANPLAMT, IRNNO,
ACKNO, ACKDT, QRCODEPATH, TRAN_CGST_AMT, TRAN_SGST_AMT, TRAN_IGST_AMT, 0  BCATEAID, 0 TRAN_TAXABLE_AMT,
replace(TRANLMNO,'BWH/','BWH/EXB/')  TRANBILLREFNO
--into MissingTranNos
FROM SPBW..TRANSACTIONMASTER A
WHERE TRANMID   in (
select distinct a1.tranmid from
SPBW..TRANSACTIONDETAIL a1
  join SCFS_ERP..BONDTRANSACTIONDETAIL b1(nolock) on (a1.TRANDBNDNO =  b1.TRANDBNDNO)
or (a1.TRANDEBNDNO =  b1.TRANDEBNDNO)
)
and TRANMID  not in (
select distinct a1.tranmid from
scfs_erp..bondtransactionmaster a1
)
and tranmid not in(select tranmid from MissingTranNos)


SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONMASTER ON 
INSERT INTO SCFS_ERP.DBO.BONDTRANSACTIONMASTER
(
TRANMID, COMPYID, SDPTID, REGSTRID, TRANBTYPE, TRANDATE, TRANTIME, TRANNO, TRANDNO,CHAID, IMPRTID, TRANCHANAME,
TRANIMPRTNAME, TRANTID, BANKMID, TRANMODE, TRANMODEDETL,TRANREFNO, TRANREFDATE, TRANREFBNAME, TRANREFAMT, TRANROAMT,
TRANGAMT, TRANSAMT,TRANHAMT, TRANIAMT, TRANNAMT, TRANAMTWRDS, TRANLMID, TRANLMNO, TRANLMDATE,TRANNARTN, TRANRMKS,
TRANPCOUNT,  CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, TRANREFNAME, BILLREFID, TRANGSTNO, TRANPTAMT, TRANPLAMT, IRNNO,
ACKNO, ACKDT, QRCODEPATH, TRAN_CGST_AMT, TRAN_SGST_AMT, TRAN_IGST_AMT, BCATEAID, TRAN_TAXABLE_AMT, TRANBILLREFNO
)

SELECT 
a.TRANMID, 31, 10, a.REGSTRID, a.TRANBTYPE, a.TRANDATE, a.TRANTIME, a.TRANNO, a.TRANDNO,a.CHAID, a.IMPRTID, a.TRANCHANAME,
a.TRANIMPRTNAME, 3 TRANTID, a.BANKMID, a.TRANMODE, a.TRANMODEDETL,a.TRANREFNO, a.TRANREFDATE, a.TRANREFBNAME, a.TRANREFAMT, a.TRANROAMT,
a.TRANGAMT, a.TRANSAMT,a.TRANHAMT, a.TRANIAMT, a.TRANNAMT, a.TRANAMTWRDS, a.TRANLMID, a.TRANLMNO, a.TRANLMDATE,a.TRANNARTN, a.TRANRMKS,
a.TRANPCOUNT,  a.CUSRID, a.LMUSRID, a.DISPSTATUS, a.PRCSDATE, a.TRANREFNAME, a.BILLREFID, a.TRANGSTNO, 0, 0, a.IRNNO,
a.ACKNO, a.ACKDT, a.QRCODEPATH, a.TRAN_CGST_AMT, a.TRAN_SGST_AMT, a.TRAN_IGST_AMT, 0, 0, replace(a.TRANLMNO,'BWH/','BWH/EXB/')
FROM SPBW..TRANSACTIONMASTER A join SCFS_ERP..MissingTranNos b on a.TRANMID = b.TRANMID
and a.TRANMID  not in (
select distinct a1.tranmid from
scfs_erp..bondTRANSACTIONDETAIL a1
)
and a.TRANMID  not in (
select distinct a1.tranmid from
scfs_erp..BONDTRANSACTIONMASTER a1
)
--FROM SPBW..TRANSACTIONMASTER A 
--WHERE TRANMID   in (
--select distinct a1.tranmid from
--SPBW..TRANSACTIONDETAIL a1
-- LEFT join SCFS_ERP..BONDTRANSACTIONDETAIL b1(nolock) on (a1.TRANDBNDNO =  b1.TRANDBNDNO)
--and a1.TRANDEBNDNO =  b1.TRANDEBNDNO
--)
--and TRANMID  not in (
--select distinct a1.tranmid from
--scfs_erp..TRANSACTIONDETAIL a1
--)
--COMPYID=25 
--AND TRANDATE < '2022-10-19'
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONMASTER OFF

drop table MissingTranNoDtl
SELECT 
TRANDID, OTD.TRANMID, BNDID, EBNDID, TRANDBNDNO, TRANDEBNDNO, OTD.TARIFFMID, OTD.SLABTID, CONTNRSID, YRDID, TRANCTYPE, TRANOTYPE,
TRANHTYPE,  TRANCDATE,  TRANSFDATE, TRANSEDATE, TRANIFDATE, TRANIEDATE, TRANDQTY, TRANDNOP, TRANDRATE, TRANDWGHT,
TRANDCIFAMT, TRANDDTYAMT, TRANDINSAMT, TRANDEIAMT, TRANDGAMT, TRANDSAMT, TRANDHAMT, TRANDIAMT, TRANDNAMT,TRANDAID,
OTD.DISPSTATUS, RCOLDESC1, RCOLDESC2, RCOLDESC3, RCOLDESC4,  TRAND_CGST_EXPRN, 
TRAND_SGST_EXPRN, TRAND_IGST_EXPRN, TRAND_CGST_AMT, TRAND_SGST_AMT, TRAND_IGST_AMT,   HSNCODE,   OST.STATETYPE
into MissingTranNoDtl
FROM SPBW..TRANSACTIONDETAIL  OTD JOIN SPBW..TRANSACTIONMASTER  OTM (NOLOCK) ON OTD.TRANMID = OTM.TRANMID
JOIN SCFS_ERP..BONDSLABTYPEMASTER BSM(NOLOCK) ON OTD.SLABTID = BSM.SLABTID
JOIN SCFS_ERP..HSNCODEMASTER HSN(NOLOCK) ON BSM.HSNID = HSN.HSNID
JOIN SPBW..CATEGORYMASTER OCTG(NOLOCK) ON OTM.BILLREFID = OCTG.CATEID
JOIN SPBW..STATEMASTER OST(NOLOCK) ON OCTG.STATEID = OST.STATEID
WHERE otd.tranmid in (select tranmid from MissingTranNos)

BEGIN  TRAN
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONDETAIL ON 
INSERT INTO SCFS_ERP.DBO.BONDTRANSACTIONDETAIL
(
TRANDID, TRANMID, BNDID, EBNDID, TRANDBNDNO, TRANDEBNDNO, TARIFFMID, SLABTID, CONTNRSID, YRDID, TRANCTYPE, TRANOTYPE,
TRANHTYPE,  TRANCDATE,  TRANSFDATE, TRANSEDATE, TRANIFDATE, TRANIEDATE, TRANDQTY, TRANDNOP, TRANDRATE, TRANDWGHT,
TRANDCIFAMT, TRANDDTYAMT, TRANDINSAMT, TRANDEIAMT, TRANDGAMT, TRANDSAMT, TRANDHAMT, TRANDIAMT, TRANDNAMT,TRANDAID,
DISPSTATUS, RCOLDESC1, RCOLDESC2, RCOLDESC3, RCOLDESC4, VTDID, TRANDPLAMT, TRANDPTAMT, TRAND_CGST_EXPRN, 
TRAND_SGST_EXPRN, TRAND_IGST_EXPRN, TRAND_CGST_AMT, TRAND_SGST_AMT, TRAND_IGST_AMT, INS_TRAND_CGST_AMT, 
INS_TRAND_SGST_AMT,  INS_TRAND_IGST_AMT, PERIODTID,  TRAND_HSN_CODE, INS_TRAND_HSN_CODE, TRAND_TAXABLE_AMT, 
INS_TRAND_TAXABLE_AMT, STATETYPE)
SELECT 
TRANDID, OTD.TRANMID, BNDID, EBNDID, TRANDBNDNO, TRANDEBNDNO, OTD.TARIFFMID, OTD.SLABTID, CONTNRSID, YRDID, TRANCTYPE, TRANOTYPE,
TRANHTYPE,  TRANCDATE,  TRANSFDATE, TRANSEDATE, TRANIFDATE, TRANIEDATE, TRANDQTY, TRANDNOP, TRANDRATE, TRANDWGHT,
TRANDCIFAMT, TRANDDTYAMT, TRANDINSAMT, TRANDEIAMT, TRANDGAMT, TRANDSAMT, TRANDHAMT, TRANDIAMT, TRANDNAMT,TRANDAID,
OTD.DISPSTATUS, RCOLDESC1, RCOLDESC2, RCOLDESC3, RCOLDESC4, 0, 0, 0, TRAND_CGST_EXPRN, 
TRAND_SGST_EXPRN, TRAND_IGST_EXPRN, TRAND_CGST_AMT, TRAND_SGST_AMT, TRAND_IGST_AMT, 0, 
0,  0, 2,  HSNCODE, '', 0, 0,  OST.STATETYPE
FROM SPBW..TRANSACTIONDETAIL  OTD JOIN SPBW..TRANSACTIONMASTER  OTM (NOLOCK) ON OTD.TRANMID = OTM.TRANMID
JOIN SCFS_ERP..BONDSLABTYPEMASTER BSM(NOLOCK) ON OTD.SLABTID = BSM.SLABTID
JOIN SCFS_ERP..HSNCODEMASTER HSN(NOLOCK) ON BSM.HSNID = HSN.HSNID
JOIN SPBW..CATEGORYMASTER OCTG(NOLOCK) ON OTM.BILLREFID = OCTG.CATEID
JOIN SPBW..STATEMASTER OST(NOLOCK) ON OCTG.STATEID = OST.STATEID
WHERE otd.tranmid in (select tranmid from MissingTranNos)
and otd.tranmid not in (select tranmid from SCFS_ERP..BONDTRANSACTIONDETAIL)

SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONDETAIL OFF



SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONMASTERFACTOR ON 
INSERT INTO SCFS_ERP.DBO.BONDTRANSACTIONMASTERFACTOR
(
TRANMFID, OTFD.TRANMID , CFID, DEDEXPRN, DEDNOS, DEDMODE, DEDTYPE, DEDORDR, CFOPTN, DORDRID, DEDVALUE)
SELECT 
TRANMFID, OTFD.TRANMID , CFID, DEDEXPRN, DEDNOS, DEDMODE, DEDTYPE, DEDORDR, CFOPTN, DORDRID, DEDVALUE
FROM SPBW..TRANSACTIONMASTERFACTOR  OTFD (NOLOCK) 
JOIN SPBW..TRANSACTIONMASTER  OTM (NOLOCK) ON OTFD.TRANMID = OTM.TRANMID
WHERE OTFD.tranmid in (select tranmid from MissingTranNos)
and OTFD.tranmid not in (select tranmid from SCFS_ERP..BONDTRANSACTIONMASTERFACTOR)
SET IDENTITY_INSERT SCFS_ERP.DBO.BONDTRANSACTIONMASTERFACTOR OFF
