
 UPDATE A
 SET BILLREFID = B.BILLREFID
 FROM  BONDTRANSACTIONMASTER A JOIN SPBW..TRANSACTIONMASTER B(NOLOCK) ON A.TRANMID = B.TRANMID

 , TRANTID = 3

 
 UPDATE A
 SET CHAID = B.CURCATEID ,TRANCHANAME = B.CATENAME
 FROM BONDTRANSACTIONMASTER A JOIN FINALInit_Bond_CategoryMaster B ON 
 ( A.TRANCHANAME = B.CATENAME and catetid = 4 and b.DISPSTATUS = 0)


 UPDATE A
 SET IMPRTID = B.CURCATEID ,TRANIMPRTNAME = B.CATENAME
 FROM BONDTRANSACTIONMASTER A JOIN FINALInit_Bond_CategoryMaster B ON 
 ( A.TRANIMPRTNAME = B.CATENAME and catetid =1 and b.DISPSTATUS = 0)


 UPDATE A
 SET BILLREFID = B.CURCATEID ,TRANREFBNAME = B.CATENAME
 FROM BONDTRANSACTIONMASTER A JOIN FINALInit_Bond_CategoryMaster B ON 
 ( A.TRANREFBNAME = B.CATENAME and catetid = 4 and b.DISPSTATUS = 0)

 
 UPDATE A
 SET CHAID = B.CURCATEID 
 FROM BONDMASTER A JOIN FINALInit_Bond_CategoryMaster B ON 
 ( A.CHAID =b.CATEID and catetid = 4 and b.DISPSTATUS = 0)
 where isnumeric(a.CUSRID)=1

  
 UPDATE A
 SET IMPRTID = B.CURCATEID 
 FROM BONDMASTER A JOIN FINALInit_Bond_CategoryMaster B ON 
 ( A.IMPRTID =b.CATEID and catetid = 1 and b.DISPSTATUS = 0)
 where isnumeric(a.CUSRID)=1

 

 UPDATE A
 SET BCATEAID = b.CATEAID
 FROM BONDTRANSACTIONMASTER A JOIN category_address_detail b
 on (A.BILLREFID =  B.CATEID )

--select * from BONDTRANSACTIONMASTER where BCATEAID =0


 
-- UPDATE A
-- SET BILLREFID = B.BILLREFID, TRANTID = 3
-- FROM  BONDTRANSACTIONMASTER A JOIN SPBW..TRANSACTIONMASTER B(NOLOCK) ON A.TRANMID = B.TRANMID

-- UPDATE A
-- SET BILLREFID = B.CURCATEID ,TRANREFBNAME = B.CATENAME
-- FROM BONDTRANSACTIONMASTER A JOIN FINALInit_Bond_CategoryMaster B ON 
-- (A.BILLREFID =  B.CATEID OR A.TRANREFBNAME = B.CATENAME and catetid = 4)

-- UPDATE A
-- SET BCATEAID = b.CATEAID
-- FROM BONDTRANSACTIONMASTER A JOIN category_address_detail b
-- on (A.BILLREFID =  B.CATEID )

-- select a.* from FINALInit_Bond_CategoryMaster a
--  left join CATEGORYMASTER b on 
-- a.curcateid =  b.cateid 
-- left join category_address_detail c on 
-- b.cateid =  c.cateid 
-- where C.cateid is null

 
--BEGIN TRAN
--INSERT INTO SCFS_ERP..CATEGORY_ADDRESS_DETAIL(CATEID, STATEID, CATEAGSTNO, CATEAADDR1, CATEAADDR2, CATEAADDR3, 
--CATEAADDR4, CATEATYPEDESC, CATEAPANNO)
--SELECT B.CATEID, B.STATEID, B.CATEGSTNO, B.CATEADDR1, B.CATEADDR2,  B.CATEADDR3, B.CATEADDR4,
--B.CATEADDR3,  ISNULL(SUBSTRING(B.CATEGSTNO,3,10),'-')
----SELECT B.*
--FROM SCFS_ERP..CATEGORYMASTER A JOIN FINALInit_Bond_CategoryMaster B ON 
-- A.CATENAME = b.CATENAME and A.CATETID = b.CATETID AND A.CATEID = B.CURCATEID
-- LEFT JOIN  SCFS_ERP..CATEGORY_ADDRESS_DETAIL C(NOLOCK) ON A.CATEID = B.CATEID
-- WHERE C.CATEAID IS NULL
-- ROLLBACK TRAN


-- select * from FINALInit_Bond_CategoryMaster