USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[OPENSHEET_SEAL_DETAIL]    Script Date: 12-08-2021 16:24:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[OPENSHEET_SEAL_DETAIL](
	[OSSID] [int] IDENTITY(1,1),
	[OSSDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_OPENSHEET_SEAL_DETAIL_OSSDATE]  DEFAULT (null),
	[OSMID] [int] NOT NULL CONSTRAINT [DF_OPENSHEET_SEAL_DETAIL_OSDID]  DEFAULT (0),
	[SEALMID] [int] NOT NULL CONSTRAINT [DF_OPENSHEET_SEAL_DETAIL_SEALMID]  DEFAULT (0),
	[OSSDESC] [varchar](25) NULL CONSTRAINT [DF_OPENSHEET_SEAL_DETAIL_OSSDESC]  DEFAULT (null),
	[CUSRID] varchar(25) NULL CONSTRAINT [DF_OPENSHEET_SEAL_DETAIL_CUSRID]  DEFAULT (''),
	[LMUSRID] varchar(25) NULL CONSTRAINT [DF_OPENSHEET_SEAL_DETAIL_LMUSRID]  DEFAULT (''),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_OPENSHEET_SEAL_DETAIL_DISPSTATUS]  DEFAULT (0),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_OPENSHEET_SEAL_DETAIL_PRCSDATE]  DEFAULT (null),
 CONSTRAINT [PK_OPENSHEET_SEAL_DETAIL] PRIMARY KEY CLUSTERED 
(
	[OSSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[OPENSHEET_SEAL_DETAIL]  WITH NOCHECK ADD  CONSTRAINT [FK_OPENSHEET_SEAL_DETAIL_OPENSHEETMASTER] FOREIGN KEY([OSMID])
REFERENCES [dbo].[OPENSHEETMASTER] ([OSMID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[OPENSHEET_SEAL_DETAIL] CHECK CONSTRAINT [FK_OPENSHEET_SEAL_DETAIL_OPENSHEETMASTER]
GO


