SELECT     TOP 100 PERCENT dbo.COMPANYMASTER.COMPNAME, dbo.OPENSHEETMASTER.COMPYID, dbo.OPENSHEETMASTER.OSMID, 
                      dbo.OPENSHEETMASTER.OSMDATE, dbo.OPENSHEETMASTER.OSMTIME, dbo.OPENSHEETMASTER.OSMNO, dbo.OPENSHEETMASTER.OSMDNO, 
                      dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.OPENSHEETMASTER.BOENO, dbo.OPENSHEETMASTER.BOEDATE, 
                      dbo.OPENSHEETMASTER.OSMNAME, dbo.OPENSHEETDETAIL.OSDID, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                      dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.CONTNRSID, dbo.OPENSHEETMASTER.CHAID, dbo.TMPRPT_IDS.RPTID, 
                      dbo.TMPRPT_IDS.KUSRID, dbo.OPENSHEETMASTER.SCTYPE, dbo.OPENSHEETMASTER.SCDATE, dbo.OPENSHEETMASTER.SCTIME, 
                      dbo.OPENSHEETMASTER.DOTYPE, dbo.OPENSHEETMASTER.DODATE, dbo.OPENSHEETMASTER.DONO, dbo.OPENSHEETMASTER.DOIDATE, 
                      dbo.GATEINDETAIL.IMPRTNAME, dbo.GATEINDETAIL.STMRID, OPENSHEET_VIA_DETAILS.OSMTYPEDESC
FROM         dbo.OPENSHEETMASTER INNER JOIN
                      dbo.OPENSHEETDETAIL ON dbo.OPENSHEETMASTER.OSMID = dbo.OPENSHEETDETAIL.OSMID INNER JOIN
                      dbo.COMPANYACCOUNTINGDETAIL ON dbo.OPENSHEETMASTER.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                      dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID INNER JOIN
                      dbo.GATEINDETAIL ON dbo.OPENSHEETDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                      dbo.TMPRPT_IDS ON dbo.GATEINDETAIL.STMRID = dbo.TMPRPT_IDS.RPTID inner join
					  OPENSHEET_VIA_DETAILS (nolock) on opensheetmaster.OSMTYPE = OPENSHEET_VIA_DETAILS.OSMTYPE
ORDER BY dbo.OPENSHEETMASTER.OSMNAME, dbo.OPENSHEETMASTER.OSMDATE, dbo.OPENSHEETMASTER.OSMDNO, dbo.OPENSHEETDETAIL.OSDID


