
ALTER TABLE [dbo].[OPENSHEETMASTER] DROP CONSTRAINT DF__OPENSHEET__OSBCH__4CF63474
GO

alter table OPENSHEETMASTER 
alter column OSBCHACATEAID int not  null 

ALTER TABLE [dbo].[OPENSHEETMASTER] ADD  CONSTRAINT DF__OPENSHEET__OSBCH__4CF63474  DEFAULT ((0)) FOR OSBCHACATEAID
GO


ALTER TABLE [dbo].[OPENSHEETMASTER] DROP CONSTRAINT DF__OPENSHEET__OSBBC__4DEA58AD
GO

alter table OPENSHEETMASTER 
alter column OSBBCHACATEAID int not  null 

ALTER TABLE [dbo].[OPENSHEETMASTER] ADD  CONSTRAINT DF__OPENSHEET__OSBBC__4DEA58AD  DEFAULT ((0)) FOR OSBBCHACATEAID
GO