alter table OPENSHEETMASTER
add [OSMLDTYPE] [smallint] NULL

alter table OPENSHEETMASTER
add [OSMDUTYAMT] [numeric](18, 0) NOT NULL CONSTRAINT [DF_OPENSHEETMASTER_OSMDUTYAMT]  DEFAULT ((0))

alter table OPENSHEETMASTER
add [OSMBLDATE] [smalldatetime] NULL

alter table OPENSHEETMASTER
add [OSMIGMDATE] [smalldatetime] NULL


ALTER TABLE [dbo].OPENSHEETMASTER DROP CONSTRAINT DF_OPENSHEETMASTER_LMUSRID
GO

alter table OPENSHEETMASTER 
alter column LMUSRID varchar(25)  null 

ALTER TABLE [dbo].OPENSHEETMASTER ADD  CONSTRAINT DF_OPENSHEETMASTER_LMUSRID  DEFAULT (('')) FOR [LMUSRID]
GO


ALTER TABLE [dbo].OPENSHEETDETAIL DROP CONSTRAINT DF_OPENSHEETDETAIL_LMUSRID
GO

alter table OPENSHEETDETAIL 
alter column LMUSRID varchar(25)  null 

ALTER TABLE [dbo].OPENSHEETDETAIL ADD  CONSTRAINT DF_OPENSHEETDETAIL_LMUSRID  DEFAULT (('')) FOR [LMUSRID]
GO