SELECT * FROM OPENSHEET_VIA_DETAILS

if not exists(SELECT '*' FROM OPENSHEET_VIA_DETAILS where OSMTYPEDESC = 'RMSOPEN')
begin
	insert into OPENSHEET_VIA_DETAILS
	select 5, 'RMSOPEN'
end
SELECT * FROM OPENSHEET_VIA_DETAILS