--USE SCFS_ERP
--GO
--alter table DELIVERYORDERMASTER
--add OOCNO varchar(50) NULL 
--GO
--alter table DELIVERYORDERMASTER
--add OOCDATE DATETIME  NULL  

--GO
--UPDATE DELIVERYORDERMASTER
--SET OOCNO = ''
--WHERE OOCNO IS NULL

--UPDATE DELIVERYORDERMASTER
--SET OOCDATE = CONVERT(VARCHAR(10),PRCSDATE,120)
--WHERE OOCDATE IS NULL


--ALTER TABLE DELIVERYORDERMASTER
--DROP COLUMN OOCNO 
--GO
--ALTER TABLE DELIVERYORDERMASTER
--DROP COLUMN OOCDATE 
--GO


USE SCFS_ERP
GO
--ALTER TABLE OPENSHEETMASTER
--DROP COLUMN OOCNO 
--GO
--ALTER TABLE OPENSHEETMASTER
--DROP COLUMN OOCDATE 
--GO

alter table OPENSHEETMASTER
add OOCNO varchar(50) NULL 
GO
alter table OPENSHEETMASTER
add OOCDATE DATETIME  NULL  

GO
UPDATE OPENSHEETMASTER
SET OOCNO = ''
WHERE OOCNO IS NULL

UPDATE OPENSHEETMASTER
SET OOCDATE = CONVERT(VARCHAR(10),PRCSDATE,120)
WHERE OOCDATE IS NULL
