select *from SOFT_TABLE_DELETE_DETAIL 

insert into SOFT_TABLE_DELETE_DETAIL(TABDID,OPTNSTR,TABNAME,PFLDNAME,DCONDTNSTR,DISPDESC)
values(55,'OPENSHEETEDIT','OPENSHEETDETAIL (nolock) inner join  TRANSACTIONDETAIL (nolock) on TRANSACTIONDETAIL.BILLEDID = OPENSHEETDETAIL.BILLEDID',
'TRANSACTIONDETAIL.BILLEDID','OSMID=','Invoice Details Exists.So U Cannot Edit......!')

--update SOFT_TABLE_DELETE_DETAIL set PFLDNAME = 'TRANSACTIONDETAIL.BILLEDID'  where TABDID=55




 
 
 