USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[OPENSHEET_VIA_DETAILS]    Script Date: 12-08-2021 12:30:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[OPENSHEET_VIA_DETAILS](
	[OSMTYPE] [int] NOT NULL CONSTRAINT [DF_OPENSHEET_VIA_DETAILS_OSMTYPE]  DEFAULT ((0)),
	[OSMTYPEDESC] [varchar](100) NULL CONSTRAINT [DF_OPENSHEET_VIA_DETAILS_OSMTYPEDESC]  DEFAULT (NULL),
 CONSTRAINT [PK_OPENSHEET_VIA_DETAILS] PRIMARY KEY CLUSTERED 
(
	[OSMTYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


