select * 
--delete 
from OPENSHEETMASTER where OSMDNO =1670

select * from scfs_erp_bk05082022..opensheetmaster where osmdno = 1670
and osmid=12976
select * From OPENSHEET_SEAL_DETAIL

begin tran

IF NOT EXISTS(SELECT '*' FROM OPENSHEETMASTER (NOLOCK) WHERE OSMID=12976)
BEGIN
SELECT 'INSERTING MASTER'
	set identity_insert opensheetmaster on
	insert into OPENSHEETMASTER (OSMID, SDPTID, COMPYID, OSMDATE, OSMTIME, OSMNO, OSMDNO, CHAID, OSMNAME, OSMCNAME, OSMIGMNO,
	OSMVSLNAME, BOENO, BOEDATE, OSMTYPE, DOTYPE, DODATE, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, OSMLNO, DONO, DOIDATE, 
	SCTYPE, SCDESC, SCDATE, SCTIME, SCREMRKS, OSMAAMT, OSMBLNO, OSMNOP, OSMWGHT, OSMUNITID, OSMLNAME, OSMTNOC, OSMFNOC, 
	OSMLCATEID, OSMLCATENAME, OSBILLEDTO, OSBILLREFID, OSBILLREFNAME, OSCATEAID, OSMLDTYPE, OSMDUTYAMT, OSMBLDATE, OSMIGMDATE,
	OSBCHACATEAID, OSBCHACATEAGSTNO, OSBCHAADDR1, OSBCHAADDR2, OSBCHAADDR3, OSBCHAADDR4, OSBCHASTATEID, OSBBCHACATEAID, 
	OSBBCHACATEAGSTNO, OSBBCHAADDR1, OSBBCHAADDR2, OSBBCHAADDR3, OSBBCHAADDR4, OSBBCHASTATEID ,OLDOSMID)
	select OSMID, SDPTID, COMPYID, OSMDATE, OSMTIME, OSMNO, OSMDNO, CHAID, OSMNAME, OSMCNAME, OSMIGMNO,
	OSMVSLNAME, BOENO, BOEDATE, OSMTYPE, DOTYPE, DODATE, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, OSMLNO, DONO, DOIDATE, 
	SCTYPE, SCDESC, SCDATE, SCTIME, SCREMRKS, OSMAAMT, OSMBLNO, OSMNOP, OSMWGHT, OSMUNITID, OSMLNAME, OSMTNOC, OSMFNOC, 
	OSMLCATEID, OSMLCATENAME, OSBILLEDTO, OSBILLREFID, OSBILLREFNAME, OSCATEAID, OSMLDTYPE, OSMDUTYAMT, OSMBLDATE, OSMIGMDATE,
	OSBCHACATEAID, OSBCHACATEAGSTNO, OSBCHAADDR1, OSBCHAADDR2, OSBCHAADDR3, OSBCHAADDR4, OSBCHASTATEID, OSBBCHACATEAID, 
	OSBBCHACATEAGSTNO, OSBBCHAADDR1, OSBBCHAADDR2, OSBBCHAADDR3, OSBBCHAADDR4, OSBBCHASTATEID ,OLDOSMID
	 from scfs_erp_bk05082022..opensheetmaster where osmdno = 1670
	and osmid=12976
	set identity_insert opensheetmaster off
END

IF NOT EXISTS(SELECT '*' FROM OPENSHEETDETAIL(NOLOCK) where osmid=12976)
BEGIN
SELECT 'INSERTING DTAL'
	set identity_insert OPENSHEETDETAIL on
	insert into OPENSHEETDETAIL (OSDID, OSMID, GIDID, GIDATE, INSPTYPE, LSEALNO, SSEALNO, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, 
	BILLEDID, CSEALNO, OLDOSDID)
	select OSDID, OSMID, GIDID, GIDATE, INSPTYPE, LSEALNO, SSEALNO, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, 
	BILLEDID, CSEALNO, OLDOSDID
	from scfs_erp_bk05082022..OPENSHEETDETAIL where osmid=12976
	set identity_insert OPENSHEETDETAIL off

END
IF NOT EXISTS(SELECT '*' FROM OPENSHEET_SEAL_DETAIL(NOLOCK) where OSMID=12976)
BEGIN
SELECT 'INSERTING OS SL DTAL'
	set identity_insert OPENSHEET_SEAL_DETAIL on
	insert into OPENSHEET_SEAL_DETAIL (OSSID, OSSDATE, OSMID, SEALMID, OSSDESC,  CUSRID, LMUSRID,   DISPSTATUS, PRCSDATE)
	select OSSID, OSSDATE, OSMID, SEALMID, OSSDESC,  CUSRID, LMUSRID,   DISPSTATUS, PRCSDATE
	from scfs_erp_bk05082022..OPENSHEET_SEAL_DETAIL where OSMID=12976
	set identity_insert OPENSHEET_SEAL_DETAIL off
END
rolLback tran
COMMIT TRAN