

-- pending GO Check
DROP TABLE #VTNGODTL
select 'CATEGORY' = CASE	WHEN vt.SDPTID = 1 THEN 'IMPORT'
							WHEN vt.SDPTID = 2 THEN 'EXPORT'
							WHEN vt.SDPTID = 9 THEN 'NON-PNR'
							ELSE 'OTHER' END,
	vt.VTDID, vt.VTDATE,  vt.VTNO, vt.VTDNO, vt.ASLDID, vt.DRVNAME, vt.VTDESC, vt.VHLNO, GATEINDETAIL.CONTNRSID,
	CONTAINERSIZEMASTER.CONTNRSDESC, OLDVTDID, CONTNRNO , ovt.VTDNO 'OVTDNO', cast(null as datetime) 'OGODT' , cast(null as datetime) 'OGOTM'
INTO #VTNGODTL
from VEHICLETICKETDETAIL as vt join AUTHORIZATIONSLIPDETAIL on vt.ASLDID = AUTHORIZATIONSLIPDETAIL.ASLDID
	left join GATEOUTDETAIL on AUTHORIZATIONSLIPDETAIL.GIDID = GATEOUTDETAIL.GIDID 
	inner join  scfs.dbo.VEHICLETICKETDETAIL as ovt on OLDVTDID = ovt.VTDID inner join
	AUTHORIZATIONSLIPMASTER ON AUTHORIZATIONSLIPDETAIL.ASLMID = AUTHORIZATIONSLIPMASTER.ASLMID
	INNER JOIN GATEINDETAIL ON vt.GIDID = GATEINDETAIL.GIDID 
	INNER JOIN CONTAINERSIZEMASTER ON GATEINDETAIL.CONTNRSID = CONTAINERSIZEMASTER.CONTNRSID
where vt.COMPYID = 32
and GATEOUTDETAIL.GIDID is null 
and vt.OLDVTDID not in (select vtdid from scfs.dbo.VEHICLETICKETDETAIL 
											join scfs.dbo.GATEOUTDETAIL on scfs.dbo.VEHICLETICKETDETAIL.GIDID = scfs.dbo.GATEOUTDETAIL.GIDID 
											where GATEOUTDETAIL.GODATE >= '2021-04-01')
and vt.SDPTID  = 1
--AND GATEOUTDETAIL.GODATE <= '2021-09-30'

UPDATE A
SET OGODT = C.GODATE, OGOTM = C.GOTIME
-- SELECT A.*
FROM #VTNGODTL A JOIN scfs.dbo.VEHICLETICKETDETAIL B ON A.OLDVTDID = B.VTDID  
join scfs.dbo.GATEOUTDETAIL C on B.GIDID = C.GIDID AND B.SDPTID = C.SDPTID 
--AND C.GODATE>= A.VTDATE
WHERE B.SDPTID = 1

SELECT * FROM #VTNGODTL


SELECT * FROM VEHICLETICKETDETAIL WHERE ASLDID = 0
SELECT * FROM GATEOUTDETAIL WHERE GIDID = 62090


SELECT E.*,F.*
FROM VEHICLETICKETDETAIL A(NOLOCK), AUTHORIZATIONSLIPDETAIL D(NOLOCK), GATEOUTDETAIL B(NOLOCK)	, GATEINDETAIL C(NOLOCK),
	SCFS.DBO.VEHICLETICKETDETAIL E(NOLOCK), SCFS.DBO.AUTHORIZATIONSLIPDETAIL E(NOLOCK), SCFS.DBO.GATEOUTDETAIL F(NOLOCK)
WHERE OLDVTDID > 0 
AND A.ASLDID = D.ASLDID
AND D.GIDID = B.GIDID 
AND B.GIDID = C.GIDID
AND A.OLDVTDID = E.VTDID
AND E.GIDID = F.GIDID
AND E.SDPTID = F.SDPTID
AND A.SDPTID = E.SDPTID
AND E.VTDATE <= F.GODATE

SELECT * FROM SCFS.DBO.GATEOUTDETAIL F(NOLOCK)