select * from GATEINDETAIL joi


ALTER VIEW VW_IMPORT_CONTAINER_RECENT_DETAIL_CTRL
AS

SELECT CONTNRNO, MAX(GIDATE) AS XGIDATE 
FROM DBO.GATEINDETAIL
WHERE SDPTID = 1 -- AND GPSTYPE IN (4,5)
AND CONTNRSID >=3 
GROUP BY CONTNRNO


ALTER VIEW VW_IMPORT_PENDING_CONTAINER_DETAIL_CTRL
AS
SELECT DBO.GATEINDETAIL.* FROM DBO.GATEINDETAIL 
				JOIN DBO.VW_IMPORT_CONTAINER_RECENT_DETAIL_CTRL ON DBO.GATEINDETAIL.CONTNRNO = VW_IMPORT_CONTAINER_RECENT_DETAIL_CTRL.CONTNRNO
				AND  GIDATE = XGIDATE
				LEFT JOIN DBO.GATEOUTDETAIL ON DBO.GATEINDETAIL.GIDID = DBO.GATEOUTDETAIL.GIDID AND GATEINDETAIL.SDPTID = GATEOUTDETAIL.SDPTID
WHERE DBO.GATEOUTDETAIL.GIDID IS NULL
AND GATEINDETAIL.SDPTID = 1
-- AND --GATEINDETAIL.GIDATE <= '2021-09-30' --GATEINDETAIL.GIDATE >= '2021-10-01'




SELECT * FROM VW_IMPORT_CONTAINER_RECENT_DETAIL_CTRL
WHERE CONTNRNO = 'CXTU1005397'

SELECT * FROM VW_IMPORT_PENDING_CONTAINER_DETAIL_CTRL
WHERE CONTNRNO = 'CXTU1005397'


SELECT DBO.GATEOUTDETAIL.*
	
 FROM DBO.GATEINDETAIL 
				JOIN DBO.VW_IMPORT_CONTAINER_RECENT_DETAIL_CTRL ON DBO.GATEINDETAIL.CONTNRNO = VW_IMPORT_CONTAINER_RECENT_DETAIL_CTRL.CONTNRNO
				AND  GIDATE = XGIDATE
				 JOIN DBO.GATEOUTDETAIL ON DBO.GATEINDETAIL.GIDID = DBO.GATEOUTDETAIL.GIDID AND GATEINDETAIL.SDPTID = GATEOUTDETAIL.SDPTID
WHERE GATEINDETAIL.SDPTID = 1
AND GATEINDETAIL.CONTNRNO = 'CXTU1005397'


SELECT	A.CONTNRNO 
FROM	VW_IMPORT_CONTAINER_RECENT_DETAIL_CTRL A(NOLOCK) JOIN GATEINDETAIL B(NOLOCK) ON A.CONTNRNO = B.CONTNRNO AND A.XGIDATE = B.GIDATE
			JOIN VEHICLETICKETDETAIL C(NOLOCK) JOIN	 SCFS.DBO.VEHICLETICKETDETAIL D(NOLOCK) ON C.OLDVTDID = D.VTDID
					JOIN SCFS.DBO.GATEOUTDETAIL E(NOLOCK) ON D.GIDID = E.GIDID 
					LEFT JOIN GATEOUTDETAIL F(NOLOCK) ON C.GIDID = F.GIDID

			
