Declare  @tblremotegatein Table 
	(
	   GIDATE smalldatetime
      , GINO INT
      , GIDNO VARCHAR(25)
      , CONTNRNO  VARCHAR(25)
      , CONTNRSID  int
	  ,IGMNO VARCHAR(25)
	  ,GPLNO VARCHAR(25)
      , STMRNAME VARCHAR(150)
	  , IMPRTNAME VARCHAR(150)
	  ,VSLNAME VARCHAR(100)
	  ,PRDTDESC VARCHAR(100)
	  ,DISPSTATUS SMALLINT
	  , GIDID int 
	  ,AGIDID INT
	)

	Insert Into @tblremotegatein(GIDATE,GINO,GIDNO,CONTNRNO,CONTNRSID,IGMNO,GPLNO,STMRNAME,IMPRTNAME, VSLNAME,
	PRDTDESC,DISPSTATUS,GIDID,AGIDID)
	SELECT --ISNULL(convert(varchar(10),REMOTEGATEINDETAIL.GIDATE,103),'') as GIDATE,
			REMOTEGATEINDETAIL.GIDATE,
			ISNULL(REMOTEGATEINDETAIL.GINO,0) as GINO, 
	       ISNULL(REMOTEGATEINDETAIL.GIDNO,'') as GIDNO , ISNULL(REMOTEGATEINDETAIL.CONTNRNO,'') as CONTNRNO ,
		   ISNULL(REMOTEGATEINDETAIL.CONTNRSID,0) as CONTNRSID ,ISNULL(REMOTEGATEINDETAIL.IGMNO,'') as IGMNO,
		   ISNULL(REMOTEGATEINDETAIL.GPLNO,'') as GPLNO,ISNULL(STMN.CATENAME,'') as STMRNAME,
		   --ISNULL(IMPN.CATENAME,'') as IMPRTNAME,ISNULL(VESSELMASTER.VSLDESC,'') as VSLNAME,
		    ISNULL(VESSELMASTER.VSLDESC,'') as IMPRTNAME,ISNULL(IMPN.CATENAME,'') as VSLNAME,

		   REMOTEGATEINDETAIL.PRDTDESC as PRDTGDESC,
		   --ISNULL(PRODUCTGROUPMASTER.PRDTGDESC,'') as PRDTGDESC,
		   ISNULL(REMOTEGATEINDETAIL.DISPSTATUS,0) as DISPSTATUS,
		   ISNULL(REMOTEGATEINDETAIL.GIDID,0) as GIDID, --0 as AGIDID,
		   ISNULL(REMOTEGATEINDETAIL.AGIDID,0) as AGIDID
		   --ISNULL(GATEINDETAIL.RGIDID,0) as AGIDID,
		    
    FROM   REMOTEGATEINDETAIL (nolock) Left Join  
	       CONTAINERSIZEMASTER (nolock) ON REMOTEGATEINDETAIL.CONTNRSID = CONTAINERSIZEMASTER.CONTNRSID Left Join
		   CATEGORYMASTER STMN (nolock) ON REMOTEGATEINDETAIL.STMRID = STMN.CATEID Left Join 
		   CATEGORYMASTER IMPN (nolock) ON REMOTEGATEINDETAIL.IMPRTID = IMPN.CATEID Left Join 
		   VESSELMASTER (nolock) ON REMOTEGATEINDETAIL.VSLID = VESSELMASTER.VSLID Left Join 
		   PRODUCTGROUPMASTER (nolock) ON REMOTEGATEINDETAIL.PRDTGID = PRODUCTGROUPMASTER.PRDTGID Left Join 
		   GATEINDETAIL (nolock) ON REMOTEGATEINDETAIL.GIDID = GATEINDETAIL.RGIDID 
	WHERE  (REMOTEGATEINDETAIL.COMPYID > 0) AND  (REMOTEGATEINDETAIL.DISPSTATUS=0) and ISNULL(REMOTEGATEINDETAIL.AGIDID,0) = 0 and ISNULL(GATEINDETAIL.RGIDID,0)=0
	
	GROUP BY REMOTEGATEINDETAIL.GIDATE,REMOTEGATEINDETAIL.GINO,REMOTEGATEINDETAIL.GIDNO,
	         REMOTEGATEINDETAIL.CONTNRNO,REMOTEGATEINDETAIL.CONTNRSID,REMOTEGATEINDETAIL.IGMNO,
			 REMOTEGATEINDETAIL.GPLNO,STMN.CATENAME,IMPN.CATENAME,REMOTEGATEINDETAIL.PRDTDESC,
	         VESSELMASTER.VSLDESC,PRODUCTGROUPMASTER.PRDTGDESC,REMOTEGATEINDETAIL.DISPSTATUS,
			 REMOTEGATEINDETAIL.GIDID,GATEINDETAIL.RGIDID,REMOTEGATEINDETAIL.AGIDID


select * from @tblremotegatein