
SELECT    oldgid, dbo.GATEINDETAIL.GIDID,gidno, gidate, dbo.GATEINDETAIL.AVHLNO, gateindetail.chaid, GATEINDETAIL.CHANAME, GATEINDETAIL.bCHANAME,
			isnull(EXPORTSHIPPINGBILLMASTER.ESBMDNO,'-') as ESBMDNO, EXPORTSHIPPINGBILLMASTER.EXPRTID, EXPORTSHIPPINGBILLMASTER.EXPRTNAME, 
          isnull(EXPORTSHIPPINGBILLMASTER.ESBMID,0) as ESBMID, GPNOP, gateindetail.PRDTDESC
FROM       dbo.GATEINDETAIL (nolock) LEFT OUTER JOIN 
	       EXPORTSHIPPINGBILLMASTER (nolock) ON GATEINDETAIL.ESBMID = EXPORTSHIPPINGBILLMASTER.ESBMID  LEFT OUTER JOIN 
	   SHIPPINGBILLDETAIL (nolock) ON EXPORTSHIPPINGBILLMASTER.ESBMID = SHIPPINGBILLDETAIL.ESBMID left join 
	   SHIPPINGBILLMASTER (nolock) ON SHIPPINGBILLMASTER.SBMID = SHIPPINGBILLDETAIL.SBMID --LEFT JOIN
	   --TMP_CARTING_ORDER_TRUCK_DUPCHK (NOLOCK) ON GATEINDETAIL.GIDID = TMP_CARTING_ORDER_TRUCK_DUPCHK.GIDID AND TMP_CARTING_ORDER_TRUCK_DUPCHK.CUSRID = @PCUSRID
		   
WHERE     (dbo.GATEINDETAIL.GPSTYPE IN (1, 5)) AND (dbo.GATEINDETAIL.SDPTID = 2) 
and isnull(SHIPPINGBILLDETAIL.SBMID,0) = 0 
--and oldgid>0
--AND TMP_CARTING_ORDER_TRUCK_DUPCHK.TRUCKNO IS NULL
ORDER BY oldgid, dbo.GATEINDETAIL.AVHLNO
