--select count('*') from GATEINDETAIL (nolock) 
--select count('*') from GATEOUTDETAIL (nolock)

EXEC PR_IMPORT_DASHBOARD_DETAILS '2022-08-24' , '2022-08-24', 1
go
EXEC PR_EXPORT_DASHBOARD_DETAILS '2022-08-24' , '2022-08-24', 1
GO

--select sdptid,count('*') from GATEINDETAIL (nolock) group by SDPTID
--select SDPTID,count('*') from GATEOUTDETAIL (nolock) group by SDPTID

-- DROP INDEX [_dta_index_GATEINDETAIL_17_1956918043__K3] ON [dbo].[GATEINDETAIL]
-- DROP INDEX [_dta_index_GATEOUTDETAIL_17_1245963515__K3] ON [dbo].[GATEOUTDETAIL]

--CREATE NONCLUSTERED INDEX [_dta_index_GATEINDETAIL_17_1956918043__K3] ON [dbo].[GATEINDETAIL]
--(
--	[SDPTID] ASC
--)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]


--CREATE NONCLUSTERED INDEX [_dta_index_GATEOUTDETAIL_17_1245963515__K3] ON [dbo].[GATEOUTDETAIL]
--(
--	[SDPTID] ASC
--)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
