--ALTER TABLE PERFORMA_TRANSACTIONMASTER
--drop column [CHACATEAID] 
--GO

--ALTER TABLE PERFORMA_TRANSACTIONMASTER
--drop column [CHACATEAGSTNO] 
--GO
	
--ALTER TABLE PERFORMA_TRANSACTIONMASTER
--drop column [CHAADDR1] 
--GO

--ALTER TABLE PERFORMA_TRANSACTIONMASTER
--drop column [CHAADDR2] 
--GO

--ALTER TABLE PERFORMA_TRANSACTIONMASTER
--drop column [CHAADDR3] 
--GO

--ALTER TABLE PERFORMA_TRANSACTIONMASTER
--drop column [CHAADDR4] 
--GO

--ALTER TABLE PERFORMA_TRANSACTIONMASTER
--drop column [OSBCHASTATEID] 
--GO




ALTER TABLE PERFORMA_TRANSACTIONMASTER
ADD [CHACATEAID] [int] NULL
GO

ALTER TABLE PERFORMA_TRANSACTIONMASTER
ADD [CHACATEAGSTNO] [varchar](50) NULL
GO
	
ALTER TABLE PERFORMA_TRANSACTIONMASTER
ADD [CHAADDR1] [varchar](100) NULL
GO

ALTER TABLE PERFORMA_TRANSACTIONMASTER
ADD [CHAADDR2] [varchar](100) NULL
GO

ALTER TABLE PERFORMA_TRANSACTIONMASTER
ADD [CHAADDR3] [varchar](100) NULL
GO

ALTER TABLE PERFORMA_TRANSACTIONMASTER
ADD [CHAADDR4] [varchar](100) NULL
GO

ALTER TABLE PERFORMA_TRANSACTIONMASTER
ADD [CHASTATEID] [int] NULL
GO


update PERFORMA_TRANSACTIONMASTER
set [CHASTATEID] = STATEID
where STATEID is not null
and [CHASTATEID] is null


update PERFORMA_TRANSACTIONMASTER
set [CHASTATEID] = 33
where  [CHASTATEID] is null