/*
EXEC pr_AutoPopulate_NonPNR_GO_DESTUFF_EMPTY_INSERT_GI 100, 34
*/
ALTER PROCEDURE [dbo].pr_AutoPopulate_NonPNR_GO_DESTUFF_EMPTY_INSERT_GI
@GODID		INT,
@COMPYID		INT
AS BEGIN
	DECLARE @EGIDID INT, @VTNO INT, @GIDID INT, @OLDEGIDID INT, @VTSTYPE INT, @VTTYPE INT

	SELECT @EGIDID = ISNULL(MAX(GIDID),0)+1 from GATEINDETAIL where COMPYID = @COMPYID and SDPTID = 3

	SELECT @VTNO = VTNO, @OLDEGIDID= EGIDID,  @VTSTYPE = VTSTYPE,  @VTTYPE = VTTYPE 
	from GATEOUTDETAIL JOIN VEHICLETICKETDETAIL  
			ON GATEOUTDETAIL.GIDID = VEHICLETICKETDETAIL.GIDID
			AND GATEOUTDETAIL.COMPYID = VEHICLETICKETDETAIL.COMPYID
			AND GATEOUTDETAIL.SDPTID = VEHICLETICKETDETAIL.SDPTID
	where GATEOUTDETAIL.COMPYID = @COMPYID and GATEOUTDETAIL.SDPTID = 9 
	and GODID = @GODID

	IF ISNULL(@OLDEGIDID,0) = 0 AND ISNULL(@VTSTYPE,0) = 1 AND ISNULL(@VTTYPE,0) = 2 
	BEGIN

		INSERT INTO GATEINDETAIL(GIDID, NGIDID, COMPYID, GIDATE, GITIME, GINO, GIDNO, CHAID,CHANAME,  SDPTID, CONTNRTID, CONTNRID, CONTNRSID, CONTNRNO,
		GIVHLTYPE,TRNSPRTID,TRNSPRTNAME, VHLNO, DRVNAME, GPREFNO, IMPRTID,IMPRTNAME, STMRID, STMRNAME, GTRNSPRTNAME,VHLMID, BCHAID , BCHANAME, GPMODEID,GPNRNO)
		select	@EGIDID, @EGIDID+1 , @COMPYID,  CONVERT(VARCHAR(10),GETDATE(),120), GETDATE(), @EGIDID, CAST(@EGIDID AS VARCHAR(50)), VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN.CHAID, 
				VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN.CHANAME, 3, GATEINDETAIL.CONTNRTID, GATEINDETAIL.CONTNRID, GATEINDETAIL.CONTNRSID, GATEINDETAIL.CONTNRNO,
				GATEINDETAIL.GIVHLTYPE,GATEINDETAIL.TRNSPRTID,GATEINDETAIL.TRNSPRTNAME, GATEINDETAIL.VHLNO, GATEINDETAIL.DRVNAME, GATEINDETAIL.GPREFNO, 
				GATEINDETAIL.IMPRTID,GATEINDETAIL.IMPRTNAME, GATEINDETAIL.STMRID, GATEINDETAIL.STMRNAME, GATEINDETAIL.GTRNSPRTNAME,GATEINDETAIL.VHLMID, GATEINDETAIL.BCHAID , 
				GATEINDETAIL.BCHANAME, 0, GATEINDETAIL.GPNRNO
		FROM VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN (nolock) JOIN GATEINDETAIL ON VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN.GIDID = GATEINDETAIL.GIDID
		AND VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN.COMPYID = GATEINDETAIL.COMPYID
		where VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN.COMPYID = @COMPYID and GODID = @GODID AND GATEINDETAIL.SDPTID = 9

		UPDATE VEHICLETICKETDETAIL SET EGIDID=@EGIDID WHERE VTDID=@VTNO  AND COMPYID = @COMPYID and SDPTID = 9 
	
		--Select 'Empty Gate In record Added for DeStuff - Gate OUT' 'result'
	END
END