/*

*/

ALTER PROCEDURE [dbo].pr_AutoPopulate_VT_to_GO
@VTID		INT,
@COMPYID		INT
AS BEGIN
	DECLARE @GODID INT
	SELECT @GODID = ISNULL(MAX(gidid),0)+1 from GATEINDETAIL where COMPYID = @COMPYID and SDPTID = 9

	IF EXISTS (SELECT '*' FROM VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN (nolock) where COMPYID = @COMPYID and VTNO = @vtid)
	begin
		INSERT INTO GATEOUTDETAIL(GODID, COMPYID, REGSTRID, GODATE, GOTIME, GONO, GODNO, GIDID, TRANDID, CHAID,CHASNAME, GOBTYPE, VHLNO, GDRVNAME, SDPTID)
		select	@GODID, @COMPYID,  1, CONVERT(VARCHAR(10),GETDATE(),120), GETDATE(), @GODID,CAST(@GODID AS VARCHAR(50)), GIDID, 0, CHAID, 
				CHANAME	 , ASLMTYPE, VHLNO, DRVNAME, 9
		FROM VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN (nolock) 
		where COMPYID = @COMPYID and VTNO = @vtid
	END
	--ELSE
	--BEGIN

		UPDATE A
		SET SDPTID = B.SDPTID, VHLNO = B.VHLNO, GDRVNAME = DRVNAME, GODATE = B.VTDATE, GOTIME = B.VTTIME, 
			LSEALNO = B.VTSSEALNO, 
			--SSEALNO, 
			CUSRID = B.CUSRID, LMUSRID = B.LMUSRID, DISPSTATUS= B.DISPSTATUS, 
			PRCSDATE = GETDATE(), GOQTY = B.VTQTY, 
			--OTDID, OTDNO, CONTNRFID, BOOKID, GOPLCNAME, GOBKGNO, GOEGMNO, OVSLID, OVSLNAME, OVOYNO, 
			--GOREMRKS = 'Auto Generated', 
			EHIDATE = convert(varchar(10), getdate(),120), 
			EHITIME = getdate() --, GOTRNSPRTNAME, GOTTYPE, GOOTYPE, GOCTYPE, EBLNO
		FROM GATEOUTDETAIL A, VEHICLETICKETDETAIL B(NOLOCK)
		WHERE A.COMPYID = @COMPYID 
		and A.GODID = @GODID
		AND A.COMPYID = B.COMPYID
		AND B.VTDID = @VTID
		AND B.SDPTID = 9
	--END
        
END