/*
 EXEC [pr_Bond_Invoice_BondNO_Grid_Assgn] @userid = 'ck', @PBNDID =1003, @PTRANMID = 0, @PSDATE = '2022-09-01', @PEDATE = '2022-09-29', @PBCHAID = 63371, @PBCATEAID = 2424, @PTARIFFMID = 5, @PSLABTID = 2, @PCHRGTYPE = 1, @PRDTID = 1, @PYRDID = 3, @POPRID 


= 1, @PHNDTID  = 0, @PCNTSID = 3, @PQTY  = 4, @PNOP = 50, @PRATE  = 45
 EXEC [pr_Bond_Invoice_BondNO_Grid_Assgn] @userid = 'ck', @PBNDID =1003, @PTRANMID = 0, @PSDATE = '2022-09-01', @PEDATE = '2022-09-29', @PBCHAID = 63371, @PBCATEAID = 2424, @PTARIFFMID = 5, @PSLABTID = 4, @PCHRGTYPE = 1, @PRDTID = 1, @PYRDID = 3, @POPRID 


= 2, @PHNDTID  = 0, @PCNTSID = 3, @PQTY  = 4, @PNOP = 12, @PRATE  = 50
 EXEC [pr_Bond_Invoice_BondNO_Grid_Assgn] @userid = 'ck', @PBNDID =1003, @PTRANMID = 0, @PSDATE = '2022-09-01', @PEDATE = '2022-09-30', @PBCHAID = 63371, @PBCATEAID = 2424, @PTARIFFMID = 2, @PSLABTID = 2, @PCHRGTYPE = 1, @PRDTID = 1, @PYRDID = 3, @POPRID 


= 1, @PHNDTID  = 0, @PCNTSID = 4, @PQTY  = 4.1, @PNOP = 50, @PRATE  = 50
 EXEC [pr_Bond_Invoice_BondNO_Grid_Assgn] @userid = 'ck', @PBNDID =1003, @PTRANMID = 0, @PSDATE = '2022-09-01', @PEDATE = '2022-09-29', @PBCHAID = 63371, @PBCATEAID = 2424, @PTARIFFMID = 2, @PSLABTID = 2, @PCHRGTYPE = 1, @PRDTID = 1, @PYRDID = 3, @POPRID 


= 1, @PHNDTID  = 0, @PCNTSID = 3, @PQTY  = 4, @PNOP = 50, @PRATE  = 25
 EXEC [pr_Bond_Invoice_BondNO_Grid_Assgn] @userid = 'ck', @PBNDID =1003, @PTRANMID = 3332, @PSDATE = '', @PEDATE = '', @PBCHAID = 63371, @PBCATEAID = 0, @PTARIFFMID = 0, @PSLABTID = 0, @PCHRGTYPE = 1, @PRDTID = 0, @PYRDID = 0, @POPRID = 0, @PHNDTID  = 0, 


@PCNTSID = 0, @PQTY  = 0, @PNOP = 0, @PRATE  = 0
 EXEC [pr_Bond_Invoice_BondNO_Grid_Assgn] @userid = 'ck', @PBNDID =1003, @PTRANMID = 3333, @PSDATE = '', @PEDATE = '', @PBCHAID = 63371, @PBCATEAID = 0, @PTARIFFMID = 0, @PSLABTID = 0, @PCHRGTYPE = 1, @PRDTID = 0, @PYRDID = 0, @POPRID = 0, @PHNDTID  = 0, 


@PCNTSID = 0, @PQTY  = 0, @PNOP = 0, @PRATE  = 0
*/
-- delete tmp_usr_bond_add_dtl
-- delete bondtransactionmaster
-- select * From tmp_usr_bond_add_dtl
-- select * from BONDMASTER
alter PROCEDURE [dbo].[pr_Bond_Invoice_BondNO_Grid_Assgn]  /* CHANGE */
		@userid varchar(50),
		@PBNDID int, 
		@PTRANMID INT,
		@PSDATE smalldatetime=null, 
		@PEDATE smalldatetime=null, 
		@PBCHAID INT=0, 
		@PBCATEAID INT=0, 
		@PTARIFFMID int=0, 
		@PSLABTID INT=0, 
		@PCHRGTYPE INT=0, 
		@PRDTID INT=0, 
		@PYRDID int=0, 
		@POPRID INT=0, 
		@PHNDTID INT=0, 
		@PCNTSID INT=0, 
--		@PRDTGID INT=0,
		@PQTY NUMERIC(18,2)=0, 
		@PNOP NUMERIC(18,2)=0, 
		@PRATE numeric(18,2)=0,
		@PAMT numeric(18,2)=0,
		@PTAXTYPE SMALLINT=1
AS BEGIN

    DECLARE @TableMaster TABLE
    ( 
	   TRANMID INT
	  ,BNDID INT 
	  ,TRANDBNDNO  VARCHAR(50)
	  ,EBNDID INT 
	  ,TRANDEBNDNO  VARCHAR(50)
	  ,TARIFFMID INT
	  ,TARIFFDESC varchar(50)
	  ,SLABTID INT
	  ,SLABTDESC varchar(50)
	  ,PERIODTID INT
	  ,PERIODTDESC varchar(50)
	  ,CONTNRSID INT
	  ,CONTNRSDESC VARCHAR(25)
	  ,YRDID INT
	  ,YRDDESC VARCHAR(50)
	  ,TRANCTYPE INT
	  ,TRANCTYPEDESC VARCHAR(25)
	  ,TRANOTYPE INT
	  ,TRANOTYPEDESC VARCHAR(25)
	  ,TRANHTYPE INT
	  ,TRANHTYPEDESC VARCHAR(25)
	  ,TRANCDATE varchar(12) 
	  ,TRANSFDATE varchar(12) 
	  ,TRANSEDATE varchar(12) 
	  ,TRANIFDATE varchar(12)  
	  ,TRANIEDATE varchar(12) 
	  ,STATETYPE int
	  ,TRANDNOP	NUMERIC(18,2)	  
	  ,TRANDQTY 	NUMERIC(18,2)
	  ,TRANDRATE 	NUMERIC(18,2)
	  ,TRANDWGHT 	NUMERIC(18,2)
	  ,TRANDID INT
	  ,TRANDCIFAMT NUMERIC(18,2)
	  ,TRANDDTYAMT NUMERIC(18,2)
	  ,TRANDINSAMT NUMERIC(18,2)
	  ,TRANDEIAMT NUMERIC(18,2)
	  ,TRANDGAMT NUMERIC(18,2)
	  ,TRANDSAMT NUMERIC(18,2)
	  ,TRANDHAMT NUMERIC(18,2)
	  ,TRANDIAMT NUMERIC(18,2)
	  ,TRANDFAMT NUMERIC(18,2)
	  ,TRANDPAMT NUMERIC(18,2)
	  ,TRANDNAMT NUMERIC(18,2)
	   ,TRAND_HSN_CODE VARCHAR(10)
	   ,INS_TRAND_HSN_CODE VARCHAR(10)
	   ,TRAND_TAXABLE_AMT  NUMERIC(18,2)
	   ,INS_TRAND_TAXABLE_AMT  NUMERIC(18,2)
	   ,TRAND_CGST_EXPRN  NUMERIC(18,2)
	 ,TRAND_SGST_EXPRN  NUMERIC(18,2)
	  ,TRAND_IGST_EXPRN  NUMERIC(18,2)
	   ,TRAND_CGST_AMT  NUMERIC(18,2)
	   ,TRAND_SGST_AMT  NUMERIC(18,2)
	   ,TRAND_IGST_AMT  NUMERIC(18,2)
	   ,INS_TRAND_CGST_EXPRN  NUMERIC(18,2)
	   ,INS_TRAND_SGST_EXPRN  NUMERIC(18,2)
	   ,INS_TRAND_IGST_EXPRN  NUMERIC(18,2)
	   ,INS_TRAND_CGST_AMT  NUMERIC(18,2)
	   ,INS_TRAND_SGST_AMT  NUMERIC(18,2)
	   ,INS_TRAND_IGST_AMT  NUMERIC(18,2)
    )


DECLARE @LBNDID int, @LEDATE smalldatetime, @LTRANMID INT, @amount numeric(18,2)
set @amount = @PAMT -- @PNOP*@pQTY*@PRATE
set @LBNDID =@PBNDID
set @LEDATE = @PEDATE
set @LTRANMID = @PTRANMID

--SELECT  * FROM @TableMaster
set nocount on

--PENDING BOND NO
if isnull(@PTRANMID,0)=0
begin
	delete tmp_usr_bond_add_dtl where userid = @userid AND  tariffmid = @PTARIFFMID and slabtid= @PSLABTID --TRANMID= @LTRANMID and

	INSERT INTO tmp_usr_bond_add_dtl(
	TRANDBNDNO,CONTNRSDESC,TRANCDATE,TRANSFDATE,TRANSEDATE,TRANIFDATE,TRANIEDATE,TRANMID,BNDID,SLABTID,TRANDNOP,TRANDQTY,
	TRANDRATE,	TRANDID,TRANDSAMT,TRANDHAMT,TRANDIAMT,TRANDNAMT, STATETYPE, TRAND_HSN_CODE, INS_TRAND_HSN_CODE ,
	TRAND_TAXABLE_AMT,INS_TRAND_TAXABLE_AMT,TRAND_CGST_EXPRN,TRAND_SGST_EXPRN,TRAND_IGST_EXPRN,TRAND_CGST_AMT,TRAND_SGST_AMT,
	TRAND_IGST_AMT,INS_TRAND_CGST_EXPRN,INS_TRAND_SGST_EXPRN,INS_TRAND_IGST_EXPRN,INS_TRAND_CGST_AMT,INS_TRAND_SGST_AMT,
	INS_TRAND_IGST_AMT,TRANDCIFAMT ,TRANDDTYAMT ,TRANDINSAMT,
		CONTNRSID,YRDID,TRANCTYPE,TRANOTYPE,TRANHTYPE, YRDDESC ,TRANCTYPEDESC ,TRANOTYPEDESC , TRANHTYPEDESC, EBNDID, TRANDEBNDNO ,
		TARIFFMID, TARIFFDESC ,  SLABTDESC , PERIODTID , PERIODTDESC, TRANDGAMT, userid
	)
    
	SELECT  dbo.BONDMASTER.BNDDNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, convert(varchar,@LEDATE,103),
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN NULL ELSE convert(varchar,@PSDATE,103) END AS TRANSFDATE, 
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN NULL ELSE convert(varchar,@LEDATE,103) END AS TRANSEDATE, 
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN convert(varchar,@PSDATE,103) ELSE NULL END AS TRANIFDATE, 
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN convert(varchar,@LEDATE,103)  ELSE NULL END AS TRANIEDATE, 
			@PTRANMID, dbo.BONDMASTER.BNDID, @PSLABTID,@PNOP,@pQTY,@PRATE,0,0,0,0,
			@amount+round(CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(CGSTEXPRN,0) ELSE isnull(ACGSTEXPRN,0) END/100*@amount,2)+
			round(CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(SGSTEXPRN,0) ELSE isnull(ASGSTEXPRN,0) END/100*@amount,2)+
			round(CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(IGSTEXPRN,0) ELSE isnull(AIGSTEXPRN,0) END/100*@amount,2),isnull(STATETYPE,0),isnull(HSNCODEMASTER.HSNCODE,''),'',
			@amount,0,CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(CGSTEXPRN,0) ELSE isnull(ACGSTEXPRN,0) END,
			CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(SGSTEXPRN,0) ELSE isnull(ASGSTEXPRN,0) END,
			CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(IGSTEXPRN,0) ELSE isnull(AIGSTEXPRN,0) END,
			round(CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(CGSTEXPRN,0) ELSE isnull(ACGSTEXPRN,0) END/100*@amount,2),
			round(CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(SGSTEXPRN,0) ELSE isnull(ASGSTEXPRN,0) END/100*@amount,2),
			round(CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(IGSTEXPRN,0) ELSE isnull(AIGSTEXPRN,0) END/100*@amount,2),0,0,0,0,0,0,
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN max(BONDMASTER.BNDCIFAMT) else 0 end,
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN max(BONDMASTER.BNDDTYAMT) else 0 end, 
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN max(BONDMASTER.BNDINSAMT) else 0 end,
			@PCNTSID,@PYRDID,@PCHRGTYPE,@POPRID,@PHNDTID,
			YRDDESC,CASE WHEN @PCHRGTYPE =1  THEN 'FCL' ELSE 'LCL' END ,
			CASE WHEN @POPRID = 1 THEN 'Manual' When @POPRID = 2 then 'Mechanical' When @POPRID = 3 then 'Both' else '' end,
			@PHNDTID,0,'',@PTARIFFMID, isnull(TARIFFMDESC,'') ,  SLABTDESC , 
			@PRDTID , case when @PRDTID = 1 then 'Weekly' else 'Daily' end,
			@amount, @userid
	FROM            dbo.VW_BOND_INVOICE_SBILL_NO_CBX_ASSGN_01 RIGHT OUTER JOIN     DBO.BONDMASTER ON
							 dbo.VW_BOND_INVOICE_SBILL_NO_CBX_ASSGN_01.BNDID = dbo.BONDMASTER.BNDID 
							 and dbo.VW_BOND_INVOICE_SBILL_NO_CBX_ASSGN_01.SLABTID = @PSLABTID RIGHT OUTER JOIN
							 dbo.CONTAINERSIZEMASTER ON dbo.CONTAINERSIZEMASTER.CONTNRSID = @PCNTSID RIGHT OUTER JOIN							 
							 dbo.CATEGORYMASTER ON  dbo.CATEGORYMASTER.CATEID = @PBCHAID RIGHT OUTER JOIN
							 dbo.CATEGORY_ADDRESS_DETAIL ON dbo.CATEGORYMASTER.CATEID = CATEGORY_ADDRESS_DETAIL.CATEID 
							 AND CATEGORY_ADDRESS_DETAIL.CATEAID=@PBCATEAID RIGHT JOIN 
							 dbo.STATEMASTER ON  CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID   INNER JOIN
							 BONDSLABTYPEMASTER ON BONDSLABTYPEMASTER.SLABTID = @PSLABTID left JOIN
							 HSNCODEMASTER ON BONDSLABTYPEMASTER.HSNID = HSNCODEMASTER.HSNID INNER JOIN
							 BONDTARIFFMASTER ON BONDTARIFFMASTER.TARIFFMID = @PTARIFFMID INNER JOIN
							 BONDYARDMASTER ON BONDYARDMASTER.YRDID = @PYRDID 
							 --INNER JOIN
							 --BONDPRODUCTGROUPMASTER ON BONDPRODUCTGROUPMASTER.PRDTGID = @PRDTGID 
						 
							 --BONDYARDMASTER ON BONDYARDMASTER.YRDID = @PYRDID
	WHERE     ((ISNULL(dbo.VW_BOND_INVOICE_SBILL_NO_CBX_ASSGN_01.TRANDID, 0) = 0)
	or (ISNULL(dbo.VW_BOND_INVOICE_SBILL_NO_CBX_ASSGN_01.SLABTID, 0) = 0))
	AND (dbo.BONDMASTER.BNDID = @LBNDID)
	GROUP BY dbo.BONDMASTER.BNDID, dbo.BONDMASTER.BNDDNO, dbo.BONDMASTER.BNDID, 
	dbo.VW_BOND_INVOICE_SBILL_NO_CBX_ASSGN_01.SLABTID,  dbo.CONTAINERSIZEMASTER.CONTNRSDESC, isnull(STATETYPE,0) ,
	BONDSLABTYPEMASTER.SLABTDESC, YRDDESC, TARIFFMDESC, SLABTDESC, isnull(HSNCODEMASTER.HSNCODE,''),
	CGSTEXPRN, ACGSTEXPRN, SGSTEXPRN,ASGSTEXPRN, IGSTEXPRN, AIGSTEXPRN

	
	INSERT INTO @TableMaster(
	TRANDBNDNO,CONTNRSDESC,TRANCDATE,TRANSFDATE,TRANSEDATE,TRANIFDATE,TRANIEDATE,TRANMID,BNDID,SLABTID,TRANDNOP,TRANDQTY, TRANDRATE,
	TRANDID,TRANDSAMT,TRANDHAMT,TRANDIAMT,TRANDNAMT, STATETYPE, TRAND_HSN_CODE, INS_TRAND_HSN_CODE ,TRAND_TAXABLE_AMT,
		INS_TRAND_TAXABLE_AMT,TRAND_CGST_EXPRN,TRAND_SGST_EXPRN,TRAND_IGST_EXPRN,TRAND_CGST_AMT,TRAND_SGST_AMT,
		TRAND_IGST_AMT,INS_TRAND_CGST_EXPRN,INS_TRAND_SGST_EXPRN,INS_TRAND_IGST_EXPRN,INS_TRAND_CGST_AMT,INS_TRAND_SGST_AMT,
		INS_TRAND_IGST_AMT,TRANDCIFAMT ,TRANDDTYAMT ,TRANDINSAMT,
		CONTNRSID,YRDID,TRANCTYPE,TRANOTYPE,TRANHTYPE, YRDDESC ,TRANCTYPEDESC ,TRANOTYPEDESC , TRANHTYPEDESC, EBNDID, TRANDEBNDNO ,
		TARIFFMID, TARIFFDESC ,  SLABTDESC , PERIODTID , PERIODTDESC,TRANDGAMT
	)
	select TRANDBNDNO,CONTNRSDESC,TRANCDATE,TRANSFDATE,TRANSEDATE,TRANIFDATE,TRANIEDATE,TRANMID,BNDID,SLABTID,TRANDNOP,TRANDQTY, TRANDRATE,
	TRANDID,TRANDSAMT,TRANDHAMT,TRANDIAMT,TRANDNAMT, STATETYPE, TRAND_HSN_CODE, INS_TRAND_HSN_CODE ,TRAND_TAXABLE_AMT,
		INS_TRAND_TAXABLE_AMT,TRAND_CGST_EXPRN,TRAND_SGST_EXPRN,TRAND_IGST_EXPRN,TRAND_CGST_AMT,TRAND_SGST_AMT,
		TRAND_IGST_AMT,INS_TRAND_CGST_EXPRN,INS_TRAND_SGST_EXPRN,INS_TRAND_IGST_EXPRN,INS_TRAND_CGST_AMT,INS_TRAND_SGST_AMT,
		INS_TRAND_IGST_AMT,TRANDCIFAMT ,TRANDDTYAMT ,TRANDINSAMT,
		CONTNRSID,YRDID,TRANCTYPE,TRANOTYPE,TRANHTYPE, YRDDESC ,TRANCTYPEDESC ,TRANOTYPEDESC , TRANHTYPEDESC, EBNDID, TRANDEBNDNO ,
		TARIFFMID, TARIFFDESC ,  SLABTDESC , PERIODTID , PERIODTDESC,TRANDGAMT 
	from tmp_usr_bond_add_dtl (nolock)
	where userid = @userid
end
else
begin
	delete tmp_usr_bond_add_dtl where userid = @userid and tranmid = @LTRANMID 
end
----ACTUAL BOND INVOICE DETAIL

INSERT INTO @TableMaster(
TRANDBNDNO,CONTNRSDESC,TRANCDATE,TRANSFDATE,TRANSEDATE,TRANIFDATE,TRANIEDATE,TRANMID,BNDID,SLABTID,TRANDNOP,TRANDQTY, TRANDRATE,
TRANDID,TRANDSAMT,TRANDHAMT,TRANDIAMT,TRANDNAMT, STATETYPE, TRAND_HSN_CODE, INS_TRAND_HSN_CODE ,TRAND_TAXABLE_AMT,
	INS_TRAND_TAXABLE_AMT,TRAND_CGST_EXPRN,TRAND_SGST_EXPRN,TRAND_IGST_EXPRN,TRAND_CGST_AMT,TRAND_SGST_AMT,
	TRAND_IGST_AMT,INS_TRAND_CGST_EXPRN,INS_TRAND_SGST_EXPRN,INS_TRAND_IGST_EXPRN,INS_TRAND_CGST_AMT,INS_TRAND_SGST_AMT,
	INS_TRAND_IGST_AMT,TRANDCIFAMT ,TRANDDTYAMT ,TRANDINSAMT,
	CONTNRSID,YRDID,TRANCTYPE,TRANOTYPE,TRANHTYPE, YRDDESC ,TRANCTYPEDESC ,TRANOTYPEDESC , TRANHTYPEDESC, EBNDID, TRANDEBNDNO ,
	TARIFFMID, TARIFFDESC ,  SLABTDESC , PERIODTID , PERIODTDESC,TRANDGAMT
)

SELECT     dbo.BONDTRANSACTIONDETAIL.TRANDBNDNO AS TRANDBNDNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC,
			convert(varchar,dbo.BONDTRANSACTIONDETAIL.TRANCDATE,103) , convert(varchar,dbo.BONDTRANSACTIONDETAIL.TRANSFDATE,103) , 
			convert(varchar,dbo.BONDTRANSACTIONDETAIL.TRANSEDATE,103) , convert(varchar,dbo.BONDTRANSACTIONDETAIL.TRANIFDATE,103) , 
                      convert(varchar,dbo.BONDTRANSACTIONDETAIL.TRANIEDATE,103) ,
					  dbo.BONDTRANSACTIONMASTER.TRANMID, dbo.BONDTRANSACTIONDETAIL.BNDID, 
                      dbo.BONDTRANSACTIONDETAIL.SLABTID, dbo.BONDTRANSACTIONDETAIL.TRANDNOP AS TRANDNOP, dbo.BONDTRANSACTIONDETAIL.TRANDQTY AS TRANDQTY, 
					  dbo.BONDTRANSACTIONDETAIL.TRANDRATE AS TRANDRATE, dbo.BONDTRANSACTIONDETAIL.TRANDID, dbo.BONDTRANSACTIONDETAIL.TRANDSAMT, 
					  dbo.BONDTRANSACTIONDETAIL.TRANDHAMT, dbo.BONDTRANSACTIONDETAIL.TRANDIAMT, dbo.BONDTRANSACTIONDETAIL.TRANDNAMT, isnull(BONDTRANSACTIONDETAIL.STATETYPE,0), 
					  dbo.BONDTRANSACTIONDETAIL.TRAND_HSN_CODE, '', dbo.BONDTRANSACTIONDETAIL.TRANDGAMT, 0, TRAND_CGST_EXPRN, TRAND_SGST_EXPRN, TRAND_IGST_EXPRN, 
					  TRAND_CGST_AMT, TRAND_SGST_AMT, TRAND_IGST_AMT, 0, 0, 0, INS_TRAND_CGST_AMT, 
					  INS_TRAND_SGST_AMT, INS_TRAND_IGST_AMT,
					  (BONDTRANSACTIONDETAIL.TRANDCIFAMT), (BONDTRANSACTIONDETAIL.TRANDDTYAMT), (BONDTRANSACTIONDETAIL.TRANDINSAMT),
					  dbo.BONDTRANSACTIONDETAIL.CONTNRSID,dbo.BONDTRANSACTIONDETAIL.YRDID,dbo.BONDTRANSACTIONDETAIL.TRANCTYPE,
					  dbo.BONDTRANSACTIONDETAIL.TRANOTYPE,dbo.BONDTRANSACTIONDETAIL.TRANHTYPE, YRDDESC,
					  CASE WHEN dbo.BONDTRANSACTIONDETAIL.TRANCTYPE =1  THEN 'FCL' ELSE 'LCL' END ,
					  CASE WHEN dbo.BONDTRANSACTIONDETAIL.TRANOTYPE = 1 THEN 'Manual' When dbo.BONDTRANSACTIONDETAIL.TRANOTYPE = 2 then 'Mechanical' 
					  When dbo.BONDTRANSACTIONDETAIL.TRANOTYPE = 3 then 'Both' else '' end,
					  @PHNDTID,EBNDID,TRANDEBNDNO,dbo.BONDTRANSACTIONDETAIL.TARIFFMID , isnull(TARIFFMDESC,'') , 
					  SLABTDESC , 
						  dbo.BONDTRANSACTIONDETAIL.PERIODTID , case when  dbo.BONDTRANSACTIONDETAIL.PERIODTID = 1 then 'Weekly' else 'Daily' end,
						  TRANDGAMT
FROM            dbo.BONDTRANSACTIONDETAIL INNER JOIN
                         dbo.BONDTRANSACTIONMASTER ON dbo.BONDTRANSACTIONDETAIL.TRANMID = dbo.BONDTRANSACTIONMASTER.TRANMID INNER JOIN
                         --dbo.BONDMASTER ON dbo.BONDTRANSACTIONDETAIL.BNDID = dbo.BONDMASTER.BNDID INNER JOIN
                         dbo.CONTAINERSIZEMASTER ON dbo.BONDTRANSACTIONDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID LEFT JOIN
						 dbo.CATEGORYMASTER ON BONDTRANSACTIONMASTER.BILLREFID= dbo.CATEGORYMASTER.CATEID LEFT join
                         dbo.BONDSLABTYPEMASTER ON dbo.BONDTRANSACTIONDETAIL.SLABTID = dbo.BONDSLABTYPEMASTER.SLABTID LEFT JOIN
						 dbo.BONDTARIFFMASTER ON dbo.BONDTRANSACTIONDETAIL.TARIFFMID = dbo.BONDTARIFFMASTER.TARIFFMID LEFT JOIN
                         dbo.BONDYARDMASTER ON dbo.BONDTRANSACTIONDETAIL.YRDID = dbo.BONDYARDMASTER.YRDID LEFT JOIN
                         dbo.CATEGORY_ADDRESS_DETAIL ON dbo.BONDTRANSACTIONMASTER.BCATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID LEFT OUTER JOIN 						 
                         dbo.STATEMASTER ON dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID
WHERE     (dbo.BONDTRANSACTIONMASTER.SDPTID = 10) 
AND TRANTID = 2
AND (dbo.BONDTRANSACTIONDETAIL.TRANMID = @LTRANMID)             

SELECT 
TRANDBNDNO,CONTNRSDESC,TRANCDATE,TRANSFDATE,TRANSEDATE,TRANIFDATE,TRANIEDATE,TRANMID,BNDID,SLABTID,TRANDNOP,TRANDQTY, TRANDRATE,
TRANDID,TRANDSAMT,TRANDHAMT,TRANDIAMT,TRANDNAMT, STATETYPE, TRAND_HSN_CODE, INS_TRAND_HSN_CODE ,TRAND_TAXABLE_AMT,
	INS_TRAND_TAXABLE_AMT,TRAND_CGST_EXPRN,TRAND_SGST_EXPRN,TRAND_IGST_EXPRN,TRAND_CGST_AMT,TRAND_SGST_AMT,
	TRAND_IGST_AMT,INS_TRAND_CGST_EXPRN,INS_TRAND_SGST_EXPRN,INS_TRAND_IGST_EXPRN,INS_TRAND_CGST_AMT,INS_TRAND_SGST_AMT,
	INS_TRAND_IGST_AMT,TRANDCIFAMT ,TRANDDTYAMT ,TRANDINSAMT,
	CONTNRSID,YRDID,TRANCTYPE,TRANOTYPE,TRANHTYPE, YRDDESC ,TRANCTYPEDESC ,TRANOTYPEDESC , TRANHTYPEDESC, EBNDID, TRANDEBNDNO ,
	TARIFFMID, TARIFFDESC ,  SLABTDESC , PERIODTID , PERIODTDESC,TRANDGAMT
FROM @TableMaster order by TRANCDATE, TRANDBNDNO, TRANDEBNDNO

return 
       
END

