alter PROCEDURE [dbo].[PR_BondSlabDuplicateCheck]
	@PSLABMDATE DATETIME,
	@PTARIFFMID int,
	@PCHRGETYPE int,
	@PCONTNRSID int,
	@PSDTYPE int,
	@PYRDTYPE int,
	@PWTYPE int,
	@PHTYPE int,
	@PHANDTYPE int,	
	@PCHAID int,
	@PSLABTID int,
	@CNT int output
AS
BEGIN

	SET NOCOUNT ON;
	SELECT @CNT =COUNT(*) FROM BONDSLABMASTER (nolock) 
	WHERE (SLABMDATE=@PSLABMDATE ) 
	AND (TARIFFMID=@PTARIFFMID) AND (CHRGETYPE=@PCHRGETYPE) 
	AND (CONTNRSID=@PCONTNRSID) AND (SDTYPE=@PSDTYPE) 
	AND (YRDTYPE=@PYRDTYPE) 
	AND (WTYPE=@PWTYPE) AND (HTYPE=@PHTYPE) 
	AND (CHAID=@PCHAID) AND (SLABTID=@PSLABTID)
	and HANDTYPE = @PHANDTYPE
	SELECT @CNT
	
	RETURN
END
