-- PR_DORDER_IGMNO_BOE_NO_CTRL_ASSGN_E001 @PIGMNO='2291844',@PGPLNO='472'
ALTER PROCEDURE [dbo].[PR_DORDER_IGMNO_BOE_NO_CTRL_ASSGN_E001] @PIGMNO VARCHAR(20), @PGPLNO VARCHAR(10)
AS

	SET NOCOUNT ON;

	DECLARE @LIGMNO VARCHAR(20), @LGPLNO VARCHAR(10)
	SET @LIGMNO = @PIGMNO
	SET @LGPLNO = @PGPLNO

    DECLARE @TableMaster TABLE
    ( 
	   GIDID  INT
    )

	INSERT INTO @TableMaster(GIDID)
    SELECT GIDID FROM GATEINDETAIL WHERE SDPTID = 1 AND IGMNO = @PIGMNO AND GPLNO = @PGPLNO ORDER BY GIDID

	SELECT     TOP (100) PERCENT dbo.BILLENTRYMASTER.COMPYID, dbo.BILLENTRYMASTER.SDPTID, dbo.BILLENTRYMASTER.BILLEMID, 
                      dbo.BILLENTRYMASTER.BILLEMDNO, dbo.BILLENTRYMASTER.DPAIDNO, dbo.BILLENTRYMASTER.DPAIDAMT,
					  dbo.OPENSHEETMASTER.OSBILLREFID as CHAID, dbo.OPENSHEETMASTER.OSBILLREFNAME AS BILLEMNAME, ISNULL(dbo.VEHICLETICKETDETAIL.VTDID, 0)
	FROM         dbo.BILLENTRYMASTER INNER JOIN
                      dbo.BILLENTRYDETAIL ON dbo.BILLENTRYMASTER.BILLEMID = dbo.BILLENTRYDETAIL.BILLEMID INNER JOIN
                      dbo.GATEINDETAIL ON dbo.BILLENTRYDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                      dbo.OPENSHEETDETAIL ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.OPENSHEETDETAIL.BILLEDID INNER JOIN
					  dbo.OPENSHEETMASTER ON OPENSHEETDETAIL.OSMID = dbo.OPENSHEETMASTER.OSMID LEFT OUTER JOIN
                      -- inner join dbo.ENDORSEMENT_DETAIL ON dbo.GATEINDETAIL.GIDID = dbo.ENDORSEMENT_DETAIL.GIDID LEFT OUTER JOIN
                      dbo.VW_TAB5_DO_FLX_ASSGN_01 ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.VW_TAB5_DO_FLX_ASSGN_01.BILLEDID LEFT OUTER JOIN
                      dbo.VEHICLETICKETDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.VEHICLETICKETDETAIL.GIDID LEFT OUTER JOIN
                      dbo.DELIVERYORDERDETAIL ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.DELIVERYORDERDETAIL.BILLEDID 
					  INNER JOIN @TableMaster tmp001 ON dbo.GATEINDETAIL.GIDID = tmp001.GIDID
	WHERE     (dbo.BILLENTRYMASTER.SDPTID = 1) AND (ISNULL(dbo.DELIVERYORDERDETAIL.DODID, 0) = 0) 
						AND (ISNULL(dbo.VEHICLETICKETDETAIL.VTDID, 0) = 0) 
						AND (ISNULL(dbo.VW_TAB5_DO_FLX_ASSGN_01.TRANDID, 0) = 0) 
					  AND (dbo.GATEINDETAIL.IGMNO = @LIGMNO) AND (dbo.GATEINDETAIL.GPLNO = @LGPLNO) AND 
                      (dbo.OPENSHEETDETAIL.INSPTYPE = 1)
	GROUP BY dbo.BILLENTRYMASTER.COMPYID, dbo.BILLENTRYMASTER.SDPTID, dbo.BILLENTRYMASTER.BILLEMID, dbo.BILLENTRYMASTER.BILLEMDNO, 
                      dbo.BILLENTRYMASTER.DPAIDNO, dbo.BILLENTRYMASTER.DPAIDAMT, 
					  --dbo.BILLENTRYMASTER.CHAID, dbo.BILLENTRYMASTER.BILLEMNAME, 
					  dbo.OPENSHEETMASTER.OSBILLREFID, dbo.OPENSHEETMASTER.OSBILLREFNAME,
                      dbo.BILLENTRYMASTER.DPAIDNO, dbo.BILLENTRYMASTER.DPAIDAMT, ISNULL(dbo.VEHICLETICKETDETAIL.VTDID, 0)
ORDER BY dbo.BILLENTRYMASTER.BILLEMDNO



