-- exec [PR_DORDER_IGMNO_BILLENTRY_WISE_CONTAINER_FLX_ASSGN] '0', '0'
alter PROCEDURE [dbo].[PR_DORDER_IGMNO_BILLENTRY_WISE_CONTAINER_FLX_ASSGN] @PIGMNO VARCHAR(20), @PGPLNO VARCHAR(10)

AS

set nocount on

    
DECLARE @LIGMNO VARCHAR(20), @LGPLNO VARCHAR(10), @LOSMID int
SET @LIGMNO = @PIGMNO
SET @LGPLNO = @PGPLNO

delete from TMP_DO_OPENSHEET_GIDID;

INSERT INTO TMP_DO_OPENSHEET_GIDID(BILLEMID)
--SELECT GIDID FROM GATEINDETAIL WHERE  (IGMNO = @LIGMNO) AND (GPLNO = @LGPLNO)
--select osmid from OPENSHEETMASTER where OSMIGMNO = @LIGMNO AND OSMLNO = @LGPLNO
SELECT  BILLENTRYDETAIL.BILLEMID FROM  GATEINDETAIL INNER JOIN
                      BILLENTRYDETAIL ON GATEINDETAIL.GIDID = BILLENTRYDETAIL.GIDID
WHERE     (GATEINDETAIL.IGMNO = @LIGMNO) AND (GATEINDETAIL.GPLNO = @LGPLNO)
GROUP BY dbo.BILLENTRYDETAIL.BILLEMID

SELECT     TOP (100) PERCENT dbo.BILLENTRYMASTER.BILLEMID, dbo.BILLENTRYDETAIL.BILLEDID, dbo.BILLENTRYDETAIL.GIDID, 
                      dbo.BILLENTRYMASTER.BILLEMNO, dbo.BILLENTRYMASTER.BILLEMDNO, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, 
                      dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.GIDATE, 
                      dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN.XGIDATE AS STRGDATE, dbo.GATEOUTDETAIL.GODATE, dbo.GATEOUTDETAIL.GOTIME, 
                      dbo.OPENSHEETMASTER.DODATE, dbo.GATEINDETAIL.STMRID, dbo.GATEINDETAIL.CONTNRSID, dbo.GATEINDETAIL.GPEAMT, 
                      dbo.GATEINDETAIL.GPWGHT, dbo.GATEINDETAIL.GPAAMT, dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.IMPRTNAME, 
                      dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, dbo.GATEINDETAIL.PRDTDESC
FROM         dbo.OPENSHEETMASTER INNER JOIN
                      dbo.BILLENTRYMASTER INNER JOIN
                      dbo.BILLENTRYDETAIL ON dbo.BILLENTRYMASTER.BILLEMID = dbo.BILLENTRYDETAIL.BILLEMID INNER JOIN
                      dbo.GATEINDETAIL ON dbo.BILLENTRYDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                      dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN ON 
                      dbo.BILLENTRYMASTER.BILLEMID = dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN.BILLEMID INNER JOIN
                      dbo.OPENSHEETDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.OPENSHEETDETAIL.GIDID ON 
                      dbo.OPENSHEETMASTER.OSMID = dbo.OPENSHEETDETAIL.OSMID INNER JOIN
                      dbo.TMP_DO_OPENSHEET_GIDID ON dbo.BILLENTRYMASTER.BILLEMID = dbo.TMP_DO_OPENSHEET_GIDID.BILLEMID AND 
                      dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN.BILLEMID = dbo.TMP_DO_OPENSHEET_GIDID.BILLEMID LEFT OUTER JOIN
                      dbo.DELIVERYORDERDETAIL ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.DELIVERYORDERDETAIL.BILLEDID LEFT OUTER JOIN
                      dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID
WHERE     (dbo.BILLENTRYMASTER.SDPTID = 1) AND (ISNULL(dbo.DELIVERYORDERDETAIL.DODID, 0) = 0) AND (dbo.GATEINDETAIL.IGMNO = @LIGMNO) AND 
                      (dbo.GATEINDETAIL.GPLNO = @LGPLNO) AND (dbo.OPENSHEETDETAIL.INSPTYPE = 1) 
ORDER BY dbo.BILLENTRYMASTER.BILLEMID
/*
SELECT   dbo.BILLENTRYMASTER.BILLEMID, dbo.BILLENTRYDETAIL.BILLEDID, dbo.BILLENTRYDETAIL.GIDID, 
                      dbo.BILLENTRYMASTER.BILLEMNO, dbo.BILLENTRYMASTER.BILLEMDNO, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, 
                      dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.GIDATE, 
                      dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN.XGIDATE AS STRGDATE, dbo.GATEOUTDETAIL.GODATE, dbo.GATEOUTDETAIL.GOTIME, 
                      dbo.OPENSHEETMASTER.DODATE, dbo.GATEINDETAIL.STMRID, dbo.GATEINDETAIL.CONTNRSID, dbo.GATEINDETAIL.GPEAMT, 
                      dbo.GATEINDETAIL.GPWGHT, dbo.GATEINDETAIL.GPAAMT, dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.IMPRTNAME, 
                      dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, dbo.GATEINDETAIL.PRDTDESC
FROM         dbo.OPENSHEETMASTER INNER JOIN
                      dbo.BILLENTRYMASTER INNER JOIN
                      dbo.BILLENTRYDETAIL ON dbo.BILLENTRYMASTER.BILLEMID = dbo.BILLENTRYDETAIL.BILLEMID INNER JOIN
                      dbo.GATEINDETAIL ON dbo.BILLENTRYDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                      dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN ON 
                      dbo.BILLENTRYMASTER.BILLEMID = dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN.BILLEMID INNER JOIN
                      dbo.OPENSHEETDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.OPENSHEETDETAIL.GIDID ON 
                      dbo.OPENSHEETMASTER.OSMID = dbo.OPENSHEETDETAIL.OSMID LEFT OUTER JOIN
                      dbo.VW_TAB5_DO_FLX_ASSGN_01 ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.VW_TAB5_DO_FLX_ASSGN_01.BILLEDID LEFT OUTER JOIN
                      dbo.DELIVERYORDERDETAIL ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.DELIVERYORDERDETAIL.BILLEDID LEFT OUTER JOIN
                      dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID
WHERE     (dbo.BILLENTRYMASTER.SDPTID = 1) AND (ISNULL(dbo.DELIVERYORDERDETAIL.DODID, 0) = 0) AND (IGMNO = @LIGMNO) AND (GPLNO = @LGPLNO) AND 
		 (dbo.OPENSHEETDETAIL.INSPTYPE = 1) AND (ISNULL(dbo.VW_TAB5_DO_FLX_ASSGN_01.TRANDID, 0) = 0)

ORDER BY dbo.BILLENTRYMASTER.BILLEMID
*/



