-- EXEC [pr_ESeal_Invoice_Grid_Assgn] '122', '1', 2
-- EXEC [pr_ESeal_Invoice_Grid_Assgn] 0,'','',1044,0 
alter PROCEDURE [dbo].[pr_ESeal_Invoice_Grid_Assgn]  /* CHANGE */
		@CHAID Int, @fromdate Smalldatetime,@todate Smalldatetime, @PTRANMID Int,@CATEAID Int
 
AS BEGIN

    DECLARE @TableMaster TABLE
    ( 
	   TRANREFID INT
	  ,TRANREFNAME VARCHAR(100)
	  ,BOENO VARCHAR(25)
	  ,BILLEMID INT
	  ,BILLEDID INT 
	  ,GIDID INT
	  ,STMRID INT
	  ,STMRNAME VARCHAR(100)
	  ,IGMNO VARCHAR(25)
	  ,GPLNO VARCHAR(10)
	  ,CONTNRNO  VARCHAR(15)
	  ,CONTNRSDESC VARCHAR(15)
	  ,CONTNRSID INT
	  ,GIDATE SMALLDATETIME 
	  ,STRGDATE SMALLDATETIME 
	  ,GODATE SMALLDATETIME
	  ,GOTIME DATETIME
	  ,DODATE SMALLDATETIME
	  ,NOD	NUMERIC(18,2)
	  ,WGHT 	NUMERIC(18,4)
	  ,PRDTGID INT
	  ,TRANDID INT
	  ,TRANDOTYPE SMALLINT
	  ,TARIFFMID INT
	  ,DPAIDNO VARCHAR(50)
	  ,DPAIDAMT NUMERIC(18, 2)
	  ,GPEAMT NUMERIC(18, 2)
	  ,GPCSAMT NUMERIC(18, 2)
	  ,GPLBAMT NUMERIC(18, 2)
	  ,GPAAMT  NUMERIC(18, 2)
	  ,TRANDSAMT NUMERIC(18,2)
	  ,TRANDHAMT NUMERIC(18,2)
	  ,TRANDEAMT NUMERIC(18,2)
	  ,TRANDFAMT NUMERIC(18,2)
	  ,TRANDAAMT NUMERIC(18,2)
	  ,TRANDNAMT NUMERIC(18,2)
	  ,RCOL1  NUMERIC(18,2)
	  ,RCOL2  NUMERIC(18,2)
	  ,RCOL3  NUMERIC(18,2)
	  ,RCOL4  NUMERIC(18,2)
	  ,RCOL5  NUMERIC(18,2)
	  ,RCOL6  NUMERIC(18,2)
	  ,RCOL7  NUMERIC(18,2)
	  ,RAMT1  NUMERIC(18,2)
	  ,RAMT2  NUMERIC(18,2)
	  ,RAMT3  NUMERIC(18,2)
	  ,RAMT4  NUMERIC(18,2)
	  ,RAMT5  NUMERIC(18,2)
	  ,RAMT6  NUMERIC(18,2)
	  ,RAMT7  NUMERIC(18,2)
	  ,RCAMT1  NUMERIC(18,2)
	  ,RCAMT2  NUMERIC(18,2)
	  ,RCAMT3  NUMERIC(18,2)
	  ,RCAMT4  NUMERIC(18,2)
	  ,RCAMT5  NUMERIC(18,2)
	  ,RCAMT6  NUMERIC(18,2)
	  ,RCAMT7  NUMERIC(18,2)
	   ,GPETYPE smallint
	   ,GPCSTYPE smallint
	   ,GPLBTYPE smallint
	  ,GPSTYPE smallint
	  ,GPWTYPE smallint
	  ,GPSCNTYPE smallint
	   ,TRANDRATE  NUMERIC(18,2)
	   , STATETYPE smallint
	   , STRG_HSN_CODE VARCHAR(10)
	   , HANDL_HSN_CODE VARCHAR(10)
	   ,STRG_TAXABLE_AMT  NUMERIC(18,2)
	   ,HANDL_TAXABLE_AMT  NUMERIC(18,2)
	   ,STRG_CGST_EXPRN  NUMERIC(18,2)
	   ,STRG_SGST_EXPRN  NUMERIC(18,2)
	   ,STRG_IGST_EXPRN  NUMERIC(18,2)
	   ,STRG_CGST_AMT  NUMERIC(18,2)
	   ,STRG_SGST_AMT  NUMERIC(18,2)
	   ,STRG_IGST_AMT  NUMERIC(18,2)
	   ,HANDL_CGST_EXPRN  NUMERIC(18,2)
	   ,HANDL_SGST_EXPRN  NUMERIC(18,2)
	   ,HANDL_IGST_EXPRN  NUMERIC(18,2)
	   ,HANDL_CGST_AMT  NUMERIC(18,2)
	   ,HANDL_SGST_AMT  NUMERIC(18,2)
	   ,HANDL_IGST_AMT  NUMERIC(18,2)
	   ,TRANCGSTAMT  NUMERIC(18,2)
	   ,TRANSGSTAMT  NUMERIC(18,2)
	   ,TRANIGSTAMT  NUMERIC(18,2)
	   ,TRAND_COVID_DISC_AMT NUMERIC(18,2)
    )


		   
DECLARE @LCHAID int,   @LSDate Smalldatetime, @LEDate Smalldatetime,  @LTRANMID INT ,@LCATEAID INT
set @LCHAID =@CHAID
set @LSDate = @fromdate
set @LEDate = @todate
set @LTRANMID = @PTRANMID 
set @LCATEAID = @CATEAID 
set nocount on


IF @LTRANMID  = 0  

	INSERT INTO @TableMaster(TRANREFID,TRANREFNAME,BOENO,BILLEMID,BILLEDID,GIDID,STMRID,STMRNAME,IGMNO,GPLNO,CONTNRNO,CONTNRSDESC,CONTNRSID,GIDATE,
	STRGDATE,GODATE,GOTIME,DODATE,NOD,WGHT,PRDTGID,TRANDID,TRANDOTYPE,TARIFFMID,DPAIDNO,DPAIDAMT,GPEAMT,GPCSAMT,GPLBAMT,GPAAMT,TRANDSAMT,TRANDHAMT,
	TRANDEAMT,TRANDFAMT,TRANDAAMT,TRANDNAMT,RCOL1,RCOL2,RCOL3,RCOL4,RCOL5,RCOL6,RCOL7,RAMT1,RAMT2,RAMT3,RAMT4,RAMT5,RAMT6,RAMT7,RCAMT1,RCAMT2,
	RCAMT3,RCAMT4,RCAMT5,RCAMT6,RCAMT7,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,TRANDRATE, STATETYPE, STRG_HSN_CODE, HANDL_HSN_CODE ,STRG_TAXABLE_AMT,
	HANDL_TAXABLE_AMT,STRG_CGST_EXPRN,STRG_SGST_EXPRN,STRG_IGST_EXPRN,STRG_CGST_AMT,STRG_SGST_AMT,
	STRG_IGST_AMT,HANDL_CGST_EXPRN,HANDL_SGST_EXPRN,HANDL_IGST_EXPRN,HANDL_CGST_AMT,HANDL_SGST_AMT,
	HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT)
	
	SELECT DISTINCT 
						  dbo.GATEINDETAIL.CHAID, dbo.GATEINDETAIL.CHANAME, '', 0 as BILLEMID, 0 as BILLEDID,
						  dbo.GATEOUTDETAIL.GIDID, dbo.GATEINDETAIL.STMRID,GATEINDETAIL.STMRNAME,'' as IGMNO, '' as GPLNO, dbo.GATEINDETAIL.CONTNRNO, 
						  dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.CONTNRSID, dbo.GATEINDETAIL.GIDATE, 
						  dbo.VW_ESEAL_BILL_MAX_GIDATE_ASSGN.XGIDATE AS STRGDATE, dbo.GATEOUTDETAIL.GODATE, dbo.GATEOUTDETAIL.GOTIME, 
						  getdate() as DODATE,0 AS NOD, dbo.GATEINDETAIL.GPWGHT, dbo.GATEINDETAIL.PRDTGID, 0 AS TRANDID, 0 AS TRANDOTYPE, 0 AS TARIFFMID, 
						  0 as DPAIDNO, 0 as DPAIDAMT, dbo.GATEINDETAIL.GPEAMT, dbo.GATEINDETAIL.GPCSAMT,dbo.GATEINDETAIL.GPLBAMT, dbo.GATEINDETAIL.GPAAMT,
						  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,0, 
						  STATEMASTER.STATETYPE as STATETYPE,
						  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0  
						 -- SELECT *
		FROM GATEINDETAIL (nolock) Inner Join 
		VW_ESEAL_BILL_MAX_GIDATE_ASSGN (nolock) on GATEINDETAIL.GIDID = VW_ESEAL_BILL_MAX_GIDATE_ASSGN.GIDID inner join
		GATEOUTDETAIL (nolock) on GATEINDETAIL.GIDID = GATEOUTDETAIL.GIDID INNER JOIN
		dbo.CONTAINERSIZEMASTER  (nolock) On  dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID   INNER JOIN  

		dbo.CATEGORY_ADDRESS_DETAIL (nolock) On GATEINDETAIL.CHAID = CATEGORY_ADDRESS_DETAIL.CATEID Left JOIN  
		dbo.STATEMASTER (nolock) on  dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID Left Outer Join 
		VW_ESEAL_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01 (nolock) on GATEINDETAIL.CHAID = VW_ESEAL_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANREFID
	
	WHERE     (ISNULL(dbo.VW_ESEAL_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDID, 0) = 0) AND (dbo.GATEINDETAIL.SDPTID = 11)  
	       and GATEINDETAIL.CHAID =@LCHAID and GATEINDETAIL.GIDATE BETWEEN @LSDate AND @LEDate and CATEGORY_ADDRESS_DETAIL.CATEAID = @LCATEAID  
				

ELSE
                      
--ACTUAL STUFF INVOICE DETAIL

	INSERT INTO @TableMaster(TRANREFID,TRANREFNAME,BOENO,BILLEMID,BILLEDID,GIDID,STMRID,STMRNAME,IGMNO,GPLNO,CONTNRNO,CONTNRSDESC,CONTNRSID,GIDATE,
	STRGDATE,GODATE,GOTIME,DODATE,NOD,WGHT,PRDTGID,TRANDID,TRANDOTYPE,TARIFFMID,DPAIDNO,DPAIDAMT,GPEAMT,GPCSAMT,GPLBAMT,GPAAMT,TRANDSAMT,TRANDHAMT,
	TRANDEAMT,TRANDFAMT,TRANDAAMT,TRANDNAMT,RCOL1,RCOL2,RCOL3,RCOL4,RCOL5,RCOL6,RCOL7,RAMT1,RAMT2,RAMT3,RAMT4,RAMT5,RAMT6,RAMT7,RCAMT1,RCAMT2,
	RCAMT3,RCAMT4,RCAMT5,RCAMT6,RCAMT7,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,TRANDRATE, STATETYPE, STRG_HSN_CODE, HANDL_HSN_CODE ,STRG_TAXABLE_AMT,
	HANDL_TAXABLE_AMT,STRG_CGST_EXPRN,STRG_SGST_EXPRN,STRG_IGST_EXPRN,STRG_CGST_AMT,STRG_SGST_AMT,
	STRG_IGST_AMT,HANDL_CGST_EXPRN,HANDL_SGST_EXPRN,HANDL_IGST_EXPRN,HANDL_CGST_AMT,HANDL_SGST_AMT,
	HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT)


	SELECT     dbo.TRANSACTIONMASTER.TRANREFID, dbo.TRANSACTIONMASTER.TRANREFNAME, dbo.TRANSACTIONDETAIL.TRANDREFNO AS BOENO, 
						  0 as BILLEMID,dbo.TRANSACTIONDETAIL.BILLEDID, dbo.TRANSACTIONDETAIL.TRANDREFID AS GIDID, dbo.GATEINDETAIL.STMRID,GATEINDETAIL.STMRNAME,
						  isnull(dbo.GATEINDETAIL.IGMNO, '') as IGMNO,isnull(dbo.GATEINDETAIL.GPLNO, '') as GPLNO,
						  dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.CONTNRSID, 
						  dbo.TRANSACTIONDETAIL.TRANIDATE, dbo.TRANSACTIONDETAIL.TRANSDATE, dbo.TRANSACTIONDETAIL.TRANEDATE, dbo.GATEOUTDETAIL.GOTIME, 
						  dbo.TRANSACTIONDETAIL.TRANVDATE, dbo.TRANSACTIONDETAIL.TRANDQTY, dbo.TRANSACTIONDETAIL.TRANDWGHT, 
						  isnull(dbo.GATEINDETAIL.PRDTGID,0) as  PRDTGID,
						  dbo.TRANSACTIONDETAIL.TRANDID, dbo.TRANSACTIONDETAIL.TRANOTYPE, dbo.TRANSACTIONDETAIL.TARIFFMID, 0 as DPAIDNO,  0 as DPAIDAMT, 
						  dbo.GATEINDETAIL.GPEAMT, dbo.GATEINDETAIL.GPCSAMT, dbo.GATEINDETAIL.GPLBAMT,dbo.GATEINDETAIL.GPAAMT, 
						  dbo.TRANSACTIONDETAIL.TRANDSAMT, dbo.TRANSACTIONDETAIL.TRANDHAMT, dbo.TRANSACTIONDETAIL.TRANDEAMT, dbo.TRANSACTIONDETAIL.TRANDFAMT, 
						  dbo.TRANSACTIONDETAIL.TRANDAAMT, dbo.TRANSACTIONDETAIL.TRANDNAMT, dbo.TRANSACTIONDETAIL.RCOL1, dbo.TRANSACTIONDETAIL.RCOL2, dbo.TRANSACTIONDETAIL.RCOL3, 
						  dbo.TRANSACTIONDETAIL.RCOL4, dbo.TRANSACTIONDETAIL.RCOL5, dbo.TRANSACTIONDETAIL.RCOL6, dbo.TRANSACTIONDETAIL.RCOL7, dbo.TRANSACTIONDETAIL.RAMT1, 
						  dbo.TRANSACTIONDETAIL.RAMT2, dbo.TRANSACTIONDETAIL.RAMT3, dbo.TRANSACTIONDETAIL.RAMT4, dbo.TRANSACTIONDETAIL.RAMT5, 
						  dbo.TRANSACTIONDETAIL.RAMT6, dbo.TRANSACTIONDETAIL.RAMT7, dbo.TRANSACTIONDETAIL.RCAMT1, dbo.TRANSACTIONDETAIL.RCAMT2, dbo.TRANSACTIONDETAIL.RCAMT3, 
						  dbo.TRANSACTIONDETAIL.RCAMT4, dbo.TRANSACTIONDETAIL.RCAMT5, dbo.TRANSACTIONDETAIL.RCAMT6, dbo.TRANSACTIONDETAIL.RCAMT7,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,
						  dbo.TRANSACTIONDETAIL.TRANDRATE,isnull(STATETYPE,0), STRG_HSNCODE, HANDL_HSNCODE, STRG_TAXABLE_AMT, HANDL_TAXABLE_AMT, STRG_CGST_EXPRN, STRG_SGST_EXPRN, STRG_IGST_EXPRN, 
                         STRG_CGST_AMT, STRG_SGST_AMT, STRG_IGST_AMT, HANDL_CGST_EXPRN, HANDL_SGST_EXPRN, HANDL_IGST_EXPRN, HANDL_CGST_AMT, 
                         HANDL_SGST_AMT, HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT

	FROM         dbo.TRANSACTIONMASTER INNER JOIN
						  dbo.TRANSACTIONDETAIL ON dbo.TRANSACTIONMASTER.TRANMID = dbo.TRANSACTIONDETAIL.TRANMID 
						  Inner join dbo.GATEINDETAIL ON dbo.TRANSACTIONDETAIL.TRANDREFID = dbo.GATEINDETAIL.GIDID INNER JOIN
						  dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID LEFT OUTER JOIN
						  dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID INNER JOIN 
						  DBO.CATEGORY_ADDRESS_DETAIL (NOLOCK) ON TRANSACTIONMASTER.TRANREFID = CATEGORY_ADDRESS_DETAIL.CATEID
						  AND TRANSACTIONMASTER.CATEAID = CATEGORY_ADDRESS_DETAIL.CATEAID LEFT JOIN  
						  dbo.STATEMASTER (nolock) on  dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID  
	WHERE     (dbo.TRANSACTIONMASTER.TRANMID = @LTRANMID)



	select *from @TableMaster

--SELECT	* FROM @TableMaster 
--order by BILLEDID



--return 
       
END



