-- [pr_EInvoice_Import_Manual_Transaction_Detail_Assgn] 3887
ALTER PROCEDURE [dbo].[pr_EInvoice_Import_Manual_Transaction_Detail_Assgn] @PTranMID int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    DECLARE @TableMaster TABLE
    ( 
	   PrdDesc  varchar(50),
	   HsnCd varchar(15),
	   Qty int,
	   UnitCode varchar(15),
	   UnitPrice numeric(18,2),
	   TotAmt  numeric(18,2),
	   AssAmt numeric(18,2),
	   GstRt numeric(18,2),
	   IgstAmt numeric(18,2),
	   CgstAmt numeric(18,2),
	   SgstAmt numeric(18,2),
	   TotItemVal numeric(18,2)	


    )
	

	Insert into @TableMaster(PrdDesc, HsnCd, Qty, UnitCode, UnitPrice, TotAmt, AssAmt, GstRt, IgstAmt, CgstAmt, SgstAmt, TotItemVal)
	--Select ACHEADDESC,STRG_HSNCODE, 1, 'Nos', STRG_TAXABLE_AMT, STRG_TAXABLE_AMT, STRG_TAXABLE_AMT, 18, STRG_IGST_AMT, STRG_CGST_AMT,
	--STRG_SGST_AMT, STRG_TAXABLE_AMT + STRG_IGST_AMT + STRG_CGST_AMT + STRG_SGST_AMT  
	--from Z_IMPORT_MANUAL_EINVOICE_DETAILS Where STRG_TAXABLE_AMT > 0 And TRANMID = @PTranMID

	--Insert into @TableMaster(PrdDesc, HsnCd, Qty, UnitCode, UnitPrice, TotAmt, AssAmt, GstRt, IgstAmt, CgstAmt, SgstAmt, TotItemVal)
	--Select ACHEADDESC,HANDL_HSNCODE, 1, 'Nos', HANDL_TAXABLE_AMT, HANDL_TAXABLE_AMT, HANDL_TAXABLE_AMT, 18, HANDL_IGST_AMT, HANDL_CGST_AMT,
	--HANDL_SGST_AMT, HANDL_TAXABLE_AMT + HANDL_IGST_AMT + HANDL_SGST_AMT + HANDL_SGST_AMT  
	--from Z_IMPORT_MANUAL_EINVOICE_DETAILS Where HANDL_TAXABLE_AMT > 0 And TRANMID = @PTranMID
	SELECT       TRANDREFNAME, TRANDREFNO,1,'Nos', SUM(TRANDGAMT), SUM(TRANDNAMT), SUM(TRANDGAMT),
				ISNULL(TRANSACTIONDETAIL.TRAND_STRG_CGST_EXPRN,0)+ISNULL(TRANSACTIONDETAIL.TRAND_STRG_SGST_EXPRN,0)+ 
				ISNULL(TRANSACTIONDETAIL.TRAND_STRG_IGST_EXPRN,0) +
				ISNULL(TRANSACTIONDETAIL.TRAND_HANDL_CGST_EXPRN,0) + ISNULL(TRANSACTIONDETAIL.TRAND_HANDL_SGST_EXPRN,0)+
				ISNULL(TRANSACTIONDETAIL.TRAND_HANDL_IGST_EXPRN,0) , 
				SUM(TRAND_STRG_IGST_AMT + TRAND_HANDL_IGST_AMT),  SUM(TRAND_STRG_CGST_AMT + TRAND_HANDL_CGST_AMT) , SUM(TRAND_STRG_SGST_AMT + TRAND_HANDL_SGST_AMT) AS SGST_AMT,
				SUM(TRANNAMT)
	FROM            dbo.TRANSACTIONMASTER join TRANSACTIONDETAIL on  TRANSACTIONMASTER.tranmid = TRANSACTIONDETAIL.tranmid 
	WHERE REGSTRID = 15
	AND TRANSACTIONMASTER.TRANMID = @PTranMID
	GROUP BY	TRANDREFNAME, TRANDREFNO, TRAND_STRG_CGST_EXPRN, TRAND_STRG_SGST_EXPRN, TRAND_STRG_IGST_EXPRN, TRAND_HANDL_CGST_EXPRN, TRAND_HANDL_SGST_EXPRN, 
                         TRAND_HANDL_IGST_EXPRN

	Select * From @TableMaster

END



