/*
EXEC [pr_Ex_Bond_VT_Invoice_BondNO_Grid_Assgn] @userid = 'ck', @PVTDID =1, @PEBNDID =14000, @PBNDID =5750, @PTRANMID = 0, @PSDATE = '2022-09-30', @PEDATE = '2022-10-13', @PBCHAID = 53617, @PBCATEAID = 860, @PTARIFFMID = 11, @PSLABTID = 2, @PCHRGTYPE = 1, 


@PRDTID = 2, @PYRDID = 1, @POPRID = 3, @PHNDTID  = 1, @PCNTSID = 2, @PQTY  = 2, @PNOP = 45, @PRATE  = 33, @PAMT = 2970, @PHTYPE = 1
EXEC [pr_Ex_Bond_VT_Invoice_BondNO_Grid_Assgn] @userid = 'ck', @PVTDID =3, @PEBNDID =0, @PBNDID =0, @PTRANMID =14725

EXEC [pr_Ex_Bond_VT_Invoice_BondNO_Grid_Assgn] @userid = 'ck', @PVTDID =26, @PEBNDID =14014, @PBNDID =5722, @PTRANMID = 14753, @PSDATE = '2022-10-15', @PEDATE = '2022-11-11', @PBCHAID = 24624, @PBCATEAID = 5002, @PTARIFFMID = 7, @PSLABTID = 2, @PCHRGTYPE 
= 1, @PRDTID = 2, @PYRDID = 1, @POPRID = 3, @PHNDTID  = 0, @PCNTSID = 2, @PQTY  = 4, @PNOP = 4, @PRATE  = 0, @PAMT = 0, @PHTYPE = 0, @PTAXTYPE = 1, @PVTSPC = 23
EXEC [pr_Ex_Bond_VT_Invoice_BondNO_Grid_Assgn] @userid = 'ck', @PVTDID =26, @PEBNDID =14014, @PBNDID =5722, @PTRANMID = 14753, @PSDATE = '2022-11-10', @PEDATE = '2022-11-10', @PBCHAID = 24624, @PBCATEAID = 5002, @PTARIFFMID = 15, @PSLABTID = 4, @PCHRGTYPE
 = 1, @PRDTID = 2, @PYRDID = 1, @POPRID = 3, @PHNDTID  = 0, @PCNTSID = 2, @PQTY  = 0, @PNOP = 4, @PRATE  = 0.15, @PAMT = 0, @PHTYPE = 0, @PTAXTYPE = 1, @PVTSPC = 23
EXEC [pr_Ex_Bond_VT_Invoice_BondNO_Grid_Assgn] @userid = 'ck', @PVTDID =60, @PEBNDID =14007, @PBNDID =5700, @PTRANMID = 0, @PSDATE = '2022-10-20', @PEDATE = '2022-10-19', @PBCHAID = 2386, @PBCATEAID = 66, @PTARIFFMID = 12, @PSLABTID = 4, @PCHRGTYPE = 1, @
PRDTID = 2, @PYRDID = 1, @POPRID = 3, @PHNDTID  = 0, @PCNTSID = 2, @PQTY  = 0, @PNOP = 140, @PRATE  = 0.15, @PAMT = 0, @PHTYPE = 0, @PTAXTYPE = 1, @PVTSPC = 6

EXEC [pr_Ex_Bond_VT_Invoice_BondNO_Grid_Assgn] @userid = 'ck', @PVTDID =335, @PEBNDID =14308, @PBNDID =5782, @PTRANMID = 0, @PSDATE = '2023-03-02', @PEDATE = '2023-03-21', @PBCHAID = 1931, @PBCATEAID = 2893, @PTARIFFMID = 9, @PSLABTID = 2, @PCHRGTYPE = 1, @PRDTID = 2, @PYRDID = 1, @POPRID = 3, @PHNDTID  = 0, @PCNTSID = 2, @PQTY  = 3, @PNOP = 7, @PRATE  = 75, @PAMT = 2925, @PHTYPE = 0, @PTAXTYPE = 1, @PVTSPC = 13
	EXEC [pr_Ex_Bond_VT_Invoice_BondNO_Grid_Assgn] @userid = 'ck', @PVTDID =335, @PEBNDID =14308, @PBNDID =5782, @PTRANMID = 0, @PSDATE = '2023-02-27', @PEDATE = '2023-03-18', @PBCHAID = 1931, @PBCATEAID = 2893, @PTARIFFMID = 9, @PSLABTID = 4, @PCHRGTYPE = 1, @PRDTID = 2, @PYRDID = 1, @POPRID = 3, @PHNDTID  = 0, @PCNTSID = 2, @PQTY  = 3, @PNOP = 7, @PRATE  = 0.15, @PAMT = 1111, @PHTYPE = 0, @PTAXTYPE = 1, @PVTSPC = 13
*/
-- delete tmp_usr_exbond_vtinv_add_dtl
-- delete bondtransactionmaster
-- select * From tmp_usr_exbond_vtinv_add_dtl
-- select * from BONDMASTER
alter PROCEDURE [dbo].[pr_Ex_Bond_VT_Invoice_BondNO_Grid_Assgn]  /* CHANGE */
		@userid varchar(50),
		@PVTDID int, 
		@PEBNDID int, 
		@PBNDID int, 
		@PTRANMID INT,
		@PSDATE smalldatetime=null, 
		@PEDATE smalldatetime=null, 
		@PBCHAID INT=0, 
		@PBCATEAID INT=0, 
		@PTARIFFMID int=0, 
		@PSLABTID INT=0, 
		@PCHRGTYPE INT=0, 
		@PRDTID INT=0, 
		@PYRDID int=0, 
		@POPRID INT=0, 
		@PHNDTID INT=0, 
		@PCNTSID INT=0, 
--		@PRDTGID INT=0,
		@PQTY NUMERIC(18,2)=0, 
		@PNOP NUMERIC(18,2)=0, 
		@PRATE numeric(18,2)=0,
		@PAMT numeric(18,2)=0,
		@PHTYPE int=0,
		@PTAXTYPE SMALLINT=1,
		@PVTSPC  numeric(18,2)=0
AS BEGIN

    DECLARE @TableMaster TABLE
    ( 
	   TRANMID INT
	  ,BNDID INT 
	  ,TRANDBNDNO  VARCHAR(50)
	  ,EBNDID INT 
	  ,TRANDEBNDNO  VARCHAR(50)
	  ,VTDID INT 
	  ,VTDNO  VARCHAR(50)
	  ,TARIFFMID INT
	  ,TARIFFDESC varchar(50)
	  ,SLABTID INT
	  ,SLABTDESC varchar(50)
	  ,PERIODTID INT
	  ,PERIODTDESC varchar(50)
	  ,CONTNRSID INT
	  ,CONTNRSDESC VARCHAR(25)
	  ,YRDID INT
	  ,YRDDESC VARCHAR(50)
	  ,TRANCTYPE INT
	  ,TRANCTYPEDESC VARCHAR(25)
	  ,TRANOTYPE INT
	  ,TRANOTYPEDESC VARCHAR(25)
	  ,TRANHTYPE INT
	  ,TRANHTYPEDESC VARCHAR(25)
	  ,TRANCDATE varchar(12) 
	  ,TRANSFDATE varchar(12) 
	  ,TRANSEDATE varchar(12) 
	  ,TRANIFDATE varchar(12)  
	  ,TRANIEDATE varchar(12) 
	  ,STATETYPE int
	  ,TRANDNOP	NUMERIC(18,2)	  
	  ,TRANDQTY 	NUMERIC(18,2)
	  ,TRANDRATE 	NUMERIC(18,2)
	  ,TRANDWGHT 	NUMERIC(18,2)
	  ,TRANDID INT
	  ,TRANDCIFAMT NUMERIC(18,2)
	  ,TRANDDTYAMT NUMERIC(18,2)
	  ,TRANDINSAMT NUMERIC(18,2)
	  ,TRANDEIAMT NUMERIC(18,2)
	  ,TRANDGAMT NUMERIC(18,2)
	  ,TRANDSAMT NUMERIC(18,2)
	  ,TRANDHAMT NUMERIC(18,2)
	  ,TRANDIAMT NUMERIC(18,2)
	  ,TRANDFAMT NUMERIC(18,2)
	  ,TRANDPAMT NUMERIC(18,2)
	  ,TRANDNAMT NUMERIC(18,2)
	   ,TRAND_HSN_CODE VARCHAR(10)
	   ,INS_TRAND_HSN_CODE VARCHAR(10)
	   ,TRAND_TAXABLE_AMT  NUMERIC(18,2)
	   ,INS_TRAND_TAXABLE_AMT  NUMERIC(18,2)
	   ,TRAND_CGST_EXPRN  NUMERIC(18,2)
	   ,TRAND_SGST_EXPRN  NUMERIC(18,2)
	  ,TRAND_IGST_EXPRN  NUMERIC(18,2)
	   ,TRAND_CGST_AMT  NUMERIC(18,2)
	   ,TRAND_SGST_AMT  NUMERIC(18,2)
	   ,TRAND_IGST_AMT  NUMERIC(18,2)
	   ,INS_TRAND_CGST_EXPRN  NUMERIC(18,2)
	   ,INS_TRAND_SGST_EXPRN  NUMERIC(18,2)
	   ,INS_TRAND_IGST_EXPRN  NUMERIC(18,2)
	   ,INS_TRAND_CGST_AMT  NUMERIC(18,2)
	   ,INS_TRAND_SGST_AMT  NUMERIC(18,2)
	   ,INS_TRAND_IGST_AMT  NUMERIC(18,2)
	   ,EXBNDVTSPC  NUMERIC(18,2)
    )


DECLARE @LBNDID int, @LEBNDID int, @LVTDID int, @LEDATE smalldatetime, @LTRANMID INT, @amount numeric(18,2)
set @amount = @PAMT -- @PNOP*@pQTY*@PRATE
set @LVTDID =@PVTDID
set @LEDATE = @PEDATE
set @LTRANMID = @PTRANMID

if(isnull(@LEBNDID,0)) =0
begin
	select @LEBNDID = EBNDID
	from BONDVEHICLETICKETDETAIL (nolock) 
	where VTDID = @LVTDID
end

if(isnull(@LBNDID,0)) =0
begin
	select @LBNDID = BNDID
	from exbondmaster (nolock) 
	where ebndid = @LEBNDID
end


--SELECT  * FROM @TableMaster
set nocount on

--PENDING BOND NO
if isnull(@PTRANMID,0)=0
begin
	delete tmp_usr_exbond_vtinv_add_dtl where userid = @userid and tariffmid = @PTARIFFMID and slabtid= @PSLABTID and VTDID = @LVTDID
	and TRANHTYPE = @PHTYPE
	and TRANMID = @PTRANMID
	

	declare @balassval numeric(18,2), @baldtyamt numeric(18,2),  @balinsamt numeric(18,2), @bndspc numeric(18,2)
	select @balassval = BNDCIFAMT, @baldtyamt= BNDDTYAMT, @balinsamt = BNDINSAMT, @bndspc = BNDSPC
	from BONDMASTER (nolock)
	where BNDID = @LBNDID

	select @balassval = @balassval - isnull(sum(EBNDASSAMT),0), @baldtyamt= @baldtyamt - isnull(sum(EBNDDTYAMT),0), 
	@balinsamt = @balinsamt- isnull(sum(EBNDINSAMT),0), @bndspc = @bndspc - isnull(sum(EBNDSPC),0)
	from EXBONDMASTER b (nolock) 
	where b.bndid= @LBNDID
	and b.ebndid in (select ebndid from BONDTRANSACTIONDETAIL where bndid = @LBNDID)
	
	INSERT INTO tmp_usr_exbond_vtinv_add_dtl(EBNDID,TRANDEBNDNO ,VTDID ,VTDNO ,
	TRANDBNDNO,CONTNRSDESC,TRANCDATE,TRANSFDATE,TRANSEDATE,TRANIFDATE,TRANIEDATE,TRANMID,BNDID,SLABTID,TRANDNOP,TRANDQTY,
	TRANDRATE,	TRANDID,TRANDSAMT,TRANDHAMT,TRANDIAMT,TRANDNAMT, STATETYPE, TRAND_HSN_CODE, INS_TRAND_HSN_CODE ,
	TRAND_TAXABLE_AMT,INS_TRAND_TAXABLE_AMT,TRAND_CGST_EXPRN,TRAND_SGST_EXPRN,TRAND_IGST_EXPRN,TRAND_CGST_AMT,TRAND_SGST_AMT,
	TRAND_IGST_AMT,INS_TRAND_CGST_EXPRN,INS_TRAND_SGST_EXPRN,INS_TRAND_IGST_EXPRN,INS_TRAND_CGST_AMT,INS_TRAND_SGST_AMT,
	INS_TRAND_IGST_AMT,TRANDCIFAMT ,TRANDDTYAMT ,TRANDINSAMT,
		CONTNRSID,YRDID,TRANCTYPE,TRANOTYPE,TRANHTYPE, YRDDESC ,TRANCTYPEDESC ,TRANOTYPEDESC , TRANHTYPEDESC,
		TARIFFMID, TARIFFDESC ,  SLABTDESC , PERIODTID , PERIODTDESC, TRANDGAMT, EXBNDVTSPC, userid
	)
    
	SELECT  dbo.EXBONDMASTER.EBNDID, dbo.EXBONDMASTER.EBNDDNO, DBO.BONDVEHICLETICKETDETAIL.VTDID, DBO.BONDVEHICLETICKETDETAIL.VTDNO, 
			dbo.BONDMASTER.BNDDNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, convert(varchar,@LEDATE,103),
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN NULL ELSE convert(varchar,@PSDATE,103) END AS TRANSFDATE, 
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN NULL ELSE convert(varchar,@LEDATE,103) END AS TRANSEDATE, 
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN convert(varchar,@PSDATE,103) ELSE NULL END AS TRANIFDATE, 
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN convert(varchar,@LEDATE,103)  ELSE NULL END AS TRANIEDATE, 
			@PTRANMID, dbo.BONDMASTER.BNDID, @PSLABTID,@PNOP,@pQTY,@PRATE,0,0,0,0,
			@amount+round(CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(CGSTEXPRN,0) ELSE isnull(ACGSTEXPRN,0) END/100*@amount,2)+
			round(CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(SGSTEXPRN,0) ELSE isnull(ASGSTEXPRN,0) END/100*@amount,2)+
			round(CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(IGSTEXPRN,0) ELSE isnull(AIGSTEXPRN,0) END/100*@amount,2),isnull(STATETYPE,0),isnull(HSNCODEMASTER.HSNCODE,''),'',
			@amount,0,CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(CGSTEXPRN,0) ELSE isnull(ACGSTEXPRN,0) END,
			CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(SGSTEXPRN,0) ELSE isnull(ASGSTEXPRN,0) END,
			CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(IGSTEXPRN,0) ELSE isnull(AIGSTEXPRN,0) END,
			round(CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(CGSTEXPRN,0) ELSE isnull(ACGSTEXPRN,0) END/100*@amount,2),
			round(CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(SGSTEXPRN,0) ELSE isnull(ASGSTEXPRN,0) END/100*@amount,2),
			round(CASE WHEN @PTAXTYPE = 2 THEN 0 WHEN isnull(STATETYPE,0) = 0 THEN isnull(IGSTEXPRN,0) ELSE isnull(AIGSTEXPRN,0) END/100*@amount,2),0,0,0,0,0,0,
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN @balassval else 0 end,
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN @baldtyamt else 0 end, 
			CASE WHEN BONDSLABTYPEMASTER.SLABTDESC = 'INSURANCE' THEN @balinsamt else 0 end,
			@PCNTSID,@PYRDID,@PCHRGTYPE,@POPRID,@PHNDTID,
			YRDDESC,CASE WHEN @PCHRGTYPE =1  THEN 'FCL' ELSE 'LCL' END ,
			CASE WHEN @POPRID = 1 THEN 'Manual' When @POPRID = 2 then 'Mechanical' When @POPRID = 3 then 'Both' else '' end,
			CASE WHEN @PHNDTID =0  THEN 'NR'
					  WHEN @PHNDTID =1  THEN 'Loading'
					  WHEN @PHNDTID =2  THEN 'Unloading' ELSE '' END,
			@PTARIFFMID, isnull(TARIFFMDESC,'') ,  SLABTDESC , 
			@PRDTID , case when @PRDTID = 1 then 'Weekly' else 'Daily' end,
			@amount, @bndspc,  @userid
	FROM         dbo.VW_BOND_VT_INVOICE_SBILL_NO_CBX_ASSGN_01 RIGHT OUTER JOIN     DBO.BONDVEHICLETICKETDETAIL ON							 
							 dbo.VW_BOND_VT_INVOICE_SBILL_NO_CBX_ASSGN_01.EBNDID = dbo.BONDVEHICLETICKETDETAIL.EBNDID
							 and dbo.VW_BOND_VT_INVOICE_SBILL_NO_CBX_ASSGN_01.VTDID = dbo.BONDVEHICLETICKETDETAIL.VTDID
							 and dbo.VW_BOND_VT_INVOICE_SBILL_NO_CBX_ASSGN_01.SLABTID = @PSLABTID  
							 and dbo.VW_BOND_VT_INVOICE_SBILL_NO_CBX_ASSGN_01.TRANHTYPE = @PHNDTID RIGHT OUTER JOIN DBO.EXBONDMASTER ON							 
							 dbo.BONDVEHICLETICKETDETAIL.EBNDID = dbo.EXBONDMASTER.EBNDID RIGHT OUTER JOIN DBO.BONDMASTER ON							 
							 dbo.EXBONDMASTER.BNDID = dbo.EXBONDMASTER.BNDID RIGHT OUTER JOIN
							 dbo.CONTAINERSIZEMASTER ON dbo.CONTAINERSIZEMASTER.CONTNRSID = @PCNTSID RIGHT OUTER JOIN							 
							 dbo.CATEGORYMASTER ON  dbo.CATEGORYMASTER.CATEID = @PBCHAID RIGHT OUTER JOIN
							 dbo.CATEGORY_ADDRESS_DETAIL ON dbo.CATEGORYMASTER.CATEID = CATEGORY_ADDRESS_DETAIL.CATEID 
							 AND CATEGORY_ADDRESS_DETAIL.CATEAID=@PBCATEAID RIGHT JOIN 
							 dbo.STATEMASTER ON  CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID   INNER JOIN
							 BONDSLABTYPEMASTER ON BONDSLABTYPEMASTER.SLABTID = @PSLABTID left JOIN
							 HSNCODEMASTER ON BONDSLABTYPEMASTER.HSNID = HSNCODEMASTER.HSNID INNER JOIN
							 BONDTARIFFMASTER ON BONDTARIFFMASTER.TARIFFMID = @PTARIFFMID INNER JOIN
							 BONDYARDMASTER ON BONDYARDMASTER.YRDID = @PYRDID 
							 --INNER JOIN
							 --BONDPRODUCTGROUPMASTER ON BONDPRODUCTGROUPMASTER.PRDTGID = @PRDTGID 
						 
							 --BONDYARDMASTER ON BONDYARDMASTER.YRDID = @PYRDID
	WHERE     ((ISNULL(dbo.VW_BOND_VT_INVOICE_SBILL_NO_CBX_ASSGN_01.TRANHTYPE, -1) = -1)	or 
	(ISNULL(dbo.VW_BOND_VT_INVOICE_SBILL_NO_CBX_ASSGN_01.VTDID, 0) = 0))
	AND (dbo.BONDVEHICLETICKETDETAIL.VTDID = @LVTDID or @LVTDID = 0)
	and dbo.EXBONDMASTER.EBNDID = @LEBNDID
	and dbo.BONDMASTER.BNDID = @LBNDID
	GROUP BY dbo.EXBONDMASTER.EBNDID, dbo.EXBONDMASTER.EBNDDNO, DBO.BONDVEHICLETICKETDETAIL.VTDID, DBO.BONDVEHICLETICKETDETAIL.VTDNO,
	dbo.BONDMASTER.BNDID, dbo.BONDMASTER.BNDDNO, dbo.BONDMASTER.BNDID, 
	dbo.VW_BOND_VT_INVOICE_SBILL_NO_CBX_ASSGN_01.SLABTID,  dbo.CONTAINERSIZEMASTER.CONTNRSDESC, isnull(STATETYPE,0) ,
	BONDSLABTYPEMASTER.SLABTDESC, YRDDESC, TARIFFMDESC, SLABTDESC, isnull(HSNCODEMASTER.HSNCODE,''),
	CGSTEXPRN, ACGSTEXPRN, SGSTEXPRN,ASGSTEXPRN, IGSTEXPRN, AIGSTEXPRN

	update a
	set TRANDGAMT = 0 , TRANDNAMT =0 , TRAND_TAXABLE_AMT=0,
		TRAND_CGST_EXPRN=0,TRAND_SGST_EXPRN=0,TRAND_IGST_EXPRN=0,TRAND_CGST_AMT=0,TRAND_SGST_AMT=0,
		TRAND_IGST_AMT=0
		-- select *
	from tmp_usr_exbond_vtinv_add_dtl a 
		join bondtransactiondetail b on a.bndid = b.bndid
	and a.slabtid = b.slabtid	
	and (@PSDATE between b.TRANSFDATE and b.TRANSEDATE
	or @PEDATE between b.TRANSFDATE and b.TRANSEDATE)	
	where a.slabtid = 2
	and userid = @userid and a.tariffmid = @PTARIFFMID and a.slabtid= @PSLABTID and a.VTDID = @LVTDID
	and a.TRANHTYPE = @PHTYPE
	and a.TRANMID = @PTRANMID
		
	
	update a
	set TRANDGAMT = 0 , TRANDNAMT =0 , TRAND_TAXABLE_AMT=0,
		TRAND_CGST_EXPRN=0,TRAND_SGST_EXPRN=0,TRAND_IGST_EXPRN=0,TRAND_CGST_AMT=0,TRAND_SGST_AMT=0,
		TRAND_IGST_AMT=0
	from tmp_usr_exbond_vtinv_add_dtl a 
		join bondtransactiondetail b on a.bndid = b.bndid
	and a.slabtid = b.slabtid	
	and (@PSDATE between b.TRANIFDATE and b.TRANIEDATE
	or @PEDATE between b.TRANIFDATE and b.TRANIEDATE)	
	where a.slabtid = 4
	and userid = @userid and a.tariffmid = @PTARIFFMID and a.slabtid= @PSLABTID and a.VTDID = @LVTDID
	and a.TRANHTYPE = @PHTYPE
	and a.TRANMID = @PTRANMID

	INSERT INTO @TableMaster(
	VTDID ,VTDNO ,TRANDBNDNO,CONTNRSDESC,TRANCDATE,TRANSFDATE,TRANSEDATE,TRANIFDATE,TRANIEDATE,TRANMID,BNDID,SLABTID,TRANDNOP,TRANDQTY, TRANDRATE,
	TRANDID,TRANDSAMT,TRANDHAMT,TRANDIAMT,TRANDNAMT, STATETYPE, TRAND_HSN_CODE, INS_TRAND_HSN_CODE ,TRAND_TAXABLE_AMT,
		INS_TRAND_TAXABLE_AMT,TRAND_CGST_EXPRN,TRAND_SGST_EXPRN,TRAND_IGST_EXPRN,TRAND_CGST_AMT,TRAND_SGST_AMT,
		TRAND_IGST_AMT,INS_TRAND_CGST_EXPRN,INS_TRAND_SGST_EXPRN,INS_TRAND_IGST_EXPRN,INS_TRAND_CGST_AMT,INS_TRAND_SGST_AMT,
		INS_TRAND_IGST_AMT,TRANDCIFAMT ,TRANDDTYAMT ,TRANDINSAMT,
		CONTNRSID,YRDID,TRANCTYPE,TRANOTYPE,TRANHTYPE, YRDDESC ,TRANCTYPEDESC ,TRANOTYPEDESC , TRANHTYPEDESC, EBNDID, TRANDEBNDNO ,
		TARIFFMID, TARIFFDESC ,  SLABTDESC , PERIODTID , PERIODTDESC,TRANDGAMT, EXBNDVTSPC
	)
	select VTDID ,VTDNO ,TRANDBNDNO,CONTNRSDESC,TRANCDATE,TRANSFDATE,TRANSEDATE,TRANIFDATE,TRANIEDATE,TRANMID,BNDID,SLABTID,TRANDNOP,TRANDQTY, TRANDRATE,
	TRANDID,TRANDSAMT,TRANDHAMT,TRANDIAMT,TRANDNAMT, STATETYPE, TRAND_HSN_CODE, INS_TRAND_HSN_CODE ,TRAND_TAXABLE_AMT,
		INS_TRAND_TAXABLE_AMT,TRAND_CGST_EXPRN,TRAND_SGST_EXPRN,TRAND_IGST_EXPRN,TRAND_CGST_AMT,TRAND_SGST_AMT,
		TRAND_IGST_AMT,INS_TRAND_CGST_EXPRN,INS_TRAND_SGST_EXPRN,INS_TRAND_IGST_EXPRN,INS_TRAND_CGST_AMT,INS_TRAND_SGST_AMT,
		INS_TRAND_IGST_AMT,TRANDCIFAMT ,TRANDDTYAMT ,TRANDINSAMT,
		CONTNRSID,YRDID,TRANCTYPE,TRANOTYPE,TRANHTYPE, YRDDESC ,TRANCTYPEDESC ,TRANOTYPEDESC , TRANHTYPEDESC, EBNDID, TRANDEBNDNO ,
		TARIFFMID, TARIFFDESC ,  SLABTDESC , PERIODTID , PERIODTDESC,TRANDGAMT , EXBNDVTSPC
	from tmp_usr_exbond_vtinv_add_dtl (nolock)
	where userid = @userid
end
else
begin
	delete tmp_usr_exbond_vtinv_add_dtl where userid = @userid and TRANMID = @LTRANMID
end
----ACTUAL BOND INVOICE DETAIL

INSERT INTO @TableMaster(
VTDID ,VTDNO ,TRANDBNDNO,CONTNRSDESC,TRANCDATE,TRANSFDATE,TRANSEDATE,TRANIFDATE,TRANIEDATE,TRANMID,BNDID,SLABTID,TRANDNOP,TRANDQTY, TRANDRATE,
TRANDID,TRANDSAMT,TRANDHAMT,TRANDIAMT,TRANDNAMT, STATETYPE, TRAND_HSN_CODE, INS_TRAND_HSN_CODE ,TRAND_TAXABLE_AMT,
	INS_TRAND_TAXABLE_AMT,TRAND_CGST_EXPRN,TRAND_SGST_EXPRN,TRAND_IGST_EXPRN,TRAND_CGST_AMT,TRAND_SGST_AMT,
	TRAND_IGST_AMT,INS_TRAND_CGST_EXPRN,INS_TRAND_SGST_EXPRN,INS_TRAND_IGST_EXPRN,INS_TRAND_CGST_AMT,INS_TRAND_SGST_AMT,
	INS_TRAND_IGST_AMT,TRANDCIFAMT ,TRANDDTYAMT ,TRANDINSAMT,
	CONTNRSID,YRDID,TRANCTYPE,TRANOTYPE,TRANHTYPE, YRDDESC ,TRANCTYPEDESC ,TRANOTYPEDESC , TRANHTYPEDESC, EBNDID, TRANDEBNDNO ,
	TARIFFMID, TARIFFDESC ,  SLABTDESC , PERIODTID , PERIODTDESC,TRANDGAMT, EXBNDVTSPC
)

SELECT     dbo.BONDTRANSACTIONDETAIL.VTDID, dbo.BONDVEHICLETICKETDETAIL.VTDNO, dbo.BONDTRANSACTIONDETAIL.TRANDBNDNO AS TRANDBNDNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC,
			convert(varchar,dbo.BONDTRANSACTIONDETAIL.TRANCDATE,103) , convert(varchar,dbo.BONDTRANSACTIONDETAIL.TRANSFDATE,103) , 
			convert(varchar,dbo.BONDTRANSACTIONDETAIL.TRANSEDATE,103) , convert(varchar,dbo.BONDTRANSACTIONDETAIL.TRANIFDATE,103) , 
                      convert(varchar,dbo.BONDTRANSACTIONDETAIL.TRANIEDATE,103) ,
					  dbo.BONDTRANSACTIONMASTER.TRANMID, dbo.BONDTRANSACTIONDETAIL.BNDID, 
                      dbo.BONDTRANSACTIONDETAIL.SLABTID, dbo.BONDTRANSACTIONDETAIL.TRANDNOP AS TRANDNOP, dbo.BONDTRANSACTIONDETAIL.TRANDQTY AS TRANDQTY, 
					  dbo.BONDTRANSACTIONDETAIL.TRANDRATE AS TRANDRATE, dbo.BONDTRANSACTIONDETAIL.TRANDID, dbo.BONDTRANSACTIONDETAIL.TRANDSAMT, 
					  dbo.BONDTRANSACTIONDETAIL.TRANDHAMT, dbo.BONDTRANSACTIONDETAIL.TRANDIAMT, dbo.BONDTRANSACTIONDETAIL.TRANDNAMT, isnull(BONDTRANSACTIONDETAIL.STATETYPE,0), 
					  dbo.BONDTRANSACTIONDETAIL.TRAND_HSN_CODE, '', dbo.BONDTRANSACTIONDETAIL.TRANDGAMT, 0, TRAND_CGST_EXPRN, TRAND_SGST_EXPRN, TRAND_IGST_EXPRN, 
					  TRAND_CGST_AMT, TRAND_SGST_AMT, TRAND_IGST_AMT, 0, 0, 0, INS_TRAND_CGST_AMT, 
					  INS_TRAND_SGST_AMT, INS_TRAND_IGST_AMT,
					  (BONDTRANSACTIONDETAIL.TRANDCIFAMT), (BONDTRANSACTIONDETAIL.TRANDDTYAMT), (BONDTRANSACTIONDETAIL.TRANDINSAMT),
					  dbo.BONDTRANSACTIONDETAIL.CONTNRSID,dbo.BONDTRANSACTIONDETAIL.YRDID,dbo.BONDTRANSACTIONDETAIL.TRANCTYPE,
					  dbo.BONDTRANSACTIONDETAIL.TRANOTYPE,dbo.BONDTRANSACTIONDETAIL.TRANHTYPE, YRDDESC,
					  CASE WHEN dbo.BONDTRANSACTIONDETAIL.TRANCTYPE =1  THEN 'FCL' ELSE 'LCL' END ,
					  CASE WHEN dbo.BONDTRANSACTIONDETAIL.TRANOTYPE = 1 THEN 'Manual' When dbo.BONDTRANSACTIONDETAIL.TRANOTYPE = 2 then 'Mechanical' 
					  When dbo.BONDTRANSACTIONDETAIL.TRANOTYPE = 3 then 'Both' else '' end,
					  CASE WHEN dbo.BONDTRANSACTIONDETAIL.TRANHTYPE =0  THEN 'NR'
					  WHEN dbo.BONDTRANSACTIONDETAIL.TRANHTYPE =1  THEN 'Loading'
					  WHEN dbo.BONDTRANSACTIONDETAIL.TRANHTYPE =2  THEN 'Unloading' ELSE '' END ,BONDTRANSACTIONDETAIL.EBNDID,TRANDEBNDNO,dbo.BONDTRANSACTIONDETAIL.TARIFFMID , isnull(TARIFFMDESC,'') , 
					  SLABTDESC , 
						  dbo.BONDTRANSACTIONDETAIL.PERIODTID , case when  dbo.BONDTRANSACTIONDETAIL.PERIODTID = 1 then 'Weekly' else 'Daily' end,
						  TRANDGAMT, isnull(EXBNDVTSPC,0)
FROM            dbo.BONDTRANSACTIONDETAIL INNER JOIN
						DBO.BONDVEHICLETICKETDETAIL ON dbo.BONDTRANSACTIONDETAIL.VTDID = dbo.BONDVEHICLETICKETDETAIL.VTDID INNER JOIN
                         dbo.BONDTRANSACTIONMASTER ON dbo.BONDTRANSACTIONDETAIL.TRANMID = dbo.BONDTRANSACTIONMASTER.TRANMID INNER JOIN
                         --dbo.BONDMASTER ON dbo.BONDTRANSACTIONDETAIL.BNDID = dbo.BONDMASTER.BNDID INNER JOIN
						 --dbo.EXBONDMASTER ON dbo.BONDTRANSACTIONDETAIL.EBNDID = dbo.EXBONDMASTER.EBNDID INNER JOIN
                         dbo.CONTAINERSIZEMASTER ON dbo.BONDTRANSACTIONDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID LEFT JOIN
						 dbo.CATEGORYMASTER ON BONDTRANSACTIONMASTER.BILLREFID= dbo.CATEGORYMASTER.CATEID LEFT join
                         dbo.BONDSLABTYPEMASTER ON dbo.BONDTRANSACTIONDETAIL.SLABTID = dbo.BONDSLABTYPEMASTER.SLABTID LEFT JOIN
						 dbo.BONDTARIFFMASTER ON dbo.BONDTRANSACTIONDETAIL.TARIFFMID = dbo.BONDTARIFFMASTER.TARIFFMID LEFT JOIN
                         dbo.BONDYARDMASTER ON dbo.BONDTRANSACTIONDETAIL.YRDID = dbo.BONDYARDMASTER.YRDID LEFT JOIN
                         dbo.CATEGORY_ADDRESS_DETAIL ON dbo.BONDTRANSACTIONMASTER.BCATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID LEFT OUTER JOIN 						 
                         dbo.STATEMASTER ON dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID
WHERE     (dbo.BONDTRANSACTIONMASTER.SDPTID = 10) 
AND TRANTID = 3
AND (dbo.BONDTRANSACTIONDETAIL.TRANMID = @LTRANMID)                                                                  

SELECT 
VTDID ,VTDNO ,TRANDBNDNO,CONTNRSDESC,TRANCDATE,TRANSFDATE,TRANSEDATE,TRANIFDATE,TRANIEDATE,TRANMID,BNDID,SLABTID,TRANDNOP,TRANDQTY, TRANDRATE,
TRANDID,TRANDSAMT,TRANDHAMT,TRANDIAMT,TRANDNAMT, STATETYPE, TRAND_HSN_CODE, INS_TRAND_HSN_CODE ,TRAND_TAXABLE_AMT,
	INS_TRAND_TAXABLE_AMT,TRAND_CGST_EXPRN,TRAND_SGST_EXPRN,TRAND_IGST_EXPRN,TRAND_CGST_AMT,TRAND_SGST_AMT,
	TRAND_IGST_AMT,INS_TRAND_CGST_EXPRN,INS_TRAND_SGST_EXPRN,INS_TRAND_IGST_EXPRN,INS_TRAND_CGST_AMT,INS_TRAND_SGST_AMT,
	INS_TRAND_IGST_AMT,TRANDCIFAMT ,TRANDDTYAMT ,TRANDINSAMT,
	CONTNRSID,YRDID,TRANCTYPE,TRANOTYPE,TRANHTYPE, YRDDESC ,TRANCTYPEDESC ,TRANOTYPEDESC , TRANHTYPEDESC, EBNDID, TRANDEBNDNO ,
	TARIFFMID, TARIFFDESC ,  SLABTDESC , PERIODTID , PERIODTDESC,TRANDGAMT, EXBNDVTSPC
FROM @TableMaster order by TRANCDATE, VTDID ,VTDNO ,TRANDEBNDNO, TRANDBNDNO

return 
       
END

