alter PROCEDURE [dbo].[pr_Export_Invoice_Stuff_No_Assgn]  /* CHANGE */
		@PCHAId int, @PSTFTID int 
 
AS BEGIN
    --Wrap filter term with % to search for values that contain @FilterTerm

    DECLARE @TableMaster TABLE
    ( 
	   STFMDNO  VARCHAR(15)
	  ,STFMID INT 
    )


DECLARE @LCHAId int, @LSTFTID int
set @LCHAId =@PCHAId
set @LSTFTID = @PSTFTID

set nocount on

INSERT INTO @TableMaster(STFMID,STFMDNO)
    
SELECT     dbo.STUFFINGDETAIL.STFMID, dbo.STUFFINGMASTER.STFMDNO
FROM         dbo.STUFFINGDETAIL INNER JOIN
                      dbo.STUFFINGMASTER ON dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID INNER JOIN
                      dbo.STUFFINGPRODUCTDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID LEFT OUTER JOIN
                      dbo.VW_EXPORT_INVOICE_SBILL_NO_CBX_ASSGN_01 ON dbo.STUFFINGDETAIL.STFDID = dbo.VW_EXPORT_INVOICE_SBILL_NO_CBX_ASSGN_01.STFDID
WHERE     (ISNULL(dbo.VW_EXPORT_INVOICE_SBILL_NO_CBX_ASSGN_01.TRANDID, 0) = 0) 
	--AND (dbo.STUFFINGMASTER.CHAID = @LCHAId) AND 
	AND (dbo.STUFFINGMASTER.STFBILLREFID = @LCHAId) AND 
	(dbo.STUFFINGMASTER.STFTID = @LSTFTID)
GROUP BY dbo.STUFFINGDETAIL.STFMID, dbo.STUFFINGMASTER.STFMDNO

                      
    SELECT STFMID,STFMDNO FROM @TableMaster order by  STFMDNO
    return    
END

