-- exec pr_Export_Manual_Invoice_Ctrl_Flx_Assgn 0
CREATE PROCEDURE [dbo].[pr_Export_Manual_Invoice_Ctrl_Flx_Assgn]  /* CHANGE */
		@PTRANMID INT
 
AS BEGIN

    DECLARE @TableMaster TABLE
    ( 
	   CONTNRNO  VARCHAR(15)
	  ,CONTNRSDESC VARCHAR(15)
	  ,GIDATE SMALLDATETIME 
	  ,SBDDATE SMALLDATETIME 
	  ,GODATE SMALLDATETIME
	  ,CONTNRSID INT
	  ,STFDID INT 
	  ,GIDID INT
	  ,STFDNOP	NUMERIC(18,2)
	  ,STFDQTY 	NUMERIC(18,2)
	  ,TRANDID INT
	  ,TRANDSAMT NUMERIC(18,2)
	  ,TRANDHAMT NUMERIC(18,2)
	  ,TRANDEAMT NUMERIC(18,2)
	  ,TRANDFAMT NUMERIC(18,2)
	  ,TRANDPAMT NUMERIC(18,2)
	  ,TRANDNAMT NUMERIC(18,2)
	  ,RCOL1  NUMERIC(18,2)
	  ,RCOL2  NUMERIC(18,2)
	  ,RCOL3  NUMERIC(18,2)
	  ,RCOL4  NUMERIC(18,2)
	  ,RCOL5  NUMERIC(18,2)
	  ,RCOL6  NUMERIC(18,2)
	  ,RCOL7  NUMERIC(18,2)
	  ,RAMT1  NUMERIC(18,2)
	  ,RAMT2  NUMERIC(18,2)
	  ,RAMT3  NUMERIC(18,2)
	  ,RAMT4  NUMERIC(18,2)
	  ,RAMT5  NUMERIC(18,2)
	  ,RAMT6  NUMERIC(18,2)
	  ,RAMT7  NUMERIC(18,2)
	  ,RCAMT1  NUMERIC(18,2)
	  ,RCAMT2  NUMERIC(18,2)
	  ,RCAMT3  NUMERIC(18,2)
	  ,RCAMT4  NUMERIC(18,2)
	  ,RCAMT5  NUMERIC(18,2)
	  ,RCAMT6  NUMERIC(18,2)
	  ,RCAMT7  NUMERIC(18,2)
	   , STATETYPE smallint
	   , STRG_HSN_CODE VARCHAR(10)
	   , HANDL_HSN_CODE VARCHAR(10)
	   ,STRG_TAXABLE_AMT  NUMERIC(18,2)
	   ,HANDL_TAXABLE_AMT  NUMERIC(18,2)
	   ,STRG_CGST_EXPRN  NUMERIC(18,2)
	   ,STRG_SGST_EXPRN  NUMERIC(18,2)
	   ,STRG_IGST_EXPRN  NUMERIC(18,2)
	   ,STRG_CGST_AMT  NUMERIC(18,2)
	   ,STRG_SGST_AMT  NUMERIC(18,2)
	   ,STRG_IGST_AMT  NUMERIC(18,2)
	   ,HANDL_CGST_EXPRN  NUMERIC(18,2)
	   ,HANDL_SGST_EXPRN  NUMERIC(18,2)
	   ,HANDL_IGST_EXPRN  NUMERIC(18,2)
	   ,HANDL_CGST_AMT  NUMERIC(18,2)
	   ,HANDL_SGST_AMT  NUMERIC(18,2)
	   ,HANDL_IGST_AMT  NUMERIC(18,2)
	   ,TRANCGSTAMT  NUMERIC(18,2)
	   ,TRANSGSTAMT  NUMERIC(18,2)
	   ,TRANIGSTAMT  NUMERIC(18,2)
	   ,TRAND_COVID_DISC_AMT NUMERIC(18,2)
    )


DECLARE @LTRANMID INT
set @LTRANMID = @PTRANMID


set nocount on


INSERT INTO @TableMaster(CONTNRNO,CONTNRSDESC,GIDATE,SBDDATE,GODATE,CONTNRSID,STFDID,GIDID,STFDNOP,STFDQTY,
TRANDID,TRANDSAMT,TRANDHAMT,TRANDEAMT,TRANDFAMT,TRANDPAMT,TRANDNAMT,RCOL1,RCOL2,RCOL3,RCOL4,RCOL5,RCOL6,
RCOL7,RAMT1,RAMT2,RAMT3,RAMT4,RAMT5,RAMT6,RAMT7,RCAMT1,RCAMT2,RCAMT3,RCAMT4,RCAMT5,RCAMT6,RCAMT7, STATETYPE, STRG_HSN_CODE, HANDL_HSN_CODE ,STRG_TAXABLE_AMT,
	HANDL_TAXABLE_AMT,STRG_CGST_EXPRN,STRG_SGST_EXPRN,STRG_IGST_EXPRN,STRG_CGST_AMT,STRG_SGST_AMT,
	STRG_IGST_AMT,HANDL_CGST_EXPRN,HANDL_SGST_EXPRN,HANDL_IGST_EXPRN,HANDL_CGST_AMT,HANDL_SGST_AMT,
	HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT)

SELECT     dbo.TRANSACTIONDETAIL.TRANDREFNO AS CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.TRANSACTIONDETAIL.TRANIDATE, 
                      dbo.TRANSACTIONDETAIL.TRANSDATE, dbo.TRANSACTIONDETAIL.TRANEDATE, dbo.GATEINDETAIL.CONTNRSID, dbo.TRANSACTIONDETAIL.STFDID, 
                      dbo.TRANSACTIONDETAIL.TRANDREFID AS GIDID, dbo.TRANSACTIONDETAIL.TRANDNOP AS STFDNOP, dbo.TRANSACTIONDETAIL.TRANDQTY AS STFDQTY, 
                      dbo.TRANSACTIONDETAIL.TRANDID, dbo.TRANSACTIONDETAIL.TRANDSAMT, dbo.TRANSACTIONDETAIL.TRANDHAMT, dbo.TRANSACTIONDETAIL.TRANDEAMT, 
                      dbo.TRANSACTIONDETAIL.TRANDFAMT, dbo.TRANSACTIONDETAIL.TRANDPAMT, dbo.TRANSACTIONDETAIL.TRANDNAMT, dbo.TRANSACTIONDETAIL.RCOL1, 
                      dbo.TRANSACTIONDETAIL.RCOL2, dbo.TRANSACTIONDETAIL.RCOL3, dbo.TRANSACTIONDETAIL.RCOL4, dbo.TRANSACTIONDETAIL.RCOL5, 
                      dbo.TRANSACTIONDETAIL.RCOL6, dbo.TRANSACTIONDETAIL.RCOL7, dbo.TRANSACTIONDETAIL.RAMT1, dbo.TRANSACTIONDETAIL.RAMT2, dbo.TRANSACTIONDETAIL.RAMT3, 
                      dbo.TRANSACTIONDETAIL.RAMT4, dbo.TRANSACTIONDETAIL.RAMT5, dbo.TRANSACTIONDETAIL.RAMT6, dbo.TRANSACTIONDETAIL.RAMT7, dbo.TRANSACTIONDETAIL.RCAMT1, 
                      dbo.TRANSACTIONDETAIL.RCAMT2, dbo.TRANSACTIONDETAIL.RCAMT3, dbo.TRANSACTIONDETAIL.RCAMT4, dbo.TRANSACTIONDETAIL.RCAMT5, 
 dbo.TRANSACTIONDETAIL.RCAMT6,dbo.TRANSACTIONDETAIL.RCAMT7,isnull(STATETYPE,0), STRG_HSNCODE, HANDL_HSNCODE, STRG_TAXABLE_AMT, HANDL_TAXABLE_AMT, STRG_CGST_EXPRN, STRG_SGST_EXPRN, STRG_IGST_EXPRN, 
                         STRG_CGST_AMT, STRG_SGST_AMT, STRG_IGST_AMT, HANDL_CGST_EXPRN, HANDL_SGST_EXPRN, HANDL_IGST_EXPRN, HANDL_CGST_AMT, 
                         HANDL_SGST_AMT, HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT
/*
FROM         dbo.TRANSACTIONDETAIL INNER JOIN
                      dbo.TRANSACTIONMASTER ON dbo.TRANSACTIONDETAIL.TRANMID = dbo.TRANSACTIONMASTER.TRANMID INNER JOIN
                      dbo.GATEINDETAIL ON dbo.TRANSACTIONDETAIL.TRANDREFID = dbo.GATEINDETAIL.GIDID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                         dbo.CATEGORYMASTER ON dbo.TRANSACTIONMASTER.TRANREFID = dbo.CATEGORYMASTER.CATEID LEFT OUTER JOIN
                         dbo.STATEMASTER ON dbo.CATEGORYMASTER.STATEID = dbo.STATEMASTER.STATEID
*/
FROM            dbo.TRANSACTIONDETAIL INNER JOIN
                         dbo.TRANSACTIONMASTER ON dbo.TRANSACTIONDETAIL.TRANMID = dbo.TRANSACTIONMASTER.TRANMID LEFT OUTER JOIN
                         dbo.GATEINDETAIL ON dbo.TRANSACTIONDETAIL.TRANDREFID = dbo.GATEINDETAIL.GIDID LEFT OUTER JOIN
                         dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID LEFT OUTER JOIN
                         dbo.STUFFINGDETAIL ON dbo.TRANSACTIONDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID LEFT OUTER JOIN
                         dbo.STUFFINGMASTER ON dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID INNER JOIN
                         dbo.CATEGORYMASTER ON dbo.TRANSACTIONMASTER.TRANREFID = dbo.CATEGORYMASTER.CATEID LEFT OUTER JOIN
                         dbo.STATEMASTER ON dbo.CATEGORYMASTER.STATEID = dbo.STATEMASTER.STATEID
WHERE     (dbo.TRANSACTIONMASTER.SDPTID = 2) AND (dbo.TRANSACTIONDETAIL.TRANMID = @LTRANMID)                                                                  

SELECT CONTNRNO,CONTNRSDESC,GIDATE,SBDDATE,GODATE,CONTNRSID,STFDID,GIDID,STFDNOP,STFDQTY,TRANDID,TRANDSAMT,
TRANDHAMT,TRANDEAMT,TRANDFAMT,TRANDPAMT,TRANDNAMT,RCOL1,RCOL2,RCOL3,RCOL4,RCOL5,RCOL6,RCOL7,RAMT1,RAMT2,
RAMT3,RAMT4,RAMT5,RAMT6,RAMT7,RCAMT1,RCAMT2,RCAMT3,RCAMT4,RCAMT5,RCAMT6,RCAMT7, STATETYPE, STRG_HSN_CODE, HANDL_HSN_CODE ,STRG_TAXABLE_AMT,
	HANDL_TAXABLE_AMT,STRG_CGST_EXPRN,STRG_SGST_EXPRN,STRG_IGST_EXPRN,STRG_CGST_AMT,STRG_SGST_AMT,
	STRG_IGST_AMT,HANDL_CGST_EXPRN,HANDL_SGST_EXPRN,HANDL_IGST_EXPRN,HANDL_CGST_AMT,HANDL_SGST_AMT,
	HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT FROM @TableMaster order by GIDATE, CONTNRNO

return 
       
END

