
CREATE PROC PR_EXPORT_MANUAL_BILL_TRANMASTER_UPD
@PTRANMID INT
AS
BEGIN

	DECLARE @LTRANMID INT

	SET @LTRANMID = @PTRANMID

	UPDATE B
	SET STRG_HSNCODE = CASE WHEN ACHEADDESC LIKE '%STORAGE%' THEN D.HSNCODE ELSE '' END
	FROM TRANSACTIONDETAIL A(NOLOCK) 
			JOIN TRANSACTIONMASTER B(NOLOCK) ON A.TRANMID = B.TRANMID 
			JOIN ACCOUNTHEADMASTER C(NOLOCK) ON A.ACHEADID = C.ACHEADID
			JOIN HSNCODEMASTER D(NOLOCK) ON C.HSNID =D.HSNID
	WHERE REGSTRID = 49
	AND (STRG_TAXABLE_AMT > 0 OR TRAND_STRG_CGST_AMT > 0  OR TRAND_STRG_IGST_AMT > 0)
	AND ISNULL(STRG_HSNCODE,'') =''
	AND A.TRANMID =  @LTRANMID

	UPDATE B
	SET STRG_TAXABLE_AMT = ISNULL(A.TRANDGAMT ,0)
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, SUM(XA.TRANDGAMT) AS TRANDGAMT FROM TRANSACTIONDETAIL XA(NOLOCK) 
			WHERE  (TRAND_STRG_CGST_AMT > 0  OR TRAND_STRG_IGST_AMT > 0 AND XA.TRANMID =  @LTRANMID) 
			GROUP BY TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND STRG_HSNCODE <> ''
	AND STRG_TAXABLE_AMT = 0 
	AND A.TRANMID =  @LTRANMID

	UPDATE B
	SET STRG_CGST_EXPRN = ISNULL(A.TRAND_STRG_CGST_EXPRN ,0)
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, MAX(XA.TRAND_STRG_CGST_EXPRN) AS TRAND_STRG_CGST_EXPRN
			FROM TRANSACTIONDETAIL XA(NOLOCK) 
			WHERE  (TRAND_STRG_CGST_AMT > 0 ) AND XA.TRANMID =  @LTRANMID
			GROUP BY TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND STRG_HSNCODE <> ''
	AND B.STRG_CGST_EXPRN = 0 
	AND A.TRANMID =  @LTRANMID

	UPDATE B
	SET STRG_SGST_EXPRN = ISNULL(A.TRAND_STRG_SGST_EXPRN ,0)
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, MAX(XA.TRAND_STRG_SGST_EXPRN) AS TRAND_STRG_SGST_EXPRN FROM TRANSACTIONDETAIL XA(NOLOCK) 
			WHERE  (TRAND_STRG_SGST_AMT > 0) AND XA.TRANMID =  @LTRANMID
			GROUP BY TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND STRG_HSNCODE <> ''
	AND B.STRG_SGST_EXPRN = 0 
	AND A.TRANMID =  @LTRANMID


	UPDATE B
	SET STRG_IGST_EXPRN = ISNULL(A.TRAND_STRG_IGST_EXPRN ,0)
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, MAX(XA.TRAND_STRG_IGST_EXPRN) AS TRAND_STRG_IGST_EXPRN FROM TRANSACTIONDETAIL XA(NOLOCK) 
			WHERE  (TRAND_STRG_IGST_AMT > 0) AND XA.TRANMID =  @LTRANMID
			GROUP BY TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND STRG_HSNCODE <> ''
	AND B.STRG_IGST_EXPRN = 0 
	AND A.TRANMID =  @LTRANMID


	UPDATE B
	SET STRG_CGST_AMT = ISNULL(A.TRAND_STRG_CGST_AMT ,0)
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, SUM(XA.TRAND_STRG_CGST_AMT) AS TRAND_STRG_CGST_AMT
			FROM TRANSACTIONDETAIL XA(NOLOCK) 
			WHERE  (TRAND_STRG_CGST_AMT > 0 ) AND XA.TRANMID =  @LTRANMID
			GROUP BY TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND STRG_HSNCODE <> ''
	AND B.STRG_CGST_AMT = 0 
	AND A.TRANMID =  @LTRANMID


	UPDATE B
	SET STRG_SGST_AMT = ISNULL(A.TRAND_STRG_SGST_AMT ,0)
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, SUM(XA.TRAND_STRG_SGST_AMT) AS TRAND_STRG_SGST_AMT FROM TRANSACTIONDETAIL XA(NOLOCK) 
			WHERE  (TRAND_STRG_SGST_AMT > 0) AND XA.TRANMID =  @LTRANMID
			GROUP BY TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND STRG_HSNCODE <> ''
	AND B.STRG_SGST_AMT = 0 
	AND A.TRANMID =  @LTRANMID

	UPDATE B
	SET STRG_IGST_AMT = ISNULL(A.TRAND_STRG_IGST_AMT ,0)
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, SUM(XA.TRAND_STRG_IGST_AMT) AS TRAND_STRG_IGST_AMT FROM TRANSACTIONDETAIL XA(NOLOCK) 
			WHERE  ( TRAND_STRG_IGST_AMT > 0) AND XA.TRANMID =  @LTRANMID
			GROUP BY TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND STRG_HSNCODE <> ''
	AND B.STRG_IGST_AMT = 0 
	AND A.TRANMID =  @LTRANMID

	UPDATE B
	SET HANDL_HSNCODE = CASE WHEN ACHEADDESC NOT LIKE '%STORAGE%' THEN D.HSNCODE ELSE '' END
	FROM TRANSACTIONDETAIL A(NOLOCK) 
			JOIN TRANSACTIONMASTER B(NOLOCK) ON A.TRANMID = B.TRANMID 
			JOIN ACCOUNTHEADMASTER C(NOLOCK) ON A.ACHEADID = C.ACHEADID
			JOIN HSNCODEMASTER D(NOLOCK) ON C.HSNID =D.HSNID
	WHERE REGSTRID = 49
	AND (HANDL_TAXABLE_AMT > 0 OR TRAND_HANDL_CGST_AMT > 0  OR TRAND_HANDL_IGST_AMT > 0)
	AND ISNULL(HANDL_HSNCODE,'') ='' 
	AND A.TRANMID =  @LTRANMID

	UPDATE B
	SET HANDL_TAXABLE_AMT = ISNULL(A.TRANDGAMT ,0)
	--SELECT HANDL_TAXABLE_AMT,  A.*
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, SUM(XA.TRANDGAMT) AS TRANDGAMT 
			FROM TRANSACTIONDETAIL XA(NOLOCK) JOIN TRANSACTIONMASTER  XB(NOLOCK) ON XA.TRANMID = XB.TRANMID
			WHERE  REGSTRID = 49 AND (TRAND_HANDL_CGST_AMT > 0  OR TRAND_HANDL_IGST_AMT > 0) AND XA.TRANMID =  @LTRANMID
			GROUP BY XA.TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND HANDL_HSNCODE <> ''
	AND ISNULL(HANDL_TAXABLE_AMT,0) = 0 
	AND A.TRANMID =  @LTRANMID

	UPDATE B
	SET HANDL_CGST_EXPRN = ISNULL(A.TRAND_HANDL_CGST_EXPRN ,0)
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, MAX(XA.TRAND_HANDL_CGST_EXPRN) AS TRAND_HANDL_CGST_EXPRN
			FROM TRANSACTIONDETAIL XA(NOLOCK) JOIN TRANSACTIONMASTER  XB(NOLOCK) ON XA.TRANMID = XB.TRANMID
			WHERE  REGSTRID = 49 AND (TRAND_HANDL_CGST_AMT > 0  OR TRAND_HANDL_CGST_EXPRN > 0) AND XA.TRANMID =  @LTRANMID
			GROUP BY XA.TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND HANDL_HSNCODE <> ''
	AND B.HANDL_CGST_EXPRN = 0 
	AND A.TRANMID =  @LTRANMID


	UPDATE B
	SET HANDL_SGST_EXPRN = ISNULL(A.TRAND_HANDL_SGST_EXPRN ,0)
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, MAX(XA.TRAND_HANDL_SGST_EXPRN) AS TRAND_HANDL_SGST_EXPRN FROM TRANSACTIONDETAIL XA(NOLOCK) 
			WHERE  (TRAND_HANDL_SGST_EXPRN > 0  OR TRAND_HANDL_SGST_AMT > 0) AND XA.TRANMID =  @LTRANMID
			GROUP BY TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND HANDL_HSNCODE <> ''
	AND B.HANDL_SGST_EXPRN = 0
	AND A.TRANMID =  @LTRANMID 


	UPDATE B
	SET HANDL_IGST_EXPRN = ISNULL(A.TRAND_HANDL_IGST_EXPRN ,0)
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, MAX(XA.TRAND_HANDL_IGST_EXPRN) AS TRAND_HANDL_IGST_EXPRN FROM TRANSACTIONDETAIL XA(NOLOCK) 
			WHERE  (TRAND_HANDL_IGST_EXPRN > 0  OR TRAND_HANDL_IGST_AMT > 0) AND XA.TRANMID =  @LTRANMID
			GROUP BY TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND HANDL_HSNCODE <> ''
	AND B.HANDL_IGST_EXPRN = 0 
	AND A.TRANMID =  @LTRANMID

	UPDATE B
	SET HANDL_CGST_AMT = A.TRAND_HANDL_CGST_AMT 
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, SUM(XA.TRAND_HANDL_CGST_AMT) AS TRAND_HANDL_CGST_AMT
			FROM TRANSACTIONDETAIL XA(NOLOCK) 
			WHERE  (TRAND_HANDL_CGST_AMT > 0) AND XA.TRANMID =  @LTRANMID
			GROUP BY TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND HANDL_HSNCODE <> ''
	AND B.HANDL_CGST_AMT = 0 
	AND A.TRANMID =  @LTRANMID


	UPDATE B
	SET HANDL_SGST_AMT = A.TRAND_HANDL_SGST_AMT 
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, SUM(XA.TRAND_HANDL_SGST_AMT) AS TRAND_HANDL_SGST_AMT FROM TRANSACTIONDETAIL XA(NOLOCK) 
			WHERE  (TRAND_HANDL_SGST_AMT > 0 ) AND XA.TRANMID =  @LTRANMID
			GROUP BY TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND HANDL_HSNCODE <> ''
	AND B.HANDL_SGST_AMT = 0 
	AND A.TRANMID =  @LTRANMID


	UPDATE B
	SET HANDL_IGST_AMT = A.TRAND_HANDL_IGST_AMT 
	FROM TRANSACTIONMASTER  B(NOLOCK) 
			JOIN 
			(SELECT XA.TRANMID, SUM(XA.TRAND_HANDL_IGST_AMT) AS TRAND_HANDL_IGST_AMT FROM TRANSACTIONDETAIL XA(NOLOCK) 
			WHERE  (TRAND_HANDL_IGST_AMT > 0) AND XA.TRANMID =  @LTRANMID
			GROUP BY TRANMID) A
			ON A.TRANMID = B.TRANMID 
	WHERE REGSTRID = 49
	AND HANDL_HSNCODE <> ''
	AND B.HANDL_IGST_AMT = 0 
	AND A.TRANMID =  @LTRANMID

END

