ALTER PROCEDURE pr_EInvoice_CreditNote_Transaction_Detail_Assgn @PTranMID int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    DECLARE @TableMaster TABLE
    ( 
	   PrdDesc  varchar(50),
	   HsnCd varchar(15),
	   Qty int,
	   UnitCode varchar(15),
	   UnitPrice numeric(18,2),
	   TotAmt  numeric(18,2),
	   AssAmt numeric(18,2),
	   GstRt numeric(18,2),
	   IgstAmt numeric(18,2),
	   CgstAmt numeric(18,2),
	   SgstAmt numeric(18,2),
	   TotItemVal numeric(18,2)	


    )
	
	Insert into @TableMaster(PrdDesc, HsnCd, Qty, UnitCode, UnitPrice, TotAmt, AssAmt, GstRt, IgstAmt, CgstAmt, SgstAmt, TotItemVal)
	SELECT       CNTDESC, TRANDHSNCODE,1,'Nos', SUM(TRANDGAMT), SUM(TRANDNAMT), SUM(TRANDGAMT),
				ISNULL(CREDITNOTE_TRANSACTIONDETAIL.TRAND_STRG_CGST_EXPRN,0)+ISNULL(CREDITNOTE_TRANSACTIONDETAIL.TRAND_STRG_SGST_EXPRN,0)+ 
				ISNULL(CREDITNOTE_TRANSACTIONDETAIL.TRAND_STRG_IGST_EXPRN,0) +
				ISNULL(CREDITNOTE_TRANSACTIONDETAIL.TRAND_HANDL_CGST_EXPRN,0) + ISNULL(CREDITNOTE_TRANSACTIONDETAIL.TRAND_HANDL_SGST_EXPRN,0)+
				ISNULL(CREDITNOTE_TRANSACTIONDETAIL.TRAND_HANDL_IGST_EXPRN,0) , 
				SUM(TRAND_STRG_IGST_AMT + TRAND_HANDL_IGST_AMT),  SUM(TRAND_STRG_CGST_AMT + TRAND_HANDL_CGST_AMT) , SUM(TRAND_STRG_SGST_AMT + TRAND_HANDL_SGST_AMT) AS SGST_AMT,
				SUM(TRANDNAMT)
	FROM            dbo.CREDITNOTE_TRANSACTIONMASTER join CREDITNOTE_TRANSACTIONDETAIL join CREDITNOTE_TYPEMASTER on CREDITNOTE_TRANSACTIONDETAIL.TRANDREFID = CREDITNOTE_TYPEMASTER.CNTID
					on  CREDITNOTE_TRANSACTIONMASTER.tranmid = CREDITNOTE_TRANSACTIONDETAIL.tranmid 
	WHERE CREDITNOTE_TRANSACTIONMASTER.TRANMID = @PTranMID
	GROUP BY	CNTDESC, TRANDHSNCODE, TRAND_STRG_CGST_EXPRN, TRAND_STRG_SGST_EXPRN, TRAND_STRG_IGST_EXPRN, TRAND_HANDL_CGST_EXPRN, TRAND_HANDL_SGST_EXPRN, 
                         TRAND_HANDL_IGST_EXPRN, CNTDESC

	Select * From @TableMaster

END



