-- EXEC PR_EXPORT_LOADVEHICLEGATEOUT_DETAILS '2022-08-01' , '2022-08-01', 2
alter PROCEDURE [dbo].[PR_EXPORT_LOADVEHICLEGATEOUT_DETAILS]
@PFDT datetime,
@PTDT datetime,
@PSDPTID int
as
begin

	Declare @temptable table
	(
	Sno int,
	Descriptn varchar(250),
	c_20 int,
	c_40 int,
	c_45 int,
	c_tues int)

	insert into @temptable
	select	1, 'EXPORT - LOADSLIP', SUM(CASE WHEN CONTNRSID = 3 THEN 1 ELSE 0 END) '20"', 
			SUM(CASE WHEN CONTNRSID = 4 THEN 1 ELSE 0 END) '40"',
			SUM(CASE WHEN CONTNRSID = 5 THEN 1 ELSE 0 END) '45"',
			0 'TUES'
	from STUFFINGDETAIL (nolock)
	Inner Join STUFFINGMASTER (NOLOCK) ON STUFFINGDETAIL.STFMID = STUFFINGMASTER.STFMID   
	Inner Join AUTHORIZATIONSLIPDETAIL (NOLOCK) ON AUTHORIZATIONSLIPDETAIL.STFDID = STUFFINGDETAIL.STFDID  
	Inner Join AUTHORIZATIONSLIPMASTER (NOLOCK) ON AUTHORIZATIONSLIPMASTER.ASLMID = AUTHORIZATIONSLIPDETAIL.ASLMID   
	Inner Join GATEINDETAIL  (NOLOCK) ON STUFFINGDETAIL.GIDID = GATEINDETAIL.GIDID  AND AUTHORIZATIONSLIPMASTER.SDPTID = GATEINDETAIL.SDPTID  
	Where  AUTHORIZATIONSLIPMASTER.SDPTID = 2 and AUTHORIZATIONSLIPMASTER.ASLMDATE between @PFDT and @PTDT
	and CONTNRSID > 2 
	and GATEINDETAIL.DISPSTATUS = 0 and AUTHORIZATIONSLIPMASTER.ASLMTYPE = 1  
	--group by CONTNRSID

	insert into @temptable
	select 2, 'EXPORT - VEHICLETICKE', SUM(CASE WHEN CONTNRSID = 3 THEN 1 ELSE 0 END) '20"', 
			SUM(CASE WHEN CONTNRSID = 4 THEN 1 ELSE 0 END) '40"',
			SUM(CASE WHEN CONTNRSID = 5 THEN 1 ELSE 0 END) '45"',
			0 'TUES'
	from STUFFINGDETAIL 
	Inner Join STUFFINGMASTER (NOLOCK) ON STUFFINGDETAIL.STFMID = STUFFINGMASTER.STFMID   
	Inner Join AUTHORIZATIONSLIPDETAIL (NOLOCK) ON AUTHORIZATIONSLIPDETAIL.STFDID = STUFFINGDETAIL.STFDID  
	Inner Join AUTHORIZATIONSLIPMASTER (NOLOCK) ON AUTHORIZATIONSLIPMASTER.ASLMID = AUTHORIZATIONSLIPDETAIL.ASLMID 
	Inner Join VEHICLETICKETDETAIL (NOLOCK) ON VEHICLETICKETDETAIL.ASLDID = AUTHORIZATIONSLIPDETAIL.ASLDID 	 
	Inner Join GATEINDETAIL  (NOLOCK) ON STUFFINGDETAIL.GIDID = GATEINDETAIL.GIDID  AND VEHICLETICKETDETAIL.SDPTID = GATEINDETAIL.SDPTID  
	where VEHICLETICKETDETAIL.SDPTID = 2
	and VEHICLETICKETDETAIL.VTDATE between @PFDT and @PTDT
	and CONTNRSID > 2 
	and GATEINDETAIL.DISPSTATUS = 0 
	--group by CONTNRSID

	--insert into @temptable
	--select 3, 'EXPORT - GATEOUT', SUM(CASE WHEN CONTNRSID = 3 THEN 1 ELSE 0 END) '20"', 
	--		SUM(CASE WHEN CONTNRSID = 4 THEN 1 ELSE 0 END) '40"',
	--		SUM(CASE WHEN CONTNRSID = 5 THEN 1 ELSE 0 END) '45"',
	--		0 'TUES'
	--from STUFFINGDETAIL 
	--Inner Join STUFFINGMASTER (NOLOCK) ON STUFFINGDETAIL.STFMID = STUFFINGMASTER.STFMID   
	--Inner Join AUTHORIZATIONSLIPDETAIL (NOLOCK) ON AUTHORIZATIONSLIPDETAIL.STFDID = STUFFINGDETAIL.STFDID  
	--Inner Join AUTHORIZATIONSLIPMASTER (NOLOCK) ON AUTHORIZATIONSLIPMASTER.ASLMID = AUTHORIZATIONSLIPDETAIL.ASLMID 
	--Inner Join VEHICLETICKETDETAIL (NOLOCK) ON VEHICLETICKETDETAIL.ASLDID = AUTHORIZATIONSLIPDETAIL.ASLDID 	 	
	--Inner Join GATEINDETAIL  (NOLOCK) ON STUFFINGDETAIL.GIDID = GATEINDETAIL.GIDID  AND VEHICLETICKETDETAIL.SDPTID = GATEINDETAIL.SDPTID  
	--Inner Join GATEOUTDETAIL (NOLOCK) ON GATEOUTDETAIL.GIDID = GATEINDETAIL.GIDID  AND GATEOUTDETAIL.SDPTID = GATEINDETAIL.SDPTID  
	--Where  GATEOUTDETAIL.SDPTID = 2
	--and GATEOUTDETAIL.GODATE between @PFDT and @PTDT
	--and CONTNRSID > 2
	--and GATEINDETAIL.DISPSTATUS = 0

	insert into @temptable
	select 3, 'EXPORT - GATEOUT', SUM(CASE WHEN CONTNRSID = 3 THEN 1 ELSE 0 END) '20"', 
			SUM(CASE WHEN CONTNRSID = 4 THEN 1 ELSE 0 END) '40"',
			SUM(CASE WHEN CONTNRSID = 5 THEN 1 ELSE 0 END) '45"',
			0 'TUES'
	from GATEOUTDETAIL a(nolock) join gateindetail b(nolock) on a.gidid = b.gidid and a.sdptid = b.sdptid
	join  STUFFINGDETAIL c(nolock) on b.GIDID = c.GIDID
	Join STUFFINGMASTER d(NOLOCK) ON c.STFMID = d.STFMID   
	Join AUTHORIZATIONSLIPDETAIL e (NOLOCK) ON e.STFDID = c.STFDID  
	Join AUTHORIZATIONSLIPMASTER f(NOLOCK) ON e.ASLMID = f.ASLMID 
	left Join VEHICLETICKETDETAIL g(NOLOCK) ON e.ASLDID = g.ASLDID 	and a.SDPTID = g.SDPTID
	Where  a.SDPTID = 2
	and a.GODATE between @PFDT and @PTDT
	and CONTNRSID > 2
	and b.DISPSTATUS = 0
	 	
	

	update @temptable
	set c_tues = isnull(c_20,0) + (isnull(c_40,0)*2)+ (isnull(c_45,0)*2)
	
	select * from @temptable
end

