USE [SCFS_ERP]
GO
/****** Object:  StoredProcedure [dbo].[pr_Finance_TranSactionBillNo]    Script Date: 12/10/2021 12:46:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[pr_Export_AUTO_TRUCKNO_CBX_ASSGN]  
        @FilterTerm varchar(100) ,
        @PCHAID INT ,
		@PEXPRTID INT 
        
AS BEGIN

Declare @LCHAID int , @LEXPRTID int

set @LEXPRTID = @PEXPRTID 
set @LCHAID = @PCHAID

 SET @FilterTerm = @FilterTerm + '%'    

    DECLARE @TableMaster Table 
	( 
	  AVHLNO nvarchar(100) not null,
	  GIDID int,
	  ESBMDNO nvarchar(100) null,
	  ESBMID int 
	)

	
   Insert Into  @TableMaster(AVHLNO ,GIDID ,ESBMDNO,ESBMID)  

   SELECT  dbo.GATEINDETAIL.AVHLNO, dbo.GATEINDETAIL.GIDID, 
   		  isnull(EXPORTSHIPPINGBILLMASTER.ESBMDNO,'-') as ESBMDNO,
          isnull(EXPORTSHIPPINGBILLMASTER.ESBMID,0) as ESBMID 
   FROM   dbo.GATEINDETAIL (nolock) 
          LEFT OUTER JOIN EXPORTSHIPPINGBILLMASTER (nolock) ON GATEINDETAIL.ESBMID = EXPORTSHIPPINGBILLMASTER.ESBMID  
		  LEFT OUTER JOIN SHIPPINGBILLDETAIL (nolock) ON EXPORTSHIPPINGBILLMASTER.ESBMID = SHIPPINGBILLDETAIL.ESBMID 
		  left join SHIPPINGBILLMASTER (nolock) ON SHIPPINGBILLMASTER.SBMID = SHIPPINGBILLDETAIL.SBMID  		   
  WHERE (dbo.GATEINDETAIL.GPSTYPE IN (1, 5)) AND (dbo.GATEINDETAIL.SDPTID = 2) and isnull(SHIPPINGBILLDETAIL.SBMID,0) = 0  AND
		(@FilterTerm IS NULL  OR GATEINDETAIL.AVHLNO LIKE @FilterTerm   ) 
		AND GATEINDETAIL.CHAID = @LCHAID  --AND (dbo.EXPORTSHIPPINGBILLMASTER.EXPRTID = @LEXPRTID)  
   GROUP BY dbo.GATEINDETAIL.AVHLNO, dbo.GATEINDETAIL.GIDID,EXPORTSHIPPINGBILLMASTER.ESBMDNO,EXPORTSHIPPINGBILLMASTER.ESBMID
      
 

  Select AVHLNO, GIDID 
	    FROM @TableMaster
        
END

