ALTER PROCEDURE [dbo].[PR_ExportSlabDuplicateCheck]
	@PSLABMDATE DATETIME,
	@PTARIFFMID int,
	@PCHRGETYPE int,
	@PCONTNRSID int,
	@PSDTYPE int,
	@PYRDTYPE int,
	@PWTYPE int,
	@PHTYPE int,
	@PCHAID int,
	@PSLABTID int,
	@PEOPTID int,
	@CNT int output
AS
BEGIN

	SET NOCOUNT ON;
	SELECT @CNT =COUNT(*) FROM EXPORTSLABMASTER WHERE (SLABMDATE=@PSLABMDATE ) AND (TARIFFMID=@PTARIFFMID) AND (CHRGETYPE=@PCHRGETYPE) AND (CONTNRSID=@PCONTNRSID) AND (SDTYPE=@PSDTYPE) AND (YRDTYPE=@PYRDTYPE) AND (WTYPE=@PWTYPE) 
	AND (HTYPE=@PHTYPE) AND (CHAID=@PCHAID) AND (SLABTID=@PSLABTID) AND (EOPTID = @PEOPTID)
	SELECT @CNT
	
	RETURN
END

