-- exec pr_Fetch_Orginal_Shipping_Bill_Detail @ESBMID =23545
-- exec pr_Fetch_Orginal_Shipping_Bill_Detail @ESBMID =22537
alter procedure pr_Fetch_Orginal_Shipping_Bill_Detail
@ESBMID int
as
begin
	select	EXPORTSHIPPINGBILLDETAIL.ESBDID, EXPORTSHIPPINGBILLDETAIL.ESBMID, EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO,
			EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLDATE, EXPORTSHIPPINGBILLDETAIL.ESBOINVNO, EXPORTSHIPPINGBILLDETAIL.ESBOINVDATE,
			EXPORTSHIPPINGBILLDETAIL.ESBOINVAMT, EXPORTSHIPPINGBILLDETAIL.ESBOINVFOBAMT, EXPORTSHIPPINGBILLDETAIL.ESBDDPNAME,
			EXPORTSHIPPINGBILLDETAIL.PRDTDESC, EXPORTSHIPPINGBILLDETAIL.ESBMNOP, EXPORTSHIPPINGBILLDETAIL.ESBMQTY, 
			SHIPPINGBILLMASTER.SBMID, EXPORTSHIPPINGBILLMASTER.ESBMDNO AS 'ESBMDDNO', EXPORTSHIPPINGBILLMASTER.PRDTDESC AS 'PRDDDESC',
			SHIPPINGBILLDETAIL.SBDQTY, SHIPPINGBILLDETAIL.SBDNOP
	FROM	SHIPPINGBILLDETAIL (nolock) Inner Join 
			SHIPPINGBILLMASTER (nolock) ON SHIPPINGBILLMASTER.SBMID = SHIPPINGBILLDETAIL.SBMID Left Join 
			EXPORTSHIPPINGBILLMASTER (nolock) ON SHIPPINGBILLDETAIL.ESBMID = EXPORTSHIPPINGBILLMASTER.ESBMID inner join
			EXPORTSHIPPINGBILLdetail (nolock) on EXPORTSHIPPINGBILLMASTER.ESBMID = EXPORTSHIPPINGBILLdetail.ESBMID Left join 
			GATEINDETAIL (nolock) ON SHIPPINGBILLDETAIL.GIDID = GATEINDETAIL.GIDID    
   WHERE	GATEINDETAIL.CONTNRID=1  and
		EXPORTSHIPPINGBILLdetail.ESBMID = @ESBMID

end

