alter PROCEDURE [dbo].[pr_Get_Finance_Transaction_Details]  
          @PTRANMID INT 
        , @PSDPTID Int
		, @PCHAID Int
        
AS BEGIN

Declare @LTRANMID int,@LSDPTID int , @LCHAID int
set @LTRANMID = @PTRANMID
set @LSDPTID = @PSDPTID 
set @LCHAID = @PCHAID


    DECLARE @TableMaster Table 
	( 
	  STRG_CGST_EXPRN numeric(18,0) not null,
	  STRG_IGST_EXPRN numeric(18,0) not null,
	  STRG_SGST_EXPRN numeric(18,0) not null,
	  HANDL_CGST_EXPRN numeric(18,0) not null,
	  HANDL_IGST_EXPRN numeric(18,0) not null,
	  HANDL_SGST_EXPRN numeric(18,0) not null,  
	  TRAND_STRG_CGST_AMT numeric(18,0) not null,
	  TRAND_STRG_IGST_AMT  numeric(18,0) not null,
	  TRAND_STRG_SGST_AMT  numeric(18,0) not null,
	  TRAND_HANDL_CGST_AMT numeric(18,0) not null,
	  TRAND_HANDL_IGST_AMT numeric(18,0) not null,
	  TRAND_HANDL_SGST_AMT numeric(18,0) not null,
	  STRG_CGST_AMT numeric(18,0) not null,
	  STRG_IGST_AMT numeric(18,0) not null,
	  STRG_SGST_AMT numeric(18,0) not null,
	  HANDL_CGST_AMT numeric(18,0) not null,
	  HANDL_IGST_AMT numeric(18,0) not null,
	  HANDL_SGST_AMT numeric(18,0) not null,
	  TRANCGSTAMT numeric(18,0) not null,
	  TRANIGSTAMT numeric(18,0) not null,
	  TRANSGSTAMT numeric(18,0) not null,
	  TRANGAMT numeric(18,0) not null,
	  TRANDGAMT numeric(18,0) not null,
	  TRANDNAMT numeric(18,0) not null,
	  TRANNAMT numeric(18,0) not null ,
	  TRANDATE Varchar(10) not null
	  
	)


   Insert Into  @TableMaster(STRG_CGST_EXPRN,STRG_IGST_EXPRN,STRG_SGST_EXPRN,
                          HANDL_CGST_EXPRN,HANDL_IGST_EXPRN,HANDL_SGST_EXPRN,
						  TRAND_STRG_CGST_AMT,TRAND_STRG_IGST_AMT,TRAND_STRG_SGST_AMT,
						  TRAND_HANDL_CGST_AMT,TRAND_HANDL_IGST_AMT,TRAND_HANDL_SGST_AMT,
						  STRG_CGST_AMT,STRG_IGST_AMT,STRG_SGST_AMT,
						  HANDL_CGST_AMT,HANDL_IGST_AMT,HANDL_SGST_AMT,
						  TRANCGSTAMT,TRANIGSTAMT,TRANSGSTAMT,TRANGAMT,
						  TRANDGAMT, TRANDNAMT,TRANNAMT ,TRANDATE )  
  SELECT TRANSACTIONMASTER.STRG_CGST_EXPRN,TRANSACTIONMASTER.STRG_IGST_EXPRN,TRANSACTIONMASTER.STRG_SGST_EXPRN,
         TRANSACTIONMASTER.HANDL_CGST_EXPRN, TRANSACTIONMASTER.HANDL_IGST_EXPRN, TRANSACTIONMASTER.HANDL_SGST_EXPRN , 
	     0,0,0,
         0, 0, 0 ,
	     0,0,0,
	     0,0,0,
	     0,0,0,0,
	     0,  0, 0,convert(varchar(10) ,TRANSACTIONMASTER.TRANDATE,103) as TRANDATE

 FROM TRANSACTIONMASTER (Nolock)
 WHERE TRANSACTIONMASTER.TRANMID = @LTRANMID  AND TRANSACTIONMASTER.SDPTID= @LSDPTID  AND TRANSACTIONMASTER.TRANREFID = @LCHAID 
 GROUP BY 
      TRANSACTIONMASTER.STRG_CGST_EXPRN,TRANSACTIONMASTER.STRG_IGST_EXPRN,TRANSACTIONMASTER.STRG_SGST_EXPRN, 
	  TRANSACTIONMASTER.HANDL_CGST_EXPRN, TRANSACTIONMASTER.HANDL_IGST_EXPRN, TRANSACTIONMASTER.HANDL_SGST_EXPRN , 
	  TRANSACTIONMASTER.STRG_CGST_AMT,TRANSACTIONMASTER.STRG_IGST_AMT,TRANSACTIONMASTER.STRG_SGST_AMT,
      TRANSACTIONMASTER.HANDL_CGST_AMT, TRANSACTIONMASTER.HANDL_IGST_AMT, TRANSACTIONMASTER.HANDL_SGST_AMT ,
	  TRANSACTIONMASTER.TRANNAMT ,TRANSACTIONMASTER.TRANDATE

  Select Isnull(STRG_CGST_EXPRN,0) as STRG_CGST_EXPRN, Isnull(STRG_IGST_EXPRN,0) as STRG_IGST_EXPRN,Isnull(STRG_SGST_EXPRN,0) as STRG_SGST_EXPRN,
	          Isnull(HANDL_CGST_EXPRN,0) as HANDL_CGST_EXPRN, Isnull(HANDL_IGST_EXPRN,0) as HANDL_IGST_EXPRN,Isnull(HANDL_SGST_EXPRN,0) as HANDL_SGST_EXPRN,
			   STRG_CGST_AMT, STRG_IGST_AMT,STRG_SGST_AMT,
			   HANDL_CGST_AMT,  HANDL_IGST_AMT, HANDL_SGST_AMT,
			  TRAND_STRG_CGST_AMT, TRAND_STRG_IGST_AMT,TRAND_STRG_SGST_AMT,
			  TRAND_HANDL_CGST_AMT, TRAND_HANDL_IGST_AMT,TRAND_HANDL_SGST_AMT,
			  TRANCGSTAMT,TRANIGSTAMT,TRANSGSTAMT,TRANGAMT,
			  TRANDGAMT, TRANDNAMT,TRANNAMT,TRANDATE
	    FROM @TableMaster
        
END

