
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- Exec pr_Import_HSN_Code_Wise_Invoice_Detail_Assgn '01-apr-2023', '31-mar-2024', 1
alter PROCEDURE pr_Import_HSN_Code_Wise_Invoice_Detail_Assgn
@PSDPTID int, @PSDate smalldatetime, @PEDate smalldatetime
AS
BEGIN

	SET NOCOUNT ON;

	Declare @TmpTable Table
	(
	   TRANMID int,
	   REGSTRID int,
	   TRANNO int,
	   TRANDNO varchar(100),
	   TRANDATE smalldatetime,
	   CATEAGSTNO varchar(30),
	   TRANREFNAME varchar(100),
	   STRG_HSNCODE varchar(25),
	   TRANSAMT numeric(18,2),
	   HANDL_HSNCODE varchar(25),
	   TRANDHAMT numeric(18,2),
	   TRANGAMT numeric(18,2),
	   CGSTAMT numeric(18,2),
	   SGSTAMT numeric(18,2),
	   IGSTAMT numeric(18,2),
	   TRANNAMT numeric(18,2)
	)
    
	--Import Invoice Register id 1
	Insert into @TmpTable(TRANMID, REGSTRID, TRANNO, TRANDNO, TRANDATE, CATEAGSTNO, TRANREFNAME, STRG_HSNCODE, TRANSAMT, HANDL_HSNCODE,
	                      TRANDHAMT, TRANGAMT, CGSTAMT, SGSTAMT, IGSTAMT, TRANNAMT)
    SELECT TOP (100) PERCENT dbo.TRANSACTIONMASTER.TRANMID, dbo.TRANSACTIONMASTER.REGSTRID, TRANNO, 
	dbo.TRANSACTIONMASTER.TRANDNO, dbo.TRANSACTIONMASTER.TRANDATE, dbo.TRANSACTIONMASTER.CATEAGSTNO, 
	dbo.TRANSACTIONMASTER.TRANREFNAME, dbo.TRANSACTIONMASTER.STRG_HSNCODE, dbo.TRANSACTIONMASTER.TRANSAMT, 
	dbo.TRANSACTIONMASTER.HANDL_HSNCODE,dbo.TRANSACTIONMASTER.TRANGAMT - dbo.TRANSACTIONMASTER.TRANSAMT + ISNULL(dbo.VW_TAXREGISTER_RPT_12.DEDVALUE, 0) AS TRANDHAMT, 
	dbo.TRANSACTIONMASTER.TRANGAMT + ISNULL(dbo.VW_TAXREGISTER_RPT_12.DEDVALUE, 0) AS TRANGAMT , dbo.TRANSACTIONMASTER.TRANCGSTAMT AS CGSTAMT, 
    dbo.TRANSACTIONMASTER.TRANSGSTAMT AS SGSTAMT, dbo.TRANSACTIONMASTER.TRANIGSTAMT AS IGSTAMT, dbo.TRANSACTIONMASTER.TRANNAMT
    FROM dbo.TRANSACTIONMASTER 
    LEFT OUTER JOIN dbo.VW_TAXREGISTER_RPT_12 ON dbo.TRANSACTIONMASTER.TRANMID = dbo.VW_TAXREGISTER_RPT_12.TRANMID
    WHERE (dbo.TRANSACTIONMASTER.REGSTRID = 1) 
    AND (dbo.TRANSACTIONMASTER.SDPTID = @PSDPTID)
    AND (dbo.TRANSACTIONMASTER.TRANDATE BETWEEN @PSDate AND @PEDate) 
    AND (dbo.TRANSACTIONMASTER.DISPSTATUS = 0)
    ORDER BY dbo.TRANSACTIONMASTER.TRANNO

	--Import Invoice Register id 2
	Insert into @TmpTable(TRANMID, REGSTRID, TRANNO, TRANDNO, TRANDATE, CATEAGSTNO, TRANREFNAME, STRG_HSNCODE, TRANSAMT, HANDL_HSNCODE,
	                      TRANDHAMT, TRANGAMT, CGSTAMT, SGSTAMT, IGSTAMT, TRANNAMT)
    SELECT TOP (100) PERCENT dbo.TRANSACTIONMASTER.TRANMID, dbo.TRANSACTIONMASTER.REGSTRID, TRANNO, 
	dbo.TRANSACTIONMASTER.TRANDNO, dbo.TRANSACTIONMASTER.TRANDATE, dbo.TRANSACTIONMASTER.CATEAGSTNO, 
	dbo.TRANSACTIONMASTER.TRANREFNAME, dbo.TRANSACTIONMASTER.STRG_HSNCODE, dbo.TRANSACTIONMASTER.TRANSAMT, 
	dbo.TRANSACTIONMASTER.HANDL_HSNCODE,dbo.TRANSACTIONMASTER.TRANGAMT - dbo.TRANSACTIONMASTER.TRANSAMT + ISNULL(dbo.VW_TAXREGISTER_RPT_12.DEDVALUE, 0) AS TRANDHAMT, 
	dbo.TRANSACTIONMASTER.TRANGAMT + ISNULL(dbo.VW_TAXREGISTER_RPT_12.DEDVALUE, 0) AS TRANGAMT , dbo.TRANSACTIONMASTER.TRANCGSTAMT AS CGSTAMT, 
    dbo.TRANSACTIONMASTER.TRANSGSTAMT AS SGSTAMT, dbo.TRANSACTIONMASTER.TRANIGSTAMT AS IGSTAMT, dbo.TRANSACTIONMASTER.TRANNAMT
    FROM dbo.TRANSACTIONMASTER 
    LEFT OUTER JOIN dbo.VW_TAXREGISTER_RPT_12 ON dbo.TRANSACTIONMASTER.TRANMID = dbo.VW_TAXREGISTER_RPT_12.TRANMID
    WHERE (dbo.TRANSACTIONMASTER.REGSTRID = 2) 
    AND (dbo.TRANSACTIONMASTER.SDPTID = @PSDPTID)
    AND (dbo.TRANSACTIONMASTER.TRANDATE BETWEEN @PSDate AND @PEDate) 
    AND (dbo.TRANSACTIONMASTER.DISPSTATUS = 0)
    ORDER BY dbo.TRANSACTIONMASTER.TRANNO

	--Import Invoice Register id 15 - manual bill
	Insert into @TmpTable(TRANMID, REGSTRID, TRANNO, TRANDNO, TRANDATE, CATEAGSTNO, TRANREFNAME, STRG_HSNCODE, TRANSAMT, HANDL_HSNCODE,
	                      TRANDHAMT, TRANGAMT, CGSTAMT, SGSTAMT, IGSTAMT, TRANNAMT)
    SELECT TOP (100) PERCENT dbo.TRANSACTIONMASTER.TRANMID, dbo.TRANSACTIONMASTER.REGSTRID, 
	dbo.TRANSACTIONMASTER.TRANNO, dbo.TRANSACTIONMASTER.TRANDNO, dbo.TRANSACTIONMASTER.TRANDATE, 
    dbo.TRANSACTIONMASTER.CATEAGSTNO, dbo.TRANSACTIONMASTER.TRANREFNAME, 
	CASE WHEN TRANDREFNAME LIKE '%STORAGE%' THEN TRANDREFNO ELSE '' END AS STRG_HSNCODE, 
    CASE WHEN TRANDREFNAME LIKE '%STORAGE%' THEN TRANDGAMT ELSE 0 END AS TRANDSAMT, 
	CASE WHEN TRANDREFNAME LIKE '%STORAGE%' THEN '' ELSE TRANDREFNO END AS HANDL_HSNCODE, 
    CASE WHEN TRANDREFNAME LIKE '%STORAGE%' THEN 0 ELSE TRANDGAMT END AS TRANDHAMT, 
	dbo.TRANSACTIONMASTER.TRANGAMT,dbo.TRANSACTIONMASTER.TRANCGSTAMT AS CGSTAMT, 
	dbo.TRANSACTIONMASTER.TRANSGSTAMT AS SGSTAMT,dbo.TRANSACTIONMASTER.TRANIGSTAMT AS IGSTAMT,
	dbo.TRANSACTIONMASTER.TRANNAMT
    FROM dbo.TRANSACTIONMASTER 
	INNER JOIN dbo.TRANSACTIONDETAIL ON dbo.TRANSACTIONMASTER.TRANMID = dbo.TRANSACTIONDETAIL.TRANMID 
	LEFT OUTER JOIN dbo.VW_TAXREGISTER_RPT_12 ON dbo.TRANSACTIONMASTER.TRANMID = dbo.VW_TAXREGISTER_RPT_12.TRANMID
    WHERE (dbo.TRANSACTIONMASTER.REGSTRID = 15) 
	AND (dbo.TRANSACTIONMASTER.TRANDATE BETWEEN @PSDate AND @PEDate) 
	AND (dbo.TRANSACTIONMASTER.DISPSTATUS = 0) AND (dbo.TRANSACTIONMASTER.SDPTID = @PSDPTID)
	GROUP BY dbo.TRANSACTIONMASTER.TRANMID, dbo.TRANSACTIONMASTER.REGSTRID, dbo.TRANSACTIONMASTER.TRANNO, 
	dbo.TRANSACTIONMASTER.TRANDNO, dbo.TRANSACTIONMASTER.TRANDATE,dbo.TRANSACTIONMASTER.CATEAGSTNO, 
	dbo.TRANSACTIONMASTER.TRANREFNAME, dbo.TRANSACTIONMASTER.TRANCGSTAMT, dbo.TRANSACTIONMASTER.TRANSGSTAMT, 
	dbo.TRANSACTIONMASTER.TRANIGSTAMT, dbo.TRANSACTIONMASTER.TRANGAMT, dbo.TRANSACTIONMASTER.TRANNAMT, 
	dbo.TRANSACTIONMASTER.DISPSTATUS, CASE WHEN TRANDREFNAME LIKE '%STORAGE%' THEN TRANDREFNO ELSE '' END, 
    CASE WHEN TRANDREFNAME LIKE '%STORAGE%' THEN TRANDGAMT ELSE 0 END, 
	CASE WHEN TRANDREFNAME LIKE '%STORAGE%' THEN '' ELSE TRANDREFNO END, 
    CASE WHEN TRANDREFNAME LIKE '%STORAGE%' THEN 0 ELSE TRANDGAMT END
    ORDER BY dbo.TRANSACTIONMASTER.TRANNO

    Select TRANDNO as [Invoice No.], TRANDATE as [Invoice Date], CATEAGSTNO as [GSTIN No.], 
	TRANREFNAME as [Party Name], STRG_HSNCODE as [Storage HSN Code], TRANSAMT as [Storage Amount], 
	HANDL_HSNCODE as [Handling HSN Code],TRANDHAMT as [Handling Amount], TRANGAMT as [Invoice Total], 
	CGSTAMT as [CGST], SGSTAMT as [SGST], IGSTAMT as [IGST], TRANNAMT as [Total Invoice Amoount] 
	From @TmpTable 
	Order by REGSTRID, TRANNO

END
GO
