-- exec [pr_Import_Performa_Invoice_IGMNO_Grid_Assgn] '2328915', '225', 0  
-- EXEC pr_Import_Performa_Invoice_IGMNO_Grid_Assgn @PIGMNO='-',@PLNO='-',@PTRANMID=430  
alter PROCEDURE [dbo].[pr_Import_Performa_Invoice_IGMNO_Grid_Assgn]  /* CHANGE */  
  @PIGMNO varchar(25), @PLNO varchar(10), @PTRANMID INT  
   
AS BEGIN  
  
    DECLARE @TableMaster TABLE  
    (   
   TRANREFID INT  
   ,TRANREFNAME VARCHAR(100)  
   ,BOENO VARCHAR(25)  
   ,BILLEMID INT  
   ,BILLEDID INT   
   ,GIDID INT  
   ,STMRID INT  
   ,STMRNAME VARCHAR(100)  
   ,IGMNO VARCHAR(25)  
   ,GPLNO VARCHAR(10)  
   ,CONTNRNO  VARCHAR(15)  
   ,CONTNRSDESC VARCHAR(15)  
   ,CONTNRSID INT  
   ,GIDATE SMALLDATETIME   
   ,STRGDATE SMALLDATETIME   
   ,GODATE SMALLDATETIME  
   ,GOTIME DATETIME  
   ,DODATE SMALLDATETIME  
   ,NOD NUMERIC(18,2)  
   ,WGHT  NUMERIC(18,4)  
   ,PRDTGID INT  
   ,TRANDID INT  
   ,TRANDOTYPE SMALLINT  
   ,TARIFFMID INT  
   ,DPAIDNO VARCHAR(50)  
   ,DPAIDAMT NUMERIC(18, 2)  
   ,GPEAMT NUMERIC(18, 2)  
   ,GPCSAMT NUMERIC(18, 2)  
   ,GPLBAMT NUMERIC(18, 2)  
   ,GPAAMT  NUMERIC(18, 2)  
   ,TRANDSAMT NUMERIC(18,2)  
   ,TRANDHAMT NUMERIC(18,2)  
   ,TRANDEAMT NUMERIC(18,2)  
   ,TRANDFAMT NUMERIC(18,2)  
   ,TRANDAAMT NUMERIC(18,2)  
   ,TRANDADONAMT NUMERIC(18,2)  
   ,TRANDNAMT NUMERIC(18,2)  
   ,RCOL1  NUMERIC(18,2)  
   ,RCOL2  NUMERIC(18,2)  
   ,RCOL3  NUMERIC(18,2)  
   ,RCOL4  NUMERIC(18,2)  
   ,RCOL5  NUMERIC(18,2)  
   ,RCOL6  NUMERIC(18,2)  
   ,RCOL7  NUMERIC(18,2)  
   ,RAMT1  NUMERIC(18,2)  
   ,RAMT2  NUMERIC(18,2)  
   ,RAMT3  NUMERIC(18,2)  
   ,RAMT4  NUMERIC(18,2)  
   ,RAMT5  NUMERIC(18,2)  
   ,RAMT6  NUMERIC(18,2)  
   ,RAMT7  NUMERIC(18,2)  
   ,RCAMT1  NUMERIC(18,2)  
   ,RCAMT2  NUMERIC(18,2)  
   ,RCAMT3  NUMERIC(18,2)  
   ,RCAMT4  NUMERIC(18,2)  
   ,RCAMT5  NUMERIC(18,2)  
   ,RCAMT6  NUMERIC(18,2)  
   ,RCAMT7  NUMERIC(18,2)  
    ,GPETYPE smallint  
    ,GPCSTYPE smallint  
    ,GPLBTYPE smallint  
   ,GPSTYPE smallint  
   ,GPWTYPE smallint  
   ,GPSCNTYPE smallint  
    ,TRANDRATE  NUMERIC(18,2)  
    , STATETYPE smallint  
    , STRG_HSN_CODE VARCHAR(10)  
    , HANDL_HSN_CODE VARCHAR(10)  
    ,STRG_TAXABLE_AMT  NUMERIC(18,2)  
    ,HANDL_TAXABLE_AMT  NUMERIC(18,2)  
    ,STRG_CGST_EXPRN  NUMERIC(18,2)  
    ,STRG_SGST_EXPRN  NUMERIC(18,2)  
    ,STRG_IGST_EXPRN  NUMERIC(18,2)  
    ,STRG_CGST_AMT  NUMERIC(18,2)  
    ,STRG_SGST_AMT  NUMERIC(18,2)  
    ,STRG_IGST_AMT  NUMERIC(18,2)  
    ,HANDL_CGST_EXPRN  NUMERIC(18,2)  
    ,HANDL_SGST_EXPRN  NUMERIC(18,2)  
    ,HANDL_IGST_EXPRN  NUMERIC(18,2)  
    ,HANDL_CGST_AMT  NUMERIC(18,2)  
    ,HANDL_SGST_AMT  NUMERIC(18,2)  
    ,HANDL_IGST_AMT  NUMERIC(18,2)  
    ,TRANCGSTAMT  NUMERIC(18,2)  
    ,TRANSGSTAMT  NUMERIC(18,2)  
    ,TRANIGSTAMT  NUMERIC(18,2)  
    ,TRAND_COVID_DISC_AMT NUMERIC(18,2)  
    )  
  
  
       
DECLARE @LIGMNO varchar(25), @LLNO varchar(10), @LTRANMID INT  
set @LIGMNO =@PIGMNO  
set @LLNO = @PLNO  
set @LTRANMID = @PTRANMID  
set nocount on  
  
--PENDING BOE CONTAINER NO  
--isnull(dbo.GATEOUTDETAIL.GODATE,@LEDATE)  
  
  
  
IF @LTRANMID  = 0    
  
 INSERT INTO @TableMaster(TRANREFID,TRANREFNAME,BOENO,BILLEMID,BILLEDID,GIDID,STMRID,STMRNAME,IGMNO,GPLNO,CONTNRNO,CONTNRSDESC,CONTNRSID,GIDATE,  
 STRGDATE,GODATE,GOTIME,DODATE,NOD,WGHT,PRDTGID,TRANDID,TRANDOTYPE,TARIFFMID,DPAIDNO,DPAIDAMT,GPEAMT,GPCSAMT,GPLBAMT,GPAAMT,TRANDSAMT,TRANDHAMT,  
 TRANDEAMT,TRANDFAMT,TRANDAAMT,TRANDADONAMT,  TRANDNAMT,RCOL1,RCOL2,RCOL3,RCOL4,RCOL5,RCOL6,RCOL7,RAMT1,RAMT2,RAMT3,RAMT4,RAMT5,RAMT6,RAMT7,RCAMT1,RCAMT2,  
 RCAMT3,RCAMT4,RCAMT5,RCAMT6,RCAMT7,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,TRANDRATE, STATETYPE, STRG_HSN_CODE, HANDL_HSN_CODE ,STRG_TAXABLE_AMT,  
 HANDL_TAXABLE_AMT,STRG_CGST_EXPRN,STRG_SGST_EXPRN,STRG_IGST_EXPRN,STRG_CGST_AMT,STRG_SGST_AMT,  
 STRG_IGST_AMT,HANDL_CGST_EXPRN,HANDL_SGST_EXPRN,HANDL_IGST_EXPRN,HANDL_CGST_AMT,HANDL_SGST_AMT,  
 HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT)  
   
 SELECT DISTINCT   
        dbo.OPENSHEETMASTER.OSBILLREFID, dbo.OPENSHEETMASTER.OSBILLREFNAME, dbo.BILLENTRYMASTER.BILLEMDNO, dbo.BILLENTRYMASTER.BILLEMID,dbo.BILLENTRYDETAIL.BILLEDID,  
        dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.STMRID,GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.CONTNRNO,   
        dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.CONTNRSID, dbo.GATEINDETAIL.GIDATE,   
        dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN.XGIDATE AS STRGDATE, dbo.GATEOUTDETAIL.GODATE, dbo.GATEOUTDETAIL.GOTIME,   
        dbo.OPENSHEETMASTER.DODATE, 0 AS NOD, dbo.GATEINDETAIL.GPWGHT, dbo.GATEINDETAIL.PRDTGID, 0 AS TRANDID, 0 AS TRANDOTYPE, 0 AS TARIFFMID,   
        dbo.BILLENTRYMASTER.DPAIDNO, dbo.BILLENTRYMASTER.DPAIDAMT, dbo.GATEINDETAIL.GPEAMT, dbo.GATEINDETAIL.GPCSAMT,dbo.GATEINDETAIL.GPLBAMT,  
         dbo.GATEINDETAIL.GPAAMT,  
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,0, isnull(STATETYPE,0),  
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0  
 FROM         dbo.GATEINDETAIL (nolock)left JOIN dbo.BILLENTRYDETAIL (nolock) ON dbo.GATEINDETAIL.GIDID = dbo.BILLENTRYDETAIL.GIDID left JOIN  
        dbo.BILLENTRYMASTER (nolock)   ON dbo.BILLENTRYDETAIL.BILLEMID = dbo.BILLENTRYMASTER.BILLEMID left JOIN  
        dbo.OPENSHEETDETAIL (nolock)  ON dbo.GATEINDETAIL.GIDID = dbo.OPENSHEETDETAIL.GIDID left JOIN  
        dbo.OPENSHEETMASTER (nolock)   on dbo.OPENSHEETMASTER.OSMID = dbo.OPENSHEETDETAIL.OSMID LEFT OUTER JOIN   
        dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN (nolock)  ON dbo.BILLENTRYMASTER.BILLEMID = dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN.BILLEMID left JOIN          
        dbo.CONTAINERSIZEMASTER (nolock)  ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID left JOIN  
        dbo.GATEOUTDETAIL (nolock)  ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID LEFT OUTER JOIN  
        dbo.VW_IMPORT_PERFORMA_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01 (nolock)  ON   
        dbo.BILLENTRYDETAIL.BILLEDID = dbo.VW_IMPORT_PERFORMA_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.BILLEDID left JOIN  
                         dbo.CATEGORYMASTER  (nolock) ON dbo.OPENSHEETMASTER.OSBILLREFID = dbo.CATEGORYMASTER.CATEID LEFT OUTER JOIN  
                         dbo.STATEMASTER  (nolock) ON dbo.CATEGORYMASTER.STATEID = dbo.STATEMASTER.STATEID  
 WHERE     (ISNULL(dbo.VW_IMPORT_PERFORMA_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDID, 0) >= 0) AND (dbo.GATEINDETAIL.SDPTID = 1) AND   
        (dbo.GATEINDETAIL.IGMNO = @LIGMNO) AND (dbo.GATEINDETAIL.GPLNO = @LLNO)  
  
ELSE  
                        
--ACTUAL STUFF INVOICE DETAIL  
  
 INSERT INTO @TableMaster(TRANREFID,TRANREFNAME,BOENO,BILLEMID,BILLEDID,GIDID,STMRID,STMRNAME,IGMNO,GPLNO,CONTNRNO,CONTNRSDESC,CONTNRSID,GIDATE,  
 STRGDATE,GODATE,GOTIME,DODATE,NOD,WGHT,PRDTGID,TRANDID,TRANDOTYPE,TARIFFMID,DPAIDNO,DPAIDAMT,GPEAMT,GPCSAMT,GPLBAMT,GPAAMT,TRANDSAMT,TRANDHAMT,  
 TRANDEAMT,TRANDFAMT,TRANDAAMT,TRANDADONAMT,  TRANDNAMT,RCOL1,RCOL2,RCOL3,RCOL4,RCOL5,RCOL6,RCOL7,RAMT1,RAMT2,RAMT3,RAMT4,RAMT5,RAMT6,RAMT7,RCAMT1,RCAMT2,  
 RCAMT3,RCAMT4,RCAMT5,RCAMT6,RCAMT7,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,TRANDRATE, STATETYPE, STRG_HSN_CODE, HANDL_HSN_CODE ,STRG_TAXABLE_AMT,  
 HANDL_TAXABLE_AMT,STRG_CGST_EXPRN,STRG_SGST_EXPRN,STRG_IGST_EXPRN,STRG_CGST_AMT,STRG_SGST_AMT,  
 STRG_IGST_AMT,HANDL_CGST_EXPRN,HANDL_SGST_EXPRN,HANDL_IGST_EXPRN,HANDL_CGST_AMT,HANDL_SGST_AMT,  
 HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT)  
  
  
 SELECT     dbo.PERFORMA_TRANSACTIONMASTER.TRANREFID, dbo.PERFORMA_TRANSACTIONMASTER.TRANREFNAME, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDREFNO AS BOENO,   
        dbo.BILLENTRYMASTER.BILLEMID,dbo.PERFORMA_TRANSACTIONDETAIL.BILLEDID, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDREFID AS GIDID, dbo.GATEINDETAIL.STMRID,GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.IGMNO,   
        dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.CONTNRSID,   
        dbo.PERFORMA_TRANSACTIONDETAIL.TRANIDATE, dbo.PERFORMA_TRANSACTIONDETAIL.TRANSDATE, dbo.PERFORMA_TRANSACTIONDETAIL.TRANEDATE, dbo.GATEOUTDETAIL.GOTIME,   
        dbo.PERFORMA_TRANSACTIONDETAIL.TRANVDATE, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDQTY, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDWGHT, dbo.GATEINDETAIL.PRDTGID,   
        dbo.PERFORMA_TRANSACTIONDETAIL.TRANDID, dbo.PERFORMA_TRANSACTIONDETAIL.TRANOTYPE, dbo.PERFORMA_TRANSACTIONDETAIL.TARIFFMID, dbo.BILLENTRYMASTER.DPAIDNO,   
        dbo.BILLENTRYMASTER.DPAIDAMT, dbo.GATEINDETAIL.GPEAMT, dbo.GATEINDETAIL.GPCSAMT, dbo.GATEINDETAIL.GPLBAMT,dbo.GATEINDETAIL.GPAAMT, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDSAMT,   
        dbo.PERFORMA_TRANSACTIONDETAIL.TRANDHAMT, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDEAMT, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDFAMT, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDAAMT,  
        isnull(dbo.PERFORMA_TRANSACTIONDETAIL.TRANDADONAMT,0) as TRANDADONAMT,   
        dbo.PERFORMA_TRANSACTIONDETAIL.TRANDNAMT, dbo.PERFORMA_TRANSACTIONDETAIL.RCOL1, dbo.PERFORMA_TRANSACTIONDETAIL.RCOL2, dbo.PERFORMA_TRANSACTIONDETAIL.RCOL3,   
        dbo.PERFORMA_TRANSACTIONDETAIL.RCOL4, dbo.PERFORMA_TRANSACTIONDETAIL.RCOL5, dbo.PERFORMA_TRANSACTIONDETAIL.RCOL6, dbo.PERFORMA_TRANSACTIONDETAIL.RCOL7, dbo.PERFORMA_TRANSACTIONDETAIL.RAMT1,   
        dbo.PERFORMA_TRANSACTIONDETAIL.RAMT2, dbo.PERFORMA_TRANSACTIONDETAIL.RAMT3, dbo.PERFORMA_TRANSACTIONDETAIL.RAMT4, dbo.PERFORMA_TRANSACTIONDETAIL.RAMT5,   
        dbo.PERFORMA_TRANSACTIONDETAIL.RAMT6, dbo.PERFORMA_TRANSACTIONDETAIL.RAMT7, dbo.PERFORMA_TRANSACTIONDETAIL.RCAMT1, dbo.PERFORMA_TRANSACTIONDETAIL.RCAMT2, dbo.PERFORMA_TRANSACTIONDETAIL.RCAMT3,   
        dbo.PERFORMA_TRANSACTIONDETAIL.RCAMT4, dbo.PERFORMA_TRANSACTIONDETAIL.RCAMT5, dbo.PERFORMA_TRANSACTIONDETAIL.RCAMT6, dbo.PERFORMA_TRANSACTIONDETAIL.RCAMT7,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,  
        dbo.PERFORMA_TRANSACTIONDETAIL.TRANDRATE,isnull(STATETYPE,0), STRG_HSNCODE, HANDL_HSNCODE, STRG_TAXABLE_AMT, HANDL_TAXABLE_AMT, STRG_CGST_EXPRN, STRG_SGST_EXPRN, STRG_IGST_EXPRN,   
                         STRG_CGST_AMT, STRG_SGST_AMT, STRG_IGST_AMT, HANDL_CGST_EXPRN, HANDL_SGST_EXPRN, HANDL_IGST_EXPRN, HANDL_CGST_AMT,   
                         HANDL_SGST_AMT, HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT  
  
 FROM         dbo.PERFORMA_TRANSACTIONMASTER (nolock) INNER JOIN  
        dbo.PERFORMA_TRANSACTIONDETAIL (nolock) ON dbo.PERFORMA_TRANSACTIONMASTER.TRANMID = dbo.PERFORMA_TRANSACTIONDETAIL.TRANMID left JOIN  
        dbo.GATEINDETAIL  (nolock)ON dbo.PERFORMA_TRANSACTIONDETAIL.TRANDREFID = dbo.GATEINDETAIL.GIDID left JOIN  
        dbo.BILLENTRYDETAIL (nolock) ON dbo.PERFORMA_TRANSACTIONDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID left JOIN            
        dbo.CONTAINERSIZEMASTER  (nolock)ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID LEFT OUTER JOIN  
        dbo.GATEOUTDETAIL  (nolock)ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID left JOIN  
        dbo.BILLENTRYMASTER  (nolock)ON dbo.BILLENTRYDETAIL.BILLEMID = dbo.BILLENTRYMASTER.BILLEMID left  JOIN  
        dbo.OPENSHEETDETAIL  (nolock)ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.OPENSHEETDETAIL.BILLEDID left JOIN  
        dbo.OPENSHEETMASTER  (nolock)ON dbo.OPENSHEETDETAIL.OSMID = dbo.OPENSHEETMASTER.OSMID left JOIN  
                         dbo.CATEGORYMASTER (nolock) ON dbo.PERFORMA_TRANSACTIONMASTER.TRANREFID = dbo.CATEGORYMASTER.CATEID LEFT OUTER JOIN  
                         dbo.STATEMASTER (nolock)ON dbo.CATEGORYMASTER.STATEID = dbo.STATEMASTER.STATEID  
 WHERE     (dbo.PERFORMA_TRANSACTIONMASTER.TRANMID = @LTRANMID)  
  
  
  
  
SELECT *  
 --TRANREFID,TRANREFNAME,BOENO,BILLEMID,BILLEDID,GIDID,STMRID,STMRNAME,IGMNO,GPLNO,CONTNRNO,CONTNRSDESC,CONTNRSID,GIDATE,  
 --STRGDATE,GODATE,GOTIME,DODATE,NOD,WGHT,PRDTGID,TRANDID,TRANDOTYPE,TARIFFMID,DPAIDNO,DPAIDAMT,GPEAMT,GPCSAMT,GPLBAMT,GPAAMT,TRANDSAMT,TRANDHAMT,  
 --TRANDEAMT,TRANDFAMT,TRANDAAMT,TRANDNAMT,RCOL1,RCOL2,RCOL3,RCOL4,RCOL5,RCOL6,RCOL7,RAMT1,RAMT2,RAMT3,RAMT4,RAMT5,RAMT6,RAMT7,RCAMT1,RCAMT2,  
 --RCAMT3,RCAMT4,RCAMT5,RCAMT6,RCAMT7,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,TRANDRATE, STATETYPE, STRG_HSN_CODE, HANDL_HSN_CODE ,STRG_TAXABLE_AMT,  
 --HANDL_TAXABLE_AMT,STRG_CGST_EXPRN,STRG_SGST_EXPRN,STRG_IGST_EXPRN,STRG_CGST_AMT,STRG_SGST_AMT,  
 --STRG_IGST_AMT,HANDL_CGST_EXPRN,HANDL_SGST_EXPRN,HANDL_IGST_EXPRN,HANDL_CGST_AMT,HANDL_SGST_AMT,  
 --HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT  
  
FROM @TableMaster   
order by BILLEDID  
  
  
  
--return   
         
END