-- EXEC [pr_Import_DO_Invoice_IGMNO_Grid_Assgn]  2
ALTER PROCEDURE [dbo].[pr_Import_DO_Invoice_IGMNO_Grid_Assgn]  /* CHANGE */
		@PDONO INT
 
AS BEGIN

    DECLARE @TableMaster TABLE
    ( 
	  DONO INT,
	  DODNO VARCHAR(25),
	  DODATE VARCHAR(10),
	  GIDID INT,
	  IGMNO VARCHAR(25),
	  GPLNO VARCHAR(10),
	  CONTNRNO  VARCHAR(15),
	  CONTNRSID INT,
	  CONTNRDESC VARCHAR(25),
	  CHANAME VARCHAR(100),
	  CHAID INT,
	  TRANBTYPE INT
    )


		   
DECLARE @LDONO INT
set @LDONO =@PDONO

set nocount on

--PENDING BOE CONTAINER NO
--isnull(dbo.GATEOUTDETAIL.GODATE,@LEDATE)


	INSERT INTO @TableMaster( DONO,  DODNO , DODATE , GIDID , IGMNO , GPLNO , CONTNRNO ,CONTNRSID, CONTNRDESC, CHANAME, CHAID)
	
	SELECT DISTINCT 
						  DELIVERYORDERMASTER.DONO, DELIVERYORDERMASTER.DODNO, CONVERT(VARCHAR(10),DELIVERYORDERMASTER.DODATE,103),
						  GATEINDETAIL.GIDID, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.CONTNRNO,
						  DBO.GATEINDETAIL.CONTNRSID, DBO.CONTAINERSIZEMASTER.CONTNRSDESC, 
						  OPENSHEETMASTER.OSBILLREFNAME, OPENSHEETMASTER.OSBILLREFID
	FROM         dbo.OPENSHEETMASTER INNER JOIN
						  dbo.BILLENTRYMASTER INNER JOIN
						  dbo.BILLENTRYDETAIL ON dbo.BILLENTRYMASTER.BILLEMID = dbo.BILLENTRYDETAIL.BILLEMID INNER JOIN
						  dbo.GATEINDETAIL ON dbo.BILLENTRYDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
						  dbo.DELIVERYORDERDETAIL on dbo.GATEINDETAIL.GIDID = dbo.DELIVERYORDERDETAIL.DODREFID INNER JOIN
						  dbo.DELIVERYORDERMASTER on dbo.DELIVERYORDERMASTER.DOMID = dbo.DELIVERYORDERDETAIL.DOMID INNER JOIN
						  dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
						  dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN ON dbo.BILLENTRYMASTER.BILLEMID = dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN.BILLEMID INNER JOIN
						  dbo.OPENSHEETDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.OPENSHEETDETAIL.GIDID ON 
						  dbo.OPENSHEETMASTER.OSMID = dbo.OPENSHEETDETAIL.OSMID LEFT OUTER JOIN
						  dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID LEFT OUTER JOIN
						  dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01 ON 
						  dbo.BILLENTRYDETAIL.BILLEDID = dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.BILLEDID INNER JOIN
                         dbo.CATEGORYMASTER ON dbo.OPENSHEETMASTER.OSBILLREFID = dbo.CATEGORYMASTER.CATEID LEFT OUTER JOIN
                         dbo.STATEMASTER ON dbo.CATEGORYMASTER.STATEID = dbo.STATEMASTER.STATEID
	WHERE     (ISNULL(dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDID, 0) = 0) AND (dbo.BILLENTRYMASTER.SDPTID = 1) AND 
						  (dbo.DELIVERYORDERMASTER.DONO = @LDONO) 

INSERT INTO @TableMaster( DONO,  DODNO , DODATE , GIDID , IGMNO , GPLNO , CONTNRNO ,CONTNRSID, CONTNRDESC, CHANAME, CHAID)
select		TRANLMID, TRANLMNO, TRANLMDATE, DODREFID, IGMNO, GPLNO, dbo.GATEINDETAIL.CONTNRNO, CNTNRSID, CONTAINERSIZEMASTER.CONTNRSDESC, BCHANAME, BCHAID
FROM         dbo.TRANSACTIONMASTER 
					inner join DELIVERYORDERDETAIL on TRANLMID = DOMID
					inner join dbo.GateInDetail on DODREFID = GIDID 
								INNER JOIN dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID 
WHERE TRANLMID = @PDONO

	UPDATE @TableMaster
	SET TRANBTYPE  = C.ASLMTYPE
	FROM @TableMaster A JOIN AUTHORIZATIONSLIPDETAIL B JOIN AUTHORIZATIONSLIPMASTER C ON B.ASLMID = C.ASLMID
	ON A.GIDID =  B.GIDID 
	WHERE C.SDPTID = 1
SELECT	* FROM @TableMaster 


--return 
       
END

