ALTER PROCEDURE [dbo].[PR_IMPORT_GATEIN_CONTAINER_CHK_ASSGN] @PCONTNRNO VARCHAR(15)  AS

SELECT     dbo.GATEINDETAIL.CONTNRNO, MAX(dbo.GATEOUTDETAIL.GODATE) AS GODATE, MAX(dbo.GATEOUTDETAIL.GODATE + 10) AS GEDATE
FROM         dbo.GATEINDETAIL INNER JOIN
                      dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID and GATEOUTDETAIL.SDPTID = GATEINDETAIL.SDPTID
WHERE GATEINDETAIL.SDPTID = 1
GROUP BY dbo.GATEINDETAIL.CONTNRNO
HAVING      (dbo.GATEINDETAIL.CONTNRNO = @PCONTNRNO)