alter PROCEDURE [dbo].[pr_IGMNO_Search_ContainerNo_GridAssgn] @PIGNNo varchar(15), @PGPLNo varchar(10)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SELECT  MAX(GATEINDETAIL.GIDID) as GIDID, GATEINDETAIL.CONTNRNO,CONTAINERSIZEMASTER.CONTNRSCODE,
	Convert(varchar(10) ,GATEINDETAIL.GIDATE,103) as GIDATE,
	Isnull(Convert(varchar(10) ,GATEOUTDETAIL.GODATE,103),'') as GODATE,
	isnull(OPENSHEETMASTER.BOENO,'-') as BOENO,isnull(BILLENTRYMASTER.BLNO,'-') as BLNO,
	isnull(GATEINDETAIL.LPSEALNO,'-') as LPSEALNO,isnull(GATEINDETAIL.CSEALNO,'-') as CSEALNO,
	isnull(GPMODEMASTER.GPMODEDESC,'') as GPMODEDESC,
	(case when AUTHORIZATIONSLIPMASTER.ASLMTYPE = 1 then 'Load' when AUTHORIZATIONSLIPMASTER.ASLMTYPE = 2 then 'Destuff' else '-' end) as SLIPTYPE,
	(case when OPENSHEETDETAIL.INSPTYPE = 1 then 'Yes' when OPENSHEETDETAIL.INSPTYPE = 0 then 'No' else '-' end) as INSPTYPE,
	(case when GATEINDETAIL.GPSCNTYPE = 1 then 'Yes' when GATEINDETAIL.GPSCNTYPE = 0 then 'No' else '-' end) as Scaned,
	(case when GATEIN_BLOCK_DETAILS.GBSTYPE = 1 then 'UnBlock' when GATEIN_BLOCK_DETAILS.GBSTYPE = 0 then 'Block' else '-' end) as Blocked,
	ROWDESC 'RowDesc'
	FROM  dbo.GATEINDETAIL (nolock) inner Join 
	CONTAINERSIZEMASTER (nolock) on  GATEINDETAIL.CONTNRSID = CONTAINERSIZEMASTER.CONTNRSID 
	Inner Join 	GPMODEMASTER (nolock) on GATEINDETAIL.GPMODEID = GPMODEMASTER.GPMODEID 
	Left Join	OPENSHEETDETAIL (nolock) on GATEINDETAIL.GIDID = OPENSHEETDETAIL.GIDID 	
	Left Join  	OPENSHEETMASTER (nolock) on OPENSHEETDETAIL.OSMID = OPENSHEETMASTER.OSMID 
	Left Join 	GATEOUTDETAIL (nolock) on GATEINDETAIL.GIDID = GATEOUTDETAIL.GIDID 
	Left Join 	BILLENTRYDETAIL (nolock) on OPENSHEETDETAIL.BILLEDID =  BILLENTRYDETAIL.GIDID 
	Left Join 	BILLENTRYMASTER (nolock) on BILLENTRYDETAIL.BILLEMID =  BILLENTRYMASTER.BILLEMID 	
	Left Join 	GATEIN_BLOCK_DETAILS (nolock) on GATEINDETAIL.GIDID =  GATEIN_BLOCK_DETAILS.GIDID 
	Left Join 	AUTHORIZATIONSLIPDETAIL (nolock) on GATEINDETAIL.GIDID = AUTHORIZATIONSLIPDETAIL.GIDID 
	Left join 	AUTHORIZATIONSLIPMASTER (nolock) on AUTHORIZATIONSLIPDETAIL.ASLMID = AUTHORIZATIONSLIPMASTER.ASLMID 
	Left join 	ROWMASTER (nolock) on GATEINDETAIL.ROWID = ROWMASTER.ROWID
	WHERE GATEINDETAIL.IGMNO =  @PIGNNo AND GATEINDETAIL.GPLNO = @PGPLNo and GATEINDETAIL.CONTNRSID > 0 --and AUTHORIZATIONSLIPMASTER.ASLMTYPE in (1,2)    
	GROUP BY GATEINDETAIL.GIDID,GATEINDETAIL.CONTNRNO,CONTAINERSIZEMASTER.CONTNRSCODE,
	GATEINDETAIL.GIDATE,GATEOUTDETAIL.GODATE,OPENSHEETMASTER.BOENO,BILLENTRYMASTER.BLNO,GATEINDETAIL.LPSEALNO,
	GATEINDETAIL.CSEALNO,GPMODEMASTER.GPMODEDESC,AUTHORIZATIONSLIPMASTER.ASLMTYPE,OPENSHEETDETAIL.INSPTYPE,
	GATEINDETAIL.GPSCNTYPE,GATEIN_BLOCK_DETAILS.GBSTYPE, ROWDESC	
	ORDER BY dbo.GATEINDETAIL.CONTNRNO

END
