
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- EXEC pr_Import_New_Opensheet_Customs_Report '01-JAN-2024', '31-DEC-2024'
CREATE PROCEDURE pr_Import_New_Opensheet_Customs_Report
@PSDate smalldatetime, @PEDate smalldatetime
AS
BEGIN

	SET NOCOUNT ON;

	SELECT        TOP (100) PERCENT dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_02.OSMDATE AS [Opensheet Date], dbo.GATEINDETAIL.GIDATE AS [In Date], RIGHT(dbo.GATEINDETAIL.GITIME, 8) AS [In Time], 
							 dbo.GATEINDETAIL.IGMNO AS [IGM No], dbo.GATEINDETAIL.GPLNO AS [Line No], dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_02.BILLEMNO AS [BOE No], 
							 dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_02.BILLEMDATE AS [BOE Date], dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_02.OSMTYPEDESC AS [Open/RMS], dbo.GATEINDETAIL.CONTNRNO AS [Container No], 
							 dbo.CONTAINERSIZEMASTER.CONTNRSDESC AS Size, dbo.CONTAINERTYPEMASTER.CONTNRTDESC AS Type, dbo.CATEGORYMASTER.CATENAME AS [CHA Name], dbo.GATEINDETAIL.STMRNAME AS [Steamer Name], 
							 dbo.GATEINDETAIL.IMPRTNAME AS [Importer Name], dbo.GATEINDETAIL.VSLNAME AS [Vessel Name], dbo.GATEINDETAIL.VOYNO AS [Voy No], dbo.GPMODEMASTER.GPMODEDESC AS [Doc. Type], 
							 dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_02.OOCNO AS [OOC No.], dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_02.OOCDATE AS [OOC Date], dbo.GATEINDETAIL.LPSEALNO AS [L Seal No], 
							 dbo.GATEINDETAIL.BLNO AS [BL No], dbo.GATEINDETAIL.PRDTDESC AS [Product Description], dbo.GATEINDETAIL.GICCTLTIME AS [Port Out Date & Time], (CASE GPSCNTYPE WHEN 0 THEN 'No' ELSE 'Yes' END) AS Scan
	FROM            dbo.CONTAINERSIZEMASTER INNER JOIN
							 dbo.GATEINDETAIL INNER JOIN
							 dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID ON dbo.CONTAINERSIZEMASTER.CONTNRSID = dbo.GATEINDETAIL.CONTNRSID LEFT OUTER JOIN
							 dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_02 ON dbo.GATEINDETAIL.GIDID = dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_02.GIDID LEFT OUTER JOIN
							 dbo.SLOTMASTER LEFT OUTER JOIN
							 dbo.ROWMASTER ON dbo.SLOTMASTER.ROWID = dbo.ROWMASTER.ROWID ON dbo.GATEINDETAIL.SLOTID = dbo.SLOTMASTER.SLOTID LEFT OUTER JOIN
							 dbo.CATEGORYMASTER ON dbo.GATEOUTDETAIL.CHAID = dbo.CATEGORYMASTER.CATEID LEFT OUTER JOIN
							 dbo.GPMODEMASTER ON dbo.GATEINDETAIL.GPMODEID = dbo.GPMODEMASTER.GPMODEID LEFT OUTER JOIN
							 dbo.CONTAINERTYPEMASTER ON dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID
	WHERE        (dbo.GATEINDETAIL.SDPTID = 1) 
	AND (dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_02.OSMDATE BETWEEN @PSDate AND @PEDate)
	ORDER BY [Opensheet Date]
END
GO
