-- [pr_EInvoice_Import_Manual_Transaction_Detail_Assgn] 3887
alter  PROCEDURE [dbo].[pr_Import_EmptyGatein_Detail_Assgn] @PCONTNRNO varchar(50)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    DECLARE @TableMaster TABLE
    ( 
	   GIDNO int,
	   GIDATE varchar(15),	 
	   CONTNRNO varchar(20),
	   VTDATE varchar(20),
	   ASLMDATE  varchar(20) 
	  
    )
	

	Insert into @TableMaster(GIDNO, GIDATE, CONTNRNO, VTDATE, ASLMDATE)

	SELECT GATEINDETAIL.GIDNO, convert(varchar(10),GIDATE,103) as GIDATE,GATEINDETAIL.CONTNRNO ,
	--convert(varchar(10),VEHICLETICKETDETAIL.VTDATE,103) as VTDATE,
	--isnull(convert(varchar(10),AUTHORIZATIONSLIPMASTER.ASLMDATE,103) ,'') as ASLMDATE , 
	isnull(convert(varchar(10),easlm.ASLMDATE,103) ,'') as ASLMDATE , 
	convert(varchar(10),ego.GODATE,103) as VTDATE
	FROM GATEINDETAIL Left Join  
	VEHICLETICKETDETAIL (nolock) on GATEINDETAIL.GIDID = VEHICLETICKETDETAIL.EGIDID Left Join  
	AUTHORIZATIONSLIPDETAIL (nolock) on VEHICLETICKETDETAIL.GIDID = AUTHORIZATIONSLIPDETAIL.GIDID Left Join  
	AUTHORIZATIONSLIPMASTER (nolock) On AUTHORIZATIONSLIPDETAIL.ASLMID = AUTHORIZATIONSLIPMASTER.ASLMID left join
	GATEOUTDETAIL ego(nolock) on ego.SDPTID=3 and GATEINDETAIL.GIDID = ego.GIDID left join
	AUTHORIZATIONSLIPDETAIL easld(nolock) on GATEINDETAIL.GIDID = easld.GIDID left join
	AUTHORIZATIONSLIPMASTER easlm(nolock) on easld.ASLMID = easlm.ASLMID
	WHERE  GATEINDETAIL.SDPTID=3 and GATEINDETAIL.CONTNRNO  = @PCONTNRNO 	
	GROUP BY GIDATE,CONTNRNO,ego.GODATE,easlm.ASLMDATE,GIDNO 

	--SELECT GATEINDETAIL.GIDNO, convert(varchar(10),GIDATE,103) as GIDATE,GATEINDETAIL.CONTNRNO ,
	--convert(varchar(10),VEHICLETICKETDETAIL.VTDATE,103) as VTDATE,
	--isnull(convert(varchar(10),AUTHORIZATIONSLIPMASTER.ASLMDATE,103) ,'') as ASLMDATE  FROM GATEINDETAIL Left Join  
	--VEHICLETICKETDETAIL (nolock) on GATEINDETAIL.GIDID = VEHICLETICKETDETAIL.EGIDID Left Join  
	--AUTHORIZATIONSLIPDETAIL (nolock) on GATEINDETAIL.GIDID = AUTHORIZATIONSLIPDETAIL.OSDID Inner Join  
	--AUTHORIZATIONSLIPMASTER (nolock) On AUTHORIZATIONSLIPDETAIL.ASLMID = AUTHORIZATIONSLIPMASTER.ASLMID  
	--WHERE ASLMTYPE=3 and GATEINDETAIL.SDPTID=3 and GATEINDETAIL.CONTNRNO  = @PCONTNRNO 
	--GROUP BY GIDATE,CONTNRNO,VTDATE,ASLMDATE,GIDNO 

	

	Select * From @TableMaster

END



