alter PROCEDURE [dbo].[PR_IMPORT_AUTHORIZATION_DETAIL_CTRL_ASSGN] @PASLMID INT
	
AS
BEGIN
	
	SET NOCOUNT ON;

DECLARE @LASLMID INT
SET @LASLMID = @PASLMID

SELECT     dbo.AUTHORIZATIONSLIPMASTER.ASLMID, dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                      dbo.GATEINDETAIL.GIDATE, dbo.OPENSHEETMASTER.OSMDNO, dbo.GATEINDETAIL.BOENO, 
					  isnull(dbo.GATEINDETAIL.BOEDATE, '') as BOEDATE,
                      dbo.OPENSHEETMASTER.DODATE, dbo.GATEINDETAIL.LPSEALNO AS LSEALNO, dbo.GATEINDETAIL.CSEALNO AS SSEALNO, 
					  dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO,dbo.AUTHORIZATIONSLIPDETAIL.GIDID, 
					  dbo.OPENSHEETMASTER.OSMIGMNO, 
                      dbo.OPENSHEETMASTER.OSMLNO, dbo.OPENSHEETDETAIL.OSDID,
					  ISNULL(dbo.GATEINDETAIL.VOYNO,'') AS VOYNO,ISNULL(dbo.GATEINDETAIL.VSLNAME,'') AS VSLNAME,
					  ISNULL(dbo.GATEINDETAIL.STMRNAME,'') AS STMRNAME,ISNULL(dbo.GATEINDETAIL.IMPRTNAME,'') AS IMPRTNAME
FROM         dbo.AUTHORIZATIONSLIPMASTER INNER JOIN
                      dbo.AUTHORIZATIONSLIPDETAIL ON dbo.AUTHORIZATIONSLIPMASTER.ASLMID = dbo.AUTHORIZATIONSLIPDETAIL.ASLMID LEFT JOIN
                      dbo.OPENSHEETDETAIL ON dbo.AUTHORIZATIONSLIPDETAIL.OSDID = dbo.OPENSHEETDETAIL.OSDID INNER JOIN
                      dbo.OPENSHEETMASTER ON dbo.OPENSHEETDETAIL.OSMID = dbo.OPENSHEETMASTER.OSMID LEFT JOIN
                      dbo.GATEINDETAIL ON dbo.AUTHORIZATIONSLIPDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID
WHERE       dbo.AUTHORIZATIONSLIPMASTER.ASLMID  = @LASLMID     
ORDER BY ASLDID     
                      
   
END

