    
-- EXEC [pr_Import_Invoice_IGMNO_Grid_Assgn] '2305891', '190', 0,-1    
ALTER PROCEDURE [dbo].[pr_Import_Invoice_IGMNO_Grid_Assgn]  /* CHANGE */    
  @PIGMNO varchar(25), @PLNO varchar(10), @PTRANMID INT,@PTRANBTYPE int = -1    
     
AS BEGIN    
    
    DECLARE @TableMaster TABLE    
    (     
   TRANREFID INT    
   ,TRANREFNAME VARCHAR(100)    
   ,BOENO VARCHAR(25)    
   ,BILLEMID INT    
   ,BILLEDID INT     
   ,GIDID INT    
   ,STMRID INT    
   ,STMRNAME VARCHAR(100)    
   ,IGMNO VARCHAR(25)    
   ,GPLNO VARCHAR(10)    
   ,CONTNRNO  VARCHAR(15)    
   ,CONTNRSDESC VARCHAR(15)    
   ,CONTNRSID INT    
   ,GIDATE SMALLDATETIME     
   ,STRGDATE SMALLDATETIME     
   ,GODATE SMALLDATETIME    
   ,GOTIME DATETIME    
   ,DODATE SMALLDATETIME    
   ,NOD NUMERIC(18,2)    
   ,WGHT  NUMERIC(18,4)    
   ,PRDTGID INT    
   ,TRANDID INT    
   ,TRANDOTYPE SMALLINT    
   ,TARIFFMID INT    
   ,DPAIDNO VARCHAR(50)    
   ,DPAIDAMT NUMERIC(18, 2)    
   ,GPEAMT NUMERIC(18, 2)    
   ,GPCSAMT NUMERIC(18, 2)    
   ,GPLBAMT NUMERIC(18, 2)    
   ,GPAAMT  NUMERIC(18, 2)    
   ,TRANDSAMT NUMERIC(18,2)    
   ,TRANDHAMT NUMERIC(18,2)    
   ,TRANDEAMT NUMERIC(18,2)    
   ,TRANDFAMT NUMERIC(18,2)    
   ,TRANDAAMT NUMERIC(18,2)    
   ,TRANDNAMT NUMERIC(18,2)    
   ,RCOL1  NUMERIC(18,2)    
   ,RCOL2  NUMERIC(18,2)    
   ,RCOL3  NUMERIC(18,2)    
   ,RCOL4  NUMERIC(18,2)    
   ,RCOL5  NUMERIC(18,2)    
   ,RCOL6  NUMERIC(18,2)    
   ,RCOL7  NUMERIC(18,2)    
   ,RAMT1  NUMERIC(18,2)    
   ,RAMT2  NUMERIC(18,2)    
   ,RAMT3  NUMERIC(18,2)    
   ,RAMT4  NUMERIC(18,2)    
   ,RAMT5  NUMERIC(18,2)    
   ,RAMT6  NUMERIC(18,2)    
   ,RAMT7  NUMERIC(18,2)    
   ,RCAMT1  NUMERIC(18,2)    
   ,RCAMT2  NUMERIC(18,2)    
   ,RCAMT3  NUMERIC(18,2)    
   ,RCAMT4  NUMERIC(18,2)    
   ,RCAMT5  NUMERIC(18,2)    
   ,RCAMT6  NUMERIC(18,2)    
   ,RCAMT7  NUMERIC(18,2)    
    ,GPETYPE smallint    
    ,GPCSTYPE smallint    
    ,GPLBTYPE smallint    
   ,GPSTYPE smallint    
   ,GPWTYPE smallint    
   ,GPSCNTYPE smallint    
    ,TRANDRATE  NUMERIC(18,2)    
    , STATETYPE smallint    
    , STRG_HSN_CODE VARCHAR(10)    
    , HANDL_HSN_CODE VARCHAR(10)    
    ,STRG_TAXABLE_AMT  NUMERIC(18,2)    
    ,HANDL_TAXABLE_AMT  NUMERIC(18,2)    
    ,STRG_CGST_EXPRN  NUMERIC(18,2)    
    ,STRG_SGST_EXPRN  NUMERIC(18,2)    
    ,STRG_IGST_EXPRN  NUMERIC(18,2)    
    ,STRG_CGST_AMT  NUMERIC(18,2)    
    ,STRG_SGST_AMT  NUMERIC(18,2)    
    ,STRG_IGST_AMT  NUMERIC(18,2)    
    ,HANDL_CGST_EXPRN  NUMERIC(18,2)    
    ,HANDL_SGST_EXPRN  NUMERIC(18,2)    
    ,HANDL_IGST_EXPRN  NUMERIC(18,2)    
    ,HANDL_CGST_AMT  NUMERIC(18,2)    
    ,HANDL_SGST_AMT  NUMERIC(18,2)    
    ,HANDL_IGST_AMT  NUMERIC(18,2)    
    ,TRANCGSTAMT  NUMERIC(18,2)    
    ,TRANSGSTAMT  NUMERIC(18,2)    
    ,TRANIGSTAMT  NUMERIC(18,2)    
    ,TRAND_COVID_DISC_AMT NUMERIC(18,2)    
    ,TRANBTYPE INT    
    ,TRANDADONAMT NUMERIC(18,2)    
 ,CUSTGID INT  
    )    
    
    
         
DECLARE @LIGMNO varchar(25), @LLNO varchar(10), @LTRANMID INT    
set @LIGMNO =@PIGMNO    
set @LLNO = @PLNO    
set @LTRANMID = @PTRANMID    
set nocount on    
    
--PENDING BOE CONTAINER NO    
--isnull(dbo.GATEOUTDETAIL.GODATE,@LEDATE)    
    
    
    
IF @LTRANMID  = 0      
BEGIN    
 INSERT INTO @TableMaster(TRANREFID,TRANREFNAME,BOENO,BILLEMID,BILLEDID,GIDID,STMRID,STMRNAME,IGMNO,GPLNO,CONTNRNO,CONTNRSDESC,CONTNRSID,GIDATE,    
 STRGDATE,GODATE,GOTIME,DODATE,NOD,WGHT,PRDTGID,TRANDID,TRANDOTYPE,TARIFFMID,DPAIDNO,DPAIDAMT,GPEAMT,GPCSAMT,GPLBAMT,GPAAMT,TRANDSAMT,TRANDHAMT,    
 TRANDEAMT,TRANDFAMT,TRANDAAMT,TRANDNAMT,RCOL1,RCOL2,RCOL3,RCOL4,RCOL5,RCOL6,RCOL7,RAMT1,RAMT2,RAMT3,RAMT4,RAMT5,RAMT6,RAMT7,RCAMT1,RCAMT2,    
 RCAMT3,RCAMT4,RCAMT5,RCAMT6,RCAMT7,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,TRANDRATE, STATETYPE, STRG_HSN_CODE, HANDL_HSN_CODE ,STRG_TAXABLE_AMT,    
 HANDL_TAXABLE_AMT,STRG_CGST_EXPRN,STRG_SGST_EXPRN,STRG_IGST_EXPRN,STRG_CGST_AMT,STRG_SGST_AMT,    
 STRG_IGST_AMT,HANDL_CGST_EXPRN,HANDL_SGST_EXPRN,HANDL_IGST_EXPRN,HANDL_CGST_AMT,HANDL_SGST_AMT,    
 HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT,TRANDADONAMT,CUSTGID)    
     
 SELECT DISTINCT     
        dbo.OPENSHEETMASTER.OSBILLREFID, dbo.OPENSHEETMASTER.OSBILLREFNAME, dbo.BILLENTRYMASTER.BILLEMDNO, dbo.BILLENTRYMASTER.BILLEMID,dbo.BILLENTRYDETAIL.BILLEDID,    
        dbo.BILLENTRYDETAIL.GIDID, dbo.GATEINDETAIL.STMRID,GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.CONTNRNO,     
        dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.CONTNRSID, dbo.GATEINDETAIL.GIDATE,     
        dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN.XGIDATE AS STRGDATE,     
        --dbo.GATEOUTDETAIL.GODATE,     
        CASE WHEN DATEPART(HOUR,GOTIME)<6 THEN DATEADD(D,-1,GODATE) ELSE GODATE END AS GODATE,    
        dbo.GATEOUTDETAIL.GOTIME,     
        dbo.OPENSHEETMASTER.DODATE, 0 AS NOD, dbo.GATEINDETAIL.GPWGHT, dbo.GATEINDETAIL.PRDTGID, 0 AS TRANDID, 0 AS TRANDOTYPE, 0 AS TARIFFMID,     
        dbo.BILLENTRYMASTER.DPAIDNO, dbo.BILLENTRYMASTER.DPAIDAMT, dbo.GATEINDETAIL.GPEAMT, dbo.GATEINDETAIL.GPCSAMT,dbo.GATEINDETAIL.GPLBAMT, dbo.GATEINDETAIL.GPAAMT,    
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,0, isnull(STATETYPE,0),    
        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,dbo.CATEGORYMASTER.CUSTGID    
 FROM  dbo.OPENSHEETMASTER (NOLOCK)   
 INNER JOIN dbo.BILLENTRYMASTER  (NOLOCK)   
 INNER JOIN dbo.BILLENTRYDETAIL  (NOLOCK) ON dbo.BILLENTRYMASTER.BILLEMID = dbo.BILLENTRYDETAIL.BILLEMID   
 INNER JOIN dbo.GATEINDETAIL  (NOLOCK) ON dbo.BILLENTRYDETAIL.GIDID = dbo.GATEINDETAIL.GIDID   
 INNER JOIN dbo.CONTAINERSIZEMASTER  (NOLOCK) ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID   
 INNER JOIN dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN  (NOLOCK) ON dbo.BILLENTRYMASTER.BILLEMID = dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN.BILLEMID   
 INNER JOIN dbo.OPENSHEETDETAIL  (NOLOCK) ON dbo.GATEINDETAIL.GIDID = dbo.OPENSHEETDETAIL.GIDID ON     
        dbo.OPENSHEETMASTER.OSMID = dbo.OPENSHEETDETAIL.OSMID   
 INNER JOIN dbo.GATEOUTDETAIL  (NOLOCK) ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID   
 LEFT OUTER JOIN dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01  (NOLOCK) ON     
        dbo.BILLENTRYDETAIL.BILLEDID = dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.BILLEDID   
 INNER JOIN dbo.CATEGORYMASTER  (NOLOCK) ON dbo.OPENSHEETMASTER.OSBILLREFID = dbo.CATEGORYMASTER.CATEID   
 LEFT OUTER JOIN dbo.CATEGORY_ADDRESS_DETAIL  (NOLOCK) ON dbo.OPENSHEETMASTER.OSBBCHACATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID    
 LEFT OUTER JOIN dbo.STATEMASTER  (NOLOCK) ON dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID   
 INNER JOIN AUTHORIZATIONSLIPDETAIL B (NOLOCK)  on dbo.GATEINDETAIL.GIDID =  b.GIDID inner JOIN AUTHORIZATIONSLIPMASTER C ON B.ASLMID = C.ASLMID and c.DISPSTATUS=0    
 WHERE (ISNULL(dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDID, 0) = 0) AND    
  (dbo.BILLENTRYMASTER.SDPTID = 1) AND     
  (dbo.GATEINDETAIL.IGMNO = @LIGMNO) AND (dbo.GATEINDETAIL.GPLNO = @LLNO)    
    
 -- SELECT * FROM @TableMaster    
    
 UPDATE @TableMaster    
 SET TRANBTYPE  = C.ASLMTYPE    
 FROM @TableMaster A JOIN AUTHORIZATIONSLIPDETAIL B  (NOLOCK)      
 JOIN AUTHORIZATIONSLIPMASTER C  (NOLOCK)  ON B.ASLMID = C.ASLMID    
 ON A.GIDID =  B.GIDID     
 WHERE C.SDPTID = 1    
 AND C.DISPSTATUS = 0    
    
     
 UPDATE @TableMaster    
 SET TRANDOTYPE=5    
 FROM @TableMaster A JOIN AUTHORIZATIONSLIPDETAIL B (NOLOCK)     
 JOIN AUTHORIZATIONSLIPMASTER C (NOLOCK)  ON B.ASLMID = C.ASLMID    
 ON A.GIDID =  B.GIDID     
 WHERE C.SDPTID = 1    
 and  C.ASLMTYPE = 1    
 AND C.DISPSTATUS = 0    
    
 UPDATE @TableMaster    
 SET TRANDOTYPE= case when ASLDTYPE = 0 and ASLLTYPE = 0 then 5     
      when ASLDTYPE = 1 and ASLLTYPE = 1 then 6 else ASLOTYPE+1 end    
 FROM @TableMaster A JOIN AUTHORIZATIONSLIPDETAIL B (NOLOCK)  JOIN     
 AUTHORIZATIONSLIPMASTER C  (NOLOCK) ON B.ASLMID = C.ASLMID    
 ON A.GIDID =  B.GIDID     
 WHERE C.SDPTID = 1    
 and  C.ASLMTYPE = 2    
 AND C.DISPSTATUS = 0    
    
     
END    
ELSE    
                          
--ACTUAL STUFF INVOICE DETAIL    
    
 INSERT INTO @TableMaster(TRANREFID,TRANREFNAME,BOENO,BILLEMID,BILLEDID,GIDID,STMRID,STMRNAME,IGMNO,GPLNO,CONTNRNO,CONTNRSDESC,CONTNRSID,GIDATE,    
 STRGDATE,GODATE,GOTIME,DODATE,NOD,WGHT,PRDTGID,TRANDID,TRANDOTYPE,TARIFFMID,DPAIDNO,DPAIDAMT,GPEAMT,GPCSAMT,GPLBAMT,GPAAMT,TRANDSAMT,TRANDHAMT,    
 TRANDEAMT,TRANDFAMT,TRANDAAMT,TRANDNAMT,RCOL1,RCOL2,RCOL3,RCOL4,RCOL5,RCOL6,RCOL7,RAMT1,RAMT2,RAMT3,RAMT4,RAMT5,RAMT6,RAMT7,RCAMT1,RCAMT2,    
 RCAMT3,RCAMT4,RCAMT5,RCAMT6,RCAMT7,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,TRANDRATE, STATETYPE, STRG_HSN_CODE, HANDL_HSN_CODE ,STRG_TAXABLE_AMT,    
 HANDL_TAXABLE_AMT,STRG_CGST_EXPRN,STRG_SGST_EXPRN,STRG_IGST_EXPRN,STRG_CGST_AMT,STRG_SGST_AMT,    
 STRG_IGST_AMT,HANDL_CGST_EXPRN,HANDL_SGST_EXPRN,HANDL_IGST_EXPRN,HANDL_CGST_AMT,HANDL_SGST_AMT,    
 HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT,TRANBTYPE, TRANDADONAMT,CUSTGID)    
    
    
 SELECT     dbo.TRANSACTIONMASTER.TRANREFID, dbo.TRANSACTIONMASTER.TRANREFNAME, dbo.TRANSACTIONDETAIL.TRANDREFNO AS BOENO,     
        dbo.BILLENTRYMASTER.BILLEMID,dbo.TRANSACTIONDETAIL.BILLEDID, dbo.TRANSACTIONDETAIL.TRANDREFID AS GIDID, dbo.GATEINDETAIL.STMRID,GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.IGMNO,     
        dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.CONTNRSID,     
        dbo.TRANSACTIONDETAIL.TRANIDATE, dbo.TRANSACTIONDETAIL.TRANSDATE, dbo.TRANSACTIONDETAIL.TRANEDATE, dbo.GATEOUTDETAIL.GOTIME,     
        dbo.TRANSACTIONDETAIL.TRANVDATE, dbo.TRANSACTIONDETAIL.TRANDQTY, dbo.TRANSACTIONDETAIL.TRANDWGHT, dbo.GATEINDETAIL.PRDTGID,     
        dbo.TRANSACTIONDETAIL.TRANDID, dbo.TRANSACTIONDETAIL.TRANOTYPE, dbo.TRANSACTIONDETAIL.TARIFFMID, dbo.BILLENTRYMASTER.DPAIDNO,     
        dbo.BILLENTRYMASTER.DPAIDAMT, dbo.GATEINDETAIL.GPEAMT, dbo.GATEINDETAIL.GPCSAMT, dbo.GATEINDETAIL.GPLBAMT,dbo.GATEINDETAIL.GPAAMT, dbo.TRANSACTIONDETAIL.TRANDSAMT,     
        dbo.TRANSACTIONDETAIL.TRANDHAMT, dbo.TRANSACTIONDETAIL.TRANDEAMT, dbo.TRANSACTIONDETAIL.TRANDFAMT, dbo.TRANSACTIONDETAIL.TRANDAAMT,     
        dbo.TRANSACTIONDETAIL.TRANDNAMT, dbo.TRANSACTIONDETAIL.RCOL1, dbo.TRANSACTIONDETAIL.RCOL2, dbo.TRANSACTIONDETAIL.RCOL3,     
        dbo.TRANSACTIONDETAIL.RCOL4, dbo.TRANSACTIONDETAIL.RCOL5, dbo.TRANSACTIONDETAIL.RCOL6, dbo.TRANSACTIONDETAIL.RCOL7, dbo.TRANSACTIONDETAIL.RAMT1,     
        dbo.TRANSACTIONDETAIL.RAMT2, dbo.TRANSACTIONDETAIL.RAMT3, dbo.TRANSACTIONDETAIL.RAMT4, dbo.TRANSACTIONDETAIL.RAMT5,     
        dbo.TRANSACTIONDETAIL.RAMT6, dbo.TRANSACTIONDETAIL.RAMT7, dbo.TRANSACTIONDETAIL.RCAMT1, dbo.TRANSACTIONDETAIL.RCAMT2, dbo.TRANSACTIONDETAIL.RCAMT3,     
        dbo.TRANSACTIONDETAIL.RCAMT4, dbo.TRANSACTIONDETAIL.RCAMT5, dbo.TRANSACTIONDETAIL.RCAMT6, dbo.TRANSACTIONDETAIL.RCAMT7,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,    
        dbo.TRANSACTIONDETAIL.TRANDRATE,isnull(STATETYPE,0), STRG_HSNCODE, HANDL_HSNCODE, STRG_TAXABLE_AMT, HANDL_TAXABLE_AMT, STRG_CGST_EXPRN, STRG_SGST_EXPRN, STRG_IGST_EXPRN,     
                         STRG_CGST_AMT, STRG_SGST_AMT, STRG_IGST_AMT, HANDL_CGST_EXPRN, HANDL_SGST_EXPRN, HANDL_IGST_EXPRN, HANDL_CGST_AMT,     
                         HANDL_SGST_AMT, HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT,TRANBTYPE,TRANDADONAMT,dbo.TRANSACTIONMASTER.CUSTGID    
    
 FROM dbo.TRANSACTIONMASTER (NOLOCK)    
 INNER JOIN dbo.TRANSACTIONDETAIL  (NOLOCK) ON dbo.TRANSACTIONMASTER.TRANMID = dbo.TRANSACTIONDETAIL.TRANMID   
 INNER JOIN dbo.BILLENTRYDETAIL  (NOLOCK) ON dbo.TRANSACTIONDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID   
 INNER JOIN dbo.BILLENTRYMASTER  (NOLOCK) ON dbo.BILLENTRYDETAIL.BILLEMID = dbo.BILLENTRYMASTER.BILLEMID   
 INNER JOIN dbo.OPENSHEETDETAIL (NOLOCK)  ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.OPENSHEETDETAIL.BILLEDID   
 INNER JOIN dbo.OPENSHEETMASTER  (NOLOCK) ON dbo.OPENSHEETDETAIL.OSMID = dbo.OPENSHEETMASTER.OSMID   
 INNER JOIN dbo.GATEINDETAIL  (NOLOCK) ON dbo.BILLENTRYDETAIL.GIDID = dbo.GATEINDETAIL.GIDID   
 INNER JOIN dbo.CONTAINERSIZEMASTER  (NOLOCK) ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID   
 LEFT OUTER JOIN dbo.GATEOUTDETAIL  (NOLOCK) ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID  
 INNER JOIN dbo.CATEGORYMASTER  (NOLOCK) ON dbo.OPENSHEETMASTER.OSBILLREFID = dbo.CATEGORYMASTER.CATEID    
 INNER JOIN dbo.CATEGORY_ADDRESS_DETAIL (NOLOCK)  ON dbo.OPENSHEETMASTER.OSBBCHACATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID   
 INNER JOIN dbo.STATEMASTER  (NOLOCK) ON dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID    
    
 WHERE     (dbo.TRANSACTIONMASTER.TRANMID = @LTRANMID)    
    
    
    
    
SELECT *    
 --TRANREFID,TRANREFNAME,BOENO,BILLEMID,BILLEDID,GIDID,STMRID,STMRNAME,IGMNO,GPLNO,CONTNRNO,CONTNRSDESC,CONTNRSID,GIDATE,    
 --STRGDATE,GODATE,GOTIME,DODATE,NOD,WGHT,PRDTGID,TRANDID,TRANDOTYPE,TARIFFMID,DPAIDNO,DPAIDAMT,GPEAMT,GPCSAMT,GPLBAMT,GPAAMT,TRANDSAMT,TRANDHAMT,    
 --TRANDEAMT,TRANDFAMT,TRANDAAMT,TRANDNAMT,RCOL1,RCOL2,RCOL3,RCOL4,RCOL5,RCOL6,RCOL7,RAMT1,RAMT2,RAMT3,RAMT4,RAMT5,RAMT6,RAMT7,RCAMT1,RCAMT2,    
 --RCAMT3,RCAMT4,RCAMT5,RCAMT6,RCAMT7,GPETYPE,GPCSTYPE,GPLBTYPE,GPSTYPE,GPWTYPE,GPSCNTYPE,TRANDRATE, STATETYPE, STRG_HSN_CODE, HANDL_HSN_CODE ,STRG_TAXABLE_AMT,    
 --HANDL_TAXABLE_AMT,STRG_CGST_EXPRN,STRG_SGST_EXPRN,STRG_IGST_EXPRN,STRG_CGST_AMT,STRG_SGST_AMT,    
 --STRG_IGST_AMT,HANDL_CGST_EXPRN,HANDL_SGST_EXPRN,HANDL_IGST_EXPRN,HANDL_CGST_AMT,HANDL_SGST_AMT,    
 --HANDL_IGST_AMT,TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,TRAND_COVID_DISC_AMT    
    
FROM @TableMaster WHERE ( TRANBTYPE = @PTRANBTYPE  OR @PTRANBTYPE=-1)    
order by BILLEDID    
    
    
    
--return     
           
END 