CREATE PROCEDURE [dbo].[pr_Invoice_Print_Customer_Detail_Assgn] @PTranMID int
AS
BEGIN

	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT  DISTINCT   dbo.TRANSACTIONMASTER.TRANMID,ISNULL(dbo.CATEGORYMASTER.CATENAME,'') AS OSBILLREFNAME, 
	       ISNULL(dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR1,'') AS CATEADDR1,ISNULL(dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR2,'') AS CATEADDR2, 
		   ISNULL(dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR3,'') AS CATEADDR3, ISNULL(dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR4,'') AS CATEADDR4,
		   ISNULL(dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO,'') AS CATEGSTNO, ISNULL(dbo.CATEGORYMASTER.CATEMAIL,'') AS CATEMAIL, 
		   ISNULL(dbo.CATEGORYMASTER.CATEPHN1,'') AS CATEPHN1, dbo.TRANSACTIONMASTER.TRANREFID 

	FROM            dbo.TRANSACTIONMASTER INNER JOIN
                         dbo.TRANSACTIONDETAIL ON dbo.TRANSACTIONMASTER.TRANMID = dbo.TRANSACTIONDETAIL.TRANMID LEFT JOIN
                         dbo.CATEGORYMASTER ON dbo.TRANSACTIONMASTER.TRANREFID = dbo.CATEGORYMASTER.CATEID   LEFT JOIN 
						 dbo.CATEGORY_ADDRESS_DETAIL ON dbo.CATEGORYMASTER.CATEID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID 


	Where TRANSACTIONMASTER.tranmid = @PTranMID
END

