-- EXEC [pr_NonPnr_Invoice_IGMNO_BillType_Load]  '999', '999', 0
-- EXEC [pr_NonPnr_Invoice_IGMNO_BillType_Load]  'IGMNO800', 'LINO0800', 0
/*

	
 SELECT * FROM GATEINDETAIL WHERE IGMNO = 'tIGM0001' AND GPLNO = 'tIGLN000001'

 SELECT DISTINCT VEHICLETICKETDETAIL.VTTYPE, IGMNO, GPLNO
	FROM dbo.GATEINDETAIL 
		INNER JOIN	dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID 
		INNER JOIN	dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID 
		LEFT JOIN	dbo.VW_NONPNR_NOT_BILL_MAX_GIDATE_ASSGN ON dbo.GATEINDETAIL.GIDID = dbo.VW_NONPNR_NOT_BILL_MAX_GIDATE_ASSGN.GIDID 
		INNER JOIN	dbo.CATEGORYMASTER ON dbo.GATEINDETAIL.CHAID = CATEGORYMASTER.CATEID 
		INNER Join	dbo.TARIFFMASTER ON TARIFFMASTER.TARIFFMID = CATEGORYMASTER.TARIFFMID 
		INNER Join  dbo.SLABMASTER ON TARIFFMASTER.TARIFFMID = SLABMASTER.TARIFFMID 
		INNER JOIN	dbo.CATEGORYMASTER STMR ON dbo.GATEINDETAIL.STMRID = STMR.CATEID 
		Left Join	dbo.CATEGORY_ADDRESS_DETAIL ON STMR.CATEID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID 
		Left Join	dbo.STATEMASTER ON dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID 
		Left Join	dbo.VEHICLETICKETDETAIL ON dbo.GATEINDETAIL.GIDID = VEHICLETICKETDETAIL.GIDID 
		Left Join	dbo.VW_NONPNR_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01 ON GATEINDETAIL.GIDID = dbo.VW_NONPNR_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDREFID  

	WHERE        (ISNULL(dbo.VW_NONPNR_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDID, 0) = 0)
 */
alter PROCEDURE [dbo].[pr_NonPnr_Invoice_IGMNO_BillType_Load]  /* CHANGE */
		@PIGMNO varchar(25), @PLNO varchar(25), @PTRANMID INT
 
AS BEGIN

    DECLARE @TableMaster TABLE
    ( 
	  TRANBTYPE INT
	  ,TRANBTYPEDESC VARCHAR(100)
    )


		   
DECLARE @LIGMNO varchar(25), @LLNO varchar(25), @LTRANMID INT
set @LIGMNO =@PIGMNO
set @LLNO = @PLNO
set @LTRANMID = @PTRANMID
set nocount on

	if isnull(@PTRANMID,0) = 0
	INSERT INTO @TableMaster
	select 0, 'Please select Bill Type'

	IF @LTRANMID  = 0  

		INSERT INTO @TableMaster(TRANBTYPE)	
		SELECT DISTINCT VEHICLETICKETDETAIL.VTTYPE
		FROM dbo.GATEINDETAIL 
			INNER JOIN	dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID 
			INNER JOIN	dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID 
			LEFT JOIN	dbo.VW_NONPNR_NOT_BILL_MAX_GIDATE_ASSGN ON dbo.GATEINDETAIL.GIDID = dbo.VW_NONPNR_NOT_BILL_MAX_GIDATE_ASSGN.GIDID 
			----INNER JOIN	dbo.CATEGORYMASTER ON dbo.GATEINDETAIL.CHAID = CATEGORYMASTER.CATEID 
			----INNER Join	dbo.TARIFFMASTER ON TARIFFMASTER.TARIFFMID = CATEGORYMASTER.TARIFFMID 
			--INNER Join  dbo.SLABMASTER ON TARIFFMASTER.TARIFFMID = SLABMASTER.TARIFFMID 
			--INNER JOIN	dbo.CATEGORYMASTER STMR ON dbo.GATEINDETAIL.STMRID = STMR.CATEID 
			--Left Join	dbo.CATEGORY_ADDRESS_DETAIL ON STMR.CATEID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID 
			--Left Join	dbo.STATEMASTER ON dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID 
			Left Join	dbo.VEHICLETICKETDETAIL ON dbo.GATEINDETAIL.GIDID = VEHICLETICKETDETAIL.GIDID 
			Left Join	dbo.VW_NONPNR_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01 ON GATEINDETAIL.GIDID = dbo.VW_NONPNR_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDREFID  

		WHERE        (ISNULL(dbo.VW_NONPNR_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDID, 0) = 0) AND 
			(dbo.GATEINDETAIL.IGMNO = @LIGMNO) AND (dbo.GATEINDETAIL.GPLNO = @LLNO) AND
			(dbo.GATEINDETAIL.SDPTID = 9)

	ELSE
		INSERT INTO @TableMaster(TRANBTYPE)
		SELECT DISTINCT VEHICLETICKETDETAIL.VTTYPE
		FROM dbo.GATEINDETAIL 
			Inner Join dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = GATEOUTDETAIL.GIDID 
			Left Join dbo.CATEGORYMASTER STMR ON dbo.GATEINDETAIL.STMRID = STMR.CATEID 
			Left Join dbo.CATEGORY_ADDRESS_DETAIL ON STMR.CATEID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID 
			Left Join dbo.STATEMASTER ON dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID 
			Left Join dbo.CONTAINERSIZEMASTER ON dbo.CONTAINERSIZEMASTER.CONTNRSID = dbo.GATEINDETAIL.CONTNRSID  
			Left Join dbo.VEHICLETICKETDETAIL ON dbo.GATEINDETAIL.GIDID = VEHICLETICKETDETAIL.GIDID 
			Left Join dbo.TRANSACTIONDETAIL ON dbo.GATEINDETAIL.GIDID = TRANSACTIONDETAIL.TRANDREFID 
			Left Join dbo.TRANSACTIONMASTER ON dbo.TRANSACTIONDETAIL.TRANMID = TRANSACTIONMASTER.TRANMID  
		WHERE        (dbo.TRANSACTIONMASTER.TRANMID = @LTRANMID)  

	UPDATE @TableMaster
	SET TRANBTYPEDESC = CASE	WHEN TRANBTYPE = 1 THEN 'LOAD' 
								WHEN TRANBTYPE = 2 THEN 'DESTUFF' ELSE 'OTH' + CAST(TRANBTYPE AS VARCHAR(10)) END
	where TRANBTYPE <> 0 

	SELECT *  FROM @TableMaster order by TRANBTYPE DESC

	return 
       
END

