alter PROCEDURE [dbo].[PR_NEW_NONPNR_RATECARDMASTER_FLX_ASSGN] @PTARIFFMID INT, @PSLABTID INT,
@PHTYPE SMALLINT, @PCHRGETYPE SMALLINT, @PCONTNRSID INT, @PSLABMIN NUMERIC(18,2)
AS
BEGIN

    DECLARE @TableMaster TABLE
    ( 
	   SLABTID  INT,
	   SLABAMT NUMERIC(18,2)
    )


	SET NOCOUNT ON;

INSERT INTO @TableMaster(SLABTID, SLABAMT)
SELECT TOP 1 SLABTID,SLABAMT FROM VW_NONPNR_RATECARDMASTER_FLX_ASSGN
WHERE TARIFFMID = @PTARIFFMID AND SLABTID = @PSLABTID AND HTYPE = @PHTYPE AND 
CHRGETYPE = @PCHRGETYPE AND CONTNRSID = @PCONTNRSID AND SLABMIN <= @PSLABMIN
and SDTYPE = 1
ORDER BY SLABMIN DESC


INSERT INTO @TableMaster(SLABTID, SLABAMT)
SELECT SLABTID,SLABAMT FROM VW_NONPNR_RATECARDMASTER_FLX_ASSGN
WHERE TARIFFMID = @PTARIFFMID AND SLABTID IN(14,15,16) AND HTYPE = @PHTYPE AND 
CHRGETYPE = @PCHRGETYPE AND CONTNRSID = @PCONTNRSID AND SDTYPE = 0 --AND SLABMIN <= @PSLABMIN
ORDER BY SLABMIN DESC


SELECT * FROM @TableMaster
RETURN

END

