-- EXEC pr_NonPnr_Invoice_IGMNO_Grid_Assgn @PIGMNO='999',@PLNO='999',@PTRANMID=0
alter PROCEDURE [dbo].[pr_NonPnr_Invoice_IGMNO_Grid_Assgn]  /* CHANGE */
		@PIGMNO varchar(25), @PLNO varchar(25), @PTRANMID INT
 
AS BEGIN

    DECLARE @TableMaster TABLE
    ( 
	  TRANREFID INT
	  ,TRANREFNAME VARCHAR(100)
	  ,BOENO VARCHAR(25)
	  --,BILLEMID INT
	  --,BILLEDID INT 
	  ,GIDID INT
	  ,STMRID INT
	  ,STMRNAME VARCHAR(100)
	  ,IGMNO VARCHAR(25)
	  ,GPLNO VARCHAR(25)
	  ,CONTNRNO  VARCHAR(25)
	  ,CONTNRSDESC VARCHAR(50)
	  ,CONTNRSID INT
	  ,GIDATE SMALLDATETIME 
	  ,STRGDATE SMALLDATETIME 
	  ,GODATE DATETIME
	  ,GOTIME SMALLDATETIME
	  --,DODATE SMALLDATETIME
	  ,NOD	NUMERIC(18,2)
	  ,WGHT 	NUMERIC(18,4)
	  ,PRDTGID INT
	  ,TRANDID INT
	  ,TRANDOTYPE SMALLINT
	  ,TARIFFMID INT
	  ,DPAIDNO VARCHAR(50)
	  ,DPAIDAMT NUMERIC(18, 2)
	  ,GPEAMT NUMERIC(18, 2)
	  ,GPCSAMT NUMERIC(18, 2)
	  ,GPLBAMT NUMERIC(18, 2)
	  ,GPAAMT  NUMERIC(18, 2)
	  ,TRANDSAMT NUMERIC(18,2)
	  ,TRANDHAMT NUMERIC(18,2)
	  ,TRANDEAMT NUMERIC(18,2)
	  ,TRANDFAMT NUMERIC(18,2)
	  ,TRANDAAMT NUMERIC(18,2)
	  ,TRANDNAMT NUMERIC(18,2)
	  ,RCOL1  NUMERIC(18,2)
	  ,RCOL2  NUMERIC(18,2)
	  ,RCOL3  NUMERIC(18,2)
	  ,RCOL4  NUMERIC(18,2)
	  ,RCOL5  NUMERIC(18,2)
	  ,RCOL6  NUMERIC(18,2)
	  ,RCOL7  NUMERIC(18,2)
	  ,RAMT1  NUMERIC(18,2)
	  ,RAMT2  NUMERIC(18,2)
	  ,RAMT3  NUMERIC(18,2)
	  ,RAMT4  NUMERIC(18,2)
	  ,RAMT5  NUMERIC(18,2)
	  ,RAMT6  NUMERIC(18,2)
	  ,RAMT7  NUMERIC(18,2)
	  ,RCAMT1  NUMERIC(18,2)
	  ,RCAMT2  NUMERIC(18,2)
	  ,RCAMT3  NUMERIC(18,2)
	  ,RCAMT4  NUMERIC(18,2)
	  ,RCAMT5  NUMERIC(18,2)
	  ,RCAMT6  NUMERIC(18,2)
	  ,RCAMT7  NUMERIC(18,2)
	   ,GPETYPE smallint
	   ,GPCSTYPE smallint
	   ,GPLBTYPE smallint
	  ,GPSTYPE smallint
	  ,GPWTYPE smallint
	  ,GPSCNTYPE smallint
	   ,TRANDRATE  NUMERIC(18,2)
	   , STATETYPE smallint
	   , STRG_HSN_CODE VARCHAR(50)
	   , HANDL_HSN_CODE VARCHAR(50)
	   ,STRG_TAXABLE_AMT  NUMERIC(18,2)
	   ,HANDL_TAXABLE_AMT  NUMERIC(18,2)
	   ,STRG_CGST_EXPRN  NUMERIC(18,2)
	   ,STRG_SGST_EXPRN  NUMERIC(18,2)
	   ,STRG_IGST_EXPRN  NUMERIC(18,2)
	   ,STRG_CGST_AMT  NUMERIC(18,2)
	   ,STRG_SGST_AMT  NUMERIC(18,2)
	   ,STRG_IGST_AMT  NUMERIC(18,2)
	   ,HANDL_CGST_EXPRN  NUMERIC(18,2)
	   ,HANDL_SGST_EXPRN  NUMERIC(18,2)
	   ,HANDL_IGST_EXPRN  NUMERIC(18,2)
	   ,HANDL_CGST_AMT  NUMERIC(18,2)
	   ,HANDL_SGST_AMT  NUMERIC(18,2)
	   ,HANDL_IGST_AMT  NUMERIC(18,2)
	   --,TRANCGSTAMT  NUMERIC(18,2)
	  -- ,TRANSGSTAMT  NUMERIC(18,2)
	  -- ,TRANIGSTAMT  NUMERIC(18,2)
	   ,TRAND_COVID_DISC_AMT NUMERIC(18,2)
    )


		   
DECLARE @LIGMNO varchar(25), @LLNO varchar(25), @LTRANMID INT
set @LIGMNO =@PIGMNO
set @LLNO = @PLNO
set @LTRANMID = @PTRANMID
set nocount on

--PENDING BOE CONTAINER NO
--isnull(dbo.GATEOUTDETAIL.GODATE,@LEDATE)



IF @LTRANMID  = 0  
 


	INSERT INTO @TableMaster(TRANREFID,TRANREFNAME,BOENO,GIDID,STMRID,STMRNAME,  IGMNO,GPLNO,CONTNRNO,CONTNRSDESC,CONTNRSID,GIDATE,
	--STRGDATE,
	GODATE,GOTIME,NOD,WGHT,PRDTGID,TRANDID,TRANDOTYPE,TARIFFMID,DPAIDNO,DPAIDAMT,GPEAMT,--GPCSAMT,GPLBAMT,
	GPAAMT,TRANDSAMT,TRANDHAMT,
	TRANDEAMT,TRANDFAMT,TRANDAAMT,TRANDNAMT,
	RCOL1,RCOL2,RCOL3,RCOL4,RCOL5,RCOL6,RCOL7,
	RAMT1,RAMT2,RAMT3,RAMT4,RAMT5,RAMT6,RAMT7,
	RCAMT1,RCAMT2,RCAMT3,RCAMT4,RCAMT5,RCAMT6,RCAMT7,
	GPETYPE,--GPCSTYPE,GPLBTYPE,
	GPSTYPE,GPWTYPE,GPSCNTYPE,TRANDRATE, STATETYPE, 
	STRG_HSN_CODE, HANDL_HSN_CODE ,
	STRG_TAXABLE_AMT,HANDL_TAXABLE_AMT,
	STRG_CGST_EXPRN,STRG_SGST_EXPRN,STRG_IGST_EXPRN,STRG_CGST_AMT,STRG_SGST_AMT,STRG_IGST_AMT,
	HANDL_CGST_EXPRN,HANDL_SGST_EXPRN,HANDL_IGST_EXPRN,HANDL_CGST_AMT,HANDL_SGST_AMT,
	HANDL_IGST_AMT,--TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,
	TRAND_COVID_DISC_AMT)
	
	SELECT DISTINCT 
                         ISNULL(dbo.GATEINDETAIL.BCHAID,0),ISNULL(dbo.GATEINDETAIL.BCHANAME ,''), ISNULL(dbo.GATEINDETAIL.BOENO,''),  
						 ISNULL(dbo.GATEINDETAIL.GIDID,0),ISNULL( dbo.GATEINDETAIL.STMRID,0),ISNULL(dbo.GATEINDETAIL.STMRNAME,''),
						 ISNUll(dbo.GATEINDETAIL.IGMNO,''),ISNULL(dbo.GATEINDETAIL.GPLNO,''),ISNULL(dbo.GATEINDETAIL.CONTNRNO, ''),
						 ISNULL(dbo.CONTAINERSIZEMASTER.CONTNRSDESC,''),ISNULL(dbo.GATEINDETAIL.CONTNRSID, 0),
						 ISNULL(dbo.GATEINDETAIL.GIDATE,''), ISNULL(dbo.GATEOUTDETAIL.GODATE,''),
                         dbo.GATEOUTDETAIL.GOTIME,ISNULL(DATEDIFF(DAY, dbo.GATEINDETAIL.GIDATE,dbo.GATEOUTDETAIL.GODATE),0) AS NOD,  ISNULL(dbo.GATEINDETAIL.GPWGHT,0),ISNULL(dbo.GATEINDETAIL.PRDTGID,0),
						  0 AS TRANDID, 0 AS TRANDOTYPE,ISNULL(TARIFFMASTER.TARIFFMID, 0 ) AS TARIFFMID,0,0, 
						ISNULL(dbo.GATEINDETAIL.GPEAMT,0),ISNULL(dbo.GATEINDETAIL.GPAAMT,0),
						0,
						0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, 						                         
						ISNULL(dbo.GATEINDETAIL.GPETYPE,0),ISNULL(dbo.GATEINDETAIL.GPSTYPE,0),ISNULL(dbo.GATEINDETAIL.GPWTYPE,0),
						 ISNULL(dbo.GATEINDETAIL.GPSCNTYPE,0),0, ISNULL(dbo.STATEMASTER.STATETYPE,0), 						
                         0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0	
						 			 
                         FROM dbo.GATEINDETAIL INNER JOIN  						  
                         dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                         dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID LEFT JOIN
                         dbo.VW_NONPNR_NOT_BILL_MAX_GIDATE_ASSGN ON dbo.GATEINDETAIL.GIDID = dbo.VW_NONPNR_NOT_BILL_MAX_GIDATE_ASSGN.GIDID INNER JOIN
                         dbo.CATEGORYMASTER ON dbo.GATEINDETAIL.CHAID = CATEGORYMASTER.CATEID left Join 
						 dbo.TARIFFMASTER ON TARIFFMASTER.TARIFFMID = CATEGORYMASTER.TARIFFMID left Join  
						 dbo.SLABMASTER ON TARIFFMASTER.TARIFFMID = SLABMASTER.TARIFFMID INNER JOIN 
						 dbo.CATEGORYMASTER STMR ON dbo.GATEINDETAIL.STMRID = STMR.CATEID Left Join 
						 dbo.CATEGORY_ADDRESS_DETAIL ON STMR.CATEID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID Left Join  						  
						 dbo.STATEMASTER ON dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID Left Join  
						 dbo.VEHICLETICKETDETAIL ON dbo.GATEINDETAIL.GIDID = VEHICLETICKETDETAIL.GIDID Left Join  
						 dbo.VW_NONPNR_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01 ON GATEINDETAIL.GIDID = dbo.VW_NONPNR_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDREFID  
						              
WHERE        (ISNULL(dbo.VW_NONPNR_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDID, 0) = 0) AND 
(dbo.GATEINDETAIL.IGMNO = @LIGMNO) AND (dbo.GATEINDETAIL.GPLNO = @LLNO) AND
 (dbo.GATEINDETAIL.SDPTID = 9)

ELSE
                      
--ACTUAL STUFF INVOICE DETAIL

	INSERT INTO @TableMaster(TRANREFID,TRANREFNAME,BOENO,GIDID,STMRID,STMRNAME,IGMNO,GPLNO,CONTNRNO,CONTNRSDESC,CONTNRSID,GIDATE,
	STRGDATE,GODATE,GOTIME,NOD,WGHT,PRDTGID,TRANDID,TRANDOTYPE,TARIFFMID,DPAIDNO,DPAIDAMT,GPEAMT,
	--GPCSAMT,GPLBAMT,
	GPAAMT,TRANDSAMT,TRANDHAMT,
	TRANDEAMT,TRANDFAMT,TRANDAAMT,TRANDNAMT,RCOL1,RCOL2,RCOL3,RCOL4,RCOL5,RCOL6,RCOL7,RAMT1,RAMT2,RAMT3,RAMT4,RAMT5,RAMT6,RAMT7,RCAMT1,RCAMT2,
	RCAMT3,RCAMT4,RCAMT5,RCAMT6,RCAMT7,GPETYPE,
	--GPCSTYPE,GPLBTYPE,
	GPSTYPE,GPWTYPE,GPSCNTYPE,TRANDRATE, STATETYPE, STRG_HSN_CODE, HANDL_HSN_CODE ,STRG_TAXABLE_AMT,
	HANDL_TAXABLE_AMT,STRG_CGST_EXPRN,STRG_SGST_EXPRN,STRG_IGST_EXPRN,STRG_CGST_AMT,STRG_SGST_AMT,
	STRG_IGST_AMT,HANDL_CGST_EXPRN,HANDL_SGST_EXPRN,HANDL_IGST_EXPRN,HANDL_CGST_AMT,HANDL_SGST_AMT,
	HANDL_IGST_AMT,--TRANCGSTAMT,TRANSGSTAMT,TRANIGSTAMT,
	TRAND_COVID_DISC_AMT)


	SELECT  DISTINCT     ISNULL(dbo.TRANSACTIONMASTER.TRANREFID,0) ,ISNULL(dbo.TRANSACTIONMASTER.TRANREFNAME,''), 
             ISNULL(dbo.GATEINDETAIL.BOENO,'') AS BOENO, ISNULL(dbo.GATEINDETAIL.GIDID,0) AS GIDID,ISNULL(dbo.GATEINDETAIL.STMRID,0),
			 ISNULL(dbo.GATEINDETAIL.STMRNAME,''),ISNULL(dbo.GATEINDETAIL.IGMNO,''),ISNULL(dbo.GATEINDETAIL.GPLNO,''),
			 ISNULL(dbo.GATEINDETAIL.CONTNRNO,''),ISNULL(dbo.CONTAINERSIZEMASTER.CONTNRSDESC,''),ISNULL(dbo.GATEINDETAIL.CONTNRSID,0),
			 ISNULL(dbo.TRANSACTIONDETAIL.TRANIDATE,''),ISNULL(dbo.TRANSACTIONDETAIL.TRANSDATE,''),
			 ISNULL(dbo.TRANSACTIONDETAIL.TRANEDATE,''),ISNULL(dbo.GATEOUTDETAIL.GOTIME, ''),
			 --dbo.TRANSACTIONDETAIL.TRANVDATE, 
			 ISNULL(dbo.TRANSACTIONDETAIL.TRANDQTY,0),ISNULL(dbo.TRANSACTIONDETAIL.TRANDWGHT,0),ISNULL(dbo.GATEINDETAIL.PRDTGID,0),
			 ISNULL(dbo.TRANSACTIONDETAIL.TRANDID,0),ISNULL(dbo.TRANSACTIONDETAIL.TRANOTYPE,0),ISNULL(dbo.TRANSACTIONDETAIL.TARIFFMID,0),0,0,
			 ISNULL(dbo.GATEINDETAIL.GPEAMT,0),ISNULL(dbo.GATEINDETAIL.GPAAMT,0),ISNULL(dbo.TRANSACTIONDETAIL.TRANDSAMT,0),
			 ISNULL(dbo.TRANSACTIONDETAIL.TRANDHAMT,0),ISNULL(dbo.TRANSACTIONDETAIL.TRANDEAMT,0),ISNULL(dbo.TRANSACTIONDETAIL.TRANDFAMT,0.00),
			 ISNULL(dbo.TRANSACTIONDETAIL.TRANDAAMT,0),ISNULL(dbo.TRANSACTIONDETAIL.TRANDNAMT,0.00),ISNULL(dbo.TRANSACTIONDETAIL.RCOL1,0), 
			 ISNULL(dbo.TRANSACTIONDETAIL.RCOL2,0), ISNULL(dbo.TRANSACTIONDETAIL.RCOL3,0),ISNULL(dbo.TRANSACTIONDETAIL.RCOL4,0),
			 ISNULL(dbo.TRANSACTIONDETAIL.RCOL5,0),ISNULL(dbo.TRANSACTIONDETAIL.RCOL6,0),ISNULL(dbo.TRANSACTIONDETAIL.RCOL7,0),
			 ISNULL(dbo.TRANSACTIONDETAIL.RAMT1,0),ISNULL(dbo.TRANSACTIONDETAIL.RAMT2, 0),ISNULL(dbo.TRANSACTIONDETAIL.RAMT3,0),
			 ISNULL(dbo.TRANSACTIONDETAIL.RAMT4,0),ISNULL(dbo.TRANSACTIONDETAIL.RAMT5,0),ISNULL(dbo.TRANSACTIONDETAIL.RAMT6,0),
			 ISNULL(dbo.TRANSACTIONDETAIL.RAMT7,0),ISNULL(dbo.TRANSACTIONDETAIL.RCAMT1,0),ISNULL(dbo.TRANSACTIONDETAIL.RCAMT2,0),
			 ISNULL(dbo.TRANSACTIONDETAIL.RCAMT3, 0),ISNULL(dbo.TRANSACTIONDETAIL.RCAMT4,0),ISNULL(dbo.TRANSACTIONDETAIL.RCAMT5,0),
			 ISNULL(dbo.TRANSACTIONDETAIL.RCAMT6,0),ISNULL(dbo.TRANSACTIONDETAIL.RCAMT7, 0),ISNULL(dbo.GATEINDETAIL.GPETYPE,0),
			 ISNULL(dbo.GATEINDETAIL.GPSTYPE,0),ISNULL(dbo.GATEINDETAIL.GPWTYPE,0),ISNULL(dbo.GATEINDETAIL.GPSCNTYPE,0),
			 ISNULL(dbo.TRANSACTIONDETAIL.TRANDRATE,0), ISNULL(dbo.STATEMASTER.STATETYPE, 0),ISNULL( dbo.TRANSACTIONMASTER.STRG_HSNCODE,''),
			 ISNULL(dbo.TRANSACTIONMASTER.HANDL_HSNCODE,''),ISNULL(dbo.TRANSACTIONMASTER.STRG_TAXABLE_AMT,0),ISNULL(dbo.TRANSACTIONMASTER.HANDL_TAXABLE_AMT, 0),
             ISNULL(dbo.TRANSACTIONMASTER.STRG_CGST_EXPRN,0),ISNULL(dbo.TRANSACTIONMASTER.STRG_SGST_EXPRN,0), ISNULL(dbo.TRANSACTIONMASTER.STRG_IGST_EXPRN, 0),
             ISNULL(dbo.TRANSACTIONMASTER.STRG_CGST_AMT,0),ISNULL(dbo.TRANSACTIONMASTER.STRG_SGST_AMT,0),ISNULL(dbo.TRANSACTIONMASTER.STRG_IGST_AMT, 0),
             ISNULL(dbo.TRANSACTIONMASTER.HANDL_CGST_EXPRN,0),ISNULL(dbo.TRANSACTIONMASTER.HANDL_SGST_EXPRN,0),ISNULL(dbo.TRANSACTIONMASTER.HANDL_IGST_EXPRN, 0),
             ISNULL(dbo.TRANSACTIONMASTER.HANDL_CGST_AMT,0),  ISNULL( dbo.TRANSACTIONMASTER.HANDL_SGST_AMT,0),  ISNULL(dbo.TRANSACTIONMASTER.HANDL_IGST_AMT, 0),
             ISNULL(dbo.TRANSACTIONDETAIL.TRAND_COVID_DISC_AMT,0)

FROM dbo.GATEINDETAIL Inner Join 
     dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = GATEOUTDETAIL.GIDID Left Join 
	 dbo.CATEGORYMASTER STMR ON dbo.GATEINDETAIL.STMRID = STMR.CATEID Left Join 
	 dbo.CATEGORY_ADDRESS_DETAIL ON STMR.CATEID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID Left Join  
	 dbo.STATEMASTER ON dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID Left Join 
     dbo.CONTAINERSIZEMASTER ON dbo.CONTAINERSIZEMASTER.CONTNRSID = dbo.GATEINDETAIL.CONTNRSID  Left Join  
	 dbo.VEHICLETICKETDETAIL ON dbo.GATEINDETAIL.GIDID = VEHICLETICKETDETAIL.GIDID Left Join 
	 dbo.TRANSACTIONDETAIL ON dbo.GATEINDETAIL.GIDID = TRANSACTIONDETAIL.TRANDREFID Left Join 
	 dbo.TRANSACTIONMASTER ON dbo.TRANSACTIONDETAIL.TRANMID = TRANSACTIONMASTER.TRANMID  
    WHERE        (dbo.TRANSACTIONMASTER.TRANMID = @LTRANMID)  


SELECT *  FROM @TableMaster order by TRANREFID



return 
       
END




-- EXEC pr_NonPnr_Invoice_IGMNO_Grid_Assgn @PIGMNO='tIGM0001',@PLNO='tIGLN000001',@PTRANMID=0
--SELECT ISNULL(DATEDIFF(DAY, dbo.GATEINDETAIL.GIDATE,dbo.GATEOUTDETAIL.GODATE),0) AS DateDiff FROM 
--dbo.GATEINDETAIL INNER JOIN 
--dbo.GATEOUTDETAIL ON GATEINDETAIL.GIDID = GATEOUTDETAIL.GIDID 




