-- =============================================
-- Author:		<Yamuna J>
-- Create date: <29/07/2021>
-- Description:	<Getting Category Address details>
-- =============================================
CREATE PROCEDURE [dbo].[pr_NonPnr_Invoice_CategoryAddresDetails]
(
--@SDPTID int null,
  @CATEID int null
)

AS
BEGIN
	
	SET NOCOUNT ON;

	Declare @DefTariffmid int , @defTgid int 
	

	SELECT @DefTariffmid = TARIFFMID  FROM CATEGORYMASTER where CATETID = 4 AND CATEID =  @CATEID   
	SELECT @defTgid = TGID  FROM TARIFFMASTER where TARIFFMID = @DefTariffmid ---And SDPTID=@SDPTID


	SELECT ISNULL(CATEAID,0) AS CATEAID, ISNULL(CATEGORY_ADDRESS_DETAIL.STATEID,0) AS STATEID ,
	ISNULL(CATEAGSTNO,'') AS CATEAGSTNO, ISNULL(CATEAADDR1,'') AS CATEAADDR1,
	ISNULL(CATEAADDR2,'') AS CATEAADDR2, ISNULL(CATEAADDR3,'') AS CATEAADDR3,
	ISNULL(CATEAADDR4,'') AS CATEAADDR4 ,ISNULL(@DefTariffmid,0) AS Tariffmid,
	ISNULL(@defTgid,0) AS TGID,

	--(ISNULL(CATEAGSTNO,'')+',' +
	--ISNULL(CATEAADDR1,'') + ','+ISNULL(CATEAADDR2,'') + ','+
	--ISNULL(CATEAADDR3,'') + ','+ISNULL(CATEAADDR4,'') + ISNULL(STATEDESC,'')
	--+','+CAST (ISNULL(CATEGORY_ADDRESS_DETAIL.STATEID,0) AS varchar(10) )
	--) Addressdetail,

	('GST:  '+ISNULL(CATEAGSTNO,'')+'   ,' +
	ISNULL(CATEAADDR1,'') + ','+ISNULL(CATEAADDR2,'') + ','+
	ISNULL(CATEAADDR3,'') + ',' + ISNULL(STATEDESC,'')) Addressdetail,

	(
	CAST (ISNULL(CATEAID,0) AS varchar(10) )+ '~'+
	CAST (ISNULL(CATEGORY_ADDRESS_DETAIL.STATEID,0) AS varchar(10) )+ '~'+
	ISNULL(CATEAGSTNO,'') + '~'+ISNULL(CATEAADDR1,'') + '~'+ISNULL(CATEAADDR2,'') + '~'+
	ISNULL(CATEAADDR3,'') + '~'+ISNULL(CATEAADDR4,'') + '~'+CAST(ISNULL(@DefTariffmid,0) AS varchar(10))
	+ '~'+CAST(ISNULL(@defTgid,0) AS varchar(10)))	AS AddressId
	FROM CATEGORY_ADDRESS_DETAIL Left JOIN STATEMASTER ON 
	CATEGORY_ADDRESS_DETAIL.STATEID = STATEMASTER.STATEID
	WHERE CATEID =  @CATEID  
	GROUP BY CATEAID,STATEMASTER.STATEDESC, CATEGORY_ADDRESS_DETAIL.STATEID,CATEAGSTNO,CATEAADDR1,CATEAADDR2,CATEAADDR3,CATEAADDR4 
END

--  EXEC pr_NonPnr_Invoice_CategoryAddresDetails @CATEID = 14894
-- select CATEID from CATEGORY_ADDRESS_DETAIL GROUP By CATEID  Having COUNT(CATEID) > 1

