alter PROCEDURE [dbo].[PR_SHUTOUT_CARGO_FLX_ASSGN] @PSTFMID INT as   
  
SELECT        TOP (100) PERCENT dbo.SHIPPINGBILLDETAIL.SBMID, dbo.SHIPPINGBILLDETAIL.SBDID, dbo.SHIPPINGBILLMASTER.CHAID, dbo.SHIPPINGBILLDETAIL.SBDNO, dbo.GATEINDETAIL.GIDID, dbo.SHIPPINGBILLDETAIL.SBDDNO, 
                         dbo.SHIPPINGBILLDETAIL.SBDDATE, dbo.SHIPPINGBILLDETAIL.PRDTDESC, dbo.SHIPPINGBILLDETAIL.SBDNOP, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE, 
                         dbo.SHIPPINGBILLDETAIL.SBDNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0) AS BNOP, dbo.STUFFINGDETAIL.STFMID, dbo.STUFFINGPRODUCTDETAIL.STFPID, 
                         dbo.STUFFINGDETAIL.STFDID, dbo.STUFFINGPRODUCTDETAIL.STFDNOP, dbo.STUFFINGPRODUCTDETAIL.STFDQTY, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                         dbo.STUFFINGDETAIL.STFTYPE, dbo.SHIPPINGBILLMASTER.SBMDATE, LTRIM(dbo.SHIPPINGBILLMASTER.SBMDNO) + '(' + dbo.VW_YEAR_DETAIL_CBX_ASSGN.YRDESC + ')' AS SBMDNO, 
                         dbo.SHIPPINGBILLMASTER.CHANAME, dbo.STUFFINGMASTER.STFMNO, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMDATE, dbo.STUFFINGMASTER.STFMTIME, dbo.STUFFINGMASTER.LCATEID, 
                         dbo.STUFFINGMASTER.LCATENAME, ISNULL(dbo.STUFFINGPRODUCTDETAIL.ESBDID, '') AS ESBDID, ISNULL(dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLNO, '') AS ESBD_SBILLNO, 
                         dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLDATE
FROM            dbo.CONTAINERSIZEMASTER RIGHT OUTER JOIN
                         dbo.GATEINDETAIL RIGHT OUTER JOIN
                         dbo.STUFFINGMASTER INNER JOIN
                         dbo.STUFFINGDETAIL ON dbo.STUFFINGMASTER.STFMID = dbo.STUFFINGDETAIL.STFMID INNER JOIN
                         dbo.STUFFINGPRODUCTDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID ON dbo.GATEINDETAIL.GIDID = dbo.STUFFINGDETAIL.GIDID ON 
                         dbo.CONTAINERSIZEMASTER.CONTNRSID = dbo.GATEINDETAIL.CONTNRSID RIGHT OUTER JOIN
                         dbo.VW_YEAR_DETAIL_CBX_ASSGN INNER JOIN
                         dbo.SHIPPINGBILLDETAIL INNER JOIN
                         dbo.SHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID ON dbo.VW_YEAR_DETAIL_CBX_ASSGN.COMPYID = dbo.SHIPPINGBILLMASTER.COMPYID ON 
                         dbo.STUFFINGPRODUCTDETAIL.SBDID = dbo.SHIPPINGBILLDETAIL.SBDID LEFT OUTER JOIN
                         dbo.EXPORTSHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.ESBMID = dbo.EXPORTSHIPPINGBILLMASTER.ESBMID LEFT OUTER JOIN
                         dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01 ON dbo.SHIPPINGBILLDETAIL.SBDID = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.SBDID LEFT OUTER JOIN
                         dbo.EXPORTSHIPPINGBILLDETAIL ON dbo.EXPORTSHIPPINGBILLMASTER.ESBMID = dbo.EXPORTSHIPPINGBILLDETAIL.ESBMID AND dbo.SHIPPINGBILLDETAIL.SBDID = dbo.EXPORTSHIPPINGBILLDETAIL.ESBDID
WHERE STFTID  = 2 and STFMDATE>='2023-01-01'
GROUP BY dbo.SHIPPINGBILLDETAIL.SBMID, dbo.SHIPPINGBILLDETAIL.SBDDNO, dbo.SHIPPINGBILLDETAIL.SBDNO, dbo.SHIPPINGBILLDETAIL.SBDID, dbo.SHIPPINGBILLDETAIL.SBDDATE, dbo.SHIPPINGBILLDETAIL.PRDTDESC, 
                         dbo.SHIPPINGBILLDETAIL.SBDNOP, dbo.SHIPPINGBILLDETAIL.SBDNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0), dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO, 
                         dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE, dbo.STUFFINGDETAIL.STFMID, dbo.STUFFINGPRODUCTDETAIL.STFPID, dbo.STUFFINGDETAIL.STFDID, dbo.SHIPPINGBILLMASTER.CHAID, 
                         dbo.STUFFINGPRODUCTDETAIL.STFDNOP, dbo.STUFFINGPRODUCTDETAIL.STFDQTY, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.STUFFINGDETAIL.STFTYPE, 
                         dbo.SHIPPINGBILLMASTER.SBMDATE, LTRIM(dbo.SHIPPINGBILLMASTER.SBMDNO) + '(' + dbo.VW_YEAR_DETAIL_CBX_ASSGN.YRDESC + ')', dbo.GATEINDETAIL.GIDID, dbo.SHIPPINGBILLMASTER.CHANAME, 
                         dbo.STUFFINGMASTER.STFMNO, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMDATE, dbo.STUFFINGMASTER.STFMTIME, dbo.STUFFINGMASTER.LCATEID, dbo.STUFFINGMASTER.LCATENAME, 
                         ISNULL(dbo.STUFFINGPRODUCTDETAIL.ESBDID, ''), ISNULL(dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLNO, ''), dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLDATE
HAVING        (dbo.STUFFINGDETAIL.STFMID = @PSTFMID)
ORDER BY dbo.SHIPPINGBILLDETAIL.SBDNO

