/*
select (REMOTEGATEINDETAIL.COMPYID ) , (REMOTEGATEINDETAIL.DISPSTATUS) , ISNULL(REMOTEGATEINDETAIL.AGIDID,0), 
ISNULL(GATEINDETAIL.RGIDID,0),
GATEINDETAIL.* from REMOTEGATEINDETAIL Left Join 
		   GATEINDETAIL (nolock) ON REMOTEGATEINDETAIL.GIDID = GATEINDETAIL.RGIDID 
		   where REMOTEGATEINDETAIL.CONTNRNO = 'HLBU1643304'
select * from GATEINDETAIL where CONTNRNO = 'HLBU1643304'
SELECT * FROM GATEINDETAIL WHERE GIDID = 58693


declare @TotalRowsCount int , @FilteredRowsCount int 
exec [pr_Search_Import_RemoteGateInTransfer] null, 1, 'desc', 1, 10, @TotalRowsCount =100, @FilteredRowsCount =100
*/

alter  PROCEDURE [dbo].[pr_Search_Import_RemoteGateInTransfer] ( 
          @FilterTerm nvarchar(250) = NULL --parameter to search all columns by
        , @SortIndex INT = 1 -- a one based index to indicate which column to order by
        , @SortDirection CHAR(4) = 'ASC' --the direction to sort in, either ASC or DESC
        , @StartRowNum INT = 1 --the first row to return
        , @EndRowNum INT = 10 --the last row to return
        , @TotalRowsCount INT OUTPUT
        , @FilteredRowsCount INT OUTPUT
        --, @PSDate Smalldatetime
        --, @PEDate Smalldatetime
 )
AS
BEGIN
	--Wrap filter term with % to search for values that contain @FilterTerm
    SET @FilterTerm = '%' + @FilterTerm + '%'
	SET NOCOUNT ON;

	Declare  @tblremotegatein Table 
	(
	   GIDATE smalldatetime
      , GINO INT
      , GIDNO VARCHAR(25)
      , CONTNRNO  VARCHAR(25)
      , CONTNRSID  int
	  ,IGMNO VARCHAR(25)
	  ,GPLNO VARCHAR(25)
      , STMRNAME VARCHAR(150)
	  , IMPRTNAME VARCHAR(150)
	  ,VSLNAME VARCHAR(100)
	  ,PRDTDESC VARCHAR(100)
	  ,DISPSTATUS SMALLINT
	  , GIDID int 
	  ,AGIDID INT
      , RowNum INT
	)

	Insert Into @tblremotegatein(GIDATE,GINO,GIDNO,CONTNRNO,CONTNRSID,IGMNO,GPLNO,STMRNAME,IMPRTNAME, VSLNAME,
	PRDTDESC,DISPSTATUS,GIDID,AGIDID,RowNum)
	SELECT --ISNULL(convert(varchar(10),REMOTEGATEINDETAIL.GIDATE,103),'') as GIDATE,
			REMOTEGATEINDETAIL.GIDATE,
			ISNULL(REMOTEGATEINDETAIL.GINO,0) as GINO, 
	       ISNULL(REMOTEGATEINDETAIL.GIDNO,'') as GIDNO , ISNULL(REMOTEGATEINDETAIL.CONTNRNO,'') as CONTNRNO ,
		   ISNULL(REMOTEGATEINDETAIL.CONTNRSID,0) as CONTNRSID ,ISNULL(REMOTEGATEINDETAIL.IGMNO,'') as IGMNO,
		   ISNULL(REMOTEGATEINDETAIL.GPLNO,'') as GPLNO,ISNULL(STMN.CATENAME,'') as STMRNAME,
		   --ISNULL(IMPN.CATENAME,'') as IMPRTNAME,ISNULL(VESSELMASTER.VSLDESC,'') as VSLNAME,
		    ISNULL(VESSELMASTER.VSLDESC,'') as IMPRTNAME,ISNULL(IMPN.CATENAME,'') as VSLNAME,

		   REMOTEGATEINDETAIL.PRDTDESC as PRDTGDESC,
		   --ISNULL(PRODUCTGROUPMASTER.PRDTGDESC,'') as PRDTGDESC,
		   ISNULL(REMOTEGATEINDETAIL.DISPSTATUS,0) as DISPSTATUS,
		   ISNULL(REMOTEGATEINDETAIL.GIDID,0) as GIDID, --0 as AGIDID,
		   ISNULL(REMOTEGATEINDETAIL.AGIDID,0) as AGIDID,
		   --ISNULL(GATEINDETAIL.RGIDID,0) as AGIDID,
		    Row_Number() OVER (
            ORDER BY
            
            /*VARCHAR, NVARCHAR, CHAR ORDER BY*/
            
            CASE @SortDirection
              WHEN 'ASC'  THEN
                CASE @SortIndex
				
           	      WHEN 2 then REMOTEGATEINDETAIL.GIDNO
			  	  WHEN 3 then REMOTEGATEINDETAIL.CONTNRNO
			  	 
				   WHEN 5 then REMOTEGATEINDETAIL.IGMNO
			  	  WHEN 6 then REMOTEGATEINDETAIL.GPLNO
				   WHEN 7 then STMN.CATENAME
				   WHEN 8 then VESSELMASTER.VSLDESC
			  	  WHEN 9 then PRODUCTGROUPMASTER.PRDTGDESC
                END             
            END ASC,
            CASE @SortDirection
              WHEN 'DESC' THEN 
                CASE @SortIndex

           	     WHEN 2 then REMOTEGATEINDETAIL.GIDNO
			  	  WHEN 3 then REMOTEGATEINDETAIL.CONTNRNO
			  	 
				   WHEN 5 then REMOTEGATEINDETAIL.IGMNO
			  	  WHEN 6 then REMOTEGATEINDETAIL.GPLNO
				   WHEN 7 then STMN.CATENAME
				   WHEN 8 then VESSELMASTER.VSLDESC
			  	  WHEN 9 then PRODUCTGROUPMASTER.PRDTGDESC
                END
            END DESC,
            
            
            CASE @SortDirection
              WHEN 'ASC'  THEN
                CASE @SortIndex
								  WHEN 1 then REMOTEGATEINDETAIL.GINO
                  WHEN 3 THEN REMOTEGATEINDETAIL.CONTNRSID
                END             
            END ASC,
            CASE @SortDirection
              WHEN 'DESC' THEN 
                CASE @SortIndex
				  WHEN 1 then REMOTEGATEINDETAIL.GINO
           WHEN 3 THEN REMOTEGATEINDETAIL.CONTNRSID
                END
            END DESC                            

            ) AS RowNum
		   

    FROM   REMOTEGATEINDETAIL (nolock) Left Join  
	       CONTAINERSIZEMASTER (nolock) ON REMOTEGATEINDETAIL.CONTNRSID = CONTAINERSIZEMASTER.CONTNRSID Left Join
		   CATEGORYMASTER STMN (nolock) ON REMOTEGATEINDETAIL.STMRID = STMN.CATEID Left Join 
		   CATEGORYMASTER IMPN (nolock) ON REMOTEGATEINDETAIL.IMPRTID = IMPN.CATEID Left Join 
		   VESSELMASTER (nolock) ON REMOTEGATEINDETAIL.VSLID = VESSELMASTER.VSLID Left Join 
		   PRODUCTGROUPMASTER (nolock) ON REMOTEGATEINDETAIL.PRDTGID = PRODUCTGROUPMASTER.PRDTGID Left Join 
		   GATEINDETAIL (nolock) ON REMOTEGATEINDETAIL.GIDID = GATEINDETAIL.RGIDID AND 
		   REMOTEGATEINDETAIL.CONTNRNO = GATEINDETAIL.CONTNRNO and REMOTEGATEINDETAIL.SDPTID = GATEINDETAIL.SDPTID
	WHERE  (REMOTEGATEINDETAIL.COMPYID > 0) AND  (REMOTEGATEINDETAIL.DISPSTATUS=0) and ISNULL(REMOTEGATEINDETAIL.AGIDID,0) = 0 and ISNULL(GATEINDETAIL.RGIDID,0)=0
	and  (@FilterTerm IS NULL 
              OR REMOTEGATEINDETAIL.GIDATE LIKE @FilterTerm
              OR REMOTEGATEINDETAIL.IGMNO LIKE @FilterTerm
			  OR REMOTEGATEINDETAIL.GPLNO LIKE @FilterTerm
              OR REMOTEGATEINDETAIL.GINO LIKE @FilterTerm
              OR  REMOTEGATEINDETAIL.CONTNRNO  LIKE @FilterTerm
			  OR  CONTAINERSIZEMASTER.CONTNRSDESC LIKE @FilterTerm
			    OR  STMN.CATENAME  LIKE @FilterTerm
				  OR   VESSELMASTER.VSLDESC LIKE @FilterTerm
			    OR  PRODUCTGROUPMASTER.PRDTGDESC  LIKE @FilterTerm
				OR REMOTEGATEINDETAIL.GIDNO LIKE @FilterTerm
           )
	GROUP BY REMOTEGATEINDETAIL.GIDATE,REMOTEGATEINDETAIL.GINO,REMOTEGATEINDETAIL.GIDNO,
	         REMOTEGATEINDETAIL.CONTNRNO,REMOTEGATEINDETAIL.CONTNRSID,REMOTEGATEINDETAIL.IGMNO,
			 REMOTEGATEINDETAIL.GPLNO,STMN.CATENAME,IMPN.CATENAME,REMOTEGATEINDETAIL.PRDTDESC,
	         VESSELMASTER.VSLDESC,PRODUCTGROUPMASTER.PRDTGDESC,REMOTEGATEINDETAIL.DISPSTATUS,
			 REMOTEGATEINDETAIL.GIDID,GATEINDETAIL.RGIDID,REMOTEGATEINDETAIL.AGIDID

	SELECT ISNULL(convert(varchar(10),GIDATE,103),'') as GIDATE
                        , GINO
                        , GIDNO
                         , CONTNRNO 
      ,CASE CONTNRSID  WHEN 2 THEN 'NR' WHEN 3 THEN '20' WHEN 4 THEN '40'  WHEN 5 THEN '45' END  AS CONTNRSID
	  ,IGMNO 
	  ,GPLNO 
      , STMRNAME 
	  ,IMPRTNAME
	  ,VSLNAME 
	  ,PRDTDESC
	  ,CASE DISPSTATUS WHEN 1 THEN 'C' WHEN 0 THEN 'In Books' END AS DISPSTATUS
	  , GIDID,AGIDID
    FROM    @tblremotegatein
    WHERE   RowNum BETWEEN @StartRowNum AND @EndRowNum and AGIDID=0
    
   -- ----SELECT @TotalRowsCount = COUNT(*)
   -- FROM         dbo.REMOTEGATEINDETAIL   /* CHANGE  TABLE NAME */
   -- WHERE   (GATEINDETAIL.RGIDID = 0) and (REMOTEGATEINDETAIL.DISPSTATUS = 0)
   --WHERE   (DISPSTATUS=0)
    
	select  @TotalRowsCount = COUNT(REMOTEGATEINDETAIL.GIDID)
    FROM         dbo.REMOTEGATEINDETAIL Left Join 
	GATEINDETAIL (nolock) ON dbo.REMOTEGATEINDETAIL.GIDID = GATEINDETAIL.RGIDID 
	AND  REMOTEGATEINDETAIL.CONTNRNO = GATEINDETAIL.CONTNRNO and REMOTEGATEINDETAIL.SDPTID = GATEINDETAIL.SDPTID
	WHERE (REMOTEGATEINDETAIL.COMPYID > 0) AND  (REMOTEGATEINDETAIL.DISPSTATUS=0) and
	 ISNULL(REMOTEGATEINDETAIL.AGIDID,0)= 0 and ISNULL(GATEINDETAIL.RGIDID,0)=0


    SELECT @FilteredRowsCount = COUNT(*)
    FROM   @tblremotegatein where AGIDID=0
         


    -- Insert statements for procedure here
	
END


