ALTER PROCEDURE [dbo].[PR_STUFFINGDETAIL_FLX_ASSGN] @PSTFMID INT as 


--, @PCHAID INT AS

/*
SELECT     TOP (100) PERCENT dbo.SHIPPINGBILLDETAIL.SBMID, dbo.SHIPPINGBILLDETAIL.SBDID, dbo.SHIPPINGBILLMASTER.CHAID, 
                      dbo.SHIPPINGBILLDETAIL.SBDNO, dbo.GATEINDETAIL.GIDID, dbo.SHIPPINGBILLDETAIL.SBDDNO, dbo.SHIPPINGBILLDETAIL.SBDDATE, 
                      dbo.SHIPPINGBILLDETAIL.PRDTDESC, dbo.SHIPPINGBILLDETAIL.SBDNOP, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO, 
                      dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE, 
                      dbo.SHIPPINGBILLDETAIL.SBDNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0) AS BNOP, 
                      ISNULL(dbo.STUFFINGDETAIL.STFMID, 0) AS STFMID, ISNULL(dbo.STUFFINGPRODUCTDETAIL.STFPID, 0) AS STFPID, 
                      ISNULL(dbo.STUFFINGDETAIL.STFDID, 0) AS STFDID, ISNULL(dbo.STUFFINGPRODUCTDETAIL.STFDNOP, 0) AS STFDNOP, 
                      ISNULL(dbo.STUFFINGPRODUCTDETAIL.STFDQTY, 0) AS STFDQTY, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                      ISNULL(dbo.STUFFINGDETAIL.STFTYPE, 0) AS STFTYPE, dbo.SHIPPINGBILLMASTER.SBMDATE, LTRIM(dbo.SHIPPINGBILLMASTER.SBMDNO) 
                      + '(' + dbo.VW_YEAR_DETAIL_CBX_ASSGN.YRDESC + ')' AS SBMDNO, dbo.SHIPPINGBILLMASTER.CHANAME, dbo.STUFFINGMASTER.STFMNO, 
                      dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMDATE, dbo.STUFFINGMASTER.STFMTIME, dbo.STUFFINGMASTER.LCATEID, 
                      dbo.STUFFINGMASTER.LCATENAME
FROM         dbo.STUFFINGPRODUCTDETAIL LEFT OUTER JOIN
                      dbo.STUFFINGMASTER INNER JOIN
                      dbo.STUFFINGDETAIL ON dbo.STUFFINGMASTER.STFMID = dbo.STUFFINGDETAIL.STFMID LEFT OUTER JOIN
                      dbo.CONTAINERSIZEMASTER RIGHT OUTER JOIN
                      dbo.GATEINDETAIL ON dbo.CONTAINERSIZEMASTER.CONTNRSID = dbo.GATEINDETAIL.CONTNRSID ON 
                      dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID ON 
                      dbo.STUFFINGPRODUCTDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID RIGHT OUTER JOIN
                      dbo.VW_YEAR_DETAIL_CBX_ASSGN INNER JOIN
                      dbo.SHIPPINGBILLDETAIL INNER JOIN
                      dbo.SHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID ON 
                      dbo.VW_YEAR_DETAIL_CBX_ASSGN.COMPYID = dbo.SHIPPINGBILLMASTER.COMPYID ON 
                      dbo.STUFFINGPRODUCTDETAIL.SBDID = dbo.SHIPPINGBILLDETAIL.SBDID LEFT OUTER JOIN
                      dbo.EXPORTSHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.ESBMID = dbo.EXPORTSHIPPINGBILLMASTER.ESBMID LEFT OUTER JOIN
                      dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01 ON 
                      dbo.SHIPPINGBILLDETAIL.SBDID = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.SBDID
GROUP BY dbo.SHIPPINGBILLDETAIL.SBMID, dbo.SHIPPINGBILLDETAIL.SBDDNO, dbo.SHIPPINGBILLDETAIL.SBDNO, dbo.SHIPPINGBILLDETAIL.SBDID, 
                      dbo.SHIPPINGBILLDETAIL.SBDDATE, dbo.SHIPPINGBILLDETAIL.PRDTDESC, dbo.SHIPPINGBILLDETAIL.SBDNOP, 
                      dbo.SHIPPINGBILLDETAIL.SBDNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0), 
                      dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE, ISNULL(dbo.STUFFINGDETAIL.STFMID, 0), 
                      ISNULL(dbo.STUFFINGPRODUCTDETAIL.STFPID, 0), ISNULL(dbo.STUFFINGDETAIL.STFDID, 0), dbo.SHIPPINGBILLMASTER.CHAID, 
                      ISNULL(dbo.STUFFINGPRODUCTDETAIL.STFDNOP, 0), ISNULL(dbo.STUFFINGPRODUCTDETAIL.STFDQTY, 0), dbo.GATEINDETAIL.CONTNRNO, 
                      dbo.CONTAINERSIZEMASTER.CONTNRSDESC, ISNULL(dbo.STUFFINGDETAIL.STFTYPE, 0), dbo.SHIPPINGBILLMASTER.SBMDATE, 
                      LTRIM(dbo.SHIPPINGBILLMASTER.SBMDNO) + '(' + dbo.VW_YEAR_DETAIL_CBX_ASSGN.YRDESC + ')', dbo.GATEINDETAIL.GIDID, 
                      dbo.SHIPPINGBILLMASTER.CHANAME, dbo.STUFFINGMASTER.STFMNO, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMDATE, 
                      dbo.STUFFINGMASTER.STFMTIME, dbo.STUFFINGMASTER.LCATEID, dbo.STUFFINGMASTER.LCATENAME
HAVING      (ISNULL(dbo.STUFFINGDETAIL.STFMID, 0) = @PSTFMID)
ORDER BY dbo.SHIPPINGBILLDETAIL.SBDNO
*/
SELECT        TOP (100) PERCENT dbo.SHIPPINGBILLDETAIL.SBMID, dbo.SHIPPINGBILLDETAIL.SBDID, dbo.SHIPPINGBILLMASTER.CHAID, dbo.SHIPPINGBILLDETAIL.SBDNO, 
                         dbo.GATEINDETAIL.GIDID, dbo.SHIPPINGBILLDETAIL.SBDDNO, dbo.SHIPPINGBILLDETAIL.SBDDATE, dbo.SHIPPINGBILLDETAIL.PRDTDESC, 
                         dbo.SHIPPINGBILLDETAIL.SBDNOP, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE, 
                         dbo.SHIPPINGBILLDETAIL.SBDNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0) AS BNOP, dbo.STUFFINGDETAIL.STFMID, 
                         dbo.STUFFINGPRODUCTDETAIL.STFPID, dbo.STUFFINGDETAIL.STFDID, dbo.STUFFINGPRODUCTDETAIL.STFDNOP, dbo.STUFFINGPRODUCTDETAIL.STFDQTY, 
                         dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.STUFFINGDETAIL.STFTYPE, dbo.SHIPPINGBILLMASTER.SBMDATE, 
                         LTRIM(dbo.SHIPPINGBILLMASTER.SBMDNO) + '(' + dbo.VW_YEAR_DETAIL_CBX_ASSGN.YRDESC + ')' AS SBMDNO, dbo.SHIPPINGBILLMASTER.CHANAME, 
                         dbo.STUFFINGMASTER.STFMNO, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMDATE, dbo.STUFFINGMASTER.STFMTIME, 
                         dbo.STUFFINGMASTER.LCATEID, dbo.STUFFINGMASTER.LCATENAME, ISNULL(STUFFINGPRODUCTDETAIL.ESBDID,'') AS ESBDID,
						 ISNULL(STUFFINGPRODUCTDETAIL.ESBD_SBILLNO,'') ESBD_SBILLNO, STUFFINGPRODUCTDETAIL.ESBD_SBILLDATE
FROM            dbo.CONTAINERSIZEMASTER RIGHT OUTER JOIN
                         dbo.STUFFINGPRODUCTDETAIL INNER JOIN
                         dbo.STUFFINGMASTER INNER JOIN
                         dbo.STUFFINGDETAIL ON dbo.STUFFINGMASTER.STFMID = dbo.STUFFINGDETAIL.STFMID INNER JOIN
                         dbo.GATEINDETAIL ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID ON dbo.STUFFINGPRODUCTDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID ON 
                         dbo.CONTAINERSIZEMASTER.CONTNRSID = dbo.GATEINDETAIL.CONTNRSID RIGHT OUTER JOIN
                         dbo.VW_YEAR_DETAIL_CBX_ASSGN INNER JOIN
                         dbo.SHIPPINGBILLDETAIL INNER JOIN
                         dbo.SHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID ON 
                         dbo.VW_YEAR_DETAIL_CBX_ASSGN.COMPYID = dbo.SHIPPINGBILLMASTER.COMPYID ON 
                         dbo.STUFFINGPRODUCTDETAIL.SBDID = dbo.SHIPPINGBILLDETAIL.SBDID LEFT OUTER JOIN
                         dbo.EXPORTSHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.ESBMID = dbo.EXPORTSHIPPINGBILLMASTER.ESBMID LEFT OUTER JOIN
                         dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01 ON 
                         dbo.SHIPPINGBILLDETAIL.SBDID = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.SBDID  LEFT JOIN
						 EXPORTSHIPPINGBILLDETAIL ON EXPORTSHIPPINGBILLMASTER.ESBMID = EXPORTSHIPPINGBILLDETAIL.ESBMID AND  
						 dbo.SHIPPINGBILLDETAIL.SBDID = EXPORTSHIPPINGBILLDETAIL.ESBDID
GROUP BY dbo.SHIPPINGBILLDETAIL.SBMID, dbo.SHIPPINGBILLDETAIL.SBDDNO, dbo.SHIPPINGBILLDETAIL.SBDNO, dbo.SHIPPINGBILLDETAIL.SBDID, 
                         dbo.SHIPPINGBILLDETAIL.SBDDATE, dbo.SHIPPINGBILLDETAIL.PRDTDESC, dbo.SHIPPINGBILLDETAIL.SBDNOP, 
                         dbo.SHIPPINGBILLDETAIL.SBDNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0), dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO, 
                         dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE, dbo.STUFFINGDETAIL.STFMID, dbo.STUFFINGPRODUCTDETAIL.STFPID, dbo.STUFFINGDETAIL.STFDID, 
                         dbo.SHIPPINGBILLMASTER.CHAID, dbo.STUFFINGPRODUCTDETAIL.STFDNOP, dbo.STUFFINGPRODUCTDETAIL.STFDQTY, dbo.GATEINDETAIL.CONTNRNO, 
                         dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.STUFFINGDETAIL.STFTYPE, dbo.SHIPPINGBILLMASTER.SBMDATE, 
                         LTRIM(dbo.SHIPPINGBILLMASTER.SBMDNO) + '(' + dbo.VW_YEAR_DETAIL_CBX_ASSGN.YRDESC + ')', dbo.GATEINDETAIL.GIDID, 
                         dbo.SHIPPINGBILLMASTER.CHANAME, dbo.STUFFINGMASTER.STFMNO, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMDATE, 
                         dbo.STUFFINGMASTER.STFMTIME, dbo.STUFFINGMASTER.LCATEID, dbo.STUFFINGMASTER.LCATENAME, ISNULL(STUFFINGPRODUCTDETAIL.ESBDID,'') ,
						 ISNULL(STUFFINGPRODUCTDETAIL.ESBD_SBILLNO,''), STUFFINGPRODUCTDETAIL.ESBD_SBILLDATE
HAVING        (dbo.STUFFINGDETAIL.STFMID = @PSTFMID)
ORDER BY dbo.SHIPPINGBILLDETAIL.SBDNO


