

ALTER PROCEDURE [dbo].[pr_UPDATAE_SSRCHARGES_CONTAINERNo]  
          @FilterTerm varchar(100) 
        
AS BEGIN


SET @FilterTerm = @FilterTerm + '%'    

    DECLARE @TableMaster Table 
	( 
	  CONTNRNO nvarchar(100) not null,
	  GIDID int,
	  CONTNRSID int 
	)

	
   Insert Into  @TableMaster(CONTNRNO ,GIDID,CONTNRSID )  
   Select GATEINDETAIL.CONTNRNO,max(GATEINDETAIL.GIDID) as GIDID,GATEINDETAIL.CONTNRSID 
   FROM GATEINDETAIL Left Join  
   TRANSACTIONDETAIL (nolock) on GATEINDETAIL.GIDID = TRANSACTIONDETAIL.TRANDREFID  Left Join  
   TRANSACTIONMASTER (nolock) on TRANSACTIONDETAIL.TRANMID = TRANSACTIONMASTER.TRANMID  
   WHERE (@FilterTerm IS NULL  OR GATEINDETAIL.CONTNRNO LIKE @FilterTerm   )  AND GATEINDETAIL.SDPTID= 1  AND GATEINDETAIL.CONTNRSID > 0 
   AND (Isnull(TRANSACTIONDETAIL.TRANDREFID,0)= 0)   
   
   GROUP BY  GATEINDETAIL.GIDID , GATEINDETAIL.CONTNRNO,GATEINDETAIL.CONTNRSID


   Select CONTNRNO ,GIDID 
	    FROM @TableMaster
        


 
        
END

-- exec [dbo].[pr_UPDATAE_SSRCHARGES_CONTAINERNo] @FilterTerm = '%mu%'