alter PROCEDURE PROC_EXPORT_INVOICE_SBILL_CONTAINER_NO_GRID_ASSGN @PCHAID INT
AS
SELECT     dbo.STUFFINGMASTER.CHAID, dbo.STUFFINGDETAIL.STFDID, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                      dbo.GATEINDETAIL.CONTNRTID, dbo.GATEINDETAIL.GIDATE, dbo.GATEOUTDETAIL.GODATE, dbo.GATEINDETAIL.CONTNRSID, dbo.GATEINDETAIL.GIDID, 
                      MIN(dbo.SHIPPINGBILLDETAIL.SBDDATE) AS SBDDATE, SUM(dbo.STUFFINGPRODUCTDETAIL.STFDNOP) AS STFDNOP, 
                      SUM(dbo.STUFFINGPRODUCTDETAIL.STFDQTY) AS STFDQTY, STUFFINGMASTER.EOPTID as EOPTID
FROM         dbo.STUFFINGPRODUCTDETAIL INNER JOIN
                      dbo.STUFFINGDETAIL ON dbo.STUFFINGPRODUCTDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID INNER JOIN
                      dbo.GATEINDETAIL ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                      dbo.SHIPPINGBILLDETAIL ON dbo.STUFFINGPRODUCTDETAIL.SBDID = dbo.SHIPPINGBILLDETAIL.SBDID INNER JOIN
                      dbo.STUFFINGMASTER ON dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID LEFT OUTER JOIN
                      dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID LEFT OUTER JOIN
                      dbo.VW_EXPORT_INVOICE_SBILL_NO_CBX_ASSGN_01 ON dbo.STUFFINGDETAIL.STFDID = dbo.VW_EXPORT_INVOICE_SBILL_NO_CBX_ASSGN_01.STFDID
WHERE     (ISNULL(dbo.VW_EXPORT_INVOICE_SBILL_NO_CBX_ASSGN_01.TRANDID, 0) = 0) AND STUFFINGMASTER.CHAID = @PCHAID
GROUP BY dbo.STUFFINGDETAIL.STFDID, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.CONTNRNO, dbo.GATEINDETAIL.CONTNRTID, 
         dbo.GATEINDETAIL.GIDATE, dbo.GATEOUTDETAIL.GODATE, dbo.GATEINDETAIL.CONTNRSID, dbo.GATEINDETAIL.GIDID, dbo.STUFFINGMASTER.CHAID,
		 STUFFINGMASTER.EOPTID 



