ALTER TABLE [dbo].[REMOTEGATEINDETAIL] DROP CONSTRAINT [DF_REMOTEGATEINDETAIL_LMUSRID]
GO

alter table REMOTEGATEINDETAIL 
alter column LMUSRID varchar(100)  null 

ALTER TABLE [dbo].[REMOTEGATEINDETAIL] ADD  CONSTRAINT [DF_REMOTEGATEINDETAIL_LMUSRID]  DEFAULT (('')) FOR [LMUSRID]
GO