select RGIDID, COMPYID, SDPTID, gateindetail.GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, 
		CONTNRID, CONTNRSID , CONTNRNO, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, IGMNO, GPLNO , gateindetail.CUSRID, gateindetail.LMUSRID, gateindetail.DISPSTATUS, 
		gateindetail.PRCSDATE, GIISOCODE, GPNWGHT,  GPGWGHT, GPCBM,  GPLENGTH, GPWIDTH, GPHEIGHT, GPBLNO, GPEAMT, GPAAMT, GPPTYPE, 0 wmdid, IGMDATE, BLNO, 
		GPMODEID, OLDGID, GATEINDETAIL.GIDID as gin_gid, OPENSHEETDETAIL.GIDID
--into #selectedrgid
from gateindetail left join OPENSHEETDETAIL on  GATEINDETAIL.GIDID = OPENSHEETDETAIL.GIDID
where RGIDID > 0 and SDPTID = 1
and rgidid not in (select gidid from REMOTEGATEINDETAIL)
and OLDGID = 0
and GATEINDETAIL.GIDID in (62171, 62422, 63836,63969, 66033, 66357)

order by GIDID 
-- drop table #duprecs
select RGIDID, gidate, count('*') 'cnt', max(gin_gid) 'recent_gidid'
into #duprecs
from #selectedrgid 
where GIDID is  null
group by RGIDID, gidate
having count('*') > 1
select * from #duprecs
set identity_insert REMOTEGATEINDETAIL on
insert into REMOTEGATEINDETAIL (GIDID, COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, 
		CONTNRID, CONTNRSID , CONTNRNO, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, IGMNO, GPLNO , CUSRID, LMUSRID, DISPSTATUS, 
		PRCSDATE, GIISOCODE, GPNWGHT,  GPGWGHT, GPCBM,  GPLENGTH, GPWIDTH, GPHEIGHT, GPBLNO, GPEAMT, GPAAMT, GPPTYPE, WMDID, IGMDATE, BLNO, 
		GPMODEID, OLDGID, AGIDID)
select a.RGIDID, COMPYID, SDPTID, a.GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, 
		CONTNRID, CONTNRSID , CONTNRNO, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, IGMNO, GPLNO , CUSRID, LMUSRID, DISPSTATUS, 
		PRCSDATE, GIISOCODE, GPNWGHT,  GPGWGHT, GPCBM,  GPLENGTH, GPWIDTH, GPHEIGHT, GPBLNO, GPEAMT, GPAAMT, GPPTYPE, WMDID, IGMDATE, BLNO, 
		GPMODEID, OLDGID, gin_gid
from #selectedrgid a left join #duprecs b on a.rgidid = b.rgidid
where gidid is not null

insert into REMOTEGATEINDETAIL (GIDID, COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, 
		CONTNRID, CONTNRSID , CONTNRNO, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, IGMNO, GPLNO , CUSRID, LMUSRID, DISPSTATUS, 
		PRCSDATE, GIISOCODE, GPNWGHT,  GPGWGHT, GPCBM,  GPLENGTH, GPWIDTH, GPHEIGHT, GPBLNO, GPEAMT, GPAAMT, GPPTYPE, WMDID, IGMDATE, BLNO, 
		GPMODEID, OLDGID, AGIDID)
select distinct a.RGIDID, COMPYID, SDPTID, a.GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, 
		CONTNRID, CONTNRSID , CONTNRNO, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, IGMNO, GPLNO , CUSRID, LMUSRID, DISPSTATUS, 
		PRCSDATE, GIISOCODE, GPNWGHT,  GPGWGHT, GPCBM,  GPLENGTH, GPWIDTH, GPHEIGHT, GPBLNO, GPEAMT, GPAAMT, GPPTYPE, WMDID, IGMDATE, BLNO, 
		GPMODEID, OLDGID, recent_gidid
from #selectedrgid a  join #duprecs b on a.rgidid = b.RGIDID
where gidid is null
and a.RGIDID not in (select gidid from REMOTEGATEINDETAIL)
and gplno <> '-'


insert into REMOTEGATEINDETAIL (GIDID, COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, 
		CONTNRID, CONTNRSID , CONTNRNO, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, IGMNO, GPLNO , CUSRID, LMUSRID, DISPSTATUS, 
		PRCSDATE, GIISOCODE, GPNWGHT,  GPGWGHT, GPCBM,  GPLENGTH, GPWIDTH, GPHEIGHT, GPBLNO, GPEAMT, GPAAMT, GPPTYPE, WMDID, IGMDATE, BLNO, 
		GPMODEID, OLDGID, AGIDID)
select distinct a.RGIDID, COMPYID, SDPTID, a.GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, 
		CONTNRID, CONTNRSID , CONTNRNO, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, IGMNO, GPLNO , CUSRID, LMUSRID, DISPSTATUS, 
		PRCSDATE, GIISOCODE, GPNWGHT,  GPGWGHT, GPCBM,  GPLENGTH, GPWIDTH, GPHEIGHT, GPBLNO, GPEAMT, GPAAMT, GPPTYPE, WMDID, IGMDATE, BLNO, 
		GPMODEID, OLDGID, gin_gid
from #selectedrgid a 
where a.gin_gid in (62171, 62422, 63836,63969, 66033, 66357)
set identity_insert REMOTEGATEINDETAIL off


select * from GATEINDETAIL where gidid = 100070
select * from REMOTEGATEINDETAIL  where OLDGID = 0
order by gidid desc









select * from REMOTEGATEINDETAIL where  WMDID > 0 and OLDGID= 0 

select * from WMENT.dbo.WEIGHMENTDETAIL where rGIDID 
in (select GIDID from REMOTEGATEINDETAIL where  WMDID = 0 and OLDGID= 0 )

update a 
set WMDID = b.WMDID
from REMOTEGATEINDETAIL a, WMENT.dbo.WEIGHMENTDETAIL b
where b.rGIDID  = a.GIDID
and a.WMDID = 0 and OLDGID= 0

in (select GIDID from REMOTEGATEINDETAIL where  WMDID = 0 and OLDGID= 0 )