INSERT INTO SCFS_ERP_DEVPT..AspNetRoles
SELECT * FROM SCFS_ERP..AspNetRoles 
WHERE NAME NOT IN (SELECT NAME FROM SCFS_ERP_DEVPT..AspNetRoles)

INSERT INTO SCFS_ERP..AspNetRoles
SELECT * FROM SCFS_ERP_DEVPT..AspNetRoles 
WHERE NAME NOT IN (SELECT NAME FROM SCFS_ERP..AspNetRoles)