select * from GATEINDETAIL where SDPTID not in(9,11)

select * from GATEINDETAIL where SDPTID in(1)

--delete from GATEINDETAIL where SDPTID not in(9,11) --AND ISNULL(OLDGID ,0) <> 0

--Gate In Details
Select * From [SCFS].dbo.GATEINDETAIL (NOLOCK) INNER JOIN
       [SCFS].dbo.z_din_18092021 (NOLOCK) ON [SCFS].dbo.GATEINDETAIL.GIDID = [SCFS].dbo.z_din_18092021.GIDID
select * from [SCFS].dbo.z_din_18092021

--Opensheet Details
Select * From [SCFS].dbo.GATEINDETAIL INNER JOIN
       [SCFS].dbo.z_din_18092021 ON [SCFS].dbo.GATEINDETAIL.GIDID = [SCFS].dbo.z_din_18092021.GIDID
select * from [SCFS].dbo.z_din_18092021

-- OLD REF ID
USE SCFS_ERP
GO

alter table GATEINDETAIL
add OLDGID INT NULL DEFAULT 0


-- OLD REF ID
USE SCFS_ERP
GO

alter table OPENSHEETDETAIL
add OLDOSMDID INT NULL DEFAULT 0

alter table BILLENTRYDETAIL
add OLDBILLEDID INT NULL DEFAULT 0


alter VIEW [dbo].[z_din_18092021]
AS
SELECT        dbo.GATEINDETAIL.GIDID, dbo.OPENSHEETDETAIL.OSDID, dbo.OPENSHEETDETAIL.OSMID, dbo.BILLENTRYDETAIL.BILLEDID, dbo.BILLENTRYMASTER.BILLEMID, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, 
                         dbo.GATEINDETAIL.CONTNRNO, ISNULL(AUTHORIZATIONSLIPDETAIL.ASLDID,0) AS ASDID, 
						 ISNULL(AUTHORIZATIONSLIPDETAIL.ASLMID,0) AS ASLMID
FROM            dbo.BILLENTRYMASTER (nolock) INNER JOIN
                         dbo.BILLENTRYDETAIL  (nolock) ON dbo.BILLENTRYMASTER.BILLEMID = dbo.BILLENTRYDETAIL.BILLEMID INNER JOIN
                         dbo.OPENSHEETDETAIL  (nolock) ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.OPENSHEETDETAIL.BILLEDID INNER JOIN
                         dbo.GATEINDETAIL (nolock)  ON dbo.BILLENTRYDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                         dbo.CATEGORYMASTER  (nolock) ON dbo.BILLENTRYMASTER.CHAID = dbo.CATEGORYMASTER.CATEID LEFT OUTER JOIN
						 DBO.AUTHORIZATIONSLIPDETAIL (NOLOCK) ON OPENSHEETDETAIL.OSDID = AUTHORIZATIONSLIPDETAIL. OSDID LEFT OUTER JOIN
                         dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01  (nolock) ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.BILLEDID INNER JOIN
                         dbo.OPENSHEETMASTER  (nolock) ON dbo.OPENSHEETDETAIL.OSMID = dbo.OPENSHEETMASTER.OSMID
WHERE        (ISNULL(dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDID, 0) = 0)
GROUP BY dbo.BILLENTRYMASTER.BILLEMID, dbo.GATEINDETAIL.GIDID, dbo.OPENSHEETDETAIL.OSDID, dbo.OPENSHEETDETAIL.OSMID, dbo.BILLENTRYDETAIL.BILLEDID, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, 
                         dbo.GATEINDETAIL.CONTNRNO,  ISNULL(AUTHORIZATIONSLIPDETAIL.ASLDID,0) ,	 ISNULL(AUTHORIZATIONSLIPDETAIL.ASLMID,0)

GO
--GateInDetail Insert Assgn
INSERT INTO [SCFS_ERP].dbo.GATEINDETAIL
(COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GIVHLTYPE, TRNSPRTID, TRNSPRTNAME, VHLNO, DRVNAME, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, 
                         CONTNRID, CONTNRSID, CONTNRNO, LPSEALNO, CSEALNO, YRDID, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, IGMNO, GPLNO, GPWTYPE, GPSTYPE, GPETYPE, BOEDID, INVDID, RGIDID, 
                         GIREMKRS, SLOTID, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, GPEAMT, CHAID, CHANAME, AVHLNO, GPNOP, PRDTTID, GIISOCODE, GIDMGDESC, NGIDID, GPNWGHT, GPGWGHT, GPCBM, GPLENGTH, GPWIDTH, 
                         GPHEIGHT, GPBLNO, GPAAMT, CLNTID, CLNTNAME, SHPRNAME, GPPLCNAME, GPTWGHT, CONTNRFID, CONDTNID, GRADEID, CNTNRSID, GPPTYPE, GFCLTYPE, GSEALTYPE, GSECTYPE, GSEALREMKRS, GSECREMKRS, 
                         GPNRNO, ESBNO, EVSLRNO, EMONO, EEGMNO, ESBDATE, GPSCNTYPE, IGMDATE, BLNO, GPMODEID, OLDGID)
Select COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GIVHLTYPE, TRNSPRTID, TRNSPRTNAME, VHLNO, 
DRVNAME, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, CONTNRID, CONTNRSID, 
[SCFS].dbo.GATEINDETAIL.CONTNRNO, LPSEALNO, CSEALNO, YRDID, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, 
[SCFS].dbo.GATEINDETAIL.IGMNO, [SCFS].dbo.GATEINDETAIL.GPLNO, GPWTYPE, GPSTYPE, GPETYPE, BOEDID, INVDID, RGIDID, 
GIREMKRS, SLOTID, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, GPEAMT, CHAID, CHANAME, AVHLNO, GPNOP, PRDTTID, GIISOCODE, 
GIDMGDESC, NGIDID, GPNWGHT, GPGWGHT, GPCBM, GPLENGTH, GPWIDTH, GPHEIGHT, GPBLNO, GPAAMT, CLNTID, CLNTNAME, SHPRNAME, 
GPPLCNAME, GPTWGHT, CONTNRFID, CONDTNID, GRADEID, CNTNRSID, GPPTYPE, GFCLTYPE, GSEALTYPE, GSECTYPE, GSEALREMKRS, 
GSECREMKRS, GPNRNO, ESBNO, EVSLRNO, EMONO, EEGMNO, ESBDATE, GPSCNTYPE, IGMDATE, BLNO, GPMODEID, GATEINDETAIL.GIDID
From [SCFS].dbo.GATEINDETAIL (NOLOCK) INNER JOIN
       [SCFS].dbo.z_din_18092021 (NOLOCK) ON [SCFS].dbo.GATEINDETAIL.GIDID = [SCFS].dbo.z_din_18092021.GIDID



--Cursor
USE [SCFS_ERP]
GO
/****** Object:  StoredProcedure [dbo].[Z_IMPORT_OPNSHEET_DETAIL_Auto_Generate_XML]    Script Date: 20/09/2021 19:37:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[Z_IMPORT_OPNSHEET_DETAIL_Auto_Generate_XML]
AS
BEGIN
	SET NOCOUNT ON
	
      DECLARE @Counter INT
      SET @Counter = 1
      
	  --Delete From OPENSHEETMASTER 

	  Declare @OSMID int

      --DECLARE THE CURSOR FOR A QUERY.
      DECLARE OSDetail CURSOR READ_ONLY
      FOR
	  
	  Select [SCFS].dbo.OPENSHEETMASTER.OSMID From [SCFS].dbo.OPENSHEETMASTER INNER JOIN
	  [SCFS].dbo.z_din_18092021 ON [SCFS].dbo.OPENSHEETMASTER.OSMID = [SCFS].dbo.z_din_18092021.OSMID
	  Group by [SCFS].dbo.OPENSHEETMASTER.OSMID
	  Order by [SCFS].dbo.OPENSHEETMASTER.OSMID
  
      --OPEN CURSOR.
      OPEN OSDetail
 
      --FETCH THE RECORD INTO THE VARIABLES.
      FETCH NEXT FROM OSDetail INTO @OSMID
 
      --LOOP UNTIL RECORDS ARE AVAILABLE.
      WHILE @@FETCH_STATUS = 0
      BEGIN

			EXEC Z_IMPORT_OPNSHEET_DETAIL_INSERT_XML @OSMID, 0, 0
             --INCREMENT COUNTER.
			 
             SET @Counter = @Counter + 1
             
             --FETCH THE NEXT RECORD INTO THE VARIABLES.
             FETCH NEXT FROM OSDetail INTO @OSMID
      END
 
      --CLOSE THE CURSOR.
      CLOSE OSDetail
      DEALLOCATE OSDetail


END


--DEtail Insert
USE [SCFS_ERP]
GO
/****** Object:  StoredProcedure [dbo].[Z_IMPORT_OPNSHEET_DETAIL_INSERT_XML]    Script Date: 20/09/2021 19:37:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
alter PROCEDURE [dbo].[Z_IMPORT_OPNSHEET_DETAIL_INSERT_XML] 
@POSMID INT,
@OSMID INT OUTPUT,
@BILLEMID INT OUTPUT

AS
BEGIN
	  SET NOCOUNT ON
	
	  Declare @ccount int, @boecount int

	  Set @ccount = 1
	  Set @boecount = 0

	  If @ccount > 0 

  			INSERT INTO [SCFS_ERP].[dbo].[OPENSHEETMASTER]
			(
			  SDPTID, COMPYID, OSMDATE, OSMTIME, OSMNO, OSMDNO, CHAID, OSMNAME, OSMCNAME, OSMIGMNO, 
			  OSMVSLNAME, BOENO, BOEDATE, OSMTYPE, DOTYPE, DODATE, CUSRID, LMUSRID, DISPSTATUS, 
              PRCSDATE, OSMLNO, DONO, DOIDATE, SCTYPE, SCDESC, SCDATE, SCTIME, SCREMRKS, OSMAAMT, 
			  OSMBLNO, OSMNOP, OSMWGHT, OSMUNITID, OSMLNAME, OSMTNOC, OSMFNOC, OSMLCATEID, OSMLCATENAME, 
              OSBILLEDTO, OSBILLREFID, OSBILLREFNAME, OSCATEAID, OSMLDTYPE, OSMBLDATE, OSMIGMDATE
			)
			Select SDPTID, COMPYID, OSMDATE, OSMTIME, OSMNO, OSMDNO, CHAID, OSMNAME, OSMCNAME, OSMIGMNO, 
			  OSMVSLNAME, BOENO, BOEDATE, OSMTYPE, DOTYPE, DODATE, CUSRID, LMUSRID, DISPSTATUS, 
              PRCSDATE, OSMLNO, DONO, DOIDATE, SCTYPE, SCDESC, SCDATE, SCTIME, SCREMRKS, OSMAAMT, 
			  OSMBLNO, OSMNOP, OSMWGHT, OSMUNITID, OSMLNAME, OSMTNOC, OSMFNOC, OSMLCATEID, OSMLCATENAME, 
              OSBILLEDTO, (CASE OSBILLREFID WHEN 0 THEN CHAID ELSE OSBILLREFID END) AS OSBILLREFID, 
			  (CASE OSBILLREFID WHEN 0 THEN OSMNAME ELSE OSBILLREFNAME END) AS OSBILLREFNAME, OSCATEAID,0, OSMBLDATE
			  From [SCFS].dbo.OPENSHEETMASTER INNER JOIN
				   [SCFS].dbo.z_din_18092021 ON [SCFS].dbo.OPENSHEETMASTER.OSMID = [SCFS].dbo.z_din_18092021.OSMID
			  Where [SCFS].dbo.OPENSHEETMASTER.OSMID = @POSMID
			  Group by SDPTID, COMPYID, OSMDATE, OSMTIME, OSMNO, OSMDNO, CHAID, OSMNAME, OSMCNAME, OSMIGMNO, 
			  OSMVSLNAME, BOENO, BOEDATE, OSMTYPE, DOTYPE, DODATE, CUSRID, LMUSRID, DISPSTATUS, 
              PRCSDATE, OSMLNO, DONO, DOIDATE, SCTYPE, SCDESC, SCDATE, SCTIME, SCREMRKS, OSMAAMT, 
			  OSMBLNO, OSMNOP, OSMWGHT, OSMUNITID, OSMLNAME, OSMTNOC, OSMFNOC, OSMLCATEID, OSMLCATENAME, 
              OSBILLEDTO, (CASE OSBILLREFID WHEN 0 THEN CHAID ELSE OSBILLREFID END) , 
			  (CASE OSBILLREFID WHEN 0 THEN OSMNAME ELSE OSBILLREFNAME END) , OSCATEAID

     
			 SET @OSMID = SCOPE_IDENTITY()

  			INSERT INTO [SCFS_ERP].[dbo].[BILLENTRYMASTER]
			(
			  SDPTID, COMPYID, BILLEMDATE, BILLEMTIME, BILLEMNO, BILLEMDNO, CHAID, BILLEMNAME, BILLEMAAMT, 
			  BLNO, NOP, WGHT, UNITID, BILLEDMTYPE, DPAIDNO, DPAIDAMT, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE
			)
			Select SDPTID, COMPYID, BILLEMDATE, BILLEMTIME, BILLEMNO, BILLEMDNO, CHAID, BILLEMNAME, BILLEMAAMT, 
			  BLNO, NOP, WGHT, UNITID, BILLEDMTYPE, DPAIDNO, DPAIDAMT, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE
			  From [SCFS].dbo.BILLENTRYMASTER INNER JOIN
				   [SCFS].dbo.z_din_18092021 ON [SCFS].dbo.BILLENTRYMASTER.BILLEMID = [SCFS].dbo.z_din_18092021.BILLEMID
			  Where [SCFS].dbo.z_din_18092021.OSMID = @POSMID
			  Group by SDPTID, COMPYID, BILLEMDATE, BILLEMTIME, BILLEMNO, BILLEMDNO, CHAID, BILLEMNAME, BILLEMAAMT, 
			  BLNO, NOP, WGHT, UNITID, BILLEDMTYPE, DPAIDNO, DPAIDAMT, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE

			  SET @BILLEMID = SCOPE_IDENTITY()

            INSERT INTO [SCFS_ERP].dbo.OPENSHEETDETAIL(
			OSMID, GIDID, GIDATE, INSPTYPE, LSEALNO, SSEALNO, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, BILLEDID, 
			CSEALNO)
			Select @OSMID, GIDID, GIDATE, INSPTYPE, LSEALNO, SSEALNO, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, 
			0, ''
			From [SCFS].dbo.OPENSHEETDETAIL Where OSMID = @POSMID 
			Order by [SCFS].dbo.OPENSHEETDETAIL.OSDID

            INSERT INTO [SCFS_ERP].dbo.BILLENTRYDETAIL(
			BILLEMID, GIDID, GIDATE, DNOP, DWGHT, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE)
			Select @BILLEMID, [SCFS].dbo.BILLENTRYDETAIL.GIDID, [SCFS].dbo.BILLENTRYDETAIL.GIDATE, 
			[SCFS].dbo.BILLENTRYDETAIL.DNOP, [SCFS].dbo.BILLENTRYDETAIL.DWGHT, 
			[SCFS].dbo.BILLENTRYDETAIL.CUSRID, [SCFS].dbo.BILLENTRYDETAIL.LMUSRID, 
			[SCFS].dbo.BILLENTRYDETAIL.DISPSTATUS, [SCFS].dbo.BILLENTRYDETAIL.PRCSDATE
			From [SCFS].dbo.OPENSHEETDETAIL INNER JOIN
				   [SCFS].dbo.BILLENTRYDETAIL ON [SCFS].dbo.OPENSHEETDETAIL.BILLEDID = [SCFS].dbo.BILLENTRYDETAIL.BILLEDID
			Where OSMID = @POSMID 
			Order by [SCFS].dbo.OPENSHEETDETAIL.OSDID


			
			

			update a
			SET GIDID = B.GIDID
			from [SCFS_ERP].dbo.OPENSHEETDETAIL a, SCFS_ERP.DBO.GATEINDETAIL B(NOLOCK)
			WHERE A.GIDID = B.OLDGID

			update a
			SET GIDID = B.GIDID
			from [SCFS_ERP].dbo.BILLENTRYDETAIL a, SCFS_ERP.DBO.GATEINDETAIL B(NOLOCK)
			WHERE A.GIDID = B.OLDGID

			update a
			SET IGMDATE = B.IGMDATE
			from [SCFS_ERP].dbo.GATEINDETAIL a, SCFS.DBO.GATEINDETAIL B(NOLOCK)
			WHERE A.OLDGID = B.GIDID

			update a
			SET OSMBLDATE = B.IGMDATE
			from [SCFS_ERP].dbo.OPENSHEETMASTER a, SCFS_ERP.DBO.GATEINDETAIL B(NOLOCK), [SCFS_ERP].dbo.OPENSHEETDETAIL c
			WHERE c.GIDID = B.GIDID
			and c.OSMID = a.OSMID
END




--Update CHA Adress Detaila
UPDATE OPENSHEETMASTER SET OSBCHACATEAID = CATEAID, OSBCHACATEAGSTNO = CATEAGSTNO,
OSBCHAADDR1 = CATEAADDR1, OSBCHAADDR2 = CATEAADDR2, OSBCHAADDR3 = CATEAADDR3, OSBCHAADDR4 = CATEAADDR4,
OSBCHASTATEID  = CATEGORY_ADDRESS_DETAIL.STATEID
FROM SCFS_ERP.DBO.OPENSHEETMASTER INNER JOIN
				   SCFS_ERP.dbo.CATEGORY_ADDRESS_DETAIL ON dbo.OPENSHEETMASTER.CHAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID

--Update Billing CHA Adress Detaila
UPDATE OPENSHEETMASTER SET OSBCHACATEAID = CATEAID, OSBBCHACATEAGSTNO = CATEAGSTNO,
OSBBCHAADDR1 = CATEAADDR1, OSBBCHAADDR2 = CATEAADDR2, OSBBCHAADDR3 = CATEAADDR3, OSBBCHAADDR4 = CATEAADDR4,
OSBBCHASTATEID  = CATEGORY_ADDRESS_DETAIL.STATEID
FROM OPENSHEETMASTER INNER JOIN
				   dbo.CATEGORY_ADDRESS_DETAIL ON dbo.OPENSHEETMASTER.OSBILLREFID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID


--Open Sheet BillEDID Update

update OPENSHEETDETAIL Set OPENSHEETDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID
FROM            dbo.OPENSHEETDETAIL INNER JOIN
                         dbo.BILLENTRYDETAIL ON dbo.OPENSHEETDETAIL.GIDID = dbo.BILLENTRYDETAIL.GIDID

