SELECT  TOP 100 PERCENT isnull(Convert(varchar(10),GATEINDETAIL.GIDATE, 103),'') as GIDATE, ISNULL(GATEINDETAIL.GIDNO,'') as GIDNO,
	                       isnull(Convert(varchar(10),EXPORTSHIPPINGBILLMASTER.ESBMIDATE, 103),'') as ESBMIDATE,
	                       
	                       --ISNULL(EXPORTSHIPPINGBILLMASTER.ESBMIDATE,'') as ESBMIDATE, 
						   ISNULL(EXPORTSHIPPINGBILLMASTER.ESBMDNO,'') as ESBMDNO, 
						   --ISNULL(SHIPPINGBILLMASTER.SBMDATE,'') as SBMDATE, 
						    isnull(Convert(varchar(10),SHIPPINGBILLMASTER.SBMDATE, 103),'') as SBMDATE,
						   ISNULL(SHIPPINGBILLMASTER.SBMDNO,'') as SBMDNO, 
						   ISNULL(GATEINDETAIL.PRDTDESC,'') as PRDTDESC,ISNULL(GATEINDETAIL.VHLNO,'') as VHLNO,
	                       ISNULL(GATEINDETAIL.VSLNAME,'') as VSLNAME,ISNULL(SHIPPINGBILLDETAIL.UNLOADEDNOP,0) as SBDQTY,
						   ISNULL(SHIPPINGBILLMASTER.DISPSTATUS,0) as DISPSTATUS,ISNULL(SHIPPINGBILLDETAIL.GIDID,0) as GIDID,
						   ISNULL(EXPORTSHIPPINGBILLMASTER.ESBMID,0) as ESBMID, ISNULL(SHIPPINGBILLMASTER.SBMID,0) as SBMID,
						   ISNULL(SHIPPINGBILLDETAIL.SBDID,0) as SBDID,
						   EXPORTSHIPPINGBILLDETAIL.*
	FROM   SHIPPINGBILLDETAIL (nolock) Inner Join 
	       SHIPPINGBILLMASTER (nolock) ON SHIPPINGBILLMASTER.SBMID = SHIPPINGBILLDETAIL.SBMID INNER Join 
		   EXPORTSHIPPINGBILLMASTER (nolock) ON SHIPPINGBILLDETAIL.ESBMID = EXPORTSHIPPINGBILLMASTER.ESBMID  Left join 
		   EXPORTSHIPPINGBILLDETAIL (nolock) ON EXPORTSHIPPINGBILLMASTER.ESBMID = EXPORTSHIPPINGBILLDETAIL.ESBMID
		   and SHIPPINGBILLDETAIL.GIDID = EXPORTSHIPPINGBILLDETAIL.GIDID Left join
		   GATEINDETAIL (nolock) ON SHIPPINGBILLDETAIL.GIDID = GATEINDETAIL.GIDID 
		   
   WHERE   GATEINDETAIL.CONTNRID=1 
   --AND GIDATE>= '2022-04-01'
   and		(isnull(EXPORTSHIPPINGBILLDETAIL.ESBMID,0) = 0 OR ISNULL(SHIPPINGBILLDETAIL.GIDID,0) =0 or EXPORTSHIPPINGBILLDETAIL.gidid is null)
   and		ISNULL(SHIPPINGBILLDETAIL.UNLOADEDNOP,0) > 0 
   and EXPORTSHIPPINGBILLMASTER.ESBMID =64589

   --update EXPORTSHIPPINGBILLDETAIL
   --set GIDID = null
   --FROM   SHIPPINGBILLDETAIL (nolock) Inner Join 
	  --     SHIPPINGBILLMASTER (nolock) ON SHIPPINGBILLMASTER.SBMID = SHIPPINGBILLDETAIL.SBMID INNER Join 
		 --  EXPORTSHIPPINGBILLMASTER (nolock) ON SHIPPINGBILLDETAIL.ESBMID = EXPORTSHIPPINGBILLMASTER.ESBMID  Left join 
		 --  EXPORTSHIPPINGBILLDETAIL (nolock) ON EXPORTSHIPPINGBILLMASTER.ESBMID = EXPORTSHIPPINGBILLDETAIL.ESBMID  Left join
		 --  GATEINDETAIL (nolock) ON SHIPPINGBILLDETAIL.GIDID = GATEINDETAIL.GIDID    
   --WHERE   GATEINDETAIL.CONTNRID=1 
   ----AND GIDATE>= '2022-04-01'
   ----and		(isnull(EXPORTSHIPPINGBILLDETAIL.ESBMID,0) = 0 OR ISNULL(SHIPPINGBILLDETAIL.GIDID,0) =0 or EXPORTSHIPPINGBILLDETAIL.gidid is null)
   --and		ISNULL(SHIPPINGBILLDETAIL.UNLOADEDNOP,0) > 0 
   --and EXPORTSHIPPINGBILLMASTER.ESBMID =64589