USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[SHUTOUTVTDETAIL]    Script Date: 10-01-2023 10:11:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE [SHUTOUTVTDETAIL]
GO

CREATE TABLE [dbo].[SHUTOUTVTDETAIL](
	[VTDID] [int] IDENTITY(1,1) NOT NULL,
	[COMPYID] [int] NOT NULL,
	[SDPTID] [int] NOT NULL,
	[VTDATE] [smalldatetime] NOT NULL,
	[VTTIME] [datetime] NOT NULL,
	[VTNO] [int] NOT NULL,
	[VTDNO] [varchar](15) NOT NULL,
	[ASLDID] [int] NOT NULL,
	[VHLNO] [varchar](15) NULL,
	[DRVNAME] [varchar](100) NULL,
	[VTDESC] [varchar](100) NULL,
	[VTQTY] [numeric](18, 2) NULL,
	[VTTYPE] [int] NULL,
	[VTSTYPE] [int] NULL,
	[VTREMRKS] [varchar](100) NULL,
	[GIDID] [int] NULL,
	[STFMID] [int] NULL,
	[EGIDID] [int] NULL,
	[CUSRID] [varchar](25) NULL,
	[LMUSRID] [varchar](100) NULL,
	[DISPSTATUS] [smallint] NULL,
	[PRCSDATE] [datetime] NULL,
	[VTSSEALNO] [varchar](25) NULL,
	[VTCTYPE] [int] NULL,
	[CGIDID] [int] NULL,
	[STFDID] [int] NULL,
	[EVLDATE] [smalldatetime] NULL,
	[EVSDATE] [smalldatetime] NULL,
	[ELRDATE] [smalldatetime] NULL,
	[TRNSPRTID] [int] NULL,
	[TRNSPRTNAME] [varchar](120) NULL,
	[GTRNSPRTNAME] [varchar](120) NULL,
	[VHLMID] [int] NULL,
	[QRCDIMGPATH] [varchar](255) NULL,
	[OLDVTDID] [int] NULL,
 CONSTRAINT [PK_SHUTOUTVTDETAIL] PRIMARY KEY CLUSTERED 
(
	[VTDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_COMPYID]  DEFAULT ((0)) FOR [COMPYID]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_SDPTID]  DEFAULT ((0)) FOR [SDPTID]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_VTDATE]  DEFAULT (NULL) FOR [VTDATE]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_VTTIME]  DEFAULT (NULL) FOR [VTTIME]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_VTNO]  DEFAULT ((0)) FOR [VTNO]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_VTDNO]  DEFAULT (NULL) FOR [VTDNO]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_ASLDID]  DEFAULT ((0)) FOR [ASLDID]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_VHLNO]  DEFAULT (NULL) FOR [VHLNO]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_DRVNAME]  DEFAULT (NULL) FOR [DRVNAME]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_VTDESC]  DEFAULT (NULL) FOR [VTDESC]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_VTQTY]  DEFAULT ((0)) FOR [VTQTY]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_VTTYPE]  DEFAULT ((0)) FOR [VTTYPE]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_VTSTYPE]  DEFAULT ((0)) FOR [VTSTYPE]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_VTREMKRS]  DEFAULT (NULL) FOR [VTREMRKS]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_GIDID]  DEFAULT ((0)) FOR [GIDID]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_EGIDID]  DEFAULT ((0)) FOR [EGIDID]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_CUSRID]  DEFAULT ('') FOR [CUSRID]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_LMUSRID]  DEFAULT ('') FOR [LMUSRID]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_DISPSTATUS]  DEFAULT ((0)) FOR [DISPSTATUS]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_PRCSDATE]  DEFAULT (NULL) FOR [PRCSDATE]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_VTSSEALNO]  DEFAULT (NULL) FOR [VTSSEALNO]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_VTCTYPE]  DEFAULT ((0)) FOR [VTCTYPE]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_CGIDID]  DEFAULT ((0)) FOR [CGIDID]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_STFDID]  DEFAULT ((0)) FOR [STFDID]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_EVLDATE]  DEFAULT (NULL) FOR [EVLDATE]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_EVSDATE]  DEFAULT (NULL) FOR [EVSDATE]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  CONSTRAINT [DF_SHUTOUTVTDETAIL_ELRDATE]  DEFAULT (NULL) FOR [ELRDATE]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  DEFAULT ((0)) FOR [TRNSPRTID]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  DEFAULT ('') FOR [TRNSPRTNAME]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  DEFAULT ('') FOR [GTRNSPRTNAME]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  DEFAULT ((0)) FOR [VHLMID]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  DEFAULT ('') FOR [QRCDIMGPATH]
GO

ALTER TABLE [dbo].[SHUTOUTVTDETAIL] ADD  DEFAULT ((0)) FOR [OLDVTDID]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'1 - LOAD, 2 - DESTUFF' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SHUTOUTVTDETAIL', @level2type=N'COLUMN',@level2name=N'VTTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'0 - PART DESTUFF, 1 - FULL DESTUFF' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SHUTOUTVTDETAIL', @level2type=N'COLUMN',@level2name=N'VTSTYPE'
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'0 - PART DESTUFF, 1 - FULL DESTUFF' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SHUTOUTVTDETAIL', @level2type=N'COLUMN',@level2name=N'VTCTYPE'
GO


