Select *from SOFT_TABLE_DELETE_DETAIL

INSERT INTO SOFT_TABLE_DELETE_DETAIL(TABDID,OPTNSTR,TABNAME,PFLDNAME,DCONDTNSTR,DISPDESC)
VALUES (53,'VEHICLETICKETDETAIL','GATEINDETAIL INNER JOIN VEHICLETICKETDETAIL ON VEHICLETICKETDETAIL.GIDID=GATEINDETAIL.GIDID',
        'GATEINDETAIL.GIDID','VEHICLETICKETDETAIL.GIDID=','Selected Record Exists In Vehicle ticket Detail ...........!')

		