select *from SOFT_DEPARTMENTMASTER

--update SOFT_DEPARTMENTMASTER set SDPTNAME='E-SEAL',OPTNSTR='E-SEAL' where SDPTID=11

--delete from SOFT_DEPARTMENTMASTER where SDPTID=10


--SET IDENTITY_INSERT DBO.SOFT_DEPARTMENTMASTER ON
--insert into SOFT_DEPARTMENTMASTER (SDPTID, SDPTNAME, OPTNSTR, DISPSTATUS, PRCSDATE)
--select 11, 'E-SEAL', 'E-SEAL',0, getdate()
--SET IDENTITY_INSERT DBO.SOFT_DEPARTMENTMASTER OFF