select * from SOFT_TABLE_DELETE_DETAIL where OPTNSTR= 'DISABLEDESBD' Order by TABDID

select *from VW_STUFFING_CHECKEXISTING_ORGSHIPPINGBILL

Insert Into SOFT_TABLE_DELETE_DETAIL (TABDID,OPTNSTR,TABNAME,PFLDNAME,DCONDTNSTR,DISPDESC)
VALUES(63,'STUFFINGESISTINGCHECK','VW_STUFFING_CHECKEXISTING_ORGSHIPPINGBILL','ESBMID','ESBMID=','Selected Record Referred Stuffing Detail.....!')

