select *from SOFT_TABLE_DELETE_DETAIL

Insert into SOFT_TABLE_DELETE_DETAIL(TABDID,OPTNSTR,TABNAME,PFLDNAME,DCONDTNSTR,DISPDESC)
VALUES(58,'DISABLEDESBD','VW_EXPORT_SHIPPLINGBILLCOUNT_DEATILS_ASSGN','ESBMID','ESBMID=','Selected Record Referred Invoice Detail.....!')