select *from SOFT_TABLE_DELETE_DETAIL

INSERT INTO SOFT_TABLE_DELETE_DETAIL(TABDID,OPTNSTR,TABNAME,PFLDNAME,DCONDTNSTR,DISPDESC)
VALUES(54,'GATEOUTDETAIL','VEHICLETICKETDETAIL INNER JOIN VEHICLETICKETDETAIL ON VEHICLETICKETDETAIL.GIDID=GATEOUTDETAIL.GIDID',
      'VEHICLETICKETDETAIL.GIDID','GATEOUTDETAIL.GIDID=','Selected Record Exists In Gate Out Detail ...........!')


	  update SOFT_TABLE_DELETE_DETAIL SET TABNAME='VEHICLETICKETDETAIL INNER JOIN GATEOUTDETAIL ON VEHICLETICKETDETAIL.GIDID=GATEOUTDETAIL.GIDID' 
	  where TABDID=54

	 

	