-- SELECT * FROM SOFT_DEPARTMENTMASTER

IF NOT EXISTS (SELECT '*' FROM SOFT_DEPARTMENTMASTER WHERE SDPTID = 9)
BEGIN
	INSERT INTO SOFT_DEPARTMENTMASTER (SDPTNAME, OPTNSTR, DISPSTATUS, PRCSDATE)
	SELECT 'NON PNR', 'NONPNR',0, GETDATE()
END