select *from SOFT_TABLE_DELETE_DETAIL where OPTNSTR Like '%ESEAL%'

update SOFT_TABLE_DELETE_DETAIL SET OPTNSTR='ESEALGATEIN',TABNAME='VEHICLETICKETDETAIL',PFLDNAME='GIDID',DCONDTNSTR='GIDID=',DISPDESC='Selected Record Exists In Vehicle ticket Detail ...........!' 
where TABDID=53

update SOFT_TABLE_DELETE_DETAIL SET OPTNSTR='ESEALVEHICLETICKET',TABNAME='GATEOUTDETAIL',PFLDNAME='GODID',DCONDTNSTR='GIDID=',DISPDESC='Selected Record Exists In Gate Out Detail ...........!' 
where TABDID=54