

select *from SOFT_TABLE_DELETE_DETAIL where OPTNSTR='IMPORTDETAILSAUTHSLIP'

insert into SOFT_TABLE_DELETE_DETAIL(TABDID,OPTNSTR,TABNAME,PFLDNAME,DCONDTNSTR,  DISPDESC)
values(59,'IMPORTDETAILSAUTHSLIP','VEHICLETICKETDETAIL','ASLDID','VEHICLETICKETDETAIL.ASLDID=','Selected Record Exists In Vehicle Ticket Detail..........................!')