ALTER PROCEDURE  SP_MANUALOPENSHEET_CONTAINER_FLX_ASSGN @PIGMNO VARCHAR(50) , @PGPLNO AS VARCHAR(15)  AS

SELECT *FROM VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_01 WHERE IGMNO = @PIGMNO AND GPLNO = @PGPLNO ORDER BY CONTNRNO

