alter PROCEDURE [dbo].[SP_STUFFING_SEAL_CONTAINER_NO_CBX_ASSGN] @PCHAID INT,@PSTFMID INT AS

SET NOCOUNT ON

SELECT     dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO
FROM         dbo.GATEINDETAIL LEFT OUTER JOIN
                      dbo.STUFFINGDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.STUFFINGDETAIL.GIDID
WHERE   (dbo.GATEINDETAIL.GPSTYPE IN ( 5)) AND (dbo.GATEINDETAIL.CHAID = @PCHAID) AND (ISNULL(dbo.STUFFINGDETAIL.STFMID, 0) = @PSTFMID) 