
alter PROCEDURE [dbo].[SP_SHIPPINGBILL_GATEINT_TRUCKNO_CBX_ASSGN] 
@PCHAID INT ,
@PEXPRTID INT ,
@PCUSRID VARCHAR(25)
AS


SELECT     dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.AVHLNO, gateindetail.chaid, GATEINDETAIL.CHANAME, GATEINDETAIL.bCHANAME,
			isnull(EXPORTSHIPPINGBILLMASTER.ESBMDNO,'-') as ESBMDNO,
          isnull(EXPORTSHIPPINGBILLMASTER.ESBMID,0) as ESBMID
FROM       dbo.GATEINDETAIL (nolock) LEFT OUTER JOIN 
	       EXPORTSHIPPINGBILLMASTER (nolock) ON GATEINDETAIL.ESBMID = EXPORTSHIPPINGBILLMASTER.ESBMID  LEFT OUTER JOIN 
	   SHIPPINGBILLDETAIL (nolock) ON EXPORTSHIPPINGBILLMASTER.ESBMID = SHIPPINGBILLDETAIL.ESBMID left join 
	   SHIPPINGBILLMASTER (nolock) ON SHIPPINGBILLMASTER.SBMID = SHIPPINGBILLDETAIL.SBMID LEFT JOIN
	   TMP_CARTING_ORDER_TRUCK_DUPCHK (NOLOCK) ON GATEINDETAIL.GIDID = TMP_CARTING_ORDER_TRUCK_DUPCHK.GIDID AND TMP_CARTING_ORDER_TRUCK_DUPCHK.CUSRID = @PCUSRID
		   
WHERE     (dbo.GATEINDETAIL.GPSTYPE IN (1, 5)) AND (dbo.GATEINDETAIL.SDPTID = 2) 
and isnull(SHIPPINGBILLDETAIL.SBMID,0) = 0 
AND (dbo.GATEINDETAIL.CHAID = @PCHAID) 
AND TMP_CARTING_ORDER_TRUCK_DUPCHK.TRUCKNO IS NULL
--AND (dbo.EXPORTSHIPPINGBILLMASTER.EXPRTID = @PEXPRTID) 
ORDER BY dbo.GATEINDETAIL.AVHLNO



