alter PROCEDURE [dbo].[SP_STUFFING_CONTAINER_NO_CBX_ASSGN] @PCHAID INT,@PSTFMID INT AS

/*
SELECT     dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO
FROM         dbo.GATEINDETAIL LEFT OUTER JOIN
                      dbo.STUFFINGDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.STUFFINGDETAIL.GIDID
WHERE (dbo.GATEINDETAIL.DispStatus = 0) and      (dbo.GATEINDETAIL.GPSTYPE = 4) AND (dbo.GATEINDETAIL.CHAID = @PCHAID) AND (ISNULL(dbo.STUFFINGDETAIL.STFMID, 0) = 0)
AND (GIDATE >= '01-APR-2012')
 OR
          (dbo.GATEINDETAIL.DispStatus = 0) and        (dbo.GATEINDETAIL.GPSTYPE = 4) AND (dbo.GATEINDETAIL.CHAID = @PCHAID) AND (ISNULL(dbo.STUFFINGDETAIL.STFMID, 0) = @PSTFMID)  AND (GIDATE >= '01-APR-2012')
*/
SELECT     dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO,ISNULL(dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO ,'') AS CATEAGSTNO
FROM         dbo.GATEINDETAIL LEFT OUTER JOIN
                      dbo.STUFFINGDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.STUFFINGDETAIL.GIDID LEfT  JOIN 
					  dbo.CATEGORYMASTER on dbo.GATEINDETAIL.CHAID = dbo.CATEGORYMASTER.CATEID LEFT JOIN 
					  dbo.CATEGORY_ADDRESS_DETAIL on dbo.CATEGORYMASTER.CATEID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID 
WHERE     (dbo.GATEINDETAIL.DISPSTATUS = 0) AND (dbo.GATEINDETAIL.GPSTYPE = 4 )
          AND (dbo.GATEINDETAIL.CHAID = @PCHAID) AND (ISNULL(dbo.STUFFINGDETAIL.STFMID, 0) = @PSTFMID) AND (dbo.GATEINDETAIL.CONTNRSID >= 2) 
--	   EXEC SP_STUFFING_CONTAINER_NO_CBX_ASSGN @PCHAID=2296,@PSTFMID=0

