select *from CREDITNOTE_TRANSACTIONMASTER

select *from CREDITNOTE_TRANSACTIONMASTER where TRANMID=6

select *from VW_EXPORT_GATE_OUT_PRINT_ASSGN

Select Top 1  *From CATEGORY_ADDRESS_DETAIL Where CATEID  = 68628 ORDER By  CATEAID DESC

select *from CATEGORYMASTER where CATEID =68628 

