USE [SCFS_ERP]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_IMPORT_EMPTY_ADSLIP_PRINT_ASSGN]
AS
SELECT TMPRPT_IDS.KUSRID,dbo.COMPANYMASTER.COMPNAME,GATEINDETAIL.GIDID, AUTHORIZATIONSLIPMASTER.ASLMID,AUTHORIZATIONSLIPMASTER.ASLMDNO,
        AUTHORIZATIONSLIPMASTER.ASLMTIME,AUTHORIZATIONSLIPMASTER.ASLMDATE,AUTHORIZATIONSLIPMASTER.ASLMTYPE,
       dbo.GATEINDETAIL.COMPYID, dbo.GATEINDETAIL.SDPTID, dbo.GATEINDETAIL.GIDATE, dbo.GATEINDETAIL.GITIME, dbo.GATEINDETAIL.GINO, 
	   dbo.GATEINDETAIL.GIDNO, dbo.GATEINDETAIL.VHLNO, dbo.GATEINDETAIL.DRVNAME, dbo.GATEINDETAIL.GPREFNO, dbo.GATEINDETAIL.IMPRTNAME,
	   dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.CONTNRNO, dbo.GATEINDETAIL.CONTNRSID, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
	   Isnull(dbo.CONTAINERTYPEMASTER.CONTNRTCODE,'') as CONTNRTCODE, isnull(dbo.GATEINDETAIL.VSLNAME, '') as VSLNAME,isnull(dbo.GATEINDETAIL.VOYNO, '') as VOYNO,
	   isnull(dbo.GATEINDETAIL.IGMNO, '') as IGMNO, isnull(dbo.GATEINDETAIL.GPLNO, '') as GPLNO,isnull(dbo.GATEINDETAIL.GPWGHT,0) as GPWGHT,
	   isnull(dbo.GATEINDETAIL.PRDTDESC,'') as PRDTDESC,isnull(dbo.GATEINDETAIL.CHANAME,'') as CHANAME

FROM    dbo.AUTHORIZATIONSLIPMASTER (NOLOCK) INNER JOIN  
        dbo.AUTHORIZATIONSLIPDETAIL (NOLOCK) ON  AUTHORIZATIONSLIPMASTER.ASLMID =   AUTHORIZATIONSLIPDETAIL.ASLMID INNER JOIN 
		dbo.GATEINDETAIL (NOLOCK) ON AUTHORIZATIONSLIPDETAIL.OSDID = GATEINDETAIL.GIDID INNER JOIN 
		dbo.TMPRPT_IDS (NOLOCK) ON AUTHORIZATIONSLIPMASTER.CUSRID = TMPRPT_IDS.KUSRID INNER JOIN  
		dbo.CONTAINERSIZEMASTER (NOLOCK) ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN  
		dbo.COMPANYACCOUNTINGDETAIL (NOLOCK) ON dbo.GATEINDETAIL.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN   
		dbo.COMPANYMASTER (NOLOCK) ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID LEFT OUTER JOIN  
		dbo.VEHICLETICKETDETAIL (NOLOCK)  ON dbo.GATEINDETAIL.GIDID = dbo.VEHICLETICKETDETAIL.EGIDID LEFT OUTER JOIN  
		dbo.BILLENTRYDETAIL (NOLOCK)  ON dbo.VEHICLETICKETDETAIL.GIDID = dbo.BILLENTRYDETAIL.GIDID LEFT OUTER JOIN  
		dbo.BILLENTRYMASTER (NOLOCK)  ON dbo.BILLENTRYDETAIL.BILLEMID = dbo.BILLENTRYMASTER.BILLEMID LEFT OUTER JOIN 
		dbo.CONTAINERTYPEMASTER (NOLOCK) ON  dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID 
		
		   WHERE     (dbo.GATEINDETAIL.SDPTID=3)



GO


