USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[STUFFINGPRODUCTDETAIL]    Script Date: 07/08/2021 16:24:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[STUFFINGPRODUCTDETAIL](
	[STFPID] [int] IDENTITY(1,1) NOT NULL,
	[STFDID] [int] NOT NULL CONSTRAINT [DF_STUFFINGPRODUCTDETAIL_STFDID]  DEFAULT ((0)),
	[SBDID] [int] NOT NULL CONSTRAINT [DF_STUFFINGPRODUCTDETAIL_SBDID]  DEFAULT ((0)),
	[STFDSBNO] [varchar](25) NOT NULL CONSTRAINT [DF_STUFFINGPRODUCTDETAIL_STFDSBNO]  DEFAULT (NULL),
	[STFDSBDNO] [varchar](25) NOT NULL CONSTRAINT [DF_STUFFINGPRODUCTDETAIL_STFDSBDNO]  DEFAULT (NULL),
	[STFDSBDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_STUFFINGPRODUCTDETAIL_STFDSBDATE]  DEFAULT (NULL),
	[STFDSBDDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_STUFFINGPRODUCTDETAIL_STFDSBDDATE]  DEFAULT (NULL),
	[STFDNOP] [numeric](18, 2) NULL CONSTRAINT [DF_STUFFINGPRODUCTDETAIL_STFDNOP]  DEFAULT ((0)),
	[STFDQTY] [numeric](18, 4) NULL CONSTRAINT [DF_STUFFINGPRODUCTDETAIL_STFDQTY]  DEFAULT ((0)),
	[CUSRID] [varchar](50) NULL CONSTRAINT [DF_STUFFINGPRODUCTDETAIL_CUSRID]  DEFAULT ((0)),
	[LMUSRID] [varchar](50) NULL CONSTRAINT [DF_STUFFINGPRODUCTDETAIL_LMUSRID]  DEFAULT ((0)),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_STUFFINGPRODUCTDETAIL_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_STUFFINGPRODUCTDETAIL_PRCSDATE]  DEFAULT (NULL),
	[STFCORDNO] [varchar](25) NULL CONSTRAINT [DF_STUFFINGPRODUCTDETAIL_STFCORDNO]  DEFAULT (NULL),
 CONSTRAINT [PK_STUFFINGPRODUCTDETAIL] PRIMARY KEY CLUSTERED 
(
	[STFPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[STUFFINGPRODUCTDETAIL]  WITH NOCHECK ADD  CONSTRAINT [FK_STUFFINGPRODUCTDETAIL_STUFFINGDETAIL] FOREIGN KEY([STFDID])
REFERENCES [dbo].[STUFFINGDETAIL] ([STFDID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[STUFFINGPRODUCTDETAIL] CHECK CONSTRAINT [FK_STUFFINGPRODUCTDETAIL_STUFFINGDETAIL]
GO


