ALTER TABLE STUFFINGPRODUCTDETAIL
add ESBDID int default 0

ALTER TABLE STUFFINGPRODUCTDETAIL
add ESBD_SBILLNO varchar(25) default ''

ALTER TABLE STUFFINGPRODUCTDETAIL
add ESBD_SBILLDATE smalldatetime NULL default NULL


update STUFFINGPRODUCTDETAIL
set ESBDID = 0
where ESBDID is null



update STUFFINGPRODUCTDETAIL
set ESBD_SBILLNO = ''
where ESBD_SBILLNO is null

