
select TOP (100) PERCENT 
dbo.SHIPPINGBILLDETAIL.UNLOADEDNOP,
dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP,VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.SBDID,
 ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.TRANDNOP, 0) ,
ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.NOP, 0),
dbo.SHIPPINGBILLMASTER.CHAID
FROM            dbo.SHIPPINGBILLDETAIL (nolock) INNER JOIN
                         dbo.SHIPPINGBILLMASTER  (nolock) ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID INNER JOIN
                         dbo.VW_YEAR_DETAIL_CBX_ASSGN  (nolock) ON dbo.SHIPPINGBILLMASTER.COMPYID = dbo.VW_YEAR_DETAIL_CBX_ASSGN.COMPYID INNER JOIN
                         dbo.EXPORTSHIPPINGBILLMASTER (nolock)  ON dbo.SHIPPINGBILLDETAIL.ESBMID = dbo.EXPORTSHIPPINGBILLMASTER.ESBMID LEFT OUTER JOIN
                         dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03 (nolock)  ON dbo.SHIPPINGBILLDETAIL.SBDID = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.SBDID LEFT OUTER JOIN
                         dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02  (nolock) ON dbo.SHIPPINGBILLDETAIL.SBDID = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.SBDID LEFT OUTER JOIN
                         dbo.GATEINDETAIL  (nolock) ON dbo.SHIPPINGBILLDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                         dbo.EXPORTSHIPPINGBILLDETAIL  (nolock) ON dbo.SHIPPINGBILLDETAIL.ESBMID = dbo.EXPORTSHIPPINGBILLDETAIL.ESBMID LEFT OUTER JOIN
                         dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01 (nolock)  ON dbo.SHIPPINGBILLDETAIL.SBDID = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.SBDID AND 
                         dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.ESBD_SBILLNO
WHERE       SHIPPINGBILLDETAIL.SBMID=23447

SELECT        TOP (100) PERCENT
dbo.SHIPPINGBILLDETAIL.UNLOADEDNOP,
dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP,
 --ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.TRANDNOP, 0) ,
--ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.NOP, 0),
dbo.SHIPPINGBILLMASTER.CHAID, dbo.SHIPPINGBILLDETAIL.SBMID, dbo.SHIPPINGBILLDETAIL.SBDID, LTRIM(dbo.SHIPPINGBILLMASTER.SBMDNO) 
                         + '(' + dbo.VW_YEAR_DETAIL_CBX_ASSGN.YRDESC + ')' AS SBMDNO, CONVERT(varchar(10), dbo.SHIPPINGBILLMASTER.SBMDATE, 103) AS SBMDATE, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO, CONVERT(varchar(10), 
                         dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE, 103) AS ESBMDATE, dbo.SHIPPINGBILLDETAIL.SBDNO, dbo.SHIPPINGBILLDETAIL.SBDDNO, CONVERT(varchar(10), dbo.SHIPPINGBILLDETAIL.SBDDATE, 103) AS SBDDATE, 
                         dbo.SHIPPINGBILLDETAIL.PRDTDESC, dbo.SHIPPINGBILLDETAIL.UNLOADEDNOP AS sbdnop, ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.KUSRID, '') AS KUSRID, 
                         dbo.SHIPPINGBILLDETAIL.UNLOADEDNOP AS OBNOP, ISNULL(dbo.GATEINDETAIL.GIDID, 0) AS GIDID, ISNULL(dbo.GATEINDETAIL.CONTNRNO, '') AS CONTNRNO, dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO, 
                         CONVERT(varchar(10), dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLDATE, 103) AS ESBD_SBILLDATE, dbo.EXPORTSHIPPINGBILLDETAIL.ESBOINVNO, CONVERT(varchar(10), 
                         dbo.EXPORTSHIPPINGBILLDETAIL.ESBOINVDATE, 103) AS ESBOINVDATE, dbo.EXPORTSHIPPINGBILLDETAIL.ESBOINVAMT, dbo.EXPORTSHIPPINGBILLDETAIL.ESBOINVFOBAMT, 
                         dbo.EXPORTSHIPPINGBILLDETAIL.ESBDDPNAME, dbo.SHIPPINGBILLDETAIL.UNLOADEDNOP AS ESBMNOP, 
                         dbo.SHIPPINGBILLDETAIL.UNLOADEDNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0) - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.TRANDNOP, 0) 
                         - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.NOP, 0) AS BNOP, dbo.EXPORTSHIPPINGBILLDETAIL.ESBDID, ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.SBDID, 0) AS id, 
                         ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.ESBD_SBILLNO, '') AS sbno, ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.SBDID, 0) AS s2id, 
                         ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.SBDID, 0) AS s3id, dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP
FROM            dbo.SHIPPINGBILLDETAIL (nolock) INNER JOIN
                         dbo.SHIPPINGBILLMASTER  (nolock) ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID INNER JOIN
                         dbo.VW_YEAR_DETAIL_CBX_ASSGN  (nolock) ON dbo.SHIPPINGBILLMASTER.COMPYID = dbo.VW_YEAR_DETAIL_CBX_ASSGN.COMPYID INNER JOIN
                         dbo.EXPORTSHIPPINGBILLMASTER (nolock)  ON dbo.SHIPPINGBILLDETAIL.ESBMID = dbo.EXPORTSHIPPINGBILLMASTER.ESBMID LEFT OUTER JOIN
                         dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03 (nolock)  ON dbo.SHIPPINGBILLDETAIL.SBDID = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.SBDID LEFT OUTER JOIN
                         dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02  (nolock) ON dbo.SHIPPINGBILLDETAIL.SBDID = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.SBDID LEFT OUTER JOIN
                         dbo.GATEINDETAIL  (nolock) ON dbo.SHIPPINGBILLDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                         dbo.EXPORTSHIPPINGBILLDETAIL  (nolock) ON dbo.SHIPPINGBILLDETAIL.ESBMID = dbo.EXPORTSHIPPINGBILLDETAIL.ESBMID LEFT OUTER JOIN
                         dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01 (nolock)  ON dbo.SHIPPINGBILLDETAIL.SBDID = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.SBDID AND 
                         dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.ESBD_SBILLNO
WHERE       SHIPPINGBILLDETAIL.SBMID=23447 and
(dbo.SHIPPINGBILLDETAIL.UNLOADEDNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0) - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.TRANDNOP, 0) 
                         - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.NOP, 0) > 0)
GROUP BY dbo.SHIPPINGBILLDETAIL.SBMID, dbo.SHIPPINGBILLDETAIL.SBDDNO, dbo.SHIPPINGBILLDETAIL.SBDNO, dbo.SHIPPINGBILLDETAIL.SBDID, dbo.SHIPPINGBILLDETAIL.SBDDATE, dbo.SHIPPINGBILLDETAIL.PRDTDESC, 
                         dbo.SHIPPINGBILLDETAIL.UNLOADEDNOP, dbo.EXPORTSHIPPINGBILLDETAIL.ESBMNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0) 
                         - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.TRANDNOP, 0) - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.NOP, 0), LTRIM(dbo.SHIPPINGBILLMASTER.SBMDNO) 
                         + '(' + dbo.VW_YEAR_DETAIL_CBX_ASSGN.YRDESC + ')', dbo.SHIPPINGBILLMASTER.SBMDATE, dbo.SHIPPINGBILLMASTER.CHAID, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO, 
                         dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE, dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.KUSRID, dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO, dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO, 
                         dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLDATE, dbo.EXPORTSHIPPINGBILLDETAIL.ESBOINVNO, dbo.EXPORTSHIPPINGBILLDETAIL.ESBOINVDATE, dbo.EXPORTSHIPPINGBILLDETAIL.ESBOINVAMT, 
                         dbo.EXPORTSHIPPINGBILLDETAIL.ESBOINVFOBAMT, dbo.EXPORTSHIPPINGBILLDETAIL.ESBDDPNAME, dbo.EXPORTSHIPPINGBILLDETAIL.ESBMNOP, dbo.EXPORTSHIPPINGBILLDETAIL.ESBMQTY, 
                         dbo.SHIPPINGBILLDETAIL.UNLOADEDNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0) - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.TRANDNOP, 0) 
                         - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.NOP, 0), dbo.EXPORTSHIPPINGBILLDETAIL.ESBDID, dbo.SHIPPINGBILLDETAIL.UNLOADEDNOP, dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.SBDID, 
                         dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.SBDID, dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.SBDID, dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.ESBD_SBILLNO, 
                         dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP
ORDER BY dbo.SHIPPINGBILLDETAIL.SBDNO

