USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[STUFFINGMASTER]    Script Date: 07/08/2021 16:33:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[STUFFINGMASTER](
	[STFMID] [int] IDENTITY(1,1) NOT NULL,
	[COMPYID] [int] NOT NULL CONSTRAINT [DF_STUFFINGMASTER1_COMPYID]  DEFAULT ((0)),
	[STFMDATE] [smalldatetime] NOT NULL CONSTRAINT [DF_STUFFINGMASTER1_STFMDATE]  DEFAULT (NULL),
	[STFMTIME] [datetime] NOT NULL CONSTRAINT [DF_STUFFINGMASTER1_STFMTIME]  DEFAULT (NULL),
	[STFMNO] [int] NOT NULL CONSTRAINT [DF_STUFFINGMASTER1_STFMNO]  DEFAULT ((0)),
	[STFMDNO] [varchar](15) NOT NULL CONSTRAINT [DF_STUFFINGMASTER1_STFMDNO]  DEFAULT (NULL),
	[CHAID] [int] NOT NULL CONSTRAINT [DF_STUFFINGMASTER1_CHAID]  DEFAULT ((0)),
	[STFMNAME] [varchar](100) NULL CONSTRAINT [DF_STUFFINGMASTER1_STFMNAME]  DEFAULT (NULL),
	[CUSRID] [varchar](50) NULL CONSTRAINT [DF_STUFFINGMASTER1_CUSRID]  DEFAULT ((0)),
	[LMUSRID] [varchar](50) NULL CONSTRAINT [DF_STUFFINGMASTER1_LMUSRID]  DEFAULT ((0)),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_STUFFINGMASTER1_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_STUFFINGMASTER1_PRCSDATE]  DEFAULT (NULL),
	[STFTID] [int] NULL CONSTRAINT [DF_STUFFINGMASTER_STFTID]  DEFAULT ((0)),
	[LCATEID] [int] NULL CONSTRAINT [DF_STUFFINGMASTER_LCATEID]  DEFAULT ((0)),
	[LCATENAME] [varchar](100) NULL CONSTRAINT [DF_STUFFINGMASTER_LCATENAME]  DEFAULT (NULL),
	[TGID] [int] NOT NULL CONSTRAINT [DF_STUFFINGMASTER_TGID]  DEFAULT ((0)),
	[EOPTID] [int] NOT NULL DEFAULT ((0)),
	[STFBILLEDTO] [smallint] NOT NULL CONSTRAINT [DF_STUFFINGMASTER_STFBILLEDTO]  DEFAULT ((0)),
	[STFBILLREFID] [int] NOT NULL CONSTRAINT [DF_STUFFINGMASTER_STFBILLREFID]  DEFAULT ((0)),
	[STFBILLREFNAME] [varchar](100) NULL CONSTRAINT [DF_STUFFINGMASTER_STFBILLREFNAME]  DEFAULT (NULL),
	[STFCATEAID] [int] NOT NULL CONSTRAINT [DF_STUFFINGMASTER_STFCATEAID]  DEFAULT ((0)),
	[TRANIMPADDR1] [varchar](100) NULL DEFAULT (NULL),
	[TRANIMPADDR2] [varchar](100) NULL DEFAULT (NULL),
	[TRANIMPADDR3] [varchar](100) NULL DEFAULT (NULL),
	[TRANIMPADDR4] [varchar](100) NULL DEFAULT (NULL),
	[STATEID] [int] NULL DEFAULT ((0)),
	[CATEAGSTNO] [varchar](50) NULL DEFAULT (''),
	[STF_SBILL_RNO] [varchar](50) NULL DEFAULT (NULL),
	[STF_FORM13_RNO] [varchar](50) NULL DEFAULT (NULL),
	[SLABTID] [int] NULL DEFAULT ((0)),
 CONSTRAINT [PK_STUFFINGMASTER1] PRIMARY KEY CLUSTERED 
(
	[STFMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


