USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[STUFFINGDETAIL]    Script Date: 07/08/2021 16:34:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[STUFFINGDETAIL](
	[STFDID] [int] IDENTITY(1,1) NOT NULL,
	[STFMID] [int] NOT NULL CONSTRAINT [DF_STUFFINGDETAIL_STFMID]  DEFAULT ((0)),
	[GIDID] [int] NOT NULL,
	[CUSRID] [varchar](50) NULL CONSTRAINT [DF_STUFFINGDETAIL_CUSRID]  DEFAULT ((0)),
	[LMUSRID] [varchar](50) NULL CONSTRAINT [DF_STUFFINGDETAIL_LMUSRID]  DEFAULT ((0)),
	[DISPSTATUS] [smallint] NULL CONSTRAINT [DF_STUFFINGDETAIL_DISPSTATUS]  DEFAULT ((0)),
	[PRCSDATE] [datetime] NULL CONSTRAINT [DF_STUFFINGDETAIL_PRCSDATE]  DEFAULT (NULL),
	[STFTYPE] [smallint] NOT NULL CONSTRAINT [DF_STUFFINGDETAIL_STFTYPE]  DEFAULT ((0)),
 CONSTRAINT [PK_STUFFINGDETAIL] PRIMARY KEY CLUSTERED 
(
	[STFDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[STUFFINGDETAIL]  WITH NOCHECK ADD  CONSTRAINT [FK_STUFFINGDETAIL_STUFFINGMASTER] FOREIGN KEY([STFMID])
REFERENCES [dbo].[STUFFINGMASTER] ([STFMID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[STUFFINGDETAIL] CHECK CONSTRAINT [FK_STUFFINGDETAIL_STUFFINGMASTER]
GO


