----select * from VW_EXPORT_STUFF_INVOICE_PRINT

--select * from VW_EXPORT_STUFF_INVOICE_PRINT_02 where TRANMID=32052
--select top 5 * from TRANSACTIONMASTER where TRANDNO='exp/2223/02513'


--sp_helptext VW_EXPORT_STUFF_INVOICE_PRINT


--SELECT        TOP (100) PERCENT dbo.TRANSACTIONDETAIL.TRANMID, dbo.SHIPPINGBILLMASTER.EXPRTNAME, dbo.SHIPPINGBILLDETAIL.PRDTDESC, dbo.SHIPPINGBILLDETAIL.SBDNO, 
--                         dbo.SHIPPINGBILLDETAIL.SBDDNO, dbo.SHIPPINGBILLDETAIL.SBDDATE, dbo.SHIPPINGBILLMASTER.SBMDNO, dbo.SHIPPINGBILLMASTER.SBMDATE, 
--                         dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO AS SBILLNO, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE AS SBILLDATE, dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO, 
--                         dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLDATE, (dbo.STUFFINGPRODUCTDETAIL.STFDNOP) AS ESBMNOP, (dbo.STUFFINGPRODUCTDETAIL.STFDQTY) AS ESBMQTY
--select *
--FROM            dbo.SHIPPINGBILLMASTER INNER JOIN
--                         dbo.SHIPPINGBILLDETAIL ON dbo.SHIPPINGBILLMASTER.SBMID = dbo.SHIPPINGBILLDETAIL.SBMID INNER JOIN
--                         dbo.TRANSACTIONDETAIL left JOIN
--                         dbo.STUFFINGDETAIL ON dbo.TRANSACTIONDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID left JOIN
--                         dbo.STUFFINGPRODUCTDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID ON dbo.SHIPPINGBILLDETAIL.SBDID = dbo.STUFFINGPRODUCTDETAIL.SBDID INNER JOIN
--                         dbo.EXPORTSHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.ESBMID = dbo.EXPORTSHIPPINGBILLMASTER.ESBMID INNER JOIN
--                         dbo.EXPORTSHIPPINGBILLDETAIL ON dbo.EXPORTSHIPPINGBILLMASTER.ESBMID = dbo.EXPORTSHIPPINGBILLDETAIL.ESBMID AND 
--                         dbo.STUFFINGPRODUCTDETAIL.ESBDID = dbo.EXPORTSHIPPINGBILLDETAIL.ESBDID
--where transactiondetail.TRANMID =32052
--GROUP BY dbo.TRANSACTIONDETAIL.TRANMID, dbo.SHIPPINGBILLMASTER.EXPRTNAME, dbo.SHIPPINGBILLDETAIL.PRDTDESC, dbo.SHIPPINGBILLDETAIL.SBDDNO, dbo.SHIPPINGBILLDETAIL.SBDDATE, 
--                         dbo.SHIPPINGBILLMASTER.SBMDNO, dbo.SHIPPINGBILLMASTER.SBMDATE, dbo.SHIPPINGBILLDETAIL.SBDNO, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO, 
--                         dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE, dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO, dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLDATE

--select * from  TRANSACTIONDETAIL where TRANMID =32052
--select * from  STUFFINGDETAIL where STFMID=17530-- STFDID =32052
--select * from  STUFFINGPRODUCTDETAIL where  STFDID =32052
--select * from  SHIPPINGBILLMASTER where SBMID=24679
--select * from  SHIPPINGBILLdetail where SBMID=24679
--select * from  SHIPPINGBILLdetail where ESBMID in (63834,63819)
--select * from EXPORTSHIPPINGBILLDETAIL where ESBD_SBILLNO='5768757'
--select * from VW_EXPORT_STUFF_INVOICE_PRINT_02 where SBMDNO= '09642'
--select * from  STUFFINGDETAIL where STFMID=17530 gidid in(180605, 180987)

--update EXPORTSHIPPINGBILLDETAIL
--set ESBMNOP=1646
--where ESBDID=23464
--and ESBMNOP=1588.00
--update EXPORTSHIPPINGBILLDETAIL 
--set ESBMID =63819
--where ESBD_SBILLNO='5768757'
--and ESBMID= 63834

--select * from STUFFINGPRODUCTDETAIL where STFDNOP=1588
--update STUFFINGPRODUCTDETAIL 
--set STFDNOP=1646
--where STFDNOP=1588
--and STFDID =18869



--update SHIPPINGBILLdetail 
--set ESBMID =63819
--where SBMID=24692
--and ESBMID= 63834


--update SHIPPINGBILLdetail 
--set SBMID =24679
--where SBMID=24692
--and GIDID= 180987



--update SHIPPINGBILLdetail 
--set  SBDNOP	=1646
--where GIDID=180605
--and SBDNOP	=1588.00
--and SBDQTY=	8.0000

--update SHIPPINGBILLdetail 
--set  UNLOADEDNOP	=1646
--where GIDID=180605
--and UNLOADEDNOP	=1588.00
--and SBDQTY=	8.0000


--1588.00
--ESBMID= 63819
--select * from EXPORTSHIPPINGBILLmaster where ESBMID in(63834, 63819)
--= 63819
--select * from STUFFINGPRODUCTDETAIL