ALTER PROC DBO.TMP_CARTING_ORDER_TRUCK_ADDMOD
@PCUSRID VARCHAR(25),
@GIDID INT
AS 
BEGIN
	--DELETE TMP_CARTING_ORDER_TRUCK_DUPCHK
	--WHERE GIDID = @GIDID AND CUSRID = @PCUSRID

	INSERT INTO TMP_CARTING_ORDER_TRUCK_DUPCHK
	SELECT @PCUSRID, VHLNO, GIDID
	FROM GATEINDETAIL (NOLOCK)
	WHERE GIDID = @GIDID
END