USE [SCFS_ERP]
GO

/****** Object:  Table [dbo].[TMP_DO_OPENSHEET_GIDID]    Script Date: 27-08-2021 12:23:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TMP_DO_OPENSHEET_GIDID](
	[BILLEMID] [int] NOT NULL
) ON [PRIMARY]

GO


