
create proc pr_category_gst_state_upd
@cateid int
as
begin
	DECLARE @TBLCATADR TABLE
	(CATEID INT,
	CATEAID INT)

	INSERT INTO @TBLCATADR
	SELECT CATEID, max(CATEAID) 'CATEAID' 
	FROM CATEGORY_ADDRESS_DETAIL (nolock)
	where cateid = @cateid
	GROUP BY CATEID

	UPDATE A
	SET CATEBGSTNO = B.CATEAGSTNO, STATEID = b.STATEID, CATEBPANNO = b.CATEAPANNO
	FROM CATEGORYMASTER A, CATEGORY_ADDRESS_DETAIL B, @TBLCATADR C
	where a.cateid = @cateid
	and  A.CATEID = B.CATEID
	AND A.CATEID = C.CATEID
	AND B.CATEID = C.CATEID
	AND B.CATEAID = C.CATEAID
end