ALTER TABLE VEHICLETICKETDETAIL
ADD TRNSPRTID int DEFAULT (0)

ALTER TABLE VEHICLETICKETDETAIL
ADD TRNSPRTNAME VARCHAR(120) DEFAULT ''


ALTER TABLE VEHICLETICKETDETAIL
ADD GTRNSPRTNAME VARCHAR(120) DEFAULT ''

ALTER TABLE VEHICLETICKETDETAIL
ADD VHLMID int DEFAULT (0)