
select * From BONDTRANSACTIONDETAIL where TRANMID = 14725
select * From BONDTRANSACTIONDETAIL where TRANMID = 14724
select * From BONDVEHICLETICKETDETAIL a(nolock) join BONDTRANSACTIONDETAIL b(nolock) on a.EBNDID = b.EBNDID

update a
set VTDID = b.vtdid
from BONDTRANSACTIONDETAIL a, BONDVEHICLETICKETDETAIL b where a.EBNDID = b.EBNDID
and isnull(a.VTDID,0)=0
