/****** Object:  View [dbo].[VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01]    Script Date: 12-10-2022 11:29:29 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01]'))
DROP VIEW [dbo].[VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01]
GO
/****** Object:  View [dbo].[VW_VT_EXBOND_BALANCE_DETAIL_ASSGN]    Script Date: 12-10-2022 11:29:29 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_VT_EXBOND_BALANCE_DETAIL_ASSGN]'))
DROP VIEW [dbo].[VW_VT_EXBOND_BALANCE_DETAIL_ASSGN]
GO


CREATE VIEW [dbo].[VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01]
AS
SELECT     EBNDID, SUM(VTQTY) AS VTNOP, SUM(VTAREA) AS VTSPC
FROM         dbo.BONDVEHICLETICKETDETAIL(nolock)
GROUP BY EBNDID
GO
/****** Object:  View [dbo].[VW_VT_EXBOND_BALANCE_DETAIL_ASSGN]    Script Date: 12-10-2022 11:29:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[VW_VT_EXBOND_BALANCE_DETAIL_ASSGN]
AS
SELECT     dbo.EXBONDMASTER.EBNDID, dbo.EXBONDMASTER.EBNDCTYPE, dbo.EXBONDMASTER.PRDTGID, dbo.BONDPRODUCTGROUPMASTER.PRDTGDESC, 
					  ISNULL(dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01.VTNOP, 0) 'CUMVTNOP',
					  ISNULL(dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01.VTSPC, 0) 'CUMVTSPC',
                      dbo.EXBONDMASTER.EBNDNOP - ISNULL(dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01.VTNOP, 0) AS BEBNOP, 
                      dbo.EXBONDMASTER.EBNDSPC - ISNULL(dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01.VTSPC, 0) AS BEBSPC
FROM         dbo.EXBONDMASTER (nolock) INNER JOIN
                      dbo.BONDPRODUCTGROUPMASTER (nolock) ON dbo.EXBONDMASTER.PRDTGID = dbo.BONDPRODUCTGROUPMASTER.PRDTGID LEFT OUTER JOIN
                      dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01 (nolock) ON 
                      dbo.EXBONDMASTER.EBNDID = dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01.EBNDID
GO