USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_ADVANCE_DETAIL_CRY_RPT]    Script Date: 19/10/2021 12:24:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_ACCOUNTHEADER_HSNCODE_DETAIL]
AS
SELECT DISTINCT HSNCODEMASTER.AIGSTEXPRN,HSNCODEMASTER.HSNCODE,ACCOUNTHEADMASTER.ACHEADID, ACCOUNTHEADMASTER.HSNID,ACCOUNTHEADMASTER.ACHEADDESC
FROM ACCOUNTHEADMASTER inner Join 
HSNCODEMASTER on ACCOUNTHEADMASTER.HSNID = HSNCODEMASTER.HSNID


GO
