USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_ASL_CONTAINER_CBX_ASSGN_02]    Script Date: 12/08/2021 17:10:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_ASL_CONTAINER_CBX_ASSGN_02]
AS
SELECT   dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, dbo.AUTHORIZATIONSLIPDETAIL.OSDID
FROM     dbo.AUTHORIZATIONSLIPMASTER (nolock) INNER JOIN  
         dbo.AUTHORIZATIONSLIPDETAIL (nolock) ON dbo.AUTHORIZATIONSLIPMASTER.ASLMID = dbo.AUTHORIZATIONSLIPDETAIL.ASLMID
WHERE    (dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE IN (1, 2))


GO


