USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_ASL_EMPTY_CONTAINER_CBX_ASSGN]    Script Date: 29/11/2021 12:37:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_ASL_EMPTY_CONTAINER_CBX_ASSGN]
AS
SELECT     TOP (100) PERCENT dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01.GIDID, dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01.GIDATE, 
                      dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01.CONTNRNO, dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01.CONTNRSID, 
                      dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01.CONTNRSDESC, dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01.STMRID, 
                      dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01.STMRNAME,dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01.CHAID, 
                      dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01.CHANAME
FROM         dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01 LEFT OUTER JOIN
                      dbo.GATEOUTDETAIL ON dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01.GIDID = dbo.GATEOUTDETAIL.GIDID LEFT OUTER JOIN
                      dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_02 ON 
                      dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01.GIDID = dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_02.OSDID
WHERE     (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) AND (ISNULL(dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_02.ASLDID, 0) = 0)
ORDER BY dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01.CONTNRNO


GO


