USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN]    Script Date: 12/08/2021 17:05:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO










ALTER VIEW [dbo].[VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN]
AS
SELECT      VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.GIDID,  VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.GIDATE,
            VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.STMRNAME,VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.IMPRTNAME,
			VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.VOYNO,VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.VSLNAME,
			VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.GIDNO,VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.GINO,
			VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.CONTNRNO, VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.IGMNO, 
			VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.GPLNO, VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.CONTNRSDESC, 
			VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.BOENO, VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.BOEDATE, 
			VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.LPSEALNO, VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.CSEALNO,
			VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.SDPTID,VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_02.ASLDID
FROM        VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01 (nolock) LEFT JOIN  
            VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_02 (nolock) ON VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.GIDID = VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_02.GIDID   

WHERE     (dbo.VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_02.ASLMTYPE = 1 ) AND ( VW_ASL_GIGMNO_CONTAINER_CBX_ASSGN_01.SDPTID = 1 )










GO


