USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_ASL_CONTAINER_CBX_ASSGN_01]    Script Date: 12/08/2021 17:10:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_ASL_CONTAINER_CBX_ASSGN_01]
AS
SELECT  ISNULL(dbo.GATEINDETAIL.GIDID,0) as GIDID,ISNULL(dbo.GATEINDETAIL.GIDATE,'') as GIDATE,
        ISNULL(dbo.GATEINDETAIL.STMRNAME,'') as STMRNAME,ISNULL(dbo.GATEINDETAIL.IMPRTNAME,'') as IMPRTNAME,
		ISNULL(dbo.GATEINDETAIL.VOYNO,'') as VOYNO,ISNULL(dbo.GATEINDETAIL.VSLNAME,'') as VSLNAME,
		ISNULL(dbo.GATEINDETAIL.GIDNO,'') as GIDNO,ISNULL(dbo.GATEINDETAIL.GINO,0) as GINO,
		ISNULL(dbo.GATEINDETAIL.CONTNRNO,'') as CONTNRNO,ISNULL(dbo.GATEINDETAIL.IGMNO,'') as IGMNO,
		ISNULL(dbo.GATEINDETAIL.GPLNO,'') as GPLNO,ISNULL(dbo.CONTAINERSIZEMASTER.CONTNRSDESC,'') as CONTNRSDESC,
		ISNULL(dbo.GATEINDETAIL.BOENO,'') as BOENO,ISNULL(dbo.GATEINDETAIL.BOEDATE,'') as BOEDATE,
		ISNULL(dbo.GATEINDETAIL.LPSEALNO,'') as LPSEALNO,ISNULL(dbo.GATEINDETAIL.CSEALNO,'') as CSEALNO,
		ISNULL(dbo.GATEINDETAIL.SDPTID,0) as SDPTID, ISNULL(dbo.OPENSHEETDETAIL.OSDID,0) as OSDID
FROM       dbo.OPENSHEETDETAIL (nolock) INNER JOIN 
           dbo.GATEINDETAIL (nolock) ON dbo.OPENSHEETDETAIL.GIDID = dbo.GATEINDETAIL.GIDID Left Join
		   dbo.CONTAINERSIZEMASTER (nolock) ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID
WHERE     (dbo.GATEINDETAIL.SDPTID IN (1,9)) AND (dbo.OPENSHEETDETAIL.INSPTYPE = 1)




GO


