CREATE VIEW [dbo].[VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_02]
AS
SELECT     dbo.AUTHORIZATIONSLIPDETAIL.OSDID, dbo.AUTHORIZATIONSLIPDETAIL.ASLDID
FROM         dbo.AUTHORIZATIONSLIPMASTER INNER JOIN
                      dbo.AUTHORIZATIONSLIPDETAIL ON dbo.AUTHORIZATIONSLIPMASTER.ASLMID = dbo.AUTHORIZATIONSLIPDETAIL.ASLMID
WHERE     (dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE = 3)

