ALTER VIEW dbo.VW_ASL_EMPTY_CONTAINER_CBX_ASSGN_01
AS
SELECT     dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.GIDATE, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSID, 
                      dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.STMRID, dbo.GATEINDETAIL.STMRNAME,dbo.GATEINDETAIL.CHAID,
					  isnull(dbo.GATEINDETAIL.CHANAME,'' ) as CHANAME
FROM         dbo.GATEINDETAIL INNER JOIN
             dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID Inner Join 
			 dbo.VEHICLETICKETDETAIL (NOLOCK) ON dbo.GATEINDETAIL.GIDID = dbo.VEHICLETICKETDETAIL.EGIDID

WHERE     (dbo.GATEINDETAIL.SDPTID = 3) AND (dbo.GATEINDETAIL.DISPSTATUS = 0)  







