CREATE VIEW dbo.VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN
AS
SELECT        dbo.BILLENTRYDETAIL.BILLEMID, MAX(dbo.BILLENTRYDETAIL.GIDATE) AS XGIDATE
FROM            dbo.BILLENTRYDETAIL LEFT OUTER JOIN
                         dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01 ON 
                         dbo.BILLENTRYDETAIL.BILLEDID = dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.BILLEDID
WHERE        (ISNULL(dbo.VW_IMPORT_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDID, 0) = 0)
GROUP BY dbo.BILLENTRYDETAIL.BILLEMID

