CREATE VIEW [dbo].[VW_BOND_SLABTYPE_HSN_DETAIL_ASSGN]
AS
SELECT        dbo.BONDSLABTYPEMASTER.SLABTID, dbo.HSNCODEMASTER.HSNCODE, dbo.HSNCODEMASTER.CGSTEXPRN, dbo.HSNCODEMASTER.SGSTEXPRN, 
                         dbo.HSNCODEMASTER.IGSTEXPRN, dbo.HSNCODEMASTER.ACGSTEXPRN, dbo.HSNCODEMASTER.ASGSTEXPRN, dbo.HSNCODEMASTER.AIGSTEXPRN
FROM            dbo.BONDSLABTYPEMASTER INNER JOIN
                         dbo.HSNCODEMASTER ON dbo.BONDSLABTYPEMASTER.HSNID = dbo.HSNCODEMASTER.HSNID
GROUP BY dbo.BONDSLABTYPEMASTER.SLABTID, dbo.HSNCODEMASTER.CGSTEXPRN, dbo.HSNCODEMASTER.SGSTEXPRN, dbo.HSNCODEMASTER.IGSTEXPRN, 
                         dbo.HSNCODEMASTER.ACGSTEXPRN, dbo.HSNCODEMASTER.ASGSTEXPRN, dbo.HSNCODEMASTER.AIGSTEXPRN, dbo.HSNCODEMASTER.HSNCODE