ALTER VIEW dbo.VW_BOND_INVOICE_TRANSACTION_GST_PRINT_ASSGN
AS
SELECT        dbo.NEW_TMPRPT_IDS.KUSRID, dbo.NEW_TMPRPT_IDS.OPTNSTR, dbo.NEW_TMPRPT_IDS.RPTID, dbo.BONDTRANSACTIONMASTER.TRANMID, dbo.BONDTRANSACTIONMASTER.COMPYID, 
                         dbo.BONDTRANSACTIONMASTER.SDPTID, dbo.BONDTRANSACTIONMASTER.REGSTRID, dbo.BONDTRANSACTIONMASTER.TRANBTYPE, dbo.BONDTRANSACTIONMASTER.TRANDATE, dbo.BONDTRANSACTIONMASTER.TRANTIME, 
                         dbo.BONDTRANSACTIONMASTER.TRANNO, dbo.BONDTRANSACTIONMASTER.TRANDNO, BONDTRANSACTIONMASTER.CUSRID AS USRNAME, dbo.BONDTRANSACTIONMASTER.TRANCHANAME, 
                         dbo.BONDTRANSACTIONMASTER.TRANIMPRTNAME, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR1 + ' '+ dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR2+
						  ' '+ dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR3+ ' '+ dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR4 AS CHAADDR, dbo.CATEGORYMASTER.CATENAME as ACHANAME, 
						 dbo.BONDMASTER.BNDID, dbo.BONDTRANSACTIONDETAIL.TRANDBNDNO, 
                         dbo.BONDTRANSACTIONDETAIL.TRANDEBNDNO, dbo.BONDTRANSACTIONMASTER.TRANMODE, dbo.BONDTRANSACTIONMASTER.TRANMODEDETL, dbo.BONDTRANSACTIONMASTER.TRANREFNO, 
                         dbo.BONDTRANSACTIONMASTER.TRANREFDATE, dbo.BONDTRANSACTIONMASTER.TRANREFBNAME, dbo.BONDTRANSACTIONMASTER.TRANREFAMT, 
                         dbo.BONDTRANSACTIONMASTER.TRANGAMT + dbo.BONDTRANSACTIONMASTER.TRAN_CGST_AMT + dbo.BONDTRANSACTIONMASTER.TRAN_SGST_AMT + dbo.BONDTRANSACTIONMASTER.TRAN_IGST_AMT + dbo.BONDTRANSACTIONMASTER.TRANROAMT
                          AS TRANNAMT, dbo.BONDTRANSACTIONMASTER.TRANRMKS, dbo.BONDTRANSACTIONMASTER.TRANAMTWRDS, dbo.BONDTRANSACTIONMASTER.TRANGAMT, dbo.BONDGODOWNMASTER.GWNDESC, 
                         dbo.BONDGODOWNMASTER.GWNADDR, dbo.BONDMASTER.BNDDNO, dbo.BONDMASTER.BNDDATE, dbo.BONDMASTER.BNDADATE, --dbo.BONDMASTER.BNDDNO, dbo.BONDMASTER.BNDDATE, dbo.BONDMASTER.BNDNOP, 
						 dbo.BONDMASTER.BNDNOP, dbo.BONDTRANSACTIONDETAIL.SLABTID, dbo.BONDSLABTYPEMASTER.SLABTDESC, dbo.BONDSLABTYPEMASTER.DISPORDER, 
                         dbo.BONDTRANSACTIONDETAIL.TRANCTYPE, dbo.BONDTRANSACTIONDETAIL.TRANOTYPE, dbo.BONDTRANSACTIONDETAIL.TRANCDATE, dbo.BONDTRANSACTIONDETAIL.TRANHTYPE, dbo.BONDTRANSACTIONDETAIL.TRANSFDATE, 
                         dbo.BONDTRANSACTIONDETAIL.TRANSEDATE, dbo.BONDTRANSACTIONDETAIL.TRANIFDATE, dbo.BONDTRANSACTIONDETAIL.TRANIEDATE, dbo.BONDMASTER.BNDSPC, dbo.BONDTRANSACTIONDETAIL.TRANDQTY, 
                         dbo.BONDTRANSACTIONDETAIL.TRANDNOP, dbo.BONDTRANSACTIONDETAIL.TRANDCIFAMT, dbo.BONDTRANSACTIONDETAIL.TRANDDTYAMT, dbo.BONDTRANSACTIONDETAIL.TRANDINSAMT, dbo.BONDTRANSACTIONDETAIL.TRANDEIAMT, 
                         dbo.BONDTRANSACTIONDETAIL.TRANDRATE, dbo.BONDTRANSACTIONDETAIL.TRANDGAMT, dbo.BONDTRANSACTIONDETAIL.TRANDNAMT, --dbo.BONDMASTER.EBNDASSAMT, dbo.BONDMASTER.EBNDDTYAMT, 
                         dbo.BONDMASTER.BNDINSAMT, dbo.BONDMASTER.BNDCIFAMT, dbo.BONDMASTER.BNDDTYAMT,  --dbo.BONDMASTER.EBNDBENO, dbo.BONDMASTER.BNDINSAMT,
                         dbo.BONDMASTER.BNDBEDATE, dbo.CATEGORYMASTER.CATENAME AS TRANREFNAME, dbo.BONDMASTER.BNDTDATE, dbo.BONDTRANSACTIONDETAIL.RCOLDESC1, 
                         dbo.BONDTRANSACTIONDETAIL.RCOLDESC2, dbo.BONDTRANSACTIONDETAIL.RCOLDESC3, dbo.BONDTRANSACTIONDETAIL.RCOLDESC4, dbo.BONDMASTER.BND20, dbo.BONDMASTER.BND40, dbo.BONDMASTER.BNDBLNO, 
                         dbo.BONDMASTER.BNDBENO, dbo.STATEMASTER.STATEDESC, dbo.STATEMASTER.STATECODE, ISNULL(dbo.BONDTRANSACTIONMASTER.TRANGSTNO, dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO) AS CATEGSTNO, 
                         dbo.BONDTRANSACTIONMASTER.TRANLMNO, dbo.BONDTRANSACTIONMASTER.IRNNO, dbo.BONDTRANSACTIONMASTER.ACKNO, dbo.BONDTRANSACTIONMASTER.ACKDT, dbo.BONDTRANSACTIONMASTER.QRCODEPATH, 
                         dbo.BONDTRANSACTIONMASTER.TRAN_CGST_AMT, dbo.BONDTRANSACTIONMASTER.TRAN_SGST_AMT, dbo.BONDTRANSACTIONMASTER.TRAN_IGST_AMT,
						 DBO.CATEGORYMASTER.CATELICNO, BONDTRANSACTIONMASTER.TRANBILLREFNO
FROM            dbo.NEW_TMPRPT_IDS INNER JOIN
                         dbo.BONDTRANSACTIONMASTER ON dbo.NEW_TMPRPT_IDS.RPTID = dbo.BONDTRANSACTIONMASTER.TRANMID INNER JOIN
                         dbo.BONDTRANSACTIONDETAIL ON dbo.BONDTRANSACTIONMASTER.TRANMID = dbo.BONDTRANSACTIONDETAIL.TRANMID INNER JOIN
                         dbo.BONDMASTER ON dbo.BONDTRANSACTIONDETAIL.BNDID = dbo.BONDMASTER.BNDID INNER JOIN    
						 dbo.CATEGORYMASTER ON dbo.BONDTRANSACTIONMASTER.BILLREFID = dbo.CATEGORYMASTER.CATEID INNER JOIN
						 dbo.CATEGORY_ADDRESS_DETAIL ON dbo.CATEGORYMASTER.CATEID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID 
						 AND BONDTRANSACTIONMASTER.BCATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.BONDTRANSACTIONMASTER.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                         dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID LEFT OUTER JOIN
                         dbo.STATEMASTER ON dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID LEFT JOIN                         
                         dbo.BONDSLABTYPEMASTER ON dbo.BONDTRANSACTIONDETAIL.SLABTID = dbo.BONDSLABTYPEMASTER.SLABTID LEFT JOIN
                         dbo.BONDGODOWNMASTER ON dbo.BONDMASTER.GWNID = dbo.BONDGODOWNMASTER.GWNID                      
                         