alter VIEW [dbo].[VW_BOND_RATECARDMASTER_FLX_ASSGN]
AS
SELECT     dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.TARIFFMID, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.SLABTID, 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.CHRGETYPE, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.CHAID, 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.CONTNRSID, dbo.BONDSLABMASTER.SLABMID, dbo.BONDSLABMASTER.COMPYID, 
                      dbo.CATEGORYMASTER.CATEDNAME, dbo.CONTAINERSIZEMASTER.CONTNRSCODE, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.YRDTYPE, 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.SDTYPE, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.HTYPE, 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.WTYPE, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.PERIODTID, 
					  dbo.BONDSLABMASTER.SLABMIN, dbo.BONDSLABMASTER.SLABMAX, dbo.BONDSLABMASTER.SLABAMT, 
                      dbo.BONDSLABMASTER.SLABMDATE, 10 SDPTTYPEID, VW_BOND_RATECARDMASTER_FLX_ASSGN_02.PRDTGID,
					  dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.HANDTYPE
FROM         dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02 INNER JOIN
                      dbo.BONDSLABMASTER ON dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.TARIFFMID = dbo.BONDSLABMASTER.TARIFFMID AND 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.CHAID = dbo.BONDSLABMASTER.CHAID AND 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.CHRGETYPE = dbo.BONDSLABMASTER.CHRGETYPE AND 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.CONTNRSID = dbo.BONDSLABMASTER.CONTNRSID AND 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.SDTYPE = dbo.BONDSLABMASTER.SDTYPE AND 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.YRDTYPE = dbo.BONDSLABMASTER.YRDTYPE AND 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.HTYPE = dbo.BONDSLABMASTER.HTYPE AND 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.WTYPE = dbo.BONDSLABMASTER.WTYPE AND 
					  dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.HANDTYPE = dbo.BONDSLABMASTER.HANDTYPE AND 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.SLABTID = dbo.BONDSLABMASTER.SLABTID AND 
					  dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.PRDTGID = dbo.BONDSLABMASTER.PRDTGID AND 
					  dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.XTRANSDATE = dbo.BONDSLABMASTER.SLABMDATE AND 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.PERIODTID = dbo.BONDSLABMASTER.PERIODTID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID LEFT OUTER JOIN
                      dbo.CATEGORYMASTER ON dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_02.CHAID = dbo.CATEGORYMASTER.CATEID
