CREATE VIEW dbo.VW_BOND_TRANSACTION_DOSPRINT_ASSGN_03
AS
SELECT     dbo.BONDTRANSACTIONMASTERFACTOR.TRANMID, dbo.BONDTRANSACTIONMASTERFACTOR.CFID, dbo.COSTFACTORMASTER.CFDESC, 
                      dbo.BONDTRANSACTIONMASTERFACTOR.DEDVALUE, dbo.BONDTRANSACTIONMASTERFACTOR.DEDEXPRN, dbo.BONDTRANSACTIONMASTERFACTOR.DORDRID, 
                      dbo.BONDTRANSACTIONMASTERFACTOR.DEDTYPE, dbo.BONDTRANSACTIONMASTER.DISPSTATUS
FROM         dbo.BONDTRANSACTIONMASTERFACTOR INNER JOIN
                      dbo.COSTFACTORMASTER ON dbo.BONDTRANSACTIONMASTERFACTOR.CFID = dbo.COSTFACTORMASTER.CFID INNER JOIN
                      dbo.BONDTRANSACTIONMASTER ON dbo.BONDTRANSACTIONMASTERFACTOR.TRANMID = dbo.BONDTRANSACTIONMASTER.TRANMID
WHERE     (dbo.BONDTRANSACTIONMASTER.DISPSTATUS = 0)
