alter VIEW [dbo].[VW_BOND_RATECARDMASTER_FLX_ASSGN_02]
AS
SELECT     MAX(dbo.BondSlabMaster.SLABMID) AS Expr1, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.SLABTID, 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.TARIFFMID, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.CHAID, 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.CHRGETYPE, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.CONTNRSID, 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.SDTYPE, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.YRDTYPE, 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.HTYPE, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.WTYPE, 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.PERIODTID, 
					  dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.PRDTGID, 
					  dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.XTRANSDATE,
					  dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.HANDTYPE
FROM         dbo.BondSlabMaster (nolock) INNER JOIN
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01 (nolock) ON dbo.BondSlabMaster.TARIFFMID = dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.TARIFFMID AND 
                      dbo.BondSlabMaster.SLABTID = dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.SLABTID AND 
                      dbo.BondSlabMaster.SLABMDATE = dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.XTRANSDATE AND					  
					   dbo.BondSlabMaster.CONTNRSID = dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.CONTNRSID AND 
					   dbo.BondSlabMaster.SDTYPE = dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.SDTYPE AND 
					   dbo.BondSlabMaster.PERIODTID = dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.PERIODTID AND
					   dbo.BondSlabMaster.PRDTGID = dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.PRDTGID AND
					   dbo.BondSlabMaster.HANDTYPE = dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.HANDTYPE
GROUP BY dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.SLABTID, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.TARIFFMID, 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.CHAID, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.CHRGETYPE, 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.CONTNRSID, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.SDTYPE, 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.YRDTYPE, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.HTYPE, 
                      dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.WTYPE, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.PERIODTID,
					  dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.XTRANSDATE, dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.PRDTGID,
					  dbo.VW_BOND_RATECARDMASTER_FLX_ASSGN_01.HANDTYPE