alter VIEW [dbo].[VW_BOND_INVOICE_SBILL_NO_CBX_ASSGN_01]
AS
	SELECT	dbo.BONDTRANSACTIONDETAIL.TRANDID, dbo.BONDTRANSACTIONDETAIL.SLABTID, dbo.BONDTRANSACTIONDETAIL.BNDID
	FROM	dbo.BONDTRANSACTIONDETAIL (nolock) INNER JOIN
				dbo.BONDTRANSACTIONMASTER  (nolock) ON dbo.BONDTRANSACTIONDETAIL.TRANMID = dbo.BONDTRANSACTIONMASTER.TRANMID left join
				dbo.BONDSLABTYPEMASTER (NOLOCK) ON dbo.BONDTRANSACTIONDETAIL.SLABTID = dbo.BONDSLABTYPEMASTER.SLABTID
	WHERE     (dbo.BONDTRANSACTIONMASTER.SDPTID = 10) AND (dbo.BONDTRANSACTIONMASTER.DISPSTATUS = 0)
	AND		dbo.BONDSLABTYPEMASTER.SLABTID IS NULL
	and TRANTID = 2