CREATE VIEW dbo.VW_BOND_PROFORMA_TRANSACTION_DOSPRINT_ASSGN_03
AS
SELECT     dbo.BONDPERFORMATRANSACTIONMASTERFACTOR.TRANMID, dbo.BONDPERFORMATRANSACTIONMASTERFACTOR.CFID, dbo.COSTFACTORMASTER.CFDESC, 
                      dbo.BONDPERFORMATRANSACTIONMASTERFACTOR.DEDVALUE, dbo.BONDPERFORMATRANSACTIONMASTERFACTOR.DEDEXPRN, dbo.BONDPERFORMATRANSACTIONMASTERFACTOR.DORDRID, 
                      dbo.BONDPERFORMATRANSACTIONMASTERFACTOR.DEDTYPE, dbo.BONDPERFORMATRANSACTIONMASTER.DISPSTATUS
FROM         dbo.BONDPERFORMATRANSACTIONMASTERFACTOR INNER JOIN
                      dbo.COSTFACTORMASTER ON dbo.BONDPERFORMATRANSACTIONMASTERFACTOR.CFID = dbo.COSTFACTORMASTER.CFID INNER JOIN
                      dbo.BONDPERFORMATRANSACTIONMASTER ON dbo.BONDPERFORMATRANSACTIONMASTERFACTOR.TRANMID = dbo.BONDPERFORMATRANSACTIONMASTER.TRANMID
WHERE     (dbo.BONDPERFORMATRANSACTIONMASTER.DISPSTATUS = 0)
