alter VIEW [dbo].[VW_BOND_VT_INVOICE_SBILL_NO_CBX_ASSGN_01]
AS
	SELECT	dbo.BONDTRANSACTIONDETAIL.TRANDID, dbo.BONDTRANSACTIONDETAIL.SLABTID, dbo.BONDTRANSACTIONDETAIL.BNDID,
			dbo.BONDTRANSACTIONDETAIL.EBNDID, dbo.BONDTRANSACTIONDETAIL.VTDID, BONDTRANSACTIONDETAIL.TRANHTYPE
	FROM	dbo.BONDTRANSACTIONDETAIL (nolock) INNER JOIN
				dbo.BONDTRANSACTIONMASTER  (nolock) ON dbo.BONDTRANSACTIONDETAIL.TRANMID = dbo.BONDTRANSACTIONMASTER.TRANMID left join
				dbo.BONDSLABTYPEMASTER (NOLOCK) ON dbo.BONDTRANSACTIONDETAIL.SLABTID = dbo.BONDSLABTYPEMASTER.SLABTID left join 
				Ex_Bond_VT_Handling_Type_Master (nolock)on BONDTRANSACTIONDETAIL.TRANHTYPE = Ex_Bond_VT_Handling_Type_Master.HandTypeID
				
	WHERE     (dbo.BONDTRANSACTIONMASTER.SDPTID = 10) AND (dbo.BONDTRANSACTIONMASTER.DISPSTATUS = 0)
	AND		(dbo.BONDSLABTYPEMASTER.SLABTID IS NULL or isnull(Ex_Bond_VT_Handling_Type_Master.HandTypeID,-1)=-1)
	and TRANTID=3