CREATE VIEW [dbo].[VW_BOND_VT_PROFORMA_INVOICE_SBILL_NO_CBX_ASSGN_01]
AS
	SELECT	dbo.BONDPERFORMATRANSACTIONDETAIL.TRANDID, dbo.BONDPERFORMATRANSACTIONDETAIL.SLABTID, dbo.BONDPERFORMATRANSACTIONDETAIL.BNDID,
			dbo.BONDPERFORMATRANSACTIONDETAIL.EBNDID, dbo.BONDPERFORMATRANSACTIONDETAIL.VTDID, BONDPERFORMATRANSACTIONDETAIL.TRANHTYPE
	FROM	dbo.BONDPERFORMATRANSACTIONDETAIL (nolock) INNER JOIN
				dbo.BONDPERFORMATRANSACTIONMASTER  (nolock) ON dbo.BONDPERFORMATRANSACTIONDETAIL.TRANMID = dbo.BONDPERFORMATRANSACTIONMASTER.TRANMID left join
				dbo.BONDSLABTYPEMASTER (NOLOCK) ON dbo.BONDPERFORMATRANSACTIONDETAIL.SLABTID = dbo.BONDSLABTYPEMASTER.SLABTID left join 
				Ex_Bond_VT_Handling_Type_Master (nolock)on BONDPERFORMATRANSACTIONDETAIL.TRANHTYPE = Ex_Bond_VT_Handling_Type_Master.HandTypeID
				
	WHERE     (dbo.BONDPERFORMATRANSACTIONMASTER.SDPTID = 10) AND (dbo.BONDPERFORMATRANSACTIONMASTER.DISPSTATUS = 0)
	AND		(dbo.BONDSLABTYPEMASTER.SLABTID IS NULL or isnull(Ex_Bond_VT_Handling_Type_Master.HandTypeID,-1)=-1)
	and TRANTID=3
