ALTER VIEW [dbo].[VW_CARGO_OUT_CONTAINER_CBX_ASSGN]
AS
SELECT     dbo.GATEINDETAIL.GIDID, dbo.OPENSHEETMASTER.BOENO + ' - ' + dbo.GATEINDETAIL.CONTNRNO AS CONTNRNO
FROM       dbo.GATEINDETAIL  INNER  JOIN 
           VEHICLETICKETDETAIL (NOLOCK ) ON GATEINDETAIL.GIDID = VEHICLETICKETDETAIL.CGIDID INNER JOIN 
		   OPENSHEETDETAIL   (NOLOCK ) ON VEHICLETICKETDETAIL.GIDID = OPENSHEETDETAIL.GIDID INNER JOIN 
		   OPENSHEETMASTER (NOLOCK ) ON OPENSHEETDETAIL.OSMID = OPENSHEETMASTER.OSMID   INNER JOIN 
		   GATEINDETAIL VG (NOLOCK) ON VEHICLETICKETDETAIL.GIDID = VG.GIDID    LEFT OUTER JOIN 
             dbo.GATEOUTDETAIL (NOLOCK) ON  dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID and dbo.GATEINDETAIL.SDPTID = dbo.GATEOUTDETAIL.SDPTID
WHERE     (dbo.GATEINDETAIL.SDPTID = 4) AND (dbo.GATEINDETAIL.GPWGHT - ISNULL(dbo.GATEOUTDETAIL.GOQTY, 0) > 0)

