alter VIEW [dbo].[VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01]
AS
SELECT        CREDITNOTE_TRANSACTIONMASTER.TRANMID, 
				STRG_HSNCODE = CASE WHEN CNTDESC not LIKE '%HANDLING%' THEN '' ELSE isnull(TRANDHSNCODE,'')  END , 
				HANDL_HSNCODE = CASE WHEN CNTDESC  LIKE '%HANDLING%' THEN isnull(TRANDHSNCODE,'')  ELSE ''  END , 
				ISNULL(CREDITNOTE_TRANSACTIONDETAIL.TRAND_STRG_CGST_EXPRN,0) AS STRG_CGST_EXPRN,ISNULL(CREDITNOTE_TRANSACTIONDETAIL.TRAND_STRG_SGST_EXPRN,0) AS STRG_SGST_EXPRN, 
				ISNULL(CREDITNOTE_TRANSACTIONDETAIL.TRAND_STRG_IGST_EXPRN,0) AS STRG_IGST_EXPRN, 
				ISNULL(CREDITNOTE_TRANSACTIONDETAIL.TRAND_HANDL_CGST_EXPRN,0) AS HANDL_CGST_EXPRN,ISNULL(CREDITNOTE_TRANSACTIONDETAIL.TRAND_HANDL_SGST_EXPRN,0) AS HANDL_SGST_EXPRN, 
				ISNULL(CREDITNOTE_TRANSACTIONDETAIL.TRAND_HANDL_IGST_EXPRN,0) AS HANDL_IGST_EXPRN, 
				STRG_TAXABLE_AMT = CASE WHEN CNTDESC not LIKE '%HANDLING%' THEN 0 ELSE SUM(TRANDGAMT)  END,
				HANDL_TAXABLE_AMT = CASE WHEN CNTDESC LIKE '%HANDLING%' THEN 0 ELSE SUM(TRANDGAMT)  END,
				SUM(TRAND_STRG_CGST_AMT) AS STRG_CGST_AMT, SUM(TRAND_STRG_SGST_AMT) AS STRG_SGST_AMT, SUM(TRAND_STRG_IGST_AMT) AS STRG_IGST_AMT, SUM(TRAND_HANDL_CGST_AMT) AS HANDL_CGST_AMT, 
                         SUM(TRAND_HANDL_SGST_AMT) AS HANDL_SGST_AMT, SUM(TRAND_HANDL_IGST_AMT) AS HANDL_IGST_AMT, SUM(TRAND_STRG_CGST_AMT + TRAND_HANDL_CGST_AMT) AS CGST_AMT, 
                         SUM(TRAND_STRG_SGST_AMT + TRAND_HANDL_SGST_AMT) AS SGST_AMT, SUM(TRAND_STRG_IGST_AMT + TRAND_HANDL_IGST_AMT) AS IGST_AMT,
				CNTDESC
FROM            dbo.CREDITNOTE_TRANSACTIONMASTER join CREDITNOTE_TRANSACTIONDETAIL join CREDITNOTE_TYPEMASTER on CREDITNOTE_TRANSACTIONDETAIL.TRANDREFID = CREDITNOTE_TYPEMASTER.CNTID
				on  CREDITNOTE_TRANSACTIONMASTER.tranmid = CREDITNOTE_TRANSACTIONDETAIL.tranmid 
GROUP BY CREDITNOTE_TRANSACTIONMASTER.TRANMID, CNTDESC, TRANDHSNCODE, TRAND_STRG_CGST_EXPRN, TRAND_STRG_SGST_EXPRN, TRAND_STRG_IGST_EXPRN, TRAND_HANDL_CGST_EXPRN, TRAND_HANDL_SGST_EXPRN, 
                         TRAND_HANDL_IGST_EXPRN, CNTDESC
--HAVING        (STRG_HSNCODE IS NOT NULL or HANDL_HSNCODE IS NOT NULL)



--select * from CREDITNOTE_TRANSACTIONMASTER
--select * from CREDITNOTE_TRANSACTIONDETAIL