USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_CARGO_OUT_CONTAINER_CBX_ASSGN]    Script Date: 06/11/2021 12:24:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_CARGOIN_CONTAINER_GATEINDETAILS_ASSGN]
AS
SELECT   Isnull(CONTAINERSIZEMASTER.CONTNRSDESC,'') as CONTNRSDESC, dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO AS CONTNRNO,
           VEHICLETICKETDETAIL.CGIDID, GATEINDETAIL.GIDNO, GATEINDETAIL.GIDATE, VEHICLETICKETDETAIL.VTDATE, GATEINDETAIL.IMPRTNAME, 
		   GATEINDETAIL.STMRNAME,GATEINDETAIL.GPLNO,VEHICLETICKETDETAIL.VHLNO ,isnull(PRODUCTGROUPMASTER.PRDTGDESC,'') as PRDTGDESC,
		   isnull(GATEINDETAIL.PRDTDESC,'') as PRDTDESC,
		   GATEINDETAIL.GPWGHT ,(GATEINDETAIL.GPWGHT - ISNUll(GATEOUTDETAIL.GOQTY,0)) AS BGOQTY
           


FROM       dbo.GATEINDETAIL  (NOLOCK)  INNER JOIN 
           dbo.VEHICLETICKETDETAIL  (NOLOCK) ON GATEINDETAIL.GIDID = VEHICLETICKETDETAIL.CGIDID INNER JOIN 
		   dbo.CONTAINERSIZEMASTER (NOLOCK) ON GATEINDETAIL.CONTNRSID = CONTAINERSIZEMASTER.CONTNRSID Inner Join 
		   dbo.PRODUCTGROUPMASTER  (NOLOCK) ON GATEINDETAIL.PRDTGID = PRODUCTGROUPMASTER.PRDTGID  LEFT OUTER JOIN 
		   dbo.GATEOUTDETAIL (NOLOCk) ON   GATEINDETAIL.GIDID = GATEOUTDETAIL.GIDID 
WHERE     (dbo.GATEINDETAIL.SDPTID = 4) 




GO


