CREATE VIEW dbo.VW_DELIVERY_ORDER_DETAIL_GRID_ASSGN
AS
SELECT     dbo.DELIVERYORDERMASTER.DOMID, dbo.DELIVERYORDERDETAIL.DODID, dbo.DELIVERYORDERDETAIL.DODREFNO, dbo.GATEINDETAIL.IGMNO, 
                      dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.DELIVERYORDERDETAIL.DOIDATE, 
                      dbo.GATEINDETAIL.GIDATE, dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.GPWGHT, 
                      dbo.GATEINDETAIL.GIDID, dbo.DELIVERYORDERDETAIL.BILLEDID, dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.IMPRTNAME, 
                      dbo.BILLENTRYMASTER.DPAIDNO, dbo.BILLENTRYMASTER.DPAIDAMT, dbo.BILLENTRYDETAIL.BILLEMID
FROM         dbo.DELIVERYORDERMASTER INNER JOIN
                      dbo.DELIVERYORDERDETAIL ON dbo.DELIVERYORDERMASTER.DOMID = dbo.DELIVERYORDERDETAIL.DOMID INNER JOIN
                      dbo.BILLENTRYDETAIL ON dbo.DELIVERYORDERDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID INNER JOIN
                      dbo.GATEINDETAIL ON dbo.BILLENTRYDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                      dbo.BILLENTRYMASTER ON dbo.BILLENTRYDETAIL.BILLEMID = dbo.BILLENTRYMASTER.BILLEMID

