USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_EXPORT_ASL_STUFF_CONTAINER_CBX_ASSGN_02]    Script Date: 06/08/2021 20:00:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [dbo].[VW_EXPORT_ASL_STUFF_CONTAINER_CBX_ASSGN_02]
AS
SELECT     dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, dbo.AUTHORIZATIONSLIPDETAIL.STFDID
FROM         dbo.AUTHORIZATIONSLIPMASTER (nolock)  INNER JOIN
                      dbo.AUTHORIZATIONSLIPDETAIL (nolock)  ON dbo.AUTHORIZATIONSLIPMASTER.ASLMID = dbo.AUTHORIZATIONSLIPDETAIL.ASLMID
WHERE     (dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE IN (1, 2)) AND (dbo.AUTHORIZATIONSLIPMASTER.SDPTID = 2)






GO


