USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_EXPORT_INVOICE_SBILL_NO_CBX_ASSGN_01]    Script Date: 04-08-2021 14:42:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_EXPORT_INVOICE_SBILL_NO_CBX_ASSGN_01]
AS
SELECT     dbo.TRANSACTIONDETAIL.TRANDID, dbo.TRANSACTIONDETAIL.STFDID
FROM         dbo.TRANSACTIONDETAIL INNER JOIN
                      dbo.TRANSACTIONMASTER ON dbo.TRANSACTIONDETAIL.TRANMID = dbo.TRANSACTIONMASTER.TRANMID
WHERE     (dbo.TRANSACTIONMASTER.SDPTID = 2) AND (dbo.TRANSACTIONMASTER.DISPSTATUS = 0)





GO


