ALTER VIEW [dbo].[VW_EXPORT_GATEOUT_MOD_ASSGN]
AS
SELECT     dbo.GATEOUTDETAIL.GODID, dbo.GATEOUTDETAIL.COMPYID, dbo.GATEOUTDETAIL.SDPTID, dbo.GATEOUTDETAIL.REGSTRID, dbo.GATEOUTDETAIL.GODATE, 
                      dbo.GATEOUTDETAIL.GOTIME, dbo.GATEOUTDETAIL.GONO, dbo.GATEOUTDETAIL.GODNO, dbo.GATEOUTDETAIL.GIDID, dbo.GATEOUTDETAIL.TRANDID, 
                      dbo.GATEOUTDETAIL.VHLNO, dbo.GATEOUTDETAIL.GDRVNAME AS DRVNAME, dbo.GATEOUTDETAIL.CHASNAME, dbo.GATEOUTDETAIL.GOBTYPE, 
                      dbo.GATEOUTDETAIL.CHAID, dbo.GATEOUTDETAIL.LSEALNO, dbo.GATEOUTDETAIL.SSEALNO, dbo.GATEOUTDETAIL.CUSRID, dbo.GATEOUTDETAIL.LMUSRID, 
                      dbo.GATEOUTDETAIL.DISPSTATUS, dbo.GATEOUTDETAIL.PRCSDATE, dbo.GATEOUTDETAIL.GOQTY, dbo.GATEOUTDETAIL.OTDID, dbo.GATEOUTDETAIL.OTDNO, 
                      dbo.GATEOUTDETAIL.CONTNRFID, dbo.GATEOUTDETAIL.BOOKID, dbo.GATEOUTDETAIL.GOPLCNAME, dbo.GATEOUTDETAIL.GOBKGNO, 
                      dbo.GATEOUTDETAIL.GOEGMNO, dbo.GATEOUTDETAIL.OVSLID, dbo.GATEOUTDETAIL.OVSLNAME, dbo.GATEOUTDETAIL.OVOYNO, dbo.GATEOUTDETAIL.GOREMRKS, 
                      dbo.GATEOUTDETAIL.EHIDATE, dbo.GATEOUTDETAIL.EHITIME, dbo.GATEOUTDETAIL.GOTRNSPRTNAME, dbo.GATEOUTDETAIL.GOTTYPE, 
                      dbo.GATEOUTDETAIL.GOOTYPE, dbo.GATEOUTDETAIL.GOCTYPE, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                      dbo.CONTAINERTYPEMASTER.CONTNRTCODE,Convert(varchar(10), dbo.GATEINDETAIL.GIDATE,103) as GIDATE, dbo.STUFFINGMASTER.STFMNAME AS CHANAME, 
                      dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, dbo.AUTHORIZATIONSLIPDETAIL.CSEALNO, dbo.AUTHORIZATIONSLIPDETAIL.ASEALNO, 
                      dbo.GATEINDETAIL.GPSTYPE,dbo.VEHICLETICKETDETAIL.VTNO
FROM         dbo.GATEOUTDETAIL INNER JOIN
                      dbo.GATEINDETAIL ON dbo.GATEOUTDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                      dbo.STUFFINGDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.STUFFINGDETAIL.GIDID INNER JOIN
                      dbo.AUTHORIZATIONSLIPDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.AUTHORIZATIONSLIPDETAIL.STFDID INNER JOIN
                      dbo.VEHICLETICKETDETAIL ON dbo.AUTHORIZATIONSLIPDETAIL.ASLDID = dbo.VEHICLETICKETDETAIL.ASLDID INNER JOIN
                      dbo.STUFFINGMASTER ON dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                      dbo.CONTAINERTYPEMASTER ON dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID