USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_AGE_WISE_RPT_01]    Script Date: 12/10/2021 11:23:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_ESEAL_LAST_GATEINRECORDS] AS
SELECT GATEINDETAIL.CONTNRNO , max(GATEINDETAIL.GIDID) as GIDID
 FROM GATEINDETAIL (Nolock)
 WHERE GATEINDETAIL.SDPTID= 11  AND GATEINDETAIL.CONTNRSID > 0 
 GROUP BY GATEINDETAIL.CONTNRNO ,GATEINDETAIL.GIDID
      




GO


