-- SELECT * FROM [VW_EXPORT_CONTAINER_DETAIL_QUERY_ASSGN] WHERE GIDID = 57428
alter VIEW [dbo].[VW_EXPORT_CONTAINER_DETAIL_QUERY_ASSGN]
AS
SELECT     dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.GITIME, dbo.GATEINDETAIL.GIDATE, dbo.GATEINDETAIL.GIDNO, dbo.GATEINDETAIL.VHLNO, 
                      dbo.GATEINDETAIL.DRVNAME, dbo.GATEINDETAIL.CHANAME, dbo.GATEINDETAIL.CHAID, dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.CONTNRNO, 
                      dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.CONTAINERTYPEMASTER.CONTNRTDESC, dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, 
                      dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, isnull(dbo.GATEINDETAIL.GPETYPE,'') GPETYPE, dbo.GATEINDETAIL.GPWTYPE, 
                      dbo.GATEINDETAIL.GPSTYPE, dbo.GATEINDETAIL.GIREMKRS, dbo.GATEINDETAIL.GPWGHT, dbo.GATEINDETAIL.GIDMGDESC, dbo.GATEOUTDETAIL.GODATE, dbo.GATEOUTDETAIL.GOTIME,
					  GATEINDETAIL.CONTNRSID
FROM         dbo.GATEOUTDETAIL RIGHT OUTER JOIN
                      dbo.GATEINDETAIL INNER JOIN
					 
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                      dbo.CONTAINERTYPEMASTER ON dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID ON 
                      dbo.GATEOUTDETAIL.GIDID = dbo.GATEINDETAIL.GIDID and GATEINDETAIL.CONTNRSID > 2
where GATEINDETAIL.SDPTID = 2

