alter VIEW dbo.VW_EXPORT_GATEOUT_TRUCKNO_CBX_ASSGN
AS
SELECT     TOP 100 PERCENT dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.AVHLNO, dbo.GATEINDETAIL.DRVNAME, dbo.GATEINDETAIL.CHAID,
			CHANAME, GIDATE
FROM         dbo.GATEINDETAIL LEFT OUTER JOIN
                      dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID
WHERE     (dbo.GATEINDETAIL.SDPTID = 2) AND (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) AND (dbo.GATEINDETAIL.GPSTYPE IN (0, 1, 2, 3))
ORDER BY dbo.GATEINDETAIL.GIDID