CREATE VIEW [dbo].[VW_EXPORT_SLABTYPE_HSN_DETAIL_ASSGN]
AS
SELECT        dbo.EXPORTSLABTYPEMASTER.SLABTID, dbo.HSNCODEMASTER.HSNCODE, dbo.HSNCODEMASTER.CGSTEXPRN, dbo.HSNCODEMASTER.SGSTEXPRN, 
                         dbo.HSNCODEMASTER.IGSTEXPRN, dbo.HSNCODEMASTER.ACGSTEXPRN, dbo.HSNCODEMASTER.ASGSTEXPRN, dbo.HSNCODEMASTER.AIGSTEXPRN
FROM            dbo.EXPORTSLABTYPEMASTER INNER JOIN
                         dbo.HSNCODEMASTER ON dbo.EXPORTSLABTYPEMASTER.HSNID = dbo.HSNCODEMASTER.HSNID
GROUP BY dbo.EXPORTSLABTYPEMASTER.SLABTID, dbo.HSNCODEMASTER.CGSTEXPRN, dbo.HSNCODEMASTER.SGSTEXPRN, dbo.HSNCODEMASTER.IGSTEXPRN, 
                         dbo.HSNCODEMASTER.ACGSTEXPRN, dbo.HSNCODEMASTER.ASGSTEXPRN, dbo.HSNCODEMASTER.AIGSTEXPRN, dbo.HSNCODEMASTER.HSNCODE


