alter VIEW dbo.VW_EXPORT_SHIPPING_BILL_INVOICE_DETAIL
AS
SELECT      distinct b.ESBMID, a.TRANMID, a.TRANDATE, a.TRANTIME, a.TRANDNO, a.TRANREFNAME, a.TRANREFNO, a.TRANREFDATE, 
			a.TRANNAMT, a.TRANREFID
FROM            dbo.TRANSACTIONMASTER a(nolock) INNER JOIN
                         dbo.VW_EXPORT_SHIPPING_BILL_WISE_STUFFNG_DETAIL_ASSGN b(nolock) ON a.TRANLMID = b.STFMID


-- select * from VW_EXPORT_SHIPPING_BILL_INVOICE_DETAIL where ESBMID = 52828