-- select * from [VW_EXPORT_SHIPPINGBILL_WISE_CARTINGORDER_DETAIL_ASSGN] where ESBOINVNO = '119106'
alter VIEW [dbo].[VW_EXPORT_SHIPPINGBILL_WISE_CARTINGORDER_DETAIL_ASSGN]
AS
SELECT     dbo.SHIPPINGBILLDETAIL.SBDID, dbo.EXPORTSHIPPINGBILLMASTER.ESBMID, dbo.SHIPPINGBILLMASTER.SBMDATE, 
                      dbo.SHIPPINGBILLMASTER.SBMDNO, dbo.SHIPPINGBILLDETAIL.SBDNOP, dbo.SHIPPINGBILLDETAIL.SBDQTY, 
                      dbo.SHIPPINGBILLDETAIL.PRDTDESC, dbo.SHIPPINGBILLDETAIL.TRUCKNO, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO, 
                      dbo.SHIPPINGBILLDETAIL.SBDDATE, dbo.SHIPPINGBILLDETAIL.GIDID, dbo.SHIPPINGBILLDETAIL.SBDDNO,
					  dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO, ESBOINVNO, ESBOINVDATE,
					  isnull(EXPORTSHIPPINGBILLDETAIL.ESBMNOP,0) ESBMNOP, isnull(EXPORTSHIPPINGBILLDETAIL.ESBMQTY,0) ESBMQTY
FROM         dbo.EXPORTSHIPPINGBILLMASTER INNER JOIN
                      dbo.SHIPPINGBILLDETAIL ON dbo.EXPORTSHIPPINGBILLMASTER.ESBMID = dbo.SHIPPINGBILLDETAIL.ESBMID INNER JOIN
                      dbo.SHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID left join
					  EXPORTSHIPPINGBILLDETAIL on EXPORTSHIPPINGBILLMASTER.ESBMID = EXPORTSHIPPINGBILLDETAIL.ESBMID



