ALTER VIEW [dbo].[VW_EXPORT_ASL_DETAIL_CTRL_ASSGN_MODS]
AS
SELECT     dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, dbo.AUTHORIZATIONSLIPDETAIL.ASLMID, dbo.AUTHORIZATIONSLIPDETAIL.OSDID, 
                      dbo.AUTHORIZATIONSLIPDETAIL.LCATEID, dbo.AUTHORIZATIONSLIPDETAIL.ASLDTYPE, dbo.AUTHORIZATIONSLIPDETAIL.ASLLTYPE, 
                      dbo.AUTHORIZATIONSLIPDETAIL.ASLOTYPE, dbo.AUTHORIZATIONSLIPDETAIL.VHLNO, dbo.AUTHORIZATIONSLIPDETAIL.DRVNAME, 
                      dbo.AUTHORIZATIONSLIPDETAIL.DISPSTATUS, dbo.AUTHORIZATIONSLIPDETAIL.ASLFDESC, dbo.AUTHORIZATIONSLIPDETAIL.ASLTDESC, 
                      dbo.AUTHORIZATIONSLIPDETAIL.PRCSDATE, dbo.AUTHORIZATIONSLIPDETAIL.ASLDODATE, dbo.AUTHORIZATIONSLIPDETAIL.STFDID, 
                      dbo.AUTHORIZATIONSLIPDETAIL.CSEALNO, dbo.AUTHORIZATIONSLIPDETAIL.ASEALNO, MAX(dbo.STUFFINGPRODUCTDETAIL.STFDSBNO) AS STFDSBNO, 
                      MAX(dbo.STUFFINGPRODUCTDETAIL.STFDSBDNO) AS STFDSBDNO, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                      dbo.SHIPPINGBILLMASTER.CHANAME, MAX(dbo.SHIPPINGBILLMASTER.EXPRTNAME) AS EXPRTNAME, dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.GIDATE, 
                      dbo.STUFFINGDETAIL.GIDID, AUTHORIZATIONSLIPDETAIL.SLTID ,Export_SealTypeMaster.SLTDESC
FROM         dbo.STUFFINGPRODUCTDETAIL INNER JOIN
                      dbo.STUFFINGDETAIL ON dbo.STUFFINGPRODUCTDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID INNER JOIN
                      dbo.GATEINDETAIL ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                      dbo.SHIPPINGBILLDETAIL ON dbo.STUFFINGPRODUCTDETAIL.SBDID = dbo.SHIPPINGBILLDETAIL.SBDID INNER JOIN
                      dbo.SHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID INNER JOIN
                      dbo.AUTHORIZATIONSLIPDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.AUTHORIZATIONSLIPDETAIL.STFDID Inner Join 
					  dbo.Export_SealTypeMaster (nolock) On dbo.AUTHORIZATIONSLIPDETAIL.SLTID = Export_SealTypeMaster.SLTID 
GROUP BY dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.GIDATE, 
                      dbo.SHIPPINGBILLMASTER.CHANAME, dbo.STUFFINGDETAIL.GIDID, dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, dbo.AUTHORIZATIONSLIPDETAIL.ASLMID, 
                      dbo.AUTHORIZATIONSLIPDETAIL.OSDID, dbo.AUTHORIZATIONSLIPDETAIL.LCATEID, dbo.AUTHORIZATIONSLIPDETAIL.ASLDTYPE, 
                      dbo.AUTHORIZATIONSLIPDETAIL.ASLLTYPE, dbo.AUTHORIZATIONSLIPDETAIL.ASLOTYPE, dbo.AUTHORIZATIONSLIPDETAIL.VHLNO, 
                      dbo.AUTHORIZATIONSLIPDETAIL.DRVNAME, dbo.AUTHORIZATIONSLIPDETAIL.DISPSTATUS, dbo.AUTHORIZATIONSLIPDETAIL.PRCSDATE, 
                      dbo.AUTHORIZATIONSLIPDETAIL.ASLFDESC, dbo.AUTHORIZATIONSLIPDETAIL.ASLTDESC, dbo.AUTHORIZATIONSLIPDETAIL.ASLDODATE, 
                      dbo.AUTHORIZATIONSLIPDETAIL.STFDID, dbo.AUTHORIZATIONSLIPDETAIL.CSEALNO, dbo.AUTHORIZATIONSLIPDETAIL.ASEALNO, 
					  AUTHORIZATIONSLIPDETAIL.SLTID,Export_SealTypeMaster.SLTDESC