alter VIEW dbo.VW_EXPORT_VT_PRINT_ASSGN
AS
SELECT        dbo.COMPANYMASTER.COMPDNAME, dbo.COMPANYMASTER.COMPADDR, dbo.TMPRPT_IDS.KUSRID, dbo.TMPRPT_IDS.RPTID, dbo.VEHICLETICKETDETAIL.VTDID, dbo.VEHICLETICKETDETAIL.COMPYID, 
                         dbo.VEHICLETICKETDETAIL.SDPTID, dbo.VEHICLETICKETDETAIL.VTDATE, RIGHT(dbo.VEHICLETICKETDETAIL.VTTIME, 8) AS VTTIME, dbo.VEHICLETICKETDETAIL.VTNO, dbo.VEHICLETICKETDETAIL.VTDNO, 
                         dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.CONTAINERTYPEMASTER.CONTNRTCODE, MAX(dbo.SHIPPINGBILLMASTER.EXPRTNAME) AS EXPRTNAME, 
                         dbo.GATEINDETAIL.CHANAME AS STMRNAME, dbo.VEHICLETICKETDETAIL.VHLNO, dbo.VEHICLETICKETDETAIL.VTTYPE, dbo.VEHICLETICKETDETAIL.DRVNAME, 
                         dbo.VEHICLETICKETDETAIL.CUSRID AS EMPNAME, MAX(dbo.SHIPPINGBILLDETAIL.PRDTTID) AS PRDTTID, MAX(dbo.SHIPPINGBILLDETAIL.PRDTDESC) AS PRDTDESC, dbo.GATEINDETAIL.IGMNO, 
                         dbo.GATEINDETAIL.GPLNO, dbo.VEHICLETICKETDETAIL.VTREMRKS, dbo.VEHICLETICKETDETAIL.VTQTY, dbo.VEHICLETICKETDETAIL.VTSSEALNO, dbo.STUFFINGMASTER.STFMDATE, 
                         dbo.STUFFINGMASTER.STFMDNO, dbo.GATEINDETAIL.GPPLCNAME AS CHANAME, SUM(dbo.STUFFINGPRODUCTDETAIL.STFDNOP) AS STFDNOP, SUM(dbo.STUFFINGPRODUCTDETAIL.STFDQTY) AS STFDQTY, 
                         MAX(dbo.EXPORTSHIPPINGBILLMASTER.ESBMDPNAME) AS SBMDPNAME, dbo.GATEOUTDETAIL.LSEALNO, dbo.GATEOUTDETAIL.SSEALNO, dbo.GATEOUTDETAIL.GOTRNSPRTNAME, 
                         dbo.GATEINDETAIL.STMRNAME AS ESTRMNAME, dbo.AUTHORIZATIONSLIPDETAIL.CSEALNO, dbo.AUTHORIZATIONSLIPDETAIL.ASEALNO, MAX(dbo.STUFFINGPRODUCTDETAIL.STFDSBNO) AS STFDSBNO, 
                         MAX(dbo.STUFFINGPRODUCTDETAIL.STFDSBDNO) AS STFDSBDNO, dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLNO, dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLDATE, 
                         dbo.VEHICLETICKETDETAIL.QRCDIMGPATH
FROM            dbo.EXPORTSHIPPINGBILLDETAIL INNER JOIN
                         dbo.EXPORTSHIPPINGBILLMASTER ON dbo.EXPORTSHIPPINGBILLDETAIL.ESBMID = dbo.EXPORTSHIPPINGBILLMASTER.ESBMID RIGHT OUTER JOIN
                         dbo.SHIPPINGBILLMASTER RIGHT OUTER JOIN
                         dbo.SHIPPINGBILLDETAIL RIGHT OUTER JOIN
                         dbo.STUFFINGMASTER RIGHT OUTER JOIN
                         dbo.TMPRPT_IDS INNER JOIN
                         dbo.VEHICLETICKETDETAIL INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.VEHICLETICKETDETAIL.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                         dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID ON dbo.TMPRPT_IDS.RPTID = dbo.VEHICLETICKETDETAIL.VTDID INNER JOIN
                         dbo.AUTHORIZATIONSLIPDETAIL ON dbo.VEHICLETICKETDETAIL.STFDID = dbo.AUTHORIZATIONSLIPDETAIL.STFDID INNER JOIN
                         dbo.STUFFINGDETAIL ON dbo.AUTHORIZATIONSLIPDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID ON dbo.STUFFINGMASTER.STFMID = dbo.STUFFINGDETAIL.STFMID LEFT OUTER JOIN
                         dbo.STUFFINGPRODUCTDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID ON dbo.SHIPPINGBILLDETAIL.SBDID = dbo.STUFFINGPRODUCTDETAIL.SBDID ON 
                         dbo.SHIPPINGBILLMASTER.SBMID = dbo.SHIPPINGBILLDETAIL.SBMID ON dbo.EXPORTSHIPPINGBILLMASTER.ESBMID = dbo.SHIPPINGBILLDETAIL.ESBMID FULL OUTER JOIN
                         dbo.CONTAINERTYPEMASTER RIGHT OUTER JOIN
                         dbo.CONTAINERSIZEMASTER INNER JOIN
                         dbo.GATEINDETAIL ON dbo.CONTAINERSIZEMASTER.CONTNRSID = dbo.GATEINDETAIL.CONTNRSID LEFT OUTER JOIN
                         dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID ON dbo.CONTAINERTYPEMASTER.CONTNRTID = dbo.GATEINDETAIL.CONTNRTID ON 
                         dbo.VEHICLETICKETDETAIL.GIDID = dbo.GATEINDETAIL.GIDID AND dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID
GROUP BY dbo.COMPANYMASTER.COMPDNAME, dbo.COMPANYMASTER.COMPADDR, dbo.TMPRPT_IDS.KUSRID, dbo.TMPRPT_IDS.RPTID, dbo.VEHICLETICKETDETAIL.VTDID, dbo.VEHICLETICKETDETAIL.COMPYID, 
                         dbo.VEHICLETICKETDETAIL.SDPTID, dbo.VEHICLETICKETDETAIL.VTDATE, RIGHT(dbo.VEHICLETICKETDETAIL.VTTIME, 8), dbo.VEHICLETICKETDETAIL.VTNO, dbo.VEHICLETICKETDETAIL.VTDNO, 
                         dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.CONTAINERTYPEMASTER.CONTNRTCODE, dbo.GATEINDETAIL.CHANAME, dbo.VEHICLETICKETDETAIL.VHLNO, 
                         dbo.VEHICLETICKETDETAIL.VTTYPE, dbo.VEHICLETICKETDETAIL.DRVNAME, dbo.VEHICLETICKETDETAIL.CUSRID, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.VEHICLETICKETDETAIL.VTREMRKS, 
                         dbo.VEHICLETICKETDETAIL.VTQTY, dbo.VEHICLETICKETDETAIL.VTSSEALNO, dbo.STUFFINGMASTER.STFMDATE, dbo.STUFFINGMASTER.STFMDNO, dbo.GATEINDETAIL.GPPLCNAME, 
                         dbo.GATEOUTDETAIL.LSEALNO, dbo.GATEOUTDETAIL.SSEALNO, dbo.GATEOUTDETAIL.GOTRNSPRTNAME, dbo.GATEINDETAIL.STMRNAME, dbo.AUTHORIZATIONSLIPDETAIL.CSEALNO, 
                         dbo.AUTHORIZATIONSLIPDETAIL.ASEALNO, dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLNO, dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLDATE, dbo.VEHICLETICKETDETAIL.QRCDIMGPATH
HAVING        (dbo.VEHICLETICKETDETAIL.SDPTID = 2)

