CREATE VIEW dbo.VW_EXPORT_EMPTY_VT_PRINT_ASSGN
AS
SELECT        dbo.COMPANYMASTER.COMPDNAME, dbo.COMPANYMASTER.COMPADDR, dbo.TMPRPT_IDS.KUSRID, dbo.TMPRPT_IDS.RPTID, dbo.VEHICLETICKETDETAIL.VTDID, dbo.VEHICLETICKETDETAIL.COMPYID, 
                         dbo.VEHICLETICKETDETAIL.SDPTID, dbo.VEHICLETICKETDETAIL.VTDATE, RIGHT(dbo.VEHICLETICKETDETAIL.VTTIME, 8) AS VTTIME, dbo.VEHICLETICKETDETAIL.VTNO, dbo.VEHICLETICKETDETAIL.VTDNO, 
                         dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.CONTAINERTYPEMASTER.CONTNRTCODE, MAX(dbo.SHIPPINGBILLMASTER.EXPRTNAME) AS EXPRTNAME, 
                         dbo.GATEINDETAIL.CHANAME AS STMRNAME, dbo.VEHICLETICKETDETAIL.VHLNO, dbo.VEHICLETICKETDETAIL.VTTYPE, dbo.VEHICLETICKETDETAIL.DRVNAME, 
                         dbo.VEHICLETICKETDETAIL.CUSRID AS EMPNAME, MAX(dbo.SHIPPINGBILLDETAIL.PRDTTID) AS PRDTTID, MAX(dbo.GATEINDETAIL.PRDTDESC) AS PRDTDESC, dbo.GATEINDETAIL.IGMNO, 
                         dbo.GATEINDETAIL.GPLNO, dbo.VEHICLETICKETDETAIL.VTREMRKS, dbo.VEHICLETICKETDETAIL.VTQTY, dbo.VEHICLETICKETDETAIL.VTSSEALNO, dbo.STUFFINGMASTER.STFMDATE, 
                         dbo.STUFFINGMASTER.STFMDNO, dbo.GATEINDETAIL.GPPLCNAME AS CHANAME, SUM(dbo.GATEINDETAIL.GPNOP) AS STFDNOP, SUM(dbo.STUFFINGPRODUCTDETAIL.STFDQTY) AS STFDQTY, 
                         MAX(dbo.EXPORTSHIPPINGBILLMASTER.ESBMDPNAME) AS SBMDPNAME, dbo.GATEOUTDETAIL.LSEALNO, dbo.GATEOUTDETAIL.SSEALNO, dbo.GATEOUTDETAIL.GOTRNSPRTNAME, 
                         dbo.GATEINDETAIL.STMRNAME AS ESTRMNAME, dbo.AUTHORIZATIONSLIPDETAIL.CSEALNO, dbo.AUTHORIZATIONSLIPDETAIL.ASEALNO, MAX(dbo.STUFFINGPRODUCTDETAIL.STFDSBNO) AS STFDSBNO, 
                         MAX(dbo.STUFFINGPRODUCTDETAIL.STFDSBDNO) AS STFDSBDNO, dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLNO, dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLDATE, 
                         dbo.VEHICLETICKETDETAIL.QRCDIMGPATH
FROM            dbo.TMPRPT_IDS 
						INNER JOIN dbo.VEHICLETICKETDETAIL ON dbo.TMPRPT_IDS.RPTID = dbo.VEHICLETICKETDETAIL.VTDID  
						inner JOIN dbo.COMPANYACCOUNTINGDETAIL ON dbo.VEHICLETICKETDETAIL.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID 
						INNER JOIN dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID 
						left JOIN dbo.GATEINDETAIL ON dbo.VEHICLETICKETDETAIL.GIDID =dbo.GATEINDETAIL.GIDID
						left JOIN dbo.AUTHORIZATIONSLIPDETAIL ON dbo.VEHICLETICKETDETAIL.STFDID = dbo.AUTHORIZATIONSLIPDETAIL.STFDID 
						left JOIN dbo.STUFFINGDETAIL ON dbo.AUTHORIZATIONSLIPDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID AND dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID
						left join dbo.STUFFINGPRODUCTDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID 
						left join dbo.STUFFINGMASTER ON dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID 
						LEFT JOIN SHIPPINGBILLDETAIL on dbo.STUFFINGPRODUCTDETAIL.SBDID  = dbo.SHIPPINGBILLDETAIL.SBDID 
						left join SHIPPINGBILLMASTER on dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID 
						left join EXPORTSHIPPINGBILLMASTER on SHIPPINGBILLDETAIL.ESBMID = dbo.EXPORTSHIPPINGBILLMASTER.ESBMID 
						left join EXPORTSHIPPINGBILLDETAIL on EXPORTSHIPPINGBILLMASTER.ESBMID = EXPORTSHIPPINGBILLDETAIL.ESBMID 
						left join dbo.CONTAINERTYPEMASTER on dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID 
						left join dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID 
                        left join dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID                          
GROUP BY dbo.COMPANYMASTER.COMPDNAME, dbo.COMPANYMASTER.COMPADDR, dbo.TMPRPT_IDS.KUSRID, dbo.TMPRPT_IDS.RPTID, dbo.VEHICLETICKETDETAIL.VTDID, dbo.VEHICLETICKETDETAIL.COMPYID, 
                         dbo.VEHICLETICKETDETAIL.SDPTID, dbo.VEHICLETICKETDETAIL.VTDATE, RIGHT(dbo.VEHICLETICKETDETAIL.VTTIME, 8), dbo.VEHICLETICKETDETAIL.VTNO, dbo.VEHICLETICKETDETAIL.VTDNO, 
                         dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.CONTAINERTYPEMASTER.CONTNRTCODE, dbo.GATEINDETAIL.CHANAME, dbo.VEHICLETICKETDETAIL.VHLNO, 
                         dbo.VEHICLETICKETDETAIL.VTTYPE, dbo.VEHICLETICKETDETAIL.DRVNAME, dbo.VEHICLETICKETDETAIL.CUSRID, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.VEHICLETICKETDETAIL.VTREMRKS, 
                         dbo.VEHICLETICKETDETAIL.VTQTY, dbo.VEHICLETICKETDETAIL.VTSSEALNO, dbo.STUFFINGMASTER.STFMDATE, dbo.STUFFINGMASTER.STFMDNO, dbo.GATEINDETAIL.GPPLCNAME, 
                         dbo.GATEOUTDETAIL.LSEALNO, dbo.GATEOUTDETAIL.SSEALNO, dbo.GATEOUTDETAIL.GOTRNSPRTNAME, dbo.GATEINDETAIL.STMRNAME, dbo.AUTHORIZATIONSLIPDETAIL.CSEALNO, 
                         dbo.AUTHORIZATIONSLIPDETAIL.ASEALNO, dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLNO, dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLDATE, dbo.VEHICLETICKETDETAIL.QRCDIMGPATH
HAVING        (dbo.VEHICLETICKETDETAIL.SDPTID = 2)

