ALTER VIEW [dbo].[VW_EXPORT_GATEOUT_CONTAINER_CBX_CHNG_ASSGN]
AS
SELECT distinct dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.CONTAINERTYPEMASTER.CONTNRTCODE, 
ISNULL(VEHICLETICKETDETAIL.VTNO,0) as VTNO,ISNULL(VEHICLETICKETDETAIL.VTDNO,'') as VTDNO ,STUFFINGMASTER.STFMNO,dbo.STUFFINGMASTER.STFMNAME AS CHANAME, 
dbo.STUFFINGMASTER.CHAID, isnull(dbo.VEHICLETICKETDETAIL.DRVNAME,'') as DRVNAME,isnull(dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, 0) as ASLDID,
isnull(dbo.AUTHORIZATIONSLIPDETAIL.CSEALNO,'') as CSEALNO, isnull(dbo.AUTHORIZATIONSLIPDETAIL.ASEALNO,'') as ASEALNO,  
convert(varchar(10),dbo.GATEINDETAIL.GIDATE,103) as  GIDATE, isnull(dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE,0) as  ASLMTYPE, isnull(dbo.VEHICLETICKETDETAIL.TRNSPRTNAME,'') as GOTRNSPRTNAME,
isnull(dbo.VEHICLETICKETDETAIL.VHLNO,'') as VHLNO 
FROM      VEHICLETICKETDETAIL (NOLOCK) inner join 
         dbo.AUTHORIZATIONSLIPDETAIL (nolock) ON dbo.VEHICLETICKETDETAIL.ASLDID = dbo.AUTHORIZATIONSLIPDETAIL.ASLDID Inner Join 
		 dbo.AUTHORIZATIONSLIPMASTER (nolock) ON dbo.AUTHORIZATIONSLIPDETAIL.ASLMID = dbo.AUTHORIZATIONSLIPMASTER.ASLMID Inner Join  
		 dbo.GATEINDETAIL (nolock) ON dbo.VEHICLETICKETDETAIL.GIDID = dbo.GATEINDETAIL.GIDID Inner Join  
		 dbo.CONTAINERSIZEMASTER (nolock) ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID Inner JOIN 
		 dbo.CONTAINERTYPEMASTER (nolock) ON dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID Inner Join
		 dbo.STUFFINGDETAIL  (nolock) On dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID Inner Join
		 dbo.STUFFINGMASTER  (nolock) On dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID LEFT OUTER JOIN
         dbo.GATEOUTDETAIL ON dbo.VEHICLETICKETDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID
		  where GATEINDETAIL.SDPTID=2   and (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0)   --and (dbo.GATEINDETAIL.GPSTYPE IN (4, 5))

