USE [SCFS_ERP_DEVPT]
GO

/****** Object:  View [dbo].[VW_BOE_NOT_BILL_MAX_GIDATE_ASSGN]    Script Date: 16/09/2021 17:38:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
alter VIEW [dbo].[VW_ESEAL_BILL_MAX_GIDATE_ASSGN]
AS
SELECT        dbo.GATEINDETAIL.GIDID,
			 case when CATESTRCALCTYPE =0 then MIN(dbo.GATEINDETAIL.GIDATE)  else MAX(dbo.GATEINDETAIL.GIDATE) end AS XGIDATE
FROM            dbo.GATEINDETAIL (nolock) LEFT OUTER JOIN
                         dbo.VW_ESEAL_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01 (nolock) ON 
                         dbo.GATEINDETAIL.CHAID = dbo.VW_ESEAL_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANREFID 

				join CATEGORYMASTER (nolock) on gateindetail.chaid = categorymaster.cateid
WHERE        (ISNULL(dbo.VW_ESEAL_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01.TRANDID, 0) = 0) and GATEINDETAIL.SDPTID=11
--and CATESTRCALCTYPE = 1
GROUP BY dbo.GATEINDETAIL.GIDID   , CATESTRCALCTYPE
 

GO

