ALTER VIEW [dbo].[VW_EXPORT_INVOICE_STUFFING_DETAIL_CTRL_ASSGN]
AS
SELECT        dbo.SHIPPINGBILLMASTER.EXPRTNAME, dbo.SHIPPINGBILLMASTER.CHANAME, dbo.SHIPPINGBILLMASTER.CHAID, dbo.SHIPPINGBILLMASTER.EXPRTID, 
                         dbo.STUFFINGMASTER.STFMID, dbo.STUFFINGMASTER.STFTID, dbo.STUFFINGMASTER.EOPTID as SLABTID, ISNULL(dbo.STATEMASTER.STATETYPE, 0) AS STATETYPE
FROM            dbo.CATEGORYMASTER INNER JOIN
                         dbo.SHIPPINGBILLDETAIL INNER JOIN
                         dbo.STUFFINGPRODUCTDETAIL ON dbo.SHIPPINGBILLDETAIL.SBDID = dbo.STUFFINGPRODUCTDETAIL.SBDID INNER JOIN
                         dbo.SHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID INNER JOIN
                         dbo.STUFFINGDETAIL ON dbo.STUFFINGPRODUCTDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID INNER JOIN
                         dbo.STUFFINGMASTER ON dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID ON 
                         dbo.CATEGORYMASTER.CATEID = dbo.STUFFINGMASTER.STFBILLREFID LEFT OUTER JOIN
						 DBO.CATEGORY_ADDRESS_DETAIL ON CATEGORYMASTER.CATEID = CATEGORY_ADDRESS_DETAIL.CATEID
						 AND STUFFINGMASTER.STFBCATEAID= CATEGORY_ADDRESS_DETAIL.CATEAID LEFT OUTER JOIN
                         dbo.STATEMASTER ON dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID




