ALTER VIEW [dbo].[VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01]
AS
SELECT     TOP (100) PERCENT dbo.EXPORTSLABMASTER.SLABTID, dbo.EXPORTSLABMASTER.TARIFFMID, dbo.EXPORTSLABMASTER.CHAID, 
                      dbo.EXPORTSLABMASTER.CHRGETYPE, dbo.EXPORTSLABMASTER.CONTNRSID, dbo.EXPORTSLABMASTER.SDTYPE, dbo.EXPORTSLABMASTER.YRDTYPE, 
                      dbo.EXPORTSLABMASTER.HTYPE, dbo.EXPORTSLABMASTER.WTYPE,dbo.EXPORTSLABMASTER.EOPTID, 
					  MAX(dbo.EXPORTSLABMASTER.SLABMDATE) AS XTRANSDATE
FROM         dbo.EXPORTTARIFFMASTER INNER JOIN
                      dbo.EXPORTSLABMASTER ON dbo.EXPORTTARIFFMASTER.TARIFFMID = dbo.EXPORTSLABMASTER.TARIFFMID
WHERE     (dbo.EXPORTSLABMASTER.SLABMDATE <=
                          (SELECT     MAX(TRANNDATE) AS Expr1
                            FROM          dbo.TRANSACTION_DAYEND_MASTER))
GROUP BY dbo.EXPORTSLABMASTER.TARIFFMID, dbo.EXPORTSLABMASTER.SLABTID, dbo.EXPORTSLABMASTER.CHAID, dbo.EXPORTSLABMASTER.CHRGETYPE, 
                      dbo.EXPORTSLABMASTER.CONTNRSID, dbo.EXPORTSLABMASTER.SDTYPE, dbo.EXPORTSLABMASTER.YRDTYPE, dbo.EXPORTSLABMASTER.HTYPE, 
                      dbo.EXPORTSLABMASTER.WTYPE, dbo.EXPORTSLABMASTER.EOPTID
ORDER BY dbo.EXPORTSLABMASTER.TARIFFMID


