ALTER VIEW [dbo].[VW_ESEAL_GATEOUT_MOD_ASSGN]
AS
SELECT     dbo.GATEOUTDETAIL.GODID, dbo.GATEOUTDETAIL.COMPYID, dbo.GATEOUTDETAIL.SDPTID, dbo.GATEOUTDETAIL.REGSTRID, dbo.GATEOUTDETAIL.GODATE, 
                      dbo.GATEOUTDETAIL.GOTIME, dbo.GATEOUTDETAIL.GONO, dbo.GATEOUTDETAIL.GODNO, dbo.GATEOUTDETAIL.GIDID, dbo.GATEOUTDETAIL.TRANDID, 
                      dbo.GATEOUTDETAIL.VHLNO, dbo.GATEOUTDETAIL.GDRVNAME AS DRVNAME, dbo.GATEOUTDETAIL.CHASNAME, dbo.GATEOUTDETAIL.GOBTYPE, 
                      dbo.GATEOUTDETAIL.CHAID,Isnull(dbo.GATEOUTDETAIL.LSEALNO,'') as LSEALNO, 
					   dbo.GATEINDETAIL.STMRID ,GATEINDETAIL.STMRNAME,GATEINDETAIL.EXPRTRID ,GATEINDETAIL.EXPRTRNAME,
					  Isnull(dbo.GATEOUTDETAIL.SSEALNO,'') as SSEALNO, 
					  dbo.GATEOUTDETAIL.CUSRID, dbo.GATEOUTDETAIL.LMUSRID, 
                      dbo.GATEOUTDETAIL.DISPSTATUS, dbo.GATEOUTDETAIL.PRCSDATE, dbo.GATEOUTDETAIL.GOQTY, dbo.GATEOUTDETAIL.OTDID, dbo.GATEOUTDETAIL.OTDNO, 
                      dbo.GATEOUTDETAIL.CONTNRFID, dbo.GATEOUTDETAIL.BOOKID, dbo.GATEOUTDETAIL.GOPLCNAME, dbo.GATEOUTDETAIL.GOBKGNO, 
                      dbo.GATEOUTDETAIL.GOEGMNO, dbo.GATEOUTDETAIL.OVSLID, dbo.GATEOUTDETAIL.OVSLNAME, dbo.GATEOUTDETAIL.OVOYNO, dbo.GATEOUTDETAIL.GOREMRKS, 
                      dbo.GATEOUTDETAIL.EHIDATE, dbo.GATEOUTDETAIL.EHITIME, dbo.GATEOUTDETAIL.GOTRNSPRTNAME, dbo.GATEOUTDETAIL.GOTTYPE, 
                      dbo.GATEOUTDETAIL.GOOTYPE, dbo.GATEOUTDETAIL.GOCTYPE, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                      dbo.VEHICLETICKETDETAIL.VTNO,
					  isnull(VEHICLETICKETDETAIL.VTTYPE,0) as VTTYPE,
					  (case when VEHICLETICKETDETAIL.VTTYPE=0 then 'CCTL' 
					        when VEHICLETICKETDETAIL.VTTYPE=1 Then 'CITPL' 
							when VEHICLETICKETDETAIL.VTTYPE=4 Then 'KATL'  
							when VEHICLETICKETDETAIL.VTTYPE=5 Then 'AECTPL'  end) as Port,
					
					 isnull(GATEINDETAIL.DRVMBLNO,'') as  DRVMBLNO,isnull(GATEINDETAIL.DRVLCNO,'') as  DRVLCNO,
					  convert(varchar(10) ,dbo.GATEINDETAIL.GIDATE,105) as  GIDATE, dbo.GATEINDETAIL.CHANAME AS CHANAME, 
                       dbo.VEHICLETICKETDETAIL.VTSSEALNO AS ASEALNO,  dbo.VEHICLETICKETDETAIL.VTSSEALNO, 
                      dbo.GATEINDETAIL.GPSTYPE
FROM   GATEOUTDETAIL (nolock) Inner Join 
       GATEINDETAIL (nolock) On dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID Inner Join 
	   VEHICLETICKETDETAIL (nolock) On dbo.GATEINDETAIL.GIDID = dbo.VEHICLETICKETDETAIL.GIDID Inner Join 
	   CONTAINERSIZEMASTER (nolock) On dbo.GATEINDETAIL.CONTNRSID = CONTAINERSIZEMASTER.CONTNRSID 


			 where GATEINDETAIL.SDPTID=11 
