alter VIEW [dbo].[VW_EXPORT_STUFFING_BILL_PRINT_ADDRESS_DETAIL_ASSGN]
AS
SELECT     dbo.TRANSACTIONDETAIL.TRANMID, dbo.CATEGORYMASTER.CATENAME AS TRANCSNAME, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR1 AS TRANIMPADDR1, 
                      dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR2 AS TRANIMPADDR2, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR3 AS TRANIMPADDR3, 
                      dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR4 AS TRANIMPADDR4, dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO AS TRANGSTNO, dbo.TRANSACTIONMASTER.TRANREFID,
					  dbo.CATEGORY_ADDRESS_DETAIL.CATEAID
FROM         dbo.TRANSACTIONDETAIL INNER JOIN
                      dbo.STUFFINGDETAIL ON dbo.TRANSACTIONDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID INNER JOIN
                      dbo.STUFFINGMASTER ON dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID INNER JOIN
                      dbo.CATEGORYMASTER LEFT JOIN CATEGORY_ADDRESS_DETAIL ON CATEGORYMASTER.CATEID = CATEGORY_ADDRESS_DETAIL.CATEID
					   ON dbo.STUFFINGMASTER.STFBILLREFID = dbo.CATEGORYMASTER.CATEID AND STUFFINGMASTER.STFCATEAID = CATEGORY_ADDRESS_DETAIL.CATEAID
					    INNER JOIN dbo.TRANSACTIONMASTER ON dbo.TRANSACTIONDETAIL.TRANMID = dbo.TRANSACTIONMASTER.TRANMID
GROUP BY dbo.TRANSACTIONDETAIL.TRANMID, dbo.CATEGORYMASTER.CATENAME, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR1, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR2, 
                      dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR3, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR4, dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO, dbo.TRANSACTIONMASTER.TRANREFID,
					  dbo.CATEGORY_ADDRESS_DETAIL.CATEAID
