CREATE VIEW VW_EXPORT_SHIPPINGBILL_NO_CTRL_ASSGN
AS
SELECT ESBMDNO,EXPORTSHIPPINGBILLMASTER.ESBMID,SBDID
       FROM EXPORTSHIPPINGBILLMASTER LEFT OUTER JOIN 
       SHIPPINGBILLDETAIL ON EXPORTSHIPPINGBILLMASTER.ESBMID=SHIPPINGBILLDETAIL.ESBMID
	   WHERE EXPORTSHIPPINGBILLMASTER.DISPSTATUS=0 AND ISNULL(SBDID,0)=0