ALTER VIEW [dbo].[VW_EXPORT_RATECARDMASTER_FLX_ASSGN]
AS
SELECT     dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.TARIFFMID, dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.SLABTID, 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.CHRGETYPE, dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.CHAID, 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.CONTNRSID, dbo.EXPORTSLABMASTER.SLABMID, dbo.EXPORTSLABMASTER.COMPYID, 
                      dbo.CATEGORYMASTER.CATEDNAME, dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.XTRANSDATE, 
                      dbo.CONTAINERSIZEMASTER.CONTNRSCODE, dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.YRDTYPE, 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.SDTYPE, dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.HTYPE, 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.WTYPE, dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.EOPTID,
					   dbo.EXPORTSLABMASTER.SLABMIN, dbo.EXPORTSLABMASTER.SLABMAX, dbo.EXPORTSLABMASTER.SLABAMT,
					   dbo.EXPORTSLABMASTER.SLABUAMT, dbo.EXPORTSLABMASTER.SLABMDATE
FROM         dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01 INNER JOIN
                      dbo.EXPORTSLABMASTER ON dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.TARIFFMID = dbo.EXPORTSLABMASTER.TARIFFMID AND 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.CHAID = dbo.EXPORTSLABMASTER.CHAID AND 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.CHRGETYPE = dbo.EXPORTSLABMASTER.CHRGETYPE AND 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.CONTNRSID = dbo.EXPORTSLABMASTER.CONTNRSID AND 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.SDTYPE = dbo.EXPORTSLABMASTER.SDTYPE AND 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.YRDTYPE = dbo.EXPORTSLABMASTER.YRDTYPE AND 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.HTYPE = dbo.EXPORTSLABMASTER.HTYPE AND 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.WTYPE = dbo.EXPORTSLABMASTER.WTYPE AND 
					  dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.EOPTID = dbo.EXPORTSLABMASTER.EOPTID AND 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.SLABTID = dbo.EXPORTSLABMASTER.SLABTID AND 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.XTRANSDATE = dbo.EXPORTSLABMASTER.SLABMDATE INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON 
                      dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID LEFT OUTER JOIN
                      dbo.CATEGORYMASTER ON dbo.VW_EXPORT_RATECARDMASTER_FLX_ASSGN_01.CHAID = dbo.CATEGORYMASTER.CATEID





