USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_EXPORT_SHIPPINGBILLDETAILS_ASSIGN]    Script Date: 27/11/2021 17:02:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[VW_EXPORT_SHIPPINGBILLDETAILS_ASSIGN]
AS
SELECT  dbo.STUFFINGMASTER.STFMDATE,   dbo.SHIPPINGBILLDETAIL.SBMID, LTRIM(dbo.SHIPPINGBILLMASTER.SBMDNO)
                         + '(' + dbo.VW_YEAR_DETAIL_CBX_ASSGN.YRDESC + ')' as CONO , SUM(dbo.STUFFINGPRODUCTDETAIL.STFDNOP) AS STFDNOP,
						 EXPORTSHIPPINGBILLMASTER.ESBMID ,EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO,STUFFINGMASTER.STFTID
FROM            dbo.STUFFINGPRODUCTDETAIL INNER JOIN
                         dbo.STUFFINGDETAIL ON dbo.STUFFINGPRODUCTDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID INNER JOIN
                         dbo.SHIPPINGBILLDETAIL ON dbo.STUFFINGPRODUCTDETAIL.SBDID = dbo.SHIPPINGBILLDETAIL.SBDID INNER JOIN
                         dbo.SHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID INNER JOIN
                         dbo.VW_YEAR_DETAIL_CBX_ASSGN ON dbo.SHIPPINGBILLMASTER.COMPYID = dbo.VW_YEAR_DETAIL_CBX_ASSGN.COMPYID  INNER JOIN 
						 dbo.STUFFINGMASTER (NOLOCK) ON dbo.STUFFINGDETAIL.STFMID = STUFFINGDETAIL.STFMID Inner Join 
						 dbo.EXPORTSHIPPINGBILLDETAIL (NOLOCK) ON dbo.SHIPPINGBILLDETAIL.ESBMID = EXPORTSHIPPINGBILLDETAIL.ESBMID  Inner Join  
						 dbo.EXPORTSHIPPINGBILLMASTER (NOLOCK) ON dbo.EXPORTSHIPPINGBILLMASTER.ESBMID = EXPORTSHIPPINGBILLDETAIL.ESBMID 
GROUP BY  dbo.SHIPPINGBILLDETAIL.SBMID, LTRIM(dbo.SHIPPINGBILLMASTER.SBMDNO) 
                         + '(' + dbo.VW_YEAR_DETAIL_CBX_ASSGN.YRDESC + ')',EXPORTSHIPPINGBILLMASTER.ESBMID ,EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO,STUFFINGMASTER.STFTID,
						 dbo.STUFFINGMASTER.STFMDATE



GO


