USE [SCFS_ERP_DEVPT]
GO

/****** Object:  View [dbo].[VW_EXPORT_GATEOUT_CONTAINER_CBX_CHNG_ASSGN]    Script Date: 15/09/2021 12:12:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VW_ESEAL_GATEOUT_CONTAINER_CBX_CHNG_ASSGN]
AS
SELECT distinct dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
       VEHICLETICKETDETAIL.VTNO as VTNO,VEHICLETICKETDETAIL.VTDNO as VTDNO ,GATEINDETAIL.CHAID,
	   dbo.GATEINDETAIL.CHANAME AS CHANAME, isnull(dbo.VEHICLETICKETDETAIL.DRVNAME,'') as DRVNAME,
	   dbo.GATEINDETAIL.STMRID ,GATEINDETAIL.STMRNAME,GATEINDETAIL.EXPRTRID ,GATEINDETAIL.EXPRTRNAME,
	   isnull(dbo.GATEINDETAIL.CSEALNO,'') as CSEALNO,
	   isnull(dbo.VEHICLETICKETDETAIL.VTSSEALNO,'') as VTSSEALNO,
	   isnull(VEHICLETICKETDETAIL.VTTYPE,0) as VTTYPE,
	   (case when VEHICLETICKETDETAIL.VTTYPE=0 then 'CCTL' 
	         when VEHICLETICKETDETAIL.VTTYPE=1 Then 'CITPL' 
	         when VEHICLETICKETDETAIL.VTTYPE=4 Then 'KATL' 
			 when VEHICLETICKETDETAIL.VTTYPE=5 Then 'AECTPL'  end) as Port,
	   convert(varchar(10) ,dbo.GATEINDETAIL.GIDATE,105) as  GIDATE,
	   isnull(GATEINDETAIL.DRVMBLNO,'') as  DRVMBLNO,isnull(GATEINDETAIL.DRVLCNO,'') as  DRVLCNO,
	   --dbo.GATEINDETAIL.GIDATE ,	   
	   isnull(dbo.VEHICLETICKETDETAIL.TRNSPRTNAME,'') as GOTRNSPRTNAME,isnull(dbo.VEHICLETICKETDETAIL.VHLNO,'') as VHLNO 
FROM    GATEINDETAIL (nolock) Inner Join 
        VEHICLETICKETDETAIL (nolock) On GATEINDETAIL.GIDID = VEHICLETICKETDETAIL.GIDID Left Join  
		GATEOUTDETAIL (nolock) On VEHICLETICKETDETAIL.GIDID = GATEOUTDETAIL.GIDID Left Join 
		CONTAINERSIZEMASTER (nolock) On GATEINDETAIL.CONTNRSID = CONTAINERSIZEMASTER.CONTNRSID 


		 where GATEINDETAIL.SDPTID=11 and (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) 

		 

GO


