--sp_helptext VW_EXPORT_INVOICE_OPERATION_WISE_TARIFF_ASSGN
--sp_helptext VW_EXPORT_STUFF_INV_TARIFF_ASSGN


ALTER  VIEW [dbo].[VW_EXPORT_INVOICE_OPERATION_WISE_TARIFF_ASSGN]
AS
SELECT     dbo.EXPORTTARIFFMASTER.TGID, 
			--dbo.EXPORTTARIFFOPERATIONMASTER.EOPTID,
			 dbo.EXPORTTARIFFMASTER.TARIFFMID, 
                      dbo.EXPORTTARIFFMASTER.TARIFFMDESC
FROM         dbo.EXPORTTARIFFMASTER 
	--LEFT JOIN dbo.EXPORTTARIFFOPERATIONMASTER ON dbo.EXPORTTARIFFMASTER.TARIFFMID = dbo.EXPORTTARIFFOPERATIONMASTER.TARIFFMID



