-- select * from VW_EXBOND_VT_PROFORMA_INVOICE_TRANSACTION_GST_PRINT_ASSGN
-- select * from VW_EXBOND_VT_PROFORMA_INVOICE_TRANSACTION_GST_PRINT_ASSGN
CREATE VIEW dbo.VW_EXBOND_VT_PROFORMA_INVOICE_TRANSACTION_GST_PRINT_ASSGN
AS
SELECT        dbo.NEW_TMPRPT_IDS.KUSRID, dbo.NEW_TMPRPT_IDS.OPTNSTR, dbo.NEW_TMPRPT_IDS.RPTID, dbo.BONDPERFORMATRANSACTIONMASTER.TRANMID, dbo.BONDPERFORMATRANSACTIONMASTER.COMPYID, 
                         dbo.BONDPERFORMATRANSACTIONMASTER.SDPTID, dbo.BONDPERFORMATRANSACTIONMASTER.REGSTRID, dbo.BONDPERFORMATRANSACTIONMASTER.TRANBTYPE, dbo.BONDPERFORMATRANSACTIONMASTER.TRANDATE, dbo.BONDPERFORMATRANSACTIONMASTER.TRANTIME, 
                         dbo.BONDPERFORMATRANSACTIONMASTER.TRANNO, dbo.BONDPERFORMATRANSACTIONMASTER.TRANDNO, BONDPERFORMATRANSACTIONMASTER.CUSRID AS USRNAME, dbo.BONDPERFORMATRANSACTIONMASTER.TRANCHANAME, 
                         dbo.BONDPERFORMATRANSACTIONMASTER.TRANIMPRTNAME, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR1 + ' '+ dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR2+
						  ' '+ dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR3+ ' '+ dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR4 AS CHAADDR, dbo.CATEGORYMASTER.CATENAME as ACHANAME, 
						 dbo.BONDMASTER.BNDID, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANDBNDNO, 
                         dbo.BONDPERFORMATRANSACTIONDETAIL.TRANDEBNDNO, dbo.BONDPERFORMATRANSACTIONMASTER.TRANMODE, dbo.BONDPERFORMATRANSACTIONMASTER.TRANMODEDETL, dbo.BONDPERFORMATRANSACTIONMASTER.TRANREFNO, 
                         dbo.BONDPERFORMATRANSACTIONMASTER.TRANREFDATE, dbo.BONDPERFORMATRANSACTIONMASTER.TRANREFBNAME, dbo.BONDPERFORMATRANSACTIONMASTER.TRANREFAMT, 
                         dbo.BONDPERFORMATRANSACTIONMASTER.TRANGAMT + dbo.BONDPERFORMATRANSACTIONMASTER.TRAN_CGST_AMT + dbo.BONDPERFORMATRANSACTIONMASTER.TRAN_SGST_AMT + dbo.BONDPERFORMATRANSACTIONMASTER.TRAN_IGST_AMT + dbo.BONDPERFORMATRANSACTIONMASTER.TRANROAMT
                          AS TRANNAMT, dbo.BONDPERFORMATRANSACTIONMASTER.TRANRMKS, dbo.BONDPERFORMATRANSACTIONMASTER.TRANAMTWRDS, dbo.BONDPERFORMATRANSACTIONMASTER.TRANGAMT, dbo.BONDGODOWNMASTER.GWNDESC, 
                         dbo.BONDGODOWNMASTER.GWNADDR, dbo.BONDMASTER.BNDDNO, dbo.BONDMASTER.BNDDATE, dbo.BONDMASTER.BNDADATE, --dbo.BONDMASTER.BNDDNO, dbo.BONDMASTER.BNDDATE, dbo.BONDMASTER.BNDNOP, 
						 dbo.BONDMASTER.BNDNOP, dbo.BONDPERFORMATRANSACTIONDETAIL.SLABTID, dbo.BONDSLABTYPEMASTER.SLABTDESC, dbo.BONDSLABTYPEMASTER.DISPORDER, 
                         dbo.BONDPERFORMATRANSACTIONDETAIL.TRANCTYPE, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANOTYPE, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANCDATE, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANHTYPE, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANSFDATE, 
                         dbo.BONDPERFORMATRANSACTIONDETAIL.TRANSEDATE, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANIFDATE, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANIEDATE, dbo.BONDMASTER.BNDSPC, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANDQTY, 
                         dbo.BONDPERFORMATRANSACTIONDETAIL.TRANDNOP, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANDCIFAMT, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANDDTYAMT, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANDINSAMT, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANDEIAMT, 
                         dbo.BONDPERFORMATRANSACTIONDETAIL.TRANDRATE, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANDGAMT, dbo.BONDPERFORMATRANSACTIONDETAIL.TRANDNAMT, dbo.EXBONDMASTER.EBNDASSAMT, dbo.EXBONDMASTER.EBNDDTYAMT, 
                         dbo.BONDMASTER.BNDINSAMT, dbo.BONDMASTER.BNDCIFAMT, dbo.BONDMASTER.BNDDTYAMT,  dbo.EXBONDMASTER.EBNDBENO, dbo.EXBONDMASTER.EBNDINSAMT,
                         dbo.BONDMASTER.BNDBEDATE, dbo.CATEGORYMASTER.CATENAME AS TRANREFNAME, dbo.BONDMASTER.BNDTDATE, dbo.BONDPERFORMATRANSACTIONDETAIL.RCOLDESC1, 
                         dbo.BONDPERFORMATRANSACTIONDETAIL.RCOLDESC2, dbo.BONDPERFORMATRANSACTIONDETAIL.RCOLDESC3, dbo.BONDPERFORMATRANSACTIONDETAIL.RCOLDESC4, dbo.BONDMASTER.BND20, dbo.BONDMASTER.BND40, dbo.BONDMASTER.BNDBLNO, 
                         dbo.BONDMASTER.BNDBENO, dbo.STATEMASTER.STATEDESC, dbo.STATEMASTER.STATECODE, ISNULL(dbo.BONDPERFORMATRANSACTIONMASTER.TRANGSTNO, dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO) AS CATEGSTNO, 
                         dbo.BONDPERFORMATRANSACTIONMASTER.TRANLMNO, dbo.BONDPERFORMATRANSACTIONMASTER.IRNNO, dbo.BONDPERFORMATRANSACTIONMASTER.ACKNO, dbo.BONDPERFORMATRANSACTIONMASTER.ACKDT, dbo.BONDPERFORMATRANSACTIONMASTER.QRCODEPATH, 
                         dbo.BONDPERFORMATRANSACTIONMASTER.TRAN_CGST_AMT, dbo.BONDPERFORMATRANSACTIONMASTER.TRAN_SGST_AMT, dbo.BONDPERFORMATRANSACTIONMASTER.TRAN_IGST_AMT,
						 DBO.CATEGORYMASTER.CATELICNO, BONDPERFORMATRANSACTIONMASTER.TRANBILLREFNO,EXBONDMASTER.EBNDDATE,EXBONDMASTER.EBNDBEDATE,
						 CurVTQty,BalVTQty,
						 dbo.COMPANYBANKMASTER.CBANKMDESC, dbo.COMPANYBANKMASTER.CBANKMACCODE, dbo.COMPANYBANKMASTER.CBANKMIFSCCODE, dbo.COMPANYBANKMASTER.CBANKMBRANCHNAME,
						 BONDPERFORMATRANSACTIONMASTER.TAXTYPE, BONDPERFORMATRANSACTIONDETAIL.BILLDESC,
						 case when BONDPERFORMATRANSACTIONMASTER.TAXTYPE = 1 then 'TAX INVOICE' else 'BILL OF SUPPLY' end 'TaxInvHeading',
						 BONDVEHICLETICKETDETAIL.VTAREA, ActualBalQTY1-TRANDNOP 'BNDBALNOP', EXBONDMASTER.EBNDNOP,
						 isnull(BONDPERFORMATRANSACTIONDETAIL.EXBNDVTSPC,isnull(BONDVEHICLETICKETDETAIL.VTAREA,0)) EXBNDVTSPC,
						 UptoLastInvQTY, ActualBalQTY1, ActualBalQTY1 ActualBalQTY2
FROM            dbo.NEW_TMPRPT_IDS INNER JOIN
                         dbo.BONDPERFORMATRANSACTIONMASTER ON dbo.NEW_TMPRPT_IDS.RPTID = dbo.BONDPERFORMATRANSACTIONMASTER.TRANMID INNER JOIN
                         dbo.BONDPERFORMATRANSACTIONDETAIL ON dbo.BONDPERFORMATRANSACTIONMASTER.TRANMID = dbo.BONDPERFORMATRANSACTIONDETAIL.TRANMID INNER JOIN
                         dbo.BONDMASTER ON dbo.BONDPERFORMATRANSACTIONDETAIL.BNDID = dbo.BONDMASTER.BNDID INNER JOIN  
						 dbo.EXBONDMASTER ON dbo.BONDPERFORMATRANSACTIONDETAIL.EBNDID = dbo.EXBONDMASTER.EBNDID INNER JOIN  
						 dbo.CATEGORYMASTER ON dbo.BONDPERFORMATRANSACTIONMASTER.BILLREFID = dbo.CATEGORYMASTER.CATEID INNER JOIN
						 dbo.CATEGORY_ADDRESS_DETAIL ON dbo.CATEGORYMASTER.CATEID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID 
						 AND BONDPERFORMATRANSACTIONMASTER.BCATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.BONDPERFORMATRANSACTIONMASTER.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                         dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID LEFT OUTER JOIN
						 dbo.COMPANYBANKMASTER ON dbo.COMPANYMASTER.COMPID = dbo.COMPANYBANKMASTER.COMPID LEFT OUTER JOIN
                         dbo.STATEMASTER ON dbo.CATEGORY_ADDRESS_DETAIL.STATEID = dbo.STATEMASTER.STATEID LEFT JOIN                         
                         dbo.BONDSLABTYPEMASTER ON dbo.BONDPERFORMATRANSACTIONDETAIL.SLABTID = dbo.BONDSLABTYPEMASTER.SLABTID LEFT JOIN
                         dbo.BONDGODOWNMASTER ON dbo.BONDMASTER.GWNID = dbo.BONDGODOWNMASTER.GWNID left join
						 VW_VT_Bal_NOP (nolock) on BONDPERFORMATRANSACTIONDETAIL.BNDID = VW_VT_Bal_NOP.BNDID and 						 
						 BONDPERFORMATRANSACTIONDETAIL.TRANMID = VW_VT_Bal_NOP.TRANMID
						 left join
						 BONDVEHICLETICKETDETAIL (nolock) on (BONDPERFORMATRANSACTIONDETAIL.VTDID = BONDVEHICLETICKETDETAIL.VTDID or  
						  BONDPERFORMATRANSACTIONDETAIL.VTDID = 0 ) and
						 BONDPERFORMATRANSACTIONDETAIL.EBNDID = BONDVEHICLETICKETDETAIL.EBNDID
						 
						 


