-- SELECT TOP 5 * FROM VW_EXPORT_GATEOUT_CONTAINER_CBX_ASSGN
ALTER VIEW dbo.VW_EXPORT_GATEOUT_CONTAINER_CBX_ASSGN
AS
SELECT     dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO, VEHICLETICKETDETAIL.VTDNO, VEHICLETICKETDETAIL.VTDID, GATEOUTDETAIL.GODID
FROM         dbo.STUFFINGDETAIL (NOLOCK) INNER JOIN
                      dbo.GATEINDETAIL  (NOLOCK)  ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                      dbo.AUTHORIZATIONSLIPDETAIL  (NOLOCK)  INNER JOIN
                      dbo.VEHICLETICKETDETAIL  (NOLOCK)  ON dbo.AUTHORIZATIONSLIPDETAIL.ASLDID = dbo.VEHICLETICKETDETAIL.ASLDID ON 
                      dbo.STUFFINGDETAIL.STFDID = dbo.AUTHORIZATIONSLIPDETAIL.STFDID LEFT OUTER JOIN
                      dbo.GATEOUTDETAIL  (NOLOCK)  ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID
WHERE     (dbo.GATEINDETAIL.SDPTID = 2) AND (dbo.GATEINDETAIL.GPSTYPE IN (4, 5)) AND (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) AND 
                      (dbo.GATEINDETAIL.GIDATE >= CONVERT(DATETIME, '2012-04-01 00:00:00', 102)) AND (dbo.GATEINDETAIL.DISPSTATUS = 0)



