USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_ASL_IGMNO_CONTAINER_CBX_ASSGN_02]    Script Date: 19/11/2021 16:01:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE  VIEW [dbo].[VW_EXPORT_SHIPPLINGBILLCOUNT_DEATILS_ASSGN]
AS
SELECT  STUFFINGDETAIL.GIDID,EXPORTSHIPPINGBILLMASTER.ESBMID,EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO,
CATEGORYMASTER.CATENAME,Isnull(EXPT.CATENAME,'') AS ExporterName,

SHIPPINGBILLMASTER.SBMID,STUFFINGMASTER.STFMID,  STUFFINGDETAIL.STFDID,
TRANSACTIONMASTER.TRANMID
 FROM  GATEINDETAIL (nolock) Inner Join 
EXPORTSHIPPINGBILLMASTER (nolock) on EXPORTSHIPPINGBILLMASTER.ESBMID = GATEINDETAIL.ESBMID Inner Join 
EXPORTSHIPPINGBILLDETAIL (nolock) on EXPORTSHIPPINGBILLMASTER.ESBMID = EXPORTSHIPPINGBILLDETAIL.ESBMID Inner Join 
SHIPPINGBILLDETAIL (nolock) on EXPORTSHIPPINGBILLDETAIL.ESBMID = SHIPPINGBILLDETAIL.ESBMID Inner Join 
SHIPPINGBILLMASTER (nolock) on SHIPPINGBILLDETAIL.SBMID = SHIPPINGBILLMASTER.SBMID Inner Join  
STUFFINGDETAIL (nolock) on SHIPPINGBILLDETAIL.GIDID = STUFFINGDETAIL.GIDID  Inner Join 
STUFFINGMASTER (nolock) on STUFFINGMASTER.STFMID = STUFFINGDETAIL.STFMID Inner Join 
TRANSACTIONDETAIL (nolock) on TRANSACTIONDETAIL.STFDID = STUFFINGDETAIL.STFDID Inner Join 
TRANSACTIONMASTER (nolock) on TRANSACTIONDETAIL.TRANMID = TRANSACTIONMASTER.TRANMID Inner Join 
CATEGORYMASTER (nolock) on CATEGORYMASTER.CATEID = GATEINDETAIL.CHAID Left Join 
CATEGORYMASTER EXPT (nolock) on GATEINDETAIL.EXPRTRID = EXPT.CATEID 
GROUP BY STUFFINGDETAIL.GIDID,EXPORTSHIPPINGBILLMASTER.ESBMID,SHIPPINGBILLMASTER.SBMID,STUFFINGMASTER.STFMID,STUFFINGDETAIL.STFDID,
TRANSACTIONMASTER.TRANMID,EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO ,CATEGORYMASTER.CATENAME,EXPT.CATENAME,EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO

GO


