USE [SCFS_ERP_DEVPT]
GO

/****** Object:  View [dbo].[VW_ESEAL_GATEINDETAIL_CONTAINERNO]    Script Date: 14/09/2021 14:34:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_ESEAL_GATEINDETAIL_CONTAINERNO]
AS
SELECT        dbo.GATEINDETAIL.CONTNRNO, dbo.GATEINDETAIL.GIDID
FROM            dbo.GATEINDETAIL LEFT OUTER JOIN
                         dbo.VEHICLETICKETDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.VEHICLETICKETDETAIL.GIDID
WHERE        (ISNULL(dbo.VEHICLETICKETDETAIL.GIDID, 0) = 0) AND (dbo.GATEINDETAIL.SDPTID = 11)
GROUP BY dbo.GATEINDETAIL.CONTNRNO, dbo.GATEINDETAIL.GIDID

GO


