USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_EXPORT_VEHICLE_TICKET_MOD_ASSGN]    Script Date: 10/08/2021 12:38:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_EXPORT_VEHICLE_TICKET_MOD_ASSGN]
AS
SELECT     dbo.VEHICLETICKETDETAIL.VTDID, dbo.VEHICLETICKETDETAIL.COMPYID, dbo.VEHICLETICKETDETAIL.SDPTID, dbo.VEHICLETICKETDETAIL.VTDATE, 
                      dbo.VEHICLETICKETDETAIL.VTTIME, dbo.VEHICLETICKETDETAIL.VTNO, dbo.VEHICLETICKETDETAIL.VTDNO, dbo.VEHICLETICKETDETAIL.ASLDID, 
                      dbo.VEHICLETICKETDETAIL.VHLNO, dbo.VEHICLETICKETDETAIL.DRVNAME, dbo.VEHICLETICKETDETAIL.VTDESC, dbo.VEHICLETICKETDETAIL.VTQTY, 
                      dbo.VEHICLETICKETDETAIL.VTTYPE, dbo.VEHICLETICKETDETAIL.VTSTYPE, dbo.VEHICLETICKETDETAIL.VTREMRKS, dbo.VEHICLETICKETDETAIL.GIDID, 
                      dbo.VEHICLETICKETDETAIL.EGIDID, dbo.VEHICLETICKETDETAIL.CUSRID, dbo.VEHICLETICKETDETAIL.LMUSRID, dbo.VEHICLETICKETDETAIL.DISPSTATUS, 
                      dbo.VEHICLETICKETDETAIL.PRCSDATE, dbo.VEHICLETICKETDETAIL.VTSSEALNO, dbo.VEHICLETICKETDETAIL.VTCTYPE, dbo.VEHICLETICKETDETAIL.CGIDID, 
                      dbo.VEHICLETICKETDETAIL.STFDID, dbo.VEHICLETICKETDETAIL.EVLDATE, dbo.VEHICLETICKETDETAIL.EVSDATE, dbo.VEHICLETICKETDETAIL.ELRDATE, 
                      dbo.GATEINDETAIL.CONTNRNO
FROM         dbo.VEHICLETICKETDETAIL INNER JOIN
                      dbo.GATEINDETAIL ON dbo.VEHICLETICKETDETAIL.GIDID = dbo.GATEINDETAIL.GIDID

GO


