CREATE VIEW [dbo].[VW_EXPORT_TRANSACTION_ADDRESS_DETAIL_ASSGN]
AS
SELECT        dbo.TRANSACTIONMASTER.TRANMID, ISNULL(dbo.TRANSACTIONMASTER.TRANCSNAME, dbo.CATEGORYMASTER.CATEDNAME) AS TRANCSNAME, 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR1, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR1) AS TRANIMPADDR1, 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR2, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR2) AS TRANIMPADDR2, 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR3, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR3) AS TRANIMPADDR3, 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR4, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR4) AS TRANIMPADDR4, dbo.SHIPPINGBILLMASTER.EXPRTNAME, 
                         CATEGORY_ADDRESS_DETAIL_1.CATEAADDR1 AS EXPRTCATEADDR1, CATEGORY_ADDRESS_DETAIL_1.CATEAADDR2 AS EXPRTCATEADDR2, 
                         CATEGORY_ADDRESS_DETAIL_1.CATEAADDR3 AS EXPRTCATEADDR3, CATEGORY_ADDRESS_DETAIL_1.CATEAADDR4 AS EXPRTCATEADDR4, 
                         dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO AS CHACATEGSTNO, CATEGORY_ADDRESS_DETAIL_1.CATEAGSTNO AS EXPRTCATEGSTNO
FROM            dbo.STUFFINGDETAIL INNER JOIN
                         dbo.TRANSACTIONDETAIL INNER JOIN
                         dbo.TRANSACTIONMASTER ON dbo.TRANSACTIONDETAIL.TRANMID = dbo.TRANSACTIONMASTER.TRANMID INNER JOIN
                         dbo.CATEGORYMASTER LEFT JOIN CATEGORY_ADDRESS_DETAIL ON CATEGORYMASTER.CATEID = CATEGORY_ADDRESS_DETAIL.CATEID 
						  ON dbo.TRANSACTIONMASTER.TRANREFID = dbo.CATEGORYMASTER.CATEID AND TRANSACTIONMASTER.CATEAID = CATEGORY_ADDRESS_DETAIL.CATEAID
						  ON dbo.STUFFINGDETAIL.STFDID = dbo.TRANSACTIONDETAIL.STFDID INNER JOIN
                         dbo.STUFFINGPRODUCTDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID INNER JOIN
                         dbo.SHIPPINGBILLDETAIL ON dbo.STUFFINGPRODUCTDETAIL.SBDID = dbo.SHIPPINGBILLDETAIL.SBDID INNER JOIN
                         dbo.SHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID INNER JOIN
                         dbo.CATEGORYMASTER AS CATEGORYMASTER_1 LEFT JOIN CATEGORY_ADDRESS_DETAIL AS CATEGORY_ADDRESS_DETAIL_1 ON CATEGORYMASTER_1.CATEID = CATEGORY_ADDRESS_DETAIL_1.CATEID 
						  ON dbo.SHIPPINGBILLMASTER.EXPRTID = CATEGORYMASTER_1.CATEID --AND SHIPPINGBILLMASTER.CATEAID = CATEGORY_ADDRESS_DETAIL.CATEAID
						  
GROUP BY dbo.TRANSACTIONMASTER.TRANMID, ISNULL(dbo.TRANSACTIONMASTER.TRANCSNAME, dbo.CATEGORYMASTER.CATEDNAME), 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR1, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR1), ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR2, 
                         dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR2), ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR3, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR3), 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR4, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR4), CATEGORY_ADDRESS_DETAIL_1.CATEAADDR1, 
                         CATEGORY_ADDRESS_DETAIL_1.CATEAADDR2, CATEGORY_ADDRESS_DETAIL_1.CATEAADDR3, CATEGORY_ADDRESS_DETAIL_1.CATEAADDR4, dbo.SHIPPINGBILLMASTER.EXPRTNAME, 
                         dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO, CATEGORY_ADDRESS_DETAIL_1.CATEAGSTNO


