
-- select * from [VW_EXPORT_CONT_STUFFING_DETAIL_ASSGN] where gidid = 63817
ALTER VIEW [dbo].[VW_EXPORT_CONT_STUFFING_DETAIL_ASSGN]
AS
SELECT    dbo.STUFFINGDETAIL.STFTYPE, ISNULL(EXPORTSHIPPINGBILLDETAIL.PRDTDESC ,'') AS PRDTDESC, dbo.STUFFINGPRODUCTDETAIL.STFPID, dbo.STUFFINGDETAIL.STFDID, 
                      dbo.STUFFINGPRODUCTDETAIL.SBDID, dbo.STUFFINGPRODUCTDETAIL.STFDNOP, dbo.STUFFINGPRODUCTDETAIL.STFCORDNO, 
                      dbo.STUFFINGPRODUCTDETAIL.STFDQTY, dbo.STUFFINGPRODUCTDETAIL.STFDSBDATE, dbo.STUFFINGPRODUCTDETAIL.STFDSBDDATE, 
                      dbo.STUFFINGPRODUCTDETAIL.STFDSBDNO, dbo.STUFFINGPRODUCTDETAIL.STFDSBNO, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGDETAIL.GIDID, 
                      dbo.STUFFINGMASTER.CHAID, ISNULL(EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO,'-') AS  ESBD_SBILLNO, 
					  ISNULL(CONVERT(VARCHAR(10),EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLDATE,103),'') AS ESBD_SBILLDATE ,
					  ISNULL(EXPORTSHIPPINGBILLDETAIL.ESBMNOP,0) AS ESBMNOP, ISNULL(SHIPPINGBILLMASTER.SBMDNO ,'') AS SBMDNO,
					  GATEINDETAIL.CONTNRNO ,SHIPPINGBILLDETAIL.TRUCKNO,ISNULL(AUTHORIZATIONSLIPMASTER.ASLMDNO ,'') AS ASLMDNO,
					  ISNULL(CONVERT(VARCHAR(10),AUTHORIZATIONSLIPMASTER.ASLMDATE,103),'') AS ASLMDATE, 
					  ISNULL(VEHICLETICKETDETAIL.VTDNO ,'') AS VTDNO,ISNULL(CONVERT(VARCHAR(10),VEHICLETICKETDETAIL.VTDATE,103),'') AS VTDATE
FROM         dbo.GATEINDETAIL   (NOLOCK)  INNER JOIN   
                      dbo.STUFFINGDETAIL (NOLOCK) ON dbo.GATEINDETAIL.GIDID = dbo.STUFFINGDETAIL.GIDID INNER JOIN
                      dbo.STUFFINGPRODUCTDETAIL  (NOLOCK) ON  dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID INNER JOIN
                      dbo.STUFFINGMASTER  (NOLOCK) ON  dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID LEFT JOIN 
					  dbo.SHIPPINGBILLDETAIL  (NOLOCK) ON   dbo.STUFFINGPRODUCTDETAIL.SBDID = dbo.SHIPPINGBILLDETAIL.SBDID LEFT JOIN
					  dbo.SHIPPINGBILLMASTER  (NOLOCK) ON   dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID LEFT JOIN
					  dbo.EXPORTSHIPPINGBILLDETAIL  (NOLOCK) ON   dbo.STUFFINGPRODUCTDETAIL.ESBDID = dbo.EXPORTSHIPPINGBILLDETAIL.ESBDID Left Join 
					  dbo.AUTHORIZATIONSLIPDETAIL (NOLOCK) ON  dbo.STUFFINGDETAIL.GIDID = dbo.AUTHORIZATIONSLIPDETAIL.GIDID  Left Join 
					  dbo.AUTHORIZATIONSLIPMASTER (NOLOCK) ON dbo.AUTHORIZATIONSLIPDETAIL.ASLMID = dbo.AUTHORIZATIONSLIPMASTER.ASLMID  Left Join 
					  dbo.VEHICLETICKETDETAIL (NOLOCK) ON  dbo.AUTHORIZATIONSLIPDETAIL.ASLDID = dbo.VEHICLETICKETDETAIL.ASLDID 


GROUP BY    dbo.EXPORTSHIPPINGBILLDETAIL.PRDTDESC, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGPRODUCTDETAIL.STFPID, dbo.STUFFINGDETAIL.STFDID, 
                      dbo.STUFFINGPRODUCTDETAIL.SBDID, dbo.STUFFINGPRODUCTDETAIL.STFDNOP, dbo.STUFFINGPRODUCTDETAIL.STFCORDNO, 
                      dbo.STUFFINGPRODUCTDETAIL.STFDQTY, dbo.STUFFINGPRODUCTDETAIL.STFDSBDATE, dbo.STUFFINGPRODUCTDETAIL.STFDSBDDATE, 
                      dbo.STUFFINGPRODUCTDETAIL.STFDSBDNO, dbo.STUFFINGPRODUCTDETAIL.STFDSBNO, dbo.STUFFINGDETAIL.STFTYPE, dbo.STUFFINGDETAIL.GIDID, 
                      dbo.STUFFINGMASTER.CHAID, EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO, EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLDATE ,
					  EXPORTSHIPPINGBILLDETAIL.ESBMNOP, SHIPPINGBILLMASTER.SBMDNO , GATEINDETAIL.CONTNRNO,SHIPPINGBILLDETAIL.TRUCKNO,
					  AUTHORIZATIONSLIPMASTER.ASLMDNO,AUTHORIZATIONSLIPMASTER.ASLMDATE,VEHICLETICKETDETAIL.VTDNO,VEHICLETICKETDETAIL.VTDATE




