USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_EXPORT_ASL_STUFF_CONTAINER_CBX_ASSGN_NEW]    Script Date: 12/10/2021 11:52:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_EXPORT_ASL_STUFF_CONTAINER_CBX_ASSGN_NEW]
AS

SELECT    dbo.GATEINDETAIL.CONTNRNO, dbo.STUFFINGDETAIL.STFDID, dbo.STUFFINGDETAIL.GIDID  
FROM         dbo.GATEINDETAIL (nolock) INNER JOIN
                      dbo.STUFFINGDETAIL (nolock)  ON dbo.GATEINDETAIL.GIDID = dbo.STUFFINGDETAIL.GIDID LEFT OUTER JOIN
                      dbo.VW_EXPORT_ASL_STUFF_CONTAINER_CBX_ASSGN_02  (nolock)  ON 
                      dbo.STUFFINGDETAIL.STFDID = dbo.VW_EXPORT_ASL_STUFF_CONTAINER_CBX_ASSGN_02.STFDID LEFT OUTER JOIN
                      dbo.GATEOUTDETAIL (nolock)  ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID
WHERE     (dbo.GATEINDETAIL.SDPTID = 2) AND (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) AND 
                      (ISNULL(dbo.VW_EXPORT_ASL_STUFF_CONTAINER_CBX_ASSGN_02.ASLDID, 0) = 0) 

GO


