USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_EXPORT_STUFF_INVOICE_PRINT_08]    Script Date: 04-08-2021 14:27:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VW_EXPORT_STUFF_INVOICE_PRINT_08]
AS
SELECT        dbo.TRANSACTIONMASTER.TRANMID, dbo.STUFFINGMASTER.STFBILLREFNAME
FROM            dbo.STUFFINGMASTER INNER JOIN
                         dbo.TRANSACTIONDETAIL INNER JOIN
                         dbo.TRANSACTIONMASTER ON dbo.TRANSACTIONDETAIL.TRANMID = dbo.TRANSACTIONMASTER.TRANMID INNER JOIN
                         dbo.STUFFINGDETAIL ON dbo.TRANSACTIONDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID ON 
                         dbo.STUFFINGMASTER.STFMID = dbo.STUFFINGDETAIL.STFMID
WHERE        (dbo.TRANSACTIONMASTER.SDPTID = 2)
GROUP BY dbo.TRANSACTIONMASTER.TRANMID, dbo.STUFFINGMASTER.STFBILLREFNAME



GO


