USE [SCFS_ERP_DEVPT]
GO

/****** Object:  View [dbo].[VW_ESEAL_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01]    Script Date: 16/09/2021 17:44:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [dbo].[VW_ESEAL_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01]
AS
SELECT     dbo.TRANSACTIONDETAIL.TRANDID, dbo.TRANSACTIONMASTER.TRANREFID
FROM         dbo.TRANSACTIONDETAIL INNER JOIN
                      dbo.TRANSACTIONMASTER ON dbo.TRANSACTIONDETAIL.TRANMID = dbo.TRANSACTIONMASTER.TRANMID
WHERE     (dbo.TRANSACTIONMASTER.DISPSTATUS = 0) AND (dbo.TRANSACTIONMASTER.SDPTID = 11)


GO


