ALTER VIEW [dbo].[VW_FINANCE_CREDITNOTE_PRINT]
AS
SELECT        dbo.COMPANYMASTER.COMPDNAME, dbo.COMPANYMASTER.COMPADDR, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANMID, dbo.CREDITNOTE_TRANSACTIONMASTER.SDPTID, 
                         dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDID, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANDATE, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANTIME, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANBTYPE, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANDNO, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANNO, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFID, dbo.CREDITNOTE_TRANSACTIONMASTER.REGSTRID, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANMODE, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFNO, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFBNAME, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFDATE, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANMODEDETL, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANNARTN, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANRMKS, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFNAME, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDREFNAME, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFAMT, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDREFNO, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANGAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANSAMT, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANHAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANNAMT, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDREFID, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANAMTWRDS, 
                         dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANIDATE, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANSDATE, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANEDATE, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANVDATE, 
                         dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDQTY, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDRATE, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDWGHT, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDGAMT, 
                         dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDSAMT, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDHAMT, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDNAMT, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANVHLFROM, 
                         dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANVHLTO, dbo.CREDITNOTE_TRANSACTIONMASTER.CUSRID, dbo.CREDITNOTE_TRANSACTIONMASTER.LMUSRID, dbo.CREDITNOTE_TRANSACTIONMASTER.CUSRID AS USRNAME, 
                         dbo.COMPANYMASTER.COMPPDESC1, dbo.COMPANYMASTER.COMPPDESC2, dbo.TMPRPT_IDS.KUSRID, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANBILLREFNO, dbo.STATEMASTER.STATEDESC, 
                         dbo.STATEMASTER.STATECODE, dbo.CREDITNOTE_TRANSACTIONMASTER.STRG_HSNCODE, dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_HSNCODE, dbo.CREDITNOTE_TRANSACTIONMASTER.STRG_TAXABLE_AMT, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_TAXABLE_AMT, dbo.CREDITNOTE_TRANSACTIONMASTER.STRG_CGST_EXPRN, dbo.CREDITNOTE_TRANSACTIONMASTER.STRG_SGST_EXPRN, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.STRG_IGST_EXPRN, dbo.CREDITNOTE_TRANSACTIONMASTER.STRG_CGST_AMT, dbo.CREDITNOTE_TRANSACTIONMASTER.STRG_SGST_AMT, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.STRG_IGST_AMT, dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_CGST_EXPRN, dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_SGST_EXPRN, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_IGST_EXPRN, dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_CGST_AMT, dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_SGST_AMT, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_IGST_AMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANCGSTAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANSGSTAMT, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANIGSTAMT, dbo.COMPANYMASTER.COMPGSTNO, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR1, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR2, 
                         dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR3, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR4, dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDDESC, 
                         dbo.CREDITNOTE_TYPEMASTER.CNTDESC, dbo.SOFT_DEPARTMENTMASTER.SDPTNAME, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRAND_STRG_CGST_EXPRN, 
                         dbo.CREDITNOTE_TRANSACTIONDETAIL.TRAND_STRG_SGST_EXPRN, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRAND_STRG_IGST_EXPRN, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRAND_STRG_CGST_AMT, 
                         dbo.CREDITNOTE_TRANSACTIONDETAIL.TRAND_STRG_SGST_AMT, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRAND_STRG_IGST_AMT, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRAND_HANDL_CGST_EXPRN, 
                         dbo.CREDITNOTE_TRANSACTIONDETAIL.TRAND_HANDL_SGST_EXPRN, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRAND_HANDL_IGST_EXPRN, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRAND_HANDL_CGST_AMT, 
                         dbo.CREDITNOTE_TRANSACTIONDETAIL.TRAND_HANDL_SGST_AMT, dbo.CREDITNOTE_TRANSACTIONDETAIL.TRAND_HANDL_IGST_AMT,
						 DBO.CREDITNOTE_TRANSACTIONMASTER.ACKNO, DBO.CREDITNOTE_TRANSACTIONMASTER.ACKDT, DBO.CREDITNOTE_TRANSACTIONMASTER.IRNNO, DBO.CREDITNOTE_TRANSACTIONMASTER.QRCODEPATH
FROM            dbo.CREDITNOTE_TRANSACTIONDETAIL INNER JOIN
                         dbo.CREDITNOTE_TRANSACTIONMASTER ON dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANMID = dbo.CREDITNOTE_TRANSACTIONMASTER.TRANMID INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.CREDITNOTE_TRANSACTIONMASTER.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                         dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID INNER JOIN
                         dbo.TMPRPT_IDS ON dbo.CREDITNOTE_TRANSACTIONMASTER.TRANMID = dbo.TMPRPT_IDS.RPTID INNER JOIN
                         dbo.CREDITNOTE_TYPEMASTER ON dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDREFID = dbo.CREDITNOTE_TYPEMASTER.CNTID INNER JOIN
                         dbo.SOFT_DEPARTMENTMASTER ON dbo.CREDITNOTE_TRANSACTIONMASTER.SDPTID = dbo.SOFT_DEPARTMENTMASTER.SDPTID LEFT OUTER JOIN
                         dbo.STATEMASTER ON dbo.CREDITNOTE_TRANSACTIONMASTER.STATEID = dbo.STATEMASTER.STATEID LEFT OUTER JOIN
                         dbo.CATEGORY_ADDRESS_DETAIL ON dbo.CREDITNOTE_TRANSACTIONMASTER.CATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID


