USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_GATEOUT_DETAIL_CHECK_ASSGN_01]    Script Date: 04/09/2021 17:23:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_GATEOUT_DETAIL_CHECK_ASSGN_01]
AS
SELECT     dbo.TRANSACTIONMASTER.*
FROM         dbo.TRANSACTIONMASTER
WHERE     (DISPSTATUS = 0) AND (SDPTID = 1) AND (REGSTRID IN (1, 2, 6))

GO


