-- select * from VW_GEN_VHLNO_DUPLICATE_CTRL_CHK where vhlno = 'TN04AC5864'
ALTER VIEW DBO.VW_GEN_VHLNO_DUPLICATE_CTRL_CHK 
AS 
SELECT	GATEINDETAIL.COMPYID , GATEINDETAIL.SDPTID, GATEINDETAIL.GIDID, GATEINDETAIL.VHLNO, 
		CASE WHEN ISNULL(GATEOUTDETAIL.GIDID,0) = 0 THEN 'OUT' ELSE 'IN' END AS 'VHLSTS'
FROM	GATEINDETAIL 
		LEFT JOIN		GATEOUTDETAIL ON GATEINDETAIL.GIDID = GATEOUTDETAIL.GIDID 
				AND		GATEINDETAIL.VHLNO = GATEOUTDETAIL.VHLNO
				AND		GATEINDETAIL.SDPTID = GATEOUTDETAIL.SDPTID
				AND		GATEINDETAIL.COMPYID = GATEOUTDETAIL.COMPYID
				AND		GATEINDETAIL.GITIME < GATEOUTDETAIL.GOTIME
WHERE	ISNULL(GATEINDETAIL.VHLNO,'-') <> '-'
AND		ISNULL(GATEINDETAIL.VHLNO,'') <> ''
and  ISNULL(GATEOUTDETAIL.GIDID,0) = 0

/*
select * from gateindetail where vhlno in ('TN04AC5864')
select * from GATEOUTDETAIL where vhlno in ('TN04AC5864')

select * from gateindetail where vhlno in ('TN21B4559')
select * from GATEOUTDETAIL where vhlno in ('TN21B4559')
*/