alter VIEW [dbo].[VW_GATEIN_BLOCK_CONTNRNO_ASSGN]
AS
SELECT CONTNRNO,GATEINDETAIL.GIDID,CONTNRSID,GPLNO,VOYNO,IGMNO,VSLNAME,IMPRTNAME,STMRNAME,Isnull(Convert(varchar(10),GATEINDETAIL.GIDATE,103),'') AS   GIDATE,
GBDID , isnull(OPENSHEETDETAIL.GIDID,0) 'OSGID'
FROM GATEINDETAIL LEFT OUTER JOIN 
       VW_GATEIN_BLOCK_DETAILS_01 ON GATEINDETAIL.GIDID=VW_GATEIN_BLOCK_DETAILS_01.GIDID
	   left join OPENSHEETDETAIL on GATEINDETAIL.GIDID=OPENSHEETDETAIL.GIDID
WHERE  CONTNRID=1  AND SDPTID=1 and ISNULL(GBDID,0)=0


