USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_GATEIN_BLOCK_DETAILS]    Script Date: 04/09/2021 17:30:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_GATEIN_BLOCK_DETAILS]
AS
SELECT     GBDID, GIDID, GBTYPE
FROM         dbo.GATEIN_BLOCK_DETAILS
WHERE     (GBTYPE = 0)

GO


