USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_GATEOUT_DETAIL_CHECK_ASSGN_02]    Script Date: 31/01/2025 15:36:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_GATEOUT_DETAIL_CHECK_ASSGN_02]
AS
SELECT        TOP (100) PERCENT dbo.OPENSHEETDETAIL.GIDID, dbo.TRANSACTIONDETAIL.TRANDREFID, MAX(dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_01.TRANLMNO) AS TRANLMNO, 
                         MAX(dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_01.TRANLMDATE) AS TRANLMDATE, MAX(dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_01.TRANDNO) AS TRANDNO, 
                         MAX(dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_01.TRANDATE) AS TRANDATE, dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_01.TRANREFNAME, MAX(dbo.VW_SUPPLEMENTARY_BILL_NO_ASSGN.TRANDNO) AS STRANDNO, 
                         MAX(dbo.VW_SUPPLEMENTARY_BILL_NO_ASSGN.TRANDATE) AS STRANDATE, MAX(dbo.DELIVERYORDERMASTER.DODNO) AS DODNO, MAX(dbo.DELIVERYORDERMASTER.DODATE) AS DOMDATE, 
                         dbo.DELIVERYORDERMASTER.DOREFNAME, dbo.OPENSHEETMASTER.BOENO AS BILLEMNO, dbo.OPENSHEETMASTER.BOEDATE AS BILLEMDATE, dbo.OPENSHEETMASTER.OSMNAME, 
                         dbo.OPENSHEETMASTER.OSBILLREFNAME, dbo.OPENSHEETDETAIL.OSMID, dbo.OPENSHEETMASTER.OSMAAMT, dbo.OPENSHEETMASTER.OSMDUTYAMT, dbo.OPENSHEETMASTER.OOCNO, 
                         dbo.OPENSHEETMASTER.OOCDATE, dbo.OPENSHEETMASTER.OSMDATE, dbo.OPENSHEET_VIA_DETAILS.OSMTYPEDESC
FROM            dbo.OPENSHEETDETAIL INNER JOIN
                         dbo.BILLENTRYDETAIL ON dbo.OPENSHEETDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID INNER JOIN
                         dbo.BILLENTRYMASTER ON dbo.BILLENTRYDETAIL.BILLEMID = dbo.BILLENTRYMASTER.BILLEMID LEFT OUTER JOIN
                         dbo.OPENSHEET_VIA_DETAILS INNER JOIN
                         dbo.OPENSHEETMASTER ON dbo.OPENSHEET_VIA_DETAILS.OSMTYPE = dbo.OPENSHEETMASTER.OSMTYPE ON dbo.OPENSHEETDETAIL.OSMID = dbo.OPENSHEETMASTER.OSMID LEFT OUTER JOIN
                         dbo.TRANSACTIONDETAIL ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.TRANSACTIONDETAIL.BILLEDID LEFT OUTER JOIN
                         dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_01 ON dbo.TRANSACTIONDETAIL.TRANMID = dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_01.TRANMID LEFT OUTER JOIN
                         dbo.VW_SUPPLEMENTARY_BILL_NO_ASSGN ON dbo.TRANSACTIONDETAIL.TRANDID = dbo.VW_SUPPLEMENTARY_BILL_NO_ASSGN.TRANDAID LEFT OUTER JOIN
                         dbo.DELIVERYORDERMASTER RIGHT OUTER JOIN
                         dbo.DELIVERYORDERDETAIL ON dbo.DELIVERYORDERMASTER.DOMID = dbo.DELIVERYORDERDETAIL.DOMID ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.DELIVERYORDERDETAIL.BILLEDID
GROUP BY dbo.OPENSHEETDETAIL.GIDID, dbo.TRANSACTIONDETAIL.TRANDREFID, dbo.VW_GATEOUT_DETAIL_CHECK_ASSGN_01.TRANREFNAME, dbo.DELIVERYORDERMASTER.DOREFNAME, dbo.OPENSHEETMASTER.BOENO, 
                         dbo.OPENSHEETMASTER.BOEDATE, dbo.OPENSHEETMASTER.OSMNAME, dbo.OPENSHEETMASTER.OSBILLREFNAME, dbo.OPENSHEETDETAIL.OSMID, dbo.OPENSHEETMASTER.OSMAAMT, 
                         dbo.OPENSHEETMASTER.OSMDUTYAMT, dbo.OPENSHEETMASTER.OOCNO, dbo.OPENSHEETMASTER.OOCDATE, dbo.OPENSHEETMASTER.OSMDATE, dbo.OPENSHEET_VIA_DETAILS.OSMTYPEDESC
GO


