USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01]    Script Date: 27-07-2025 23:19:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01]
AS
SELECT        dbo.OPENSHEETDETAIL.OSDID, dbo.OPENSHEETDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.GIDATE, 
                         dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.OPENSHEETMASTER.OSMDNO, dbo.OPENSHEETMASTER.BOENO, dbo.OPENSHEETMASTER.BOEDATE, dbo.OPENSHEETMASTER.DODATE, 
                         dbo.OPENSHEETDETAIL.LSEALNO, dbo.OPENSHEETDETAIL.SSEALNO, CONVERT(varchar, dbo.OPENSHEETMASTER.OOCDATE, 103) AS OOCDATE
FROM            dbo.OPENSHEETDETAIL INNER JOIN
                         dbo.GATEINDETAIL ON dbo.OPENSHEETDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                         dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                         dbo.OPENSHEETMASTER ON dbo.OPENSHEETDETAIL.OSMID = dbo.OPENSHEETMASTER.OSMID LEFT OUTER JOIN
                         dbo.VW_GATEIN_BLOCK_DETAILS_01 ON dbo.GATEINDETAIL.GIDID = dbo.VW_GATEIN_BLOCK_DETAILS_01.GIDID
WHERE        (dbo.GATEINDETAIL.SDPTID = 1) AND (dbo.OPENSHEETDETAIL.INSPTYPE = 1) AND (dbo.OPENSHEETMASTER.OSMLDTYPE = 0) AND (ISNULL(dbo.VW_GATEIN_BLOCK_DETAILS_01.GBDID, 0) = 0)
GO


