USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_IMPORT_TRANSACTION_ADDRESS_DETAIL_ASSGN]    Script Date: 16-08-2021 17:42:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


alter VIEW [dbo].[VW_IMPORT_TRANSACTION_ADDRESS_DETAIL_ASSGN]
AS
SELECT        dbo.TRANSACTIONMASTER.TRANMID, ISNULL(dbo.TRANSACTIONMASTER.TRANCSNAME, dbo.CATEGORYMASTER.CATEDNAME) AS TRANCSNAME, 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR1, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR1) AS TRANIMPADDR1, 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR2, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR2) AS TRANIMPADDR2, 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR3, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR3) AS TRANIMPADDR3, 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR4, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR4) AS TRANIMPADDR4, 
						 dbo.GATEINDETAIL.IMPRTNAME, 
                         CATEGORY_ADDRESS_DETAIL_1.CATEAADDR1 AS IMPCATEADDR1, CATEGORY_ADDRESS_DETAIL_1.CATEAADDR2 AS IMPCATEADDR2, 
                         CATEGORY_ADDRESS_DETAIL_1.CATEAADDR3 AS IMPCATEADDR3, CATEGORY_ADDRESS_DETAIL_1.CATEAADDR4 AS IMPCATEADDR4, 
                         dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO AS CHACATEGSTNO, CATEGORY_ADDRESS_DETAIL_1.CATEAGSTNO AS IMPCATEGSTNO
FROM            dbo.TRANSACTIONDETAIL INNER JOIN
                         dbo.TRANSACTIONMASTER ON dbo.TRANSACTIONDETAIL.TRANMID = dbo.TRANSACTIONMASTER.TRANMID INNER JOIN
                         dbo.BILLENTRYDETAIL ON dbo.TRANSACTIONDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID INNER JOIN
                         dbo.GATEINDETAIL ON dbo.BILLENTRYDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                         dbo.CATEGORYMASTER ON dbo.TRANSACTIONMASTER.TRANREFID = dbo.CATEGORYMASTER.CATEID 
							LEFT JOIN CATEGORY_ADDRESS_DETAIL ON CATEGORYMASTER.CATEID = CATEGORY_ADDRESS_DETAIL.CATEID 
							AND  dbo.TRANSACTIONMASTER.CATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID 
							INNER JOIN 
                         dbo.CATEGORYMASTER AS CATEGORYMASTER_1 ON dbo.GATEINDETAIL.IMPRTID = CATEGORYMASTER_1.CATEID
							LEFT JOIN CATEGORY_ADDRESS_DETAIL AS CATEGORY_ADDRESS_DETAIL_1  ON CATEGORYMASTER_1.CATEID = CATEGORY_ADDRESS_DETAIL_1.CATEID
							AND  dbo.TRANSACTIONMASTER.CATEAID = CATEGORY_ADDRESS_DETAIL_1.CATEAID 


GO


