alter VIEW [dbo].[VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN]
AS
SELECT     dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.OSDID, dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.GIDID,  dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.GIDATE,
                      dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.CONTNRNO, dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.IGMNO, 
                      dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.GPLNO, dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.CONTNRSDESC, 
                      dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.OSMDNO, dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.BOENO, 
                      dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.BOEDATE, dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.DODATE, 
                      dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.LSEALNO, dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.SSEALNO,					  
					   Convert(varchar,VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.OOCDATE,103) OOCDATE
FROM         dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_02 RIGHT OUTER JOIN
                      dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01 ON 
                      dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_02.OSDID = dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_01.OSDID
WHERE     (ISNULL(dbo.VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_02.ASLDID, 0) = 0)


