ALTER VIEW [dbo].[VW_IMPORT_RATECARDMASTER_FLX_ASSGN]
AS
SELECT     dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.TARIFFMID, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.SLABTID, 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.CHRGETYPE, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.STMRID, 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.CONTNRSID, dbo.SLABMASTER.SLABMID, dbo.SLABMASTER.COMPYID, 
                      dbo.CATEGORYMASTER.CATEDNAME, dbo.CONTAINERSIZEMASTER.CONTNRSCODE, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.YRDTYPE, 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.SDTYPE, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.HTYPE, 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.WTYPE, dbo.SLABMASTER.SLABMIN, dbo.SLABMASTER.SLABMAX, dbo.SLABMASTER.SLABAMT, 
                      dbo.SLABMASTER.SLABMDATE, dbo.SLABMASTER.SDPTTYPEID
FROM         dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02 INNER JOIN
                      dbo.SLABMASTER ON dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.TARIFFMID = dbo.SLABMASTER.TARIFFMID AND 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.STMRID = dbo.SLABMASTER.STMRID AND 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.CHRGETYPE = dbo.SLABMASTER.CHRGETYPE AND 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.CONTNRSID = dbo.SLABMASTER.CONTNRSID AND 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.SDTYPE = dbo.SLABMASTER.SDTYPE AND 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.YRDTYPE = dbo.SLABMASTER.YRDTYPE AND 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.HTYPE = dbo.SLABMASTER.HTYPE AND 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.WTYPE = dbo.SLABMASTER.WTYPE AND 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.SLABTID = dbo.SLABMASTER.SLABTID AND 
					  dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.XTRANSDATE = dbo.SLABMASTER.SLABMDATE AND 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.SDPTTYPEID = dbo.SLABMASTER.SDPTTYPEID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID LEFT OUTER JOIN
                      dbo.CATEGORYMASTER ON dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02.STMRID = dbo.CATEGORYMASTER.CATEID


