CREATE VIEW dbo.VW_IMPORT_BILL_OPEN_SHEET_SEAL_COUNT_ASSGN_02
AS
SELECT     TOP 100 PERCENT dbo.OPENSHEETMASTER.OSMID, dbo.BILLENTRYDETAIL.BILLEMID
FROM         dbo.OPENSHEETMASTER INNER JOIN
                      dbo.OPENSHEETDETAIL ON dbo.OPENSHEETMASTER.OSMID = dbo.OPENSHEETDETAIL.OSMID INNER JOIN
                      dbo.BILLENTRYDETAIL ON dbo.OPENSHEETDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID
GROUP BY dbo.OPENSHEETMASTER.OSMID, dbo.BILLENTRYDETAIL.BILLEMID
ORDER BY dbo.OPENSHEETMASTER.OSMID, dbo.BILLENTRYDETAIL.BILLEMID