ALTER VIEW [dbo].[VW_IMPORT_GATEOUT_CONTAINER_CBX_CHNG_ASSGN]
AS
SELECT distinct dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.CONTAINERTYPEMASTER.CONTNRTCODE, 
ISNULL(VEHICLETICKETDETAIL.VTNO,0) as VTNO,ISNULL(VEHICLETICKETDETAIL.VTDNO,'') as VTDNO ,OPENSHEETMASTER.OSMNO,dbo.OPENSHEETMASTER.OSMNAME AS CHANAME, 
dbo.OPENSHEETMASTER.CHAID, isnull(dbo.VEHICLETICKETDETAIL.DRVNAME,'') as DRVNAME,isnull(dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, 0) as ASLDID,
isnull(dbo.AUTHORIZATIONSLIPDETAIL.CSEALNO,'') as CSEALNO, isnull(dbo.AUTHORIZATIONSLIPDETAIL.ASEALNO,'') as ASEALNO,                      
dbo.GATEINDETAIL.GIDATE ,isnull(dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE,0) as  ASLMTYPE, isnull(dbo.VEHICLETICKETDETAIL.TRNSPRTNAME,'') as GOTRNSPRTNAME,
isnull(dbo.VEHICLETICKETDETAIL.VHLNO,'') as VHLNO 
FROM   GATEINDETAIL (nolock) Inner Join 
     dbo.OPENSHEETDETAIL (nolock) on OPENSHEETDETAIL.GIDID = GATEINDETAIL.GIDID Inner Join 
	 dbo.OPENSHEETMASTER (nolock) on OPENSHEETMASTER.OSMID = OPENSHEETDETAIL.OSMID Inner Join 
	 dbo.CONTAINERSIZEMASTER (nolock) ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID Inner Join 
	 dbo.CONTAINERTYPEMASTER (nolock) ON dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID Inner Join 
	 dbo.AUTHORIZATIONSLIPDETAIL (nolock) ON dbo.GATEINDETAIL.GIDID = dbo.AUTHORIZATIONSLIPDETAIL.GIDID Inner Join 
	 dbo.AUTHORIZATIONSLIPMASTER (nolock) ON dbo.AUTHORIZATIONSLIPDETAIL.ASLMID = dbo.AUTHORIZATIONSLIPMASTER.ASLMID Inner Join 
	 dbo.VEHICLETICKETDETAIL (nolock) ON  dbo.VEHICLETICKETDETAIL.ASLDID = dbo.AUTHORIZATIONSLIPDETAIL.ASLDID  LEFT OUTER JOIN  
	 dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID  
	 where GATEINDETAIL.SDPTID=1  and (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) >= 0)  --and (dbo.GATEINDETAIL.GPSTYPE IN (4, 5))
	 and GATEOUTDETAIL.REGSTRID =3
       