-- select * from [VW_IMPORT_EINVOICE_TRANSACTION_GST_PRINT_ASSGN]
CREATE VIEW [dbo].[VW_IMPORT_EINVOICE_TRANSACTION_GST_PRINT_ASSGN]
AS
SELECT        dbo.NEW_TMPRPT_IDS.KUSRID, dbo.COMPANYMASTER.COMPNAME, dbo.TRANSACTIONMASTER.COMPYID, dbo.TRANSACTIONMASTER.TRANMID, dbo.TRANSACTIONMASTER.SDPTID, 
                         dbo.TRANSACTIONMASTER.REGSTRID, dbo.TRANSACTIONMASTER.TRANBTYPE, dbo.TRANSACTIONMASTER.TRANDATE, RIGHT(dbo.TRANSACTIONMASTER.TRANTIME, 8) AS TRANTIME, 
                         dbo.TRANSACTIONMASTER.TRANNO, dbo.TRANSACTIONMASTER.TRANDNO, dbo.TRANSACTIONMASTER.TRANREFNAME, dbo.TRANSACTIONMASTER.TRANMODE, dbo.TRANSACTIONMASTER.TRANMODEDETL, 
                         dbo.TRANSACTIONMASTER.TRANREFNO, dbo.TRANSACTIONMASTER.TRANREFDATE, dbo.TRANSACTIONMASTER.TRANREFBNAME, dbo.TRANSACTIONMASTER.TRANREFAMT, 
                         dbo.TRANSACTIONMASTER.TRANGAMT, dbo.TRANSACTIONMASTER.TRANSAMT, dbo.TRANSACTIONMASTER.TRANHAMT, dbo.TRANSACTIONMASTER.TRANEAMT, dbo.TRANSACTIONMASTER.TRANFAMT, 
                         dbo.TRANSACTIONMASTER.TRANAAMT, dbo.TRANSACTIONMASTER.TRANNAMT, dbo.TRANSACTIONMASTER.TRANAMTWRDS, dbo.TRANSACTIONMASTER.TRANRMKS, dbo.CATEGORYMASTER.CATEADDR, 
                         dbo.GATEINDETAIL.IMPRTNAME, dbo.GATEINDETAIL.STMRNAME, dbo.TRANSACTIONDETAIL.TRANDREFNAME, dbo.TRANSACTIONDETAIL.TRANDREFNO, dbo.BILLENTRYMASTER.BILLEMDATE, 
                         dbo.BILLENTRYMASTER.BILLEMTIME, dbo.TRANSACTIONDETAIL.TRANIDATE, dbo.TRANSACTIONDETAIL.TRANSDATE, dbo.TRANSACTIONDETAIL.TRANEDATE, dbo.TRANSACTIONDETAIL.TRANVDATE, 
                         dbo.TRANSACTIONDETAIL.RCOL1, dbo.TRANSACTIONDETAIL.RCOL2, dbo.TRANSACTIONDETAIL.RCOL3, dbo.TRANSACTIONDETAIL.RCOL4, dbo.TRANSACTIONDETAIL.RCOL5, dbo.TRANSACTIONDETAIL.RCOL6, 
                         dbo.TRANSACTIONDETAIL.RCOL7, dbo.TRANSACTIONDETAIL.RAMT1, dbo.TRANSACTIONDETAIL.RAMT2, dbo.TRANSACTIONDETAIL.RAMT3, dbo.TRANSACTIONDETAIL.RAMT4, dbo.TRANSACTIONDETAIL.RAMT5, 
                         dbo.TRANSACTIONDETAIL.RAMT6, dbo.TRANSACTIONDETAIL.RAMT7, dbo.TRANSACTIONDETAIL.TRANDQTY, dbo.TRANSACTIONDETAIL.TRANDGAMT, dbo.TRANSACTIONDETAIL.TRANDSAMT, 
                         dbo.TRANSACTIONDETAIL.TRANDHAMT, dbo.TRANSACTIONDETAIL.TRANDEAMT, dbo.TRANSACTIONDETAIL.TRANDFAMT, dbo.TRANSACTIONDETAIL.TRANDAAMT, dbo.TRANSACTIONDETAIL.TRANDNAMT, 
                         dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, dbo.BILLENTRYMASTER.BLNO, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.PRDTDESC, 
                         ISNULL(dbo.VW_TRANSACTION_DOSPRINT_ASSGN_01.BNOP, 0) AS BOENOP, ISNULL(dbo.VW_TRANSACTION_DOSPRINT_ASSGN_01.BWGHT, 0) AS BOEWGHT, dbo.GATEINDETAIL.CONTNRNO, 
                         dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.TRANSACTIONMASTER.LMUSRID, dbo.TRANSACTIONMASTER.CUSRID, dbo.TRANSACTIONMASTER.CUSRID AS USRNAME, 
                         dbo.TRANSACTIONMASTER.DISPSTATUS, dbo.SLOTMASTER.SLOTDESC, dbo.SLOTMASTER.SLOTCODE, dbo.ROWMASTER.ROWDESC, dbo.ROWMASTER.ROWCODE, dbo.GATEINDETAIL.GPWGHT, 
                         dbo.BILLENTRYDETAIL.DWGHT, dbo.DELIVERYORDERMASTER.DODNO, dbo.DELIVERYORDERMASTER.DODATE, dbo.DELIVERYORDERMASTER.DOTIME, dbo.OPENSHEETMASTER.OSMLNAME, 
                         dbo.COMPANYMASTER.COMPPDESC1, dbo.COMPANYMASTER.COMPPDESC2, dbo.CATEGORYMASTER.CATEMAIL, dbo.CATEGORYMASTER.CATEPHN1, dbo.CATEGORYMASTER.CATEPHN2, 
                         dbo.CATEGORYMASTER.CATEPHN3, dbo.CATEGORYMASTER.CATEPHN4, dbo.CONTAINERTYPEMASTER.CONTNRTDESC, dbo.VW_TRANSACTION_CRY_PRINT_ASSGN_01.COL1, 
                         dbo.VW_TRANSACTION_CRY_PRINT_ASSGN_01.COL2, dbo.TRANSACTIONMASTER.TRANNARTN, ISNULL(dbo.TRANSACTIONMASTER.TRANHBLNO, dbo.BILLENTRYMASTER.BLNO) AS TRANHBLNO, 
                         dbo.TRANSACTIONMASTER.TRANPONO, dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CHANAME, dbo.GATEINDETAIL.CLNTNAME, dbo.GATEINDETAIL.SHPRNAME, dbo.GATEINDETAIL.GPPLCNAME, 
                         dbo.TRANSACTIONMASTER.TRANIMPADDR1, dbo.TRANSACTIONMASTER.TRANIMPADDR2, dbo.TRANSACTIONMASTER.TRANIMPADDR3, dbo.TRANSACTIONMASTER.TRANIMPADDR4, 
                         dbo.TRANSACTIONDETAIL.TRANDAHAMT, dbo.TRANSACTIONMASTER.TRANAHAMT, dbo.TRANSACTIONMASTER.TRANGSTNO AS CATEBGSTNO, dbo.COMPANYMASTER.COMPGSTNO, 
                         dbo.STATEMASTER.STATEDESC, dbo.STATEMASTER.STATECODE, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_HSNCODE, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_HSNCODE, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_EXPRN, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_EXPRN, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_EXPRN, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_EXPRN, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_EXPRN, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_EXPRN, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_TAXABLE_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_TAXABLE_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.CGST_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.SGST_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.IGST_AMT, dbo.TRANSACTIONMASTER.TRANCSNAME, 
                         dbo.TRANSACTIONMASTER.TRANGSTNO, dbo.TRANSACTIONMASTER.CATEAID, dbo.OPENSHEETMASTER.OSMNAME, dbo.OPENSHEETMASTER.OSMCNAME, dbo.CATEGORYMASTER.CATENAME, 
                         dbo.CATEGORYMASTER.CATELICNO, dbo.OPENSHEETMASTER.OSMNOP, dbo.OPENSHEETMASTER.OSMWGHT, dbo.TRANSACTIONMASTER.TRAN_COVID_DISC_AMT, dbo.TRANSACTIONMASTER.IRNNO, 
                         dbo.TRANSACTIONMASTER.ACKNO, dbo.TRANSACTIONMASTER.ACKDT, dbo.TRANSACTIONMASTER.QRCODEPATH AS ImgPath
FROM            dbo.STATEMASTER RIGHT OUTER JOIN
                         dbo.CATEGORY_ADDRESS_DETAIL ON dbo.STATEMASTER.STATEID = dbo.CATEGORY_ADDRESS_DETAIL.STATEID RIGHT OUTER JOIN
                         dbo.NEW_TMPRPT_IDS INNER JOIN
                         dbo.TRANSACTIONMASTER INNER JOIN
                         dbo.TRANSACTIONDETAIL ON dbo.TRANSACTIONMASTER.TRANMID = dbo.TRANSACTIONDETAIL.TRANMID INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.TRANSACTIONMASTER.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                         dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID INNER JOIN
                         dbo.CATEGORYMASTER ON dbo.TRANSACTIONMASTER.TRANREFID = dbo.CATEGORYMASTER.CATEID INNER JOIN
                         dbo.BILLENTRYDETAIL ON dbo.TRANSACTIONDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID INNER JOIN
                         dbo.GATEINDETAIL ON dbo.BILLENTRYDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                         dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                         dbo.BILLENTRYMASTER ON dbo.BILLENTRYDETAIL.BILLEMID = dbo.BILLENTRYMASTER.BILLEMID ON dbo.NEW_TMPRPT_IDS.RPTID = dbo.TRANSACTIONMASTER.TRANMID INNER JOIN
                         dbo.CONTAINERTYPEMASTER ON dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID INNER JOIN
                         dbo.VW_TRANSACTION_CRY_PRINT_ASSGN_01 ON dbo.TRANSACTIONMASTER.TRANMID = dbo.VW_TRANSACTION_CRY_PRINT_ASSGN_01.TRANMID INNER JOIN
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01 ON dbo.TRANSACTIONMASTER.TRANMID = dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.TRANMID ON 
                         dbo.CATEGORY_ADDRESS_DETAIL.CATEAID = dbo.TRANSACTIONMASTER.CATEAID LEFT OUTER JOIN
                         dbo.STATEMASTER AS STATEMASTER_1 ON dbo.CATEGORYMASTER.STATEID = STATEMASTER_1.STATEID LEFT OUTER JOIN
                         dbo.OPENSHEETDETAIL INNER JOIN
                         dbo.OPENSHEETMASTER ON dbo.OPENSHEETDETAIL.OSMID = dbo.OPENSHEETMASTER.OSMID ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.OPENSHEETDETAIL.BILLEDID LEFT OUTER JOIN
                         dbo.DELIVERYORDERDETAIL LEFT OUTER JOIN
                         dbo.DELIVERYORDERMASTER ON dbo.DELIVERYORDERDETAIL.DOMID = dbo.DELIVERYORDERMASTER.DOMID ON 
                         dbo.BILLENTRYDETAIL.BILLEDID = dbo.DELIVERYORDERDETAIL.BILLEDID LEFT OUTER JOIN
                         dbo.ROWMASTER RIGHT OUTER JOIN
                         dbo.SLOTMASTER ON dbo.ROWMASTER.ROWID = dbo.SLOTMASTER.ROWID ON dbo.GATEINDETAIL.SLOTID = dbo.SLOTMASTER.SLOTID LEFT OUTER JOIN
                         dbo.VW_TRANSACTION_DOSPRINT_ASSGN_01 ON dbo.TRANSACTIONMASTER.TRANMID = dbo.VW_TRANSACTION_DOSPRINT_ASSGN_01.TRANMID
WHERE        (dbo.TRANSACTIONMASTER.DISPSTATUS = 0) AND (ISNULL(dbo.DELIVERYORDERMASTER.DISPSTATUS, 0) = 0) --AND (dbo.TRANSACTIONMASTER.TRANMID = 1285)

