USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_IMPORT_GATEOUT_TRUCKNO_CBX_ASSGN]    Script Date: 23/11/2021 13:02:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_IMPORT_GATEOUT_TRUCKNO_CBX_ASSGN]
AS

SELECT     TOP 100 PERCENT dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.AVHLNO
			

FROM  dbo.GATEINDETAIL (nolock) Left Join  
dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID  

 WHERE GATEINDETAIL.SDPTID=1  and (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) and (GATEINDETAIL.CONTNRSID=0)
       and dbo.GATEINDETAIL.AVHLNO is not null --and GATEINDETAIL.AVHLNO='TN04AJ8548' 

	   GROUP BY dbo.GATEINDETAIL.AVHLNO,dbo.GATEINDETAIL.GIDID
 


GO


