ALTER VIEW [dbo].[VW_IMPORT_RATECARDMASTER_FLX_ASSGN_02]
AS
SELECT     MAX(dbo.SLABMASTER.SLABMID) AS Expr1, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.SLABTID, 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.TARIFFMID, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.STMRID, 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.CHRGETYPE, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.CONTNRSID, 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.SDTYPE, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.YRDTYPE, 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.HTYPE, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.WTYPE, 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.XTRANSDATE, DBO.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.SDPTTYPEID 
FROM         dbo.SLABMASTER INNER JOIN
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01 ON dbo.SLABMASTER.TARIFFMID = dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.TARIFFMID AND 
                      dbo.SLABMASTER.SLABTID = dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.SLABTID AND 
                      dbo.SLABMASTER.SLABMDATE = dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.XTRANSDATE AND
					  dbo.SLABMASTER.SDPTTYPEID = dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.SDPTTYPEID  
GROUP BY dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.SLABTID, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.TARIFFMID, 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.STMRID, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.CHRGETYPE, 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.CONTNRSID, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.SDTYPE, 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.YRDTYPE, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.HTYPE, 
                      dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.WTYPE, dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.XTRANSDATE,
					  dbo.VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01.SDPTTYPEID


