alter VIEW [dbo].[VW_IMPORT_PERFORMA_INVOICE_BOE_CONTAINER_NO_CBX_ASSGN_01]
AS
SELECT     dbo.PERFORMA_TRANSACTIONDETAIL.TRANDID, dbo.PERFORMA_TRANSACTIONDETAIL.BILLEDID
FROM         dbo.PERFORMA_TRANSACTIONDETAIL (nolock) INNER JOIN
                      dbo.PERFORMA_TRANSACTIONMASTER (nolock)  ON dbo.PERFORMA_TRANSACTIONDETAIL.TRANMID = dbo.PERFORMA_TRANSACTIONMASTER.TRANMID
WHERE     (dbo.PERFORMA_TRANSACTIONMASTER.DISPSTATUS = 0) AND (dbo.PERFORMA_TRANSACTIONMASTER.SDPTID = 1)

