CREATE VIEW dbo.VW_IMPORT_LORRYHIRE_DETAIL_CTRL_MOD_ASSGN
AS
SELECT     TOP (100) PERCENT dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO,dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                      dbo.GATEINDETAIL.GIDATE, dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.IMPRTNAME, 
                      dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO,dbo.GATEINDETAIL.TRNSPRTNAME,dbo.GATEINDETAIL.TRNSPRTID
FROM         dbo.GATEINDETAIL INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID 
					  --LEFT OUTER JOIN 
					  --dbo.GATEINLORRYHIREDETAIL ON GATEINDETAIL.GIDID=GATEINLORRYHIREDETAIL.GIDID
WHERE     (dbo.GATEINDETAIL.SDPTID = 1) AND (dbo.GATEINDETAIL.CONTNRSID>2) AND 
                      (dbo.GATEINDETAIL.DISPSTATUS=0) 
ORDER BY dbo.GATEINDETAIL.CONTNRNO

