USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_NONPNR_LAST_GATEINRECORDS]    Script Date: 12/10/2021 11:36:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VW_IMPORT_LAST_GATEINRECORDS] AS
SELECT GATEINDETAIL.CONTNRNO , max(GATEINDETAIL.GIDID) as GIDID
 FROM GATEINDETAIL (Nolock)
 WHERE GATEINDETAIL.SDPTID= 1  AND GATEINDETAIL.CONTNRSID > 0 
 GROUP BY GATEINDETAIL.CONTNRNO ,GATEINDETAIL.GIDID
      





GO


