ALTER VIEW [dbo].[VW_IMPORT_RATECARDMASTER_FLX_ASSGN_01]
AS
SELECT     TOP (100) PERCENT dbo.SLABMASTER.SLABTID, dbo.SLABMASTER.TARIFFMID, dbo.SLABMASTER.STMRID, dbo.SLABMASTER.CHRGETYPE, 
                      dbo.SLABMASTER.CONTNRSID, dbo.SLABMASTER.SDTYPE, dbo.SLABMASTER.YRDTYPE, dbo.SLABMASTER.HTYPE, dbo.SLABMASTER.WTYPE, 
                      MAX(dbo.SLABMASTER.SLABMDATE) AS XTRANSDATE, DBO.SLABMASTER.SDPTTYPEID 
FROM         dbo.TARIFFMASTER INNER JOIN
                      dbo.SLABMASTER ON dbo.TARIFFMASTER.TARIFFMID = dbo.SLABMASTER.TARIFFMID
WHERE     (dbo.SLABMASTER.SLABMDATE <=
                          (SELECT     MAX(TRANNDATE) AS Expr1
                            FROM          dbo.TRANSACTION_DAYEND_MASTER))
GROUP BY dbo.SLABMASTER.TARIFFMID, dbo.SLABMASTER.SLABTID, dbo.SLABMASTER.STMRID, dbo.SLABMASTER.CHRGETYPE, dbo.SLABMASTER.CONTNRSID, 
                      dbo.SLABMASTER.SDTYPE, dbo.SLABMASTER.YRDTYPE, dbo.SLABMASTER.HTYPE, dbo.SLABMASTER.WTYPE, DBO.SLABMASTER.SDPTTYPEID 
ORDER BY dbo.SLABMASTER.TARIFFMID

