CREATE VIEW dbo.VW_IMPORT_BILL_OPEN_SHEET_SEAL_COUNT_ASSGN
AS
SELECT     TOP 100 PERCENT dbo.VW_IMPORT_BILL_OPEN_SHEET_SEAL_COUNT_ASSGN_02.OSMID, 
                      dbo.VW_IMPORT_BILL_OPEN_SHEET_SEAL_COUNT_ASSGN_02.BILLEMID, 
                      dbo.VW_IMPORT_BILL_OPEN_SHEET_SEAL_COUNT_ASSGN_01.NOC
FROM         dbo.VW_IMPORT_BILL_OPEN_SHEET_SEAL_COUNT_ASSGN_01 INNER JOIN
                      dbo.VW_IMPORT_BILL_OPEN_SHEET_SEAL_COUNT_ASSGN_02 ON 
                      dbo.VW_IMPORT_BILL_OPEN_SHEET_SEAL_COUNT_ASSGN_01.OSMID = dbo.VW_IMPORT_BILL_OPEN_SHEET_SEAL_COUNT_ASSGN_02.OSMID
ORDER BY dbo.VW_IMPORT_BILL_OPEN_SHEET_SEAL_COUNT_ASSGN_02.OSMID, dbo.VW_IMPORT_BILL_OPEN_SHEET_SEAL_COUNT_ASSGN_02.BILLEMID



