alter VIEW [dbo].[VW_IMPORT_GATEOUT_DETAIL_CTRL_ASSGN]
AS
SELECT     TOP (100) PERCENT dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO, dbo.VEHICLETICKETDETAIL.VTDNO, dbo.VEHICLETICKETDETAIL.VTNO, dbo.VEHICLETICKETDETAIL.COMPYID, 
                      dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
					  --convert(varchar(10),dbo.GATEINDETAIL.GIDATE,103) AS GIDATE,
                      --dbo.GATEINDETAIL.GIDATE,
                      convert(varchar(10),dbo.GATEINDETAIL.GIDATE,105) as 'GIDATE',
					   dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.IMPRTNAME, 
                      dbo.GATEINDETAIL.STMRNAME,dbo.OPENSHEETMASTER.OSMNAME AS CHANAME,ISNULL(dbo.OPENSHEETMASTER.CHAID,0) AS  CHAID,
					  ISNULL(dbo.OPENSHEETMASTER.OSMNAME,'') AS  CFSNAME,
					   dbo.GATEINDETAIL.IGMNO,ISNULL(dbo.GATEINDETAIL.GPLNO,'') AS GPLNO,  ISNULL(dbo.VEHICLETICKETDETAIL.VHLNO,'') AS VHLNO,ISNULL(dbo.VEHICLETICKETDETAIL.DRVNAME,'') AS DRVNAME, 
					   ISNULL(dbo.GATEINDETAIL.LPSEALNO, '') AS LPSEALNO ,	
					   --ISNULL(dbo.GATEINDETAIL.CSEALNO,'') AS VTSSEALNO,
					   ISNULL(dbo.VEHICLETICKETDETAIL.VTSSEALNO, '') AS VTSSEALNO ,				  
                      dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE, isnull(dbo.GATEOUTDETAIL.GODID,'') AS GODID, dbo.VEHICLETICKETDETAIL.VTSTYPE ,
					   Convert(varchar,OPENSHEETMASTER.OOCDATE,103) OOCDATE
FROM         dbo.GATEINDETAIL INNER JOIN
                      dbo.OPENSHEETDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.OPENSHEETDETAIL.GIDID INNER JOIN
                      dbo.AUTHORIZATIONSLIPDETAIL ON dbo.OPENSHEETDETAIL.OSDID = dbo.AUTHORIZATIONSLIPDETAIL.OSDID INNER JOIN
					  dbo.AUTHORIZATIONSLIPMASTER on  dbo.AUTHORIZATIONSLIPDETAIL.ASLMID=dbo.AUTHORIZATIONSLIPMASTER.ASLMID INNER JOIN
                      dbo.VEHICLETICKETDETAIL ON dbo.AUTHORIZATIONSLIPDETAIL.ASLDID = dbo.VEHICLETICKETDETAIL.ASLDID INNER JOIN
                      dbo.OPENSHEETMASTER ON dbo.OPENSHEETDETAIL.OSMID = dbo.OPENSHEETMASTER.OSMID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID LEFT OUTER JOIN
                      dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID
WHERE     (dbo.GATEINDETAIL.SDPTID = 1) AND (dbo.VEHICLETICKETDETAIL.VTSTYPE = 1) AND (dbo.VEHICLETICKETDETAIL.VTTYPE IN (1, 2)) AND 
                      (dbo.GATEOUTDETAIL.GODID IS NULL)
ORDER BY dbo.GATEINDETAIL.CONTNRNO

