USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_IMPORT_EMPTYGATEIN_CONTAINER_DEATILS_ASSGN]    Script Date: 23/11/2021 12:03:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER  VIEW [dbo].[VW_IMPORT_EMPTYGATEIN_CONTAINER_DEATILS_ASSGN]
AS
SELECT TOP 100 PERCENT  dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO,Convert(varchar(10),  GATEINDETAIL.GIDATE,103) as GIDATE,
                dbo.GATEINDETAIL.AVHLNO as VHLNO ,isnull(dbo.GATEINDETAIL.STMRID,0) as STMRID,isnull(dbo.GATEINDETAIL.STMRNAME,'') as STMRNAME
				,isnull(dbo.GATEINDETAIL.IMPRTID,0) as IMPRTID,isnull(dbo.GATEINDETAIL.IMPRTNAME,'') as IMPRTNAME

FROM  dbo.GATEINDETAIL (nolock) Left Join  
dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID  

 WHERE GATEINDETAIL.SDPTID=1  and (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) and (GATEINDETAIL.CONTNRSID=0)
 and dbo.GATEINDETAIL.AVHLNO is not null  

GO


