
ALTER VIEW [dbo].[VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01]
AS
--SELECT        TRANMID, STRG_HSNCODE, HANDL_HSNCODE, STRG_CGST_EXPRN, STRG_SGST_EXPRN, STRG_IGST_EXPRN, HANDL_CGST_EXPRN, HANDL_SGST_EXPRN, 
--                         HANDL_IGST_EXPRN, SUM(STRG_TAXABLE_AMT) AS STRG_TAXABLE_AMT, SUM(HANDL_TAXABLE_AMT) AS HANDL_TAXABLE_AMT, SUM(STRG_CGST_AMT) 
--                         AS STRG_CGST_AMT, SUM(STRG_SGST_AMT) AS STRG_SGST_AMT, SUM(STRG_IGST_AMT) AS STRG_IGST_AMT, SUM(HANDL_CGST_AMT) AS HANDL_CGST_AMT, 
--                         SUM(HANDL_SGST_AMT) AS HANDL_SGST_AMT, SUM(HANDL_IGST_AMT) AS HANDL_IGST_AMT, SUM(STRG_CGST_AMT + HANDL_CGST_AMT) AS CGST_AMT, 
--                         SUM(STRG_SGST_AMT + HANDL_SGST_AMT) AS SGST_AMT, SUM(STRG_IGST_AMT + HANDL_IGST_AMT) AS IGST_AMT
--FROM            dbo.TRANSACTIONMASTER
--WHERE REGSTRID = 15 
--GROUP BY TRANMID, STRG_HSNCODE, HANDL_HSNCODE, STRG_CGST_EXPRN, STRG_SGST_EXPRN, STRG_IGST_EXPRN, HANDL_CGST_EXPRN, HANDL_SGST_EXPRN, 
--                         HANDL_IGST_EXPRN
--HAVING        (STRG_HSNCODE IS NOT NULL OR HANDL_HSNCODE IS NOT NULL)

SELECT        TRANSACTIONMASTER.TRANMID, --ACHEADDESC 'HSNCODE',
				STRG_HSNCODE = CASE WHEN ACHEADDESC not LIKE '%HANDLING%' THEN '' ELSE isnull(ISNULL(ACHEADCODE,TRANSACTIONDETAIL.ACHEADID),'')  END , 
				HANDL_HSNCODE = CASE WHEN ACHEADDESC  LIKE '%HANDLING%' THEN isnull(ISNULL(ACHEADCODE,TRANSACTIONDETAIL.ACHEADID),'')   ELSE ''  END , 
				ISNULL(TRANSACTIONDETAIL.TRAND_STRG_CGST_EXPRN,0) AS STRG_CGST_EXPRN,ISNULL(TRANSACTIONDETAIL.TRAND_STRG_SGST_EXPRN,0) AS STRG_SGST_EXPRN, 
				ISNULL(TRANSACTIONDETAIL.TRAND_STRG_IGST_EXPRN,0) AS STRG_IGST_EXPRN, 
				ISNULL(TRANSACTIONDETAIL.TRAND_HANDL_CGST_EXPRN,0) AS HANDL_CGST_EXPRN,ISNULL(TRANSACTIONDETAIL.TRAND_HANDL_SGST_EXPRN,0) AS HANDL_SGST_EXPRN, 
				ISNULL(TRANSACTIONDETAIL.TRAND_HANDL_IGST_EXPRN,0) AS HANDL_IGST_EXPRN, 
				STRG_TAXABLE_AMT = CASE WHEN ACHEADDESC not LIKE '%HANDLING%' THEN 0 ELSE SUM(TRANDGAMT)  END,
				HANDL_TAXABLE_AMT = CASE WHEN ACHEADDESC LIKE '%HANDLING%' THEN 0 ELSE SUM(TRANDGAMT)  END,
				SUM(TRAND_STRG_CGST_AMT) AS STRG_CGST_AMT, SUM(TRAND_STRG_SGST_AMT) AS STRG_SGST_AMT, SUM(TRAND_STRG_IGST_AMT) AS STRG_IGST_AMT, SUM(TRAND_HANDL_CGST_AMT) AS HANDL_CGST_AMT, 
                         SUM(TRAND_HANDL_SGST_AMT) AS HANDL_SGST_AMT, SUM(TRAND_HANDL_IGST_AMT) AS HANDL_IGST_AMT, SUM(TRAND_STRG_CGST_AMT + TRAND_HANDL_CGST_AMT) AS CGST_AMT, 
                         SUM(TRAND_STRG_SGST_AMT + TRAND_HANDL_SGST_AMT) AS SGST_AMT, SUM(TRAND_STRG_IGST_AMT + TRAND_HANDL_IGST_AMT) AS IGST_AMT,
				ACHEADDESC
FROM            dbo.TRANSACTIONMASTER join TRANSACTIONDETAIL LEFT join ACCOUNTHEADMASTER on TRANSACTIONDETAIL.ACHEADID = ACCOUNTHEADMASTER.ACHEADID
				on  TRANSACTIONMASTER.tranmid = TRANSACTIONDETAIL.tranmid 
WHERE REGSTRID = 15 
GROUP BY TRANSACTIONMASTER.TRANMID, TRAND_STRG_CGST_EXPRN, TRAND_STRG_SGST_EXPRN, TRAND_STRG_IGST_EXPRN, TRAND_HANDL_CGST_EXPRN, TRAND_HANDL_SGST_EXPRN, 
                         TRAND_HANDL_IGST_EXPRN, ACHEADDESC, isnull(ISNULL(ACHEADCODE,TRANSACTIONDETAIL.ACHEADID),'')
						 