USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_02]    Script Date: 19/08/2021 18:45:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[VW_IMPORT_IGMNO_CONTAINER_CBX_ASSGN_02]
AS
SELECT     dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, dbo.AUTHORIZATIONSLIPDETAIL.OSDID
FROM         dbo.AUTHORIZATIONSLIPMASTER INNER JOIN
                      dbo.AUTHORIZATIONSLIPDETAIL ON dbo.AUTHORIZATIONSLIPMASTER.ASLMID = dbo.AUTHORIZATIONSLIPDETAIL.ASLMID
WHERE     (dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE IN (1, 2)) AND (dbo.AUTHORIZATIONSLIPMASTER.SDPTID = 1) AND 
                      (dbo.AUTHORIZATIONSLIPMASTER.DISPSTATUS = 0)


GO


