
ALTER VIEW [dbo].[VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02]
AS
SELECT     TOP (100) PERCENT dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO, dbo.GATEINDETAIL.GIDATE, 
                      dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.LPSEALNO, dbo.GATEINDETAIL.CSEALNO, dbo.GATEINDETAIL.VSLNAME, 
                      dbo.GATEINDETAIL.IMPRTNAME, dbo.GATEINDETAIL.STMRNAME, dbo.GATEOUTDETAIL.GODATE, dbo.GATEINDETAIL.PRDTGID,
					  dbo.GATEINDETAIL.VOYNO,
					  dbo.PRODUCTGROUPMASTER.PRDTGCODE,dbo.PRODUCTGROUPMASTER.PRDTGDESC,
					  isnull(dbo.GATEINDETAIL.BLNO,'-') as BLNO, 
					  isnull(Convert(varchar(10),dbo.GATEINDETAIL.BOEDATE,103),'') as BOEDATE,isnull(Convert(varchar(10),dbo.GATEINDETAIL.IGMDATE,103),'') as IGMDATE
FROM         dbo.GATEINDETAIL INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID LEFT OUTER JOIN
                      dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID inner join 
					  dbo.PRODUCTGROUPMASTER (nolock) on dbo.GATEINDETAIL.PRDTGID = dbo.PRODUCTGROUPMASTER.PRDTGID  
WHERE     (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) AND (dbo.GATEINDETAIL.SDPTID = 1)
ORDER BY dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.CONTNRNO




