
CREATE VIEW dbo.VW_MANUALOPENSHEET_DETAIL_CTRL_ASSGN
AS
SELECT        dbo.MANUALOPENSHEETDETAIL.OSDID, dbo.MANUALOPENSHEETDETAIL.OSMID,isnull(dbo.BILLENTRYDETAIL.BILLEDID,0) as BILLEDID,isnull(dbo.BILLENTRYDETAIL.BILLEMID,0) as BILLEMID, 
               dbo.MANUALOPENSHEETDETAIL.GIDID, dbo.MANUALOPENSHEETDETAIL.GIDATE, 
                         dbo.MANUALOPENSHEETDETAIL.LSEALNO, dbo.MANUALOPENSHEETDETAIL.SSEALNO, '-' AS CSEALNO, dbo.MANUALOPENSHEETDETAIL.INSPTYPE, dbo.GATEINDETAIL.IMPRTNAME, 
                         dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, dbo.PRODUCTGROUPMASTER.PRDTGDESC, dbo.GATEINDETAIL.PRDTGID,dbo.PRODUCTGROUPMASTER.PRDTGCODE,
						 dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.CONTNRNO, 
                         dbo.GATEINDETAIL.CONTNRSID, dbo.MANUALOPENSHEETMASTER.OSMIGMNO, dbo.MANUALOPENSHEETMASTER.OSMLNO, (CASE WHEN INSPTYPE = 1 THEN 'Yes' WHEN INSPTYPE = 0 THEN 'No' ELSE '-' END) AS INSP_DES, 
						 (CASE WHEN GATEIN_BLOCK_DETAILS.GBSTYPE = 1 THEN 'No' WHEN isnull(GATEIN_BLOCK_DETAILS.GBDID,0)  = 0 THEN 'No' ELSE 'Yes' END) AS Block, 
                       isnull(convert(varchar(10),dbo.BILLENTRYMASTER.BILLEMDATE,103),'') as BILLEMDATE
FROM    dbo.MANUALOPENSHEETMASTER WITH (nolock) INNER JOIN  
        dbo.MANUALOPENSHEETDETAIL WITH (nolock) ON dbo.MANUALOPENSHEETMASTER.OSMID = dbo.MANUALOPENSHEETDETAIL.OSMID Left Join 
		dbo.BILLENTRYDETAIL WITH (nolock) ON dbo.MANUALOPENSHEETDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID Left JOIN
        dbo.BILLENTRYMASTER WITH (nolock) ON dbo.BILLENTRYDETAIL.BILLEMID = dbo.BILLENTRYMASTER.BILLEMID inner JOIN  
		dbo.GATEINDETAIL WITH (nolock) ON dbo.MANUALOPENSHEETDETAIL.GIDID = dbo.GATEINDETAIL.GIDID inner JOIN  
		dbo.GATEIN_BLOCK_DETAILS WITH (nolock) ON dbo.GATEINDETAIL.GIDID = dbo.GATEIN_BLOCK_DETAILS.GIDID inner JOIN  
		dbo.PRODUCTGROUPMASTER WITH (nolock) ON dbo.GATEINDETAIL.PRDTGID = dbo.PRODUCTGROUPMASTER.PRDTGID



