USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_03]    Script Date: 28/09/2021 16:46:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_03]
AS
SELECT     GBDID, GIDID
FROM         dbo.GATEIN_BLOCK_DETAILS
WHERE     (GBTYPE = 0)


GO


