ALTER VIEW [dbo].[VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_01]
AS
SELECT     TOP (100) PERCENT dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.IGMNO, dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.GPLNO, 
                      dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.GIDID, dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.CONTNRNO, 
                      dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.GIDATE, dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.CONTNRSDESC, 
                      dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.LPSEALNO, dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.CSEALNO, 
                      dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.VSLNAME, dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.IMPRTNAME, 
                      dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.STMRNAME, ISNULL(dbo.GATEIN_BLOCK_DETAILS.GBSTYPE, 1) AS GBDID, 1 AS INS_TYPE,                      
					   dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.PRDTGID, dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.VOYNO,
					  dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.BLNO,dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.BOEDATE,dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.PRDTGDESC,
					  dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.PRDTGCODE,
					  dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.IGMDATE
FROM         dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02 
          LEFT OUTER JOIN dbo.MANUALOPENSHEETDETAIL ON dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.GIDID = dbo.MANUALOPENSHEETDETAIL.GIDID 
		  LEFT OUTER JOIN GATEIN_BLOCK_DETAILS (NOLOCK) ON dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.GIDID = dbo.GATEIN_BLOCK_DETAILS.GIDID 
     
                     
WHERE     (ISNULL(dbo.MANUALOPENSHEETDETAIL.OSDID, 0) = 0)  --and ( ISNULL(dbo.GATEIN_BLOCK_DETAILS.GBDID,0) = 0 OR ISNULL(dbo.GATEIN_BLOCK_DETAILS.GBSTYPE,1) = 1 )
ORDER BY dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.IGMNO, dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.GPLNO, 
                      dbo.VW_MANUALOPENSHEET_CONTAINER_CBX_ASSGN_02.CONTNRNO 


