USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN]    Script Date: 04/08/2021 15:57:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER VIEW [dbo].[VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN]
AS
SELECT     TOP (100) PERCENT dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO, dbo.VEHICLETICKETDETAIL.VTDNO, dbo.VEHICLETICKETDETAIL.VTNO, dbo.VEHICLETICKETDETAIL.COMPYID, 
                      dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
					  --convert(varchar(10),dbo.GATEINDETAIL.GIDATE,103) AS GIDATE,
                      --dbo.GATEINDETAIL.GIDATE,
                      convert(varchar(10),dbo.GATEINDETAIL.GIDATE,105) as 'GIDATE',
					   dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.IMPRTNAME, 
                      dbo.GATEINDETAIL.STMRNAME,dbo.GATEINDETAIL.CHANAME,ISNULL(dbo.GATEINDETAIL.CHAID,0) AS  CHAID,
					  ISNULL(dbo.GATEINDETAIL.CFSNAME,'') AS  CFSNAME,
					   dbo.GATEINDETAIL.IGMNO,ISNULL(dbo.GATEINDETAIL.GPLNO,'') AS GPLNO,  ISNULL(dbo.VEHICLETICKETDETAIL.VHLNO,'') AS VHLNO,ISNULL(dbo.VEHICLETICKETDETAIL.DRVNAME,'') AS DRVNAME, 
					   ISNULL(dbo.GATEINDETAIL.LPSEALNO, '') AS LPSEALNO ,	
					   --ISNULL(dbo.GATEINDETAIL.CSEALNO,'') AS VTSSEALNO,
					   ISNULL(dbo.VEHICLETICKETDETAIL.VTSSEALNO, '') AS VTSSEALNO ,				  
                      dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE, isnull(dbo.GATEOUTDETAIL.GODID,'') AS GODID, dbo.VEHICLETICKETDETAIL.VTSTYPE 
FROM     dbo.VEHICLETICKETDETAIL INNER JOIN  
         dbo.AUTHORIZATIONSLIPDETAIL ON  dbo.VEHICLETICKETDETAIL.ASLDID = dbo.AUTHORIZATIONSLIPDETAIL.ASLDID   INNER JOIN 
		 dbo.AUTHORIZATIONSLIPMASTER ON dbo.AUTHORIZATIONSLIPDETAIL.ASLMID = dbo.AUTHORIZATIONSLIPMASTER.ASLMID INNER JOIN 
		 dbo.GATEINDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.AUTHORIZATIONSLIPDETAIL.GIDID LEFT JOIN 
		 dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID LEFT  OUTER JOIN                       
		 dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID

      
WHERE     (dbo.GATEINDETAIL.SDPTID = 9) AND (dbo.VEHICLETICKETDETAIL.VTSTYPE IN (1,2)) AND (dbo.VEHICLETICKETDETAIL.VTTYPE IN (1, 2)) 
        --AND   (dbo.GATEOUTDETAIL.GODID IS NULL) 
ORDER BY dbo.GATEINDETAIL.CONTNRNO







GO


