alter VIEW [dbo].[VW_NONPNR_TRANSACTION_ADDRESS_DETAIL_ASSGN]
AS
SELECT        dbo.TRANSACTIONMASTER.TRANMID, ISNULL(dbo.TRANSACTIONMASTER.TRANCSNAME, dbo.CATEGORYMASTER.CATEDNAME) AS TRANCSNAME, 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR1, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR1) AS TRANIMPADDR1, 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR2, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR2) AS TRANIMPADDR2, 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR3, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR3) AS TRANIMPADDR3, 
                         ISNULL(dbo.TRANSACTIONMASTER.TRANIMPADDR4, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR4) AS TRANIMPADDR4,
						 ISNULL(dbo.GATEINDETAIL.IMPRTNAME,'') AS  IMPRTNAME,
						 ISNULL(CATEGORY_ADDRESS_DETAIL.CATEAADDR1,'') AS IMPCATEADDR1, ISNULL(CATEGORY_ADDRESS_DETAIL.CATEAADDR2,'') AS IMPCATEADDR2, 
                         ISNULL(CATEGORY_ADDRESS_DETAIL.CATEAADDR3,'') AS IMPCATEADDR3, ISNULL(CATEGORY_ADDRESS_DETAIL.CATEAADDR4,'')  AS IMPCATEADDR4, 
                        ISNULL(CATEGORY_ADDRESS_DETAIL.CATEAGSTNO,'') AS CHACATEGSTNO,ISNULL(CATEGORY_ADDRESS_DETAIL.CATEAGSTNO,'') AS IMPCATEGSTNO,
						isnull(dbo.CATEGORYMASTER.CATEID,'') AS CATEID, isnull(dbo.TRANSACTIONMASTER.CATEAID,'') AS CATEAID, isnull(CATEGORY_ADDRESS_DETAIL.STATEID,0) 'STATEID'
FROM            dbo.TRANSACTIONDETAIL INNER JOIN
                         dbo.TRANSACTIONMASTER ON dbo.TRANSACTIONDETAIL.TRANMID = dbo.TRANSACTIONMASTER.TRANMID LEFT  JOIN                         
                         dbo.GATEINDETAIL ON dbo.TRANSACTIONDETAIL.TRANDREFID = dbo.GATEINDETAIL.GIDID LEFT JOIN
                         dbo.CATEGORYMASTER ON dbo.TRANSACTIONMASTER.TRANREFID = dbo.CATEGORYMASTER.CATEID LEFT JOIN
						 dbo.CATEGORY_ADDRESS_DETAIL ON dbo.CATEGORYMASTER.CATEID=dbo.CATEGORY_ADDRESS_DETAIL.CATEID

