USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_EMPTY_CONTAINERNO_AUTOASSGN]    Script Date: 20/10/2021 18:26:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[VW_NEW_EMPTY_VT_CONTAINERNO_AUTOASSGN]
AS

Select CONTNRNO,MAX(GIDID) as GIDID From VW_NEW_EMPTY_GATEOUT_CONTAINER_CBX_ASSGN
Group By CONTNRNO,GIDID 



GO


