USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN_001]    Script Date: 04/08/2021 15:58:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[VW_NONPNR_GATEOUT_DETAIL_CTRL_ASSGN_001]
AS
SELECT     TOP (100) PERCENT dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO, dbo.VEHICLETICKETDETAIL.VTNO,dbo.VEHICLETICKETDETAIL.VTDNO, dbo.VEHICLETICKETDETAIL.COMPYID, 
                      dbo.CONTAINERSIZEMASTER.CONTNRSDESC,GATEINDETAIL.CHAID, GATEINDETAIL.CHANAME,GATEINDETAIL.CFSNAME ,
					  --convert(varchar(10),dbo.GATEINDETAIL.GIDATE,103) AS GIDATE,
                      dbo.GATEINDETAIL.GIDATE,
					   dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.IMPRTNAME, 
                      dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.VEHICLETICKETDETAIL.VHLNO, dbo.VEHICLETICKETDETAIL.DRVNAME, 
                      dbo.VEHICLETICKETDETAIL.VTSSEALNO, dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE, isnull(dbo.GATEOUTDETAIL.GODID,'') AS GODID, 
					  dbo.VEHICLETICKETDETAIL.VTSTYPE, isnull(dbo.GATEINDETAIL.LPSEALNO,'') AS LPSEALNO
FROM         dbo.GATEINDETAIL INNER JOIN
                      dbo.AUTHORIZATIONSLIPDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.AUTHORIZATIONSLIPDETAIL.GIDID INNER JOIN                      
                      dbo.AUTHORIZATIONSLIPMASTER ON dbo.AUTHORIZATIONSLIPDETAIL.ASLMID = dbo.AUTHORIZATIONSLIPMASTER.ASLMID INNER JOIN
                      dbo.VEHICLETICKETDETAIL ON dbo.AUTHORIZATIONSLIPDETAIL.ASLDID = dbo.VEHICLETICKETDETAIL.ASLDID INNER JOIN                        
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID LEFT OUTER JOIN
                      dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID
WHERE     (dbo.GATEINDETAIL.SDPTID = 9) AND (dbo.VEHICLETICKETDETAIL.VTSTYPE = 1) AND (dbo.VEHICLETICKETDETAIL.VTTYPE IN (1, 2))
ORDER BY dbo.GATEINDETAIL.CONTNRNO


GO


