alter VIEW [dbo].[VW_NONPNR_ADSLIP_CRY_PRINT_ASSGN]
AS
SELECT        dbo.COMPANYMASTER.COMPDNAME, dbo.COMPANYMASTER.COMPADDR, dbo.AUTHORIZATIONSLIPMASTER.ASLMID, dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, dbo.AUTHORIZATIONSLIPMASTER.ASLMNO, 
                         dbo.AUTHORIZATIONSLIPMASTER.ASLMDNO, dbo.AUTHORIZATIONSLIPMASTER.ASLMDATE, RIGHT(dbo.AUTHORIZATIONSLIPMASTER.ASLMTIME, 8) AS ASLMTIME, dbo.GATEINDETAIL.CONTNRNO, 
                         dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.SLOTMASTER.SLOTDESC, dbo.ROWMASTER.ROWDESC, dbo.GATEINDETAIL.GIDATE, dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.STMRNAME, 
                         dbo.GATEINDETAIL.IMPRTNAME, dbo.AUTHORIZATIONSLIPDETAIL.ASLDTYPE, dbo.AUTHORIZATIONSLIPDETAIL.ASLLTYPE, dbo.AUTHORIZATIONSLIPDETAIL.ASLOTYPE, 
                         dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE, dbo.AUTHORIZATIONSLIPDETAIL.VHLNO, dbo.AUTHORIZATIONSLIPDETAIL.DRVNAME, dbo.CONTAINERTYPEMASTER.CONTNRTDESC, dbo.GATEINDETAIL.IGMNO, 
                         dbo.GATEINDETAIL.GPLNO, dbo.AUTHORIZATIONSLIPMASTER.CUSRID AS EMPNAME, dbo.TMPRPT_IDS.KUSRID, dbo.TMPRPT_IDS.OPTNSTR, dbo.TMPRPT_IDS.RPTID
						 ---- code added by rajesh on 16-Jul-2021 for mapping additional columns in edmx EF
						 --,dbo.GATEINDETAIL.LPSEALNO, dbo.GATEINDETAIL.CSEALNO , dbo.GATEINDETAIL.CHANAME, dbo.GATEINDETAIL.BCHANAME
FROM            dbo.TMPRPT_IDS INNER JOIN
                         dbo.AUTHORIZATIONSLIPMASTER INNER JOIN
                         dbo.COMPANYMASTER INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.COMPANYMASTER.COMPID = dbo.COMPANYACCOUNTINGDETAIL.COMPID ON 
                         dbo.AUTHORIZATIONSLIPMASTER.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                         dbo.AUTHORIZATIONSLIPDETAIL ON dbo.AUTHORIZATIONSLIPMASTER.ASLMID = dbo.AUTHORIZATIONSLIPDETAIL.ASLMID ON 
                         dbo.TMPRPT_IDS.RPTID = dbo.AUTHORIZATIONSLIPMASTER.ASLMID LEFT OUTER JOIN
                         dbo.ROWMASTER RIGHT OUTER JOIN
                         dbo.SLOTMASTER ON dbo.ROWMASTER.ROWID = dbo.SLOTMASTER.ROWID RIGHT OUTER JOIN
                         dbo.CONTAINERSIZEMASTER INNER JOIN
                         dbo.GATEINDETAIL ON dbo.CONTAINERSIZEMASTER.CONTNRSID = dbo.GATEINDETAIL.CONTNRSID INNER JOIN
                         dbo.CONTAINERTYPEMASTER ON dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID ON dbo.SLOTMASTER.SLOTID = dbo.GATEINDETAIL.SLOTID ON 
                         dbo.AUTHORIZATIONSLIPDETAIL.GIDID = dbo.GATEINDETAIL.GIDID



--Severity	Code	Description	Project	File	Line	Suppression State
--Error		Error 11007: Entity type 'VW_ASD_GIGMNO_CONTAINER_CBX_ASSGN' is not mapped.	scfs_erp	E:\Rajesh\SCFS_ERP_15_07_2021\scfs\Data\SCFS.edmx	3005	
