ALTER VIEW [dbo].[VW_NONPNR_GATEIN_STATUS]
AS 

 SELECT    dbo.GATEINDETAIL.GIDID, 
          (CASE 
			when (TRANSACTIONMASTER.DISPSTATUS = 1 or GATEINDETAIL.DISPSTATUS = 1 or GATEOUTDETAIL.DISPSTATUS = 1
				 or VEHICLETICKETDETAIL.DISPSTATUS = 1 or  dbo.AUTHORIZATIONSLIPMASTER.DISPSTATUS = 1) THEN 'Cancelled' 
		   WHEN dbo.TRANSACTIONDETAIL.TRANDREFID IS NOT NULL AND TRANSACTIONMASTER.DISPSTATUS = 0 THEN 'Invoice' 
		    WHEN dbo.GATEOUTDETAIL.GIDID IS NOT NULL  AND GATEOUTDETAIL.DISPSTATUS = 0 THEN 'Gate Out' 
			WHEN dbo.VEHICLETICKETDETAIL.GIDID IS NOT NULL AND VEHICLETICKETDETAIL.DISPSTATUS = 0  THEN 'Vehicle Ticket' 
			WHEN dbo.AUTHORIZATIONSLIPDETAIL.GIDID IS NOT NULL AND  dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE = 1  AND dbo.AUTHORIZATIONSLIPMASTER.DISPSTATUS = 0  THEN 'Load Slip'  
			WHEN dbo.AUTHORIZATIONSLIPDETAIL.GIDID IS NOT NULL AND  dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE = 2 AND dbo.AUTHORIZATIONSLIPMASTER.DISPSTATUS = 0  THEN 'De Stuff'  
			WHEN dbo.GATEINDETAIL.GIDID IS NOT NULL  AND GATEINDETAIL.DISPSTATUS = 0 THEN 'Gate In'
			END ) AS  CURRENTSTATUS 
  FROM     dbo.GATEINDETAIL (nolock) LEFT JOIN  
		   dbo.AUTHORIZATIONSLIPDETAIL (nolock) ON  dbo.GATEINDETAIL.GIDID = dbo.AUTHORIZATIONSLIPDETAIL.GIDID LEFT JOIN 
		   dbo.AUTHORIZATIONSLIPMASTER (nolock) ON dbo.AUTHORIZATIONSLIPDETAIL.ASLMID = dbo.AUTHORIZATIONSLIPMASTER.ASLMID LEFT JOIN 
		   dbo.VEHICLETICKETDETAIL (nolock) ON  dbo.AUTHORIZATIONSLIPDETAIL.ASLDID =  dbo.VEHICLETICKETDETAIL.ASLDID LEFT JOIN 
		   dbo.GATEOUTDETAIL (nolock) ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID LEFT JOIN  
		   dbo.TRANSACTIONDETAIL (nolock) ON dbo.GATEINDETAIL.GIDID = dbo.TRANSACTIONDETAIL.TRANDREFID   LEFT JOIN 
		   dbo.TRANSACTIONMASTER (nolock) ON dbo.TRANSACTIONMASTER.TRANMID = TRANSACTIONDETAIL.TRANMID 
 WHERE     (dbo.GATEINDETAIL.SDPTID = 9)   
 GROUP BY  dbo.GATEINDETAIL.GIDID,dbo.GATEOUTDETAIL.GIDID,dbo.VEHICLETICKETDETAIL.GIDID,
           dbo.AUTHORIZATIONSLIPDETAIL.GIDID,dbo.AUTHORIZATIONSLIPDETAIL.GIDID,
		   dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE,dbo.TRANSACTIONDETAIL.TRANDREFID,
		   dbo.TRANSACTIONMASTER.DISPSTATUS, GATEOUTDETAIL.DISPSTATUS,VEHICLETICKETDETAIL.DISPSTATUS,
		   dbo.AUTHORIZATIONSLIPMASTER.DISPSTATUS,GATEINDETAIL.DISPSTATUS

