alter VIEW [dbo].[VW_NONPNR_RATECARDMASTER_FLX_ASSGN_01]
AS
SELECT     TOP (100) PERCENT dbo.SLABMASTER.SLABTID, dbo.SLABMASTER.TARIFFMID, dbo.SLABMASTER.STMRID, dbo.SLABMASTER.CHRGETYPE, 
                      dbo.SLABMASTER.CONTNRSID, dbo.SLABMASTER.SDTYPE, dbo.SLABMASTER.YRDTYPE, dbo.SLABMASTER.HTYPE, dbo.SLABMASTER.WTYPE, 
                      MAX(dbo.SLABMASTER.SLABMDATE) AS XTRANSDATE
FROM         dbo.TARIFFMASTER INNER JOIN
                      dbo.SLABMASTER ON dbo.TARIFFMASTER.TARIFFMID = dbo.SLABMASTER.TARIFFMID
WHERE     (dbo.SLABMASTER.SLABMDATE <=
                          --(SELECT     MAX(GODATE) AS Expr1
                          --  FROM          dbo.GATEOUTDETAIL)
						  (SELECT     ISNULL(MAX(TRANDATE),'') AS Expr1
                            FROM          dbo.TRANSACTION_DAYEND_MASTER)
						  
						  )
GROUP BY dbo.SLABMASTER.TARIFFMID, dbo.SLABMASTER.SLABTID, dbo.SLABMASTER.STMRID, dbo.SLABMASTER.CHRGETYPE, dbo.SLABMASTER.CONTNRSID, 
                      dbo.SLABMASTER.SDTYPE, dbo.SLABMASTER.YRDTYPE, dbo.SLABMASTER.HTYPE, dbo.SLABMASTER.WTYPE
ORDER BY dbo.SLABMASTER.TARIFFMID