alter VIEW dbo.VW_NONPNR_VT_CRY_PRINT_ASSGN
AS
SELECT        dbo.COMPANYMASTER.COMPDNAME, dbo.COMPANYMASTER.COMPADDR, dbo.VEHICLETICKETDETAIL.VTDID, dbo.VEHICLETICKETDETAIL.COMPYID, dbo.VEHICLETICKETDETAIL.SDPTID, 
                         dbo.VEHICLETICKETDETAIL.VTDATE, RIGHT(dbo.VEHICLETICKETDETAIL.VTTIME, 8) AS VTTIME, dbo.VEHICLETICKETDETAIL.VTNO, dbo.VEHICLETICKETDETAIL.VTDNO, dbo.GATEINDETAIL.CONTNRNO, 
                         dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.CONTAINERTYPEMASTER.CONTNRTCODE, dbo.GATEINDETAIL.IMPRTNAME, dbo.GATEINDETAIL.STMRNAME, dbo.VEHICLETICKETDETAIL.VHLNO, 
                         dbo.VEHICLETICKETDETAIL.VTTYPE, dbo.VEHICLETICKETDETAIL.DRVNAME, dbo.VEHICLETICKETDETAIL.CUSRID AS EMPNAME, dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.IGMNO, 
                         dbo.GATEINDETAIL.GPLNO, dbo.VEHICLETICKETDETAIL.VTREMRKS, dbo.VEHICLETICKETDETAIL.VTQTY, dbo.VEHICLETICKETDETAIL.VTSSEALNO, dbo.AUTHORIZATIONSLIPMASTER.ASLMTIME, 
                         dbo.AUTHORIZATIONSLIPMASTER.ASLMDATE, dbo.AUTHORIZATIONSLIPMASTER.ASLMDNO, dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE, dbo.VEHICLETICKETDETAIL.VTSTYPE, dbo.TMPRPT_IDS.KUSRID, 
                         dbo.TMPRPT_IDS.OPTNSTR, dbo.TMPRPT_IDS.RPTID, dbo.GATEINDETAIL.CHANAME, dbo.VEHICLETICKETDETAIL.QRCDIMGPATH
FROM            dbo.TMPRPT_IDS INNER JOIN
                         dbo.VEHICLETICKETDETAIL INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.VEHICLETICKETDETAIL.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                         dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID ON dbo.TMPRPT_IDS.RPTID = dbo.VEHICLETICKETDETAIL.VTDID RIGHT OUTER JOIN
                         dbo.CONTAINERSIZEMASTER INNER JOIN
                         dbo.GATEINDETAIL ON dbo.CONTAINERSIZEMASTER.CONTNRSID = dbo.GATEINDETAIL.CONTNRSID INNER JOIN
                         dbo.CONTAINERTYPEMASTER ON dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID RIGHT OUTER JOIN
                         dbo.AUTHORIZATIONSLIPMASTER INNER JOIN
                         dbo.AUTHORIZATIONSLIPDETAIL ON dbo.AUTHORIZATIONSLIPMASTER.ASLMID = dbo.AUTHORIZATIONSLIPDETAIL.ASLMID ON dbo.GATEINDETAIL.GIDID = dbo.AUTHORIZATIONSLIPDETAIL.GIDID ON 
                         dbo.VEHICLETICKETDETAIL.ASLDID = dbo.AUTHORIZATIONSLIPDETAIL.ASLDID

