ALTER VIEW dbo.VW_NEW_EMPTY_GATEOUT_CONTAINER_CBX_ASSGN
AS
SELECT     dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO, dbo.VEHICLETICKETDETAIL.GIDID AS PGIDID, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
           dbo.GATEINDETAIL.GIDATE, dbo.GATEINDETAIL.STMRNAME, Isnull(GATEINDETAIL.CHAID,0) as  CHAID,isnull(GATEINDETAIL.CHANAME,'') as CHANAME, dbo.GATEINDETAIL.DRVNAME
FROM       dbo.GATEINDETAIL  
           INNER JOIN  dbo.CONTAINERSIZEMASTER (NOLOCK) ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID 
		   INNER JOIN  dbo.VEHICLETICKETDETAIL (NOLOCK) ON dbo.GATEINDETAIL.GIDID = dbo.VEHICLETICKETDETAIL.EGIDID 
		   INNER JOIN  dbo.AUTHORIZATIONSLIPDETAIL (NOLOCK) ON dbo.GATEINDETAIL.GIDID = dbo.AUTHORIZATIONSLIPDETAIL.OSDID  
		   INNER JOIN  dbo.AUTHORIZATIONSLIPMASTER (NOLOCK) ON dbo.AUTHORIZATIONSLIPDETAIL.ASLMID = dbo.AUTHORIZATIONSLIPMASTER.ASLMID 
		   LEFT OUTER JOIN  dbo.GATEOUTDETAIL (NOLOCK) ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID
WHERE     (dbo.GATEINDETAIL.SDPTID = 3) AND (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) AND (AUTHORIZATIONSLIPMASTER.ASLMTYPE = 3)

