alter VIEW [dbo].[VW_NONPNR_GATE_IN_PRINT_ASSGN]
AS
SELECT     dbo.COMPANYMASTER.COMPDNAME, dbo.COMPANYMASTER.COMPADDR, dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.COMPYID, dbo.GATEINDETAIL.SDPTID, 
                      dbo.GATEINDETAIL.GIDATE, RIGHT(dbo.GATEINDETAIL.GITIME, 8) AS GITIME, dbo.GATEINDETAIL.GINO, dbo.GATEINDETAIL.GIDNO, dbo.GATEINDETAIL.GIVHLTYPE, 
					  --code commented and modified by rajesh on 23-07-2021
                      ISNULL(dbo.GATEINDETAIL.GTRNSPRTNAME, dbo.GATEINDETAIL.TRNSPRTNAME) 'TRNSPRTNAME' ,
					  dbo.GATEINDETAIL.VHLNO, dbo.GATEINDETAIL.DRVNAME, dbo.GATEINDETAIL.GPREFNO, dbo.GATEINDETAIL.IMPRTNAME, 
                      dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.CONTAINERTYPEMASTER.CONTNRTCODE, 
                      dbo.GATEINDETAIL.LPSEALNO, dbo.GATEINDETAIL.CSEALNO, dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, dbo.GATEINDETAIL.PRDTDESC, 
                      dbo.GATEINDETAIL.GPWGHT, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO,  dbo.TMPRPT_IDS.KUSRID, 
                      dbo.GATEINDETAIL.GIISOCODE, dbo.GATEINDETAIL.GPSCNTYPE, dbo.GATEINDETAIL.IGMDATE--,dbo.ROWMASTER.ROWDESC,
FROM         dbo.GATEINDETAIL INNER JOIN
                      dbo.COMPANYACCOUNTINGDETAIL ON dbo.GATEINDETAIL.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                      dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID INNER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                      dbo.CONTAINERTYPEMASTER ON dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID INNER JOIN
                      dbo.TMPRPT_IDS ON dbo.GATEINDETAIL.GIDID = dbo.TMPRPT_IDS.RPTID --LEFT OUTER JOIN
                     -- dbo.ROWMASTER ON dbo.GATEINDETAIL.ROWID = dbo.ROWMASTER.ROWID


