
CREATE VIEW [dbo].[VW_NEW_CATEGORY_STATETYPE_ASSGN]
AS
SELECT     dbo.CATEGORYMASTER.CATEID, dbo.CATEGORYMASTER.CATENAME, ISNULL(dbo.STATEMASTER.STATETYPE, 0) AS STATETYPE, dbo.CATEGORYMASTER.CATETID, 
                      dbo.CATEGORYMASTER.DISPSTATUS
FROM         dbo.CATEGORYMASTER LEFT OUTER JOIN
			dbo.CATEGORY_ADDRESS_DETAIL on CATEGORYMASTER.CATEID = CATEGORY_ADDRESS_DETAIL.CATEID inner join
			dbo.STATEMASTER ON isnull(CATEGORY_ADDRESS_DETAIL.STATEID, CATEGORYMASTER.STATEID) = dbo.STATEMASTER.STATEID


