USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_OPENSHEET_BILL_ENTRY_MID_ASSGN]    Script Date: 02-10-2021 15:46:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[VW_OPENSHEET_BILL_ENTRY_MID_ASSGN]
AS
SELECT        dbo.OPENSHEETDETAIL.OSMID, dbo.BILLENTRYDETAIL.BILLEMID
FROM            dbo.BILLENTRYDETAIL INNER JOIN
                         dbo.OPENSHEETDETAIL ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.OPENSHEETDETAIL.BILLEDID
GROUP BY dbo.OPENSHEETDETAIL.OSMID, dbo.BILLENTRYDETAIL.BILLEMID

GO


