alter VIEW [dbo].[VW_OPENSHEET_CONTAINER_CBX_ASSGN_01]
AS
SELECT     TOP (100) PERCENT dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.IGMNO, dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.GPLNO, 
                      dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.GIDID, dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.CONTNRNO, 
                      dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.GIDATE, dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.CONTNRSDESC, 
                      dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.LPSEALNO, dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.CSEALNO, 
                      dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.VSLNAME, dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.IMPRTNAME, 
                      dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.STMRNAME, ISNULL(dbo.GATEIN_BLOCK_DETAILS.GBSTYPE, 1) AS GBDID, 
                      dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.PRDTGID, dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.VOYNO,
					  dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.BLNO,dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.BOEDATE,dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.PRDTGDESC,
					  dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.PRDTGCODE,
					  dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.IGMDATE,
					  dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.PRDTDESC
FROM         dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02 LEFT OUTER JOIN  
              dbo.GATEIN_BLOCK_DETAILS (NOLOCK) ON 
			  dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.GIDID = dbo.GATEIN_BLOCK_DETAILS.GIDID LEFT OUTER JOIN
                      dbo.OPENSHEETDETAIL ON dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.GIDID = dbo.OPENSHEETDETAIL.GIDID
                      
WHERE     (ISNULL(dbo.OPENSHEETDETAIL.OSDID, 0) = 0) --and ISNULL(dbo.GATEIN_BLOCK_DETAILS.GBDID, 0) = 0
--( ISNULL(dbo.GATEIN_BLOCK_DETAILS.GBDID, 0) = 0 OR isnull(dbo.GATEIN_BLOCK_DETAILS.GBSTYPE,1) in (1,0) )
ORDER BY dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.IGMNO, dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.GPLNO, 
                      dbo.VW_OPENSHEET_CONTAINER_CBX_ASSGN_02.CONTNRNO

