-- select * from VW_OPENSHEET_DETAIL_CTRL_ASSGN where  OSMID=9315
ALTER VIEW dbo.VW_OPENSHEET_DETAIL_CTRL_ASSGN
AS
SELECT        dbo.OPENSHEETDETAIL.OSDID, dbo.OPENSHEETDETAIL.OSMID,isnull(dbo.BILLENTRYDETAIL.BILLEDID,0) as BILLEDID,isnull(dbo.BILLENTRYDETAIL.BILLEMID,0) as BILLEMID, dbo.OPENSHEETDETAIL.GIDID, dbo.OPENSHEETDETAIL.GIDATE, 
                         dbo.OPENSHEETDETAIL.LSEALNO, dbo.OPENSHEETDETAIL.SSEALNO, ISNULL(dbo.OPENSHEETDETAIL.CSEALNO, '-') AS CSEALNO, dbo.OPENSHEETDETAIL.INSPTYPE, dbo.GATEINDETAIL.IMPRTNAME, 
                         dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, dbo.PRODUCTGROUPMASTER.PRDTGDESC, dbo.GATEINDETAIL.PRDTGID,dbo.PRODUCTGROUPMASTER.PRDTGCODE,
						 dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.CONTNRNO, 
                         dbo.GATEINDETAIL.CONTNRSID, dbo.OPENSHEETMASTER.OSMIGMNO, dbo.OPENSHEETMASTER.OSMLNO, (CASE WHEN INSPTYPE = 1 THEN 'Yes' WHEN INSPTYPE = 0 THEN 'No' ELSE '-' END) AS INSP_DES, 
						 (CASE WHEN GATEIN_BLOCK_DETAILS.GBSTYPE = 1 THEN 'No' WHEN isnull(GATEIN_BLOCK_DETAILS.GBDID,0)  = 0 THEN 'No' ELSE 'Yes' END) AS Block, 
                         dbo.BILLENTRYMASTER.BILLEMDATE
FROM            dbo.OPENSHEETMASTER WITH (nolock) INNER JOIN
                         dbo.OPENSHEETDETAIL WITH (nolock) ON dbo.OPENSHEETMASTER.OSMID = dbo.OPENSHEETDETAIL.OSMID LEFT JOIN
                         dbo.BILLENTRYDETAIL WITH (nolock) ON dbo.OPENSHEETDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID LEFT JOIN
                         dbo.BILLENTRYMASTER WITH (nolock) ON dbo.BILLENTRYDETAIL.BILLEMID = dbo.BILLENTRYMASTER.BILLEMID INNER JOIN
                         dbo.GATEINDETAIL WITH (nolock) ON dbo.OPENSHEETDETAIL.GIDID = dbo.GATEINDETAIL.GIDID LEFT JOIN  
						 dbo.GATEIN_BLOCK_DETAILS WITH (nolock) ON dbo.GATEINDETAIL.GIDID = dbo.GATEIN_BLOCK_DETAILS.GIDID INNER JOIN
                         dbo.PRODUCTGROUPMASTER WITH (nolock) ON dbo.GATEINDETAIL.PRDTGID = dbo.PRODUCTGROUPMASTER.PRDTGID




