USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_SUPPLEMENTARY_BILL_NO_ASSGN]    Script Date: 04/09/2021 17:21:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_SUPPLEMENTARY_BILL_NO_ASSGN]
AS
SELECT     dbo.TRANSACTIONDETAIL.TRANDAID, dbo.TRANSACTIONMASTER.TRANDNO, dbo.TRANSACTIONMASTER.TRANDATE, 
                      dbo.TRANSACTIONMASTER.TRANMID
FROM         dbo.TRANSACTIONMASTER INNER JOIN
                      dbo.TRANSACTIONDETAIL ON dbo.TRANSACTIONMASTER.TRANMID = dbo.TRANSACTIONDETAIL.TRANMID
WHERE     (dbo.TRANSACTIONDETAIL.TRANDAID > 0)

GO


