alter VIEW [dbo].[VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02]
AS
SELECT     TOP 100 PERCENT dbo.TRANSACTIONDETAIL.SBDID, SUM(dbo.TRANSACTIONDETAIL.TRANDNOP) AS TRANDNOP
FROM         dbo.TRANSACTIONMASTER (nolock) INNER JOIN
                      dbo.TRANSACTIONDETAIL (nolock) ON dbo.TRANSACTIONMASTER.TRANMID = dbo.TRANSACTIONDETAIL.TRANMID
WHERE     (dbo.TRANSACTIONMASTER.TRANBTYPE = 5)
GROUP BY dbo.TRANSACTIONDETAIL.SBDID
HAVING      (SUM(dbo.TRANSACTIONDETAIL.TRANDNOP) > 0)
ORDER BY dbo.TRANSACTIONDETAIL.SBDID