--select * from VW_SHUTOUT_VT_PRINT_ASSGN
alter VIEW dbo.VW_SHUTOUT_VT_PRINT_ASSGN
AS
SELECT        TOP (100) PERCENT dbo.COMPANYMASTER.COMPNAME, dbo.COMPANYMASTER.COMPADDR, dbo.TMPRPT_IDS.KUSRID, dbo.TMPRPT_IDS.RPTID, dbo.STUFFINGMASTER.STFMID, dbo.TMPRPT_IDS.OPTNSTR, 
                         dbo.STUFFINGMASTER.STFMNO, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMDATE, dbo.STUFFINGMASTER.STFMTIME, dbo.STUFFINGMASTER.STFMNAME, 
                         dbo.SHIPPINGBILLDETAIL.PRDTDESC, GATEINDETAIL_1.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.STUFFINGPRODUCTDETAIL.STFDSBNO AS SBMO1, 
                         dbo.STUFFINGPRODUCTDETAIL.STFDSBDATE AS SBDATE1, dbo.STUFFINGPRODUCTDETAIL.STFDSBDNO AS SREFNO, dbo.STUFFINGPRODUCTDETAIL.STFDSBDDATE AS SREFDATE, 
                         dbo.STUFFINGPRODUCTDETAIL.STFDNOP, dbo.STUFFINGPRODUCTDETAIL.STFDQTY, dbo.STUFFINGDETAIL.STFTYPE, GATEINDETAIL_1.GPPLCNAME AS LCHANAME, dbo.SHIPPINGBILLMASTER.EXPRTNAME, 
                         dbo.STUFFINGMASTER.STFTID, dbo.STUFFINGPRODUCTDETAIL.STFDID, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO AS SBMO, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE AS SBDATE, 
                         dbo.SHIPPINGBILLMASTER.SBMDATE, dbo.SHIPPINGBILLMASTER.SBMDNO, dbo.SHIPPINGBILLMASTER.SBMTIME, RIGHT(dbo.STUFFINGMASTER.STFMTIME, 8) AS TIME, dbo.STUFFINGMASTER.CUSRID, 
                         dbo.STUFFINGMASTER.STFBILLREFNAME, dbo.GATEINDETAIL.GINO, dbo.GATEINDETAIL.GIDATE, dbo.STUFFINGMASTER.STF_SBILL_RNO, dbo.STUFFINGMASTER.STF_FORM13_RNO, 
                         dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO, dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLDATE, dbo.EXPORT_OPERATIONTYPEMASTER.EOPTDESC, dbo.COMPANYBANKMASTER.CBANKMDESC, 
                         dbo.COMPANYBANKMASTER.CBANKMACCODE, dbo.COMPANYBANKMASTER.CBANKMIFSCCODE, dbo.COMPANYBANKMASTER.CBANKMBRANCHNAME, V.STFMDNO 'STFNO', V.STFMDATE 'STFDATE',
						 VT.VTDID, VT.COMPYID,  VT.SDPTID, VT.VTDATE, RIGHT(VT.VTTIME, 8) AS VTTIME, VT.VTNO, VT.VTDNO, VT.VHLNO, VT.VTTYPE, VT.DRVNAME,
						 VT.VTREMRKS, VT.VTQTY, VT.CUSRID AS EMPNAME, VT.VTSSEALNO, VT.QRCDIMGPATH, VT.VTCTYPE, VT.GTRNSPRTNAME, vt.TRNSPRTNAME
FROM            dbo.COMPANYBANKMASTER INNER JOIN
                         dbo.GATEINDETAIL INNER JOIN
                         dbo.EXPORTSHIPPINGBILLMASTER INNER JOIN
                         dbo.SHIPPINGBILLDETAIL INNER JOIN
                         dbo.STUFFINGPRODUCTDETAIL ON dbo.SHIPPINGBILLDETAIL.SBDID = dbo.STUFFINGPRODUCTDETAIL.SBDID INNER JOIN
                         dbo.SHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID ON dbo.EXPORTSHIPPINGBILLMASTER.ESBMID = dbo.SHIPPINGBILLDETAIL.ESBMID INNER JOIN
                         dbo.STUFFINGDETAIL ON dbo.STUFFINGPRODUCTDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID INNER JOIN
                         dbo.COMPANYMASTER INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.COMPANYMASTER.COMPID = dbo.COMPANYACCOUNTINGDETAIL.COMPID INNER JOIN                         
                         dbo.STUFFINGMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPYID = dbo.STUFFINGMASTER.COMPYID ON 
                         dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID ON dbo.GATEINDETAIL.GIDID = dbo.SHIPPINGBILLDETAIL.GIDID ON 
                         dbo.COMPANYBANKMASTER.COMPID = dbo.COMPANYMASTER.COMPID LEFT OUTER JOIN
                         dbo.EXPORTSHIPPINGBILLDETAIL ON dbo.EXPORTSHIPPINGBILLMASTER.ESBMID = dbo.EXPORTSHIPPINGBILLDETAIL.ESBMID AND 
                         dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLNO = dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO LEFT OUTER JOIN
                         dbo.EXPORTSLABTYPEMASTER ON dbo.STUFFINGMASTER.SLABTID = dbo.EXPORTSLABTYPEMASTER.SLABTID LEFT OUTER JOIN
                         dbo.EXPORT_OPERATIONTYPEMASTER ON dbo.STUFFINGMASTER.EOPTID = dbo.EXPORT_OPERATIONTYPEMASTER.EOPTID LEFT OUTER JOIN
             dbo.GATEINDETAIL AS GATEINDETAIL_1 ON dbo.STUFFINGDETAIL.GIDID = GATEINDETAIL_1.GIDID LEFT OUTER JOIN
                         dbo.CONTAINERSIZEMASTER ON GATEINDETAIL_1.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID left join 
						 VW_SHUTOUT_STUFFING_DETAIL_PRINT_ASSGN V(NOLOCK) ON  dbo.SHIPPINGBILLMASTER.SBMDNO = V.SBMDNO AND SHIPPINGBILLMASTER.SBMDATE = V.SBMDATE INNER JOIN
						 SHUTOUTVTDETAIL VT (NOLOCK) ON STUFFINGMASTER.STFMID = VT.STFMID INNER JOIN 
						 dbo.TMPRPT_IDS ON VT.VTDID = dbo.TMPRPT_IDS.RPTID 
where STUFFINGMASTER.STFTID=2
GROUP BY  dbo.COMPANYMASTER.COMPNAME, dbo.COMPANYMASTER.COMPADDR, dbo.TMPRPT_IDS.KUSRID, dbo.TMPRPT_IDS.RPTID, dbo.STUFFINGMASTER.STFMID, dbo.TMPRPT_IDS.OPTNSTR, 
                         dbo.STUFFINGMASTER.STFMNO, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMDATE, dbo.STUFFINGMASTER.STFMTIME, dbo.STUFFINGMASTER.STFMNAME, 
                         dbo.SHIPPINGBILLDETAIL.PRDTDESC, GATEINDETAIL_1.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.STUFFINGPRODUCTDETAIL.STFDSBNO, 
                         dbo.STUFFINGPRODUCTDETAIL.STFDSBDATE , dbo.STUFFINGPRODUCTDETAIL.STFDSBDNO , dbo.STUFFINGPRODUCTDETAIL.STFDSBDDATE , 
                         dbo.STUFFINGPRODUCTDETAIL.STFDNOP, dbo.STUFFINGPRODUCTDETAIL.STFDQTY, dbo.STUFFINGDETAIL.STFTYPE, GATEINDETAIL_1.GPPLCNAME , dbo.SHIPPINGBILLMASTER.EXPRTNAME, 
                         dbo.STUFFINGMASTER.STFTID, dbo.STUFFINGPRODUCTDETAIL.STFDID, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO , dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE , 
                         dbo.SHIPPINGBILLMASTER.SBMDATE, dbo.SHIPPINGBILLMASTER.SBMDNO, dbo.SHIPPINGBILLMASTER.SBMTIME, RIGHT(dbo.STUFFINGMASTER.STFMTIME, 8) , dbo.STUFFINGMASTER.CUSRID, 
                         dbo.STUFFINGMASTER.STFBILLREFNAME, dbo.GATEINDETAIL.GINO, dbo.GATEINDETAIL.GIDATE, dbo.STUFFINGMASTER.STF_SBILL_RNO, dbo.STUFFINGMASTER.STF_FORM13_RNO, 
                         dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO, dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLDATE, dbo.EXPORT_OPERATIONTYPEMASTER.EOPTDESC, dbo.COMPANYBANKMASTER.CBANKMDESC, 
                         dbo.COMPANYBANKMASTER.CBANKMACCODE, dbo.COMPANYBANKMASTER.CBANKMIFSCCODE, dbo.COMPANYBANKMASTER.CBANKMBRANCHNAME, V.STFMDNO , V.STFMDATE,
						 VT.VTDID, VT.COMPYID,  VT.SDPTID, VT.VTDATE, RIGHT(VT.VTTIME, 8) , VT.VTNO, VT.VTDNO, VT.VHLNO, VT.VTTYPE, VT.DRVNAME,
						 VT.VTREMRKS, VT.VTQTY, VT.CUSRID, VT.VTSSEALNO, VT.QRCDIMGPATH, VT.VTCTYPE, VT.GTRNSPRTNAME, vt.TRNSPRTNAME
ORDER BY dbo.STUFFINGPRODUCTDETAIL.STFDID


