ALTER VIEW [dbo].[VW_SHIPPINGBILL_GATEINT_TRUCKNO_CBX_ASSGN]
AS

SELECT     TOP 100 PERCENT GATEINDETAIL.GIDID,isnull(EXPORTSHIPPINGBILLMASTER.EXPRTID,0) as EXPRTID ,ISNULL(SUM(SHIPPINGBILLDETAIL.SBDNOP),0) AS SBDNOP, 
         ISNULL(EXPORTSHIPPINGBILLMASTER.ESBMDNO,'-') as ESBMDNO,
         ISNULL(EXPORTSHIPPINGBILLMASTER.ESBMID,0) as ESBMID 
FROM    GATEINDETAIL (nolock)  LEFT Join 
       EXPORTSHIPPINGBILLMASTER (nolock) ON GATEINDETAIL.ESBMID = EXPORTSHIPPINGBILLMASTER.ESBMID 
	    Left Join
	   SHIPPINGBILLDETAIL (nolock) ON EXPORTSHIPPINGBILLMASTER.ESBMID = SHIPPINGBILLDETAIL.ESBMID left join 
	   SHIPPINGBILLMASTER (nolock) ON SHIPPINGBILLMASTER.SBMID = SHIPPINGBILLDETAIL.SBMID

	   where GATEINDETAIL.CONTNRID=1 --and isnull(SHIPPINGBILLDETAIL.SBDID,0) = 0
	   
	   GROUP BY GATEINDETAIL.GIDID, EXPORTSHIPPINGBILLMASTER.EXPRTID,EXPORTSHIPPINGBILLMASTER.ESBMDNO,EXPORTSHIPPINGBILLMASTER.ESBMID
ORDER BY GATEINDETAIL.GIDID, EXPORTSHIPPINGBILLMASTER.EXPRTID,EXPORTSHIPPINGBILLMASTER.ESBMDNO,EXPORTSHIPPINGBILLMASTER.ESBMID
