create VIEW dbo.VW_SHUTOUT_STUFFING_DETAIL_PRINT_ASSGN
AS
SELECT        TOP (100) PERCENT dbo.COMPANYMASTER.COMPNAME, dbo.COMPANYMASTER.COMPADDR, dbo.STUFFINGMASTER.STFMID, 
                         dbo.STUFFINGMASTER.STFMNO, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMDATE, dbo.STUFFINGMASTER.STFMTIME, dbo.STUFFINGMASTER.STFMNAME, 
                         dbo.SHIPPINGBILLDETAIL.PRDTDESC, GATEINDETAIL_1.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.STUFFINGPRODUCTDETAIL.STFDSBNO AS SBMO1, 
                         dbo.STUFFINGPRODUCTDETAIL.STFDSBDATE AS SBDATE1, dbo.STUFFINGPRODUCTDETAIL.STFDSBDNO AS SREFNO, dbo.STUFFINGPRODUCTDETAIL.STFDSBDDATE AS SREFDATE, 
                         dbo.STUFFINGPRODUCTDETAIL.STFDNOP, dbo.STUFFINGPRODUCTDETAIL.STFDQTY, dbo.STUFFINGDETAIL.STFTYPE, GATEINDETAIL_1.GPPLCNAME AS LCHANAME, dbo.SHIPPINGBILLMASTER.EXPRTNAME, 
                         dbo.STUFFINGMASTER.STFTID, dbo.STUFFINGPRODUCTDETAIL.STFDID, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO AS SBMO, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE AS SBDATE, 
                         dbo.SHIPPINGBILLMASTER.SBMDATE, dbo.SHIPPINGBILLMASTER.SBMDNO, dbo.SHIPPINGBILLMASTER.SBMTIME, RIGHT(dbo.STUFFINGMASTER.STFMTIME, 8) AS TIME, dbo.STUFFINGMASTER.CUSRID, 
                         dbo.STUFFINGMASTER.STFBILLREFNAME, dbo.GATEINDETAIL.GINO, dbo.GATEINDETAIL.GIDATE, dbo.STUFFINGMASTER.STF_SBILL_RNO, dbo.STUFFINGMASTER.STF_FORM13_RNO, 
                         dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO, dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLDATE, dbo.EXPORT_OPERATIONTYPEMASTER.EOPTDESC, dbo.COMPANYBANKMASTER.CBANKMDESC, 
                         dbo.COMPANYBANKMASTER.CBANKMACCODE, dbo.COMPANYBANKMASTER.CBANKMIFSCCODE, dbo.COMPANYBANKMASTER.CBANKMBRANCHNAME
FROM            dbo.COMPANYBANKMASTER INNER JOIN
                         dbo.GATEINDETAIL INNER JOIN
                         dbo.EXPORTSHIPPINGBILLMASTER INNER JOIN
                         dbo.SHIPPINGBILLDETAIL INNER JOIN
                         dbo.STUFFINGPRODUCTDETAIL ON dbo.SHIPPINGBILLDETAIL.SBDID = dbo.STUFFINGPRODUCTDETAIL.SBDID INNER JOIN
                         dbo.SHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID ON dbo.EXPORTSHIPPINGBILLMASTER.ESBMID = dbo.SHIPPINGBILLDETAIL.ESBMID INNER JOIN
                         dbo.STUFFINGDETAIL ON dbo.STUFFINGPRODUCTDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID INNER JOIN
                         dbo.COMPANYMASTER INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.COMPANYMASTER.COMPID = dbo.COMPANYACCOUNTINGDETAIL.COMPID INNER JOIN                         
                         dbo.STUFFINGMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPYID = dbo.STUFFINGMASTER.COMPYID ON 
                         dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID ON dbo.GATEINDETAIL.GIDID = dbo.SHIPPINGBILLDETAIL.GIDID ON 
                         dbo.COMPANYBANKMASTER.COMPID = dbo.COMPANYMASTER.COMPID LEFT OUTER JOIN
                         dbo.EXPORTSHIPPINGBILLDETAIL ON dbo.EXPORTSHIPPINGBILLMASTER.ESBMID = dbo.EXPORTSHIPPINGBILLDETAIL.ESBMID AND 
                         dbo.STUFFINGPRODUCTDETAIL.ESBD_SBILLNO = dbo.EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO LEFT OUTER JOIN
                         dbo.EXPORTSLABTYPEMASTER ON dbo.STUFFINGMASTER.SLABTID = dbo.EXPORTSLABTYPEMASTER.SLABTID LEFT OUTER JOIN
                         dbo.EXPORT_OPERATIONTYPEMASTER ON dbo.STUFFINGMASTER.EOPTID = dbo.EXPORT_OPERATIONTYPEMASTER.EOPTID LEFT OUTER JOIN
                         dbo.GATEINDETAIL AS GATEINDETAIL_1 ON dbo.STUFFINGDETAIL.GIDID = GATEINDETAIL_1.GIDID LEFT OUTER JOIN
                         dbo.CONTAINERSIZEMASTER ON GATEINDETAIL_1.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID
where STFTID=0
ORDER BY dbo.STUFFINGPRODUCTDETAIL.STFDID
