USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_STUFFING_CHECKEXISTING_ORGSHIPPINGBILL]    Script Date: 21/04/2022 13:05:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




ALTER VIEW [dbo].[VW_STUFFING_CHECKEXISTING_ORGSHIPPINGBILL]
AS
SELECT  TOP (100) PERCENT EXPORTSHIPPINGBILLDETAIL.ESBMID ,SHIPPINGBILLDETAIL.SBMID,STUFFINGMASTER.STFMID, STUFFINGDETAIL.GIDID , STUFFINGPRODUCTDETAIL.ESBDID  FROM  
      EXPORTSHIPPINGBILLMASTER  (nolock) Inner Join  
	  EXPORTSHIPPINGBILLDETAIL (nolock) on EXPORTSHIPPINGBILLMASTER.ESBMID = EXPORTSHIPPINGBILLDETAIL.ESBMID Inner Join  
	  SHIPPINGBILLDETAIL (nolock) on SHIPPINGBILLDETAIL.ESBMID = EXPORTSHIPPINGBILLDETAIL.ESBMID Inner Join  
	  SHIPPINGBILLMASTER (nolock) on SHIPPINGBILLDETAIL.SBMID = SHIPPINGBILLMASTER.SBMID inner Join  
	  GATEINDETAIL (nolock) on GATEINDETAIL.ESBMID = EXPORTSHIPPINGBILLDETAIL.ESBMID inner Join 
	  STUFFINGDETAIL (nolock) on SHIPPINGBILLDETAIL.GIDID = STUFFINGDETAIL.GIDID and GATEINDETAIL.GIDID = STUFFINGDETAIL.GIDID  inner Join   
	  STUFFINGMASTER (nolock) on STUFFINGDETAIL.STFMID = STUFFINGMASTER.STFMID inner Join  
	  STUFFINGPRODUCTDETAIL (nolock) on EXPORTSHIPPINGBILLDETAIL.ESBDID = STUFFINGPRODUCTDETAIL.ESBDID 




GO


