ALTER view VW_SHUTOUT_VEHICLETICKET_CTRL_ASSGN
AS
SELECT  dbo.STUFFINGMASTER.STFMDATE, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMNAME,  dbo.STUFFINGMASTER.CHAID,
		dbo.STUFFINGMASTER.STFMID,STUFFINGMASTER.STFCATEAID,dbo.STUFFINGMASTER.TRANIMPADDR1, dbo.STUFFINGMASTER.TRANIMPADDR2, 
		dbo.STUFFINGMASTER.TRANIMPADDR3, dbo.STUFFINGMASTER.TRANIMPADDR4, dbo.STUFFINGMASTER.STATEID, CATEATYPEDESC STFCATELOCN,
		cadr.CATEAGSTNO,
        --dbo.STUFFINGPRODUCTDETAIL.STFDSBDNO, dbo.STUFFINGPRODUCTDETAIL.STFCORDNO,     
		--dbo.STUFFINGDETAIL.STFDID, dbo.STUFFINGDETAIL.STFMID,dbo.STUFFINGMASTER.DISPSTATUS ,
		SUM(dbo.STUFFINGPRODUCTDETAIL.STFDNOP) AS STFDNOP, dbo.SHUTOUTVTDETAIL.STFMID as SHUTOUTVTSTFMID
FROM dbo.STUFFINGMASTER INNER JOIN     
   dbo.STUFFINGDETAIL ON dbo.STUFFINGMASTER.STFMID = dbo.STUFFINGDETAIL.STFMID INNER JOIN     
   dbo.STUFFINGPRODUCTDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID   
   LEFT JOIN dbo.SHUTOUTVTDETAIL ON dbo.STUFFINGMASTER.STFMID = dbo.SHUTOUTVTDETAIL.STFMID
   join CATEGORY_ADDRESS_DETAIL cadr (nolock) on STUFFINGMASTER.STFCATEAID = cadr.CATEAID
WHERE STFTID = 2
AND dbo.STUFFINGMASTER.DISPSTATUS = 0
--and STFMDATE>='2023-01-01'
--AND dbo.SHUTOUTVTDETAIL.STFMID IS NULL
group by  dbo.STUFFINGMASTER.STFMDATE, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMNAME,  dbo.STUFFINGMASTER.CHAID,
dbo.STUFFINGMASTER.STFMID,STUFFINGMASTER.STFCATEAID,dbo.STUFFINGMASTER.TRANIMPADDR1, dbo.STUFFINGMASTER.TRANIMPADDR2, 
		dbo.STUFFINGMASTER.TRANIMPADDR3, dbo.STUFFINGMASTER.TRANIMPADDR4, dbo.STUFFINGMASTER.STATEID, CATEATYPEDESC,
		cadr.CATEAGSTNO,  dbo.SHUTOUTVTDETAIL.STFMID
--,   dbo.STUFFINGPRODUCTDETAIL.STFDSBDNO, dbo.STUFFINGPRODUCTDETAIL.STFCORDNO,
--		dbo.STUFFINGDETAIL.STFDID, dbo.STUFFINGDETAIL.STFMID,dbo.STUFFINGMASTER.DISPSTATUS 



