CREATE VIEW dbo.VW_SHIPPINGBILL_EXPORT_GATE_IN_CTRL_ASSGN
AS
SELECT     dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.GIDATE, dbo.GATEINDETAIL.PRDTGID, dbo.GATEINDETAIL.PRDTTID, dbo.GATEINDETAIL.GPNOP, 
                      dbo.GATEINDETAIL.GPWGHT, dbo.GATEINDETAIL.PRDTDESC, dbo.PRODUCTGROUPMASTER.PRDTGDESC, 
                      ISNULL(dbo.VW_SHIPPINGBILL_EXPORT_GATE_IN_CTRL_ASSGN_01.SBDNOP, 0) AS SBDNOP
FROM         dbo.GATEINDETAIL INNER JOIN
                      dbo.PRODUCTGROUPMASTER ON dbo.GATEINDETAIL.PRDTGID = dbo.PRODUCTGROUPMASTER.PRDTGID LEFT OUTER JOIN
                      dbo.VW_SHIPPINGBILL_EXPORT_GATE_IN_CTRL_ASSGN_01 ON 
                      dbo.GATEINDETAIL.GIDID = dbo.VW_SHIPPINGBILL_EXPORT_GATE_IN_CTRL_ASSGN_01.GIDID
WHERE     (dbo.GATEINDETAIL.SDPTID = 2)

