
ALTER VIEW [dbo].[VW_SERVICE_TAX_RPT_01]
AS

SELECT     TRANMID, 
SUM(CASE CFID WHEN 2 THEN DEDVALUE ELSE 0 END) AS STAXAMT,
SUM(CASE CFID WHEN 3 THEN DEDVALUE ELSE 0 END) AS SBCAMT,
SUM(CASE CFID WHEN 4 THEN DEDVALUE ELSE 0 END) AS KKCAMT,
SUM(CASE CFID WHEN 5 THEN DEDVALUE ELSE 0 END) AS CGSTAMT,
SUM(CASE CFID WHEN 6 THEN DEDVALUE ELSE 0 END) AS SGSTAMT,
SUM(CASE CFID WHEN 7 THEN DEDVALUE ELSE 0 END) AS IGSTAMT
FROM         dbo.BONDTRANSACTIONMASTERFACTOR
where      (CFID IN(2,3,4,5,6,7))
GROUP BY TRANMID