-- select * from VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN where sbmid = 16653
ALTER VIEW [dbo].[VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN]
AS
SELECT     TOP (100) PERCENT dbo.SHIPPINGBILLMASTER.CHAID, dbo.SHIPPINGBILLDETAIL.SBMID, dbo.SHIPPINGBILLDETAIL.SBDID, 
                      LTRIM(dbo.SHIPPINGBILLMASTER.SBMDNO) + '(' + dbo.VW_YEAR_DETAIL_CBX_ASSGN.YRDESC + ')' AS SBMDNO, 
                      dbo.SHIPPINGBILLMASTER.SBMDATE, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE, 
                      dbo.SHIPPINGBILLDETAIL.SBDNO, dbo.SHIPPINGBILLDETAIL.SBDDNO, dbo.SHIPPINGBILLDETAIL.SBDDATE, dbo.SHIPPINGBILLDETAIL.PRDTDESC, 
                      --dbo.SHIPPINGBILLDETAIL.SBDNOP, dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.KUSRID, 
                      --dbo.SHIPPINGBILLDETAIL.SBDNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0) 
					     dbo.EXPORTSHIPPINGBILLDETAIL.ESBMNOP AS SBDNOP, dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.KUSRID, 
                      dbo.EXPORTSHIPPINGBILLDETAIL.ESBMNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0) 
                      - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.TRANDNOP, 0) 
                      - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.NOP, 0) AS BNOP,
					 ISNULL(dbo.GATEINDETAIL.GIDID,0) AS  GIDID,ISNULL(dbo.GATEINDETAIL.CONTNRNO,'') AS CONTNRNO,
					 ISNULL(EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO, '') ESBD_SBILLNO, ISNULL(ESBD_SBILLDATE, '') ESBD_SBILLDATE
FROM         dbo.SHIPPINGBILLDETAIL INNER JOIN
                      dbo.SHIPPINGBILLMASTER ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID INNER JOIN
                      dbo.VW_YEAR_DETAIL_CBX_ASSGN ON dbo.SHIPPINGBILLMASTER.COMPYID = dbo.VW_YEAR_DETAIL_CBX_ASSGN.COMPYID INNER JOIN
                      (dbo.EXPORTSHIPPINGBILLMASTER LEFT JOIN DBO.EXPORTSHIPPINGBILLDETAIL ON dbo.EXPORTSHIPPINGBILLMASTER.ESBMID = DBO.EXPORTSHIPPINGBILLDETAIL.ESBMID)
								ON dbo.SHIPPINGBILLDETAIL.ESBMID = dbo.EXPORTSHIPPINGBILLMASTER.ESBMID LEFT OUTER JOIN
                      dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03 ON 
                      dbo.SHIPPINGBILLDETAIL.SBDID = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.SBDID LEFT OUTER JOIN
                      dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02 ON 
                      dbo.SHIPPINGBILLDETAIL.SBDID = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.SBDID LEFT OUTER JOIN
                      dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01 ON 
                      dbo.SHIPPINGBILLDETAIL.SBDID = dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.SBDID LEFT OUTER JOIN 
					  dbo.GATEINDETAIL ON
					  dbo.SHIPPINGBILLDETAIL.GIDID = dbo.GATEINDETAIL.GIDID 
WHERE     (dbo.SHIPPINGBILLDETAIL.SBDNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0) 
                      - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.TRANDNOP, 0) 
                      - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.NOP, 0) > 0)
GROUP BY dbo.SHIPPINGBILLDETAIL.SBMID, dbo.SHIPPINGBILLDETAIL.SBDDNO, dbo.SHIPPINGBILLDETAIL.SBDNO, dbo.SHIPPINGBILLDETAIL.SBDID, 
                      dbo.SHIPPINGBILLDETAIL.SBDDATE, dbo.SHIPPINGBILLDETAIL.PRDTDESC, dbo.EXPORTSHIPPINGBILLDETAIL.ESBMNOP, 
                      dbo.EXPORTSHIPPINGBILLDETAIL.ESBMNOP - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01.STFDNOP, 0) 
                      - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_02.TRANDNOP, 0) 
                      - ISNULL(dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.NOP, 0), LTRIM(dbo.SHIPPINGBILLMASTER.SBMDNO) 
                      + '(' + dbo.VW_YEAR_DETAIL_CBX_ASSGN.YRDESC + ')', dbo.SHIPPINGBILLMASTER.SBMDATE, dbo.SHIPPINGBILLMASTER.CHAID, 
                      dbo.EXPORTSHIPPINGBILLMASTER.ESBMDNO, dbo.EXPORTSHIPPINGBILLMASTER.ESBMDATE, 
                      dbo.VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_03.KUSRID,dbo.GATEINDETAIL.GIDID,dbo.GATEINDETAIL.CONTNRNO,
					 ISNULL(EXPORTSHIPPINGBILLDETAIL.ESBD_SBILLNO, ''), ISNULL(ESBD_SBILLDATE, '')
ORDER BY dbo.SHIPPINGBILLDETAIL.SBDNO






