CREATE VIEW [dbo].[VW_STUFFING_SBILLNO_REFNO_CBX_ASSGN_01]
AS
SELECT     TOP 100 PERCENT SBDID, ESBD_SBILLNO,SUM(STFDNOP) AS STFDNOP
FROM         dbo.STUFFINGPRODUCTDETAIL (nolock) --left join exportshippingbilldetail (nolock)  on  STUFFINGPRODUCTDETAIL.SBDID = exportshippingbilldetail.ESBDID
GROUP BY SBDID, ESBD_SBILLNO
