USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_STUFF_GATEIN_CTRL_ASSGN]    Script Date: 06/08/2021 20:01:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER VIEW [dbo].[VW_STUFF_GATEIN_CTRL_ASSGN]
AS
SELECT    dbo.GATEINDETAIL.GIDID, dbo.STUFFINGPRODUCTDETAIL.STFDID, MAX(dbo.STUFFINGPRODUCTDETAIL.STFDSBNO) AS STFDSBNO, 
                      MAX(dbo.STUFFINGPRODUCTDETAIL.STFDSBDNO) AS STFDSBDNO, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                      dbo.SHIPPINGBILLMASTER.CHANAME, MAX(dbo.SHIPPINGBILLMASTER.EXPRTNAME) AS EXPRTNAME, dbo.GATEINDETAIL.PRDTDESC, 
                      dbo.GATEINDETAIL.GIDATE,ISNULL(dbo.GATEINDETAIL.DRVNAME,'') AS DRVNAME,ISNULL(dbo.GATEINDETAIL.LPSEALNO,'') AS LPSEALNO,
					  ISNULL(dbo.GATEINDETAIL.CSEALNO,'') AS CSEALNO 
FROM         dbo.STUFFINGPRODUCTDETAIL (nolock)  INNER JOIN
                      dbo.STUFFINGDETAIL (nolock)  ON dbo.STUFFINGPRODUCTDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID INNER JOIN
                      dbo.GATEINDETAIL (nolock)  ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                      dbo.CONTAINERSIZEMASTER (nolock)  ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                      dbo.SHIPPINGBILLDETAIL (nolock)  ON dbo.STUFFINGPRODUCTDETAIL.SBDID = dbo.SHIPPINGBILLDETAIL.SBDID INNER JOIN
                      dbo.SHIPPINGBILLMASTER (nolock)  ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID  
					  WHERE dbo.GATEINDETAIL.SDPTID = 2
GROUP BY dbo.GATEINDETAIL.GIDID,dbo.STUFFINGPRODUCTDETAIL.STFDID, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                      dbo.GATEINDETAIL.PRDTDESC, dbo.GATEINDETAIL.GIDATE, dbo.SHIPPINGBILLMASTER.CHANAME,dbo.GATEINDETAIL.DRVNAME,
					  dbo.GATEINDETAIL.LPSEALNO,dbo.GATEINDETAIL.CSEALNO




GO


