CREATE VIEW dbo.VW_TAB5_DO_FLX_ASSGN_01
AS
SELECT     dbo.TRANSACTIONDETAIL.BILLEDID, dbo.TRANSACTIONDETAIL.TRANDID
FROM         dbo.TRANSACTIONMASTER INNER JOIN
                      dbo.TRANSACTIONDETAIL ON dbo.TRANSACTIONMASTER.TRANMID = dbo.TRANSACTIONDETAIL.TRANMID
WHERE     (dbo.TRANSACTIONMASTER.DISPSTATUS = 0) AND (dbo.TRANSACTIONMASTER.SDPTID = 1) AND (dbo.TRANSACTIONDETAIL.BILLEDID > 0)

