-- select * from [VW_TRANSACTION_PERFORMA_CRY_PRINT_ASSGN_01] where tranmid = 669
alter VIEW [dbo].[VW_TRANSACTION_PERFORMA_CRY_PRINT_ASSGN_01]
AS
SELECT     dbo.PERFORMA_TRANSACTIONDETAIL.TRANMID, 
SUM(CASE dbo.CONTAINERSIZEMASTER.CONTNRSID WHEN 3 THEN 1 ELSE 0 END) AS COL1, 
SUM(CASE dbo.CONTAINERSIZEMASTER.CONTNRSID WHEN 4 THEN 1 ELSE 0 END) AS COL2 
FROM         dbo.PERFORMA_TRANSACTIONDETAIL left JOIN
                      dbo.BILLENTRYDETAIL ON dbo.PERFORMA_TRANSACTIONDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID left JOIN
                      dbo.GATEINDETAIL ON dbo.PERFORMA_TRANSACTIONDETAIL.TRANDREFID = dbo.GATEINDETAIL.GIDID left JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID
GROUP BY dbo.PERFORMA_TRANSACTIONDETAIL.TRANMID

-- select * from PERFORMA_TRANSACTIONDETAIL where tranmid = 669