-- select * From PERFORMA_TRANSACTIONMASTER where tranmid = 669
-- select * from VW_TRANSACTION_PERFORMA_CRY_PRINT_ASSGN where tranmid = 669
alter VIEW dbo.VW_TRANSACTION_PERFORMA_CRY_PRINT_ASSGN
AS
SELECT        dbo.TMPRPT_IDS.KUSRID, dbo.COMPANYMASTER.COMPNAME, dbo.PERFORMA_TRANSACTIONMASTER.COMPYID, dbo.PERFORMA_TRANSACTIONMASTER.TRANMID, 
                         dbo.PERFORMA_TRANSACTIONMASTER.SDPTID, dbo.PERFORMA_TRANSACTIONMASTER.REGSTRID, dbo.PERFORMA_TRANSACTIONMASTER.TRANBTYPE, dbo.PERFORMA_TRANSACTIONMASTER.TRANDATE, 
                         RIGHT(dbo.PERFORMA_TRANSACTIONMASTER.TRANTIME, 8) AS TRANTIME, dbo.PERFORMA_TRANSACTIONMASTER.TRANNO, dbo.PERFORMA_TRANSACTIONMASTER.TRANDNO, 
                         dbo.PERFORMA_TRANSACTIONMASTER.TRANREFNAME, dbo.PERFORMA_TRANSACTIONMASTER.TRANMODE, dbo.PERFORMA_TRANSACTIONMASTER.TRANMODEDETL, 
                         dbo.PERFORMA_TRANSACTIONMASTER.TRANREFNO, dbo.PERFORMA_TRANSACTIONMASTER.TRANREFDATE, dbo.PERFORMA_TRANSACTIONMASTER.TRANREFBNAME, 
                         dbo.PERFORMA_TRANSACTIONMASTER.TRANREFAMT, dbo.PERFORMA_TRANSACTIONMASTER.TRANGAMT, dbo.PERFORMA_TRANSACTIONMASTER.TRANSAMT, 
                         dbo.PERFORMA_TRANSACTIONMASTER.TRANHAMT, dbo.PERFORMA_TRANSACTIONMASTER.TRANEAMT, dbo.PERFORMA_TRANSACTIONMASTER.TRANFAMT, 
                         dbo.PERFORMA_TRANSACTIONMASTER.TRANAAMT, dbo.PERFORMA_TRANSACTIONMASTER.TRANNAMT, dbo.PERFORMA_TRANSACTIONMASTER.TRANAMTWRDS, 
                         dbo.PERFORMA_TRANSACTIONMASTER.TRANRMKS, dbo.CATEGORYMASTER.CATEADDR, dbo.GATEINDETAIL.IMPRTNAME, dbo.GATEINDETAIL.STMRNAME, 
                         dbo.PERFORMA_TRANSACTIONDETAIL.TRANDREFNAME, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDREFNO, dbo.BILLENTRYMASTER.BILLEMDATE, dbo.BILLENTRYMASTER.BILLEMTIME, 
                         dbo.PERFORMA_TRANSACTIONDETAIL.TRANIDATE, dbo.PERFORMA_TRANSACTIONDETAIL.TRANSDATE, dbo.PERFORMA_TRANSACTIONDETAIL.TRANEDATE, dbo.PERFORMA_TRANSACTIONDETAIL.TRANVDATE, 
                         dbo.PERFORMA_TRANSACTIONDETAIL.RCOL1, dbo.PERFORMA_TRANSACTIONDETAIL.RCOL2, dbo.PERFORMA_TRANSACTIONDETAIL.RCOL3, dbo.PERFORMA_TRANSACTIONDETAIL.RCOL4, 
                         dbo.PERFORMA_TRANSACTIONDETAIL.RCOL5, dbo.PERFORMA_TRANSACTIONDETAIL.RCOL6, dbo.PERFORMA_TRANSACTIONDETAIL.RCOL7, dbo.PERFORMA_TRANSACTIONDETAIL.RAMT1, 
                         dbo.PERFORMA_TRANSACTIONDETAIL.RAMT2, dbo.PERFORMA_TRANSACTIONDETAIL.RAMT3, dbo.PERFORMA_TRANSACTIONDETAIL.RAMT4, dbo.PERFORMA_TRANSACTIONDETAIL.RAMT5, 
                         dbo.PERFORMA_TRANSACTIONDETAIL.RAMT6, dbo.PERFORMA_TRANSACTIONDETAIL.RAMT7, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDQTY, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDGAMT, 
                         dbo.PERFORMA_TRANSACTIONDETAIL.TRANDSAMT, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDHAMT, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDEAMT, 
                         dbo.PERFORMA_TRANSACTIONDETAIL.TRANDFAMT, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDAAMT, dbo.PERFORMA_TRANSACTIONDETAIL.TRANDNAMT, dbo.GATEINDETAIL.VSLNAME, 
                         dbo.GATEINDETAIL.VOYNO, dbo.BILLENTRYMASTER.BLNO, dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.PRDTDESC, 
                         ISNULL(dbo.VW_TRANSACTION_PERFORMA_PRINT_ASSGN_01.BNOP, 0) AS BOENOP, ISNULL(dbo.VW_TRANSACTION_PERFORMA_PRINT_ASSGN_01.BWGHT, 0) AS BOEWGHT, 
                         dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.PERFORMA_TRANSACTIONMASTER.LMUSRID, dbo.PERFORMA_TRANSACTIONMASTER.CUSRID, 
                         dbo.PERFORMA_TRANSACTIONMASTER.CUSRID AS USRNAME, dbo.PERFORMA_TRANSACTIONMASTER.DISPSTATUS, dbo.SLOTMASTER.SLOTDESC, dbo.SLOTMASTER.SLOTCODE, 
                         dbo.ROWMASTER.ROWDESC, dbo.ROWMASTER.ROWCODE, dbo.GATEINDETAIL.GPWGHT, dbo.BILLENTRYDETAIL.DWGHT, dbo.DELIVERYORDERMASTER.DODNO, dbo.DELIVERYORDERMASTER.DODATE, 
                         dbo.DELIVERYORDERMASTER.DOTIME, dbo.OPENSHEETMASTER.OSMLNAME, 
						 dbo.COMPANYMASTER.COMPPDESC1, dbo.COMPANYMASTER.COMPPDESC2, dbo.CATEGORYMASTER.CATEMAIL, 
                         dbo.CATEGORYMASTER.CATEPHN1, dbo.CATEGORYMASTER.CATEPHN2, dbo.CATEGORYMASTER.CATEPHN3, dbo.CATEGORYMASTER.CATEPHN4, dbo.CONTAINERTYPEMASTER.CONTNRTDESC, 
                         dbo.VW_TRANSACTION_PERFORMA_CRY_PRINT_ASSGN_01.COL1, dbo.VW_TRANSACTION_PERFORMA_CRY_PRINT_ASSGN_01.COL2, dbo.PERFORMA_TRANSACTIONMASTER.TRANNARTN, 
                         ISNULL(dbo.PERFORMA_TRANSACTIONMASTER.TRANHBLNO, dbo.BILLENTRYMASTER.BLNO) AS TRANHBLNO, dbo.PERFORMA_TRANSACTIONMASTER.TRANPONO, dbo.GATEINDETAIL.GIDID, 
                         dbo.GATEINDETAIL.CHANAME, dbo.GATEINDETAIL.CLNTNAME, dbo.GATEINDETAIL.SHPRNAME, dbo.GATEINDETAIL.GPPLCNAME, dbo.PERFORMA_TRANSACTIONMASTER.TRANIMPADDR1, 
                         dbo.PERFORMA_TRANSACTIONMASTER.TRANIMPADDR2, dbo.PERFORMA_TRANSACTIONMASTER.TRANIMPADDR3, dbo.PERFORMA_TRANSACTIONMASTER.TRANIMPADDR4, 
                         dbo.PERFORMA_TRANSACTIONDETAIL.TRANDAHAMT, dbo.PERFORMA_TRANSACTIONMASTER.TRANAHAMT, dbo.PERFORMA_TRANSACTIONMASTER.TRANCGSTAMT, 
                         dbo.PERFORMA_TRANSACTIONMASTER.TRANSGSTAMT, dbo.PERFORMA_TRANSACTIONMASTER.TRANIGSTAMT,
						 dbo.PERFORMA_TRANSACTIONMASTER.CATEAGSTNO  'CATEAGSTNO',
                         dbo.PERFORMA_TRANSACTIONMASTER.STRG_HSNCODE, dbo.PERFORMA_TRANSACTIONMASTER.HANDL_HSNCODE, dbo.PERFORMA_TRANSACTIONMASTER.STRG_TAXABLE_AMT, 
                         dbo.PERFORMA_TRANSACTIONMASTER.HANDL_TAXABLE_AMT, dbo.PERFORMA_TRANSACTIONMASTER.STRG_CGST_EXPRN, dbo.PERFORMA_TRANSACTIONMASTER.STRG_SGST_EXPRN, 
                         dbo.PERFORMA_TRANSACTIONMASTER.STRG_IGST_EXPRN, dbo.PERFORMA_TRANSACTIONMASTER.STRG_CGST_AMT, dbo.PERFORMA_TRANSACTIONMASTER.STRG_SGST_AMT, 
                         dbo.PERFORMA_TRANSACTIONMASTER.STRG_IGST_AMT, dbo.PERFORMA_TRANSACTIONMASTER.HANDL_CGST_EXPRN, dbo.PERFORMA_TRANSACTIONMASTER.HANDL_SGST_EXPRN, 
                         dbo.PERFORMA_TRANSACTIONMASTER.HANDL_IGST_EXPRN, dbo.PERFORMA_TRANSACTIONMASTER.HANDL_CGST_AMT, dbo.PERFORMA_TRANSACTIONMASTER.HANDL_SGST_AMT, 
                         dbo.PERFORMA_TRANSACTIONMASTER.HANDL_IGST_AMT, dbo.PERFORMA_TRANSACTIONMASTER.TRAN_COVID_DISC_AMT, dbo.PERFORMA_TRANSACTIONMASTER.TRANBILLREFNO, 
                         STATEMASTER_1.STATEDESC, STATEMASTER_1.STATECODE, dbo.PERFORMA_TRANSACTIONMASTER.TRANCSNAME, 
						 isnull(dbo.OPENSHEETMASTER.OSBBCHACATEAGSTNO, PERFORMA_TRANSACTIONMASTER.CHACATEAGSTNO) as OSBBCHACATEAGSTNO,
                         isnull(dbo.OPENSHEETMASTER.OSBBCHAADDR1,  PERFORMA_TRANSACTIONMASTER.CHAADDR1) OSBBCHAADDR1, 
						 isnull(dbo.OPENSHEETMASTER.OSBBCHAADDR2,  PERFORMA_TRANSACTIONMASTER.CHAADDR2) OSBBCHAADDR2,
						 isnull( dbo.OPENSHEETMASTER.OSBBCHAADDR3,  PERFORMA_TRANSACTIONMASTER.CHAADDR3) OSBBCHAADDR3,
						 isnull( dbo.OPENSHEETMASTER.OSBBCHAADDR4,  PERFORMA_TRANSACTIONMASTER.CHAADDR4) OSBBCHAADDR4,
						 isnull( dbo.OPENSHEETMASTER.OSBBCHASTATEID,  PERFORMA_TRANSACTIONMASTER.CHASTATEID) OSBBCHASTATEID,
						 isnull(dbo.STATEMASTER.STATEDESC,StateMaster2.STATEDESC) AS OSBBSTATEDESC,
						 isnull( dbo.STATEMASTER.STATECODE,StateMaster2.STATECODE) AS OSBBSTATECODE, 						 
						  isnull(dbo.OPENSHEETMASTER.OSBILLREFNAME,PERFORMA_TRANSACTIONMASTER.TRANREFNAME)  'OSBILLREFNAME', 
                         dbo.COMPANYBANKMASTER.CBANKMDESC, dbo.COMPANYBANKMASTER.CBANKMACCODE, dbo.COMPANYBANKMASTER.CBANKMIFSCCODE, dbo.COMPANYBANKMASTER.CBANKMBRANCHNAME
FROM            dbo.STATEMASTER AS STATEMASTER_1 RIGHT OUTER JOIN
                         dbo.TMPRPT_IDS INNER JOIN
                         dbo.PERFORMA_TRANSACTIONMASTER INNER JOIN
                         dbo.PERFORMA_TRANSACTIONDETAIL ON dbo.PERFORMA_TRANSACTIONMASTER.TRANMID = dbo.PERFORMA_TRANSACTIONDETAIL.TRANMID INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.PERFORMA_TRANSACTIONMASTER.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                         dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID INNER JOIN
                         dbo.CATEGORYMASTER ON dbo.PERFORMA_TRANSACTIONMASTER.TRANREFID = dbo.CATEGORYMASTER.CATEID left JOIN
                         dbo.BILLENTRYDETAIL ON dbo.PERFORMA_TRANSACTIONDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID INNER JOIN
                         --dbo.GATEINDETAIL ON dbo.BILLENTRYDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
						 dbo.GATEINDETAIL ON dbo.PERFORMA_TRANSACTIONDETAIL.TRANDREFID = dbo.GATEINDETAIL.GIDID INNER JOIN						  
                         dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID left JOIN
                         dbo.BILLENTRYMASTER ON dbo.BILLENTRYDETAIL.BILLEMID = dbo.BILLENTRYMASTER.BILLEMID ON dbo.TMPRPT_IDS.RPTID = dbo.PERFORMA_TRANSACTIONMASTER.TRANMID INNER JOIN
                         dbo.CONTAINERTYPEMASTER ON dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID INNER JOIN
                         dbo.VW_TRANSACTION_PERFORMA_CRY_PRINT_ASSGN_01 ON dbo.PERFORMA_TRANSACTIONMASTER.TRANMID = dbo.VW_TRANSACTION_PERFORMA_CRY_PRINT_ASSGN_01.TRANMID INNER JOIN
                         dbo.COMPANYBANKMASTER ON dbo.COMPANYMASTER.COMPID = dbo.COMPANYBANKMASTER.COMPID ON STATEMASTER_1.STATEID = dbo.PERFORMA_TRANSACTIONMASTER.STATEID LEFT OUTER JOIN
                         dbo.STATEMASTER left JOIN
                         dbo.OPENSHEETDETAIL left JOIN
                         dbo.OPENSHEETMASTER ON dbo.OPENSHEETDETAIL.OSMID = dbo.OPENSHEETMASTER.OSMID ON dbo.STATEMASTER.STATEID = dbo.OPENSHEETMASTER.OSBBCHASTATEID ON 
                         dbo.BILLENTRYDETAIL.BILLEDID = dbo.OPENSHEETDETAIL.BILLEDID LEFT OUTER JOIN
                         dbo.DELIVERYORDERDETAIL LEFT OUTER JOIN
                         dbo.DELIVERYORDERMASTER ON dbo.DELIVERYORDERDETAIL.DOMID = dbo.DELIVERYORDERMASTER.DOMID ON 
                         dbo.BILLENTRYDETAIL.BILLEDID = dbo.DELIVERYORDERDETAIL.BILLEDID LEFT OUTER JOIN
                         dbo.ROWMASTER RIGHT OUTER JOIN
                         dbo.SLOTMASTER ON dbo.ROWMASTER.ROWID = dbo.SLOTMASTER.ROWID ON dbo.GATEINDETAIL.SLOTID = dbo.SLOTMASTER.SLOTID LEFT OUTER JOIN
                         dbo.VW_TRANSACTION_PERFORMA_PRINT_ASSGN_01 ON dbo.PERFORMA_TRANSACTIONMASTER.TRANMID = dbo.VW_TRANSACTION_PERFORMA_PRINT_ASSGN_01.TRANMID left join
						 STATEMASTER as StateMaster2 on PERFORMA_TRANSACTIONMASTER.CHASTATEID = StateMaster2.STATEID

WHERE        (dbo.PERFORMA_TRANSACTIONMASTER.DISPSTATUS = 0) 
AND (ISNULL(dbo.DELIVERYORDERMASTER.DISPSTATUS, 0) = 0)

