alter VIEW [dbo].[VW_VEHICLETICKET_IMPORT_CONTAINER_CTRL_ASSGN]
AS
SELECT  DISTINCT   dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.GIDATE, dbo.GATEINDETAIL.GITIME, dbo.GATEINDETAIL.GIDNO, dbo.GATEINDETAIL.CONTNRNO, 
                      dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.GPLNO, dbo.GATEINDETAIL.VSLNAME, dbo.GATEINDETAIL.VOYNO, 
                      dbo.GATEINDETAIL.IGMNO, dbo.GATEINDETAIL.IMPRTNAME, dbo.GATEINDETAIL.STMRNAME, dbo.GATEINDETAIL.LPSEALNO, 
                      dbo.GATEINDETAIL.CSEALNO, dbo.GATEINDETAIL.SLOTID, dbo.AUTHORIZATIONSLIPMASTER.ASLMDNO, dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, 
                      dbo.AUTHORIZATIONSLIPDETAIL.VHLNO, dbo.AUTHORIZATIONSLIPDETAIL.DRVNAME, dbo.GATEINDETAIL.PRDTDESC, 
                      dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE, dbo.OPENSHEETMASTER.OSMNAME, dbo.OPENSHEETMASTER.BOENO, 
                      dbo.OPENSHEETMASTER.BOEDATE, dbo.OPENSHEETMASTER.DOTYPE, dbo.OPENSHEETMASTER.DODATE, dbo.OPENSHEETDETAIL.LSEALNO, 
                      dbo.OPENSHEETDETAIL.SSEALNO, dbo.AUTHORIZATIONSLIPMASTER.ASLMDATE, dbo.AUTHORIZATIONSLIPMASTER.ASLMTIME, 
                      ISNULL(dbo.DELIVERYORDERDETAIL.DODID, 0) AS DODID, dbo.DELIVERYORDERMASTER.DODATE AS DOMDATE, 
                      dbo.DELIVERYORDERMASTER.DODNO,dbo.GATEINDETAIL.STMRID,dbo.GATEINDETAIL.CONTNRSID,dbo.GATEINDETAIL.CONTNRTID,
					  isnull(AUTHORIZATIONSLIPDETAIL.ASLOTYPE,0) as ASLOTYPE,isnull(IMPORT_DESTUFF_SLIP_OPERATION_TYPE.OPRTYPEDESC,0) as OPRTYPEDESC,
					  dbo.OPENSHEETMASTER.OSBILLREFNAME,dbo.OPENSHEETMASTER.OSBILLREFID,dbo.OPENSHEETMASTER.CHAID,
					  Convert(varchar,OPENSHEETMASTER.OOCDATE,103) OOCDATE, Convert(varchar,dbo.OPENSHEETMASTER.DODATE,103) DODATEChr
FROM                  dbo.DELIVERYORDERMASTER (NOLOCK)  
                      RIGHT OUTER JOIN  dbo.DELIVERYORDERDETAIL (NOLOCK) ON dbo.DELIVERYORDERMASTER.DOMID = dbo.DELIVERYORDERDETAIL.DOMID 
	                  RIGHT OUTER JOIN  dbo.OPENSHEETMASTER 
	                  INNER JOIN  dbo.AUTHORIZATIONSLIPMASTER 
	                  INNER JOIN  dbo.AUTHORIZATIONSLIPDETAIL 
					  INNER JOIN  dbo.GATEINDETAIL 
					  INNER JOIN  dbo.OPENSHEETDETAIL (NOLOCK) ON dbo.GATEINDETAIL.GIDID = dbo.OPENSHEETDETAIL.GIDID ON 
                                  dbo.AUTHORIZATIONSLIPDETAIL.OSDID = dbo.OPENSHEETDETAIL.OSDID ON 
								  dbo.AUTHORIZATIONSLIPMASTER.ASLMID = dbo.AUTHORIZATIONSLIPDETAIL.ASLMID ON 
								  dbo.OPENSHEETMASTER.OSMID = dbo.OPENSHEETDETAIL.OSMID ON  
								  dbo.DELIVERYORDERDETAIL.DODREFID = dbo.GATEINDETAIL.GIDID 
					  LEFT OUTER JOIN dbo.CONTAINERSIZEMASTER (NOLOCK) ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID 
					  LEFT OUTER JOIN dbo.IMPORT_DESTUFF_SLIP_OPERATION_TYPE (NOLOCK) ON AUTHORIZATIONSLIPDETAIL.ASLOTYPE = dbo.IMPORT_DESTUFF_SLIP_OPERATION_TYPE.OPRTYPE 

