USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[VW_VEHICLETICKET_EXPORT_CONTAINER_CBX_ASSGN_01]    Script Date: 07/08/2021 18:05:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_VEHICLETICKET_EXPORT_CONTAINER_CBX_ASSGN_01]
AS
SELECT     TOP (100) PERCENT GIDID, VTDID
FROM         dbo.VEHICLETICKETDETAIL
WHERE     (SDPTID = 2) AND (GIDID > 0)

GO


