alter VIEW [dbo].[VW_VEHICLETICKET_EXPORT_CONTAINER_CBX_ASSGN_DIRECT]
AS
SELECT     TOP (100) PERCENT dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC
FROM         dbo.STUFFINGDETAIL RIGHT OUTER JOIN
                      dbo.GATEINDETAIL ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID LEFT OUTER JOIN
                      dbo.VW_VEHICLETICKET_EXPORT_CONTAINER_CBX_ASSGN_01 ON 
                      dbo.GATEINDETAIL.GIDID = dbo.VW_VEHICLETICKET_EXPORT_CONTAINER_CBX_ASSGN_01.GIDID LEFT OUTER JOIN
                      dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID LEFT OUTER JOIN
                      dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID
WHERE     (ISNULL(dbo.VW_VEHICLETICKET_EXPORT_CONTAINER_CBX_ASSGN_01.VTDID, 0) = 0) AND (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) AND 
                      (dbo.GATEINDETAIL.GIDATE >= CONVERT(DATETIME, '2022-04-01 00:00:00', 102)) AND (dbo.GATEINDETAIL.DISPSTATUS = 0) AND
					   (dbo.GATEINDETAIL.GPSTYPE IN (4)) AND (dbo.STUFFINGDETAIL.STFDID IS NULL)
GROUP BY dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.GIDID
ORDER BY dbo.GATEINDETAIL.CONTNRNO



