ALTER VIEW [dbo].[VW_VEHICLETICKET_EXPORT_CONTAINER_CTRL_ASSGN_DIRECT]
AS
SELECT     TOP (100) PERCENT 0 AS STFDID, '---' AS STFMDNO, dbo.GATEINDETAIL.GIDATE AS STFMDATE, dbo.GATEINDETAIL.CHANAME, '---' AS EXPRTNAME, 
                      dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.GIDATE, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.PRDTDESC, '---' AS SBILLNO, 
                      '---' AS SBILLDATE, '---' AS SBMDNO, '---' AS SBMDATE, dbo.GATEINDETAIL.SDPTID, dbo.GATEINDETAIL.GPSTYPE,
					  isnull(AUTHORIZATIONSLIPDETAIL.ASLDID,0) as ASLDID,isnull(AUTHORIZATIONSLIPDETAIL.CSEALNO,'') as CSEALNO,
					  isnull(AUTHORIZATIONSLIPDETAIL.ASEALNO,'') as ASEALNO
FROM         dbo.GATEINDETAIL (nolock) INNER JOIN
                      dbo.CONTAINERSIZEMASTER (nolock) ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID inner Join 
					  dbo.AUTHORIZATIONSLIPDETAIL (nolock) On dbo.AUTHORIZATIONSLIPDETAIL.GIDID = dbo.GATEINDETAIL.GIDID Inner Join 
					  dbo.AUTHORIZATIONSLIPMASTER (nolock) On dbo.AUTHORIZATIONSLIPMASTER.ASLMID = dbo.AUTHORIZATIONSLIPDETAIL.ASLMID 

WHERE     (dbo.GATEINDETAIL.SDPTID = 2) AND (dbo.GATEINDETAIL.GPSTYPE IN (4, 5))