ALTER VIEW [dbo].[VW_VEHICLETICKET_EXPORT_CONTAINER_CTRL_ASSGN]
AS
SELECT     TOP 100 PERCENT Isnull(dbo.AUTHORIZATIONSLIPDETAIL.ASLDID,0) as ASLDID, dbo.STUFFINGDETAIL.STFDID, dbo.STUFFINGMASTER.STFMDNO, 
                      dbo.STUFFINGMASTER.STFMDATE, dbo.SHIPPINGBILLMASTER.CHANAME, dbo.SHIPPINGBILLMASTER.EXPRTNAME, 
                      MAX(dbo.STUFFINGPRODUCTDETAIL.STFDSBNO) AS SBILLNO, MAX(dbo.STUFFINGPRODUCTDETAIL.STFDSBDATE) AS SBILLDATE, 
                      MAX(dbo.SHIPPINGBILLMASTER.SBMDNO) AS SBMDNO, MAX(dbo.SHIPPINGBILLMASTER.SBMDATE) AS SBMDATE, dbo.STUFFINGDETAIL.GIDID, 
                      dbo.GATEINDETAIL.GIDATE, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.SHIPPINGBILLDETAIL.PRDTDESC,
					  isnull(AUTHORIZATIONSLIPDETAIL.CSEALNO,'') as CSEALNO,isnull(AUTHORIZATIONSLIPDETAIL.ASEALNO,'') as ASEALNO,
					  isnull(AUTHORIZATIONSLIPDETAIL.SLTID,0) as SLTID,isnull(EXPORT_SEALTYPEMASTER.SLTDESC,'') as SLTDESC,
					    ISNULL(STUFFINGMASTER.EOPTID,0) AS EOPTID
FROM STUFFINGDETAIL (nolock)
					inner Join STUFFINGMASTER (nolock) On STUFFINGDETAIL.STFMID = STUFFINGMASTER.STFMID 
					inner Join STUFFINGPRODUCTDETAIL (nolock)  ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID 
					inner Join SHIPPINGBILLDETAIL  (nolock) ON dbo.STUFFINGPRODUCTDETAIL.SBDID = dbo.SHIPPINGBILLDETAIL.SBDID  
					inner join SHIPPINGBILLMASTER (nolock) ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID  
					inner join GATEINDETAIL (nolock) ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID  
					inner join CONTAINERSIZEMASTER (nolock) ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID 
					inner Join  AUTHORIZATIONSLIPDETAIL (nolock) ON dbo.STUFFINGDETAIL.STFDID = dbo.AUTHORIZATIONSLIPDETAIL.STFDID  
					inner Join  EXPORT_SEALTYPEMASTER ON AUTHORIZATIONSLIPDETAIL.SLTID = EXPORT_SEALTYPEMASTER.SLTID  
					
GROUP BY dbo.STUFFINGDETAIL.STFDID, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMDATE, dbo.SHIPPINGBILLMASTER.EXPRTNAME, 
                      dbo.SHIPPINGBILLMASTER.CHANAME, dbo.STUFFINGDETAIL.GIDID, dbo.GATEINDETAIL.GIDATE, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                      dbo.SHIPPINGBILLDETAIL.PRDTDESC, dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, AUTHORIZATIONSLIPDETAIL.CSEALNO, AUTHORIZATIONSLIPDETAIL.ASEALNO,
					  AUTHORIZATIONSLIPDETAIL.SLTID,
					EXPORT_SEALTYPEMASTER.SLTDESC,STUFFINGMASTER.EOPTID
ORDER BY dbo.STUFFINGDETAIL.STFDID
