-- select * From exbondmaster where EXBONDMASTER.EBNDDNO ='839'
-- select * From [VW_VT_EXBOND_BALANCE_DETAIL_ASSGN] where EBNDDNO ='839'
alter VIEW [dbo].[VW_VT_EXBOND_BALANCE_DETAIL_ASSGN]
AS
SELECT     dbo.BONDMASTER.BNDID, BONDMASTER.BNDDNO, dbo.EXBONDMASTER.EBNDID, EXBONDMASTER.EBNDDNO, dbo.EXBONDMASTER.EBNDCTYPE, dbo.EXBONDMASTER.PRDTGID, dbo.BONDPRODUCTGROUPMASTER.PRDTGDESC, 
					  ISNULL(dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01.VTNOP, 0) 'CUMVTNOP',
					  ISNULL(dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01.VTSPC, 0) 'CUMVTSPC',
                      dbo.EXBONDMASTER.EBNDNOP - ISNULL(dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01.VTNOP, 0) AS BBNOP, 
                      dbo.EXBONDMASTER.EBNDSPC - ISNULL(dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01.VTSPC, 0) AS BBSPC,
					  dbo.BONDMASTER.BNDNOP - ISNULL(dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01.VTNOP, 0) AS BEBNOP, 
                      dbo.BONDMASTER.BNDSPC - ISNULL(dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01.VTSPC, 0) AS BEBSPC
FROM         dbo.EXBONDMASTER (nolock) 
				left JOIN dbo.BONDMASTER (nolock)  on  EXBONDMASTER.BNDID = BONDMASTER.BNDID
				left JOIN dbo.BONDPRODUCTGROUPMASTER (nolock) ON dbo.EXBONDMASTER.PRDTGID = dbo.BONDPRODUCTGROUPMASTER.PRDTGID LEFT OUTER JOIN
                      dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01 (nolock) ON 
                      dbo.EXBONDMASTER.EBNDID = dbo.VW_VT_EXBOND_BALANCE_DETAIL_ASSGN_01.EBNDID
