ALTER VIEW [dbo].[VW_VEHICLETICKET_IMPORT_CONTAINER_CBX_ASSGN]
AS
SELECT     TOP (100) PERCENT dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, dbo.AUTHORIZATIONSLIPMASTER.SDPTID, dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.IGMNO, 
                      dbo.GATEINDETAIL.CONTNRNO, dbo.GATEINDETAIL.GPLNO  FROM dbo.AUTHORIZATIONSLIPDETAIL  
					  INNER JOIN  dbo.OPENSHEETDETAIL ON dbo.AUTHORIZATIONSLIPDETAIL.OSDID = dbo.OPENSHEETDETAIL.OSDID 
					  INNER JOIN  dbo.GATEINDETAIL ON dbo.OPENSHEETDETAIL.GIDID = dbo.GATEINDETAIL.GIDID 
					  INNER JOIN  dbo.AUTHORIZATIONSLIPMASTER ON dbo.AUTHORIZATIONSLIPDETAIL.ASLMID = dbo.AUTHORIZATIONSLIPMASTER.ASLMID  
					  LEFT OUTER JOIN  dbo.GATEOUTDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.GATEOUTDETAIL.GIDID 
					  LEFT OUTER JOIN  dbo.VW_VEHICLETICKET_CONTAINER_CBX_ASSGN_01 ON dbo.AUTHORIZATIONSLIPDETAIL.ASLDID = dbo.VW_VEHICLETICKET_CONTAINER_CBX_ASSGN_01.ASLDID   
					  LEFT OUTER JOIN dbo.GATEIN_BLOCK_DETAILS (NOLOCK) ON GATEINDETAIL.GIDID = GATEIN_BLOCK_DETAILS.GIDID 
                      
WHERE     (ISNULL(dbo.VW_VEHICLETICKET_CONTAINER_CBX_ASSGN_01.ASLDID, 0) = 0) AND (ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) AND 
                      (dbo.AUTHORIZATIONSLIPMASTER.ASLMTYPE IN (1, 2)) AND (dbo.AUTHORIZATIONSLIPMASTER.DISPSTATUS = 0) AND 
                      --(dbo.AUTHORIZATIONSLIPMASTER.ASLMLTYPE = 0) AND 
					  (isnull(dbo.GATEIN_BLOCK_DETAILS.GBDID,0) = 0 OR isnull(dbo.GATEIN_BLOCK_DETAILS.GBSTYPE,0) = 1 )
ORDER BY dbo.GATEINDETAIL.CONTNRNO 
