ALTER VIEW [dbo].[VW_VEHICLETICKET_EXPORT_CONTAINER_CBX_ASSGN]
AS
SELECT DISTINCT  TOP (100) PERCENT dbo.GATEINDETAIL.CONTNRNO, dbo.STUFFINGDETAIL.GIDID, 
 dbo.CONTAINERSIZEMASTER.CONTNRSDESC
FROM    dbo.STUFFINGDETAIL (NOLOCK) 
        Inner Join  dbo.STUFFINGPRODUCTDETAIL (NOLOCK) ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID 
		Inner Join  dbo.STUFFINGMASTER (NOLOCK) ON dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID 
		Inner Join  dbo.GATEINDETAIL (NOLOCK) ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID 
		Inner Join  dbo.CONTAINERSIZEMASTER (NOLOCK) ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID 
		Inner Join  dbo.AUTHORIZATIONSLIPDETAIL (NOLOCK) ON dbo.AUTHORIZATIONSLIPDETAIL.STFDID = dbo.STUFFINGDETAIL.STFDID 
		Inner Join  dbo.AUTHORIZATIONSLIPMASTER (NOLOCK) ON dbo.AUTHORIZATIONSLIPMASTER.ASLMID = dbo.AUTHORIZATIONSLIPDETAIL.ASLMID
		Left Outer Join dbo.VW_VEHICLETICKET_EXPORT_CONTAINER_CBX_ASSGN_01 (NOLOCK) ON  STUFFINGDETAIL.GIDID = VW_VEHICLETICKET_EXPORT_CONTAINER_CBX_ASSGN_01.GIDID
                      
WHERE     (ISNULL(dbo.VW_VEHICLETICKET_EXPORT_CONTAINER_CBX_ASSGN_01.VTDID, 0) = 0) AND --(ISNULL(dbo.GATEOUTDETAIL.GODID, 0) = 0) AND 
                       (dbo.STUFFINGDETAIL.DISPSTATUS = 0)
GROUP BY dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.STUFFINGDETAIL.GIDID,dbo.VW_VEHICLETICKET_EXPORT_CONTAINER_CBX_ASSGN_01.VTDID
ORDER BY dbo.GATEINDETAIL.CONTNRNO  