alter VIEW [dbo].[VW_VEHICLETICKET_EXPORT_CONTAINER_DIRECT_CTRL_ASSGN]
AS
SELECT     TOP 100 PERCENT 0 as ASLDID, 0 STFDID, ''  STFMDNO, 
                      getdate() STFMDATE, dbo.GATEINDETAIL.CHANAME, isnull(dbo.SHIPPINGBILLMASTER.EXPRTNAME,'') EXPRTNAME, 
                      '' AS SBILLNO, getdate() AS SBILLDATE, 
                      '' AS SBMDNO, getdate() AS SBMDATE, dbo.GATEINDETAIL.GIDID, 
                      dbo.GATEINDETAIL.GIDATE, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.GATEINDETAIL.PRDTDESC,
					  '' as CSEALNO,'' as ASEALNO,
					  0 as SLTID,'' as SLTDESC,
					    0 AS EOPTID
FROM GATEINDETAIL (nolock) left join STUFFINGDETAIL (nolock) ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID  
					left Join STUFFINGMASTER (nolock) On STUFFINGDETAIL.STFMID = STUFFINGMASTER.STFMID 
					left Join STUFFINGPRODUCTDETAIL (nolock)  ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID 
					left Join SHIPPINGBILLDETAIL  (nolock) ON dbo.STUFFINGPRODUCTDETAIL.SBDID = dbo.SHIPPINGBILLDETAIL.SBDID  
					left join SHIPPINGBILLMASTER (nolock) ON dbo.SHIPPINGBILLDETAIL.SBMID = dbo.SHIPPINGBILLMASTER.SBMID  					
					join CONTAINERSIZEMASTER (nolock) ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID 
					left Join  AUTHORIZATIONSLIPDETAIL (nolock) ON dbo.STUFFINGDETAIL.STFDID = dbo.AUTHORIZATIONSLIPDETAIL.STFDID  
					left Join  EXPORT_SEALTYPEMASTER ON AUTHORIZATIONSLIPDETAIL.SLTID = EXPORT_SEALTYPEMASTER.SLTID  
where dbo.STUFFINGDETAIL.STFDID is null					
GROUP BY dbo.STUFFINGDETAIL.STFDID, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMDATE, dbo.SHIPPINGBILLMASTER.EXPRTNAME, 
                      dbo.GATEINDETAIL.CHANAME, dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.GIDATE, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, 
                      dbo.GATEINDETAIL.PRDTDESC, dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, AUTHORIZATIONSLIPDETAIL.CSEALNO, AUTHORIZATIONSLIPDETAIL.ASEALNO,
					  AUTHORIZATIONSLIPDETAIL.SLTID,
					EXPORT_SEALTYPEMASTER.SLTDESC,STUFFINGMASTER.EOPTID

