alter VIEW [dbo].[VW_YEAR_DETAIL_CBX_ASSGN]
AS
SELECT     TOP 100 PERCENT dbo.COMPANYACCOUNTINGDETAIL.COMPID, dbo.COMPANYACCOUNTINGDETAIL.COMPYID, dbo.ACCOUNTINGYEAR.YRDESC, 
                      dbo.ACCOUNTINGYEAR.FDATE
FROM         dbo.COMPANYACCOUNTINGDETAIL (nolock) INNER JOIN
                      dbo.ACCOUNTINGYEAR (nolock) ON dbo.COMPANYACCOUNTINGDETAIL.YRID = dbo.ACCOUNTINGYEAR.YRID
ORDER BY dbo.ACCOUNTINGYEAR.FDATE