CREATE VIEW dbo.Z_BOND_EXBOND_EINVOICE_DETAILS
AS
SELECT     dbo.BONDTRANSACTIONMASTER.TRANMID, dbo.BONDTRANSACTIONMASTER.TRANDATE, dbo.BONDTRANSACTIONMASTER.TRANNO, 
                      dbo.BONDTRANSACTIONMASTER.TRANDNO, '33AAACS7690F1ZB' AS COMPGSTNO, dbo.COMPANYMASTER.COMPNAME, '# 592,' AS COMPADDR1, 
                      'ENNORE EXPRESS HIGH ROAD,' AS COMPADDR2, 'CHENNAI' AS COMPLOCTDESC, '600057' AS COMPPINCODE, '33' AS COMPSTATECODE, 
                      dbo.COMPANYMASTER.COMPPHN1, dbo.COMPANYMASTER.COMPMAIL, '12' AS COMPPOS, 'Nos' AS UNITCODE, 
                      dbo.BONDTRANSACTIONMASTER.TRANREFNAME, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR1 AS TRANIMPADDR1, 
                      dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR2 AS TRANIMPADDR2, dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR3 AS TRANIMPADDR3, 
                      dbo.CATEGORY_ADDRESS_DETAIL.CATEAADDR4 AS TRANIMPADDR4, dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO AS CATEBGSTNO, dbo.STATEMASTER.STATECODE, 
                      dbo.CATEGORYMASTER.CATEPHN1, dbo.BONDTRANSACTIONMASTER.TRANGAMT, 
                      dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01.STRGAMT AS STRG_TAXABLE_AMT, 
                      dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01.HANDLAMT AS HANDL_TAXABLE_AMT, dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01.INSRAMT AS INSR_TAXABLE_AMT, 
                      dbo.BONDTRANSACTIONMASTER.TRANNAMT, dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01.HANDL_IGST_AMT, 
                      dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01.HANDL_CGST_AMT, dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01.HANDL_SGST_AMT, 
                      dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01.STRG_IGST_AMT, dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01.STRG_CGST_AMT, 
                      dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01.STRG_SGST_AMT, dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01.INSR_IGST_AMT, 
                      dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01.INSR_CGST_AMT, dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01.INSR_SGST_AMT, 
                      dbo.BONDTRANSACTIONMASTER.TRAN_CGST_AMT AS CGSTAMT, dbo.BONDTRANSACTIONMASTER.TRAN_SGST_AMT AS SGSTAMT, 
                      dbo.BONDTRANSACTIONMASTER.TRAN_IGST_AMT AS IGSTAMT
FROM         dbo.BONDTRANSACTIONMASTER INNER JOIN
                      dbo.CATEGORYMASTER ON dbo.BONDTRANSACTIONMASTER.BILLREFID = dbo.CATEGORYMASTER.CATEID INNER JOIN
					  dbo.CATEGORY_ADDRESS_DETAIL ON dbo.BONDTRANSACTIONMASTER.BCATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID INNER JOIN
                      dbo.COMPANYACCOUNTINGDETAIL ON dbo.BONDTRANSACTIONMASTER.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                      dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID INNER JOIN
                      dbo.STATEMASTER ON dbo.CATEGORYMASTER.STATEID = dbo.STATEMASTER.STATEID INNER JOIN
                      dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01 ON dbo.BONDTRANSACTIONMASTER.TRANMID = dbo.Z_BOND_EXBOND_EINVOICE_DETAILS_01.TRANMID LEFT OUTER JOIN
                      dbo.VW_SERVICE_TAX_RPT_01 ON dbo.BONDTRANSACTIONMASTER.TRANMID = dbo.VW_SERVICE_TAX_RPT_01.TRANMID

