ALTER VIEW [dbo].[Z_BOND_EXBOND_EINVOICE_DETAILS_01]
AS
SELECT        TRANMID, SUM(CASE SLABTID WHEN 2 THEN TRANDGAMT ELSE 0 END) AS STRGAMT, SUM(CASE SLABTID WHEN 4 THEN TRANDGAMT ELSE 0 END) AS INSRAMT, SUM(CASE WHEN SLABTID not IN (2,4) 
                         THEN TRANDGAMT ELSE 0 END) AS HANDLAMT, SUM(CASE SLABTID WHEN 2 THEN TRAND_CGST_AMT ELSE 0 END) AS STRG_CGST_AMT, SUM(CASE SLABTID WHEN 2 THEN TRAND_SGST_AMT ELSE 0 END) 
                         AS STRG_SGST_AMT, SUM(CASE SLABTID WHEN 2 THEN TRAND_IGST_AMT ELSE 0 END) AS STRG_IGST_AMT, SUM(CASE SLABTID WHEN 4 THEN TRAND_CGST_AMT ELSE 0 END) AS INSR_CGST_AMT, 
                         SUM(CASE SLABTID WHEN 4 THEN TRAND_SGST_AMT ELSE 0 END) AS INSR_SGST_AMT, SUM(CASE SLABTID WHEN 4 THEN TRAND_IGST_AMT ELSE 0 END) AS INSR_IGST_AMT, SUM(CASE WHEN SLABTID not IN (2,4)  
                         THEN TRAND_CGST_AMT ELSE 0 END) AS HANDL_CGST_AMT, SUM(CASE WHEN SLABTID not IN (2,4)  THEN TRAND_SGST_AMT ELSE 0 END) AS HANDL_SGST_AMT, SUM(CASE WHEN SLABTID not IN (2,4)  
                         THEN TRAND_IGST_AMT ELSE 0 END) AS HANDL_IGST_AMT
FROM            dbo.BONDTRANSACTIONDETAIL --JOIN BONDSLABTYPEMASTER ON BONDTRANSACTIONDETAIL.SLABTID = BONDSLABTYPEMASTER.SLABTID
GROUP BY TRANMID