-- SELECT * FROM Z_CREDITNOTE_EINVOICE_DETAILS
alter VIEW dbo.Z_CREDITNOTE_EINVOICE_DETAILS
AS
SELECT        dbo.COMPANYMASTER.COMPNAME, dbo.CREDITNOTE_TRANSACTIONMASTER.COMPYID, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANMID, dbo.CREDITNOTE_TRANSACTIONMASTER.SDPTID, dbo.CREDITNOTE_TRANSACTIONMASTER.REGSTRID, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANBTYPE, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANDATE, RIGHT(dbo.CREDITNOTE_TRANSACTIONMASTER.TRANTIME, 8) AS TRANTIME, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANNO, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANDNO, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFNAME, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANMODE, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANMODEDETL, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFNO, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFDATE, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFBNAME, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANGAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANSAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANHAMT, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANEAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANFAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANAAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANNAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANAMTWRDS, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANRMKS, '' AS IMPRTNAME, '' AS STMRNAME, SUM(dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDQTY) AS TRANDQTY, 
                         SUM(dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDGAMT) AS TRANDGAMT, SUM(dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDSAMT) AS TRANDSAMT, SUM(dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDHAMT) AS TRANDHAMT, 
                         SUM(dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDEAMT) AS TRANDEAMT, SUM(dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDFAMT) AS TRANDFAMT, SUM(dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDAAMT) AS TRANDAAMT, 
                         SUM(dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDNAMT) AS TRANDNAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.LMUSRID, dbo.CREDITNOTE_TRANSACTIONMASTER.CUSRID, dbo.CREDITNOTE_TRANSACTIONMASTER.LMUSRID AS USRNAME, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.DISPSTATUS, '' AS OSMLNAME, dbo.COMPANYMASTER.COMPPDESC1, dbo.COMPANYMASTER.COMPPDESC2, '' COL1, 
                         '' COL2, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANNARTN, MAX(ISNULL(dbo.CREDITNOTE_TRANSACTIONMASTER.TRANHBLNO,'')) AS TRANHBLNO, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANPONO,'' AS CHANAME, 
						--dbo.GATEINDETAIL.CLNTNAME, dbo.GATEINDETAIL.SHPRNAME, 
						''  as CLNTNAME, ''   as SHPRNAME, '' AS GPPLCNAME, 
                         dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDAHAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANAHAMT, dbo.COMPANYMASTER.COMPGSTNO, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_HSNCODE, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_HSNCODE, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_EXPRN, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_EXPRN, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_EXPRN, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_EXPRN, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_EXPRN, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_EXPRN, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_TAXABLE_AMT, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_TAXABLE_AMT, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_AMT, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_AMT, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_AMT, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_AMT, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_AMT, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_AMT, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.CGST_AMT, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.SGST_AMT, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.IGST_AMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANCSNAME, dbo.CREDITNOTE_TRANSACTIONMASTER.CATEAID, '' OSMNAME, 
                         '' AS OSMCNAME, 0 AS OSMNOP,0.0 AS OSMWGHT, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRAN_COVID_DISC_AMT, '# 592,' AS COMPADDR1, 'ENNORE EXPRESS HIGH ROAD,' AS COMPADDR2, 'CHENNAI' AS COMPLOCTDESC, '600057' AS COMPPINCODE, '33' AS COMPSTATECODE, 
                         dbo.COMPANYMASTER.COMPPHN1, dbo.COMPANYMASTER.COMPMAIL, '12' AS COMPPOS, 'Nos' AS UNITCODE, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_TAXABLE_AMT + dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_IGST_AMT + dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_CGST_AMT + dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_SGST_AMT AS TOTALITEMVAL, 
                         SUM(dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDSAMT) AS STRG_AMT, 
                         SUM(dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDHAMT + dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDEAMT + dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDFAMT + dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDAAMT + dbo.CREDITNOTE_TRANSACTIONMASTER.TRANAHAMT) 
                         AS HANDL_AMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANIMPADDR1 AS TRANIMPADDR1, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANIMPADDR2 AS TRANIMPADDR2, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANIMPADDR3 AS TRANIMPADDR3, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANIMPADDR4 AS TRANIMPADDR4, dbo.CREDITNOTE_TRANSACTIONMASTER.STATEID AS statid, dbo.CREDITNOTE_TRANSACTIONMASTER.CATEAGSTNO AS CATEBGSTNO, STATEMASTER_1.STATECODE, 
                         STATEMASTER_1.STATEDESC, dbo.CATEGORYMASTER.CATEPHN1, dbo.CATEGORYMASTER.CATEMAIL, CREDITNOTE_TRANSACTIONDETAIL.TRANDREFID, VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.CNTDESC,
						 TRANBILLREFNO
FROM            dbo.STATEMASTER AS STATEMASTER_1 INNER JOIN
                         dbo.CREDITNOTE_TRANSACTIONMASTER ON STATEMASTER_1.STATEID = dbo.CREDITNOTE_TRANSACTIONMASTER.STATEID INNER JOIN
						 DBO.CATEGORYMASTER ON CREDITNOTE_TRANSACTIONMASTER.TRANREFID = CATEGORYMASTER.CATEID INNER JOIN
                         dbo.CREDITNOTE_TRANSACTIONDETAIL ON dbo.CREDITNOTE_TRANSACTIONMASTER.TRANMID = dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANMID INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.CREDITNOTE_TRANSACTIONMASTER.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                         dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID INNER JOIN
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01 ON dbo.CREDITNOTE_TRANSACTIONMASTER.TRANMID = dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.TRANMID 
WHERE        dbo.CREDITNOTE_TRANSACTIONMASTER.DISPSTATUS = 0
GROUP BY dbo.COMPANYMASTER.COMPNAME, dbo.CREDITNOTE_TRANSACTIONMASTER.COMPYID, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANMID, dbo.CREDITNOTE_TRANSACTIONMASTER.SDPTID, dbo.CREDITNOTE_TRANSACTIONMASTER.REGSTRID, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANBTYPE, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANDATE, RIGHT(dbo.CREDITNOTE_TRANSACTIONMASTER.TRANTIME, 8), dbo.CREDITNOTE_TRANSACTIONMASTER.TRANNO, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANDNO, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFNAME, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANMODE, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANMODEDETL, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFNO, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFDATE, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFBNAME, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANREFAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANGAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANSAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANHAMT, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANEAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANFAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANAAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANNAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANAMTWRDS, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANRMKS, dbo.CREDITNOTE_TRANSACTIONMASTER.LMUSRID, dbo.CREDITNOTE_TRANSACTIONMASTER.CUSRID, dbo.CREDITNOTE_TRANSACTIONMASTER.LMUSRID, dbo.CREDITNOTE_TRANSACTIONMASTER.DISPSTATUS, 
                         dbo.COMPANYMASTER.COMPPDESC1, dbo.COMPANYMASTER.COMPPDESC2, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANNARTN, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANPONO, --dbo.GATEINDETAIL.CLNTNAME, dbo.GATEINDETAIL.SHPRNAME, 
                         dbo.CREDITNOTE_TRANSACTIONDETAIL.TRANDAHAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANAHAMT, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANGSTNO, dbo.COMPANYMASTER.COMPGSTNO, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_HSNCODE, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_HSNCODE, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_EXPRN, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_EXPRN, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_EXPRN, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_EXPRN, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_EXPRN, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_EXPRN, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_TAXABLE_AMT, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_TAXABLE_AMT, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_AMT, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_AMT, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_AMT, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_AMT, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_AMT, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_AMT, 
                         dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.CGST_AMT, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.SGST_AMT, dbo.VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.IGST_AMT, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANCSNAME, dbo.CREDITNOTE_TRANSACTIONMASTER.CATEAID,  dbo.CREDITNOTE_TRANSACTIONMASTER.TRAN_COVID_DISC_AMT, dbo.COMPANYMASTER.COMPPHN1, 
                         dbo.COMPANYMASTER.COMPMAIL, 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_TAXABLE_AMT + dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_IGST_AMT + dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_CGST_AMT + dbo.CREDITNOTE_TRANSACTIONMASTER.HANDL_SGST_AMT, 
                         STATEMASTER_1.STATECODE, STATEMASTER_1.STATEDESC, dbo.CATEGORYMASTER.CATEPHN1, dbo.CATEGORYMASTER.CATEMAIL,
						 dbo.CREDITNOTE_TRANSACTIONMASTER.TRANIMPADDR1, dbo.CREDITNOTE_TRANSACTIONMASTER.TRANIMPADDR2 , dbo.CREDITNOTE_TRANSACTIONMASTER.TRANIMPADDR3 , 
                         dbo.CREDITNOTE_TRANSACTIONMASTER.TRANIMPADDR4, dbo.CREDITNOTE_TRANSACTIONMASTER.STATEID, dbo.CREDITNOTE_TRANSACTIONMASTER.CATEAGSTNO, CREDITNOTE_TRANSACTIONDETAIL.TRANDREFID, VW_CREDITNOTE_TRANSACTION_GST_PRINT_ASSGN_01.CNTDESC,
						 TRANBILLREFNO
