CREATE VIEW dbo.z_EXport_SCMTR_Json_File_Detail_Assgn
AS
SELECT        dbo.STUFFING_JSON_DETAIL.STFXID, dbo.STUFFING_JSON_DETAIL.STFDID, 'P' AS indicator, 'CUCHE01' AS messageID, dbo.STUFFING_JSON_DETAIL.STFXNO AS sequenceOrControlNumber, 
                         dbo.REPORTING_EVENT.RECODE, 'INMAA1STL1' AS senderID, 'INMAA1' AS receiverID, '1.0' AS versionNo, dbo.STUFFING_MESSAGE_TYPE.STF_MSG_TCODE, dbo.PORT_OF_REPORTING.PRCODE, 
                         dbo.REPORTING_PARTY_TYPE.RPTYPECODE, dbo.STUFFING_JSON_DETAIL.STF_RPTYPE_CODE, dbo.STUFFING_JSON_DETAIL.STF_RLOCT_CODE, dbo.STUFFING_JSON_DETAIL.STF_RLOCT_NAME, 
                         dbo.STUFFING_JSON_DETAIL.STF_AP_PANNO, dbo.STUFFING_JSON_DETAIL.STF_CONTNRNO, dbo.EQUIPMENT_TYPE_MASTER.EQTCODE, LEFT(dbo.STUFFING_JSON_DETAIL.STF_CONTNRSDESC, 2) 
                         AS STF_CONTNRSDESC, dbo.EQUIPMENT_LOAD_STATUS.ELSCODE, dbo.FINAL_DESTINATION_CODE.FDCODE, dbo.EQUIPMENT_SEAL_TYPE.ESTYPEDESC, dbo.STUFFING_JSON_DETAIL.STF_EVENTDATE, 
                         RIGHT(dbo.STUFFING_JSON_DETAIL.STF_EQSEALNO, 5) AS STF_EQSEALNO, dbo.EQUIPMENT_STATUS.ESCODE, dbo.STUFFING_JSON_DETAIL.STF_EQPKG_DESC, 
                         dbo.STUFFING_JSON_DETAIL.STF_EQPKG_QTY, dbo.EQUIPMENT_UQC.EUQCCODE, dbo.STUFFING_JSON_DETAIL.CREATEDDATETIME
FROM            dbo.STUFFING_JSON_DETAIL INNER JOIN
                         dbo.REPORTING_EVENT ON dbo.STUFFING_JSON_DETAIL.REID = dbo.REPORTING_EVENT.REID INNER JOIN
                         dbo.STUFFING_MESSAGE_TYPE ON dbo.STUFFING_JSON_DETAIL.STF_MSG_TID = dbo.STUFFING_MESSAGE_TYPE.STF_MSG_TID INNER JOIN
                         dbo.PORT_OF_REPORTING ON dbo.STUFFING_JSON_DETAIL.PRID = dbo.PORT_OF_REPORTING.PRID INNER JOIN
                         dbo.REPORTING_PARTY_TYPE ON dbo.STUFFING_JSON_DETAIL.RPTYPEID = dbo.REPORTING_PARTY_TYPE.RPTYPEID INNER JOIN
                         dbo.EQUIPMENT_TYPE_MASTER ON dbo.STUFFING_JSON_DETAIL.EQTID = dbo.EQUIPMENT_TYPE_MASTER.EQTID INNER JOIN
                         dbo.EQUIPMENT_LOAD_STATUS ON dbo.STUFFING_JSON_DETAIL.ELSID = dbo.EQUIPMENT_LOAD_STATUS.ELSID INNER JOIN
                         dbo.FINAL_DESTINATION_CODE ON dbo.STUFFING_JSON_DETAIL.FDID = dbo.FINAL_DESTINATION_CODE.FDID INNER JOIN
                         dbo.EQUIPMENT_SEAL_TYPE ON dbo.STUFFING_JSON_DETAIL.ESTYPEID = dbo.EQUIPMENT_SEAL_TYPE.ESTYPEID INNER JOIN
                         dbo.EQUIPMENT_STATUS ON dbo.STUFFING_JSON_DETAIL.ESID = dbo.EQUIPMENT_STATUS.ESID INNER JOIN
                         dbo.EQUIPMENT_UQC ON dbo.STUFFING_JSON_DETAIL.EUQCID = dbo.EQUIPMENT_UQC.EUQCID

