USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[Z_HSNCODE_INVOICE_DETAIL_24122024]    Script Date: 25/12/2024 20:32:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[Z_HSNCODE_INVOICE_DETAIL_24122024]
AS
SELECT        TOP (100) PERCENT dbo.TRANSACTIONMASTER.SDPTID, dbo.TRANSACTIONMASTER.REGSTRID, dbo.TRANSACTIONMASTER.TRANNO, dbo.TRANSACTIONMASTER.TRANDNO, dbo.TRANSACTIONMASTER.TRANDATE, 
                         dbo.TRANSACTIONMASTER.CATEAGSTNO, dbo.TRANSACTIONMASTER.TRANREFNAME, dbo.TRANSACTIONMASTER.STRG_HSNCODE, dbo.TRANSACTIONMASTER.TRANSAMT, dbo.TRANSACTIONMASTER.HANDL_HSNCODE, 
                         dbo.TRANSACTIONMASTER.TRANGAMT - dbo.TRANSACTIONMASTER.TRANSAMT + ISNULL(dbo.VW_TAXREGISTER_RPT_12.DEDVALUE, 0) AS TRANDHAMT, dbo.TRANSACTIONMASTER.TRANCGSTAMT AS CGSTAMT, 
                         dbo.TRANSACTIONMASTER.TRANSGSTAMT AS SGSTAMT, dbo.TRANSACTIONMASTER.TRANIGSTAMT AS IGSTAMT, dbo.TRANSACTIONMASTER.TRANGAMT, dbo.TRANSACTIONMASTER.TRANNAMT, 
                         dbo.TRANSACTIONMASTER.DISPSTATUS
FROM            dbo.TRANSACTIONMASTER LEFT OUTER JOIN
                         dbo.VW_TAXREGISTER_RPT_12 ON dbo.TRANSACTIONMASTER.TRANMID = dbo.VW_TAXREGISTER_RPT_12.TRANMID
WHERE        (dbo.TRANSACTIONMASTER.REGSTRID = 1) AND (dbo.TRANSACTIONMASTER.TRANDATE BETWEEN CONVERT(DATETIME, '2024-04-01 00:00:00', 102) AND CONVERT(DATETIME, '2024-04-30 00:00:00', 102)) AND 
                         (dbo.TRANSACTIONMASTER.DISPSTATUS = 0)
ORDER BY dbo.TRANSACTIONMASTER.TRANNO
GO


