USE [SCFS_ERP]
GO

/****** Object:  View [dbo].[Z_IMPORT_EINVOICE_DETAILS]    Script Date: 29-05-2025 15:55:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[Z_IMPORT_EINVOICE_DETAILS]
AS
SELECT        dbo.COMPANYMASTER.COMPNAME, dbo.TRANSACTIONMASTER.COMPYID, dbo.TRANSACTIONMASTER.TRANMID, dbo.TRANSACTIONMASTER.SDPTID, dbo.TRANSACTIONMASTER.REGSTRID, 
                         dbo.TRANSACTIONMASTER.TRANBTYPE, dbo.TRANSACTIONMASTER.TRANDATE, RIGHT(dbo.TRANSACTIONMASTER.TRANTIME, 8) AS TRANTIME, dbo.TRANSACTIONMASTER.TRANNO, dbo.TRANSACTIONMASTER.TRANDNO, 
                         dbo.TRANSACTIONMASTER.TRANREFNAME, dbo.TRANSACTIONMASTER.TRANMODE, dbo.TRANSACTIONMASTER.TRANMODEDETL, dbo.TRANSACTIONMASTER.TRANREFNO, dbo.TRANSACTIONMASTER.TRANREFDATE, 
                         dbo.TRANSACTIONMASTER.TRANREFBNAME, dbo.TRANSACTIONMASTER.TRANREFAMT, dbo.TRANSACTIONMASTER.TRANGAMT, dbo.TRANSACTIONMASTER.TRANSAMT, dbo.TRANSACTIONMASTER.TRANHAMT, 
                         dbo.TRANSACTIONMASTER.TRANEAMT, dbo.TRANSACTIONMASTER.TRANFAMT, dbo.TRANSACTIONMASTER.TRANAAMT, dbo.TRANSACTIONMASTER.TRANNAMT, dbo.TRANSACTIONMASTER.TRANAMTWRDS, 
                         dbo.TRANSACTIONMASTER.TRANRMKS, MAX(dbo.GATEINDETAIL.IMPRTNAME) AS IMPRTNAME, MAX(dbo.GATEINDETAIL.STMRNAME) AS STMRNAME, SUM(dbo.TRANSACTIONDETAIL.TRANDQTY) AS TRANDQTY, 
                         SUM(dbo.TRANSACTIONDETAIL.TRANDGAMT) AS TRANDGAMT, SUM(dbo.TRANSACTIONDETAIL.TRANDSAMT) AS TRANDSAMT, SUM(dbo.TRANSACTIONDETAIL.TRANDHAMT) AS TRANDHAMT, 
                         SUM(dbo.TRANSACTIONDETAIL.TRANDEAMT) AS TRANDEAMT, SUM(dbo.TRANSACTIONDETAIL.TRANDFAMT) AS TRANDFAMT, SUM(dbo.TRANSACTIONDETAIL.TRANDAAMT) AS TRANDAAMT, 
                         SUM(dbo.TRANSACTIONDETAIL.TRANDNAMT) AS TRANDNAMT, dbo.TRANSACTIONMASTER.LMUSRID, dbo.TRANSACTIONMASTER.CUSRID, dbo.TRANSACTIONMASTER.LMUSRID AS USRNAME, 
                         dbo.TRANSACTIONMASTER.DISPSTATUS, dbo.OPENSHEETMASTER.OSMLNAME, dbo.COMPANYMASTER.COMPPDESC1, dbo.COMPANYMASTER.COMPPDESC2, dbo.VW_TRANSACTION_CRY_PRINT_ASSGN_01.COL1, 
                         dbo.VW_TRANSACTION_CRY_PRINT_ASSGN_01.COL2, dbo.TRANSACTIONMASTER.TRANNARTN, MAX(ISNULL(dbo.TRANSACTIONMASTER.TRANHBLNO, dbo.BILLENTRYMASTER.BLNO)) AS TRANHBLNO, 
                         dbo.TRANSACTIONMASTER.TRANPONO, MAX(dbo.GATEINDETAIL.CHANAME) AS CHANAME, MAX(dbo.GATEINDETAIL.CLNTNAME) AS CLNTNAME, MAX(dbo.GATEINDETAIL.SHPRNAME) AS SHPRNAME, 
                         MAX(dbo.GATEINDETAIL.GPPLCNAME) AS GPPLCNAME, dbo.TRANSACTIONDETAIL.TRANDAHAMT, dbo.TRANSACTIONMASTER.TRANAHAMT, dbo.COMPANYMASTER.COMPGSTNO, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_HSNCODE, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_HSNCODE, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_EXPRN, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_EXPRN, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_EXPRN, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_EXPRN, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_EXPRN, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_EXPRN, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_TAXABLE_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_TAXABLE_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.CGST_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.SGST_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.IGST_AMT, 
                         dbo.TRANSACTIONMASTER.TRANCSNAME, dbo.TRANSACTIONMASTER.CATEAID, dbo.OPENSHEETMASTER.OSMNAME, MAX(dbo.OPENSHEETMASTER.OSMCNAME) AS OSMCNAME, SUM(dbo.OPENSHEETMASTER.OSMNOP) 
                         AS OSMNOP, SUM(dbo.OPENSHEETMASTER.OSMWGHT) AS OSMWGHT, dbo.TRANSACTIONMASTER.TRAN_COVID_DISC_AMT, '# 592,' AS COMPADDR1, 'ENNORE EXPRESS HIGH ROAD,' AS COMPADDR2, 
                         'CHENNAI' AS COMPLOCTDESC, '600057' AS COMPPINCODE, '33' AS COMPSTATECODE, dbo.COMPANYMASTER.COMPPHN1, dbo.COMPANYMASTER.COMPMAIL, '12' AS COMPPOS, 'Nos' AS UNITCODE, 
                         dbo.TRANSACTIONMASTER.HANDL_TAXABLE_AMT + dbo.TRANSACTIONMASTER.HANDL_IGST_AMT + dbo.TRANSACTIONMASTER.HANDL_CGST_AMT + dbo.TRANSACTIONMASTER.HANDL_SGST_AMT AS TOTALITEMVAL, 
                         SUM(dbo.TRANSACTIONDETAIL.TRANDSAMT) AS STRG_AMT, 
                         SUM(dbo.TRANSACTIONDETAIL.TRANDHAMT + dbo.TRANSACTIONDETAIL.TRANDEAMT + dbo.TRANSACTIONDETAIL.TRANDFAMT + dbo.TRANSACTIONDETAIL.TRANDAAMT + dbo.TRANSACTIONMASTER.TRANAHAMT) 
                         AS HANDL_AMT, dbo.OPENSHEETMASTER.OSBBCHAADDR1 AS TRANIMPADDR1, dbo.OPENSHEETMASTER.OSBBCHAADDR2 AS TRANIMPADDR2, dbo.OPENSHEETMASTER.OSBBCHAADDR3 AS TRANIMPADDR3, 
                         dbo.OPENSHEETMASTER.OSBBCHAADDR4 AS TRANIMPADDR4, dbo.OPENSHEETMASTER.OSBBCHASTATEID AS statid, dbo.OPENSHEETMASTER.OSBBCHACATEAGSTNO AS CATEBGSTNO, STATEMASTER_1.STATECODE, 
                         STATEMASTER_1.STATEDESC, dbo.CATEGORYMASTER.CATEPHN1, dbo.CATEGORYMASTER.CATEMAIL, dbo.CATEGORYMASTER.CUSTGID
FROM            dbo.STATEMASTER AS STATEMASTER_1 INNER JOIN
                         dbo.OPENSHEETDETAIL INNER JOIN
                         dbo.OPENSHEETMASTER ON dbo.OPENSHEETDETAIL.OSMID = dbo.OPENSHEETMASTER.OSMID ON STATEMASTER_1.STATEID = dbo.OPENSHEETMASTER.OSBBCHASTATEID INNER JOIN
                         dbo.CATEGORYMASTER ON dbo.OPENSHEETMASTER.OSBILLREFID = dbo.CATEGORYMASTER.CATEID RIGHT OUTER JOIN
                         dbo.TRANSACTIONMASTER INNER JOIN
                         dbo.TRANSACTIONDETAIL ON dbo.TRANSACTIONMASTER.TRANMID = dbo.TRANSACTIONDETAIL.TRANMID INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.TRANSACTIONMASTER.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                         dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID INNER JOIN
                         dbo.BILLENTRYDETAIL ON dbo.TRANSACTIONDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID INNER JOIN
                         dbo.GATEINDETAIL ON dbo.BILLENTRYDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
                         dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
                         dbo.BILLENTRYMASTER ON dbo.BILLENTRYDETAIL.BILLEMID = dbo.BILLENTRYMASTER.BILLEMID INNER JOIN
                         dbo.CONTAINERTYPEMASTER ON dbo.GATEINDETAIL.CONTNRTID = dbo.CONTAINERTYPEMASTER.CONTNRTID INNER JOIN
                         dbo.VW_TRANSACTION_CRY_PRINT_ASSGN_01 ON dbo.TRANSACTIONMASTER.TRANMID = dbo.VW_TRANSACTION_CRY_PRINT_ASSGN_01.TRANMID INNER JOIN
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01 ON dbo.TRANSACTIONMASTER.TRANMID = dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.TRANMID ON 
                         dbo.OPENSHEETDETAIL.BILLEDID = dbo.BILLENTRYDETAIL.BILLEDID LEFT OUTER JOIN
                         dbo.DELIVERYORDERDETAIL LEFT OUTER JOIN
                         dbo.DELIVERYORDERMASTER ON dbo.DELIVERYORDERDETAIL.DOMID = dbo.DELIVERYORDERMASTER.DOMID ON dbo.BILLENTRYDETAIL.BILLEDID = dbo.DELIVERYORDERDETAIL.BILLEDID LEFT OUTER JOIN
                         dbo.ROWMASTER RIGHT OUTER JOIN
                         dbo.SLOTMASTER ON dbo.ROWMASTER.ROWID = dbo.SLOTMASTER.ROWID ON dbo.GATEINDETAIL.SLOTID = dbo.SLOTMASTER.SLOTID LEFT OUTER JOIN
                         dbo.VW_TRANSACTION_DOSPRINT_ASSGN_01 ON dbo.TRANSACTIONMASTER.TRANMID = dbo.VW_TRANSACTION_DOSPRINT_ASSGN_01.TRANMID
WHERE        (ISNULL(dbo.DELIVERYORDERMASTER.DISPSTATUS, 0) = 0)
GROUP BY dbo.COMPANYMASTER.COMPNAME, dbo.TRANSACTIONMASTER.COMPYID, dbo.TRANSACTIONMASTER.TRANMID, dbo.TRANSACTIONMASTER.SDPTID, dbo.TRANSACTIONMASTER.REGSTRID, 
                         dbo.TRANSACTIONMASTER.TRANBTYPE, dbo.TRANSACTIONMASTER.TRANDATE, RIGHT(dbo.TRANSACTIONMASTER.TRANTIME, 8), dbo.TRANSACTIONMASTER.TRANNO, dbo.TRANSACTIONMASTER.TRANDNO, 
                         dbo.TRANSACTIONMASTER.TRANREFNAME, dbo.TRANSACTIONMASTER.TRANMODE, dbo.TRANSACTIONMASTER.TRANMODEDETL, dbo.TRANSACTIONMASTER.TRANREFNO, dbo.TRANSACTIONMASTER.TRANREFDATE, 
                         dbo.TRANSACTIONMASTER.TRANREFBNAME, dbo.TRANSACTIONMASTER.TRANREFAMT, dbo.TRANSACTIONMASTER.TRANGAMT, dbo.TRANSACTIONMASTER.TRANSAMT, dbo.TRANSACTIONMASTER.TRANHAMT, 
                         dbo.TRANSACTIONMASTER.TRANEAMT, dbo.TRANSACTIONMASTER.TRANFAMT, dbo.TRANSACTIONMASTER.TRANAAMT, dbo.TRANSACTIONMASTER.TRANNAMT, dbo.TRANSACTIONMASTER.TRANAMTWRDS, 
                         dbo.TRANSACTIONMASTER.TRANRMKS, dbo.TRANSACTIONMASTER.LMUSRID, dbo.TRANSACTIONMASTER.CUSRID, dbo.TRANSACTIONMASTER.LMUSRID, dbo.TRANSACTIONMASTER.DISPSTATUS, 
                         dbo.OPENSHEETMASTER.OSMLNAME, dbo.COMPANYMASTER.COMPPDESC1, dbo.COMPANYMASTER.COMPPDESC2, dbo.VW_TRANSACTION_CRY_PRINT_ASSGN_01.COL1, 
                         dbo.VW_TRANSACTION_CRY_PRINT_ASSGN_01.COL2, dbo.TRANSACTIONMASTER.TRANNARTN, dbo.TRANSACTIONMASTER.TRANPONO, dbo.TRANSACTIONDETAIL.TRANDAHAMT, dbo.TRANSACTIONMASTER.TRANAHAMT, 
                         dbo.TRANSACTIONMASTER.TRANGSTNO, dbo.COMPANYMASTER.COMPGSTNO, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_HSNCODE, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_HSNCODE, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_EXPRN, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_EXPRN, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_EXPRN, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_EXPRN, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_EXPRN, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_EXPRN, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_TAXABLE_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_TAXABLE_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.CGST_AMT, dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.SGST_AMT, 
                         dbo.VW_IMPORT_TRANSACTION_GST_PRINT_ASSGN_01.IGST_AMT, dbo.TRANSACTIONMASTER.TRANCSNAME, dbo.TRANSACTIONMASTER.CATEAID, dbo.OPENSHEETMASTER.OSMNAME, 
                         dbo.TRANSACTIONMASTER.TRAN_COVID_DISC_AMT, dbo.COMPANYMASTER.COMPPHN1, dbo.COMPANYMASTER.COMPMAIL, 
                         dbo.TRANSACTIONMASTER.HANDL_TAXABLE_AMT + dbo.TRANSACTIONMASTER.HANDL_IGST_AMT + dbo.TRANSACTIONMASTER.HANDL_CGST_AMT + dbo.TRANSACTIONMASTER.HANDL_SGST_AMT, 
                         dbo.OPENSHEETMASTER.OSBBCHAADDR1, dbo.OPENSHEETMASTER.OSBBCHAADDR2, dbo.OPENSHEETMASTER.OSBBCHAADDR3, dbo.OPENSHEETMASTER.OSBBCHAADDR4, dbo.OPENSHEETMASTER.OSBBCHASTATEID, 
                         dbo.OPENSHEETMASTER.OSBBCHACATEAGSTNO, STATEMASTER_1.STATECODE, STATEMASTER_1.STATEDESC, dbo.CATEGORYMASTER.CATEPHN1, dbo.CATEGORYMASTER.CATEMAIL, 
                         dbo.CATEGORYMASTER.CUSTGID
HAVING        (dbo.TRANSACTIONMASTER.DISPSTATUS = 0)
GO


