ALTER VIEW [dbo].[Z_IMPORT_MANUAL_EINVOICE_DETAILS]
AS
SELECT        dbo.COMPANYMASTER.COMPNAME, dbo.TRANSACTIONMASTER.COMPYID, dbo.TRANSACTIONMASTER.TRANMID, dbo.TRANSACTIONMASTER.SDPTID, dbo.TRANSACTIONMASTER.REGSTRID, 
                         dbo.TRANSACTIONMASTER.TRANBTYPE, dbo.TRANSACTIONMASTER.TRANDATE, RIGHT(dbo.TRANSACTIONMASTER.TRANTIME, 8) AS TRANTIME, dbo.TRANSACTIONMASTER.TRANNO, dbo.TRANSACTIONMASTER.TRANDNO, 
                         dbo.TRANSACTIONMASTER.TRANREFNAME, dbo.TRANSACTIONMASTER.TRANMODE, dbo.TRANSACTIONMASTER.TRANMODEDETL, dbo.TRANSACTIONMASTER.TRANREFNO, dbo.TRANSACTIONMASTER.TRANREFDATE, 
                         dbo.TRANSACTIONMASTER.TRANREFBNAME, dbo.TRANSACTIONMASTER.TRANREFAMT, dbo.TRANSACTIONMASTER.TRANGAMT, dbo.TRANSACTIONMASTER.TRANSAMT, dbo.TRANSACTIONMASTER.TRANHAMT, 
                         dbo.TRANSACTIONMASTER.TRANEAMT, dbo.TRANSACTIONMASTER.TRANFAMT, dbo.TRANSACTIONMASTER.TRANAAMT, dbo.TRANSACTIONMASTER.TRANNAMT, dbo.TRANSACTIONMASTER.TRANAMTWRDS, 
                         dbo.TRANSACTIONMASTER.TRANRMKS, SUM(dbo.TRANSACTIONDETAIL.TRANDQTY) AS TRANDQTY, SUM(dbo.TRANSACTIONDETAIL.TRANDGAMT) AS TRANDGAMT, SUM(dbo.TRANSACTIONDETAIL.TRANDSAMT) 
                         AS TRANDSAMT, SUM(dbo.TRANSACTIONDETAIL.TRANDHAMT) AS TRANDHAMT, SUM(dbo.TRANSACTIONDETAIL.TRANDEAMT) AS TRANDEAMT, SUM(dbo.TRANSACTIONDETAIL.TRANDFAMT) AS TRANDFAMT, 
                         SUM(dbo.TRANSACTIONDETAIL.TRANDAAMT) AS TRANDAAMT, SUM(dbo.TRANSACTIONDETAIL.TRANDNAMT) AS TRANDNAMT, dbo.TRANSACTIONMASTER.LMUSRID, dbo.TRANSACTIONMASTER.CUSRID, 
                         dbo.TRANSACTIONMASTER.LMUSRID AS USRNAME, dbo.TRANSACTIONMASTER.DISPSTATUS, dbo.COMPANYMASTER.COMPPDESC1, dbo.COMPANYMASTER.COMPPDESC2, dbo.TRANSACTIONMASTER.TRANNARTN, 
                         dbo.TRANSACTIONMASTER.TRANPONO, dbo.TRANSACTIONDETAIL.TRANDAHAMT, dbo.TRANSACTIONMASTER.TRANAHAMT, dbo.COMPANYMASTER.COMPGSTNO, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_HSNCODE, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_HSNCODE, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_EXPRN, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_EXPRN, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_EXPRN, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_EXPRN, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_EXPRN, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_EXPRN, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_TAXABLE_AMT, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_TAXABLE_AMT, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_AMT, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_AMT, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_AMT, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_AMT, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_AMT, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_AMT, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.CGST_AMT, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.SGST_AMT, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.IGST_AMT, 
                         dbo.TRANSACTIONMASTER.TRANCSNAME, dbo.TRANSACTIONMASTER.CATEAID, dbo.TRANSACTIONMASTER.TRAN_COVID_DISC_AMT, '# 592,' AS COMPADDR1, 'ENNORE EXPRESS HIGH ROAD,' AS COMPADDR2, 
                         'CHENNAI' AS COMPLOCTDESC, '600057' AS COMPPINCODE, '33' AS COMPSTATECODE, dbo.COMPANYMASTER.COMPPHN1, dbo.COMPANYMASTER.COMPMAIL, '12' AS COMPPOS, 'Nos' AS UNITCODE, 
                         dbo.TRANSACTIONMASTER.HANDL_TAXABLE_AMT + dbo.TRANSACTIONMASTER.HANDL_IGST_AMT + dbo.TRANSACTIONMASTER.HANDL_CGST_AMT + dbo.TRANSACTIONMASTER.HANDL_SGST_AMT AS TOTALITEMVAL, 
                         SUM(dbo.TRANSACTIONDETAIL.TRANDSAMT) AS STRG_AMT, 
                         SUM(dbo.TRANSACTIONDETAIL.TRANDHAMT + dbo.TRANSACTIONDETAIL.TRANDEAMT + dbo.TRANSACTIONDETAIL.TRANDFAMT + dbo.TRANSACTIONDETAIL.TRANDAAMT + dbo.TRANSACTIONMASTER.TRANAHAMT) 
                         AS HANDL_AMT, dbo.TRANSACTIONMASTER.TRANIMPADDR1, dbo.TRANSACTIONMASTER.TRANIMPADDR2, dbo.TRANSACTIONMASTER.TRANIMPADDR3, dbo.TRANSACTIONMASTER.TRANIMPADDR4, 
                         dbo.TRANSACTIONMASTER.CATEAGSTNO AS CATEBGSTNO, STATEMASTER_1.STATECODE, STATEMASTER_1.STATEDESC, dbo.CATEGORYMASTER.CATEPHN1, dbo.CATEGORYMASTER.CATEMAIL,
						 ACHEADDESC
FROM            dbo.STATEMASTER AS STATEMASTER_1 INNER JOIN
                         dbo.TRANSACTIONMASTER INNER JOIN
                         dbo.TRANSACTIONDETAIL ON dbo.TRANSACTIONMASTER.TRANMID = dbo.TRANSACTIONDETAIL.TRANMID INNER JOIN
                         dbo.COMPANYACCOUNTINGDETAIL ON dbo.TRANSACTIONMASTER.COMPYID = dbo.COMPANYACCOUNTINGDETAIL.COMPYID INNER JOIN
                         dbo.COMPANYMASTER ON dbo.COMPANYACCOUNTINGDETAIL.COMPID = dbo.COMPANYMASTER.COMPID INNER JOIN
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01 ON dbo.TRANSACTIONMASTER.TRANMID = dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.TRANMID ON 
                         STATEMASTER_1.STATEID = dbo.TRANSACTIONMASTER.STATEID INNER JOIN
                         dbo.CATEGORYMASTER ON dbo.TRANSACTIONMASTER.TRANREFID = dbo.CATEGORYMASTER.CATEID
GROUP BY dbo.COMPANYMASTER.COMPNAME, dbo.TRANSACTIONMASTER.COMPYID, dbo.TRANSACTIONMASTER.TRANMID, dbo.TRANSACTIONMASTER.SDPTID, dbo.TRANSACTIONMASTER.REGSTRID, 
                         dbo.TRANSACTIONMASTER.TRANBTYPE, dbo.TRANSACTIONMASTER.TRANDATE, RIGHT(dbo.TRANSACTIONMASTER.TRANTIME, 8), dbo.TRANSACTIONMASTER.TRANNO, dbo.TRANSACTIONMASTER.TRANDNO, 
                         dbo.TRANSACTIONMASTER.TRANREFNAME, dbo.TRANSACTIONMASTER.TRANMODE, dbo.TRANSACTIONMASTER.TRANMODEDETL, dbo.TRANSACTIONMASTER.TRANREFNO, dbo.TRANSACTIONMASTER.TRANREFDATE, 
                         dbo.TRANSACTIONMASTER.TRANREFBNAME, dbo.TRANSACTIONMASTER.TRANREFAMT, dbo.TRANSACTIONMASTER.TRANGAMT, dbo.TRANSACTIONMASTER.TRANSAMT, dbo.TRANSACTIONMASTER.TRANHAMT, 
                         dbo.TRANSACTIONMASTER.TRANEAMT, dbo.TRANSACTIONMASTER.TRANFAMT, dbo.TRANSACTIONMASTER.TRANAAMT, dbo.TRANSACTIONMASTER.TRANNAMT, dbo.TRANSACTIONMASTER.TRANAMTWRDS, 
                         dbo.TRANSACTIONMASTER.TRANRMKS, dbo.TRANSACTIONMASTER.LMUSRID, dbo.TRANSACTIONMASTER.CUSRID, dbo.TRANSACTIONMASTER.LMUSRID, dbo.TRANSACTIONMASTER.DISPSTATUS, 
                         dbo.COMPANYMASTER.COMPPDESC1, dbo.COMPANYMASTER.COMPPDESC2, dbo.TRANSACTIONMASTER.TRANNARTN, dbo.TRANSACTIONMASTER.TRANPONO, dbo.TRANSACTIONDETAIL.TRANDAHAMT, 
                         dbo.TRANSACTIONMASTER.TRANAHAMT, dbo.TRANSACTIONMASTER.TRANGSTNO, dbo.COMPANYMASTER.COMPGSTNO, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_HSNCODE, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_HSNCODE, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_EXPRN, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_EXPRN, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_EXPRN, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_EXPRN, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_EXPRN, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_EXPRN, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_TAXABLE_AMT, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_TAXABLE_AMT, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_CGST_AMT, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_SGST_AMT, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.STRG_IGST_AMT, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_CGST_AMT, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_SGST_AMT, 
        dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.HANDL_IGST_AMT, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.CGST_AMT, dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.SGST_AMT, 
                         dbo.VW_IMPORT_MANUAL_TRANSACTION_GST_PRINT_ASSGN_01.IGST_AMT, dbo.TRANSACTIONMASTER.TRANCSNAME, dbo.TRANSACTIONMASTER.CATEAID, dbo.TRANSACTIONMASTER.TRAN_COVID_DISC_AMT, 
                         dbo.COMPANYMASTER.COMPPHN1, dbo.COMPANYMASTER.COMPMAIL, 
                         dbo.TRANSACTIONMASTER.HANDL_TAXABLE_AMT + dbo.TRANSACTIONMASTER.HANDL_IGST_AMT + dbo.TRANSACTIONMASTER.HANDL_CGST_AMT + dbo.TRANSACTIONMASTER.HANDL_SGST_AMT, 
                         dbo.TRANSACTIONMASTER.TRANIMPADDR1, dbo.TRANSACTIONMASTER.TRANIMPADDR2, dbo.TRANSACTIONMASTER.TRANIMPADDR3, dbo.TRANSACTIONMASTER.TRANIMPADDR4, dbo.TRANSACTIONMASTER.CATEAGSTNO, 
                         STATEMASTER_1.STATECODE, STATEMASTER_1.STATEDESC, dbo.CATEGORYMASTER.CATEPHN1, dbo.CATEGORYMASTER.CATEMAIL, ACHEADDESC
HAVING        (dbo.TRANSACTIONMASTER.DISPSTATUS = 0)



