CREATE PROCEDURE [dbo].[z_pr_XML_Stuffed_SBill_No_Detail_Assgn] @PSTFDID int
AS
BEGIN

	SET NOCOUNT ON;

	SELECT        dbo.STUFFINGPRODUCTDETAIL.STFPID, dbo.STUFFINGPRODUCTDETAIL.STFDSBNO, 
	dbo.STUFFINGPRODUCTDETAIL.STFDSBDATE, dbo.GATEINDETAIL.PRDTDESC, dbo.STUFFINGPRODUCTDETAIL.STFDNOP,
	STF_PACKETS_FROM,STF_PACKETS_TO
	FROM            dbo.STUFFINGDETAIL INNER JOIN
							 dbo.STUFFINGPRODUCTDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID INNER JOIN
							 dbo.GATEINDETAIL ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID
	WHERE        (dbo.STUFFINGDETAIL.STFDID = @PSTFDID)
	Order by dbo.STUFFINGPRODUCTDETAIL.STFDSBDATE

END
