
CREATE PROCEDURE [dbo].[z_pr_XML_Stuffed_SBill_No_Detail_With_CIN_No] @PSTFDID int
AS
BEGIN

	SET NOCOUNT ON;
	/*
	SELECT        TOP (100) PERCENT dbo.STUFFINGPRODUCTDETAIL.STFPID, dbo.STUFFINGPRODUCTDETAIL.STFDSBNO, dbo.STUFFINGPRODUCTDETAIL.STFDSBDATE, dbo.GATEINDETAIL.PRDTDESC, 
							 dbo.STUFFINGPRODUCTDETAIL.STFDNOP, dbo.STUFFINGPRODUCTDETAIL.STF_PACKETS_FROM, dbo.STUFFINGPRODUCTDETAIL.STF_PACKETS_TO, dbo.XML_CHPOE07Payload_Leo.CinNo
	FROM            dbo.XML_CHPOE07Payload_Leo INNER JOIN
							 dbo.STUFFINGDETAIL INNER JOIN
							 dbo.STUFFINGPRODUCTDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID INNER JOIN
							 dbo.GATEINDETAIL ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID ON dbo.XML_CHPOE07Payload_Leo.SBNo = dbo.STUFFINGPRODUCTDETAIL.STFDSBNO
	WHERE        (dbo.STUFFINGDETAIL.STFDID = @PSTFDID)
	ORDER BY dbo.STUFFINGPRODUCTDETAIL.STFDSBDATE
	*/
	SELECT        TOP (100) PERCENT MAX(dbo.STUFFINGPRODUCTDETAIL.STFPID) AS STFPID, dbo.STUFFINGPRODUCTDETAIL.STFDSBNO, dbo.STUFFINGPRODUCTDETAIL.STFDSBDATE, dbo.GATEINDETAIL.PRDTDESC, 
							 SUM(dbo.STUFFINGPRODUCTDETAIL.STFDNOP) AS STFDNOP, dbo.STUFFINGPRODUCTDETAIL.STF_PACKETS_FROM, dbo.STUFFINGPRODUCTDETAIL.STF_PACKETS_TO, dbo.XML_CHPOE07Payload_Leo.CinNo
	FROM            dbo.XML_CHPOE07Payload_Leo INNER JOIN
							 dbo.STUFFINGDETAIL INNER JOIN
							 dbo.STUFFINGPRODUCTDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID INNER JOIN
							 dbo.GATEINDETAIL ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID ON dbo.XML_CHPOE07Payload_Leo.SBNo = dbo.STUFFINGPRODUCTDETAIL.STFDSBNO
	WHERE        (dbo.STUFFINGDETAIL.STFDID = @PSTFDID)
	GROUP BY dbo.STUFFINGPRODUCTDETAIL.STFDSBNO, dbo.STUFFINGPRODUCTDETAIL.STFDSBDATE, dbo.GATEINDETAIL.PRDTDESC, dbo.STUFFINGPRODUCTDETAIL.STF_PACKETS_FROM, 
							 dbo.STUFFINGPRODUCTDETAIL.STF_PACKETS_TO, dbo.XML_CHPOE07Payload_Leo.CinNo
	ORDER BY dbo.STUFFINGPRODUCTDETAIL.STFDSBDATE

END

