
CREATE PROCEDURE [dbo].[z_pr_XML_Export_Stuffed_Detail_Assgn] @PSTFDID int
AS
BEGIN

	SET NOCOUNT ON;

	/*
	SELECT        dbo.STUFFINGDETAIL.STFDID, dbo.STUFFINGDETAIL.STFMID, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMDATE, dbo.STUFFINGMASTER.STFBILLREFNAME, 
							 dbo.EXPORT_OPERATIONTYPEMASTER.EOPTDESC, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC
	FROM            dbo.STUFFINGDETAIL INNER JOIN
							 dbo.STUFFINGMASTER ON dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID INNER JOIN
							 dbo.EXPORT_OPERATIONTYPEMASTER ON dbo.STUFFINGMASTER.EOPTID = dbo.EXPORT_OPERATIONTYPEMASTER.EOPTID INNER JOIN
							 dbo.GATEINDETAIL ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
							 dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID
	WHERE STFDID = @PSTFDID
	*/

	SELECT        dbo.STUFFINGDETAIL.STFDID, dbo.STUFFINGDETAIL.STFMID, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGMASTER.STFMDATE, dbo.STUFFINGMASTER.STFBILLREFNAME, 
							 dbo.EXPORT_OPERATIONTYPEMASTER.EOPTDESC, dbo.GATEINDETAIL.CONTNRNO, dbo.CONTAINERSIZEMASTER.CONTNRSDESC, dbo.AUTHORIZATIONSLIPDETAIL.CSEALNO, 
							 dbo.AUTHORIZATIONSLIPDETAIL.ASEALNO
	FROM            dbo.STUFFINGDETAIL INNER JOIN
							 dbo.STUFFINGMASTER ON dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID INNER JOIN
							 dbo.EXPORT_OPERATIONTYPEMASTER ON dbo.STUFFINGMASTER.EOPTID = dbo.EXPORT_OPERATIONTYPEMASTER.EOPTID INNER JOIN
							 dbo.GATEINDETAIL ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID INNER JOIN
							 dbo.CONTAINERSIZEMASTER ON dbo.GATEINDETAIL.CONTNRSID = dbo.CONTAINERSIZEMASTER.CONTNRSID INNER JOIN
							 dbo.AUTHORIZATIONSLIPDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.AUTHORIZATIONSLIPDETAIL.STFDID
	WHERE        (dbo.STUFFINGDETAIL.STFDID = @PSTFDID)

END


