create VIEW [dbo].[Z_TRANSACTION_BONDPRINT_ASSGN]
AS
SELECT        dbo.BONDTRANSACTIONMASTER.TRANMID, dbo.BONDMASTER.BNDID, dbo.BONDMASTER.BNDNOP,
				dbo.BONDMASTER.BNDSPC, dbo.BONDMASTER.BNDNOP - dbo.BONDTRANSACTIONDETAIL.TRANDNOP AS BBNDNOP
FROM            dbo.BONDTRANSACTIONMASTER INNER JOIN
                         dbo.BONDTRANSACTIONDETAIL ON dbo.BONDTRANSACTIONMASTER.TRANMID = dbo.BONDTRANSACTIONDETAIL.TRANMID INNER JOIN
                         dbo.BONDMASTER ON dbo.BONDTRANSACTIONDETAIL.BNDID = dbo.BONDMASTER.BNDID LEFT JOIN
                         --dbo.BONDMASTER ON dbo.BONDTRANSACTIONDETAIL.EBNDID = dbo.BONDMASTER.EBNDID INNER JOIN
                         dbo.SLABTYPEMASTER ON dbo.BONDTRANSACTIONDETAIL.SLABTID = dbo.SLABTYPEMASTER.SLABTID LEFT JOIN
                         dbo.BONDGODOWNMASTER ON dbo.BONDMASTER.GWNID = dbo.BONDGODOWNMASTER.GWNID INNER JOIN
                         --dbo.EMPLOYEEMASTER ON dbo.BONDTRANSACTIONMASTER.LMUSRID = dbo.EMPLOYEEMASTER.USRID INNER JOIN
                         dbo.CATEGORYMASTER ON dbo.BONDTRANSACTIONMASTER.BILLREFID = dbo.CATEGORYMASTER.CATEID LEFT OUTER JOIN
                         dbo.STATEMASTER ON dbo.CATEGORYMASTER.STATEID = dbo.STATEMASTER.STATEID
GROUP BY dbo.BONDTRANSACTIONMASTER.TRANMID, dbo.BONDMASTER.BNDID, dbo.BONDMASTER.BNDNOP,  dbo.BONDMASTER.BNDSPC, 
                         dbo.BONDMASTER.BNDNOP - dbo.BONDTRANSACTIONDETAIL.TRANDNOP