CREATE PROCEDURE [dbo].[z_XML_JSON_Packets_From_To_Details_Update] 
@PSTFPID int,
@PSTFPFrom int,
@PSTFPTo int
AS
BEGIN

	SET NOCOUNT ON;

	UPdate STUFFINGPRODUCTDETAIL Set STF_PACKETS_FROM = @PSTFPFrom, STF_PACKETS_TO = @PSTFPTo
	Where STFPID = @PSTFPID
    
END

