use SCFS_ERP
go
 

--delete SCFS_ERP.DBO.GATEINDETAIL WHERE SDPTID = 2
--delete SCFS_ERP.DBO.SHIPPINGBILLMASTER 
--delete SCFS_ERP.DBO.SHIPPINGBILLDETAIL
--delete SCFS_ERP.DBO.EXPORTSHIPPINGBILLMASTER
--delete SCFS_ERP.DBO.EXPORTSHIPPINGBILLDETAIL
--delete SCFS_ERP.DBO.STUFFINGMASTER

--delete SCFS_ERP.DBO.AUTHORIZATIONSLIPMASTER WHERE SDPTID = 2
--delete SCFS_ERP.DBO.VEHICLETICKETDETAIL WHERE SDPTID = 2
--delete SCFS_ERP.DBO.GATEOUTDETAIL WHERE SDPTID = 2

--GateInDetail Insert Assgn
-- GI
EXEC [Z_EXPORT_GATEIN_DETAIL_Auto_Generate_XML]
GO

	update B
	SET ROWID = C.ROWID
	from SCFS_ERP.DBO.GATEINDETAIL B, SLOTMASTER C(NOLOCK)
	WHERE OLDGID > 0 
	AND B.SLOTID = C.SLOTID
	and SDPTID = 2

	update B
	SET CONTNRID = 1
	from SCFS_ERP.DBO.GATEINDETAIL B
	WHERE OLDGID > 0
	and CONTNRID = 0
	and SDPTID = 2

	update A
			set CHAID = CATEID
			FROM SCFS_ERP.DBO.GATEINDETAIL A JOIN CATEGORYMASTER B(NOLOCK) ON A.CHANAME = B.CATENAME 
			where ISNULL(CHAID,0)= 0
			AND B.CATETID = 4

			
	update A
			set STMRID = CATEID
			FROM SCFS_ERP.DBO.GATEINDETAIL A JOIN CATEGORYMASTER B(NOLOCK) ON A.STMRNAME = B.CATENAME 
			where ISNULL(STMRID,0)= 0
			AND B.CATETID = 4

	

-- SHIPPINGBILLMASTER-DETAIL 
EXEC [Z_SHIPPINGBILLMASTER_DETAIL_Auto_Generate_XML]
GO


UPDATE A
SET GIDID = B.GIDID
FROM SHIPPINGBILLDETAIL A, GATEINDETAIL B(NOLOCK)
WHERE A.OLDSBDID > 0 
AND A.GIDID = B.OLDGID


UPDATE A
SET ESBMID= B.ESBMID
FROM SHIPPINGBILLDETAIL A, EXPORTSHIPPINGBILLMASTER B(NOLOCK)
WHERE A.OLDSBDID > 0 
AND A.ESBMID = B.OLDESBMID

UPDATE [SCFS_ERP].[dbo].EXPORTSHIPPINGBILLMASTER
SET ESBMDNO = ESBMID, ESBMNO = ESBMID
WHERE OLDESBMID > 0

UPDATE B
SET ESBNO = A.ESBMDNO, ESBDATE = A.ESBMDATE, ESBMID = A.ESBMID, EXPRTRID = A.EXPRTID, EXPRTRNAME = A.EXPRTNAME 
FROM [SCFS_ERP].[dbo].GATEINDETAIL B , EXPORTSHIPPINGBILLMASTER A (NOLOCK), SHIPPINGBILLDETAIL C(NOLOCK)
WHERE OLDGID > 0
AND A.ESBMID = C.ESBMID
AND B.GIDID = C.GIDID

INSERT INTO [SCFS_ERP].[dbo].EXPORTSHIPPINGBILLDETAIL
					 (
					  ESBMID, ESBD_SBILLNO, ESBD_SBILLDATE , ESBOINVNO, ESBOINVDATE, ESBOINVAMT, ESBOINVFOBAMT, ESBDDPNAME, PRDTDESC, ESBMNOP, ESBMQTY, CUSRID, LMUSRID,
					  PRCSDATE, DISPSTATUS 
					)
					SELECT		ESBMID, ESBMDNO, ESBMDATE , ESBMREFNO, ESBMREFDATE, ESBMREFAMT, ESBMFOBAMT, ESBMDPNAME, PRDTDESC, ESBMNOP, ESBMQTY, CUSRID, LMUSRID,
								PRCSDATE, DISPSTATUS 
					FROM		[SCFS_ERP].[dbo].EXPORTSHIPPINGBILLMASTER (NOLOCK)
					WHERE		OLDESBMID > 0
					AND ESBMID NOT IN (SELECT ESBMID FROM EXPORTSHIPPINGBILLDETAIL)



-- STUFFINGLMASTER-DETAIL 
EXEC [Z_EXPORT_STUFFING_MASTERDETAIL_Auto_Generate_XML]
GO



	update a
	SET GIDID = B.GIDID
	from [SCFS_ERP].dbo.STUFFINGDETAIL a, SCFS_ERP.DBO.GATEINDETAIL B(NOLOCK)
	WHERE A.GIDID = B.OLDGID
	and a.OLDSTFDID > 0 
	--SELECT * FROM STUFFINGMASTER 
--Update CHA Adress Detaila
UPDATE STUFFINGMASTER SET CATEAGSTNO = SCFS_ERP.dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO,
TRANIMPADDR1 = CATEAADDR1, TRANIMPADDR2 = CATEAADDR2, TRANIMPADDR3 = CATEAADDR3, TRANIMPADDR4 = CATEAADDR4,
STATEID = dbo.CATEGORY_ADDRESS_DETAIL.STATEID
FROM SCFS_ERP.DBO.STUFFINGMASTER INNER JOIN
				   SCFS_ERP.dbo.CATEGORY_ADDRESS_DETAIL ON 
				   DBO.STUFFINGMASTER.CHAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID and
				   dbo.STUFFINGMASTER.STFCATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID
where 
isnull(SCFS_ERP.DBO.STUFFINGMASTER.CATEAGSTNO ,'') ='' or isnull(TRANIMPADDR1,'') = ''

update a
	SET SBDID = B.SBDID
	from [SCFS_ERP].dbo.STUFFINGPRODUCTDETAIL a, SCFS_ERP.DBO.SHIPPINGBILLDETAIL B(NOLOCK)
	WHERE A.SBDID = B.OLDSBDID
	and OLDSBDID > 0 

--Update Billing CHA Adress Detaila

UPDATE STUFFINGMASTER SET STFBCHAGSTNO = SCFS_ERP.dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO,
STFBCHAADDR1 = CATEAADDR1, STFBCHAADDR2 = CATEAADDR2, STFBCHAADDR3 = CATEAADDR3, STFBCHAADDR4 = CATEAADDR4,
STFBCHASTATEID = dbo.CATEGORY_ADDRESS_DETAIL.STATEID
FROM SCFS_ERP.DBO.STUFFINGMASTER INNER JOIN
				   SCFS_ERP.dbo.CATEGORY_ADDRESS_DETAIL ON 
				   DBO.STUFFINGMASTER.STFBILLREFID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID and
				   dbo.STUFFINGMASTER.STFBCATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID
where isnull(SCFS_ERP.DBO.STUFFINGMASTER.STFBCHAGSTNO ,'') ='' or isnull(TRANIMPADDR1,'') = ''



-- ASL

EXEC [Z_EXPORT_ASL_DETAIL_Auto_Generate_XML]
GO

update a
SET GIDID = B.GIDID
from [SCFS_ERP].dbo.AUTHORIZATIONSLIPDETAIL a, SCFS_ERP.DBO.GATEINDETAIL B(NOLOCK)
WHERE A.GIDID = B.OLDGID
AND A.OLDASLDID > 0 
AND SDPTID = 2



update C
SET ASLMNO = C.ASLMID, ASLMDNO = C.ASLMID
from [SCFS_ERP].dbo.AUTHORIZATIONSLIPDETAIL a, [SCFS_ERP].dbo.AUTHORIZATIONSLIPMASTER C
WHERE  A.ASLMID = C.ASLMID
AND A.OLDASLDID > 0 
AND SDPTID = 2

GO

-- VT
EXEC [Z_EXPORT_VT_DETAIL_Auto_Generate_XML]
GO


--update a
--SET GIDID = C.GIDID
--from [SCFS_ERP].dbo.VEHICLETICKETDETAIL a, [SCFS_ERP].dbo.AUTHORIZATIONSLIPDETAIL B(NOLOCK),
-- [SCFS].dbo.OPENSHEETDETAIL C(NOLOCK)
--WHERE A.ASLDID = B.OLDASLDID
--AND B.OSDID = C.OLDOSDID
--AND A.OLDVTDID > 0 

update a
SET GIDID = B.GIDID
from [SCFS_ERP].dbo.VEHICLETICKETDETAIL a, SCFS_ERP.DBO.GATEINDETAIL B(NOLOCK)
WHERE A.GIDID = B.OLDGID
AND A.OLDVTDID > 0 

update a
SET VTNO = VTDID, VTDNO = VTDID
from [SCFS_ERP].dbo.VEHICLETICKETDETAIL a
WHERE A.OLDVTDID > 0 
AND SDPTID = 2

update a
SET ASLDID = C.ASLDID
from [SCFS_ERP].dbo.VEHICLETICKETDETAIL a, SCFS_ERP.DBO.AUTHORIZATIONSLIPDETAIL C
WHERE  A.ASLDID = C.OLDASLDID
AND A.OLDVTDID > 0 
AND SDPTID = 2

GO

EXEC [Z_EXPORT_GO_DETAIL_Auto_Generate_XML]
GO

--SELECT * fROM GATEOUTDETAIL WHERE OLDGODID > 0 AND SDPTID
update a
SET GONO = GODID, GODNO = GODID
from [SCFS_ERP].dbo.GATEOUTDETAIL a
WHERE OLDGODID > 0 
AND SDPTID = 2

update a
SET EHIDATE = PRCSDATE, EHITIME= PRCSDATE
from [SCFS_ERP].dbo.GATEOUTDETAIL a
WHERE OLDGODID > 0 
AND SDPTID = 2

update a
SET GIDID = B.GIDID
from [SCFS_ERP].dbo.GATEOUTDETAIL a JOIN [SCFS_ERP].dbo.GATEINDETAIL B ON A.GIDID = B.OLDGID
WHERE B.OLDGID > 0 
AND a.SDPTID = 2


