select * from GATEINDETAIL where SDPTID not in(9,11)

select * from GATEINDETAIL where SDPTID in(1)

--delete from GATEINDETAIL where SDPTID not in(9,11) --AND ISNULL(OLDGID ,0) <> 0

--Gate In Details
Select * From [SCFS].dbo.GATEINDETAIL (NOLOCK) INNER JOIN
       [SCFS].dbo.Z_EXPDIN_27092021 (NOLOCK) ON [SCFS].dbo.GATEINDETAIL.GIDID = [SCFS].dbo.Z_EXPDIN_27092021.GIDID

select DISTINCT GIDID from [SCFS].dbo.Z_EXPDIN_27092021

-- OLD REF ID
USE SCFS_ERP
GO

alter table GATEINDETAIL
add OLDGID INT NULL DEFAULT 0


-- OLD REF ID
USE SCFS_ERP
GO


alter table STUFFINGDETAIL 
add OLDSTFDID INT NULL DEFAULT 0

alter table EXPORTSHIPPINGBILLMASTER
add OLDESBMID INT NULL DEFAULT 0

alter table SHIPPINGBILLDETAIL
add OLDSBDID INT NULL DEFAULT 0

--alter table AUTHORIZATIONSLIPDETAIL
--add OLDASLDID INT NULL DEFAULT 0


--alter table GATEOUTDETAIL
--add OLDGODID INT NULL DEFAULT 0


--- EXPORT 
GO

USE SCFS
GO
--- SELECT * INTO ZEXPBK01102021 FROM Z_EXPDIN_27092021
IF EXISTS (SELECT '*' FROM SYSOBJECTS WHERE NAME = 'Z_EXPDIN_27092021')
DROP TABLE Z_EXPDIN_27092021


--bASED ON sTUFFING
SELECT      DISTINCT  dbo.STUFFINGDETAIL.STFMID, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGPRODUCTDETAIL.SBDID, dbo.SHIPPINGBILLDETAIL.GIDID, dbo.STUFFINGDETAIL.STFDID, dbo.SHIPPINGBILLDETAIL.SBMID, 
                         dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, dbo.VEHICLETICKETDETAIL.VTDID, dbo.GATEINDETAIL.GIDID AS Expr1, dbo.GATEINDETAIL.CONTNRNO, 0 AS GODID
INTO Z_EXPDIN_27092021
FROM            dbo.STUFFINGDETAIL INNER JOIN
                         dbo.STUFFINGMASTER ON dbo.STUFFINGDETAIL.STFMID = dbo.STUFFINGMASTER.STFMID INNER JOIN
                         dbo.STUFFINGPRODUCTDETAIL ON dbo.STUFFINGDETAIL.STFDID = dbo.STUFFINGPRODUCTDETAIL.STFDID INNER JOIN
                         dbo.SHIPPINGBILLDETAIL ON dbo.STUFFINGPRODUCTDETAIL.SBDID = dbo.SHIPPINGBILLDETAIL.SBDID LEFT OUTER JOIN
                         dbo.GATEINDETAIL ON dbo.STUFFINGDETAIL.GIDID = dbo.GATEINDETAIL.GIDID LEFT OUTER JOIN
                         dbo.VEHICLETICKETDETAIL RIGHT OUTER JOIN
                         dbo.AUTHORIZATIONSLIPDETAIL ON dbo.VEHICLETICKETDETAIL.ASLDID = dbo.AUTHORIZATIONSLIPDETAIL.ASLDID ON dbo.STUFFINGDETAIL.STFDID = dbo.AUTHORIZATIONSLIPDETAIL.STFDID LEFT OUTER JOIN
                         dbo.VW_EXPORT_INVOICE_SBILL_NO_CBX_ASSGN_01 ON dbo.STUFFINGDETAIL.STFDID = dbo.VW_EXPORT_INVOICE_SBILL_NO_CBX_ASSGN_01.STFDID
WHERE        (ISNULL(dbo.VW_EXPORT_INVOICE_SBILL_NO_CBX_ASSGN_01.TRANDID, 0) = 0)
GROUP BY dbo.STUFFINGDETAIL.STFMID, dbo.STUFFINGMASTER.STFMDNO, dbo.STUFFINGPRODUCTDETAIL.SBDID, dbo.SHIPPINGBILLDETAIL.GIDID, dbo.STUFFINGDETAIL.STFDID, dbo.SHIPPINGBILLDETAIL.SBMID, 
                         dbo.AUTHORIZATIONSLIPDETAIL.ASLDID, dbo.VEHICLETICKETDETAIL.VTDID, dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO

INSERT INTO Z_EXPDIN_27092021 (GIDID, SBDID, SBMID, STFMID, STFDID,GODID,STFMDNO)
SELECT        scfs.dbo.GATEINDETAIL.GIDID,0,0,0,0,0,0
FROM            scfs.dbo.GATEINDETAIL INNER JOIN
                         scfs.dbo.SHIPPINGBILLDETAIL ON scfs.dbo.GATEINDETAIL.GIDID = scfs.dbo.SHIPPINGBILLDETAIL.GIDID LEFT OUTER JOIN
                         scfs.dbo.STUFFINGPRODUCTDETAIL ON scfs.dbo.SHIPPINGBILLDETAIL.SBDID = scfs.dbo.STUFFINGPRODUCTDETAIL.SBDID
WHERE        (scfs.dbo.STUFFINGPRODUCTDETAIL.STFPID IS NULL)
and (
	(scfs.dbo.GATEINDETAIL.CHAID = 20610 or scfs.dbo.GATEINDETAIL.CHAID = 18872) or 
	(scfs.dbo.GATEINDETAIL.CHAID <> 20610 and scfs.dbo.GATEINDETAIL.CHAID <> 18872 and GIDATE>='2021-09-01')
	)
AND scfs.dbo.GATEINDETAIL.GIDID NOT IN (SELECT GIDID FROM Z_EXPDIN_27092021)  


INSERT INTO Z_EXPDIN_27092021 (SBDID, SBMID,GODID,STFMDNO,STFMID,GIDID,STFDID)
SELECT        scfs.dbo.SHIPPINGBILLDETAIL.SBDID, scfs.dbo.SHIPPINGBILLDETAIL.SBMID, 0, 0,0,0,0
FROM            scfs.dbo.GATEINDETAIL INNER JOIN
                         scfs.dbo.SHIPPINGBILLDETAIL ON scfs.dbo.GATEINDETAIL.GIDID = scfs.dbo.SHIPPINGBILLDETAIL.GIDID LEFT OUTER JOIN
                         scfs.dbo.STUFFINGPRODUCTDETAIL ON scfs.dbo.SHIPPINGBILLDETAIL.SBDID = scfs.dbo.STUFFINGPRODUCTDETAIL.SBDID
WHERE        (scfs.dbo.STUFFINGPRODUCTDETAIL.STFPID IS NULL)
and (
	(scfs.dbo.GATEINDETAIL.CHAID = 20610 or scfs.dbo.GATEINDETAIL.CHAID = 18872) or 
	(scfs.dbo.GATEINDETAIL.CHAID <> 20610 and scfs.dbo.GATEINDETAIL.CHAID <> 18872 and GIDATE>='2021-10-01')
	)
AND scfs.dbo.SHIPPINGBILLDETAIL.SBDID NOT IN (SELECT SBDID FROM Z_EXPDIN_27092021 where SBDID > 0)  

--tRUCK pENDING
INSERT INTO Z_EXPDIN_27092021 (GIDID, GODID, STFMID, STFMDNO, SBDID,STFDID, SBMID)
SELECT     DISTINCT dbo.GATEINDETAIL.GIDID, 0, 0, 0,0,0,0
FROM         dbo.GATEINDETAIL LEFT OUTER JOIN
                      dbo.VW_SHIPPINGBILL_GATEINT_TRUCKNO_CBX_ASSGN ON 
                      dbo.GATEINDETAIL.GIDID = dbo.VW_SHIPPINGBILL_GATEINT_TRUCKNO_CBX_ASSGN.GIDID
WHERE     (dbo.GATEINDETAIL.GPSTYPE IN (1, 5)) AND (dbo.GATEINDETAIL.SDPTID = 2) AND 
                      (dbo.GATEINDETAIL.GPNOP - ISNULL(dbo.VW_SHIPPINGBILL_GATEINT_TRUCKNO_CBX_ASSGN.SBDNOP, 0) > 0)
and (GIDATE >='2021-04-01')  
and (
	(scfs.dbo.GATEINDETAIL.CHAID = 20610 or scfs.dbo.GATEINDETAIL.CHAID = 18872) or 
	(scfs.dbo.GATEINDETAIL.CHAID <> 20610 and scfs.dbo.GATEINDETAIL.CHAID <> 18872 and GIDATE>='2021-04-01')
	) 
AND dbo.GATEINDETAIL.GIDID NOT IN (SELECT GIDID FROM Z_EXPDIN_27092021)             


--cONTAINER pENDING
INSERT INTO Z_EXPDIN_27092021 (GIDID, CONTNRNO, GODID, STFMID, STFMDNO, SBDID,STFDID, SBMID)
SELECT     DISTINCT dbo.GATEINDETAIL.GIDID, dbo.GATEINDETAIL.CONTNRNO , 0, 0, 0,0,0,0
FROM         dbo.GATEINDETAIL LEFT OUTER JOIN
                      dbo.STUFFINGDETAIL ON dbo.GATEINDETAIL.GIDID = dbo.STUFFINGDETAIL.GIDID
WHERE (dbo.GATEINDETAIL.DispStatus = 0) and      (dbo.GATEINDETAIL.GPSTYPE = 4)  AND (ISNULL(dbo.STUFFINGDETAIL.STFMID, 0) = 0)
AND (GIDATE >= '2021-04-01')
AND dbo.GATEINDETAIL.GIDID NOT IN (SELECT GIDID FROM Z_EXPDIN_27092021)
--cONTAINER pENDING
INSERT INTO Z_EXPDIN_27092021 (GIDID,  GODID, STFMID, STFMDNO, SBDID,STFDID, SBMID)
SELECT     expr1, 0, 0, 0,0,0,0
FROM        Z_EXPDIN_27092021
where dbo.Z_EXPDIN_27092021.GIDID NOT IN (SELECT GIDID FROM Z_EXPDIN_27092021)

SELECT * FROM Z_EXPDIN_27092021
WHERE GIDID = 372948	

SELECT * FROM Z_EXPDIN_27092021
WHERE SBDID = 74435

SELECT * FROM Z_EXPDIN_27092021
WHERE ESBMID = 31652

--GI Cursor
USE [SCFS_ERP]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

alter PROCEDURE [dbo].[Z_EXPORT_GATEIN_DETAIL_Auto_Generate_XML]
AS
BEGIN
	SET NOCOUNT ON
	
      DECLARE @Counter INT
      SET @Counter = 1
      
	  DELETE [SCFS_ERP].dbo.GATEINDETAIL WHERE OLDGID > 0 AND SDPTID = 2

	  Declare @GIDID int

      --DECLARE THE CURSOR FOR A QUERY.
      DECLARE GIDetail CURSOR READ_ONLY
      FOR
	  
	  Select DISTINCT [SCFS].dbo.Z_EXPDIN_27092021.GIDID 
	  From [SCFS].dbo.Z_EXPDIN_27092021 (nolock)
      --OPEN CURSOR.
      OPEN GIDetail
 
      --FETCH THE RECORD INTO THE VARIABLES.
      FETCH NEXT FROM GIDetail INTO @GIDID
 
      --LOOP UNTIL RECORDS ARE AVAILABLE.
      WHILE @@FETCH_STATUS = 0
      BEGIN

			EXEC Z_EXPORT_GATEIN_DETAIL_INSERT_XML @GIDID
             --INCREMENT COUNTER.
			 
             SET @Counter = @Counter + 1
             
             --FETCH THE NEXT RECORD INTO THE VARIABLES.
             FETCH NEXT FROM GIDetail INTO @GIDID
      END
 
      --CLGIE THE CURSOR.
      CLOSE GIDetail
      DEALLOCATE GIDetail


END


--GI DEtail Insert
USE [SCFS_ERP]
GO
/****** Object:  StoredProcedure [dbo].[Z_EXPORT_GATEIN_DETAIL_INSERT_XML]    Script Date: 20/09/2021 19:37:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[Z_EXPORT_GATEIN_DETAIL_INSERT_XML] 
@PGIDID INT
AS
BEGIN
	  SET NOCOUNT ON
	
	  Declare @ccount int, @boecount int

	  Set @ccount = 1
	  Set @boecount = 0
	  
	  If @ccount > 0 

  			INSERT INTO [SCFS_ERP].dbo.GATEINDETAIL
			(COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GIVHLTYPE, TRNSPRTID, TRNSPRTNAME, VHLNO, DRVNAME, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, 
									 CONTNRID, CONTNRSID, CONTNRNO, LPSEALNO, CSEALNO, YRDID, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, IGMNO, GPLNO, GPWTYPE, GPSTYPE, GPETYPE, BOEDID, INVDID, RGIDID, 
									 GIREMKRS, SLOTID, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, GPEAMT, BCHAID, BCHANAME, AVHLNO, GPNOP, PRDTTID, GIISOCODE, GIDMGDESC, NGIDID, GPNWGHT, GPGWGHT, GPCBM, GPLENGTH, GPWIDTH, 
									 GPHEIGHT, GPBLNO, GPAAMT, CLNTID, CLNTNAME, SHPRNAME, GPPLCNAME, GPTWGHT, CONTNRFID, CONDTNID, GRADEID, CNTNRSID, GPPTYPE, GFCLTYPE, GSEALTYPE, GSECTYPE, GSEALREMKRS, GSECREMKRS, 
									 GPNRNO, ESBNO, EVSLRNO, EMONO, EEGMNO, ESBDATE, GPSCNTYPE, IGMDATE, BLNO, GPMODEID, OLDGID,  CHANAME)
			Select COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GIVHLTYPE, TRNSPRTID, TRNSPRTNAME, VHLNO, 
			DRVNAME, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, CONTNRID, CONTNRSID, 
			[SCFS].dbo.GATEINDETAIL.CONTNRNO, LPSEALNO, CSEALNO, YRDID, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, 
			[SCFS].dbo.GATEINDETAIL.IGMNO, [SCFS].dbo.GATEINDETAIL.GPLNO, GPWTYPE, GPSTYPE, GPETYPE, BOEDID, INVDID, RGIDID, 
			GIREMKRS, SLOTID, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, GPEAMT, CHAID, CHANAME, AVHLNO, GPNOP, PRDTTID, GIISOCODE, 
			GIDMGDESC, NGIDID, GPNWGHT, GPGWGHT, GPCBM, GPLENGTH, GPWIDTH, GPHEIGHT, GPBLNO, GPAAMT, CLNTID, CLNTNAME, SHPRNAME, 
			GPPLCNAME, GPTWGHT, CONTNRFID, CONDTNID, GRADEID, CNTNRSID, GPPTYPE, CASE WHEN GFCLTYPE = 0 THEN 1 ELSE 0 END, GSEALTYPE, GSECTYPE, GSEALREMKRS, 
			GSECREMKRS, GPNRNO, ESBNO, EVSLRNO, EMONO, EEGMNO, ESBDATE, GPSCNTYPE, IGMDATE, BLNO, GPMODEID, GATEINDETAIL.GIDID,STMRNAME
			From [SCFS].dbo.GATEINDETAIL (NOLOCK) 
			where [SCFS].dbo.GATEINDETAIL.GIDID = @PGIDID
			group by COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GIVHLTYPE, TRNSPRTID, TRNSPRTNAME, VHLNO, 
			DRVNAME, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, CONTNRID, CONTNRSID, 
			[SCFS].dbo.GATEINDETAIL.CONTNRNO, LPSEALNO, CSEALNO, YRDID, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, 
			[SCFS].dbo.GATEINDETAIL.IGMNO, [SCFS].dbo.GATEINDETAIL.GPLNO, GPWTYPE, GPSTYPE, GPETYPE, BOEDID, INVDID, RGIDID, 
			GIREMKRS, SLOTID, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, GPEAMT, CHAID, CHANAME, AVHLNO, GPNOP, PRDTTID, GIISOCODE, 
			GIDMGDESC, NGIDID, GPNWGHT, GPGWGHT, GPCBM, GPLENGTH, GPWIDTH, GPHEIGHT, GPBLNO, GPAAMT, CLNTID, CLNTNAME, SHPRNAME, 
			GPPLCNAME, GPTWGHT, CONTNRFID, CONDTNID, GRADEID, CNTNRSID, GPPTYPE, CASE WHEN GFCLTYPE = 0 THEN 1 ELSE 0 END, GSEALTYPE, GSECTYPE, GSEALREMKRS, 
			GSECREMKRS, GPNRNO, ESBNO, EVSLRNO, EMONO, EEGMNO, ESBDATE, GPSCNTYPE, IGMDATE, BLNO, GPMODEID, GATEINDETAIL.GIDID

			update [SCFS_ERP].dbo.GATEINDETAIL
			set CONTNRID = 1
			where GIDID = @PGIDID
			and CONTNRID = 0

			update A
			set CHAID = CATEID
			FROM SCFS_ERP.DBO.GATEINDETAIL A JOIN CATEGORYMASTER B(NOLOCK) ON A.CHANAME = B.CATENAME 
			where GIDID = @PGIDID
			and ISNULL(CHAID,0)= 0
			AND B.CATETID = 4

			update A
			set STMRID = CATEID
			FROM SCFS_ERP.DBO.GATEINDETAIL A JOIN CATEGORYMASTER B(NOLOCK) ON A.STMRNAME = B.CATENAME 
			where GIDID = @PGIDID
			and ISNULL(STMRID,0)= 0
			AND B.CATETID = 4
			
			

END

--Shipping Bill Cursor
USE [SCFS_ERP]
GO
/****** Object:  StoredProcedure [dbo].[Z_EXPORT_SHIPPINGBILLMASTER_DETAIL_AUTO_GENERATE_XML]    Script Date: 20/09/2021 19:37:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--drop proc [Z_SHIPPINGBILLMASTER_DETAIL_Auto_Generate_XML]
ALTER PROCEDURE [dbo].[Z_SHIPPINGBILLMASTER_DETAIL_Auto_Generate_XML]
AS
BEGIN
	SET NOCOUNT ON
	
      DECLARE @Counter INT
      SET @Counter = 1
      
	  Delete a 
	  From [SCFS_ERP].dbo.EXPORTSHIPPINGBILLMASTER a join [SCFS_ERP].dbo.SHIPPINGBILLDETAIL b on a.ESBMID = b.ESBMID 
	  where b.OLDSBDID > 0

	  Delete a 
	  From [SCFS_ERP].dbo.SHIPPINGBILLMASTER a join [SCFS_ERP].dbo.SHIPPINGBILLDETAIL B ON A.SBMID = B.SBMID 
	  where b.OLDSBDID > 0

	  Declare @SBMID int

      --DECLARE THE CURSOR FOR A QUERY.
      DECLARE SBMDetail CURSOR READ_ONLY
      FOR
	  
	  Select DISTINCT [SCFS].dbo.Z_EXPDIN_27092021.SBMID 
	  From [SCFS].dbo.Z_EXPDIN_27092021 (nolock) 
  
      --OPEN CURSOR.
      OPEN SBMDetail
 
      --FETCH THE RECORD INTO THE VARIABLES.
      FETCH NEXT FROM SBMDetail INTO @SBMID
 
      --LOOP UNTIL RECORDS ARE AVAILABLE.
      WHILE @@FETCH_STATUS = 0
      BEGIN

			EXEC Z_SHIPPINGBILLMASTER_DETAIL_INSERT_XML @SBMID
             --INCREMENT COUNTER.
			 
             SET @Counter = @Counter + 1
             
             --FETCH THE NEXT RECORD INTO THE VARIABLES.
             FETCH NEXT FROM SBMDetail INTO @SBMID
      END
 
      --CLOSE THE CURSOR.
      CLOSE SBMDetail
      DEALLOCATE SBMDetail


END


--SHIPPING BILL MASTER/DETAIL - DEtail Insert
USE [SCFS_ERP]
GO
/****** Object:  StoredProcedure [dbo].[Z_SHIPPINGBILLMASTER_DETAIL_INSERT_XML]    Script Date: 20/09/2021 19:37:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].Z_SHIPPINGBILLMASTER_DETAIL_INSERT_XML 
@PSBMID INT

AS
BEGIN
	  SET NOCOUNT ON
	
	  Declare @ccount int, @boecount int, @TSBMID INT , @TSBDID INT, @TESBMID INT, @Counter INT

	  Set @ccount = 1
	  Set @boecount = 0
	  SET @Counter = 1

	  --If @ccount > 0 

  			INSERT INTO [SCFS_ERP].[dbo].[SHIPPINGBILLMASTER]
			(
			 COMPYID, SBMDATE,SBMTIME,SBMNO,SBMDNO,EXPRTID,EXPRTNAME,CHAID,CHANAME,SBMRMKS,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE
			)
			Select COMPYID, SBMDATE,SBMTIME,SBMNO,SBMDNO,EXPRTID,EXPRTNAME,CHAID,CHANAME,SBMRMKS,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE
			From [SCFS].dbo.[SHIPPINGBILLMASTER] (nolock)
			Where [SCFS].dbo.[SHIPPINGBILLMASTER].SBMID = @PSBMID
			Group by COMPYID, SBMDATE,SBMTIME,SBMNO,SBMDNO,EXPRTID,EXPRTNAME,CHAID,CHANAME,SBMRMKS,CUSRID,LMUSRID,DISPSTATUS,PRCSDATE

     
			SET @TSBMID = SCOPE_IDENTITY()

  			INSERT INTO [SCFS_ERP].[dbo].SHIPPINGBILLDETAIL
			(
			  SBMID, GIDID, SBDDATE , SBDNO, SBDDNO, TRUCKNO, PRDTTID, PRDTGID , PRDTDESC, SBDNOP, SBDQTY, GDWNID, STAGID, CUSRID ,
			  LMUSRID, DISPSTATUS, PRCSDATE, SBTYPE, ESBMID,  UNLOADEDNOP, UNLOADEDQTY, OLDSBDID
			)
			Select	@TSBMID, GIDID, SBDDATE , SBDNO, SBDDNO, TRUCKNO, PRDTTID, PRDTGID , PRDTDESC, SBDNOP, SBDQTY, GDWNID, STAGID, 
					A.CUSRID , A.LMUSRID, A.DISPSTATUS, A.PRCSDATE, SBTYPE, ESBMID, SBDNOP, SBDQTY, SBDID
			From [SCFS].dbo.SHIPPINGBILLMASTER A(nolock) INNER JOIN SCFS.DBO.SHIPPINGBILLDETAIL B(NOLOCK) ON A.SBMID = B.SBMID
			WHERE A.SBMID = @PSBMID
			AND SBDID IN (SELECT SBDID FROM SCFS..Z_EXPDIN_27092021(NOLOCK) WHERE SBDID>0 AND SBMID = @PSBMID)

			
			--DECLARE THE CURSOR FOR A QUERY.
			DECLARE SBDDetail CURSOR READ_ONLY
			FOR
			Select DISTINCT XSB.SBDID
			FROM [SCFS].dbo.EXPORTSHIPPINGBILLMASTER X(NOLOCK) JOIN SCFS..SHIPPINGBILLDETAIL XSB(NOLOCK) ON X.ESBMID = XSB.ESBMID
			WHERE XSB.SBMID = @PSBMID
			AND SBDID IN (SELECT SBDID FROM SCFS..Z_EXPDIN_27092021(NOLOCK) WHERE SBDID>0 AND SBMID = @PSBMID)
  
			  --OPEN CURSOR.
			  OPEN SBDDetail
 
			  --FETCH THE RECORD INTO THE VARIABLES.
			  FETCH NEXT FROM SBDDetail INTO @TSBDID
 
			  --LOOP UNTIL RECORDS ARE AVAILABLE.
			  WHILE @@FETCH_STATUS = 0
			  BEGIN
			
					INSERT INTO [SCFS_ERP].[dbo].EXPORTSHIPPINGBILLMASTER
					(
					  COMPYID , ESBMDNO ,ESBMDATE , EXPRTID, EXPRTNAME, CHAID, CHANAME, ESBMREFNO, ESBMREFDATE, ESBMREFAMT, ESBMFOBAMT, ESBMDPNAME, PRDTGID, PRDTDESC, 
					  ESBMNOP , ESBMQTY, ESBMRMKS , ESBMITYPE, ESBMIDATE , CUSRID, LMUSRID, PRCSDATE, DISPSTATUS, ESBMNO, OLDESBMID
					)
					Select	DISTINCT COMPYID , ESBMDNO ,ESBMDATE , EXPRTID, EXPRTNAME, CHAID, CHANAME, ESBMREFNO, ESBMREFDATE, ESBMREFAMT, ESBMFOBAMT, ESBMDPNAME, A.PRDTGID, A.PRDTDESC, 
					  ESBMNOP , ESBMQTY, ESBMRMKS , ESBMITYPE, ESBMIDATE , A.CUSRID, A.LMUSRID, A.PRCSDATE, 0, 0, A.ESBMID
					From [SCFS].dbo.EXPORTSHIPPINGBILLMASTER A(nolock) INNER JOIN SCFS.DBO.SHIPPINGBILLDETAIL B(NOLOCK) ON A.ESBMID = B.ESBMID
					WHERE SBDID = @TSBDID
					
					--SET @TESBMID = SCOPE_IDENTITY()

					
					-- INSERT INTO [SCFS_ERP].[dbo].EXPORTSHIPPINGBILLDETAIL
					-- (
					--  ESBMID, ESBD_SBILLNO, ESBD_SBILLDATE , ESBOINVNO, ESBOINVDATE, ESBOINVAMT, ESBOINVFOBAMT, ESBDDPNAME, PRDTDESC, ESBMNOP, ESBMQTY, CUSRID, LMUSRID,
					--  PRCSDATE, DISPSTATUS 
					--)
					--SELECT		ESBMID, ESBMDNO, ESBMDATE , ESBMREFNO, ESBMREFDATE, ESBMREFAMT, ESBMFOBAMT, ESBMDPNAME, PRDTDESC, ESBMNOP, ESBMQTY, CUSRID, LMUSRID,
					--			PRCSDATE, DISPSTATUS 
					--FROM		[SCFS_ERP].[dbo].EXPORTSHIPPINGBILLMASTER (NOLOCK)
					--WHERE		ESBMID = @TSBMID

					 --INCREMENT COUNTER.
			 
					 SET @Counter = @Counter + 1
             
					 --FETCH THE NEXT RECORD INTO THE VARIABLES.
					 FETCH NEXT FROM SBDDetail INTO @TSBDID
			  END
 
			  --CLOSE THE CURSOR.
			  CLOSE SBDDetail
			  DEALLOCATE SBDDetail

			
END


-- STUFFING DETAILS

USE [SCFS_ERP]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--STF Cursor
ALTER PROCEDURE [dbo].[Z_EXPORT_STUFFING_MASTERDETAIL_Auto_Generate_XML]
AS
BEGIN
	SET NOCOUNT ON
	
      DECLARE @Counter INT
      SET @Counter = 1
      
	  Delete A
	  From STUFFINGMASTER A JOIN STUFFINGDETAIL B ON A.STFMID = B.STFMID
	  WHERE OLDSTFDID > 0 

	  
	  Declare @STFDID int
	  

      --DECLARE THE CURSOR FOR A QUERY.
      DECLARE STFDetail CURSOR READ_ONLY
      FOR
	  
	  Select DISTINCT B.STFDID 
	  From [SCFS].dbo.Z_EXPDIN_27092021 B (NOLOCK)
	  WHERE B.STFDID > 0
  
      --OPEN CURSOR.
      OPEN STFDetail
 
      --FETCH THE RECORD INTO THE VARIABLES.
      FETCH NEXT FROM STFDetail INTO @STFDID
 
      --LOOP UNTIL RECORDS ARE AVAILABLE.
      WHILE @@FETCH_STATUS = 0
      BEGIN

			EXEC Z_EXPORT_STUFFING_MASTERDETAIL_INSERT_XML @STFDID
             --INCREMENT COUNTER.
			 
             SET @Counter = @Counter + 1
             
             --FETCH THE NEXT RECORD INTO THE VARIABLES.
             FETCH NEXT FROM STFDetail INTO @STFDID
      END
 
      --CLOSE THE CURSOR.
      CLOSE STFDetail
      DEALLOCATE STFDetail


END

USE [SCFS_ERP]
GO
ALTER PROCEDURE [dbo].[Z_EXPORT_STUFFING_MASTERDETAIL_INSERT_XML] 
@STFDID INT
AS
BEGIN
	  SET NOCOUNT ON
	
	  Declare @ccount int, @boecount int, @STFMID INT, @TSTFDID INT

	  Set @ccount = 1
	  Set @boecount = 0

	  INSERT INTO [SCFS_ERP].[dbo].STUFFINGMASTER
			(
			 COMPYID, STFMDATE, STFMTIME, STFMNO , STFMDNO, CHAID, STFMNAME, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, STFTID, LCATEID, LCATENAME, TGID, EOPTID, STFBILLEDTO, 
			 STFBILLREFID, STFBILLREFNAME, STFCATEAID
			)
			Select	COMPYID, STFMDATE, STFMTIME, STFMNO , STFMDNO, CHAID, STFMNAME, A.CUSRID, A.LMUSRID, A.DISPSTATUS, A.PRCSDATE, STFTID, LCATEID, LCATENAME, TGID, EOPTID, 
					STFBILLEDTO, STFBILLREFID, STFBILLREFNAME, STFCATEAID
			From [SCFS].dbo.STUFFINGMASTER A(NOLOCK) inner join [SCFS].dbo.STUFFINGDETAIL b(NOLOCK)
					ON a.STFMID = b.STFMID					
			  Where b.STFDID = @STFDID
			  Group by  COMPYID, STFMDATE, STFMTIME, STFMNO , STFMDNO, CHAID, STFMNAME, A.CUSRID, A.LMUSRID, A.DISPSTATUS, A.PRCSDATE, STFTID, LCATEID, LCATENAME, TGID, EOPTID, 
					STFBILLEDTO, STFBILLREFID, STFBILLREFNAME, STFCATEAID

			SET @STFMID = SCOPE_IDENTITY()
			-- SELECT TOP 5 * FROM STUFFINGDETAIL
			INSERT INTO [SCFS_ERP].[dbo].STUFFINGDETAIL
			(
			  STFMID, GIDID , CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, STFTYPE, OLDSTFDID
			)
			Select	@STFMID, A.GIDID , A.CUSRID, A.LMUSRID, A.DISPSTATUS, A.PRCSDATE, STFTYPE, a.STFDID
			From [SCFS].dbo.STUFFINGDETAIL A(NOLOCK) 
			  Where A.STFDID = @STFDID
			  Group by  A.GIDID , A.CUSRID, A.LMUSRID, A.DISPSTATUS, A.PRCSDATE, STFTYPE, a.STFDID

			SET @TSTFDID = SCOPE_IDENTITY()
			-- SELECT TOP 5 * FROM STUFFINGPRODUCTDETAIL
			INSERT INTO [SCFS_ERP].[dbo].STUFFINGPRODUCTDETAIL
			(
			  STFDID, SBDID, STFDSBNO, STFDSBDNO, STFDSBDATE, STFDSBDDATE, STFDNOP, STFDQTY, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, 
			  STFCORDNO
			)
			Select	@TSTFDID, A.SBDID, STFDSBNO, STFDSBDNO, STFDSBDATE, STFDSBDDATE, STFDNOP, STFDQTY, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, 
			  STFCORDNO
			From [SCFS].dbo.STUFFINGPRODUCTDETAIL A(NOLOCK) 
			  Where A.STFDID = @STFDID
			  Group by  A.SBDID, STFDSBNO, STFDSBDNO, STFDSBDATE, STFDSBDDATE, STFDNOP, STFDQTY, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, 
			  STFCORDNO

END



-- ASL DETAILS

USE [SCFS_ERP]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--ASL Cursor
CREATE PROCEDURE [dbo].[Z_EXPORT_ASL_DETAIL_Auto_Generate_XML]
AS
BEGIN
	SET NOCOUNT ON
	
      DECLARE @Counter INT
      SET @Counter = 1
      
	  Delete A
	  From AUTHORIZATIONSLIPMASTER A JOIN AUTHORIZATIONSLIPDETAIL B ON A.ASLMID = B.ASLMID 
	  WHERE OLDASLDID > 0 AND SDPTID = 2

	  --Delete From AUTHORIZATIONSLIPDETAIL WHERE OLDASLDID > 0 AND SDPTID = 2

	  Declare @ASLDID int
	  
	  --DBCC CHECKIDENT ('AUTHORIZATIONSLIPMASTER', RESEED,1236)
	  --DBCC CHECKIDENT ('AUTHORIZATIONSLIPDETAIL', RESEED,1236)


      --DECLARE THE CURSOR FOR A QUERY.
      DECLARE ASLDetail CURSOR READ_ONLY
      FOR
	  
	  Select DISTINCT ASLDID 
	  From [SCFS].dbo.Z_EXPDIN_27092021 B (NOLOCK)
	  WHERE B.ASLDID > 0
      --OPEN CURSOR.
      OPEN ASLDetail
 
      --FETCH THE RECORD INTO THE VARIABLES.
      FETCH NEXT FROM ASLDetail INTO @ASLDID
 
      --LOOP UNTIL RECORDS ARE AVAILABLE.
      WHILE @@FETCH_STATUS = 0
      BEGIN

			EXEC Z_EXPORT_ASL_DETAIL_INSERT_XML @ASLDID
             --INCREMENT COUNTER.
			 
             SET @Counter = @Counter + 1
             
             --FETCH THE NEXT RECORD INTO THE VARIABLES.
             FETCH NEXT FROM ASLDetail INTO @ASLDID
      END
 
      --CLOSE THE CURSOR.
      CLOSE ASLDetail
      DEALLOCATE ASLDetail


END

USE [SCFS_ERP]
GO
ALTER  PROCEDURE [dbo].[Z_EXPORT_ASL_DETAIL_INSERT_XML] 
@ASLDID INT
AS
BEGIN
	  SET NOCOUNT ON
	
	  Declare @ccount int, @boecount int, @ASLMID INT

		Set @ccount = 1
		Set @boecount = 0

		INSERT INTO [SCFS_ERP].[dbo].AUTHORIZATIONSLIPMASTER
		(
		COMPYID, SDPTID, ASLMDATE, ASLMTIME, ASLMNO, ASLMDNO, ASLMTYPE, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE ,
		NGIDID , NGINO
		)

		Select	A.COMPYID, A.SDPTID, A.ASLMDATE, A.ASLMTIME, A.ASLMNO, A.ASLMDNO, A.ASLMTYPE, A.CUSRID, A.LMUSRID, 
				A.DISPSTATUS, A.PRCSDATE , A.NGIDID , A.NGINO
		From [SCFS].dbo.AUTHORIZATIONSLIPMASTER A(NOLOCK) inner join [SCFS].dbo.AUTHORIZATIONSLIPDETAIL b(NOLOCK)
				ON a.ASLMID = b.ASLMID
		Where b.ASLDID =  @ASLDID
		AND SDPTID = 2
		Group by  A.COMPYID, A.SDPTID, A.ASLMDATE, A.ASLMTIME, A.ASLMNO, A.ASLMDNO, A.ASLMTYPE, A.CUSRID, A.LMUSRID, 
					A.DISPSTATUS, A.PRCSDATE , A.NGIDID , A.NGINO
					
		SET @ASLMID = SCOPE_IDENTITY()
		-- SELECT TOP 5 * FROM AUTHORIZATIONSLIPDETAIL
		INSERT INTO [SCFS_ERP].[dbo].AUTHORIZATIONSLIPDETAIL
		(
			ASLMID, OSDID, GIDID, LCATEID, ASLDTYPE, ASLLTYPE, ASLOTYPE, VHLNO, DRVNAME, DISPSTATUS, PRCSDATE, ASLFDESC, ASLTDESC,
			ASLDODATE, STFDID, CSEALNO, ASEALNO, SLTID, OLDASLDID
		)
		Select	@ASLMID, a.OSDID, b.GIDID, a.LCATEID, a.ASLDTYPE, a.ASLLTYPE, a.ASLOTYPE, a.VHLNO, a.DRVNAME, a.DISPSTATUS, a.PRCSDATE,
				a.ASLFDESC, a.ASLTDESC, a.ASLDODATE, a.STFDID, a.CSEALNO, a.ASEALNO, 0, a.ASLDID
		From [SCFS].dbo.AUTHORIZATIONSLIPDETAIL A(NOLOCK) join SCFS.dbo.STUFFINGDETAIL b(nolock) on a.STFDID = b.STFDID
		Where A.ASLDID = @ASLDID
		Group by	 a.OSDID, b.GIDID, A.LCATEID, A.ASLDTYPE, A.ASLLTYPE, A.ASLOTYPE, A.VHLNO, A.DRVNAME, A.DISPSTATUS, 
				A.PRCSDATE, A.ASLFDESC, A.ASLTDESC, A.ASLDODATE, A.STFDID, A.CSEALNO, A.ASEALNO,  a.ASLDID
END
/*
SELECT * FROM GATEINDETAIL WHERE OLDGID > 0
and STMRID NOT IN (SELECT CATEID FROM CATEGORYMASTER WHERE CATETID = 3)


SELECT * FROM GATEINDETAIL WHERE OLDGID > 0
and IMPRTID NOT IN (SELECT CATEID FROM CATEGORYMASTER WHERE CATETID = 4)


SELECT * FROM GATEINDETAIL WHERE OLDGID > 0
and lcateid NOT IN (SELECT CATEID FROM CATEGORYMASTER WHERE CATETID = 6)
*/


--VT DETAILS

USE [SCFS_ERP]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--VT Cursor
CREATE PROCEDURE [dbo].[Z_EXPORT_VT_DETAIL_Auto_Generate_XML]
AS
BEGIN
	SET NOCOUNT ON
	
      DECLARE @Counter INT
      SET @Counter = 1
      
	  Delete  VEHICLETICKETDETAIL 
	  WHERE OLDVTDID > 0 AND SDPTID = 2

	  Declare @VTDID int
	  
	  --DBCC CHECKIDENT ('VEHICLETICKETDETAIL', RESEED,1)


      --DECLARE THE CURSOR FOR A QUERY.
      DECLARE VTDetail CURSOR READ_ONLY
      FOR
	  
	  Select DISTINCT VTDID 
	  From  [SCFS].dbo.Z_EXPDIN_27092021 B (NOLOCK)
	  WHERE B.VTDID > 0
	  Group by  VTDID
	  Order by  VTDID
  
      --OPEN CURSOR.
      OPEN VTDetail
 
      --FETCH THE RECORD INTO THE VARIABLES.
      FETCH NEXT FROM VTDetail INTO @VTDID
 
      --LOOP UNTIL RECORDS ARE AVAILABLE.
      WHILE @@FETCH_STATUS = 0
      BEGIN

			EXEC Z_EXPORT_VT_DETAIL_INSERT_XML @VTDID
             --INCREMENT COUNTER.
			 
             SET @Counter = @Counter + 1
             
             --FETCH THE NEXT RECORD INTO THE VARIABLES.
             FETCH NEXT FROM VTDetail INTO @VTDID
      END
 
      --CLOSE THE CURSOR.
      CLOSE VTDetail
      DEALLOCATE VTDetail


END

USE [SCFS_ERP]
GO
CREATE PROCEDURE [dbo].[Z_EXPORT_VT_DETAIL_INSERT_XML] 
@VTDID INT
AS
BEGIN
	  SET NOCOUNT ON
	
	  Declare @ccount int, @boecount int

	  Set @ccount = 1
	  Set @boecount = 0

	  If @ccount > 0 
			-- SELECT TOP 5 * FROM VEHICLETICKETDETAIL
		
			INSERT INTO [SCFS_ERP].[dbo].VEHICLETICKETDETAIL
			(
			  COMPYID, SDPTID, VTDATE, VTTIME, VTNO, VTDNO, ASLDID, VHLNO, DRVNAME, VTDESC, VTQTY, VTTYPE, VTSTYPE, VTREMRKS, 
			  GIDID, EGIDID , CUSRID,  LMUSRID, DISPSTATUS, PRCSDATE, VTSSEALNO, VTCTYPE, CGIDID, STFDID, EVLDATE, EVSDATE,
			  ELRDATE, TRNSPRTID, TRNSPRTNAME, GTRNSPRTNAME, VHLMID, OLDVTDID
			)
			Select	A.COMPYID, A.SDPTID, A.VTDATE, A.VTTIME, A.VTNO, A.VTDNO, A.ASLDID, A.VHLNO, A.DRVNAME, A.VTDESC, 
					A.VTQTY, A.VTTYPE, A.VTSTYPE, A.VTREMRKS, A.GIDID, A.EGIDID , A.CUSRID,  A.LMUSRID, A.DISPSTATUS, 
					A.PRCSDATE, A.VTSSEALNO, A.VTCTYPE, A.CGIDID, A.STFDID, A.EVLDATE, A.EVSDATE, A.ELRDATE, 0, 
					'', '', 0, A.VTDID
			From [SCFS].dbo.VEHICLETICKETDETAIL A(NOLOCK) INNER JOIN
					[SCFS].dbo.Z_EXPDIN_27092021 b(nolock) ON a.VTDID = b.VTDID
			  Where B.VTDID = @VTDID
			  Group by  A.COMPYID, A.SDPTID, A.VTDATE, A.VTTIME, A.VTNO, A.VTDNO, A.ASLDID, A.VHLNO, A.DRVNAME, A.VTDESC, 
					A.VTQTY, A.VTTYPE, A.VTSTYPE, A.VTREMRKS, A.GIDID, A.EGIDID , A.CUSRID,  A.LMUSRID, A.DISPSTATUS, 
					A.PRCSDATE, A.VTSSEALNO, A.VTCTYPE, A.CGIDID, A.STFDID, A.EVLDATE, A.EVSDATE, A.ELRDATE, A.VTDID

			
END

/*
*/

--GO DETAILS

USE [SCFS_ERP]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--GO Cursor
CREATE  PROCEDURE [dbo].[Z_EXPORT_GO_DETAIL_Auto_Generate_XML]
AS
BEGIN
	SET NOCOUNT ON
	
      DECLARE @Counter INT
      SET @Counter = 1
      
	  Delete  GATEOUTDETAIL 
	  WHERE OLDGODID > 0 AND SDPTID = 2

	  Declare @GODID int
	  
	  --DBCC CHECKIDENT ('GATEOUTDETAIL', RESEED,1)


      --DECLARE THE CURSOR FOR A QUERY.
      DECLARE GODetail CURSOR READ_ONLY
      FOR
	  
	  Select DISTINCT GODID 
	  From  [SCFS].dbo.Z_EXPDIN_27092021 B (NOLOCK)
	  WHERE B.GODID > 0
  
      --OPEN CURSOR.
      OPEN GODetail
 
      --FETCH THE RECORD INTO THE VARIABLES.
      FETCH NEXT FROM GODetail INTO @GODID
 
      --LOOP UNTIL RECORDS ARE AVAILABLE.
      WHILE @@FETCH_STATUS = 0
      BEGIN

			EXEC Z_EXPORT_GO_DETAIL_INSERT_XML @GODID
             --INCREMENT COUNTER.
			 
             SET @Counter = @Counter + 1
             
             --FETCH THE NEXT RECORD INTO THE VARIABLES.
             FETCH NEXT FROM GODetail INTO @GODID
      END
 
      --CLOSE THE CURSOR.
      CLOSE GODetail
      DEALLOCATE GODetail


END

USE [SCFS_ERP]
GO
-- GO
CREATE PROCEDURE [dbo].[Z_EXPORT_GO_DETAIL_INSERT_XML] 
@GODID INT
AS
BEGIN
	  SET NOCOUNT ON
	
	  Declare @ccount int, @boecount int

	  Set @ccount = 1
	  Set @boecount = 0

	  If @ccount > 0 
			-- SELECT TOP 5 * FROM GATEOUTDETAIL
		
			INSERT INTO [SCFS_ERP].[dbo].GATEOUTDETAIL
			(
			  COMPYID, SDPTID, REGSTRID, GODATE, GOTIME, GONO, GODNO, GIDID, TRANDID, VHLNO, GDRVNAME, CHASNAME, GOBTYPE, 
			  CHAID, LSEALNO, SSEALNO, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, GOQTY, OTDID, OTDNO, CONTNRFID, BOOKID, 
			  GOPLCNAME, GOBKGNO, GOEGMNO, OVSLID, OVSLNAME, OVOYNO, GOREMRKS, EHIDATE, EHITIME, GOTRNSPRTNAME, GOTTYPE, 
			  GOOTYPE, GOCTYPE, EBLNO, ESSBLNO, ESSBLDT, ESPORT, ESTOPLACE, ESINVNO, ESINVDT, OLDGODID
			)
			Select	A.COMPYID, A.SDPTID, A.REGSTRID, A.GODATE, A.GOTIME, A.GONO, A.GODNO, A.GIDID, A.TRANDID, A.VHLNO, A.GDRVNAME, 
					A.CHASNAME, A.GOBTYPE, A.CHAID, A.LSEALNO, A.SSEALNO, A.CUSRID, A.LMUSRID, A.DISPSTATUS, A.PRCSDATE, 
					A.GOQTY, A.OTDID, A.OTDNO, A.CONTNRFID, A.BOOKID, A.GOPLCNAME, A.GOBKGNO, A.GOEGMNO, A.OVSLID, A.OVSLNAME, 
					A.OVOYNO, A.GOREMRKS, A.EHIDATE, A.EHITIME, A.GOTRNSPRTNAME, A.GOTTYPE, A.GOOTYPE, A.GOCTYPE, A.EBLNO, 
					'', NULL, NULL, NULL, NULL, NULL, A.GODID
			From [SCFS].dbo.GATEOUTDETAIL A(NOLOCK) INNER JOIN
					[SCFS].dbo.Z_EXPDIN_27092021 b(nolock) ON a.GODID = b.GODID
			  Where B.GODID = @GODID
			  Group by  A.COMPYID, A.SDPTID, A.REGSTRID, A.GODATE, A.GOTIME, A.GONO, A.GODNO, A.GIDID, A.TRANDID, A.VHLNO, A.GDRVNAME, 
					A.CHASNAME, A.GOBTYPE, A.CHAID, A.LSEALNO, A.SSEALNO, A.CUSRID, A.LMUSRID, A.DISPSTATUS, A.PRCSDATE, 
					A.GOQTY, A.OTDID, A.OTDNO, A.CONTNRFID, A.BOOKID, A.GOPLCNAME, A.GOBKGNO, A.GOEGMNO, A.OVSLID, A.OVSLNAME, 
					A.OVOYNO, A.GOREMRKS, A.EHIDATE, A.EHITIME, A.GOTRNSPRTNAME, A.GOTTYPE, A.GOOTYPE, A.GOCTYPE, A.EBLNO, A.GODID

			
END


/*


*/