

--SELECT a.OLDGID, SDPTID, count('*') FROM SCFS_ERP.DBO.GATEINDETAIL a(nolock) 
--WHERE SDPTID = 2 AND OLDGID > 0
--and OLDGID in ( select GIDID from scfs.dbo.Z_EXPDIN_27092021 b (nolock) )
--group by a.OLDGID, SDPTID
--having count('*')> 1

--Select COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GIVHLTYPE, TRNSPRTID, TRNSPRTNAME, VHLNO, 
--			DRVNAME, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, CONTNRID, CONTNRSID, 
--			[SCFS].dbo.GATEINDETAIL.CONTNRNO, LPSEALNO, CSEALNO, YRDID, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, 
--			[SCFS].dbo.GATEINDETAIL.IGMNO, [SCFS].dbo.GATEINDETAIL.GPLNO, GPWTYPE, GPSTYPE, GPETYPE, BOEDID, INVDID, RGIDID, 
--			GIREMKRS, SLOTID, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, GPEAMT, CHAID, CHANAME, AVHLNO, GPNOP, PRDTTID, GIISOCODE, 
--			GIDMGDESC, NGIDID, GPNWGHT, GPGWGHT, GPCBM, GPLENGTH, GPWIDTH, GPHEIGHT, GPBLNO, GPAAMT, CLNTID, CLNTNAME, SHPRNAME, 
--			GPPLCNAME, GPTWGHT, CONTNRFID, CONDTNID, GRADEID, CNTNRSID, GPPTYPE, CASE WHEN GFCLTYPE = 0 THEN 1 ELSE 0 END, GSEALTYPE, GSECTYPE, GSEALREMKRS, 
--			GSECREMKRS, GPNRNO, ESBNO, EVSLRNO, EMONO, EEGMNO, ESBDATE, GPSCNTYPE, IGMDATE, BLNO, GPMODEID, GATEINDETAIL.GIDID
--			From [SCFS].dbo.GATEINDETAIL (NOLOCK) 
--			where [SCFS].dbo.GATEINDETAIL.GIDID = 1555981
--			group by COMPYID, SDPTID, GIDATE, GITIME, GICCTLDATE, GICCTLTIME, GINO, GIDNO, GIVHLTYPE, TRNSPRTID, TRNSPRTNAME, VHLNO, 
--			DRVNAME, GPREFNO, IMPRTID, IMPRTNAME, STMRID, STMRNAME, CONTNRTID, CONTNRID, CONTNRSID, 
--			[SCFS].dbo.GATEINDETAIL.CONTNRNO, LPSEALNO, CSEALNO, YRDID, VSLID, VSLNAME, VOYNO, PRDTGID, PRDTDESC, UNITID, GPWGHT, 
--			[SCFS].dbo.GATEINDETAIL.IGMNO, [SCFS].dbo.GATEINDETAIL.GPLNO, GPWTYPE, GPSTYPE, GPETYPE, BOEDID, INVDID, RGIDID, 
--			GIREMKRS, SLOTID, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, GPEAMT, CHAID, CHANAME, AVHLNO, GPNOP, PRDTTID, GIISOCODE, 
--			GIDMGDESC, NGIDID, GPNWGHT, GPGWGHT, GPCBM, GPLENGTH, GPWIDTH, GPHEIGHT, GPBLNO, GPAAMT, CLNTID, CLNTNAME, SHPRNAME, 
--			GPPLCNAME, GPTWGHT, CONTNRFID, CONDTNID, GRADEID, CNTNRSID, GPPTYPE, CASE WHEN GFCLTYPE = 0 THEN 1 ELSE 0 END, GSEALTYPE, GSECTYPE, GSEALREMKRS, 
--			GSECREMKRS, GPNRNO, ESBNO, EVSLRNO, EMONO, EEGMNO, ESBDATE, GPSCNTYPE, IGMDATE, BLNO, GPMODEID, GATEINDETAIL.GIDID


--SELECT 'SB',COUNT('*') FROM SCFS_ERP.DBO.SHIPPINGBILLDETAIL WHERE OLDSBDID > 0
--SELECT 'STF',COUNT('*') FROM SCFS_ERP.DBO.STUFFINGDETAIL WHERE OLDSTFDID > 0
--SELECT 'ASL',COUNT('*') FROM SCFS_ERP.DBO.AUTHORIZATIONSLIPMASTER A (NOLOCK) , SCFS_ERP.DBO.AUTHORIZATIONSLIPDETAIL B(NOLOCK)
--WHERE SDPTID = 2 AND B.OLDASLDID > 0 
--AND A.ASLMID = B.ASLMID
--SELECT 'VT', COUNT('*') FROM SCFS_ERP.DBO.VEHICLETICKETDETAIL WHERE SDPTID = 2
--SELECT 'GO', COUNT('*') FROM SCFS_ERP.DBO.GATEOUTDETAIL WHERE SDPTID = 2


	--update A
	--		set CHAID = CATEID
	--		FROM SCFS_ERP.DBO.GATEINDETAIL A JOIN CATEGORYMASTER B(NOLOCK) ON A.CHANAME = B.CATENAME 
	--		where ISNULL(CHAID,0)= 0
	--		AND B.CATETID = 4

			
	--update A
	--		set STMRID = CATEID
	--		FROM SCFS_ERP.DBO.GATEINDETAIL A JOIN CATEGORYMASTER B(NOLOCK) ON A.STMRNAME = B.CATENAME 
	--		where ISNULL(STMRID,0)= 0
	--		AND B.CATETID = 4


SELECT 'GI',COUNT('*') FROM SCFS_ERP.DBO.GATEINDETAIL  WHERE SDPTID = 2 AND OLDGID > 0
SELECT 'SB',COUNT('*') FROM SCFS_ERP.DBO.SHIPPINGBILLDETAIL WHERE OLDSBDID > 0
SELECT 'STF',COUNT('*') FROM SCFS_ERP.DBO.STUFFINGDETAIL WHERE OLDSTFDID > 0
SELECT 'ESB',COUNT('*') FROM SCFS_ERP.DBO.EXPORTSHIPPINGBILLMASTER WHERE OLDESBMID > 0
SELECT 'ESB',COUNT('*') FROM SCFS_ERP.DBO.EXPORTSHIPPINGBILLDETAIL 

 --SELECT * fROM SCFS..GATEINDETAIL WHERE GIDNO = 8280 AND AVHLNO LIKE 'TN39CK6250XZ'

SELECT 'ASL',COUNT('*') FROM SCFS_ERP.DBO.AUTHORIZATIONSLIPMASTER A (NOLOCK) , SCFS_ERP.DBO.AUTHORIZATIONSLIPDETAIL B(NOLOCK)
WHERE SDPTID = 2 AND B.OLDASLDID > 0 
AND A.ASLMID = B.ASLMID

SELECT 'VT', COUNT('*') FROM SCFS_ERP.DBO.VEHICLETICKETDETAIL WHERE SDPTID = 2
SELECT 'GO', COUNT('*') FROM SCFS_ERP.DBO.GATEOUTDETAIL WHERE SDPTID = 2


