SELECT * INTO STUFFINGDETAILBKUP271021 FROM STUFFINGDETAIL
SELECT * INTO STUFFINGMASTERBKUP271021 FROM STUFFINGMASTER
select a.stfmid from STUFFINGMASTER a left join STUFFINGDETAIL b (nolock) on a.stfmid = b.stfmid
where b.stfmid is null
DROP TABLE VTGOIssueStuffing_261021_1015
SELECT a.STFDID , min(C.stfmid) 'minstfmid', count(C.stfmid) 'cnt', max(case when compyid = 32 then C.stfmid else 0 end) 'cymaxstfmid',
 max(case when compyid < 32 then C.stfmid else 0 end) 'pymaxstfmid' , MAX(TRANMID)  TRANMID, max(OLDASLDID) 'OLDASLDID'
into VTGOIssueStuffing_261021_1015
FROM   AUTHORIZATIONSLIPDETAIL a JOIN AUTHORIZATIONSLIPMASTER b ON a.ASLMID = b.ASLMID
	join scfs.dbo.STUFFINGDETAIL c on a.STFDID = c.STFDID 
	LEFT JOIN scfs.dbo.TRANSACTIONDETAIL (NOLOCK)D ON C.STFDID = D.STFDID
WHERE a.STFDID NOT IN (SELECT STFDID  FROM STUFFINGDETAIL)
AND a.STFDID NOT IN (SELECT STFDID  FROM TRANSACTIONDETAIL)
--AND STFDID NOT IN (SELECT STFDID  FROM STUFFINGMASTER)
AND SDPTID =2 
and OLDASLDID > 0
GROUP BY A.STFDID
HAVING MAX(TRANMID) IS NULL

select max (stfdid) from VTGOIssueStuffing_261021_1015 where OLDASLDID >0
BEGIN TRAN
-- STUFFINGLMASTER-DETAIL 
--EXEC [Z_EXPORT_STUFFING_MASTERDETAIL_Auto_Generate_XML]
exec [Z_EXPORT_VTGO_Issues_STUFFING_MASTERDETAIL_Auto_Generate_XML]
GO
ROLLBACK TRAN

COMMIT
	update a
	SET GIDID = B.GIDID
	from [SCFS_ERP].dbo.STUFFINGDETAIL a, SCFS_ERP.DBO.GATEINDETAIL B(NOLOCK), VTGOIssueStuffing_261021_1015 c(nolock)
	WHERE A.GIDID = B.OLDGID
	and a.OLDSTFDID = c.STFDID
	and a.OLDSTFDID > 0 
	and b.OLDGID > 0 
	and a.CUSRID = '99'

	update b
	SET STFDID = a.STFDID
	from [SCFS_ERP].dbo.STUFFINGDETAIL a, SCFS_ERP.DBO.AUTHORIZATIONSLIPDETAIL B(NOLOCK), VTGOIssueStuffing_261021_1015 c(nolock)
	WHERE a.OLDSTFDID = B.STFDID
	and a.OLDSTFDID = c.STFDID
	and a.OLDSTFDID > 0 
	and b.OLDASLDID > 0 
	and a.CUSRID = '99'


	--update D
	--SET stfmid = a.STFMID
	SELECT A.STFDID, A.STFMID, C.STFDID, A.GIDID, A.OLDSTFDID, D.STFMID
	from [SCFS_ERP].dbo.STUFFINGDETAIL a  JOIN SCFS_ERP.dbo.STUFFINGMASTER d(nolock) ON a.STFMID=d.STFMID, VTGOIssueStuffing_261021_1015 c(nolock)
	WHERE a.OLDSTFDID =c.STFDID	
	and a.OLDSTFDID > 0 
	--AND D.STFMID IS NULL
	ORDER BY OLDSTFDID
	SELECT * FROM STUFFINGMASTER 
--Update CHA Adress Detaila
UPDATE STUFFINGMASTER SET CATEAGSTNO = SCFS_ERP.dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO,
TRANIMPADDR1 = CATEAADDR1, TRANIMPADDR2 = CATEAADDR2, TRANIMPADDR3 = CATEAADDR3, TRANIMPADDR4 = CATEAADDR4,
STATEID = dbo.CATEGORY_ADDRESS_DETAIL.STATEID
FROM SCFS_ERP.DBO.STUFFINGMASTER INNER JOIN
				   SCFS_ERP.dbo.CATEGORY_ADDRESS_DETAIL ON 
				   DBO.STUFFINGMASTER.CHAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID and
				   dbo.STUFFINGMASTER.STFCATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID
where 
isnull(SCFS_ERP.DBO.STUFFINGMASTER.CATEAGSTNO ,'') ='' or isnull(TRANIMPADDR1,'') = ''

--Update Billing CHA Adress Detaila

UPDATE STUFFINGMASTER SET STFBCHAGSTNO = SCFS_ERP.dbo.CATEGORY_ADDRESS_DETAIL.CATEAGSTNO,
STFBCHAADDR1 = CATEAADDR1, STFBCHAADDR2 = CATEAADDR2, STFBCHAADDR3 = CATEAADDR3, STFBCHAADDR4 = CATEAADDR4,
STFBCHASTATEID = dbo.CATEGORY_ADDRESS_DETAIL.STATEID
FROM SCFS_ERP.DBO.STUFFINGMASTER INNER JOIN
				   SCFS_ERP.dbo.CATEGORY_ADDRESS_DETAIL ON 
				   DBO.STUFFINGMASTER.STFBILLREFID = dbo.CATEGORY_ADDRESS_DETAIL.CATEID and
				   dbo.STUFFINGMASTER.STFBCATEAID = dbo.CATEGORY_ADDRESS_DETAIL.CATEAID
where isnull(SCFS_ERP.DBO.STUFFINGMASTER.STFBCHAGSTNO ,'') ='' or isnull(TRANIMPADDR1,'') = ''

