alter PROCEDURE [dbo].[Z_EXPORT_STUFFING_MSTDTL_INSERT_XML] 
@STFDID INT,
@OSTFMID INT,
@PRVSTFMID INT,
@PRVSTFDID INT
AS
BEGIN
	  SET NOCOUNT ON
	
	  Declare @ccount int, @boecount int, @NSTFMID INT, @TSTFDID INT, @tchkstfmid int

	  Set @ccount = 1
	  Set @boecount = 0

	  IF @PRVSTFMID <> @OSTFMID OR @PRVSTFDID = 0
	  BEGIN
		--SET @tchkstfmid = 0
		--select @tchkstfmid = isnull(max(a.STFMID),0)
		--From [SCFS_ERP].dbo.STUFFINGMASTER A(NOLOCK) inner join [SCFS_ERP].dbo.STUFFINGDETAIL b(NOLOCK)
		--			ON a.STFMID = b.STFMID					
		--	  Where b.OLDSTFDID = @PRVSTFDID
		--if ISNULL(@tchkstfmid,0) > 0 
		--BEGIN
		--	set @NSTFMID = @tchkstfmid
		--	SELECT 'USING NEW-OLD STFMID MASTER'  + CAST(@NSTFMID AS VARCHAR(20))
		--END
		--else
		--begin
		
			INSERT INTO [SCFS_ERP].[dbo].STUFFINGMASTER
				(
				 COMPYID, STFMDATE, STFMTIME, STFMNO , STFMDNO, CHAID, STFMNAME, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, STFTID, LCATEID, LCATENAME, TGID, EOPTID, STFBILLEDTO, 
				 STFBILLREFID, STFBILLREFNAME, STFCATEAID
				)
				Select	COMPYID, STFMDATE, STFMTIME, STFMNO , STFMDNO, CHAID, STFMNAME, '99', A.LMUSRID, A.DISPSTATUS, A.PRCSDATE, STFTID, LCATEID, LCATENAME, TGID, EOPTID, 
						STFBILLEDTO, STFBILLREFID, STFBILLREFNAME, STFCATEAID
				From [SCFS].dbo.STUFFINGMASTER A(NOLOCK) inner join [SCFS].dbo.STUFFINGDETAIL b(NOLOCK)
						ON a.STFMID = b.STFMID					
				  Where b.STFDID = @STFDID
				  AND A.STFMID = @OSTFMID
				  Group by  COMPYID, STFMDATE, STFMTIME, STFMNO , STFMDNO, CHAID, STFMNAME, A.CUSRID, A.LMUSRID, A.DISPSTATUS, A.PRCSDATE, STFTID, LCATEID, LCATENAME, TGID, EOPTID, 
						STFBILLEDTO, STFBILLREFID, STFBILLREFNAME, STFCATEAID

				SET @NSTFMID = SCOPE_IDENTITY()

				SELECT 'INSERTING MASTER'  + CAST(@NSTFMID AS VARCHAR(20))
		--end
	END
	ELSE
	BEGIN
		SELECT @NSTFMID = MAX(B.STFMID)
		From [SCFS_ERP].dbo.STUFFINGMASTER A(NOLOCK) inner join [SCFS_ERP].dbo.STUFFINGDETAIL b(NOLOCK)	ON A.STFMID = B.STFMID
		Where b.OLDSTFDID = @PRVSTFDID
		SELECT 'USING PREVIOUS ID'  + CAST(@NSTFMID AS VARCHAR(20))
	END
			-- SELECT TOP 5 * FROM STUFFINGDETAIL
			INSERT INTO [SCFS_ERP].[dbo].STUFFINGDETAIL
			(
			  STFMID, GIDID , CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, STFTYPE, OLDSTFDID
			)
			Select	@NSTFMID, A.GIDID , '99', A.LMUSRID, A.DISPSTATUS, A.PRCSDATE, STFTYPE, a.STFDID
			From [SCFS].dbo.STUFFINGDETAIL A(NOLOCK) 
			  Where 
			  A.STFDID = @STFDID
			  Group by  A.GIDID , A.CUSRID, A.LMUSRID, A.DISPSTATUS, A.PRCSDATE, STFTYPE, a.STFDID

			SET @TSTFDID = SCOPE_IDENTITY()

			--SELECT @TSTFDID 'STFDID', @NSTFMID 'NSTFMID', @PRVSTFMID 'PSTFMID'

			-- SELECT TOP 5 * FROM STUFFINGPRODUCTDETAIL
			INSERT INTO [SCFS_ERP].[dbo].STUFFINGPRODUCTDETAIL
			(
			  STFDID, SBDID, STFDSBNO, STFDSBDNO, STFDSBDATE, STFDSBDDATE, STFDNOP, STFDQTY, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, 
			  STFCORDNO
			)
			Select	@TSTFDID, A.SBDID, STFDSBNO, STFDSBDNO, STFDSBDATE, STFDSBDDATE, STFDNOP, STFDQTY, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, 
			  STFCORDNO
			From [SCFS].dbo.STUFFINGPRODUCTDETAIL A(NOLOCK) 
			  Where A.STFDID = @STFDID
			  Group by  A.SBDID, STFDSBNO, STFDSBDNO, STFDSBDATE, STFDSBDDATE, STFDNOP, STFDQTY, CUSRID, LMUSRID, DISPSTATUS, PRCSDATE, 
			  STFCORDNO

				update a
				SET GIDID = B.GIDID
				from [SCFS_ERP].dbo.STUFFINGDETAIL a, SCFS_ERP.DBO.GATEINDETAIL B(NOLOCK), VTGOIssueStuffing_261021_1015 c(nolock)
				WHERE A.GIDID = B.OLDGID
				and a.OLDSTFDID = c.STFDID
				and a.OLDSTFDID > 0
				and b.OLDGID > 0 
				and a.CUSRID = '99'
				and a.STFDID = @STFDID

				update b
				SET STFDID = a.STFDID
				from [SCFS_ERP].dbo.STUFFINGDETAIL a, SCFS_ERP.DBO.AUTHORIZATIONSLIPDETAIL B(NOLOCK), VTGOIssueStuffing_261021_1015 c(nolock)
				WHERE a.OLDSTFDID = B.STFDID
				and a.OLDSTFDID = c.STFDID
				and a.OLDSTFDID > 0 
				and b.OLDASLDID > 0
				and a.CUSRID = '99'
END


